// Title: C# batch encryption of ODS files with filename‑based SHA‑256 passwords using Aspose.Cells
// Description: Iterates through a directory of *.ods workbooks, creates a unique SHA‑256 hash from each file name, applies the hash as the workbook password via Aspose.Cells, and writes the protected files to an output folder.
// Keywords: Aspose.Cells ODS encryption C# | batch ODS password protection | SHA‑256 filename hash | C# encrypt ODS workbook | programmatic spreadsheet security
// Common Searches: how to encrypt multiple ODS files with Aspose.Cells | C# batch ODS password protection using filename hash | generate SHA‑256 password for each ODS workbook | automate ODS encryption in .NET | set workbook password before saving ODS Aspose
// Developer Intent: Secure every ODS workbook in a folder by assigning a password derived from its file name.
// Use Cases: Protect a batch of financial ODS reports before archiving. | Automatically lock ODS templates generated by an application without manual steps. | Create per‑user password‑protected ODS exports based on file naming conventions.
// AI Prompts: Write C# code that reads all ODS files in a folder and encrypts each with a SHA‑256 hash of its filename using Aspose.Cells. | Show how to replace the SHA‑256 hash with an MD5 hash for password generation while encrypting ODS workbooks in C#. | Explain how to test whether an ODS file is password‑protected and verify the password before opening it with Aspose.Cells.

using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Ods;

// Iterates through a directory of *.ods workbooks, creates a unique SHA‑256 hash from each file name, applies the hash as the workbook password via Aspose.Cells, and writes the protected files to an output folder.
class BatchEncryptOds
{
    static void Main()
    {
        // Folder containing source ODS files
        string inputFolder = @"C:\InputOds";

        // Folder where encrypted ODS files will be saved
        string outputFolder = @"C:\EncryptedOds";

        try
        {
            // Verify input folder exists
            if (!Directory.Exists(inputFolder))
            {
                Console.WriteLine($"Input folder not found: {inputFolder}");
                return;
            }

            // Ensure output folder exists
            Directory.CreateDirectory(outputFolder);

            // Process each ODS file in the input folder
            foreach (string sourcePath in Directory.GetFiles(inputFolder, "*.ods"))
            {
                try
                {
                    // Verify the source file still exists
                    if (!File.Exists(sourcePath))
                    {
                        Console.WriteLine($"File not found: {sourcePath}");
                        continue;
                    }

                    // Derive a unique password from the file name (without extension) using SHA‑256
                    string fileName = Path.GetFileNameWithoutExtension(sourcePath);
                    string password = GetSha256Hash(fileName);

                    // Load the workbook (using OdsLoadOptions as required by the lifecycle rule)
                    Workbook workbook = new Workbook(sourcePath, new OdsLoadOptions());

                    // Apply the derived password to encrypt the workbook
                    workbook.Settings.Password = password;

                    // Prepare ODS save options (default settings are sufficient)
                    OdsSaveOptions saveOptions = new OdsSaveOptions();

                    // Save the encrypted workbook to the output folder
                    string destPath = Path.Combine(outputFolder, Path.GetFileName(sourcePath));
                    workbook.Save(destPath, saveOptions);

                    Console.WriteLine($"Encrypted file saved: {destPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error processing file '{sourcePath}': {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unexpected error: {ex.Message}");
        }
    }

    // Helper method to compute SHA‑256 hash and return it as a hex string
    static string GetSha256Hash(string input)
    {
        using (SHA256 sha = SHA256.Create())
        {
            byte[] hashBytes = sha.ComputeHash(Encoding.UTF8.GetBytes(input));
            StringBuilder sb = new StringBuilder();
            foreach (byte b in hashBytes)
                sb.Append(b.ToString("x2"));
            return sb.ToString();
        }
    }
}
