// Title: Batch add identical signature line to Excel workbooks with Aspose.Cells for .NET
// Description: C# program that scans a folder for .xlsx files, loads each workbook with Aspose.Cells, inserts the same SignatureLine into the first worksheet, and saves the updated files to a target directory while keeping original names.
// Keywords: Aspose.Cells batch signature line | C# add signature to multiple Excel files | automate Excel signature insertion | process Excel workbooks programmatically | add digital signature line Aspose.Cells | .NET Excel protection automation | bulk edit Excel worksheets
// Common Searches: how to add the same signature line to all Excel files in a folder using Aspose.Cells | C# code for batch inserting a signature line into multiple .xlsx workbooks | Aspose.Cells example for adding a signature line to each workbook | automate signature line addition to Excel spreadsheets .NET | bulk add approval signature to Excel files programmatically
// Developer Intent: Insert a predefined SignatureLine into every workbook within a directory and save the modified copies to another folder.
// Use Cases: Automatically embed an approval signature in monthly financial reports before distribution. | Prepare a set of contract templates with a standard signer line for legal review. | Add a compliance stamp to all spreadsheets generated by nightly ETL jobs.
// AI Prompts: Write C# code using Aspose.Cells to batch‑add a SignatureLine to the first worksheet of every .xlsx file in a source folder and save to a destination folder. | Show how to customize signer name, title, email, and instructions for a bulk signature line insertion with Aspose.Cells. | Provide robust error handling for missing files, read‑only workbooks, or unsupported formats when adding signature lines in bulk.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// C# program that scans a folder for .xlsx files, loads each workbook with Aspose.Cells, inserts the same SignatureLine into the first worksheet, and saves the updated files to a target directory while keeping original names.
class Program
{
    static void Main()
    {
        // Input directory containing the Excel files
        string sourceDir = @"C:\InputExcelFiles";

        // Output directory where modified files will be saved
        string outputDir = @"C:\OutputExcelFiles";

        // Ensure the output directory exists
        Directory.CreateDirectory(outputDir);

        // Get all .xlsx files in the source directory (non‑recursive)
        string[] excelFiles = Directory.GetFiles(sourceDir, "*.xlsx");

        // Define the signature line that will be added to every workbook
        SignatureLine commonSignature = new SignatureLine
        {
            Signer = "John Doe",
            Title = "Approved By",
            Email = "john.doe@example.com",
            Instructions = "Please sign to confirm the content.",
            AllowComments = true,
            ShowSignedDate = true,
            IsLine = true // display as a line
        };

        // Process each workbook
        foreach (string filePath in excelFiles)
        {
            // Load the workbook (uses the Workbook(string) constructor)
            using (Workbook workbook = new Workbook(filePath))
            {
                // Access the first worksheet (you can modify this to target other sheets)
                Worksheet sheet = workbook.Worksheets[0];

                // Add the signature line at row 0, column 0 (top‑left corner)
                // AddSignatureLine returns a Picture object; we don't need to use it further
                sheet.Shapes.AddSignatureLine(0, 0, commonSignature);

                // Build the output file path (preserve original file name)
                string outputPath = Path.Combine(outputDir, Path.GetFileName(filePath));

                // Save the modified workbook (uses Workbook.Save(string))
                workbook.Save(outputPath);
            }
        }

        Console.WriteLine("Signature lines added to all workbooks.");
    }
}
