// Title: Determine the file size impact of password‑protecting an XLSX workbook with Aspose.Cells for .NET
// AI Prompts: Generate C# code that creates an Excel workbook using Aspose.Cells, saves it as an unprotected .xlsx, then applies a password via Workbook.Settings.Password, saves the protected file, and prints the byte sizes of both files. | Show how to calculate and display the size difference between a plain XLSX file and the same file encrypted with a password using Aspose.Cells in a .NET application.
// Common Searches: asp.net compare size of password protected xlsx generated by Aspose.Cells | does Workbook.Settings.Password increase XLSX file size in C# | how to get file size of encrypted Excel workbook with Aspose.Cells .NET | measure encryption overhead for Excel files created by Aspose.Cells | size difference between unencrypted and protected workbook using Aspose.Cells
// Tags: Aspose.Cells workbook password protection file size | C# measure encrypted XLSX size Aspose.Cells | Workbook.Settings.Password encryption overhead | compare plain vs protected Excel file size Aspose

using System;
using System.IO;
using Aspose.Cells;

// The program creates a workbook with sample data, saves it as an unprotected XLSX file, then sets Workbook.Settings.Password to apply password protection, saves the protected file, and outputs the byte sizes of both files along with the size increase caused by encryption.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        for (int row = 0; row < 100; row++)
        {
            sheet.Cells[row, 0].PutValue($"Sample data row {row}");
        }

        // Save the workbook without encryption
        string unencryptedPath = "unprotected.xlsx";
        workbook.Save(unencryptedPath, SaveFormat.Xlsx);
        long unencryptedSize = new FileInfo(unencryptedPath).Length;

        // Apply password protection (encryption) and save
        workbook.Settings.Password = "MySecretPassword";
        string encryptedPath = "protected.xlsx";
        workbook.Save(encryptedPath, SaveFormat.Xlsx);
        long encryptedSize = new FileInfo(encryptedPath).Length;

        // Output the file sizes for comparison
        Console.WriteLine($"Unencrypted file size: {unencryptedSize} bytes");
        Console.WriteLine($"Encrypted file size:   {encryptedSize} bytes");
        Console.WriteLine($"Size increase:         {encryptedSize - unencryptedSize} bytes");
    }
}
