// Title: Batch encrypt Excel and ODS workbooks in a folder with a shared password using Aspose.Cells for .NET (C#)
// Description: C# program that scans a directory for supported spreadsheet files (.xlsx, .xls, .xlsm, .xlsb, .ods), loads each workbook with Aspose.Cells, sets a common password via Workbook.Settings.Password, and saves the file, overwriting the original while handling missing files and errors.
// Keywords: Aspose.Cells batch encrypt | C# encrypt multiple Excel files | set workbook password .NET | protect ODS files programmatically | shared password for spreadsheets | Aspose.Cells Workbook.Settings.Password | Excel file encryption C# | bulk spreadsheet protection
// Common Searches: encrypt all Excel files in a folder Aspose.Cells C# | batch protect .xlsx and .ods workbooks with one password | set same password for multiple spreadsheets using Aspose.Cells | C# code to encrypt a directory of Excel files | how to apply shared password to many workbooks programmatically
// Developer Intent: Apply a single password to every supported workbook in a specified directory in one automated run.
// Use Cases: Secure a batch of financial reports before archiving on a shared drive. | Enforce organization‑wide protection for spreadsheets generated by nightly reporting jobs. | Automatically encrypt user‑uploaded Excel/ODS files in a web service to satisfy compliance policies.
// AI Prompts: Write C# code that encrypts all .xlsx, .xls, .xlsm, .xlsb, and .ods files in a given folder with a shared password using Aspose.Cells, preserving original filenames. | Modify the sample to output encrypted files to a separate folder instead of overwriting the source files. | Add detailed logging to the loop that records each filename, success or error, to a CSV file while continuing processing. | Create a version that accepts the source folder, destination folder, and password as command‑line arguments. | Generate unit tests for the encryption routine that verify password protection on a sample workbook.

using System;
using System.IO;
using Aspose.Cells;

namespace EncryptWorkbooksInDirectory
{
    // C# program that scans a directory for supported spreadsheet files (.xlsx, .xls, .xlsm, .xlsb, .ods), loads each workbook with Aspose.Cells, sets a common password via Workbook.Settings.Password, and saves the file, overwriting the original while handling missing files and errors.
    class Program
    {
        static void Main()
        {
            // Directory containing the workbooks to encrypt
            string sourceDirectory = @"C:\Path\To\Workbooks";

            // Verify that the source directory exists
            if (!Directory.Exists(sourceDirectory))
            {
                Console.WriteLine($"Source directory not found: {sourceDirectory}");
                return;
            }

            // Shared password for all workbooks
            const string sharedPassword = "MySharedPassword123";

            // Supported Excel file extensions
            string[] extensions = new[] { ".xlsx", ".xls", ".xlsm", ".xlsb", ".ods" };

            try
            {
                // Iterate over each file with a supported extension
                foreach (string filePath in Directory.EnumerateFiles(sourceDirectory, "*.*", SearchOption.TopDirectoryOnly))
                {
                    // Skip files that do not have a supported extension
                    if (Array.IndexOf(extensions, Path.GetExtension(filePath).ToLower()) < 0)
                        continue;

                    // Ensure the file still exists before loading
                    if (!File.Exists(filePath))
                    {
                        Console.WriteLine($"File not found (skipped): {filePath}");
                        continue;
                    }

                    try
                    {
                        // Load the workbook, set password, and save (overwrites original)
                        using (Workbook workbook = new Workbook(filePath))
                        {
                            workbook.Settings.Password = sharedPassword;
                            workbook.Save(filePath);
                        }

                        Console.WriteLine($"Encrypted: {Path.GetFileName(filePath)}");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error processing file '{filePath}': {ex.Message}");
                    }
                }

                Console.WriteLine("All applicable workbooks have been processed.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Unexpected error: {ex.Message}");
            }
        }
    }
}
