// Title: Parallel encryption of multiple Excel workbooks with SHA‑256‑derived passwords using Aspose.Cells for .NET (C#)
// Description: Creates a list of workbook file names, then uses Parallel.ForEach to instantiate a Workbook for each file, writes a sample cell, generates an 8‑byte hex password from the file name via SHA‑256, assigns it to Workbook.Settings.Password, applies strong encryption options, saves the file, and disposes the workbook—producing concurrently encrypted Excel files each protected by a unique password.
// Keywords: Aspose.Cells parallel encryption C# | SHA256 password generation Excel | Workbook.Settings.Password Aspose | set encryption options Aspose.Cells | batch encrypt Excel files .NET
// Common Searches: encrypt multiple Excel files simultaneously Aspose.Cells | generate unique password per workbook C# SHA256 | Parallel.ForEach workbook encryption example | strong encryption options for .xlsx using Aspose.Cells
// Developer Intent: Encrypt a collection of Excel workbooks concurrently, assigning each a distinct password derived from its file name.
// Use Cases: Batch‑create password‑protected financial statements for different clients, each with a unique key derived from the report name. | Secure temporary spreadsheets generated by a web service before delivery, ensuring every file has its own encryption password. | Automate archival of legacy Excel files with individual encryption keys to satisfy compliance and data‑protection requirements.
// AI Prompts: Write C# code that encrypts a list of Excel files in parallel with Aspose.Cells, using SHA‑256 of the file names to create passwords. | Show how to switch the sample to AES‑256 encryption and pull passwords from Azure Key Vault instead of hashing the file name. | Provide robust error handling and logging patterns for parallel workbook encryption with Aspose.Cells.

using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Aspose.Cells;

namespace AsposeCellsParallelEncryption
{
    // Creates a list of workbook file names, then uses Parallel.ForEach to instantiate a Workbook for each file, writes a sample cell, generates an 8‑byte hex password from the file name via SHA‑256, assigns it to Workbook.Settings.Password, applies strong encryption options, saves the file, and disposes the workbook—producing concurrently encrypted Excel files each protected by a unique password.
    class Program
    {
        static void Main()
        {
            // List of output file names (could be generated or read from elsewhere)
            List<string> outputFiles = new List<string>
            {
                "Workbook1.xlsx",
                "Workbook2.xlsx",
                "Workbook3.xlsx",
                "Workbook4.xlsx"
            };

            // Encrypt each workbook in parallel
            Parallel.ForEach(outputFiles, filePath =>
            {
                // Create a new workbook (lifecycle: create)
                Workbook wb = new Workbook();

                // Add some sample data to the first worksheet
                Worksheet sheet = wb.Worksheets[0];
                sheet.Cells["A1"].PutValue($"Encrypted file: {filePath}");

                // Derive a password from the file name using SHA256 hash
                string password = DerivePasswordFromString(filePath);

                // Apply the password to protect the workbook (encryption)
                wb.Settings.Password = password;

                // Optionally set stronger encryption options (ignored for modern formats but kept for completeness)
                wb.SetEncryptionOptions(EncryptionType.StrongCryptographicProvider, 128);

                // Save the encrypted workbook (lifecycle: save)
                wb.Save(filePath);

                // Dispose the workbook to release resources
                wb.Dispose();
            });

            Console.WriteLine("All workbooks have been encrypted and saved.");
        }

        // Helper method to create a password string from a hash of the input
        private static string DerivePasswordFromString(string input)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(input));
                // Convert first 8 bytes of the hash to a hex string for a reasonably short password
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < 8; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2"));
                }
                return sb.ToString();
            }
        }
    }
}
