// Title: Encrypt an XLSX workbook with a password using AES‑256 in Aspose.Cells for .NET (C#)
// Description: Creates a new Workbook, writes data to cell A1, sets an opening password, applies AES‑256 encryption via StrongCryptographicProvider, and saves the file as EncryptedWorkbook.xlsx using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | AES-256 encryption | C# Excel password protection | Workbook.SetEncryptionOptions | StrongCryptographicProvider | encrypt XLSX | Excel file security | Aspose.Cells .NET encryption
// Common Searches: Aspose.Cells encrypt Excel with password C# | How to use AES-256 encryption in Aspose.Cells .NET | Set workbook password and encryption type Aspose.Cells | C# code to protect XLSX with StrongCryptographicProvider | Encrypt workbook before saving with Aspose.Cells
// Developer Intent: Apply a user‑defined password and AES‑256 encryption to an Excel workbook using Aspose.Cells for .NET.
// Use Cases: Protect confidential financial statements before distribution. | Secure payroll or HR spreadsheets generated by automated processes. | Encrypt temporary data files before uploading to cloud storage. | Meet compliance requirements for archiving sensitive Excel reports.
// AI Prompts: Generate C# code that opens an existing workbook, sets a password, applies AES‑256 encryption with StrongCryptographicProvider, and saves it using Aspose.Cells. | Show how to change the encryption key length to 128 bits while keeping the password in Aspose.Cells for .NET. | Explain the steps to decrypt a workbook encrypted with StrongCryptographicProvider in Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsEncryptionDemo
{
    // Creates a new Workbook, writes data to cell A1, sets an opening password, applies AES‑256 encryption via StrongCryptographicProvider, and saves the file as EncryptedWorkbook.xlsx using Aspose.Cells for .NET.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Add some data to the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sensitive data");

            // Set the password that will be required to open the workbook
            workbook.Settings.Password = "MySecretPassword";

            // Apply AES‑256 encryption (key length 256 bits) using a strong cryptographic provider
            workbook.SetEncryptionOptions(EncryptionType.StrongCryptographicProvider, 256);

            // Save the encrypted workbook
            workbook.Save("EncryptedWorkbook.xlsx");
        }
    }
}
