// Title: Create a timestamped log of workbook encryption actions with Aspose.Cells in C#
// AI Prompts: Write a static C# logger that appends the current date‑time, workbook file name, and a description of the encryption action to a text file, then invoke it after saving an encrypted workbook with Aspose.Cells. | Update the workbook encryption method to set a password, save the file, and record the operation using the logger you created.
// Common Searches: how to add a timestamped audit log for Excel file encryption using Aspose.Cells C# | record workbook name and encryption action in a log file after saving with Aspose.Cells | C# log encryption activity of XLSX files generated by Aspose.Cells
// Tags: Aspose.Cells workbook encryption logging | C# timestamped Excel audit log | log encrypted workbook actions .NET | record workbook encryption activity Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsLoggingDemo
{
    // Simple logger that writes timestamp, file name and action to a log file.
    // Defines a static WorkbookLogger that appends a timestamp, file name, and encryption action to a log file, and a WorkbookEncryptor that loads a workbook, applies a password to encrypt it, saves it as XLSX, and records the encryption operation using the logger.
    public static class WorkbookLogger
    {
        private static readonly string LogFilePath = "WorkbookActions.log";

        // Appends a log entry.
        public static void Log(string fileName, string action)
        {
            string entry = $"{DateTime.Now:yyyy-MM-dd HH:mm:ss}\t{fileName}\t{action}";
            File.AppendAllLines(LogFilePath, new[] { entry });
        }
    }

    public class WorkbookEncryptor
    {
        // Encrypts a workbook with a password and logs the operation.
        public void EncryptWorkbook(string sourcePath, string destinationPath, string password)
        {
            // Load the workbook (using the provided load rule if any; otherwise standard load)
            Workbook workbook = new Workbook(sourcePath);

            // Set the password for the workbook.
            // This will encrypt the entire file when saved.
            workbook.Settings.Password = password;

            // Save the encrypted workbook (using the provided save rule if any; otherwise standard save)
            workbook.Save(destinationPath, SaveFormat.Xlsx);

            // Log the encryption action.
            WorkbookLogger.Log(Path.GetFileName(destinationPath), $"Encrypted with password");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // Example usage:
            // source.xlsx will be encrypted and saved as encrypted.xlsx with password "Secret123".
            string sourceFile = "source.xlsx";
            string encryptedFile = "encrypted.xlsx";
            string password = "Secret123";

            WorkbookEncryptor encryptor = new WorkbookEncryptor();
            encryptor.EncryptWorkbook(sourceFile, encryptedFile, password);

            Console.WriteLine("Encryption completed and logged.");
        }
    }
}
