// Title: Log Excel workbook encryption with timestamp and file name using Aspose.Cells C#
// Description: Demonstrates how to encrypt an Excel workbook with Aspose.Cells, then append a UTC timestamp, the workbook's file name, and a description of the encryption action to a plain‑text log file for audit purposes.
// Keywords: Aspose.Cells encryption logging | C# workbook password protection | timestamp log Excel encryption | record workbook encryption action | Aspose.Cells SetEncryptionOptions log | audit trail Excel files .NET
// Common Searches: Aspose.Cells log encryption actions C# | how to record timestamp when protecting Excel with Aspose | append encryption details to text file using Aspose.Cells | audit log for password‑protected workbooks .NET | save encryption activity log for Excel files
// Developer Intent: Create a reusable routine that logs each workbook encryption event—including UTC timestamp, file name, and action description—after applying password protection or encryption with Aspose.Cells.
// Use Cases: Maintain an audit trail of all password‑protected Excel reports generated by an application. | Track encryption activity across batch processing jobs for compliance reporting. | Integrate encryption logging into a Windows Service or scheduled task that creates secure workbooks.
// AI Prompts: Generate C# code that logs Aspose.Cells workbook encryption events to a CSV file with columns for timestamp, file path, and action. | Show how to include the encryption algorithm name in the log entry when using SetEncryptionOptions with Aspose.Cells. | Explain how to embed the logging routine into a .NET Core worker service that processes Excel files daily.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsEncryptionLogger
{
    // Demonstrates how to encrypt an Excel workbook with Aspose.Cells, then append a UTC timestamp, the workbook's file name, and a description of the encryption action to a plain‑text log file for audit purposes.
    class Program
    {
        // Path to the log file where encryption actions will be recorded
        private const string LogFilePath = "encryption_log.txt";

        static void Main()
        {
            // Example usage: encrypt two workbooks and log the actions
            EncryptWorkbook("Sample1.xlsx", "Password123");
            EncryptWorkbook("Sample2.xls", "Secret!@#");
        }

        /// <param name="outputFile">The file name (including path) to save the encrypted workbook.</param>
        /// <param name="password">The password to protect the workbook.</param>
        private static void EncryptWorkbook(string outputFile, string password)
        {
            // Create a new workbook (lifecycle rule: use the provided constructor)
            Workbook workbook = new Workbook();

            // Add some sample data
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Encrypted content");

            // Set the password for opening the workbook
            workbook.Settings.Password = password;

            // Optional: set encryption options for older Excel formats (ignored for .xlsx/.xlsm)
            // Here we use StrongCryptographicProvider with a 128-bit key as an example
            workbook.SetEncryptionOptions(EncryptionType.StrongCryptographicProvider, 128);

            // Save the workbook (lifecycle rule: use the provided Save method)
            workbook.Save(outputFile, SaveFormat.Xlsx);

            // Log the encryption action
            LogEncryptionAction(outputFile, "Password protection applied");
        }

        /// <summary>
        /// Appends a log entry with timestamp, file name, and action description to the log file.
        /// </summary>
        /// <param name="fileName">The name of the workbook file.</param>
        /// <param name="action">Description of the encryption action performed.</param>
        private static void LogEncryptionAction(string fileName, string action)
        {
            string timestamp = DateTime.Now.ToString("u"); // Universal sortable format
            string logEntry = $"{timestamp} | {fileName} | {action}{Environment.NewLine}";
            File.AppendAllText(LogFilePath, logEntry);
        }
    }
}
