// Title: C# – Mask “confidential” text in a named range with Aspose.Cells
// Description: Loads an Excel file, accesses a named range, scans each string cell, and replaces every occurrence of the word “confidential” with asterisks using a case‑insensitive, partial‑match replace option, then writes the result to a new workbook.
// Keywords: Aspose.Cells C# replace text | named range mask confidential | Excel redaction Aspose | case insensitive replace Aspose.Cells | partial string replace C#
// Common Searches: Aspose.Cells replace word in named range C# | how to redact confidential text in Excel using .NET | mask specific keyword in Excel cells with Aspose | partial match replace in Excel workbook C#
// Developer Intent: Redact the word “confidential” inside a predefined named range of an Excel workbook.
// Use Cases: Prepare a workbook for external distribution by removing sensitive labels. | Automate compliance checks that hide prohibited terms before archiving. | Integrate a preprocessing step that sanitizes data extracts generated by internal tools.
// AI Prompts: Write C# code that uses Aspose.Cells to replace a case‑insensitive substring within a named range and save the file. | Show how to extend the example to mask multiple keywords (e.g., "confidential", "secret") in the same range. | Provide robust error handling for missing files, undefined named ranges, and permission issues when masking text with Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsMaskConfidential
{
    // Loads an Excel file, accesses a named range, scans each string cell, and replaces every occurrence of the word “confidential” with asterisks using a case‑insensitive, partial‑match replace option, then writes the result to a new workbook.
    class Program
    {
        static void Main()
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.xlsx";
            const string rangeName = "MyRange";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file \"{inputPath}\" not found.");
                return;
            }

            try
            {
                // Load the workbook
                Workbook workbook = new Workbook(inputPath);

                // Assume the named range is on the first worksheet
                Worksheet worksheet = workbook.Worksheets[0];

                // Retrieve the named range by its name
                Name namedRange = workbook.Worksheets.Names[rangeName];
                if (namedRange == null)
                {
                    Console.WriteLine($"Named range \"{rangeName}\" not found.");
                    return;
                }

                // Get the address of the range (e.g., Sheet1!$A$1:$C$10) and remove leading '=' if present
                string rangeAddress = namedRange.RefersTo;
                if (rangeAddress.StartsWith("="))
                    rangeAddress = rangeAddress.Substring(1);

                // Create an Aspose.Cells.Range object from the address
                Aspose.Cells.Range asposeRange = worksheet.Cells.CreateRange(rangeAddress);

                // Prepare replace options for partial (contains) replacement, case‑insensitive
                ReplaceOptions replaceOptions = new ReplaceOptions
                {
                    MatchEntireCellContents = false, // replace only the matching part
                    CaseSensitive = false
                };

                // Iterate through each cell in the named range
                foreach (Cell cell in asposeRange)
                {
                    // Process only string cells
                    if (cell.Type == CellValueType.IsString)
                    {
                        // Replace the word "confidential" with a mask
                        cell.Replace("confidential", "********", replaceOptions);
                    }
                }

                // Save the modified workbook
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved to \"{outputPath}\".");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
