// Title: Validate Exported JSON Row Count Against Worksheet Rows with Aspose.Cells for .NET
// Description: Creates a workbook, adds a header and three data rows, determines the total rows using MaxDataRow, exports the used range to a JSON string via JsonUtility.ExportRangeToJson with JsonSaveOptions, parses the JSON array, and verifies that the number of data elements matches the worksheet rows (excluding the header).
// Keywords: Aspose.Cells | C# | Excel to JSON | JsonUtility ExportRangeToJson | JsonSaveOptions | row count validation | MaxDataRow | JSON array length | automated testing | data integrity
// Common Searches: Aspose.Cells verify JSON row count | C# compare Excel rows with exported JSON | JsonUtility ExportRangeToJson example | How to validate row count after JSON export in .NET | SkipEmptyRows effect on JSON export Aspose.Cells
// Developer Intent: Confirm that the JSON produced from a worksheet contains the same number of data rows as the original sheet.
// Use Cases: Parse the JSON string returned by JsonUtility.ExportRangeToJson and assert that its array length equals the worksheet's data rows (total rows minus header). | Adjust JsonSaveOptions (HasHeaderRow, SkipEmptyRows, ExportEmptyCells) to control exported content before performing row‑count verification. | Embed the validation routine in unit tests or CI pipelines to catch discrepancies between Excel data and JSON output.
// AI Prompts: Write C# code that reads a JSON file generated by Aspose.Cells and checks that its row count matches the source worksheet, handling the header row correctly. | Create an NUnit test that builds a workbook, exports it to JSON with Aspose.Cells, and asserts that the exported row count equals the worksheet's data rows. | Explain how changing JsonSaveOptions properties such as SkipEmptyRows or ExportEmptyCells influences the row‑count validation logic.

using System;
using System.IO;
using System.Text.Json;
using Aspose.Cells;
using Aspose.Cells.Utility;

namespace AsposeCellsJsonRowValidation
{
    // Creates a workbook, adds a header and three data rows, determines the total rows using MaxDataRow, exports the used range to a JSON string via JsonUtility.ExportRangeToJson with JsonSaveOptions, parses the JSON array, and verifies that the number of data elements matches the worksheet rows (excluding the header).
    class Program
    {
        static void Main()
        {
            try
            {
                // ---------- Create a workbook and populate it ----------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Header row
                cells["A1"].PutValue("Name");
                cells["B1"].PutValue("Age");
                cells["C1"].PutValue("City");

                // Data rows
                cells["A2"].PutValue("John");
                cells["B2"].PutValue(30);
                cells["C2"].PutValue("New York");

                cells["A3"].PutValue("Alice");
                cells["B3"].PutValue(25);
                cells["C3"].PutValue("London");

                cells["A4"].PutValue("Bob");
                cells["B4"].PutValue(40);
                cells["C4"].PutValue("Paris");

                // ---------- Determine original row count ----------
                // MaxDataRow returns zero‑based index of the last row that contains data.
                int originalRowCount = cells.MaxDataRow + 1; // includes header row

                // ---------- Export the worksheet to JSON ----------
                // Define the range that covers all used cells.
                int totalRows = originalRowCount;
                int totalColumns = cells.MaxDataColumn + 1;

                // Resolve ambiguity between Aspose.Cells.Range and System.Range
                Aspose.Cells.Range exportRange = cells.CreateRange(0, 0, totalRows, totalColumns);

                JsonSaveOptions jsonOptions = new JsonSaveOptions
                {
                    HasHeaderRow = true,      // First row is header
                    SkipEmptyRows = true,     // Skip any completely empty rows
                    ExportEmptyCells = true   // Keep empty cells for accurate column count
                };

                // Export to JSON string using the utility method.
                string jsonString = JsonUtility.ExportRangeToJson(exportRange, jsonOptions);

                // Optionally save the JSON to a file (demonstrates the save lifecycle).
                string jsonPath = "exported.json";
                File.WriteAllText(jsonPath, jsonString);

                // ---------- Validate row count in exported JSON ----------
                // Parse the JSON array; each element corresponds to a data row (header excluded).
                using JsonDocument doc = JsonDocument.Parse(jsonString);
                JsonElement root = doc.RootElement;

                int jsonDataRowCount = 0;
                if (root.ValueKind == JsonValueKind.Array)
                {
                    jsonDataRowCount = root.GetArrayLength();
                }

                // Expected data rows = original rows minus the header row.
                int expectedDataRows = originalRowCount - 1;

                // Output the comparison result.
                Console.WriteLine($"Original worksheet rows (including header): {originalRowCount}");
                Console.WriteLine($"Expected data rows (excluding header): {expectedDataRows}");
                Console.WriteLine($"Rows exported in JSON: {jsonDataRowCount}");

                if (jsonDataRowCount == expectedDataRows)
                {
                    Console.WriteLine("Validation succeeded: JSON row count matches the worksheet.");
                }
                else
                {
                    Console.WriteLine("Validation failed: JSON row count does not match the worksheet.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
