// Title: How to embed fonts and keep slicer formatting when exporting an Excel workbook to PDF with Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an .xlsx file, configures PdfSaveOptions to embed all fonts and retain slicer appearance, then saves the workbook as a PDF using Aspose.Cells. | Show how to enable the EmbedStandardFonts and SlicerFormatting properties of PdfSaveOptions before calling Workbook.Save for PDF output in Aspose.Cells .NET.
// Common Searches: Aspose.Cells .NET how to embed all fonts during PDF export | retain slicer visual style when converting Excel to PDF with Aspose.Cells | PdfSaveOptions properties for font embedding and slicer formatting in C# | C# code sample for preserving slicer formatting in PDF generated by Aspose.Cells | enable font embedding and slicer formatting in Aspose.Cells PDF conversion
// Tags: PdfSaveOptions font embedding | Aspose.Cells slicer style preservation | C# Excel to PDF conversion settings | PDF export with slicer formatting | Aspose.Cells PDF save options

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example loads an Excel workbook, optionally sets PdfSaveOptions to embed standard fonts and retain slicer formatting, and saves the workbook as a PDF, including file existence verification and exception handling.
class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            // Verify that the source workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputPath);

            // Set PDF conversion options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // The following options are available in newer versions of Aspose.Cells.
            // Uncomment them if your version supports these properties.

            // pdfOptions.EmbedStandardFonts = true;   // Embed all fonts in the PDF
            // pdfOptions.SlicerFormatting = true;    // Retain slicer formatting

            // Export the workbook to PDF using the configured options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
