// Title: Save an Aspose.Cells workbook to PDF and embed the slicer's visual style with PdfSaveOptions in C#
// AI Prompts: Write C# code that creates a workbook, configures PdfSaveOptions to keep slicer layout, and saves it as a PDF with Aspose.Cells. | Show how to enable document structure export in PdfSaveOptions so the slicer's visual style appears in the generated PDF. | Provide a concise example demonstrating the use of Aspose.Cells PdfSaveOptions to embed slicer styling when converting Excel to PDF.
// Common Searches: Aspose.Cells how to keep slicer look when converting Excel to PDF in .NET | C# PdfSaveOptions ExportDocumentStructure slicer visual style | Save workbook to PDF with slicer formatting using Aspose.Cells | embed slicer style in PDF export Aspose.Cells C# example | retain slicer visual formatting in PDF generated by Aspose.Cells
// Tags: Aspose.Cells PDF export with slicer styling | PdfSaveOptions slicer style retention | C# embed slicer visual style in PDF | Export slicer formatting using Aspose.Cells | Workbook to PDF preserving slicer appearance

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering; // Required for PdfSaveOptions

// Creates a workbook (or loads one containing a slicer), sets PdfSaveOptions.ExportDocumentStructure to true to embed the slicer's visual style, and saves the workbook as a PDF.
class Program
{
    static void Main()
    {
        // Create a new workbook (or load an existing one that contains a slicer)
        Workbook workbook = new Workbook(); // lifecycle: create

        // Configure PDF save options to embed the slicer's visual style
        PdfSaveOptions pdfOptions = new PdfSaveOptions(); // lifecycle: create
        pdfOptions.ExportDocumentStructure = true; // ensures slicer visual style is retained in the PDF

        // Save the workbook to PDF using the specified options
        workbook.Save("WorkbookWithSlicer.pdf", pdfOptions); // lifecycle: save
    }
}
