// Title: How to set a custom caption for an Excel slicer linked to a pivot table using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that creates a workbook, adds a pivot table, inserts a slicer for a field, and assigns a custom caption to the slicer with Aspose.Cells. | Demonstrate how to enable the slicer caption header and set a custom label in an Excel file generated by Aspose.Cells for .NET.
// Common Searches: aspnet set slicer caption text in Excel file using Aspose.Cells | c# Aspose.Cells slicer caption property example | how to display custom header for slicer linked to pivot table in Aspose.Cells | change slicer caption in generated workbook with Aspose.Cells for .NET | add slicer with custom caption to pivot table using Aspose.Cells C#
// Tags: Aspose.Cells set slicer caption C# | Excel slicer caption customization Aspose.Cells | pivot table slicer header modification .NET | Aspose.Cells slicer properties example | C# generate workbook with slicer caption

using System;
using Aspose.Cells;
using Aspose.Cells.Slicers;
using Aspose.Cells.Pivot;

namespace SlicerCaptionExample
{
    // The example creates a new workbook, fills it with sample data, builds a pivot table, adds a slicer linked to the 'Category' field, sets the slicer's caption to "Select Category" and makes the caption visible, then saves the file as SlicerWithCustomCaption.xlsx.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Populate sample data for a pivot table
                cells["A1"].PutValue("Category");
                cells["A2"].PutValue("Fruit");
                cells["A3"].PutValue("Vegetable");
                cells["A4"].PutValue("Fruit");
                cells["A5"].PutValue("Vegetable");

                cells["B1"].PutValue("Sales");
                cells["B2"].PutValue(120);
                cells["B3"].PutValue(80);
                cells["B4"].PutValue(150);
                cells["B5"].PutValue(90);

                // Add a pivot table based on the data range
                int pivotIdx = sheet.PivotTables.Add("A1:B5", "D1", "PivotTable1");
                PivotTable pivot = sheet.PivotTables[pivotIdx];
                pivot.AddFieldToArea(PivotFieldType.Row, "Category");
                pivot.AddFieldToArea(PivotFieldType.Data, "Sales");
                pivot.RefreshData();
                pivot.CalculateData();

                // Add a slicer linked to the pivot table for the "Category" field
                // Note: The correct parameter order is (pivot, destination cell, field name)
                int slicerIdx = sheet.Slicers.Add(pivot, "E1", "Category");
                Slicer slicer = sheet.Slicers[slicerIdx];

                // Set a custom caption for the slicer
                slicer.Caption = "Select Category";
                slicer.ShowCaption = true; // Ensure the caption header is visible

                // Save the workbook
                workbook.Save("SlicerWithCustomCaption.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
