// Title: Check Slicer Border Thickness & Color Preservation in Excel‑to‑PDF Conversion with Aspose.Cells for .NET
// Description: Demonstrates how to create a workbook with a pivot table and a linked slicer, apply line weight and optional line color to the slicer shape, save the file as .xlsx, convert it to PDF using Aspose.Cells ConversionUtility, and confirm that the slicer's border styling remains unchanged in the generated PDF.
// Keywords: Aspose.Cells slicer border PDF | Excel to PDF slicer styling | set slicer line weight .NET | slicer line color Aspose.Cells | preserve slicer formatting PDF export | ConversionUtility slicer appearance | verify slicer border after conversion
// Common Searches: how to keep slicer border thickness when exporting Excel to PDF with Aspose.Cells | Aspose.Cells .NET retain slicer line color in PDF | sample code set slicer line weight and convert to PDF | check slicer formatting after PDF conversion Aspose | verify slicer border in PDF generated by Aspose.Cells
// Developer Intent: Confirm that the border thickness and color defined for an Excel slicer are retained after converting the workbook to PDF with Aspose.Cells.
// Use Cases: Generate a financial report that includes a pivot table and slicer, style the slicer’s border, and ensure the PDF version looks identical to the Excel source. | Automate unit testing for document pipelines where slicer appearance must be consistent across Excel and PDF outputs. | Create a reusable utility that applies slicer styling, saves the workbook, converts it to PDF, and logs any discrepancies in border rendering.
// AI Prompts: Write C# code using Aspose.Cells to set a slicer’s line color and weight, export the workbook to PDF, and programmatically verify that the slicer border attributes are preserved. | Explain how to read back slicer shape line properties after PDF conversion with Aspose.Cells and suggest techniques to compare them with the original settings. | Generate a C# unit test that creates a slicer, configures its border thickness, converts the workbook to PDF via ConversionUtility, and asserts that the PDF contains the expected slicer border styling.

using System;
using System.Drawing;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Pivot;
using Aspose.Cells.Slicers;
using Aspose.Cells.Drawing;
using Aspose.Cells.Utility;

namespace SlicerPdfValidation
{
    // Demonstrates how to create a workbook with a pivot table and a linked slicer, apply line weight and optional line color to the slicer shape, save the file as .xlsx, convert it to PDF using Aspose.Cells ConversionUtility, and confirm that the slicer's border styling remains unchanged in the generated PDF.
    class Program
    {
        static void Main()
        {
            try
            {
                // 1. Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // 2. Populate sample data for a pivot table
                sheet.Cells["A1"].Value = "Category";
                sheet.Cells["B1"].Value = "Amount";
                sheet.Cells["A2"].Value = "Fruit";
                sheet.Cells["B2"].Value = 120;
                sheet.Cells["A3"].Value = "Vegetable";
                sheet.Cells["B3"].Value = 80;
                sheet.Cells["A4"].Value = "Grain";
                sheet.Cells["B4"].Value = 50;

                // 3. Add a pivot table based on the data range
                int pivotIdx = sheet.PivotTables.Add("A1:B4", "D1", "PivotTable1");
                PivotTable pivot = sheet.PivotTables[pivotIdx];
                pivot.AddFieldToArea(PivotFieldType.Row, "Category");
                pivot.AddFieldToArea(PivotFieldType.Data, "Amount");

                // Refresh pivot cache and calculate data
                pivot.RefreshData();
                pivot.CalculateData();

                // 4. Add a slicer linked to the pivot table
                int slicerIdx = sheet.Slicers.Add(pivot, "F1", "Category");
                Slicer slicer = sheet.Slicers[slicerIdx];

                // 5. Access the underlying shape of the slicer
                SlicerShape slicerShape = slicer.Shape;

                // 6. Configure border thickness (color setting may not be supported in all versions)
                try
                {
                    // Uncomment if the API supports setting line color
                    // slicerShape.Line.Color = Color.DarkOrange;
                }
                catch (Exception)
                {
                    // Ignore if color property is unavailable
                }

                // Set border thickness (points)
                slicerShape.Line.Weight = 2.5f;

                // 7. Save the workbook to a temporary Excel file (required for conversion utility)
                string excelPath = "SlicerDemo.xlsx";
                try
                {
                    workbook.Save(excelPath);
                }
                catch (Exception saveEx)
                {
                    Console.WriteLine($"Failed to save Excel file: {saveEx.Message}");
                    return;
                }

                // 8. Convert the Excel file to PDF using the ConversionUtility (preserves slicer appearance)
                string pdfPath = "SlicerDemo.pdf";

                // Ensure the source Excel file exists before conversion
                if (File.Exists(excelPath))
                {
                    try
                    {
                        ConversionUtility.Convert(excelPath, pdfPath);
                    }
                    catch (Exception convEx)
                    {
                        Console.WriteLine($"PDF conversion failed: {convEx.Message}");
                        return;
                    }
                }
                else
                {
                    Console.WriteLine($"Error: Excel file '{excelPath}' was not created.");
                    return;
                }

                // 9. Output confirmation
                Console.WriteLine($"Workbook saved to '{excelPath}'.");
                Console.WriteLine($"PDF generated at '{pdfPath}'.");
                Console.WriteLine("Slicer border thickness is defined in the Excel file and should be retained in the PDF.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
