// Title: C# – Aspose.Cells Conditional Formatting: Set Font Color to Theme Dark2 for Negative Values
// Description: Shows how to use Aspose.Cells for .NET to add a conditional formatting rule to range A1:A5 that changes the font color to the workbook’s Dark2 theme color when the cell value is less than zero, then saves the file as NegativeFontColorDemo.xlsx.
// Keywords: Aspose.Cells | C# conditional formatting | negative values font color | theme Dark2 | Excel automation .NET | FormatCondition | OperatorType.LessThan | Style.Font.ThemeColor | Aspose.Cells example | Excel conditional formatting
// Common Searches: Aspose.Cells set font color for negative numbers C# | conditional formatting dark2 theme color Aspose.Cells | how to apply theme color to cell font with Aspose.Cells | C# Excel conditional formatting less than zero | Aspose.Cells conditional formatting example
// Developer Intent: Create a conditional formatting rule that applies the Dark2 theme font color to cells containing negative numbers.
// Use Cases: Highlight losses in financial statements with a distinct theme color. | Emphasize negative inventory levels in automated reports. | Visually separate deficit values in a sales dashboard generated by code.
// AI Prompts: Generate C# code using Aspose.Cells that applies a conditional formatting rule to set the font color to the workbook's Dark2 theme color for values < 0. | Provide an Aspose.Cells example that demonstrates using Style.Font.ThemeColor instead of a fixed RGB value. | Explain how to modify the conditional formatting style to reference any theme color (e.g., Accent1, Dark2) in Aspose.Cells for .NET.

using System;
using System.Drawing;
using Aspose.Cells;

namespace AsposeCellsConditionalFormattingDemo
{
    // Shows how to use Aspose.Cells for .NET to add a conditional formatting rule to range A1:A5 that changes the font color to the workbook’s Dark2 theme color when the cell value is less than zero, then saves the file as NegativeFontColorDemo.xlsx.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Sample data (optional)
                sheet.Cells["A1"].PutValue(10);
                sheet.Cells["A2"].PutValue(-5);
                sheet.Cells["A3"].PutValue(15);
                sheet.Cells["A4"].PutValue(-20);
                sheet.Cells["A5"].PutValue(0);

                // Add a conditional formatting collection
                int cfIndex = sheet.ConditionalFormattings.Add();
                FormatConditionCollection conditions = sheet.ConditionalFormattings[cfIndex];

                // Define the range to which the rule applies (A1:A5)
                CellArea area = new CellArea
                {
                    StartRow = 0,
                    EndRow = 4,
                    StartColumn = 0,
                    EndColumn = 0
                };
                conditions.AddArea(area);

                // Add a condition: cell value less than 0 (negative)
                int conditionIndex = conditions.AddCondition(
                    FormatConditionType.CellValue,
                    OperatorType.LessThan,
                    "0",
                    null);

                FormatCondition condition = conditions[conditionIndex];

                // Create a style that uses a solid color for the font
                Style style = workbook.CreateStyle();
                // Use a red color for the font (replace with any desired color)
                style.Font.Color = Color.Red;

                // Assign the style to the condition
                condition.Style = style;

                // Save the workbook
                workbook.Save("NegativeFontColorDemo.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
