// Title: Create a three‑significant‑digit scientific notation format in Aspose.Cells for .NET (C#)
// Description: Demonstrates how to generate a workbook, insert a numeric value, define a custom style with the format string "0.00E+00" (three significant digits), apply the style to cell A1 (or any range) using a StyleFlag that targets only the number format, and save the file as ScientificNotation.xlsx.
// Keywords: Aspose.Cells | C# | .NET | custom number format | scientific notation | three significant digits | Excel format string | StyleFlag | apply style to range | Excel export
// Common Searches: Aspose.Cells scientific notation three digits | C# custom number format 0.00E+00 Aspose | How to apply number format to a range Aspose.Cells | Set scientific format in Excel using Aspose.Cells .NET | Apply custom format to cells Aspose.Cells C#
// Developer Intent: The developer wants to display numeric values in Excel as scientific notation with exactly three significant digits using Aspose.Cells in a .NET application.
// Use Cases: Compactly present large measurement results in reports generated by a .NET service. | Standardize scientific notation across all exported Excel files for a data‑analysis pipeline. | Apply the same three‑digit scientific format to multiple columns of measurement data to ensure visual consistency.
// AI Prompts: Generate C# code that creates a custom scientific notation format with three significant digits and applies it to a range of cells using Aspose.Cells. | Show how to change the format string to four significant digits in Aspose.Cells for .NET. | Explain the role of StyleFlag when applying only a number format to cells in Aspose.Cells.

using System;
using Aspose.Cells;

// Demonstrates how to generate a workbook, insert a numeric value, define a custom style with the format string "0.00E+00" (three significant digits), apply the style to cell A1 (or any range) using a StyleFlag that targets only the number format, and save the file as ScientificNotation.xlsx.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Put a numeric value that will be displayed in scientific notation
        sheet.Cells["A1"].PutValue(12345.6789);

        // Create a style with a custom scientific format (three significant digits)
        Style sciStyle = workbook.CreateStyle();
        sciStyle.Custom = "0.00E+00"; // one digit before decimal, two after = three sig. digits

        // Configure the StyleFlag to apply only the number format
        StyleFlag flag = new StyleFlag();
        flag.NumberFormat = true;

        // Apply the style to the target cell using a range
        Aspose.Cells.Range range = sheet.Cells.CreateRange("A1");
        range.ApplyStyle(sciStyle, flag);

        // Save the workbook
        workbook.Save("ScientificNotation.xlsx");
    }
}
