// Title: C# Utility to Merge Excel Theme Palettes, Preserving Primary Colors (Aspose.Cells)
// Description: Loads a primary and a secondary workbook, copies the secondary workbook's theme into the primary workbook, then restores the primary workbook's original 12 theme colors (Background1, Text1, Background2, Text2, Accent1‑6, Hyperlink, FollowedHyperlink) so they take precedence, and saves the result as an XLSX file. Includes file‑existence checks and automatic output‑folder creation.
// Keywords: Aspose.Cells C# merge theme | Excel theme palette merge | preserve primary theme colors | CopyTheme Aspose.Cells | SetThemeColor | Workbook theme utility | C# Excel theme example | Aspose.Cells theme colors | merge workbook themes .NET
// Common Searches: merge Excel theme palettes Aspose.Cells C# | preserve primary workbook theme colors when copying theme | copy theme from one workbook to another Aspose.Cells | set specific theme colors after copying theme | C# code to combine Excel themes without losing colors
// Developer Intent: Combine the theme palettes of two Excel workbooks while keeping the primary workbook's original theme colors intact.
// Use Cases: Apply a corporate template's theme to an existing report without overwriting its custom accent colors. | Standardize visual styling across multiple workbooks generated by different processes while retaining each file's unique branding hues. | Create a merged workbook that inherits additional theme colors from a secondary source but preserves the primary workbook's branding palette.
// AI Prompts: Generate C# code using Aspose.Cells that merges two workbook theme palettes and ensures the primary workbook's colors remain unchanged. | Show how to copy a theme from a secondary workbook and then reapply the original theme colors of the primary workbook with Aspose.Cells. | Explain error handling for missing files and automatic creation of the output directory when merging workbook themes in C#.

using System;
using System.Drawing;
using System.IO;
using Aspose.Cells;

namespace MergeThemeApp
{
    // Loads a primary and a secondary workbook, copies the secondary workbook's theme into the primary workbook, then restores the primary workbook's original 12 theme colors (Background1, Text1, Background2, Text2, Accent1‑6, Hyperlink, FollowedHyperlink) so they take precedence, and saves the result as an XLSX file. Includes file‑existence checks and automatic output‑folder creation.
    public static class MergeThemeUtility
    {
        // Merges the theme palettes of two workbooks.
        // Colors from the primary workbook take precedence.
        public static void MergeThemes(string primaryPath, string secondaryPath, string outputPath)
        {
            // Validate input files
            if (!File.Exists(primaryPath))
                throw new FileNotFoundException($"Primary workbook not found: {primaryPath}");
            if (!File.Exists(secondaryPath))
                throw new FileNotFoundException($"Secondary workbook not found: {secondaryPath}");

            // Load the primary workbook (the one that will receive the merged theme)
            Workbook primaryWorkbook = new Workbook(primaryPath);

            // Load the secondary workbook (the source of additional theme colors)
            Workbook secondaryWorkbook = new Workbook(secondaryPath);

            // Preserve the original theme colors of the primary workbook
            Color[] primaryColors = new Color[12];
            primaryColors[0] = primaryWorkbook.GetThemeColor(ThemeColorType.Background1);
            primaryColors[1] = primaryWorkbook.GetThemeColor(ThemeColorType.Text1);
            primaryColors[2] = primaryWorkbook.GetThemeColor(ThemeColorType.Background2);
            primaryColors[3] = primaryWorkbook.GetThemeColor(ThemeColorType.Text2);
            primaryColors[4] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent1);
            primaryColors[5] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent2);
            primaryColors[6] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent3);
            primaryColors[7] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent4);
            primaryColors[8] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent5);
            primaryColors[9] = primaryWorkbook.GetThemeColor(ThemeColorType.Accent6);
            primaryColors[10] = primaryWorkbook.GetThemeColor(ThemeColorType.Hyperlink);
            primaryColors[11] = primaryWorkbook.GetThemeColor(ThemeColorType.FollowedHyperlink);

            // Copy the theme from the secondary workbook into the primary workbook
            primaryWorkbook.CopyTheme(secondaryWorkbook);

            // Reapply the primary's original theme colors to give them precedence
            primaryWorkbook.SetThemeColor(ThemeColorType.Background1, primaryColors[0]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Text1, primaryColors[1]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Background2, primaryColors[2]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Text2, primaryColors[3]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent1, primaryColors[4]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent2, primaryColors[5]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent3, primaryColors[6]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent4, primaryColors[7]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent5, primaryColors[8]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Accent6, primaryColors[9]);
            primaryWorkbook.SetThemeColor(ThemeColorType.Hyperlink, primaryColors[10]);
            primaryWorkbook.SetThemeColor(ThemeColorType.FollowedHyperlink, primaryColors[11]);

            // Ensure output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            // Save the merged workbook
            primaryWorkbook.Save(outputPath, SaveFormat.Xlsx);
        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            // Example file paths – adjust as needed
            string primaryPath = "Primary.xlsx";
            string secondaryPath = "Secondary.xlsx";
            string outputPath = "MergedOutput.xlsx";

            try
            {
                MergeThemeUtility.MergeThemes(primaryPath, secondaryPath, outputPath);
                Console.WriteLine($"Merged workbook saved to: {outputPath}");
            }
            catch (FileNotFoundException ex)
            {
                Console.Error.WriteLine($"File error: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
        }
    }
}
