// Title: Save an Aspose.Cells workbook as XLSX, modify theme1.xml accent colors, and verify the changes in C#
// AI Prompts: Generate C# code that creates a workbook with Aspose.Cells, saves it to XLSX, opens the file with ZipArchive, updates the <a:accent1> and <a:accent2> elements in xl/theme/theme1.xml to specified ARGB values, and writes the modified XML back. | Show how to read back the theme XML from the saved XLSX and compare the rgb attributes of accent1 and accent2 with the expected hex strings to confirm the update. | Provide a reusable method that accepts a Workbook, two System.Drawing.Color values, and returns a boolean indicating whether the theme colors were successfully applied and verified.
// Common Searches: how to change theme accent colors in an Excel file generated by Aspose.Cells using C# | verify modified theme XML values after saving workbook with Aspose.Cells .NET | edit xl/theme/theme1.xml programmatically with ZipArchive and XDocument | Aspose.Cells custom theme color example for .NET developers | C# code to update Excel theme accent1 accent2 colors in a saved XLSX
// Tags: Aspose.Cells modify theme XML in XLSX | update accent1 accent2 colors using ZipArchive | validate theme rgb attributes with XDocument | C# change Excel theme colors programmatically | save workbook as XLSX and edit theme1.xml

using System;
using System.Drawing;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Xml.Linq;
using Aspose.Cells;

// The sample creates a new Workbook with Aspose.Cells, saves it as an XLSX file, converts custom System.Drawing.Color values to ARGB hex strings, opens the package with ZipArchive, updates the <a:accent1> and <a:accent2> elements in xl/theme/theme1.xml, rewrites the XML, and then reads the theme file again to verify that the rgb attributes match the new colors.
class ThemeVerification
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Define new colors for the theme (example: change Accent1 and Accent2)
            Color newAccent1 = Color.FromArgb(255, 0, 120, 215); // a shade of blue
            Color newAccent2 = Color.FromArgb(255, 232, 17, 35); // a shade of red

            // Save the workbook to XLSX
            string outputPath = "ModifiedThemeWorkbook.xlsx";
            workbook.Save(outputPath, SaveFormat.Xlsx);

            // Ensure the file was created
            if (!File.Exists(outputPath))
            {
                Console.WriteLine("Saved workbook not found.");
                return;
            }

            // Helper to convert System.Drawing.Color to ARGB hex string used in theme XML (e.g., "FF0078D7")
            string ColorToHex(Color c) => $"{c.A:X2}{c.R:X2}{c.G:X2}{c.B:X2}";
            string hexAccent1 = ColorToHex(newAccent1);
            string hexAccent2 = ColorToHex(newAccent2);

            // Open the XLSX package and modify the theme XML
            using (FileStream fs = new FileStream(outputPath, FileMode.Open, FileAccess.ReadWrite))
            using (ZipArchive zip = new ZipArchive(fs, ZipArchiveMode.Update))
            {
                ZipArchiveEntry themeEntry = zip.GetEntry("xl/theme/theme1.xml");
                if (themeEntry == null)
                {
                    Console.WriteLine("Theme XML not found in the workbook.");
                    return;
                }

                // Load the theme XML
                XDocument themeDoc;
                using (Stream themeStream = themeEntry.Open())
                {
                    themeDoc = XDocument.Load(themeStream);
                }

                XNamespace a = "http://schemas.openxmlformats.org/drawingml/2006/main";

                // Update <a:accent1> and <a:accent2> elements with new colors
                var accent1Element = themeDoc.Descendants(a + "accent1").FirstOrDefault();
                var accent2Element = themeDoc.Descendants(a + "accent2").FirstOrDefault();

                if (accent1Element != null)
                    accent1Element.SetAttributeValue("rgb", hexAccent1);
                if (accent2Element != null)
                    accent2Element.SetAttributeValue("rgb", hexAccent2);

                // Write the modified XML back into the package
                using (Stream writeStream = themeEntry.Open())
                {
                    writeStream.SetLength(0); // truncate existing content
                    themeDoc.Save(writeStream);
                }
            }

            // Verify that the theme XML now reflects the new colors
            using (FileStream fs = new FileStream(outputPath, FileMode.Open, FileAccess.Read))
            using (ZipArchive zip = new ZipArchive(fs, ZipArchiveMode.Read))
            {
                ZipArchiveEntry themeEntry = zip.GetEntry("xl/theme/theme1.xml");
                if (themeEntry == null)
                {
                    Console.WriteLine("Theme XML not found during verification.");
                    return;
                }

                XDocument themeDoc;
                using (Stream themeStream = themeEntry.Open())
                {
                    themeDoc = XDocument.Load(themeStream);
                }

                XNamespace a = "http://schemas.openxmlformats.org/drawingml/2006/main";

                var accent1Element = themeDoc.Descendants(a + "accent1").FirstOrDefault();
                var accent2Element = themeDoc.Descendants(a + "accent2").FirstOrDefault();

                bool accent1Matches = accent1Element != null &&
                                      string.Equals(accent1Element.Attribute("rgb")?.Value,
                                                    hexAccent1,
                                                    StringComparison.OrdinalIgnoreCase);

                bool accent2Matches = accent2Element != null &&
                                      string.Equals(accent2Element.Attribute("rgb")?.Value,
                                                    hexAccent2,
                                                    StringComparison.OrdinalIgnoreCase);

                Console.WriteLine($"Accent1 verification: {(accent1Matches ? "PASS" : "FAIL")}");
                Console.WriteLine($"Accent2 verification: {(accent2Matches ? "PASS" : "FAIL")}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
