// Title: Set Header Row Font to Theme Accent1 Across All Worksheets with Aspose.Cells for .NET
// Description: Shows how to iterate every worksheet in a workbook, find the last used column, and apply the workbook’s Theme Accent 1 font color to the first‑row header cells using Aspose.Cells in C#.
// Keywords: Aspose.Cells C# header font color | theme Accent1 Excel | apply theme color to row | iterate worksheets Aspose.Cells | style header row .NET | Excel theme color programmatically | Workbook styling Aspose | C# set font theme color
// Common Searches: Aspose.Cells set header row theme color | C# apply Accent1 font to first row in all sheets | how to change header font color using Aspose.Cells | loop through worksheets and style header cells | apply workbook theme to header rows programmatically
// Developer Intent: Apply the workbook’s Theme Accent 1 font color to the header (first) row of every worksheet in an Excel file using Aspose.Cells for .NET.
// Use Cases: Enforce corporate theme colors on report headers before distribution | Standardize header appearance when consolidating multiple workbooks | Automate branding for Excel exports generated by a .NET application
// AI Prompts: Generate C# code with Aspose.Cells that sets the header row font to Theme Accent2 for all worksheets. | Provide an example that applies a custom tint to the Accent1 theme color for header cells. | Explain how to retrieve a workbook’s theme and use its Accent1 color on a specific cell range.

using System;
using Aspose.Cells;

// Shows how to iterate every worksheet in a workbook, find the last used column, and apply the workbook’s Theme Accent 1 font color to the first‑row header cells using Aspose.Cells in C#.
class Program
{
    static void Main()
    {
        // Create a new workbook (or load an existing one)
        Workbook workbook = new Workbook();

        // OPTIONAL: add sample data so the header row has cells
        foreach (Worksheet ws in workbook.Worksheets)
        {
            ws.Cells["A1"].PutValue("Header1");
            ws.Cells["B1"].PutValue("Header2");
            ws.Cells["A2"].PutValue("Data1");
            ws.Cells["B2"].PutValue("Data2");
        }

        // Iterate over all worksheets
        foreach (Worksheet worksheet in workbook.Worksheets)
        {
            // Find the last used column in the sheet (covers the header row)
            int lastCol = worksheet.Cells.MaxDataColumn;

            // Apply the theme's Accent1 font color to each cell in the first row (header)
            for (int col = 0; col <= lastCol; col++)
            {
                Cell cell = worksheet.Cells[0, col];
                Style style = cell.GetStyle();

                // Use the theme color Accent1 (no tint)
                style.Font.ThemeColor = new ThemeColor(ThemeColorType.Accent1, 0);

                cell.SetStyle(style);
            }
        }

        // Save the workbook
        workbook.Save("HeaderThemeAccent1.xlsx");
    }
}
