// Title: C# – Apply Built‑In Chart Style Style1 to All Charts in an Excel Workbook with Aspose.Cells
// Description: Loads an existing workbook, iterates through every worksheet and chart, sets each chart's Style property to the built‑in Style1 (value 1), and saves the updated file. Demonstrates bulk chart styling using Aspose.Cells for .NET.
// Keywords: Aspose.Cells chart style | C# apply chart style | Style1 Excel chart | bulk chart formatting Aspose | set chart.Style property | iterate worksheets charts
// Common Searches: how to set chart style for all charts in Aspose.Cells | apply built‑in Style1 to Excel charts C# | loop through worksheets and charts Aspose.Cells | change chart appearance programmatically .NET
// Developer Intent: Automatically assign the predefined Style1 chart style to every chart in a workbook using Aspose.Cells for .NET.
// Use Cases: Standardize chart appearance across financial reports before distribution. | Batch‑process legacy workbooks to enforce a corporate chart theme. | Ensure consistent visual branding for dashboards generated by automated pipelines.
// AI Prompts: Write C# code with Aspose.Cells to apply Style2 to all charts in a workbook. | Show how to choose different built‑in chart styles based on chart type while iterating through worksheets. | Explain how to list available chart style IDs and preview their effects using Aspose.Cells for .NET.

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Loads an existing workbook, iterates through every worksheet and chart, sets each chart's Style property to the built‑in Style1 (value 1), and saves the updated file. Demonstrates bulk chart styling using Aspose.Cells for .NET.
class ApplyChartStyle
{
    static void Main()
    {
        // Load an existing workbook (create/load rule)
        Workbook workbook = new Workbook("input.xlsx");

        // Loop through all worksheets in the workbook
        foreach (Worksheet sheet in workbook.Worksheets)
        {
            // Loop through all charts in the current worksheet
            foreach (Chart chart in sheet.Charts)
            {
                // Apply the predefined built‑in style 'Style1' (value 1) to the chart
                chart.Style = 1; // Chart.Style property (1‑48)
            }
        }

        // Save the modified workbook (save rule)
        workbook.Save("output.xlsx");
    }
}
