// Title: Create a Candlestick Stock Chart with 20% Candle Width in C# using Aspose.Cells
// Description: Demonstrates how to build an Excel workbook, fill it with OHLC data, add a StockOpenHighLowClose (candlestick) chart, set the candle width to 20 % of the bar spacing via the GapWidth property, and save the file with Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# | .NET | candlestick chart | stock chart | OHLC data | ChartType.StockOpenHighLowClose | GapWidth | candle width | financial chart | Excel export
// Common Searches: Aspose.Cells candlestick chart C# | Set candle width GapWidth Aspose.Cells | Change stock chart to candlestick Aspose.Cells | Adjust candle width percentage in Excel chart using C# | Create OHLC chart with Aspose.Cells
// Developer Intent: Generate a candlestick (Open‑High‑Low‑Close) chart from OHLC data and configure its candle width to 20 % of the bar spacing using Aspose.Cells for .NET.
// Use Cases: Produce financial reports that visualize daily price movements as candlestick charts. | Fine‑tune chart density by setting a specific candle width for clearer data interpretation. | Automate the creation of Excel workbooks with pre‑formatted candlestick charts for distribution to analysts. | Integrate candlestick visualizations into .NET applications that require dynamic Excel export.
// AI Prompts: Show C# code that creates a StockOpenHighLowClose chart, converts it to a candlestick type, and sets the candle width to 20 % with Aspose.Cells. | Explain the effect of the GapWidth property on candle width in a candlestick chart generated by Aspose.Cells. | Provide a step‑by‑step guide to add OHLC data to a worksheet and automatically generate a candlestick chart with a 20 % candle width.

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Demonstrates how to build an Excel workbook, fill it with OHLC data, add a StockOpenHighLowClose (candlestick) chart, set the candle width to 20 % of the bar spacing via the GapWidth property, and save the file with Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data for a stock chart (Date, Open, High, Low, Close)
        sheet.Cells["A1"].PutValue("Date");
        sheet.Cells["B1"].PutValue("Open");
        sheet.Cells["C1"].PutValue("High");
        sheet.Cells["D1"].PutValue("Low");
        sheet.Cells["E1"].PutValue("Close");

        sheet.Cells["A2"].PutValue("2023-01-01");
        sheet.Cells["B2"].PutValue(100);
        sheet.Cells["C2"].PutValue(110);
        sheet.Cells["D2"].PutValue(95);
        sheet.Cells["E2"].PutValue(105);

        sheet.Cells["A3"].PutValue("2023-01-02");
        sheet.Cells["B3"].PutValue(105);
        sheet.Cells["C3"].PutValue(115);
        sheet.Cells["D3"].PutValue(100);
        sheet.Cells["E3"].PutValue(110);

        sheet.Cells["A4"].PutValue("2023-01-03");
        sheet.Cells["B4"].PutValue(110);
        sheet.Cells["C4"].PutValue(120);
        sheet.Cells["D4"].PutValue(108);
        sheet.Cells["E4"].PutValue(115);

        // Add a stock chart (candlestick) to the worksheet
        int chartIndex = sheet.Charts.Add(ChartType.StockOpenHighLowClose, 5, 0, 20, 15);
        Chart chart = sheet.Charts[chartIndex];

        // Set the data range: OHLC values and dates as categories
        chart.NSeries.Add("B2:E4", true);          // Open, High, Low, Close series
        chart.NSeries.CategoryData = "A2:A4";      // Dates as category axis

        // Ensure the chart type is candlestick (Open‑High‑Low‑Close)
        chart.Type = ChartType.StockOpenHighLowClose;

        // Adjust candle width: set GapWidth to 20% of the bar width
        chart.GapWidth = 20;

        // Save the workbook with the modified chart
        workbook.Save("CandlestickChart.xlsx");
    }
}
