// Title: Compare English and Chinese Chart Localization with Aspose.Cells for .NET
// Description: Shows how to create two identical column charts—one with the default English globalization and another using a custom ChineseChartGlobalizationSettings—render each chart to PNG via SheetRender, and programmatically compare the images to detect language‑specific differences.
// Keywords: Aspose.Cells | C# | chart localization | Chinese globalization | ChartGlobalizationSettings | render chart to PNG | image comparison | multilingual Excel | visual regression testing | .NET chart export
// Common Searches: Aspose.Cells Chinese chart title example | C# compare two chart images generated by Aspose.Cells | apply globalization settings to Excel chart .NET | render chart in different language Aspose.Cells | visual regression of Excel charts C#
// Developer Intent: Generate English and Chinese versions of a chart, render each to an image, and automatically verify whether the localized charts differ.
// Use Cases: Produce localized chart graphics for multilingual Excel reports | Validate that custom titles and axis labels appear correctly in each language | Automate visual regression testing of chart localization | Create language‑specific assets for documentation or marketing | Ensure compliance with regional language standards in generated reports
// AI Prompts: Write a C# method that compares two PNG files pixel by pixel without using System.Drawing. | Generate a subclass of ChartGlobalizationSettings for Japanese localization and apply it to a chart. | Provide code to export a localized chart to SVG format after setting custom globalization settings. | Create a unit test that asserts the chart title is correctly translated for a given language. | Show how to batch render the same chart in multiple languages using Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// Shows how to create two identical column charts—one with the default English globalization and another using a custom ChineseChartGlobalizationSettings—render each chart to PNG via SheetRender, and programmatically compare the images to detect language‑specific differences.
class ChartLocalizationComparison
{
    static void Main()
    {
        try
        {
            // ---------- English workbook (default globalization) ----------
            Workbook wbEn = new Workbook();
            Worksheet wsEn = wbEn.Worksheets[0];
            PopulateData(wsEn);

            int chartIdxEn = wsEn.Charts.Add(ChartType.Column, 5, 0, 15, 5);
            Chart chartEn = wsEn.Charts[chartIdxEn];
            chartEn.NSeries.Add("B2:B4", true);
            chartEn.NSeries.CategoryData = "A2:A4";

            // Use default (English) chart title
            chartEn.Title.Text = new ChartGlobalizationSettings().GetChartTitleName();

            // Render English chart to image
            ImageOrPrintOptions optsEn = new ImageOrPrintOptions
            {
                // Default image format is PNG; no need to set explicitly
                DefaultEditLanguage = DefaultEditLanguage.English
            };
            SheetRender srEn = new SheetRender(wsEn, optsEn);
            srEn.ToImage(0, "chart_en.png");

            // Save English workbook (optional)
            wbEn.Save("EnglishWorkbook.xlsx");

            // ---------- Chinese workbook with custom globalization ----------
            Workbook wbZh = new Workbook();
            Worksheet wsZh = wbZh.Worksheets[0];
            PopulateData(wsZh);

            int chartIdxZh = wsZh.Charts.Add(ChartType.Column, 5, 0, 15, 5);
            Chart chartZh = wsZh.Charts[chartIdxZh];
            chartZh.NSeries.Add("B2:B4", true);
            chartZh.NSeries.CategoryData = "A2:A4";

            // Apply custom Chinese globalization settings
            wbZh.Settings.GlobalizationSettings = new GlobalizationSettings
            {
                ChartSettings = new ChineseChartGlobalizationSettings()
            };
            // Use Chinese chart title from custom settings
            chartZh.Title.Text = wbZh.Settings.GlobalizationSettings.ChartSettings.GetChartTitleName();

            // Render Chinese chart to image
            ImageOrPrintOptions optsZh = new ImageOrPrintOptions
            {
                // Default image format is PNG; no need to set explicitly
                DefaultEditLanguage = DefaultEditLanguage.CJK
            };
            SheetRender srZh = new SheetRender(wsZh, optsZh);
            srZh.ToImage(0, "chart_zh.png");

            // Save Chinese workbook (optional)
            wbZh.Save("ChineseWorkbook.xlsx");

            // ---------- Compare the two rendered images ----------
            bool areDifferent = CompareImages("chart_en.png", "chart_zh.png");
            Console.WriteLine("Charts differ: " + areDifferent);
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }

    // Helper to fill sample data for both workbooks
    static void PopulateData(Worksheet ws)
    {
        ws.Cells["A1"].PutValue("Category");
        ws.Cells["A2"].PutValue("Q1");
        ws.Cells["A3"].PutValue("Q2");
        ws.Cells["A4"].PutValue("Q3");
        ws.Cells["B1"].PutValue("Series");
        ws.Cells["B2"].PutValue(100);
        ws.Cells["B3"].PutValue(200);
        ws.Cells["B4"].PutValue(300);
    }

    // Custom Chinese globalization settings overriding default strings
    class ChineseChartGlobalizationSettings : ChartGlobalizationSettings
    {
        public override string GetChartTitleName() => "图表标题";
        public override string GetAxisTitleName() => "轴标题";
        public override string GetOtherName() => "其他";
        public override string GetLegendIncreaseName() => "增加";
        public override string GetLegendDecreaseName() => "减少";
        public override string GetLegendTotalName() => "总计";
        public override string GetSeriesName() => "系列";
        public override string GetAxisUnitName(DisplayUnitType type)
        {
            return type switch
            {
                DisplayUnitType.Hundreds => "百",
                DisplayUnitType.Thousands => "千",
                DisplayUnitType.TenThousands => "万",
                _ => base.GetAxisUnitName(type),
            };
        }
    }

    // Simple byte‑by‑byte image comparison to avoid System.Drawing dependencies
    static bool CompareImages(string path1, string path2)
    {
        try
        {
            if (!File.Exists(path1) || !File.Exists(path2))
                return true; // Missing file implies difference

            byte[] bytes1 = File.ReadAllBytes(path1);
            byte[] bytes2 = File.ReadAllBytes(path2);

            if (bytes1.Length != bytes2.Length)
                return true; // Different sizes imply difference

            for (int i = 0; i < bytes1.Length; i++)
            {
                if (bytes1[i] != bytes2[i])
                    return true; // Found a differing byte
            }
            return false; // Images are identical
        }
        catch
        {
            // In case of any I/O error, treat as different
            return true;
        }
    }
}
