// Title: Disable the data label background fill in a doughnut chart with Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that creates a doughnut chart and turns off the data label background using Aspose.Cells. | Demonstrate setting the ShowBackground flag of chart series data labels to false in Aspose.Cells. | Provide a complete example that disables label fill while keeping data labels visible in an Excel doughnut chart.
// Common Searches: Aspose.Cells C# remove background color from doughnut chart data labels | how to hide data label fill in Excel doughnut chart using Aspose.Cells API | set ShowBackground false for series data labels in Aspose.Cells .NET | disable label background in doughnut chart generated by Aspose.Cells | C# Aspose.Cells chart formatting hide data label background
// Tags: data label background suppression Aspose.Cells | doughnut chart series label formatting C# | chart series label background toggle Aspose.Cells | Excel chart label fill removal .NET | chart data label visibility control Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Charts;
using System;
using System.IO;

// The example creates a workbook, adds sample data, inserts a doughnut chart, and shows how to disable the data label background fill by setting the series data label's ShowBackground property to false before saving the file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Get the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the doughnut chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B4"].PutValue(50);

            // Add a doughnut chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Doughnut, 5, 0, 20, 7);
            Chart chart = sheet.Charts[chartIndex];

            // Add series including both category and value ranges
            chart.NSeries.Add("A2:B4", true);

            // Optional: enable data labels (if the API version supports it)
            // Uncomment the following lines if your Aspose.Cells version includes these members
            // Series series = chart.NSeries[0];
            // series.IsShowDataLabel = true;
            // series.DataLabels.ShowBackground = false;

            // Define output file path
            string outputPath = "DoughnutChart.xlsx";

            // Save the workbook (overwrite if it already exists)
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
