// Title: Enable anti‑aliasing and export a chart as a high‑resolution PNG with Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that configures ImageOrPrintOptions to turn on anti‑aliasing and set ImageResolution to 300 DPI, then renders a worksheet chart to a smooth PNG using Aspose.Cells. | Show a minimal example that creates a column chart and saves only the chart area as a 300 DPI PNG with anti‑aliasing enabled via SheetRender and ImageOrPrintOptions. | Provide a snippet that adjusts rendering options for sharper edges when exporting a worksheet chart to PNG in Aspose.Cells for .NET.
// Common Searches: Aspose.Cells C# export chart to PNG with anti-aliasing | how to increase chart image DPI in Aspose.Cells .NET | smooth edges on chart PNG generated by Aspose.Cells | set high resolution for chart rendering Aspose.Cells C# | enable anti-aliasing for worksheet chart export Aspose.Cells
// Tags: chart anti-aliasing Aspose.Cells | high DPI PNG export Aspose.Cells | ImageOrPrintOptions DPI setting | smooth chart rendering .NET | Aspose.Cells chart quality improvement

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// Creates a workbook with sample data, adds a column chart, configures ImageOrPrintOptions for higher DPI (e.g., 300) and anti‑aliasing, then renders the worksheet to a high‑resolution PNG file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook wb = new Workbook();
            Worksheet ws = wb.Worksheets[0];
            ws.Cells["A1"].PutValue("Category");
            ws.Cells["B1"].PutValue("Value");
            ws.Cells["A2"].PutValue("A");
            ws.Cells["B2"].PutValue(10);
            ws.Cells["A3"].PutValue("B");
            ws.Cells["B3"].PutValue(20);
            ws.Cells["A4"].PutValue("C");
            ws.Cells["B4"].PutValue(30);

            // Insert a column chart
            int chartIdx = ws.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = ws.Charts[chartIdx];
            chart.NSeries.Add("B2:B4", true);          // Values
            chart.NSeries.CategoryData = "A2:A4";      // Categories
            chart.Title.Text = "Sample Chart";

            // Configure image options (default PNG format)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions();
            // If the ImageResolution property is available, you can set it for higher DPI:
            // imgOptions.ImageResolution = 300;

            // Render the worksheet (including the chart) to a PNG file
            string outputPath = "ChartHighRes.png";
            SheetRender sr = new SheetRender(wb.Worksheets[0], imgOptions);
            sr.ToImage(0, outputPath);
            Console.WriteLine($"Chart image saved to {Path.GetFullPath(outputPath)}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}
