// Title: Export a Waterfall chart to a high‑resolution transparent PNG using Aspose.Cells for .NET
// AI Prompts: Generate C# code that creates a waterfall chart from a data range and saves it as a 300 dpi transparent PNG with Aspose.Cells. | Show how to configure ImageOrPrintOptions to export any Aspose.Cells chart at 600 dpi and write the image to a custom file path. | Demonstrate exporting only the chart object (without the worksheet) to a PNG file while preserving the chart title and formatting.
// Common Searches: asp.net how to export a waterfall chart as a 300 dpi PNG with Aspose.Cells | C# Aspose.Cells ImageOrPrintOptions set transparent background for chart image | save Excel waterfall chart to high resolution PNG using Aspose.Cells library | increase DPI of chart image generated by Aspose.Cells in .NET | export only chart area to PNG file from Aspose.Cells workbook
// Tags: waterfall chart export PNG Aspose.Cells | high‑dpi chart PNG Aspose.Cells | ImageOrPrintOptions DPI configuration Aspose.Cells | transparent PNG output for Excel charts C# | Aspose.Cells chart rendering to image

using System;
using System.Drawing.Imaging;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// The sample creates a workbook, fills it with category/value data, adds a Waterfall chart, and uses ImageOrPrintOptions with 300 dpi resolution and transparency to export the chart directly to a PNG file named WaterfallChart.png via Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            var workbook = new Workbook();
            var sheet = workbook.Worksheets[0];

            // Populate sample data for the waterfall chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            string[] categories = { "Start", "Revenue", "Cost", "Profit", "End" };
            double[] values = { 0, 200, -80, 120, 0 };
            for (int i = 0; i < categories.Length; i++)
            {
                sheet.Cells[i + 1, 0].PutValue(categories[i]);
                sheet.Cells[i + 1, 1].PutValue(values[i]);
            }

            // Add a waterfall chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Waterfall, 5, 0, 25, 10);
            var chart = sheet.Charts[chartIndex];

            // Set chart title and data source
            chart.Title.Text = "Waterfall Chart";
            chart.NSeries.Add("B2:B6", true);
            chart.NSeries.CategoryData = "A2:A6";

            // Export the chart directly to a high‑resolution PNG file
            var imgOptions = new ImageOrPrintOptions
            {
                HorizontalResolution = 300,
                VerticalResolution = 300,
                Transparent = true
            };
            // Use overload without ImageFormat parameter
            chart.ToImage("WaterfallChart.png", imgOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
