// Title: Export Aspose.Cells Chart to SVG with Selectable Text (C#)
// Description: Creates a workbook, adds a column chart with fruit‑sales data, and uses SvgImageOptions (FitToViewPort, CssPrefix, EmbeddedFontType.None) to export the chart as a responsive SVG where all labels remain selectable text.
// Keywords: Aspose.Cells | C# | chart export SVG | selectable text SVG | SvgImageOptions | FitToViewPort | CssPrefix | EmbeddedFontType.None | responsive web chart | column chart SVG | Aspose.Cells example GitHub
// Common Searches: Aspose.Cells export chart to SVG C# | How to keep text selectable in SVG generated by Aspose.Cells | FitToViewPort option Aspose SVG example | Add CSS prefix to Aspose.Cells SVG output | Export column chart as scalable SVG using Aspose.Cells
// Developer Intent: Generate an SVG file from a workbook chart while preserving searchable, selectable text for web integration.
// Use Cases: Embedding a sales chart in a web page where users can copy axis labels and titles. | Building a dashboard that requires scalable SVG graphics without embedding fonts. | Creating multiple charts on a single page and avoiding CSS conflicts by applying unique prefixes.
// AI Prompts: Show how to embed fonts in the exported SVG instead of using selectable text. | Demonstrate exporting several charts to separate SVG files with different CssPrefix values. | Explain how to modify the SVG viewport size after export using Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

namespace ExportChartToSvgApp
{
    // Creates a workbook, adds a column chart with fruit‑sales data, and uses SvgImageOptions (FitToViewPort, CssPrefix, EmbeddedFontType.None) to export the chart as a responsive SVG where all labels remain selectable text.
    class ExportChartToSvg
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet worksheet = workbook.Worksheets[0];

                // Populate sample data for the chart
                worksheet.Cells["A1"].PutValue("Category");
                worksheet.Cells["A2"].PutValue("Apple");
                worksheet.Cells["A3"].PutValue("Orange");
                worksheet.Cells["A4"].PutValue("Banana");

                worksheet.Cells["B1"].PutValue("Value");
                worksheet.Cells["B2"].PutValue(120);
                worksheet.Cells["B3"].PutValue(80);
                worksheet.Cells["B4"].PutValue(150);

                // Add a column chart to the worksheet
                int chartIndex = worksheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
                Chart chart = worksheet.Charts[chartIndex];
                chart.NSeries.Add("B2:B4", true);               // Values
                chart.NSeries.CategoryData = "A2:A4";           // Categories
                chart.Title.Text = "Fruit Sales";

                // Configure SVG rendering options
                SvgImageOptions svgOptions = new SvgImageOptions
                {
                    FitToViewPort = true,                        // Fit SVG to viewport for responsive display
                    CssPrefix = "chart-",                        // Optional CSS prefix
                    EmbeddedFontType = SvgEmbeddedFontType.None // Keep text as selectable text
                };

                // Export the chart to an SVG file
                string outputPath = "FruitSalesChart.svg";
                chart.ToImage(outputPath, svgOptions);
                Console.WriteLine($"Chart exported successfully to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
