// Title: Export a Column Chart to Responsive SVG with Embedded WOFF Fonts using Aspose.Cells for .NET (C#)
// Description: Creates an Excel workbook, fills it with month‑wise sales data, adds a column chart, and uses Aspose.Cells' SvgImageOptions (FitToViewPort, CssPrefix, EmbeddedFontType.Woff) to render the chart directly to a scalable SVG file suitable for web pages.
// Keywords: Aspose.Cells SVG export | C# chart to SVG | responsive SVG chart | FitToViewPort Aspose.Cells | CssPrefix SVG | embedded WOFF fonts | column chart SVG | Aspose.Cells for .NET
// Common Searches: How to export an Aspose.Cells chart as SVG in C# | Aspose.Cells FitToViewPort option for SVG | Add CSS prefix to SVG generated by Aspose.Cells | Embed WOFF fonts in SVG using Aspose.Cells | Render Excel chart to scalable SVG
// Developer Intent: Generate a web‑ready SVG version of an Excel chart that scales automatically and preserves text styling through embedded fonts.
// Use Cases: Display quarterly sales data on a website without raster images. | Integrate multiple charts into a single HTML page while avoiding CSS conflicts. | Archive the original workbook alongside the SVG for data analysis and visual reporting.
// AI Prompts: Show C# code to export a pie chart to SVG with FitToViewPort and a custom CssPrefix using Aspose.Cells. | Explain how to change SvgImageOptions to embed TrueType (TTF) fonts instead of WOFF. | Provide a loop that iterates through all charts in a workbook and saves each as a separate SVG file.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

namespace AsposeCellsSvgDemo
{
    // Creates an Excel workbook, fills it with month‑wise sales data, adds a column chart, and uses Aspose.Cells' SvgImageOptions (FitToViewPort, CssPrefix, EmbeddedFontType.Woff) to render the chart directly to a scalable SVG file suitable for web pages.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data for the chart
                sheet.Cells["A1"].PutValue("Month");
                sheet.Cells["A2"].PutValue("Jan");
                sheet.Cells["A3"].PutValue("Feb");
                sheet.Cells["A4"].PutValue("Mar");
                sheet.Cells["B1"].PutValue("Sales");
                sheet.Cells["B2"].PutValue(12000);
                sheet.Cells["B3"].PutValue(15000);
                sheet.Cells["B4"].PutValue(18000);

                // Add a column chart to the worksheet
                int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
                Chart chart = sheet.Charts[chartIndex];

                // Set the data range for the chart
                chart.NSeries.Add("B2:B4", true);
                chart.NSeries.CategoryData = "A2:A4";
                chart.Title.Text = "Quarterly Sales";

                // Configure SVG rendering options
                SvgImageOptions svgOptions = new SvgImageOptions
                {
                    // Ensure the generated SVG fits the viewport for responsive scaling
                    FitToViewPort = true,
                    // Optional: add a CSS prefix to avoid style conflicts in web pages
                    CssPrefix = "mychart-",
                    // Embed fonts as WOFF to preserve text appearance across browsers
                    EmbeddedFontType = SvgEmbeddedFontType.Woff
                    // No need to set ImageType for SVG rendering
                };

                // Render the chart directly to an SVG file
                string svgPath = "QuarterlySalesChart.svg";
                chart.ToImage(svgPath, svgOptions);

                // Optionally save the workbook for reference
                string workbookPath = "QuarterlySalesWorkbook.xlsx";
                workbook.Save(workbookPath);

                Console.WriteLine($"SVG chart generated at: {Path.GetFullPath(svgPath)}");
                Console.WriteLine($"Workbook saved at: {Path.GetFullPath(workbookPath)}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
