// Title: Create an Excel column chart and hide its legend with Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code using Aspose.Cells that builds a column chart from worksheet data and turns off the legend. | Provide a complete Aspose.Cells example that adds a chart to a sheet and sets ShowLegend to false for a clean layout. | Write a .NET snippet that creates sample data, inserts a column chart, and disables the legend display with Aspose.Cells.
// Common Searches: Aspose.Cells C# example to hide chart legend in a column chart | how to disable legend in Excel chart using Aspose.Cells .NET | minimalist column chart without legend generated by Aspose.Cells | set ShowLegend false Aspose.Cells C# tutorial
// Tags: Aspose.Cells chart legend removal | column chart minimal layout Aspose.Cells | Excel chart formatting Aspose.Cells C# | ShowLegend property usage Aspose.Cells | create chart with data series Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Charts;
using System;
using System.IO;

// The program creates a workbook, adds sample data, inserts a column chart, disables its legend via ShowLegend = false, and saves the file as ChartWithoutLegend.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B4"].PutValue(30);

            // Add a column chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];

            // Define the data series and categories
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Hide the chart legend for a minimalist layout
            chart.ShowLegend = false;

            // Save the workbook with the chart
            string outputPath = "ChartWithoutLegend.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to {Path.GetFullPath(outputPath)}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
