// Title: Hide major and minor Y‑axis gridlines in an Aspose.Cells column chart with C#
// AI Prompts: Generate C# code using Aspose.Cells that creates a column chart and disables both major and minor gridlines on the value (Y) axis. | Show how to set chart.ValueAxis.MajorGridLines.IsVisible and chart.ValueAxis.MinorGridLines.IsVisible to false in a .NET workbook. | Provide a complete Aspose.Cells example that adds sample data, inserts a column chart, hides Y‑axis gridlines, and saves the workbook.
// Common Searches: asp.net aspose.cells hide y axis gridlines column chart | c# aspose.cells turn off major gridlines on chart value axis | remove minor gridlines from chart using Aspose.Cells for .NET | how to hide y‑axis gridlines in an Excel chart generated by Aspose.Cells | Aspose.Cells chart formatting hide y axis gridlines programmatically
// Tags: Aspose.Cells remove Y‑axis gridlines | C# set chart ValueAxis gridline visibility | column chart visual formatting Aspose.Cells | disable major and minor gridlines .NET | Excel chart cleanup using Aspose.Cells

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;

// // This example creates a workbook, populates sample data, adds a column chart, and sets the chart's ValueAxis major and minor gridlines to invisible before saving the file as HideYAxisGridlines.xlsx.
class HideYAxisGridlines
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Add sample data for the chart
        sheet.Cells["A1"].PutValue("Category");
        sheet.Cells["A2"].PutValue("A");
        sheet.Cells["A3"].PutValue("B");
        sheet.Cells["A4"].PutValue("C");
        sheet.Cells["B1"].PutValue("Value");
        sheet.Cells["B2"].PutValue(10);
        sheet.Cells["B3"].PutValue(20);
        sheet.Cells["B4"].PutValue(30);

        // Insert a column chart
        int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
        Chart chart = sheet.Charts[chartIndex];

        // Set the chart data range
        chart.NSeries.Add("B2:B4", true);
        chart.NSeries.CategoryData = "A2:A4";

        // Hide Y‑axis (value axis) major and minor gridlines for a cleaner look
        chart.ValueAxis.MajorGridLines.IsVisible = false;
        chart.ValueAxis.MinorGridLines.IsVisible = false;

        // Save the workbook
        workbook.Save("HideYAxisGridlines.xlsx");
    }
}
