// Title: Aspose.Cells C# – Apply Arial 12pt Font to All Chart Titles in a Workbook
// Description: Demonstrates how to create or load an Aspose.Cells Workbook, loop through every worksheet and its charts, ensure each chart title is visible, and set the title font to Arial size 12 before saving the file.
// Keywords: Aspose.Cells chart title font | C# set chart title Arial 12pt | iterate all charts Aspose.Cells | .NET workbook chart formatting | bulk chart title styling | Aspose.Cells API title visibility | Excel chart title automation | US developers Aspose.Cells | European .NET chart customization
// Common Searches: how to change font of all chart titles in Aspose.Cells C# | iterate worksheets and charts to set title font Aspose.Cells | make chart titles visible and set Arial 12pt programmatically | bulk update chart title style in .NET Excel library | Aspose.Cells set chart title size and family
// Developer Intent: Programmatically set every chart title in a workbook to Arial 12pt and ensure the titles are visible.
// Use Cases: Standardize chart title appearance across multiple worksheets in automated reports. | Apply corporate branding by enforcing a uniform title font for all charts generated by a .NET service. | Batch‑process workbooks to ensure consistent chart title styling before distribution.
// AI Prompts: Write C# code using Aspose.Cells that changes all chart titles to Verdana 10pt and hides titles that are empty. | Create a reusable method that accepts a font name and size and applies it to every chart title in a given Workbook. | Explain how to extend the example to also set the chart title color to blue and align the text to the center.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Demonstrates how to create or load an Aspose.Cells Workbook, loop through every worksheet and its charts, ensure each chart title is visible, and set the title font to Arial size 12 before saving the file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Iterate through all worksheets in the workbook
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Iterate through all charts in the current worksheet
                foreach (Chart chart in sheet.Charts)
                {
                    // Ensure the title is visible
                    chart.Title.IsVisible = true;

                    // Set the title font to Arial, size 12
                    chart.Title.Font.Name = "Arial";
                    chart.Title.Font.Size = 12;
                }
            }

            // Define output file name
            string outputPath = "AllChartTitlesArial12.xlsx";

            // Save the workbook with the updated chart titles
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
