// Title: Read an existing chart title and assign a custom title in an Excel workbook using Aspose.Cells for .NET (C#)
// AI Prompts: Create a new Workbook, populate cells with sample data, add a column chart, print the chart.Title.Text, then set chart.Title.Text to a custom string and save the workbook. | Retrieve the current title of a chart generated by Aspose.Cells, display it in the console, replace it with "Custom Chart Title", and verify the update before saving. | Programmatically generate a column chart from range B2:B4, read its initial title, change the title to a user‑defined value, and output the modified workbook.
// Common Searches: asp.net aspose.cells read chart title from generated Excel file | c# change column chart title using Aspose.Cells API | how to set a custom chart title after creating a chart with Aspose.Cells | example of updating chart.Title.Text property in Aspose.Cells for .NET | modify Excel chart title programmatically with Aspose.Cells C#
// Tags: Aspose.Cells chart title modification C# | Aspose.Cells assign new chart title | Aspose.Cells access chart title | Aspose.Cells column chart creation example | Aspose.Cells workbook save after chart update | Aspose.Cells chart Title.Text API usage

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;

namespace AsposeCellsExamples
{
    // // Demonstrates creating a workbook, adding sample data, inserting a column chart, reading its initial title, changing the title to a custom string, and saving the file.
    public class ModifyChartTitle
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data for the chart
                sheet.Cells["A1"].PutValue("Category");
                sheet.Cells["A2"].PutValue("A");
                sheet.Cells["A3"].PutValue("B");
                sheet.Cells["A4"].PutValue("C");
                sheet.Cells["B1"].PutValue("Value");
                sheet.Cells["B2"].PutValue(10);
                sheet.Cells["B3"].PutValue(20);
                sheet.Cells["B4"].PutValue(30);

                // Add a column chart (positioned from row 5, column 0 to row 20, column 8)
                int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
                Chart chart = sheet.Charts[chartIndex];

                // Set data range for the chart
                chart.NSeries.Add("B2:B4", true);
                chart.NSeries.CategoryData = "A2:A4";

                // Optionally set an initial title
                chart.Title.Text = "Original Title";

                // Read and display the existing chart title
                string existingTitle = chart.Title.Text;
                Console.WriteLine("Existing Chart Title: " + existingTitle);

                // Modify the chart title to a custom string
                chart.Title.Text = "Custom Chart Title";

                // Verify the change
                Console.WriteLine("Updated Chart Title: " + chart.Title.Text);

                // Save the workbook
                workbook.Save("ModifiedChartTitle.xlsx");
                Console.WriteLine("Workbook saved as ModifiedChartTitle.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            ModifyChartTitle.Run();
        }
    }
}
