// Title: Export an Aspose.Cells Column Chart to PNG in C# and Save to an Output Folder
// Description: Creates a workbook, fills cells A1:B4 with fruit sales data, adds a column chart, sets the data range and title, ensures an "output" directory exists, then uses Chart.ToImage with ImageType.Png to render the chart as "chart.png" in that folder.
// Keywords: Aspose.Cells | C# chart export PNG | Chart.ToImage | save chart image .NET | export Excel chart as PNG | column chart image | Aspose.Cells example | output directory | render chart to image | Aspose.Cells Chart export
// Common Searches: Aspose.Cells export chart to PNG C# | How to save chart image with Aspose.Cells .NET | Chart.ToImage method example | Create output folder Aspose.Cells | Render Excel chart as PNG using C#
// Developer Intent: Generate a PNG image of a modified Excel chart and store it in a designated folder using Aspose.Cells for .NET.
// Use Cases: Include chart PNGs in automated reporting pipelines. | Create thumbnail images for web dashboards from Excel data. | Attach chart snapshots to email notifications generated by a backend service.
// AI Prompts: Show how to export the chart as a JPEG instead of PNG. | Provide code to set custom width and height before saving the chart image. | Explain how to embed the generated PNG chart into a PDF with Aspose.PDF.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Drawing;

// Creates a workbook, fills cells A1:B4 with fruit sales data, adds a column chart, sets the data range and title, ensures an "output" directory exists, then uses Chart.ToImage with ImageType.Png to render the chart as "chart.png" in that folder.
class RenderChartToPng
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data for the chart
        sheet.Cells["A1"].PutValue("Category");
        sheet.Cells["A2"].PutValue("Apple");
        sheet.Cells["A3"].PutValue("Orange");
        sheet.Cells["A4"].PutValue("Banana");

        sheet.Cells["B1"].PutValue("Value");
        sheet.Cells["B2"].PutValue(1200);
        sheet.Cells["B3"].PutValue(800);
        sheet.Cells["B4"].PutValue(1500);

        // Add a column chart to the worksheet
        int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
        Chart chart = sheet.Charts[chartIndex];

        // Set the data range for the chart
        chart.SetChartDataRange("A1:B4", true);

        // Example modification: set a chart title
        chart.Title.Text = "Sales by Fruit";

        // Ensure the output directory exists
        string outputDir = Path.Combine(Environment.CurrentDirectory, "output");
        Directory.CreateDirectory(outputDir);

        // Define the full path for the PNG image
        string imagePath = Path.Combine(outputDir, "chart.png");

        // Render the chart to a PNG image and save it
        chart.ToImage(imagePath, ImageType.Png);

        Console.WriteLine($"Chart image successfully saved to: {imagePath}");
    }
}
