// Title: How to set a localized chart title and axis labels on a Gantt chart using Aspose.Cells for .NET (C#)
// AI Prompts: Generate a new workbook, populate task data, add a stacked‑bar Gantt chart, and assign culture‑specific strings to the chart title, X‑axis, and Y‑axis with Aspose.Cells. | Implement a helper that returns a localized string for a given key and CultureInfo, then apply the returned values to Chart.Title.Text, Chart.ValueAxis.Title.Text, and Chart.CategoryAxis.Title.Text. | Enable visibility for the chart and axis titles and save the workbook as an .xlsx file.
// Common Searches: aspocells set chart title with localization c# | how to add axis titles to a gantt chart using aspocells | retrieve resource strings for chart elements based on cultureinfo .net | create stacked bar gantt chart aspocells c# example | display localized chart titles in excel file generated by aspocells
// Tags: Aspose.Cells set localized chart title | Aspose.Cells Gantt chart axis labels | Aspose.Cells culture-specific chart text | Aspose.Cells stacked bar chart .xlsx | Aspose.Cells retrieve localized strings C#

using System;
using System.Globalization;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Creates a workbook, adds sample task data, builds a stacked‑bar Gantt chart, fetches culture‑aware strings for the chart title and both axes, makes the titles visible, and saves the result as GanttChart.xlsx using Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for a Gantt chart
            sheet.Cells["A1"].PutValue("Task");
            sheet.Cells["B1"].PutValue("Start");
            sheet.Cells["C1"].PutValue("Duration");
            sheet.Cells["A2"].PutValue("Task 1");
            sheet.Cells["B2"].PutValue(DateTime.Today);
            sheet.Cells["C2"].PutValue(5);
            sheet.Cells["A3"].PutValue("Task 2");
            sheet.Cells["B3"].PutValue(DateTime.Today.AddDays(2));
            sheet.Cells["C3"].PutValue(3);

            // Add a stacked bar chart (horizontal bars are used for Gantt charts)
            int chartIndex = sheet.Charts.Add(ChartType.BarStacked, 5, 0, 25, 10);
            Chart chart = sheet.Charts[chartIndex];

            // Set the data range for the series (Start and Duration)
            chart.NSeries.Add("B2:C3", true);
            // Set the category (task names)
            chart.NSeries.CategoryData = "A2:A3";

            // Retrieve localized strings
            string chartTitle = GetLocalizedString("ChartTitle", CultureInfo.CurrentCulture);
            string xAxisTitle = GetLocalizedString("XAxisTitle", CultureInfo.CurrentCulture);
            string yAxisTitle = GetLocalizedString("YAxisTitle", CultureInfo.CurrentCulture);

            // Set chart title
            chart.Title.Text = chartTitle;
            chart.Title.IsVisible = true;

            // Set axis titles
            chart.ValueAxis.Title.Text = xAxisTitle;      // X‑axis (duration)
            chart.ValueAxis.Title.IsVisible = true;
            chart.CategoryAxis.Title.Text = yAxisTitle;   // Y‑axis (tasks)
            chart.CategoryAxis.Title.IsVisible = true;

            // Save the workbook
            string outputPath = "GanttChart.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"Error: {ex.Message}");
        }
    }

    // Simple localization mock‑up; replace with real resource lookup as needed
    static string GetLocalizedString(string key, CultureInfo culture)
    {
        switch (key)
        {
            case "ChartTitle":
                return culture.TwoLetterISOLanguageName switch
                {
                    "fr" => "Diagramme de Gantt",
                    "es" => "Diagrama de Gantt",
                    _ => "Gantt Chart"
                };
            case "XAxisTitle":
                return culture.TwoLetterISOLanguageName switch
                {
                    "fr" => "Durée (jours)",
                    "es" => "Duración (días)",
                    _ => "Duration (Days)"
                };
            case "YAxisTitle":
                return culture.TwoLetterISOLanguageName switch
                {
                    "fr" => "Tâches",
                    "es" => "Tareas",
                    _ => "Tasks"
                };
            default:
                return string.Empty;
        }
    }
}
