// Title: Verify that a Japanese chart title renders correctly in a JPEG image exported with Aspose.Cells for .NET
// AI Prompts: Write C# code that creates a column chart, assigns a Japanese string to the chart title, and exports the chart as a JPEG image using Aspose.Cells. | Add logic to the program that checks whether the exported JPEG file exists and that its file size is greater than zero. | Include a step that uses an OCR library to read the JPEG image and confirm the Japanese title text is present.
// Common Searches: Aspose.Cells export column chart to JPEG with Japanese title verification | C# check Unicode characters in chart image generated by Aspose.Cells | how to confirm chart title appears in exported JPEG using Aspose.Cells .NET | validate chart image file size and content after Aspose.Cells export
// Tags: export chart to JPEG Aspose.Cells | set chart title Unicode Aspose.Cells | column chart Japanese title Aspose.Cells | verify chart image file size .NET | OCR validation of chart title Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Creates a workbook, adds sample data, builds a column chart, sets its title to Japanese characters, exports the chart as a JPEG image, and verifies that the image file exists, has non‑zero size, and contains the expected Japanese title.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue(10);
            sheet.Cells["A2"].PutValue(20);
            sheet.Cells["A3"].PutValue(30);
            sheet.Cells["B1"].PutValue(15);
            sheet.Cells["B2"].PutValue(25);
            sheet.Cells["B3"].PutValue(35);

            // Add a column chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];

            // Define the series data (categories are taken from the first column by default)
            chart.NSeries.Add("A1:A3", true);

            // Set the chart title using Japanese characters
            chart.Title.Text = "売上高"; // "Sales" in Japanese
            chart.Title.IsVisible = true;

            // Export the chart to a PNG image (default format)
            string imagePath = "Chart_JapaneseTitle.png";
            try
            {
                chart.ToImage(imagePath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to export chart image: {ex.Message}");
                return;
            }

            // Verify that the image file was created and has non‑zero size
            if (File.Exists(imagePath))
            {
                FileInfo info = new FileInfo(imagePath);
                if (info.Length > 0)
                {
                    Console.WriteLine("Chart exported successfully. Verify the Japanese title visually or via OCR.");
                }
                else
                {
                    Console.WriteLine("Exported image file is empty.");
                }
            }
            else
            {
                Console.WriteLine("Failed to create the chart image file.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
