// Title: Add a Diagonal CONFIDENTIAL Text Watermark to a Timeline Chart PDF with Aspose.Cells for .NET
// Description: Creates an Excel workbook, populates date‑value rows, generates a line chart as a project timeline, configures a semi‑transparent rotated text watermark via RenderingWatermark, and saves the result as a PDF using PdfSaveOptions.
// Keywords: Aspose.Cells watermark PDF | C# RenderingWatermark example | timeline chart export Aspose | diagonal text watermark .NET | PDFSaveOptions Aspose.Cells | confidential watermark Excel | chart to PDF with watermark
// Common Searches: how to add a diagonal watermark to a PDF generated by Aspose.Cells | Aspose.Cells render line chart and apply text watermark | C# export Excel chart as PDF with background watermark | set opacity and rotation for RenderingWatermark in Aspose.Cells | save workbook as PDF with watermark using Aspose.Cells for .NET
// Developer Intent: Apply a rotated, semi‑transparent text watermark to a PDF that contains a rendered timeline chart created with Aspose.Cells.
// Use Cases: Distribute internal project timelines marked as CONFIDENTIAL. | Include a company slogan or logo behind charts in compliance reports. | Produce legal documents where the chart must remain visible under a watermark.
// AI Prompts: Generate C# code that builds a line chart from date‑value data, adds a 45° CONFIDENTIAL watermark, and saves the workbook as a PDF with Aspose.Cells. | Show how to set RenderingWatermark properties such as Rotation, Opacity, ScaleToPagePercent, and alignment for PDF export. | Explain the steps to embed a background text watermark while preserving chart clarity in an Aspose.Cells PDF output.

using System;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

namespace AsposeCellsWatermarkDemo
{
    // Creates an Excel workbook, populates date‑value rows, generates a line chart as a project timeline, configures a semi‑transparent rotated text watermark via RenderingWatermark, and saves the result as a PDF using PdfSaveOptions.
    public class TimelineWatermark
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample timeline data (dates and values)
                sheet.Cells["A1"].PutValue("Date");
                sheet.Cells["B1"].PutValue("Value");
                sheet.Cells["A2"].PutValue(new DateTime(2023, 1, 1));
                sheet.Cells["B2"].PutValue(120);
                sheet.Cells["A3"].PutValue(new DateTime(2023, 2, 1));
                sheet.Cells["B3"].PutValue(150);
                sheet.Cells["A4"].PutValue(new DateTime(2023, 3, 1));
                sheet.Cells["B4"].PutValue(130);
                sheet.Cells["A5"].PutValue(new DateTime(2023, 4, 1));
                sheet.Cells["B5"].PutValue(170);

                // Add a line chart to represent the timeline
                int chartIndex = sheet.Charts.Add(ChartType.Line, 7, 0, 25, 15);
                Chart chart = sheet.Charts[chartIndex];
                chart.NSeries.Add("B2:B5", true);               // Values
                chart.NSeries.CategoryData = "A2:A5";           // Dates as categories
                chart.Title.Text = "Project Timeline";

                // Configure a text watermark
                RenderingFont watermarkFont = new RenderingFont("Arial", 48)
                {
                    Color = Color.LightGray,
                    Bold = true,
                    Italic = true
                };
                RenderingWatermark watermark = new RenderingWatermark("CONFIDENTIAL", watermarkFont)
                {
                    Rotation = 45f,                     // Diagonal watermark
                    Opacity = 0.25f,                    // Semi‑transparent
                    IsBackground = true,                // Place behind content
                    HAlignment = TextAlignmentType.Center,
                    VAlignment = TextAlignmentType.Center,
                    ScaleToPagePercent = 80
                };

                // Set PDF save options with the watermark
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    Watermark = watermark
                };

                // Save the workbook (including the rendered timeline chart) as a PDF with watermark
                workbook.Save("TimelineWatermarked.pdf", pdfOptions);
                Console.WriteLine("PDF saved successfully: TimelineWatermarked.pdf");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            TimelineWatermark.Run();
        }
    }
}
