// Title: Create a pivot‑driven timeline in an Excel worksheet and export to a multi‑page PDF with the timeline on every page using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that builds a workbook, adds a pivot table from a date‑sales range, inserts a timeline linked to the Date field, customizes its size and caption, and saves the workbook as a PDF where the timeline repeats on each page using Aspose.Cells. | Show how to set up Aspose.Cells PdfSaveOptions to produce a multi‑page PDF from a worksheet containing a timeline control, ensuring the timeline is rendered on every page.
// Common Searches: Aspose.Cells C# add timeline to pivot table and keep it in PDF output | How to export Excel worksheet with timeline to multi‑page PDF using Aspose.Cells | C# PdfSaveOptions timeline visibility across PDF pages | Create Excel timeline programmatically with Aspose.Cells and save as PDF | Include Excel timeline control in PDF generated by Aspose.Cells .NET
// Tags: pivot table timeline insertion Aspose.Cells | pdf export with timeline control Aspose.Cells | multi‑page PDF generation using PdfSaveOptions Aspose.Cells | timeline shape customization C# Aspose.Cells | render Excel timeline in PDF Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Pivot;
using Aspose.Cells.Timelines;
using Aspose.Cells.Rendering;

namespace TimelinePdfDemo
{
    // The example creates a new workbook, fills it with date and sales data, builds a pivot table, adds a timeline linked to the Date field, customizes the timeline's position, size, and caption, configures PdfSaveOptions for multi‑page output, and saves the workbook as a PDF where the timeline appears on every generated page.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Populate worksheet with sample date and sales data
                cells["A1"].Value = "Date";
                cells["B1"].Value = "Sales";

                cells["A2"].Value = new DateTime(2023, 1, 1);
                cells["B2"].Value = 1200;

                cells["A3"].Value = new DateTime(2023, 2, 1);
                cells["B3"].Value = 1500;

                cells["A4"].Value = new DateTime(2023, 3, 1);
                cells["B4"].Value = 1800;

                // Create a pivot table that will serve as the data source for the timeline
                int pivotIdx = sheet.PivotTables.Add("A1:B4", "D1", "SalesPivot");
                PivotTable pivot = sheet.PivotTables[pivotIdx];
                pivot.AddFieldToArea(PivotFieldType.Row, "Date");
                pivot.AddFieldToArea(PivotFieldType.Data, "Sales");

                // Refresh pivot cache and calculate data (no explicit IsDate needed)
                pivot.CalculateData();

                // Add a timeline linked to the pivot table (placed at row 0, column 0)
                int timelineIdx = sheet.Timelines.Add(pivot, 0, 0, "Date");
                Timeline timeline = sheet.Timelines[timelineIdx];

                // Customize the timeline appearance via its Shape object
                timeline.Shape.Top = 20;      // distance from top of the sheet (pixels)
                timeline.Shape.Left = 20;     // distance from left of the sheet (pixels)
                timeline.Shape.Width = 400;   // width in pixels
                timeline.Shape.Height = 80;   // height in pixels
                timeline.Caption = "Sales Timeline";

                // Configure PDF save options so that each sheet can span multiple pages
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    OnePagePerSheet = false,
                    AllColumnsInOnePagePerSheet = false
                };

                // Save the workbook as PDF; the timeline will be included in the output
                string outputPath = "TimelineReport.pdf";
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to '{Path.GetFullPath(outputPath)}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
