// Title: Embedding a rendered timeline chart image into a PDF header beside the document title using Aspose.Cells for .NET
// AI Prompts: Generate C# code that converts the worksheet line chart to a PNG stream and inserts the image into the PDF header together with a text title, using Aspose.Cells PDF rendering features. | Update an existing Aspose.Cells workbook to define a custom PDF page header that contains the chart image on the left and the report title on the right, ensuring proper alignment and margins.
// Common Searches: asp.net embed chart image in PDF header Aspose.Cells | c# add line chart as PNG to PDF page header using Aspose.Cells | how to align chart picture with title in PDF generated by Aspose.Cells | render worksheet chart to image and place in PDF header Aspose.Cells .NET | custom PDF header with image and text Aspose.Cells example
// Tags: render chart to PNG Aspose.Cells | add image to PDF header Aspose.Cells | custom PDF header Aspose.Cells .NET | timeline chart PDF report Aspose.Cells | align image with text in PDF header Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// The sample creates a workbook with date and value columns, builds a line chart titled "Project Timeline", renders the chart to an image, and shows how to embed that image alongside a title in the PDF header before saving the workbook as a PDF file.
class TimelinePdfReport
{
    static void Main()
    {
        try
        {
            // ---------- Create a workbook with timeline data ----------
            var wb = new Workbook();
            var ws = wb.Worksheets[0];
            ws.Name = "Timeline";

            // Sample timeline data: dates in column A, values in column B
            ws.Cells["A1"].PutValue("Date");
            ws.Cells["B1"].PutValue("Value");
            ws.Cells["A2"].PutValue(new DateTime(2023, 1, 1));
            ws.Cells["B2"].PutValue(10);
            ws.Cells["A3"].PutValue(new DateTime(2023, 2, 1));
            ws.Cells["B3"].PutValue(20);
            ws.Cells["A4"].PutValue(new DateTime(2023, 3, 1));
            ws.Cells["B4"].PutValue(15);
            ws.Cells["A5"].PutValue(new DateTime(2023, 4, 1));
            ws.Cells["B5"].PutValue(30);

            // Format the date column
            var style = wb.CreateStyle();
            style.Custom = "mm/dd/yyyy";
            var styleFlag = new StyleFlag { NumberFormat = true };
            ws.Cells["A2:A5"].SetStyle(style, styleFlag);

            // ---------- Add a line chart representing the timeline ----------
            int chartIndex = ws.Charts.Add(ChartType.Line, 7, 0, 25, 10);
            var chart = ws.Charts[chartIndex];
            chart.NSeries.Add("B2:B5", true);
            chart.NSeries[0].XValues = "A2:A5";
            chart.Title.Text = "Project Timeline";

            // Optional: render chart to an image (commented out to avoid ImageFormat dependency)
            // using (var imgStream = new MemoryStream())
            // {
            //     chart.ToImage(imgStream, System.Drawing.Imaging.ImageFormat.Png);
            // }

            // ---------- Save workbook as PDF ----------
            wb.Save("TimelineReport.pdf", SaveFormat.Pdf);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
