// Title: Set a workbook’s default column width using Cells.StandardWidth in Aspose.Cells for .NET before adding data
// AI Prompts: Apply the Cells.StandardWidth property to define a uniform column width (in character units) for the worksheet, then insert cell values. | After configuring StandardWidth, call Cells.GetColumnWidth for a specific column index, output the result, and save the workbook as an .xlsx file.
// Common Searches: Aspose.Cells C# set default column width for all columns before writing data | How to use Cells.StandardWidth to define column width in a new workbook | Retrieve column width after setting StandardWidth with Aspose.Cells .NET | Initialize worksheet column width to 20 characters using Aspose.Cells | Set column width globally in Excel file generated by Aspose.Cells C#
// Tags: Cells.StandardWidth configuration | global column width setting Aspose.Cells | programmatic column width retrieval | uniform column width before data entry | export workbook with standardized column width

using System;
using Aspose.Cells;

namespace AsposeCellsStandardWidthDemo
{
    // Demonstrates creating a workbook, setting Cells.StandardWidth to 20 characters to establish a base column width, adding sample data, printing the width of column A, and saving the file as StandardWidthDemo.xlsx.
    class Program
    {
        static void Main(string[] args)
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet and its cells collection
            Worksheet worksheet = workbook.Worksheets[0];
            Cells cells = worksheet.Cells;

            // Set the default column width (in character units) before adding any data
            // This establishes a base width for all columns
            cells.StandardWidth = 20.0; // Example width; adjust as needed

            // Populate some sample data to demonstrate the effect of the standard width
            cells["A1"].PutValue("Short");
            cells["B1"].PutValue("This is a longer piece of text");
            cells["C1"].PutValue("Medium length");
            cells["A2"].PutValue(12345);
            cells["B2"].PutValue(DateTime.Now);
            cells["C2"].PutValue(true);

            // Optionally, you can verify the width of a specific column
            Console.WriteLine("Column A width after setting StandardWidth: " + cells.GetColumnWidth(0));

            // Save the workbook to a file
            workbook.Save("StandardWidthDemo.xlsx");
        }
    }
}
