// Title: How to auto‑fit rows containing merged cells with wrapped text for accurate PDF output using Aspose.Cells for .NET
// AI Prompts: Write C# code that merges a cell range, enables text wrapping, sets AutoFitMergedCellsType to EachLine and AutoFitWrappedTextType to Paragraph, then auto‑fits rows and columns before exporting to PDF with Aspose.Cells. | Show the steps to configure AutoFitterOptions for merged cells so that each line of wrapped text expands the row height in a PDF generated by Aspose.Cells. | Provide a complete example that creates a workbook, merges A1:C3, applies text wrap, auto‑fits rows/columns using rendering‑aware options, and saves the file as a PDF.
// Common Searches: aspnet auto fit rows merged cells wrapped text pdf export | c# Aspose.Cells AutoFitMergedCellsType EachLine example | adjust row height for merged cells when saving workbook as PDF | how to enable text wrapping and auto‑fit merged range in Aspose.Cells | auto‑fit columns and rows for merged area before PDF generation Aspose.Cells
// Tags: auto‑fit rows merged cells Aspose.Cells | AutoFitMergedCellsType EachLine PDF | wrapped text row height adjustment .NET | AutoFitterOptions rendering mode Aspose.Cells | merge cells auto‑fit columns C#

using System;
using Aspose.Cells;

// The example creates a workbook, merges cells A1:C3, enables text wrapping, configures AutoFitterOptions with AutoFitMergedCellsType=EachLine and AutoFitWrappedTextType=Paragraph (rendering mode enabled), auto‑fits rows and columns, and saves the sheet as a PDF, ensuring merged content displays correctly.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Insert long text that will need to be wrapped and auto‑fitted
        worksheet.Cells["A1"].PutValue(
            "This is a long piece of text that should be displayed correctly after auto‑fitting merged cells in the PDF output. " +
            "It spans multiple lines and demonstrates how the row height is adjusted for merged cells.");

        // Merge a range of cells (A1:C3) to simulate a merged area
        worksheet.Cells.Merge(0, 0, 3, 3); // firstRow, firstColumn, totalRows, totalColumns

        // Enable text wrapping for the merged cell
        Style style = worksheet.Cells["A1"].GetStyle();
        style.IsTextWrapped = true;
        worksheet.Cells["A1"].SetStyle(style);

        // Configure AutoFitterOptions to handle merged cells and wrapped text
        AutoFitterOptions options = new AutoFitterOptions
        {
            // Expand the height of each row that participates in the merged area
            AutoFitMergedCellsType = AutoFitMergedCellsType.EachLine,
            // Fit based on the longest paragraph when text is wrapped
            AutoFitWrappedTextType = AutoFitWrappedTextType.Paragraph,
            // Ensure fitting is done with rendering considerations (important for PDF)
            ForRendering = true
        };

        // Auto‑fit rows using the specified options
        worksheet.AutoFitRows(options);

        // Optionally auto‑fit columns so the merged content is fully visible
        worksheet.AutoFitColumns(options);

        // Save the workbook as PDF
        workbook.Save("MergedCellsAutoFit.pdf", SaveFormat.Pdf);
    }
}
