// Title: Group Columns, AutoFit Rows, and Export to PDF with Aspose.Cells for .NET (C#)
// Description: Create a workbook, fill sample data, group columns 2‑5, auto‑fit rows (and optionally columns), configure PdfSaveOptions (OnePagePerSheet, AllColumnsInOnePagePerSheet, ExportDocumentStructure) and save the sheet as a single‑page PDF using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# | GroupColumns | AutoFitRows | PdfSaveOptions | OnePagePerSheet | AllColumnsInOnePagePerSheet | ExportDocumentStructure | Excel to PDF | column grouping | row height auto fit | export worksheet to PDF
// Common Searches: Aspose.Cells group columns C# | auto fit rows before PDF export Aspose.Cells | PdfSaveOptions OnePagePerSheet example | export Excel sheet to single page PDF Aspose.Cells | how to collapse columns and fit rows in Aspose.Cells
// Developer Intent: Group a set of columns, automatically adjust row heights, and generate a PDF where all columns fit on one page.
// Use Cases: Produce printable reports with related columns collapsed and rows sized to content, delivered as a single‑page PDF. | Create invoices where detail columns are grouped for clarity, rows auto‑adjust, and the final document is saved as PDF with preserved structure. | Generate summary sheets that hide auxiliary columns, auto‑fit row heights, and export the entire sheet to a compact PDF for distribution.
// AI Prompts: Write C# code using Aspose.Cells to group columns 3‑7, auto‑fit rows, and export the worksheet to a PDF with one page per sheet. | Explain the impact of PdfSaveOptions properties OnePagePerSheet and AllColumnsInOnePagePerSheet on PDF output when columns are grouped. | Provide troubleshooting steps if grouped columns are not visible in the PDF generated by Aspose.Cells after using GroupColumns and AutoFitRows.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExamples
{
    // Create a workbook, fill sample data, group columns 2‑5, auto‑fit rows (and optionally columns), configure PdfSaveOptions (OnePagePerSheet, AllColumnsInOnePagePerSheet, ExportDocumentStructure) and save the sheet as a single‑page PDF using Aspose.Cells for .NET.
    public class GroupColumnsAutoFitRowsExportPdf
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet worksheet = workbook.Worksheets[0];
                Cells cells = worksheet.Cells;

                // Populate sample data across several columns
                for (int row = 0; row < 20; row++)
                {
                    for (int col = 0; col < 10; col++)
                    {
                        cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                    }
                }

                // Group columns 2 to 5 (zero‑based indexes 1 to 4)
                cells.GroupColumns(1, 4);

                // Auto‑fit all rows so that row heights adjust to the content
                worksheet.AutoFitRows();

                // (Optional) Auto‑fit all columns for better visibility
                worksheet.AutoFitColumns();

                // Prepare PDF save options – fit all columns on a single page per sheet
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    OnePagePerSheet = true,
                    AllColumnsInOnePagePerSheet = true,
                    ExportDocumentStructure = true
                };

                // Export the worksheet to a PDF file
                workbook.Save("GroupedColumns_AutoFitRows.pdf", pdfOptions);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            GroupColumnsAutoFitRowsExportPdf.Run();
        }
    }
}
