// Title: C# – Delete Blank Rows & Columns with DeleteOptions (UpdateReference) in Aspose.Cells
// Description: This Aspose.Cells for .NET example creates a workbook, adds data with empty rows and columns, configures DeleteOptions to update references, calls Cells.DeleteBlankRows and Cells.DeleteBlankColumns on the first worksheet, and saves the cleaned file as DeletedBlankRowsAndColumns.xlsx.
// Keywords: Aspose.Cells DeleteBlankRows | Aspose.Cells DeleteBlankColumns | DeleteOptions UpdateReference | remove empty rows C# | remove empty columns .NET | clean workbook Aspose | C# Excel blank row deletion | C# Excel blank column removal
// Common Searches: How to delete blank rows and columns with Aspose.Cells C# | DeleteOptions UpdateReference example Aspose.Cells | Remove empty rows from first worksheet Aspose.Cells | Aspose.Cells delete empty columns .NET | C# code to clean up blank rows in Excel workbook
// Developer Intent: Eliminate all completely empty rows and columns from the first worksheet while automatically adjusting any formula references.
// Use Cases: Sanitize imported CSV or user‑generated data before analysis. | Prepare a report for distribution by stripping unnecessary blank rows/columns to reduce file size and improve layout. | Optimize workbooks generated by automation scripts, ensuring formulas remain accurate after cleanup.
// AI Prompts: Write C# code that uses Aspose.Cells DeleteOptions with UpdateReference to delete blank rows and columns on a given worksheet. | Create a reusable method that accepts a Worksheet and DeleteOptions, then removes empty rows and columns in one call. | Show how to delete blank rows/columns while preserving merged cells and updating named ranges using Aspose.Cells.

using System;
using Aspose.Cells;

namespace DeleteBlankRowsAndColumnsDemo
{
    // This Aspose.Cells for .NET example creates a workbook, adds data with empty rows and columns, configures DeleteOptions to update references, calls Cells.DeleteBlankRows and Cells.DeleteBlankColumns on the first worksheet, and saves the cleaned file as DeletedBlankRowsAndColumns.xlsx.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet worksheet = workbook.Worksheets[0];
            Cells cells = worksheet.Cells;

            // Populate some data with blank rows and columns for demonstration
            cells["A1"].PutValue("Header");
            cells["A2"].PutValue("Data1");
            // Row 3 is blank
            cells["A4"].PutValue("Data2"); // Blank row at index 2 (row 3)

            cells["A1"].PutValue("Header");
            cells["C1"].PutValue("Column C"); // Column B (index 1) will be blank

            // Configure DeleteOptions (e.g., update references after deletion)
            DeleteOptions options = new DeleteOptions
            {
                UpdateReference = true
            };

            // Delete all blank rows using the configured options
            cells.DeleteBlankRows(options);

            // Delete all blank columns using the same options
            cells.DeleteBlankColumns(options);

            // Save the workbook
            workbook.Save("DeletedBlankRowsAndColumns.xlsx", SaveFormat.Xlsx);
        }
    }
}
