// Title: Aspose.Cells for .NET – Set Excel Comment Font Color to Red (C#)
// Description: This example creates a workbook, adds a comment to cell A1, accesses the comment's CommentShape, and changes the comment text color to red by assigning Color.Red to Shape.TextBody[0].Font.Color. The comment is made visible and the file is saved as CommentWithRedFont.xlsx.
// Keywords: Aspose.Cells comment font color | C# set comment text color | Excel comment shape color | Shape.TextBody.Font.Color | Aspose.Cells formatting example
// Common Searches: how to change comment font color Aspose.Cells C# | set Excel comment text to red using Aspose.Cells | Aspose.Cells comment shape color property | C# change comment text color in generated workbook | Aspose.Cells modify comment appearance programmatically
// Developer Intent: Apply a red font color to an Excel comment using Aspose.Cells for .NET.
// Use Cases: Highlight critical notes in automated reports with red comment text. | Standardize comment styling across spreadsheets generated by a .NET application. | Implement visual cues in Excel files for data validation warnings.
// AI Prompts: Write C# code that changes an existing Excel comment's font color to blue with Aspose.Cells. | Show how to apply multiple FontSetting colors within a single comment's TextBody using Aspose.Cells. | Provide an example that makes comment text bold and red in an Aspose.Cells workbook.

using System;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsCommentFontColor
{
    // This example creates a workbook, adds a comment to cell A1, accesses the comment's CommentShape, and changes the comment text color to red by assigning Color.Red to Shape.TextBody[0].Font.Color. The comment is made visible and the file is saved as CommentWithRedFont.xlsx.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add a comment to cell A1
            int commentIndex = worksheet.Comments.Add("A1");
            Comment comment = worksheet.Comments[commentIndex];
            comment.Note = "This is a sample comment";

            // Access the shape attached to the comment
            CommentShape commentShape = comment.CommentShape;

            // Change the font color of the comment text to red
            // The TextBody property returns a collection of FontSetting objects.
            // Setting the color on the first FontSetting applies to the whole comment text.
            commentShape.TextBody[0].Font.Color = Color.Red;

            // Make the comment visible (optional)
            comment.IsVisible = true;

            // Save the workbook
            workbook.Save("CommentWithRedFont.xlsx");
        }
    }
}
