// Title: Create SMIL fill‑color animation for each <path> element in a worksheet SVG exported with Aspose.Cells (C#)
// AI Prompts: Write C# code that uses Aspose.Cells to save a workbook as SVG, then loads the SVG with XmlDocument, finds every <path> node, and appends an <animate> element that cycles the fill attribute between red and blue. | Show how to programmatically add a repeating SMIL animation (attributeName='fill', values='red;blue;red', dur='4s', repeatCount='indefinite') to all path elements in an existing SVG file using .NET's XmlDocument API. | Provide a method that writes the modified SVG containing the new <animate> elements to a separate file and prints the full path of the animated SVG.
// Common Searches: C# add SMIL fill animation to SVG paths generated by Aspose.Cells workbook export | how to inject <animate> elements into exported worksheet.svg using XmlDocument | Aspose.Cells export to SVG then animate chart colors with SMIL in .NET | programmatically modify SVG file from Excel to create color cycling animation in C#
// Tags: Aspose.Cells SVG export with SMIL animation | C# XmlDocument inject animate element into SVG paths | SMIL fill color animation for worksheet SVG | modify exported SVG path elements using .NET | dynamic color cycling in Excel-to-SVG conversion

using System;
using System.IO;
using System.Xml;
using Aspose.Cells;

// The example creates a workbook, exports it to SVG with Aspose.Cells, loads the SVG via XmlDocument, adds an <animate> element to each <path> to cycle the fill color between red and blue, and saves the animated SVG to a new file.
class SvgAnimationExample
{
    static void Main()
    {
        // 1. Create a workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Category");
        sheet.Cells["B1"].PutValue("Value");
        sheet.Cells["A2"].PutValue("A");
        sheet.Cells["B2"].PutValue(30);
        sheet.Cells["A3"].PutValue("B");
        sheet.Cells["B3"].PutValue(70);
        sheet.Cells["A4"].PutValue("C");
        sheet.Cells["B4"].PutValue(45);

        // 2. Export the worksheet to SVG format
        string svgPath = "worksheet.svg";
        workbook.Save(svgPath, SaveFormat.Svg);

        // 3. Load the generated SVG for manipulation
        XmlDocument svgDoc = new XmlDocument();
        svgDoc.Load(svgPath);

        // Define the SVG namespace for element creation
        string svgNs = "http://www.w3.org/2000/svg";

        // 4. Find all <path> elements and add SMIL animation
        XmlNodeList pathNodes = svgDoc.GetElementsByTagName("path");
        foreach (XmlElement pathElem in pathNodes)
        {
            // Create an <animate> element to animate the fill color
            XmlElement animateElem = svgDoc.CreateElement("animate", svgNs);
            animateElem.SetAttribute("attributeName", "fill");
            animateElem.SetAttribute("values", "red;blue;red"); // cycle red -> blue -> red
            animateElem.SetAttribute("dur", "4s");
            animateElem.SetAttribute("repeatCount", "indefinite");

            // Append the animation to the current <path> element
            pathElem.AppendChild(animateElem);
        }

        // 5. Save the modified SVG with animations
        string animatedSvgPath = "worksheet_animated.svg";
        using (FileStream fs = new FileStream(animatedSvgPath, FileMode.Create, FileAccess.Write))
        {
            svgDoc.Save(fs);
        }

        Console.WriteLine("Animated SVG saved to: " + Path.GetFullPath(animatedSvgPath));
    }
}
