// Title: Add SMIL stroke-color animation to SVG paths generated from an Aspose.Cells worksheet in C#
// AI Prompts: Generate a C# workbook with a column chart, export it to SVG using Aspose.Cells, then programmatically insert <animate> elements to animate the stroke attribute of each <path>. | Load the SVG produced by Aspose.Cells, traverse all <path> nodes, add a SMIL <animate> element that cycles stroke colors, and save the animated SVG file. | Show how to ensure each chart path has a stroke attribute and apply an indefinite 3‑second color transition using SMIL in a C# Aspose.Cells SVG export workflow.
// Common Searches: C# how to add SMIL animation to SVG paths generated by Aspose.Cells | Aspose.Cells export worksheet as SVG and animate chart lines | Add color transition animation to column chart SVG using Aspose.Cells .NET | Programmatically insert <animate> elements into SVG output from Aspose.Cells
// Tags: Aspose.Cells SVG export with SMIL stroke animation | C# insert animate element into SVG path | dynamic stroke color transition in worksheet SVG | XML manipulation of Aspose.Cells generated SVG | column chart SVG SMIL animation in .NET

using System;
using System.IO;
using System.Xml.Linq;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// // Creates a workbook with a column chart, saves the sheet as SVG via Aspose.Cells, loads the SVG XML, adds a SMIL <animate> element to each <path> to cycle the stroke color, and writes the animated SVG to a file.
class SvgAnimationExample
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for a chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["B3"].PutValue(30);
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B4"].PutValue(20);

            // Add a column chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Render the worksheet to SVG using a memory stream
            using (MemoryStream svgStream = new MemoryStream())
            {
                // Save the workbook (or specific sheet) as SVG into the stream
                workbook.Save(svgStream, SaveFormat.Svg);
                svgStream.Position = 0;

                // Load SVG XML for manipulation
                XDocument svgDoc = XDocument.Load(svgStream);
                XNamespace ns = "http://www.w3.org/2000/svg";

                // Add SMIL animation to each <path> element
                foreach (XElement path in svgDoc.Descendants(ns + "path"))
                {
                    // Ensure a stroke attribute exists
                    if (path.Attribute("stroke") == null)
                    {
                        path.SetAttributeValue("stroke", "red");
                    }

                    // Create <animate> element
                    XElement animate = new XElement(ns + "animate",
                        new XAttribute("attributeName", "stroke"),
                        new XAttribute("values", "red;blue;red"),
                        new XAttribute("dur", "3s"),
                        new XAttribute("repeatCount", "indefinite")
                    );

                    // Append animation to the path
                    path.Add(animate);
                }

                // Save the modified SVG to a file
                string outputPath = "AnimatedWorksheet.svg";
                try
                {
                    // Ensure the directory exists
                    string directory = Path.GetDirectoryName(outputPath);
                    if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                    {
                        Directory.CreateDirectory(directory);
                    }

                    using (FileStream fileOut = new FileStream(outputPath, FileMode.Create, FileAccess.Write))
                    {
                        svgDoc.Save(fileOut);
                    }

                    Console.WriteLine($"SVG with SMIL animation saved to: {outputPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to save SVG file: {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
