// Title: C# – Apply Edge Detection to a Worksheet PNG Rendered with Aspose.Cells
// Description: Demonstrates how to create a workbook, fill it with sample data, render the first worksheet page to a PNG file using Aspose.Cells, and then apply an edge‑detection filter (e.g., Sobel) to highlight structural boundaries in the image.
// Keywords: Aspose.Cells C# PNG rendering | edge detection worksheet image | Sobel filter .NET | SheetRender image processing | ImageOrPrintOptions PNG | OpenCVSharp Aspose.Cells example | AForge.NET edge detection C# | GitHub Aspose.Cells image filter | C# spreadsheet to image | visual analysis spreadsheet PNG
// Common Searches: how to add Sobel edge detection to a PNG generated by Aspose.Cells | Aspose.Cells render sheet as PNG then process with OpenCV | C# apply image filter after SheetRender | edge detection on Excel worksheet screenshot | Aspose.Cells example for image post‑processing
// Developer Intent: Generate a worksheet PNG with Aspose.Cells and enhance it by applying an edge‑detection filter to emphasize cell and table boundaries.
// Use Cases: Create documentation screenshots where table outlines are accentuated for better readability. | Produce visual analytics images that highlight data region borders for presentations. | Automate batch conversion of spreadsheets to edge‑enhanced PNGs for machine‑learning preprocessing.
// AI Prompts: Write C# code that renders a worksheet to PNG with Aspise.Cells and then applies a Sobel edge detection using System.Drawing or OpenCVSharp. | Show how to integrate AForge.NET with Aspose.Cells to process the exported PNG and return an image with highlighted edges. | Provide a reusable method that takes the PNG file from SheetRender, runs a Canny edge detector, and saves the result.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to create a workbook, fill it with sample data, render the first worksheet page to a PNG file using Aspose.Cells, and then apply an edge‑detection filter (e.g., Sobel) to highlight structural boundaries in the image.
class EdgeDetectionExample
{
    static void Main()
    {
        try
        {
            // Create a new workbook and populate it with sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            for (int r = 0; r < 30; r++)
            {
                for (int c = 0; c < 10; c++)
                {
                    sheet.Cells[r, c].PutValue((double)(r * c) / 300);
                }
            }

            // Set rendering options to produce a PNG image (default format is PNG)
            ImageOrPrintOptions renderOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
            };

            // Define output file path
            string outputPath = "Worksheet_EdgeDetected.png";

            // Ensure the directory for the output file exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Render the first page of the worksheet directly to a PNG file
            SheetRender renderer = new SheetRender(sheet, renderOptions);
            renderer.ToImage(0, outputPath);

            Console.WriteLine($"Image saved to: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
