// Title: Apply custom CSS styling to <path> elements in an SVG exported from an Aspose.Cells worksheet using C#
// AI Prompts: Generate C# code that creates a workbook, exports the first worksheet page to SVG with Aspose.Cells, and injects a <style> block defining a CSS class for path elements. | Write a C# routine that reads the exported SVG file, adds a CSS class attribute to every <path> tag using regular expressions, and saves the updated SVG. | Show how to change the stroke color and width in the injected CSS definition to customize the appearance of paths in the SVG. | Explain how to verify that the custom CSS class has been applied to all path elements in the resulting SVG file.
// Common Searches: c# add css class to all path tags in svg generated by aspose.cells | how to inject stylesheet into aspose.cells exported svg file | customize stroke color of chart lines in svg output from Aspose.Cells | regex replace to add class attribute to svg path elements in .net | modify exported svg from Aspose.Cells to include custom CSS
// Tags: Aspose.Cells SVG export with embedded CSS | C# regex to add class attribute to SVG path | custom CSS class for SVG path elements | modify Aspose.Cells generated SVG styling | apply stroke styling to worksheet SVG

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Rendering;   // Required for ImageOrPrintOptions and SheetRender

namespace AsposeCellsSvgStyling
{
    // The program creates a workbook, populates sample data, exports the first worksheet page to SVG using Aspose.Cells, injects a <style> block that defines a .customPath CSS class, adds that class to every <path> element via regular expressions, and saves the styled SVG file.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // 1. Create a new workbook and add some sample data
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Month");
                sheet.Cells["B1"].PutValue("Sales");
                sheet.Cells["A2"].PutValue("Jan");
                sheet.Cells["B2"].PutValue(1200);
                sheet.Cells["A3"].PutValue("Feb");
                sheet.Cells["B3"].PutValue(1500);
                sheet.Cells["A4"].PutValue("Mar");
                sheet.Cells["B4"].PutValue(1800);

                // 2. Export the worksheet to SVG format
                string svgPath = "Worksheet.svg";

                ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
                {
                    SaveFormat = SaveFormat.Svg   // Export as SVG
                };

                SheetRender sheetRender = new SheetRender(sheet, imgOptions);
                // Export the first page (page index 0) of the worksheet
                sheetRender.ToImage(0, svgPath);

                // Ensure the SVG file was created before attempting to read it
                if (!File.Exists(svgPath))
                    throw new FileNotFoundException("SVG file was not generated.", svgPath);

                // 3. Load the generated SVG content
                string svgContent = File.ReadAllText(svgPath);

                // 4. Define CSS styling that will be applied to all <path> elements
                string css = @"
    <style type=""text/css"">
        .customPath {
            stroke: #FF0000;          /* Red outline */
            stroke-width: 2;          /* Thicker line */
            fill: none;               /* No fill */
        }
    </style>";

                // 5. Insert the CSS block right after the opening <svg> tag
                svgContent = Regex.Replace(svgContent, @"(<svg[^>]*>)", "$1" + css, RegexOptions.IgnoreCase);

                // 6. Add the CSS class to every <path> element (preserve existing attributes)
                svgContent = Regex.Replace(svgContent,
                    @"<path\b([^>]*)>",
                    "<path class=\"customPath\" $1>",
                    RegexOptions.IgnoreCase);

                // 7. Save the modified SVG back to file
                File.WriteAllText(svgPath, svgContent);

                Console.WriteLine("SVG exported and styled successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
