// Title: Apply a 45-degree CSS rotate transform to an SVG chart generated with Aspose.Cells in C#
// AI Prompts: Generate C# code that creates a column chart with Aspose.Cells, renders it as SVG, and wraps the SVG content in a <g> element using a rotate(45) transform. | Write a method that takes the SVG stream from Aspose.Cells, inserts a configurable CSS rotate transform around the chart, and saves the modified file. | Show how to locate the opening <svg> tag in the Aspose.Cells output, prepend a <g transform="rotate(...)"> element, and close it correctly in C#.
// Common Searches: how to add a rotate(45) transform to an SVG chart generated by Aspose.Cells using C# | C# Aspose.Cells export chart as SVG and apply CSS rotation | modify Aspose.Cells SVG output to rotate the chart element | insert <g transform> into SVG produced by Aspose.Cells in .NET
// Tags: Aspose.Cells rotate SVG chart | C# inject CSS transform into SVG | render column chart to SVG with Aspose.Cells | modify generated SVG for rotation in .NET | wrap SVG body in <g> element

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// Creates a column chart in a workbook, renders it to SVG using Aspose.Cells, injects a <g transform="rotate(45)"> wrapper around the SVG body, and saves the rotated chart as RotatedChart.svg.
class SvgChartRotateExample
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["B4"].PutValue(30);

            // Add a column chart
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Set options for SVG rendering
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                // Export as SVG
                SaveFormat = SaveFormat.Svg
            };

            using (MemoryStream svgStream = new MemoryStream())
            {
                // Render the chart to the memory stream as SVG
                chart.ToImage(svgStream, imgOptions);
                string svgContent = Encoding.UTF8.GetString(svgStream.ToArray());

                // Insert a <g> element with a rotate transform (45 degrees)
                int svgTagEnd = svgContent.IndexOf('>');
                if (svgTagEnd > -1)
                {
                    string header = svgContent.Substring(0, svgTagEnd + 1);
                    string body = svgContent.Substring(svgTagEnd + 1);
                    string rotatedBody = "\n<g transform=\"rotate(45)\">\n" + body + "\n</g>\n";
                    string rotatedSvg = header + rotatedBody;

                    // Save the modified SVG to a file
                    File.WriteAllText("RotatedChart.svg", rotatedSvg, Encoding.UTF8);
                    Console.WriteLine("SVG chart saved with 45-degree rotation as RotatedChart.svg");
                }
                else
                {
                    Console.WriteLine("Failed to locate <svg> tag in the generated content.");
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
