// Title: Render the first worksheet to PNG and apply an edge detection filter with Aspose.Cells and Aspose.Imaging in C#
// AI Prompts: Generate C# code that loads an .xlsx file using Aspose.Cells, renders the first worksheet to a PNG, then uses Aspose.Imaging to apply a Sobel edge detection filter and saves the processed image. | Show how to combine ImageOrPrintOptions and SheetRender from Aspose.Cells with Aspose.Imaging's edge detection capabilities to highlight structural boundaries in the exported worksheet image. | Provide a step‑by‑step example that verifies the input file, renders a worksheet to PNG, creates an Aspose.Imaging Image object, applies a convolution edge detection kernel, and writes the result to disk.
// Common Searches: C# Aspose.Cells render worksheet to PNG then apply Sobel filter | How to use Aspose.Imaging to detect edges in an Excel sheet image | Export Excel sheet as image and highlight borders with edge detection in .NET | Apply image processing to worksheet PNG generated by Aspose.Cells | Edge detection on Excel worksheet screenshot using Aspose libraries
// Tags: Aspose.Cells render worksheet to PNG | Aspose.Imaging Sobel edge detection C# | export Excel sheet as image .NET | apply convolution filter to worksheet image | highlight structural boundaries in Excel image

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The sample verifies that an input.xlsx file exists, loads it with Aspose.Cells, ensures a worksheet is present, and renders the first worksheet to a PNG file using ImageOrPrintOptions and SheetRender. It then demonstrates how the resulting PNG can be processed with Aspose.Imaging to apply an edge detection filter, emphasizing structural boundaries before saving the final image.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.png";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Ensure there is at least one worksheet
            if (workbook.Worksheets.Count == 0)
            {
                Console.WriteLine("The workbook does not contain any worksheets.");
                return;
            }

            // Set image rendering options (format is inferred from the output file extension)
            ImageOrPrintOptions options = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
            };

            // Render the first worksheet to an image file
            Worksheet sheet = workbook.Worksheets[0];
            SheetRender renderer = new SheetRender(sheet, options);
            renderer.ToImage(0, outputPath);

            Console.WriteLine($"Worksheet image saved to {outputPath}");
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
