// Title: Render an Excel worksheet to PNG and convert the result to a grayscale image using Aspose.Cells for .NET
// AI Prompts: Write C# code that uses Aspose.Cells to render a worksheet as a PNG file and then applies a grayscale filter to the saved image using System.Drawing. | Show how to configure ImageOrPrintOptions for PNG export and demonstrate a method to transform the exported image to monochrome in .NET. | Provide a reusable function that takes a rendered worksheet PNG path and returns a black‑and‑white version without altering the original workbook.
// Common Searches: Aspose.Cells export worksheet to PNG and make it black and white in C# | C# convert rendered Excel sheet image to grayscale after saving | How to apply a grayscale filter to an image generated by Aspose.Cells | ImageOrPrintOptions PNG rendering then System.Drawing grayscale conversion | Create monochrome Excel sheet screenshot using Aspose.Cells .NET
// Tags: Aspose.Cells PNG export with ImageOrPrintOptions | grayscale conversion of rendered worksheet image | post‑process Excel sheet PNG using System.Drawing | C# monochrome image generation from Excel | one page per sheet PNG rendering Aspose.Cells | convert PNG to black and white .NET

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example creates a workbook, adds sample data, configures ImageOrPrintOptions to render the first worksheet as a PNG file, saves the image, and then demonstrates how to load that PNG and apply a grayscale filter using .NET image‑processing APIs.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Text");
            sheet.Cells["B2"].PutValue(12345);
            sheet.Cells["C3"].PutValue(DateTime.Now);

            // Set image rendering options (one page per sheet)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
                // Additional options such as grayscale can be set if supported by the library version
            };

            // Render the worksheet to a PNG file
            SheetRender renderer = new SheetRender(sheet, imgOptions);
            string pngPath = "worksheet.png";

            // Ensure any existing file is removed before rendering
            if (File.Exists(pngPath))
            {
                File.Delete(pngPath);
            }

            renderer.ToImage(0, pngPath); // page index 0

            // Verify that the PNG file was created
            if (!File.Exists(pngPath))
                throw new FileNotFoundException("Rendered PNG file not found.", pngPath);

            Console.WriteLine($"Worksheet rendered successfully to '{pngPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
