// Title: Rotate an Aspose.Cells SVG Chart 45° with a CSS Transform in C#
// Description: Creates a workbook, adds sample data, generates a line chart, renders it to SVG, injects a CSS rotate(45) attribute into the <g id="chart"> element, and saves the rotated SVG file.
// Keywords: Aspose.Cells | C# SVG chart | CSS rotate transform | 45 degree rotation | modify Aspose.Cells SVG | chart group transform | .NET chart to SVG | programmatic SVG manipulation | line chart SVG | Aspose.Cells example
// Common Searches: rotate svg chart aspose.cells c# | add css transform to aspose.cells svg output | how to tilt an aspose.cells chart 45 degrees | c# inject rotate attribute into svg <g> element | aspnet modify svg generated by Aspose.Cells | github aspose.cells svg rotate demo | apply css rotate to chart group in svg
// Developer Intent: Insert a CSS rotate(45) attribute into the <g id="chart"> element of an SVG chart produced by Aspose.Cells using C#.
// Use Cases: Display a chart diagonally in a web dashboard without altering the original data. | Batch‑process multiple charts to a uniform 45° tilt before embedding them in reports. | Create stylized infographics where chart graphics need a consistent angular orientation.
// AI Prompts: Write C# code that generates a line chart with Aspose.Cells, renders it to SVG, and adds a rotate(45) CSS transform to the chart group. | Show how to locate the <g id="chart"> element in the SVG string returned by Aspose.Cells and inject any CSS transform attribute. | Explain how to generalize SVG post‑processing for Aspose.Cells charts to apply scaling, rotation, or translation via CSS.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

namespace AsposeCellsSvgRotateDemo
{
    // Creates a workbook, adds sample data, generates a line chart, renders it to SVG, injects a CSS rotate(45) attribute into the <g id="chart"> element, and saves the rotated SVG file.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (lifecycle create)
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue("Month");
            sheet.Cells["A2"].PutValue("Jan");
            sheet.Cells["A3"].PutValue("Feb");
            sheet.Cells["A4"].PutValue("Mar");
            sheet.Cells["B1"].PutValue("Sales");
            sheet.Cells["B2"].PutValue(1200);
            sheet.Cells["B3"].PutValue(1500);
            sheet.Cells["B4"].PutValue(1800);

            // Add a line chart
            int chartIndex = sheet.Charts.Add(ChartType.Line, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.SetChartDataRange("A1:B4", true);

            // Prepare SVG rendering options
            SvgImageOptions svgOptions = new SvgImageOptions();

            // Render chart to SVG stored in a memory stream
            using (MemoryStream svgStream = new MemoryStream())
            {
                chart.ToImage(svgStream, svgOptions);
                svgStream.Position = 0;

                // Read SVG content as text
                string svgContent = new StreamReader(svgStream, Encoding.UTF8).ReadToEnd();

                // Insert CSS rotate transform (45 degrees) on the main <g> element that holds the chart graphics.
                // The Aspose.Cells SVG output wraps chart drawing inside a <g id="chart"> element.
                // We'll add a transform attribute to this group.
                string transformedSvg = svgContent.Replace("<g id=\"chart\"", "<g id=\"chart\" transform=\"rotate(45)\"");

                // Save the modified SVG to a file (lifecycle save)
                File.WriteAllText("RotatedChart.svg", transformedSvg, Encoding.UTF8);
            }

            Console.WriteLine("SVG chart saved with 45-degree CSS rotation as RotatedChart.svg");
        }
    }
}
