// Title: C# – Apply custom CSS to SVG <path> elements generated by Aspose.Cells
// Description: Create a workbook, add a line shape, render the worksheet to SVG with SvgImageOptions, inject a <style> block, assign a custom CSS class to every <path>, and save the styled SVG file using Aspose.Cells.
// Keywords: Aspose.Cells SVG styling | C# inject CSS into SVG | SvgImageOptions CssPrefix | custom CSS class for SVG path | Aspose.Cells render worksheet to SVG | modify SVG output Aspose.Cells | line shape SVG path styling
// Common Searches: how to add CSS to SVG paths exported by Aspose.Cells C# | inject custom style block into Aspose.Cells SVG output | change stroke color of line shape in Aspose.Cells SVG | apply class attribute to all <path> elements in Aspose.Cells generated SVG | Aspose.Cells SvgImageOptions custom CSS example
// Developer Intent: Add a custom CSS class to every <path> element in an SVG produced by Aspose.Cells to control stroke, fill, and other visual properties.
// Use Cases: Uniformly style line shapes (e.g., red 2 px stroke) across exported SVG worksheets. | Inject a reusable CSS block after the <svg> tag for theming without modifying the workbook. | Automate SVG post‑processing in a .NET pipeline to meet corporate branding guidelines.
// AI Prompts: Generate C# code that renders an Aspose.Cells worksheet to SVG, inserts a <style> block after the opening <svg> tag, and adds a custom class to all <path> elements. | Show how to use SvgImageOptions.CssPrefix and then replace <path> tags with a class attribute while preserving existing attributes. | Explain step‑by‑step how to customize stroke and fill of SVG paths exported from Aspose.Cells using injected CSS.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;
using Aspose.Cells.Rendering;

namespace AsposeCellsSvgStylingDemo
{
    // Create a workbook, add a line shape, render the worksheet to SVG with SvgImageOptions, inject a <style> block, assign a custom CSS class to every <path>, and save the styled SVG file using Aspose.Cells.
    class Program
    {
        static void Main()
        {
            try
            {
                // 1. Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // 2. Populate some sample data (optional, just to have content)
                sheet.Cells["A1"].PutValue("Month");
                sheet.Cells["A2"].PutValue("Jan");
                sheet.Cells["A3"].PutValue("Feb");
                sheet.Cells["A4"].PutValue("Mar");

                sheet.Cells["B1"].PutValue("Sales");
                sheet.Cells["B2"].PutValue(120);
                sheet.Cells["B3"].PutValue(210);
                sheet.Cells["B4"].PutValue(150);

                // 3. Add a simple line shape – this will be rendered as an SVG <path>
                //    Parameters: shape type, start row, start column, end row, end column, width, height
                sheet.Shapes.AddAutoShape(AutoShapeType.Line, 5, 5, 5, 6, 200, 0);

                // 4. Configure SVG rendering options
                SvgImageOptions svgOptions = new SvgImageOptions
                {
                    // Prefix that will be added to generated CSS class names
                    CssPrefix = "custom-",
                    // Ensure the output format is SVG
                    ImageType = ImageType.Svg,
                    // Fit the generated SVG to the viewport (optional)
                    FitToViewPort = true
                };

                // 5. Render the worksheet to an in‑memory SVG stream
                SheetRender renderer = new SheetRender(sheet, svgOptions);
                using (MemoryStream svgStream = new MemoryStream())
                {
                    renderer.ToImage(0, svgStream);
                    svgStream.Position = 0;

                    // 6. Read the SVG content as text
                    string svgContent = new StreamReader(svgStream).ReadToEnd();

                    // 7. Define custom CSS that will style all path elements
                    //    The class name uses the CssPrefix defined above
                    string customCss = @".custom-path { stroke:#FF0000; stroke-width:2; fill:none; }";

                    // 8. Insert the CSS block right after the opening <svg> tag
                    int svgTagEnd = svgContent.IndexOf('>');
                    if (svgTagEnd > -1)
                    {
                        svgContent = svgContent.Insert(svgTagEnd + 1,
                            $"\n<style type=\"text/css\">\n{customCss}\n</style>\n");
                    }

                    // 9. Apply the custom CSS class to every <path> element
                    //    This simple replace adds the class attribute if it does not already exist
                    svgContent = svgContent.Replace("<path ", "<path class=\"custom-path\" ");

                    // 10. Save the modified SVG to a file
                    string outputPath = "styled_worksheet.svg";
                    File.WriteAllText(outputPath, svgContent);

                    Console.WriteLine($"SVG worksheet saved with custom path styling to: {outputPath}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
