// Title: Rotate an exported SVG chart 45 degrees with CSS using Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that creates a column chart with Aspose.Cells, saves it as SVG, and injects a `transform: rotate(45deg);` style into the chart's `<g>` element. | Show how to load an SVG produced by Aspose.Cells in C#, locate the chart group by its id attribute, and append a CSS rotate transform to its existing style attribute using LINQ to XML. | Adapt the Aspose.Cells SVG export example to apply a 45‑degree rotation by modifying the SVG DOM after the workbook is saved.
// Common Searches: C# add CSS rotate transform to SVG chart generated by Aspose.Cells | Aspose.Cells export chart to SVG and rotate it 45 degrees using .NET | how to modify the style attribute of a chart group in an SVG saved from Aspose.Cells | apply CSS transform to Aspose.Cells SVG output in C#
// Tags: Aspose.Cells add CSS transform to SVG chart | C# rotate SVG element using LINQ to XML | modify SVG style attribute Aspose.Cells export | export chart as SVG with Aspose.Cells .NET | locate chart group element by id in SVG

using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Creates a column chart with Aspose.Cells, saves it as an SVG file, loads the SVG via LINQ to XML, finds the chart's <g> element by its id, appends `transform: rotate(45deg);` to the style attribute, and writes the modified SVG back to disk.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (lifecycle rule: create)
            Workbook workbook = new Workbook();

            // Populate sample data for the chart
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;
            cells["A1"].PutValue(10);
            cells["A2"].PutValue(20);
            cells["A3"].PutValue(30);
            cells["B1"].PutValue(15);
            cells["B2"].PutValue(25);
            cells["B3"].PutValue(35);

            // Add a column chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 15, 7);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("A1:A3", true);
            chart.NSeries[0].Name = "Series1";
            chart.NSeries.Add("B1:B3", true);
            chart.NSeries[1].Name = "Series2";

            // Save the workbook as an SVG file (lifecycle rule: save)
            string svgPath = "chart.svg";
            workbook.Save(svgPath, SaveFormat.Svg);

            // Ensure the SVG file exists before loading
            if (!File.Exists(svgPath))
                throw new FileNotFoundException($"SVG file not found: {svgPath}");

            // Load the generated SVG (lifecycle rule: load)
            XDocument svgDoc = XDocument.Load(svgPath);

            // Locate the first <g> element that represents the chart graphics.
            // Aspose.Cells typically assigns an id containing "chart" to this group.
            XElement? chartGroup = svgDoc.Root?
                .Descendants()
                .FirstOrDefault(e => e.Name.LocalName == "g" &&
                                     ((string?)e.Attribute("id"))?.Contains("chart") == true);

            if (chartGroup != null)
            {
                // Append a CSS rotate transform to the existing style attribute.
                string existingStyle = (string?)chartGroup.Attribute("style") ?? "";
                string rotateStyle = "transform: rotate(45deg);";
                chartGroup.SetAttributeValue("style", existingStyle + rotateStyle);
            }

            // Save the modified SVG back to the same file.
            svgDoc.Save(svgPath);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
