// Title: Apply Custom CSS to SVG <path> Elements After Exporting a Chart with Aspose.Cells (C#)
// Description: This example creates a workbook with a line chart, exports the worksheet to SVG using Aspose.Cells, injects a <style> block that defines a CSS class for <path> elements, adds the class to every <path> tag via regular expressions, and saves the updated SVG. The result is a chart SVG with a red stroke, 2 px width, and no fill applied globally.
// Keywords: Aspose.Cells | C# | SVG export | custom CSS | path styling | chart SVG | inject style | modify SVG | regular expressions | XmlDocument | XDocument
// Common Searches: How to add custom CSS to SVG paths generated by Aspose.Cells | Inject style block into Aspose.Cells chart SVG | Change stroke color of exported chart SVG in C# | Add class attribute to all <path> elements in Aspose.Cells SVG output | Apply CSS to Aspose.Cells SVG without re‑rendering
// Developer Intent: Add a custom CSS class to every <path> element in an SVG file produced by Aspose.Cells to control stroke, width, and fill of chart lines.
// Use Cases: Globally change the appearance of line‑chart SVG output (e.g., red stroke, thicker line) after export. | Programmatically insert a <style> element with a prefixed CSS class into the generated SVG and assign it to each <path> tag for consistent styling. | Update an exported SVG without re‑creating the chart, using either regex or XML DOM manipulation.
// AI Prompts: Generate C# code that reads an SVG created by Aspose.Cells, inserts a <style> element with a custom CSS rule for <path> elements, and adds the class attribute to each <path> tag. | Show how to use C# regular expressions to locate the <defs> section of an Aspose.Cells SVG and inject a CSS class definition for paths. | Provide an alternative solution using XmlDocument or XDocument to modify the SVG DOM and apply a CSS class to all <path> elements after export.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// This example creates a workbook with a line chart, exports the worksheet to SVG using Aspose.Cells, injects a <style> block that defines a CSS class for <path> elements, adds the class to every <path> tag via regular expressions, and saves the updated SVG. The result is a chart SVG with a red stroke, 2 px width, and no fill applied globally.
class SvgPathStylingDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Populate sample data for a chart (so the SVG will contain <path> elements)
            worksheet.Cells["A1"].PutValue("X");
            worksheet.Cells["B1"].PutValue("Y");
            worksheet.Cells["A2"].PutValue(1);
            worksheet.Cells["B2"].PutValue(10);
            worksheet.Cells["A3"].PutValue(2);
            worksheet.Cells["B3"].PutValue(20);

            // Add a line chart that uses the data
            int chartIndex = worksheet.Charts.Add(ChartType.Line, 5, 0, 20, 10);
            Chart chart = worksheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B3", true);
            chart.NSeries.CategoryData = "A2:A3";

            // Configure SVG rendering options (no CssClassPrefix in .NET API)
            SvgImageOptions svgOptions = new SvgImageOptions
            {
                FitToViewPort = true // Fit SVG to viewport
            };

            // Export the worksheet (including the chart) to an SVG file
            SheetRender renderer = new SheetRender(worksheet, svgOptions);
            string svgFilePath = "worksheet.svg";
            renderer.ToImage(0, svgFilePath);

            // Ensure the SVG file was created before attempting to read it
            if (!File.Exists(svgFilePath))
                throw new FileNotFoundException("SVG file was not generated.", svgFilePath);

            // Load the generated SVG content
            string svgContent = File.ReadAllText(svgFilePath);

            // Define a CSS class prefix (manual, since SvgImageOptions lacks this property)
            string cssClassPrefix = "mychart-";

            // Define a custom CSS rule that will be applied to all <path> elements
            // Example: red stroke, 2px width, no fill
            string customStyle = $".{cssClassPrefix}custom-path {{stroke:#FF0000;stroke-width:2;fill:none;}}";

            // Insert the style block into the SVG (preferably after <defs> if it exists)
            if (svgContent.Contains("<defs>"))
            {
                svgContent = Regex.Replace(svgContent, "(<defs>\\s*)", $"$1<style type=\"text/css\">{customStyle}</style>\n");
            }
            else
            {
                // If no <defs>, place the style block right after the opening <svg> tag
                svgContent = svgContent.Replace("<svg", $"<svg><style type=\"text/css\">{customStyle}</style>");
            }

            // Add the custom CSS class to every <path> element in the SVG
            svgContent = Regex.Replace(svgContent, "<path", $"<path class=\"{cssClassPrefix}custom-path\"");

            // Save the modified SVG back to the same file
            File.WriteAllText(svgFilePath, svgContent);

            Console.WriteLine("SVG exported and path elements styled with custom CSS.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
