// Title: Render an Excel worksheet to SVG and embed it inline in an email using MIME multipart/related with Aspose.Cells in C#
// AI Prompts: Write C# code that uses Aspose.Cells to convert a worksheet to an SVG stream and creates a multipart/related email with the SVG as an inline image. | Show how to build an AlternateView containing an HTML body that references a LinkedResource SVG (Content-ID) and send it via SmtpClient. | Extend the example to embed multiple worksheet SVGs in a single email, assigning each a unique Content-ID and updating the HTML accordingly.
// Common Searches: c# embed svg generated by Aspose.Cells into email body | how to send worksheet as inline SVG using System.Net.Mail multipart related | Aspose.Cells export worksheet to SVG memory stream and attach to email | sending Excel sheet image as inline SVG in HTML email C# | multipart/related email with linked SVG resource Aspose.Cells example
// Tags: Aspose.Cells worksheet to SVG conversion | C# email multipart/related with linked SVG | LinkedResource image/svg+xml in System.Net.Mail | SheetRender export SVG stream | inline SVG in HTML email C#

using System;
using System.IO;
using System.Net.Mail;
using System.Net.Mime;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Loads or creates an Excel workbook, renders the first worksheet to an SVG image in a MemoryStream using Aspose.Cells SheetRender, builds an HTML email that references the SVG via a Content-ID, adds the SVG as a LinkedResource with MIME type image/svg+xml in an AlternateView (multipart/related), and sends the message with SmtpClient.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";

            // Ensure the input workbook exists; create a simple one if missing
            Workbook workbook;
            if (File.Exists(inputPath))
            {
                workbook = new Workbook(inputPath);
            }
            else
            {
                workbook = new Workbook();
                Worksheet ws = workbook.Worksheets[0];
                ws.Cells["A1"].PutValue("Sample Data");
                workbook.Save(inputPath);
            }

            // Select the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Export the worksheet to SVG in memory
            using (MemoryStream svgStream = new MemoryStream())
            {
                // Configure SVG export options
                ImageOrPrintOptions options = new ImageOrPrintOptions
                {
                    SaveFormat = SaveFormat.Svg,          // Updated enum value
                    OnePagePerSheet = true
                };

                // Render the worksheet to the SVG stream
                SheetRender renderer = new SheetRender(sheet, options);
                renderer.ToImage(0, svgStream);
                svgStream.Position = 0; // Reset for reading

                // Prepare the email message
                MailMessage mail = new MailMessage
                {
                    From = new MailAddress("sender@example.com"),
                    Subject = "Worksheet as SVG"
                };
                mail.To.Add("recipient@example.com");

                // Define a Content-ID for the inline SVG
                const string contentId = "worksheetSvg";

                // HTML body referencing the inline SVG via CID
                string htmlBody = $"<html><body><h3>Worksheet Image</h3><img src=\"cid:{contentId}\" alt=\"Worksheet\"/></body></html>";

                // Create an alternate view for HTML
                AlternateView htmlView = AlternateView.CreateAlternateViewFromString(
                    htmlBody, null, MediaTypeNames.Text.Html);

                // Create a linked resource from the SVG stream
                LinkedResource svgResource = new LinkedResource(svgStream, "image/svg+xml")
                {
                    ContentId = contentId,
                    TransferEncoding = TransferEncoding.Base64
                };
                svgResource.ContentType.MediaType = "image/svg+xml";

                // Attach the linked resource to the HTML view
                htmlView.LinkedResources.Add(svgResource);
                mail.AlternateViews.Add(htmlView);

                // Send the email (configure SMTP settings as needed)
                using (SmtpClient smtp = new SmtpClient("smtp.example.com"))
                {
                    smtp.Credentials = new System.Net.NetworkCredential("username", "password");
                    smtp.Send(mail);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}
