// Title: Compress an SVG chart exported from Aspose.Cells using DeflateStream in C#
// AI Prompts: Generate C# code that renders a worksheet chart to SVG with Aspose.Cells and then compresses the SVG data using DeflateStream before saving or uploading. | Show how to write the compressed SVG byte array to a file and optionally stream it to a web service. | Adapt the example to use GZipStream instead of DeflateStream while preserving the Aspose.Cells rendering steps.
// Common Searches: how to use DeflateStream to compress SVG output from Aspose.Cells in a .NET application | C# example for exporting an Aspose.Cells chart to SVG and reducing its size for network transfer | compressing chart SVG generated by Aspose.Cells before uploading to a server | Aspose.Cells render chart to SVG then apply Deflate compression in memory | best practice for minimizing SVG payload size when using Aspose.Cells chart export
// Tags: deflate compression of Aspose.Cells SVG output | export chart to SVG with Aspose.Cells | compress SVG bytes using DeflateStream in C# | reduce network bandwidth for chart SVG | memory stream compression for Aspose.Cells rendering

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// The program creates a workbook, adds a column chart, renders the worksheet to SVG with Aspose.Cells, compresses the SVG using DeflateStream, and writes the compressed bytes to a .deflate file.
class Program
{
    static void Main()
    {
        try
        {
            // -------------------------------------------------
            // 1. Create a workbook and add sample data
            // -------------------------------------------------
            Workbook workbook = new Workbook();                     // create workbook (lifecycle rule)
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue(10);
            sheet.Cells["A2"].PutValue(20);
            sheet.Cells["A3"].PutValue(30);

            // -------------------------------------------------
            // 2. Add a chart that will be exported as SVG
            // -------------------------------------------------
            int chartIdx = sheet.Charts.Add(ChartType.Column, 5, 0, 15, 5);
            Chart chart = sheet.Charts[chartIdx];
            chart.NSeries.Add("A1:A3", true);

            // -------------------------------------------------
            // 3. Export the worksheet (including the chart) to SVG
            // -------------------------------------------------
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                SaveFormat = SaveFormat.Svg,
                OnePagePerSheet = true
            };

            using (MemoryStream svgStream = new MemoryStream())
            {
                // Render the worksheet to SVG and write into the memory stream
                SheetRender renderer = new SheetRender(sheet, imgOptions);
                renderer.ToImage(0, svgStream);                     // save (lifecycle rule)
                svgStream.Position = 0;                             // reset for reading

                // -------------------------------------------------
                // 4. Compress the SVG data using Deflate algorithm
                // -------------------------------------------------
                using (MemoryStream compressedStream = new MemoryStream())
                {
                    using (DeflateStream deflate = new DeflateStream(compressedStream, CompressionLevel.Optimal, true))
                    {
                        svgStream.CopyTo(deflate);
                    }

                    // Get the compressed byte array
                    byte[] compressedSvg = compressedStream.ToArray();

                    // -------------------------------------------------
                    // 5. Example: write compressed data to a file (or upload)
                    // -------------------------------------------------
                    File.WriteAllBytes("ChartCompressed.deflate", compressedSvg);
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
