// Title: C# – DeflateStream compression of Aspose.Cells chart SVG before upload
// Description: Generates a workbook, adds sample data, creates a column chart, renders the chart to SVG with Aspose.Cells, compresses the SVG using .NET DeflateStream (optimal level), and saves the compressed payload to a .deflate file ready for transmission.
// Keywords: Aspose.Cells | C# chart SVG | DeflateStream | SVG compression .NET | reduce bandwidth | chart image optimization | Aspose.Cells render SVG | compress SVG before upload | Deflate algorithm C# | Aspose.Cells example
// Common Searches: How to compress an SVG chart generated by Aspose.Cells in C# | DeflateStream example for Aspose.Cells chart output | Reduce size of Aspose.Cells SVG before uploading | C# code to zip SVG from Aspose.Cells chart | Aspose.Cells render chart to SVG and compress
// Developer Intent: Compress the SVG output of an Aspose.Cells chart with the Deflate algorithm to lower file size for network transfer.
// Use Cases: Create a workbook, add data, render a column chart to SVG, then compress the SVG for API upload. | Store chart graphics in a compressed .deflate file to save storage and bandwidth. | Integrate SVG compression into a CI pipeline that generates reports with Aspose.Cells.
// AI Prompts: Show C# code that renders an Aspose.Cells chart to SVG and returns a compressed byte array using DeflateStream. | Generate a snippet that uploads the compressed SVG directly to a REST endpoint with HttpClient. | Explain how to decompress the .deflate file back to SVG in a .NET application.

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;

// Generates a workbook, adds sample data, creates a column chart, renders the chart to SVG with Aspose.Cells, compresses the SVG using .NET DeflateStream (optimal level), and saves the compressed payload to a .deflate file ready for transmission.
class SvgChartCompressionDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["A3"].PutValue("Banana");
            sheet.Cells["A4"].PutValue("Cherry");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["B3"].PutValue(45);
            sheet.Cells["B4"].PutValue(25);

            // Add a column chart
            int chartIdx = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
            Chart chart = sheet.Charts[chartIdx];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Configure SVG rendering options (no ImageFormat property needed)
            SvgImageOptions svgOpts = new SvgImageOptions
            {
                FitToViewPort = true
            };

            // Render the chart to an SVG file
            string svgPath = "chart.svg";
            chart.ToImage(svgPath, svgOpts);

            // Ensure the SVG file was created before reading
            if (!File.Exists(svgPath))
                throw new FileNotFoundException("SVG file was not generated.", svgPath);

            // Read the generated SVG bytes
            byte[] svgBytes = File.ReadAllBytes(svgPath);

            // Compress the SVG using Deflate algorithm
            byte[] compressedBytes;
            using (MemoryStream ms = new MemoryStream())
            {
                using (DeflateStream ds = new DeflateStream(ms, CompressionLevel.Optimal, leaveOpen: true))
                {
                    ds.Write(svgBytes, 0, svgBytes.Length);
                }
                compressedBytes = ms.ToArray();
            }

            // Save the compressed data to a file (demo purpose)
            File.WriteAllBytes("chart.deflate", compressedBytes);

            // Save the workbook
            workbook.Save("ChartWorkbook.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
