// Title: Compress Excel-to-TIFF conversion with GZip using Aspose.Cells in C#
// AI Prompts: Generate C# code that loads an .xlsx file with Aspose.Cells, saves it as a TIFF, compresses the TIFF into a .gz archive using GZipStream, and deletes the temporary file. | Show a complete example that checks for the source Excel file, creates the output directory if missing, exports the workbook to a temporary TIFF, and then creates a .tiff.gz file. | Write a C# snippet that demonstrates how to use Aspose.Cells SaveFormat.Tiff together with GZipStream for efficient storage of Excel images.
// Common Searches: c# aspnet convert xlsx to tiff and gzip the result | using Aspose.Cells to export workbook as tiff then compress with GZipStream | how to create .tiff.gz file from an Excel workbook in .NET | compress temporary TIFF file generated by Aspose.Cells in C#
// Tags: Aspose.Cells export workbook to TIFF | C# GZipStream compress TIFF file | temporary TIFF file cleanup Aspose.Cells | create .tiff.gz archive in .NET | Excel to compressed TIFF conversion

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;

// The example loads an Excel workbook with Aspose.Cells, saves it as a temporary TIFF image, compresses the TIFF into a .tiff.gz file using GZipStream, ensures the output directory exists, and removes the intermediate TIFF file.
class Program
{
    static void Main()
    {
        try
        {
            // Path to the source Excel workbook
            string excelPath = "input.xlsx";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(excelPath))
            {
                Console.WriteLine($"Input file not found: {excelPath}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(excelPath);

            // Temporary TIFF file path
            string tempTiffPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".tiff");

            // Save workbook as TIFF (default options)
            workbook.Save(tempTiffPath, SaveFormat.Tiff);

            // Define the path for the compressed output
            string compressedPath = "output.tiff.gz";

            // Ensure the directory for the output file exists
            string outputDir = Path.GetDirectoryName(compressedPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Compress the TIFF file using GZip and write to the target file
            try
            {
                using (FileStream tiffFileStream = new FileStream(tempTiffPath, FileMode.Open, FileAccess.Read))
                using (FileStream outFileStream = new FileStream(compressedPath, FileMode.Create, FileAccess.Write))
                using (GZipStream gzipStream = new GZipStream(outFileStream, CompressionMode.Compress))
                {
                    tiffFileStream.CopyTo(gzipStream);
                }

                Console.WriteLine("TIFF conversion completed and compressed file saved.");
            }
            finally
            {
                // Clean up the temporary TIFF file
                if (File.Exists(tempTiffPath))
                {
                    File.Delete(tempTiffPath);
                }
            }
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
