// Title: Compress SVG Worksheet Rendered by Aspose.Cells with GZip in C# for Faster Network Transfer
// Description: This example creates a workbook, fills cells, renders the first worksheet to an SVG file using Aspose.Cells, reads the SVG bytes, compresses them with GZipStream into a memory buffer, saves the result as a .gz file, and displays original vs. compressed sizes.
// Keywords: Aspose.Cells SVG compression | C# GZipStream SVG | compress worksheet SVG | reduce SVG size network | Aspose.Cells render to SVG | gzip .gz file C# | vector graphics compression | bandwidth optimization
// Common Searches: how to gzip compress an SVG generated by Aspose.Cells in C# | compress Aspose.Cells worksheet SVG before sending over network | C# code to create .gz from SVG output | Aspose.Cells render worksheet to compressed SVG | reduce SVG file size with GZip in .NET
// Developer Intent: Use GZip to shrink the SVG output produced by Aspose.Cells so it can be transmitted or stored more efficiently.
// Use Cases: Transmit a compressed SVG representation of a spreadsheet to a web client, lowering bandwidth consumption. | Archive worksheet visualizations as .gz files to save storage while keeping vector quality intact. | Serve GZip‑compressed SVG directly from an ASP.NET endpoint without writing temporary files.
// AI Prompts: Write C# code that streams GZip‑compressed SVG directly to an HttpResponse in ASP.NET Core. | Show JavaScript to decompress a worksheet.svg.gz file in the browser and render the SVG. | Create a method that batches multiple worksheet SVG files into a single ZIP archive while preserving individual GZip streams.

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;
using Aspose.Cells.Drawing;
using Aspose.Cells.Rendering;

// This example creates a workbook, fills cells, renders the first worksheet to an SVG file using Aspose.Cells, reads the SVG bytes, compresses them with GZipStream into a memory buffer, saves the result as a .gz file, and displays original vs. compressed sizes.
class Program
{
    static void Main()
    {
        // Create a new workbook and access the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate the worksheet with sample data
        worksheet.Cells["A1"].PutValue("Item");
        worksheet.Cells["B1"].PutValue("Quantity");
        worksheet.Cells["A2"].PutValue("Apple");
        worksheet.Cells["B2"].PutValue(10);
        worksheet.Cells["A3"].PutValue("Orange");
        worksheet.Cells["B3"].PutValue(15);

        // Configure SVG rendering options
        SvgImageOptions svgOptions = new SvgImageOptions
        {
            FitToViewPort = true,
            ImageType = ImageType.Svg
        };

        // Render the worksheet to an SVG file
        string svgFilePath = "worksheet.svg";
        SheetRender renderer = new SheetRender(worksheet, svgOptions);
        renderer.ToImage(0, svgFilePath);

        // Read the generated SVG file into a byte array
        byte[] svgData = File.ReadAllBytes(svgFilePath);

        // Compress the SVG data using GZip
        byte[] gzData;
        using (MemoryStream compressedStream = new MemoryStream())
        {
            using (GZipStream gzip = new GZipStream(compressedStream, CompressionMode.Compress, true))
            {
                gzip.Write(svgData, 0, svgData.Length);
            }
            gzData = compressedStream.ToArray();
        }

        // Save the compressed data to a .gz file (ready for network transmission)
        string gzFilePath = "worksheet.svg.gz";
        File.WriteAllBytes(gzFilePath, gzData);

        // Output size information
        Console.WriteLine($"Original SVG size: {svgData.Length} bytes");
        Console.WriteLine($"Compressed GZip size: {gzData.Length} bytes");
    }
}
