// Title: Compress a worksheet rendered to SVG with GZip using Aspose.Cells in C#
// AI Prompts: Write C# code that loads an Excel workbook with Aspose.Cells, renders a chosen worksheet to SVG via SheetRender, and returns the SVG as a GZip‑compressed byte array ready for network transmission. | Demonstrate how to set ImageOrPrintOptions for SVG output, capture the SVG stream, and compress it with GZipStream while providing proper error handling.
// Common Searches: how to export an Excel worksheet to SVG and gzip it in C# | Aspose.Cells compress SVG output before sending over HTTP | C# GZipStream compress SheetRender SVG data | reduce size of SVG generated by Aspose.Cells for web transmission
// Tags: gzip compression of aspose cells svg output | sheetrender export worksheet to svg c# | imageorprintoptions saveformat svg aspose cells | compress svg stream with gzip in .net | network transmission of compressed svg from excel

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Loads an Excel file with Aspose.Cells, renders the first worksheet to SVG using SheetRender, then compresses the SVG stream with GZipStream and returns the compressed byte array for efficient network transfer.
public class SvgCompressor
{
    /// <param name="excelPath">Full path to the source Excel file.</param>
    /// <returns>GZip‑compressed SVG data.</returns>
    public static byte[] GetCompressedWorksheetSvg(string excelPath)
    {
        // Verify that the input file exists.
        if (!File.Exists(excelPath))
            throw new FileNotFoundException($"Excel file not found: {excelPath}");

        try
        {
            // Load the workbook from the specified file.
            Workbook workbook = new Workbook(excelPath);

            // Choose the worksheet to export (first worksheet).
            Worksheet sheet = workbook.Worksheets[0];

            // Ensure full sheet is exported.
            sheet.PageSetup.PrintArea = "";
            sheet.PageSetup.PrintGridlines = false;
            sheet.PageSetup.PrintHeadings = false;

            // Export the worksheet to SVG using SheetRender.
            using (MemoryStream svgStream = new MemoryStream())
            {
                ImageOrPrintOptions options = new ImageOrPrintOptions
                {
                    SaveFormat = SaveFormat.Svg,
                    OnePagePerSheet = true
                };

                SheetRender renderer = new SheetRender(sheet, options);
                renderer.ToImage(0, svgStream); // Render first page to SVG stream.

                // Reset the stream position before compression.
                svgStream.Position = 0;

                // Compress the SVG data using GZip.
                using (MemoryStream compressedStream = new MemoryStream())
                {
                    using (GZipStream gzip = new GZipStream(compressedStream, CompressionMode.Compress, true))
                    {
                        svgStream.CopyTo(gzip);
                    }

                    return compressedStream.ToArray();
                }
            }
        }
        catch (Exception ex)
        {
            // Wrap any exception for clearer diagnostics.
            throw new InvalidOperationException("Failed to compress worksheet SVG.", ex);
        }
    }

    // Simple entry point for testing the compressor.
    public static void Main(string[] args)
    {
        string excelPath = args.Length > 0 ? args[0] : "sample.xlsx";

        try
        {
            byte[] compressedSvg = GetCompressedWorksheetSvg(excelPath);
            Console.WriteLine($"Compressed SVG size: {compressedSvg.Length} bytes");
        }
        catch (Exception e)
        {
            Console.WriteLine($"Error: {e.Message}");
        }
    }
}
