// Title: C# – Render Aspose.Cells Workbook to Multi‑Page TIFF and Convert to PDF via a Third‑Party Converter
// Description: Demonstrates how to create a Workbook with Aspose.Cells, configure ImageOrPrintOptions for LZW‑compressed multi‑page TIFF output using WorkbookRender, save the TIFF, and then hand it off to an external library or service to produce a PDF file.
// Keywords: Aspose.Cells | WorkbookRender | C# | TIFF export | multi‑page TIFF | LZW compression | TIFF to PDF conversion | third‑party converter | ImageMagick | Ghostscript
// Common Searches: export Aspose.Cells workbook as multi‑page TIFF C# | convert TIFF generated by Aspose.Cells to PDF | C# example converting Excel to PDF via TIFF | WorkbookRender ToImage TIFF C# sample | third‑party TIFF to PDF library for .NET
// Developer Intent: Generate a TIFF from an Excel workbook with Aspose.Cells and then transform that TIFF into a PDF using an external conversion tool.
// Use Cases: Archive financial reports as high‑quality TIFF files and provide client‑ready PDFs. | Batch‑process Excel files: render each to TIFF with Aspose.Cells, then convert to PDF for distribution. | Integrate Aspose.Cells TIFF output with a custom PDF service that requires image input.
// AI Prompts: Write C# code that renders an Aspose.Cells workbook to a multi‑page TIFF and then uses ImageMagick to convert the TIFF to PDF. | Provide a method that streams the generated TIFF directly to a PDF conversion API without creating intermediate files on disk. | Show how to replace the placeholder ConvertTiffToPdf method with a real call to Ghostscript or PDFSharp for TIFF‑to‑PDF conversion.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;
using Aspose.Cells.Rendering;

// Demonstrates how to create a Workbook with Aspose.Cells, configure ImageOrPrintOptions for LZW‑compressed multi‑page TIFF output using WorkbookRender, save the TIFF, and then hand it off to an external library or service to produce a PDF file.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample data for TIFF to PDF conversion");

        // Configure image options for TIFF rendering
        ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
        {
            ImageType = ImageType.Tiff,                     // render as TIFF
            TiffCompression = TiffCompression.CompressionLZW,
            OnePagePerSheet = true
        };

        // Render the entire workbook to a multi‑page TIFF file
        string tiffPath = "workbook_output.tiff";
        WorkbookRender wbRender = new WorkbookRender(workbook, imgOptions);
        wbRender.ToImage(tiffPath); // uses WorkbookRender.ToImage(string)

        // Invoke a third‑party converter to turn the TIFF into PDF
        string pdfPath = "workbook_output.pdf";
        ConvertTiffToPdf(tiffPath, pdfPath);

        Console.WriteLine("TIFF generated and converted to PDF successfully.");
    }

    // Placeholder for the third‑party TIFF‑to‑PDF conversion logic
    static void ConvertTiffToPdf(string tiffFile, string pdfFile)
    {
        // Example: replace this with the actual library call, e.g.
        // ThirdPartyConverter.Convert(tiffFile, pdfFile);
        // For demonstration purposes we simply copy the file.
        File.Copy(tiffFile, pdfFile, overwrite: true);
    }
}
