// Title: Crop a rendered worksheet PNG to a custom rectangle with System.Drawing after using Aspose.Cells SheetRender in C#
// AI Prompts: Render the first worksheet to a PNG stream using Aspose.Cells SheetRender, load the stream into a System.Drawing.Bitmap, define a Rectangle for the desired crop area, and save the cropped bitmap as a new PNG file. | Refactor the sample to accept crop coordinates (x, y, width, height) as parameters, apply them to the bitmap, and write the resulting cropped image to a user‑specified output path. | Add validation for crop dimensions and ensure the output directory exists before writing the cropped PNG, providing clear error messages for invalid inputs.
// Common Searches: c# crop worksheet image generated by Aspose.Cells to a specific region | using System.Drawing to cut a rectangle from a PNG rendered by SheetRender | how to extract a portion of an Excel sheet image with Aspose.Cells and System.Drawing | Aspose.Cells render to memory stream then crop bitmap in C#
// Tags: Aspose.Cells SheetRender PNG cropping with System.Drawing | bitmap rectangle crop after Excel worksheet rendering | C# crop PNG from MemoryStream using System.Drawing | custom region extraction from rendered worksheet image | image cropping workflow Aspose.Cells to System.Drawing

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example loads an Excel workbook, renders the first worksheet to a PNG image via Aspose.Cells SheetRender into a MemoryStream, then demonstrates how to load that stream into a System.Drawing.Bitmap, define a custom rectangular area, crop the bitmap, and save the cropped image as a new PNG file, including handling of directories and basic error checking.
class Program
{
    static void Main()
    {
        try
        {
            // Path to the source workbook
            string workbookPath = @"C:\Path\To\YourWorkbook.xlsx";

            // Verify that the workbook file exists
            if (!File.Exists(workbookPath))
            {
                Console.WriteLine($"Workbook not found: {workbookPath}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(workbookPath);

            // Get the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Set image rendering options (default format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                // Uncomment and adjust resolution if needed
                // HorizontalResolution = 300,
                // VerticalResolution = 300
            };

            // Render the worksheet to an image stream
            SheetRender sr = new SheetRender(sheet, imgOptions);
            using (MemoryStream ms = new MemoryStream())
            {
                sr.ToImage(0, ms);
                ms.Position = 0; // Reset stream position

                // Output path for the rendered image
                string outputPath = @"C:\Path\To\RenderedImage.png";

                // Ensure the output directory exists
                string? outputDir = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the image stream to file
                using (FileStream fs = new FileStream(outputPath, FileMode.Create, FileAccess.Write))
                {
                    ms.CopyTo(fs);
                }

                Console.WriteLine($"Image saved to: {outputPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
