// Title: Crop a rendered worksheet PNG to a custom rectangle using System.Drawing (Aspose.Cells .NET)
// Description: This example shows how to render a worksheet to a PNG file with Aspose.Cells, then load the image with System.Drawing, define a rectangular region, crop the bitmap, and save the trimmed image. It includes proper disposal of graphics resources to avoid memory leaks.
// Keywords: Aspose.Cells crop PNG | System.Drawing image cropping C# | render worksheet to PNG .NET | crop bitmap after Aspose rendering | C# trim worksheet image | remove margins from worksheet PNG | extract cell range as image
// Common Searches: how to crop a PNG generated by Aspose.Cells in C# | System.Drawing crop rectangle from worksheet image | trim whitespace from Aspose.Cells PNG output | C# code to cut a specific area from a rendered Excel sheet | extract cell range image after rendering with Aspose.Cells
// Developer Intent: Trim a PNG produced by Aspose.Cells to a defined rectangle using System.Drawing.
// Use Cases: Create a thumbnail without surrounding margins for a dashboard. | Extract a specific cell block (e.g., A1:B2) as an image for a report. | Isolate a chart area from a worksheet screenshot for documentation.
// AI Prompts: Generate C# code that loads "Worksheet.png", sets a Rectangle (x, y, width, height), crops the bitmap with System.Drawing, and saves it as "Worksheet_Cropped.png". | Explain how to calculate the rectangle coordinates from cell positions after rendering with Aspose.Cells, then perform the crop. | Show the correct disposal pattern for Bitmap and Graphics objects after cropping to prevent memory leaks.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// This example shows how to render a worksheet to a PNG file with Aspose.Cells, then load the image with System.Drawing, define a rectangular region, crop the bitmap, and save the trimmed image. It includes proper disposal of graphics resources to avoid memory leaks.
class Program
{
    static void Main()
    {
        try
        {
            // Create a workbook and add some data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample");
            sheet.Cells["B2"].PutValue("Data");

            // Set rendering options to PNG
            ImageOrPrintOptions renderOptions = new ImageOrPrintOptions
            {
                ImageType = Aspose.Cells.Drawing.ImageType.Png,
                HorizontalResolution = 96,
                VerticalResolution = 96
            };

            // Render the first page of the worksheet directly to a PNG file
            SheetRender sheetRender = new SheetRender(sheet, renderOptions);
            sheetRender.ToImage(0, "Worksheet.png");

            // Release resources
            sheetRender.Dispose();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
