// Title: Crop a rendered worksheet PNG to a custom rectangle using System.Drawing in C# with Aspose.Cells
// AI Prompts: Render a worksheet to PNG with Aspose.Cells, load the file into System.Drawing.Bitmap, define a Rectangle, use Bitmap.Clone to extract the region, and save the cropped image. | Extend the sample to accept rectangle coordinates as input parameters, perform the crop on the rendered PNG without re‑rendering, and write the cropped result to a new file.
// Common Searches: C# how to crop a specific area from an Excel worksheet image generated by Aspose.Cells | using System.Drawing to cut out a rectangle from a PNG rendered by SheetRender | Aspose.Cells render worksheet to PNG then crop part of the image in .NET | programmatically define crop rectangle for Excel sheet screenshot in C# | save only selected cells as cropped PNG using Aspose.Cells and System.Drawing
// Tags: aspose.cells render worksheet png | system.drawing bitmap crop rectangle | crop excel worksheet image c# | png image cropping after aspose.cells render | define custom crop area for worksheet screenshot

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example creates a workbook, adds sample data, renders the first worksheet to a PNG file with SheetRender, then shows how to load that PNG using System.Drawing.Bitmap, specify a Rectangle, clone the region to obtain a cropped image, and save the result as a new file, all with proper exception handling.
class WorksheetImageCrop
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data (optional)
            sheet.Cells["A1"].PutValue("Header");
            sheet.Cells["A2"].PutValue(123);
            sheet.Cells["B2"].PutValue(456);
            sheet.Cells["C2"].PutValue(789);

            // Set up rendering options (default format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions();

            // Render the worksheet to an image file using SheetRender
            SheetRender renderer = new SheetRender(sheet, imgOptions);
            string outputPath = "RenderedWorksheet.png";

            try
            {
                // Render the first page (index 0) directly to a file
                renderer.ToImage(0, outputPath);
                Console.WriteLine($"Image saved to: {Path.GetFullPath(outputPath)}");
            }
            catch (Exception saveEx)
            {
                Console.WriteLine($"Failed to save image: {saveEx.Message}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
