// Title: Inject JavaScript to create hover tooltips in an SVG worksheet exported with Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that saves a worksheet as SVG using Aspose.Cells, then inserts a <script> element containing tooltip functions immediately after the opening <svg> tag. | Generate a C# regex routine that adds onmouseover and onmouseout attributes to each <rect> element in the exported SVG, using the cell address from the element's id as the tooltip text. | Create a hidden <text> element in the SVG and adjust the injected JavaScript to position and display this element when a cell rectangle is hovered.
// Common Searches: how to add mouseover tooltip to SVG cells generated by Aspose.Cells C# | Aspose.Cells export worksheet to SVG with interactive JavaScript | C# embed <script> tag into SVG file produced by Aspose.Cells | regex replace rect elements in SVG to include tooltip events using Aspose.Cells | display cell address as tooltip in SVG output from Aspose.Cells .NET
// Tags: Aspose.Cells SVG export with JavaScript injection | C# add mouseover events to SVG rect elements | interactive tooltip in SVG worksheet | regex modify SVG content Aspose.Cells | hidden text element for SVG tooltip

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Saving;

// The program creates a workbook, fills it with sample data, saves the first worksheet as an SVG file using Aspose.Cells, injects a JavaScript block that defines tooltip functions, adds a hidden <text> element as the tooltip container, and enhances each cell rectangle with onmouseover/onmouseout attributes (using regex) to display the cell address as a tooltip on hover.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            cells["A1"].PutValue("Product");
            cells["B1"].PutValue("Price");
            cells["A2"].PutValue("Apple");
            cells["B2"].PutValue(1.2);
            cells["A3"].PutValue("Banana");
            cells["B3"].PutValue(0.8);
            cells["A4"].PutValue("Cherry");
            cells["B4"].PutValue(2.5);

            // Save the worksheet as SVG into a memory stream using ImageSaveOptions
            using (MemoryStream svgStream = new MemoryStream())
            {
                ImageSaveOptions saveOptions = new ImageSaveOptions(SaveFormat.Svg)
                {
                    // Export only the first worksheet (one page per sheet)
                    ImageOrPrintOptions = { OnePagePerSheet = true }
                };
                workbook.Save(svgStream, saveOptions);

                // Convert the SVG stream to a string for manipulation
                string svgContent = Encoding.UTF8.GetString(svgStream.ToArray());

                // JavaScript to display a simple tooltip on hover
                string script = @"
                    <script type='text/ecmascript'>
                    <![CDATA[
                        function showTooltip(evt, text) {
                            var tooltip = document.getElementById('tooltip');
                            tooltip.textContent = text;
                            tooltip.setAttribute('x', evt.clientX + 10);
                            tooltip.setAttribute('y', evt.clientY + 10);
                            tooltip.setAttribute('visibility', 'visible');
                        }
                        function hideTooltip() {
                            var tooltip = document.getElementById('tooltip');
                            tooltip.setAttribute('visibility', 'hidden');
                        }
                    ]]>
                    </script>";

                // Insert the script right after the opening <svg> tag
                int insertPos = svgContent.IndexOf('>') + 1; // after the first '>'
                svgContent = svgContent.Insert(insertPos, script);

                // Add a <text> element that will act as the tooltip container
                string tooltipElement = @"
                    <text id='tooltip' visibility='hidden' font-family='Arial' font-size='12' fill='black' background='white' />
                ";
                // Insert the tooltip element before the closing </svg> tag
                int closeTagPos = svgContent.LastIndexOf("</svg>");
                svgContent = svgContent.Insert(closeTagPos, tooltipElement);

                // Enhance each cell rectangle with mouse events to trigger the tooltip
                Regex rectRegex = new Regex(@"<rect([^>]*?)>", RegexOptions.IgnoreCase);
                svgContent = rectRegex.Replace(svgContent, match =>
                {
                    string original = match.Value;
                    // Extract the cell address from the 'id' attribute if present (e.g., id='A1')
                    string idPattern = @"id=['""](?<addr>[A-Z]+\d+)['""]";
                    Match idMatch = Regex.Match(original, idPattern);
                    string tooltipText = idMatch.Success ? idMatch.Groups["addr"].Value : "Cell";

                    // Add mouseover and mouseout event handlers
                    string events = $" onmouseover=\"showTooltip(evt, '{tooltipText}')\" onmouseout=\"hideTooltip()\"";
                    // Insert events before the closing '>'
                    return original.Insert(original.Length - 1, events);
                });

                // Write the modified SVG to a file
                File.WriteAllText("InteractiveWorksheet.svg", svgContent, Encoding.UTF8);
            }

            Console.WriteLine("SVG file with interactive tooltips has been created.");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
