// Title: Inject JavaScript tooltip into an SVG file generated from an Excel worksheet using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that saves a workbook with Aspose.Cells as SVG, then inserts a <script> block containing tooltip functions and a hidden <text> element into the SVG markup. | Show how to use a regular expression in C# to add onmouseover and onmouseout attributes to all shape elements in the SVG produced by Aspose.Cells. | Demonstrate how to write the modified SVG string back to a file after embedding interactive JavaScript for hover tooltips.
// Common Searches: how to embed JavaScript in SVG exported from Excel with Aspose.Cells C# | add hover tooltip to SVG worksheet saved by Aspose.Cells .NET | inject script tag into Aspose.Cells SVG output using C# | regex to attach mouseover events to SVG shapes generated by Aspose.Cells | custom interactive features in SVG files created from workbooks with Aspose.Cells
// Tags: Aspose.Cells SVG export with embedded JavaScript | C# inject script tag into exported SVG | add mouseover tooltip to SVG shapes | modify SVG output using regex in .NET | hidden text element for SVG tooltip

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

// The example creates a workbook, populates cells, saves the first worksheet as SVG via Aspose.Cells, converts the SVG to a string, injects a <script> block with tooltip functions, adds a hidden <text> element for displaying the tooltip, uses a regex to attach onmouseover/onmouseout attributes to <rect> elements, and writes the enhanced SVG to a file.
class EmbedJavaScriptInSvg
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();                     // create
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Product");
        sheet.Cells["B1"].PutValue("Price");
        sheet.Cells["A2"].PutValue("Apple");
        sheet.Cells["B2"].PutValue(1.2);
        sheet.Cells["A3"].PutValue("Banana");
        sheet.Cells["B3"].PutValue(0.8);

        // Save the worksheet as SVG into a memory stream
        using (MemoryStream svgStream = new MemoryStream())
        {
            SvgSaveOptions svgOptions = new SvgSaveOptions(SaveFormat.Svg);
            workbook.Save(svgStream, svgOptions);               // save

            // Convert the SVG bytes to a string for manipulation
            string svgContent = Encoding.UTF8.GetString(svgStream.ToArray());

            // JavaScript code to show a custom tooltip on hover
            string script = @"
<script type=""text/ecmascript""><![CDATA[
function showTooltip(evt, text) {
    var tooltip = document.getElementById('tooltip');
    tooltip.textContent = text;
    tooltip.setAttribute('x', evt.clientX + 10);
    tooltip.setAttribute('y', evt.clientY + 10);
    tooltip.setAttribute('visibility', 'visible');
}
function hideTooltip() {
    var tooltip = document.getElementById('tooltip');
    tooltip.setAttribute('visibility', 'hidden');
}
]]></script>";

            // Tooltip text element (initially hidden)
            string tooltipElement = @"<text id=""tooltip"" visibility=""hidden"" font-family=""Arial"" font-size=""12"" fill=""black""></text>";

            // Insert the script just after the opening <svg> tag
            int svgTagEnd = svgContent.IndexOf('>') + 1;
            svgContent = svgContent.Insert(svgTagEnd, script + Environment.NewLine);

            // Insert the tooltip element before the closing </svg> tag
            int closeTagPos = svgContent.LastIndexOf("</svg>", StringComparison.Ordinal);
            svgContent = svgContent.Insert(closeTagPos, tooltipElement + Environment.NewLine);

            // Optionally, add mouse event attributes to existing shapes (example for all <rect> elements)
            // This demonstrates how to attach the tooltip functions; adjust selectors as needed.
            svgContent = System.Text.RegularExpressions.Regex.Replace(
                svgContent,
                @"<rect([^>]*?)>",
                m => $"<rect{m.Groups[1].Value} onmouseover=\"showTooltip(evt, 'Rectangle')\" onmouseout=\"hideTooltip()\">",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);

            // Write the modified SVG to a file
            File.WriteAllText("WorksheetWithTooltip.svg", svgContent, Encoding.UTF8);
        }
    }
}
