// Title: Add JavaScript Hover Tooltips to SVG Worksheets Generated by Aspose.Cells for .NET
// Description: This example shows how to create a workbook with Aspose.Cells, render a worksheet to SVG, and programmatically inject a <script> block that adds <title> elements to each text node, enabling native hover tooltips in the resulting SVG file.
// Keywords: Aspose.Cells SVG tooltip | C# embed JavaScript in SVG | interactive SVG from Excel | post‑process Aspose.Cells SVG | hover tooltip for SVG text
// Common Searches: how to add JavaScript to SVG generated by Aspose.Cells | C# tooltip on SVG worksheet cells | inject <title> tags into Aspose.Cells SVG output | make Excel SVG interactive with hover text | post‑processing Aspose.Cells SVG for web
// Developer Intent: Insert client‑side JavaScript into an SVG file produced by Aspose.Cells so that hovering over text elements displays tooltips.
// Use Cases: Create a sales‑report SVG that shows product details when the user hovers over each cell. | Enhance web‑based dashboards by adding lightweight, client‑side tooltips to SVG charts generated from Excel data. | Automate a build step that enriches Aspose.Cells SVG assets with custom scripts for interactive documentation.
// AI Prompts: Generate C# code that reads an Aspose.Cells SVG file and inserts a <script> element to add <title> tags to all <text> nodes for tooltip support. | Explain how to locate the correct insertion point for a JavaScript block when the SVG contains an XML declaration or DOCTYPE. | Show how to render a specific worksheet page to SVG using SvgImageOptions, then embed interactive JavaScript for browser display.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsSvgTooltipDemo
{
    // This example shows how to create a workbook with Aspose.Cells, render a worksheet to SVG, and programmatically inject a <script> block that adds <title> elements to each text node, enabling native hover tooltips in the resulting SVG file.
    class Program
    {
        static void Main()
        {
            try
            {
                // 1. Create a workbook and populate some sample data
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Product");
                sheet.Cells["B1"].PutValue("Sales");
                sheet.Cells["A2"].PutValue("Apple");
                sheet.Cells["B2"].PutValue(120);
                sheet.Cells["A3"].PutValue("Orange");
                sheet.Cells["B3"].PutValue(95);
                sheet.Cells["A4"].PutValue("Banana");
                sheet.Cells["B4"].PutValue(150);

                // 2. Set up SVG rendering options
                SvgImageOptions svgOptions = new SvgImageOptions
                {
                    FitToViewPort = true // make SVG fit the viewport
                    // No need to set ImageType; SvgImageOptions inherently produces SVG
                };

                // 3. Render the worksheet to an SVG file
                string svgPath = "worksheet.svg";
                SheetRender renderer = new SheetRender(sheet, svgOptions);
                renderer.ToImage(0, svgPath);

                // Ensure the SVG file was created before attempting to modify it
                if (!File.Exists(svgPath))
                {
                    Console.WriteLine($"Failed to generate SVG file at: {Path.GetFullPath(svgPath)}");
                    return;
                }

                // 4. Load the generated SVG, inject JavaScript for tooltips, and save it back
                string svgContent = File.ReadAllText(svgPath);

                // JavaScript that adds a <title> element (native SVG tooltip) to each text node
                string script = @"
<script type=""text/ecmascript""><![CDATA[
document.addEventListener('DOMContentLoaded', function () {
    var texts = document.querySelectorAll('text');
    texts.forEach(function (t) {
        var tooltip = document.createElementNS('http://www.w3.org/2000/svg', 'title');
        tooltip.textContent = t.textContent;
        t.appendChild(tooltip);
    });
});
]]></script>";

                // Insert the script right after the opening <svg> tag
                int insertPos = svgContent.IndexOf('>') + 1; // position after first '>'
                if (insertPos > 0 && insertPos < svgContent.Length)
                {
                    svgContent = svgContent.Insert(insertPos, script);
                }

                // Overwrite the original SVG with the modified content
                File.WriteAllText(svgPath, svgContent);

                Console.WriteLine($"SVG file with embedded JavaScript tooltips saved to: {Path.GetFullPath(svgPath)}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
