// Title: Encrypt a TIFF file generated from an Excel worksheet with AES‑256 using Aspose.Cells for .NET and store it in a protected folder
// AI Prompts: Write C# code that uses Aspose.Cells to render the first worksheet of an Excel workbook to a TIFF image, then encrypt the TIFF with AES‑256 CBC via CryptoStream, and save the encrypted file to a designated secure directory. | Show how to create a 256‑bit AES key and IV in C#, read a TIFF file into a byte array, encrypt the bytes using CryptoStream, and write the encrypted output to disk. | Provide a C# example that verifies the target secure folder exists, writes the encrypted TIFF there, and deletes the original unencrypted TIFF after successful encryption.
// Common Searches: aspnet encrypt tiff file generated by aspose.cells using aes 256 | c# render excel worksheet to tiff and then encrypt with aes cbc | how to store encrypted tiff in a secure folder with .net | remove original tiff after encryption asp.net example | aes encryption of image files produced by Aspose.Cells
// Tags: Aspose.Cells export to TIFF with AES protection | C# AES‑256 CBC encryption of byte arrays | secure folder storage for encrypted images .NET | CryptoStream usage for image encryption | cleanup of temporary files after encryption C#

using System;
using System.IO;
using System.Security.Cryptography;
using System.Drawing.Imaging;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The sample loads an Excel workbook, renders the first worksheet to a TIFF image using Aspose.Cells, reads the TIFF bytes, encrypts them with AES‑256 CBC via CryptoStream, writes the encrypted file to a protected directory, and optionally removes the original unencrypted TIFF.
class Program
{
    static void Main()
    {
        try
        {
            // Verify input workbook exists
            string inputPath = "input.xlsx";
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the source workbook
            Workbook workbook = new Workbook(inputPath);

            // Set image rendering options (default options are sufficient for TIFF when using .tiff extension)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions();

            // Render the first worksheet to a TIFF image
            SheetRender sheetRender = new SheetRender(workbook.Worksheets[0], imgOptions);
            string tiffPath = "output.tiff";

            // Ensure any previous TIFF is removed
            if (File.Exists(tiffPath))
                File.Delete(tiffPath);

            sheetRender.ToImage(0, tiffPath);

            // Read the generated TIFF bytes
            byte[] tiffBytes = File.ReadAllBytes(tiffPath);

            // AES encryption parameters (use a secure key/IV in production)
            byte[] aesKey = new byte[32]; // 256‑bit key
            byte[] aesIv = new byte[16];  // 128‑bit IV
            for (int i = 0; i < aesKey.Length; i++) aesKey[i] = (byte)i;
            for (int i = 0; i < aesIv.Length; i++) aesIv[i] = (byte)(i + 1);

            // Encrypt the TIFF bytes
            byte[] encryptedBytes;
            using (Aes aes = Aes.Create())
            {
                aes.Key = aesKey;
                aes.IV = aesIv;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;

                using (MemoryStream msEncrypt = new MemoryStream())
                using (CryptoStream cs = new CryptoStream(msEncrypt, aes.CreateEncryptor(), CryptoStreamMode.Write))
                {
                    cs.Write(tiffBytes, 0, tiffBytes.Length);
                    cs.FlushFinalBlock();
                    encryptedBytes = msEncrypt.ToArray();
                }
            }

            // Ensure the secure storage directory exists
            string secureDir = @"C:\SecureStorage";
            if (!Directory.Exists(secureDir))
                Directory.CreateDirectory(secureDir);

            // Store the encrypted TIFF in a secure location
            string securePath = Path.Combine(secureDir, "output_encrypted.tiff");
            File.WriteAllBytes(securePath, encryptedBytes);

            // Optionally, delete the unencrypted TIFF if no longer needed
            if (File.Exists(tiffPath))
                File.Delete(tiffPath);

            Console.WriteLine("TIFF exported and encrypted successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
