// Title: Export a specific Excel worksheet to a fixed-size SVG file without a viewBox attribute using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx workbook, sets the first worksheet to fit on one page, configures SvgSaveOptions to omit the viewBox element, and saves the output as a fixed-dimension SVG with Aspose.Cells. | Show how to use Aspose.Cells SvgSaveOptions in C# to export a selected worksheet to SVG with explicit width and height, ensuring the SVG canvas does not contain a viewBox attribute.
// Common Searches: how to remove viewBox from SVG generated by Aspose.Cells C# | Aspose.Cells export Excel sheet to SVG with fixed width and height | C# save worksheet as SVG without viewBox using SvgSaveOptions | fit Excel worksheet to single page when exporting to SVG Aspose.Cells | Aspose.Cells .NET generate fixed-size SVG from workbook
// Tags: Aspose.Cells SvgSaveOptions ExportToSvgWithoutViewBox | C# fixed-size SVG export from Excel | fit worksheet to single page Aspose.Cells | export selected worksheet to SVG Aspose.Cells | Aspose.Cells SVG save options for dimensions

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, selects the first worksheet, configures the page setup to fit the content on a single page, uses SvgSaveOptions to disable the viewBox attribute, and saves the worksheet as a fixed-size SVG file with Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        // Path to the source Excel file
        string inputPath = "input.xlsx";

        // Verify that the input file exists to avoid FileNotFoundException
        if (!File.Exists(inputPath))
        {
            Console.WriteLine($"Error: Input file not found at '{inputPath}'.");
            return;
        }

        try
        {
            // Load the workbook from the file system
            Workbook workbook = new Workbook(inputPath);

            // Select the worksheet you want to export (e.g., the first worksheet)
            Worksheet sheet = workbook.Worksheets[0];

            // Configure page setup to fit content on a single page
            sheet.PageSetup.FitToPagesWide = 1;
            sheet.PageSetup.FitToPagesTall = 1;

            // Path for the resulting SVG file
            string outputPath = "output.svg";

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the worksheet (or entire workbook) as SVG
            // Using SaveFormat.Svg ensures the output is an SVG file
            workbook.Save(outputPath, SaveFormat.Svg);

            Console.WriteLine($"Worksheet exported successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
