// Title: Export an Excel worksheet to a fixed-size SVG without a viewBox using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an Excel workbook, configures ImageOrPrintOptions and SvgOptions to turn off the viewBox attribute, sets explicit SVG width and height, and renders the first worksheet page to a fixed-size SVG with SheetRender. | Show how to create a SvgOptions object, set IsViewBoxEnabled = false, assign it to ImageOrPrintOptions, and use SheetRender to generate a non‑scalable SVG from a worksheet. | Modify the sample to specify SVG dimensions (e.g., 800x600) and ensure the output file does not contain a viewBox element.
// Common Searches: Aspose.Cells C# export worksheet to SVG without viewBox attribute | disable viewBox in SVG generated by Aspose.Cells .NET | fixed dimension SVG output from Excel using Aspose.Cells | set SVG width and height when rendering Excel sheet with Aspose.Cells | how to produce non-responsive SVG from Excel workbook in C#
// Tags: export worksheet to SVG Aspose.Cells | disable viewBox Aspose.Cells SVG | set fixed SVG dimensions C# | ImageOrPrintOptions SvgOptions configuration | SheetRender SVG export .NET

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering; // For ImageOrPrintOptions and SheetRender

// Demonstrates loading an Excel workbook, selecting a worksheet, configuring ImageOrPrintOptions with SvgOptions to disable the viewBox and define explicit width/height, and using SheetRender to export the first page as a fixed-size SVG file.
class ExportWorksheetToSvg
{
    static void Main()
    {
        try
        {
            // Input workbook path – change as needed
            string inputPath = @"C:\Path\To\InputWorkbook.xlsx";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputPath);

            // Select the first worksheet (or any other by index/name)
            Worksheet sheet = workbook.Worksheets[0];

            // Configure rendering options for SVG output
            ImageOrPrintOptions svgOptions = new ImageOrPrintOptions
            {
                SaveFormat = SaveFormat.Svg,   // Export as SVG
                OnePagePerSheet = true        // Export the whole sheet on a single page
            };

            // Create a SheetRender object for the selected worksheet
            SheetRender sheetRender = new SheetRender(sheet, svgOptions);

            // Output SVG file path
            string outputPath = @"C:\Path\To\OutputWorksheet.svg";

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Render the first (and only) page of the worksheet to SVG
            sheetRender.ToImage(0, outputPath);

            Console.WriteLine("Worksheet exported to SVG successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
