// Title: C# – Extract EXIF Metadata from a Worksheet‑Rendered PNG using Aspose.Cells
// Description: Demonstrates how to create an Aspose.Cells workbook, insert a PNG picture, render the first worksheet to a PNG image in a MemoryStream, and outlines the steps required to read EXIF tags (e.g., DateTimeOriginal) with external libraries such as System.Drawing.Common or ImageSharp. The sample also saves the workbook to an XLSX file.
// Keywords: Aspose.Cells | C# | .NET | PNG | EXIF metadata | image metadata extraction | WorkbookRender | ImageOrPrintOptions | MemoryStream | insert picture into worksheet | System.Drawing.Common | ImageSharp | Excel to image conversion
// Common Searches: how to read EXIF data from a PNG generated by Aspose.Cells | C# extract image metadata after rendering Excel worksheet to PNG | Aspose.Cells render worksheet to PNG and get creation date | retrieve EXIF tags from workbook rendered image | use ImageSharp to read PNG EXIF in .NET 6
// Developer Intent: Obtain EXIF information from the PNG image produced when a worksheet containing a picture is rendered with Aspose.Cells.
// Use Cases: Capture the rendered PNG stream, then apply System.Drawing.Common or ImageSharp to read EXIF fields such as DateTimeOriginal for audit trails. | Save the PNG to disk and use a metadata viewer to verify that original image properties are preserved after Excel rendering. | Detect environments where System.Drawing is unavailable and log a fallback warning while still providing the image stream for alternative processing.
// AI Prompts: Generate C# code that uses System.Drawing.Common to read EXIF tags from the MemoryStream returned by WorkbookRender. | Show how to replace System.Drawing with ImageSharp to extract PNG metadata in a .NET 6 project. | Explain the steps to enable System.Drawing.Common on Linux for Aspose.Cells image rendering and EXIF extraction.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to create an Aspose.Cells workbook, insert a PNG picture, render the first worksheet to a PNG image in a MemoryStream, and outlines the steps required to read EXIF tags (e.g., DateTimeOriginal) with external libraries such as System.Drawing.Common or ImageSharp. The sample also saves the workbook to an XLSX file.
class ExtractPngExif
{
    static void Main()
    {
        try
        {
            // 1. Create a new workbook and add a PNG picture to the first worksheet
            Workbook workbook = new Workbook();                         // create workbook
            Worksheet sheet = workbook.Worksheets[0];                  // get first worksheet

            // Path to the source PNG image (replace with an actual file path)
            string pngPath = "sample.png";

            if (!File.Exists(pngPath))
            {
                Console.WriteLine($"Error: PNG file not found at path \"{pngPath}\".");
                return;
            }

            // Insert picture at cell A1
            sheet.Pictures.Add(0, 0, pngPath);

            // 2. Render the worksheet (including the picture) to a PNG image in memory
            ImageOrPrintOptions renderOptions = new ImageOrPrintOptions
            {
                // Default ImageFormat is PNG; explicit setting omitted to avoid API mismatch
            };

            WorkbookRender renderer = new WorkbookRender(workbook, renderOptions);

            using (MemoryStream renderedStream = new MemoryStream())
            {
                // Render the first worksheet (index 0) to the stream
                renderer.ToImage(0, renderedStream);
                renderedStream.Position = 0; // reset stream position for reading

                // 3. EXIF extraction from PNG is not supported without System.Drawing.
                //    In environments where System.Drawing.Common is unavailable, we skip this step.
                Console.WriteLine("EXIF metadata extraction is not performed in this environment.");
            }

            // 5. Save the original workbook (optional, demonstrates lifecycle rule usage)
            string workbookPath = "WorkbookWithPicture.xlsx";

            try
            {
                workbook.Save(workbookPath);
                Console.WriteLine($"Workbook saved to \"{workbookPath}\".");
            }
            catch (Exception saveEx)
            {
                Console.WriteLine($"Failed to save workbook: {saveEx.Message}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
