// Title: Render a worksheet to PNG and display workbook built‑in properties as EXIF‑like information using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file, uses Aspose.Cells to render the first worksheet to a PNG image, and then prints the workbook's built‑in document properties such as author, title, and creation date. | Write a method that converts a specific worksheet to PNG with Aspose.Cells and extracts the workbook's metadata to emulate EXIF fields for the generated image.
// Common Searches: Aspose.Cells C# export first worksheet as PNG and read workbook built‑in document properties | how to get author and creation date from Excel after converting worksheet to PNG using Aspose.Cells | C# retrieve Excel built‑in properties for PNG image generated by Aspose.Cells | simulate EXIF metadata for worksheet PNG with Aspose.Cells document properties
// Tags: Aspose.Cells worksheet to PNG rendering | extract workbook built‑in document properties C# | simulate EXIF data from Excel image | C# Excel to PNG conversion with metadata | Aspose.Cells image export and property retrieval

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example loads an Excel workbook, renders the first worksheet to a PNG file using Aspose.Cells, verifies the image creation, and then prints various built‑in document properties (author, title, subject, keywords, comments, created date, last modified date) from the workbook, providing EXIF‑like metadata for the generated PNG.
class ExifExtraction
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string pngPath = "sheet.png";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: Input file \"{inputPath}\" not found.");
                return;
            }

            // Load the workbook
            Workbook workbook;
            try
            {
                workbook = new Workbook(inputPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading workbook: {ex.Message}");
                return;
            }

            // Set PNG export options (default format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                HorizontalResolution = 96,
                VerticalResolution = 96
            };

            // Render the first worksheet to a PNG image
            SheetRender sheetRender = new SheetRender(workbook.Worksheets[0], imgOptions);
            try
            {
                sheetRender.ToImage(0, pngPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error during image rendering: {ex.Message}");
                return;
            }

            // Verify that the PNG was created
            if (!File.Exists(pngPath))
            {
                Console.WriteLine($"Error: Failed to create PNG file \"{pngPath}\".");
                return;
            }

            // Output workbook built‑in document properties (as a substitute for PNG EXIF)
            Console.WriteLine("=== Workbook Built‑in Document Properties ===");
            Console.WriteLine($"Author: {workbook.BuiltInDocumentProperties["Author"]?.Value}");
            Console.WriteLine($"Title: {workbook.BuiltInDocumentProperties["Title"]?.Value}");
            Console.WriteLine($"Subject: {workbook.BuiltInDocumentProperties["Subject"]?.Value}");
            Console.WriteLine($"Keywords: {workbook.BuiltInDocumentProperties["Keywords"]?.Value}");
            Console.WriteLine($"Comments: {workbook.BuiltInDocumentProperties["Comments"]?.Value}");
            Console.WriteLine($"Created Time: {workbook.BuiltInDocumentProperties["Created Date"]?.Value}");
            Console.WriteLine($"Last Modified Time: {workbook.BuiltInDocumentProperties["Last Modified"]?.Value}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unexpected error: {ex.Message}");
        }
    }
}
