// Title: Generate an HTML <img> tag that references a PNG worksheet image rendered with Aspose.Cells in C#
// AI Prompts: Write C# code that uses Aspose.Cells to render a worksheet to a PNG file and then prints an HTML <img> tag pointing to the saved image. | Add verification that the PNG file exists before outputting the <img> element, and include customizable alt text and a CSS class attribute. | Refactor the example to accept the output file path and image file name as parameters, then generate the corresponding <img> tag dynamically.
// Common Searches: asp.net display excel worksheet as png using aspose.cells and html img tag | c# render worksheet to png and embed image in html page | how to create html img element for aspose.cells generated png file | asp.net core show excel sheet image generated by aspose.cells
// Tags: Aspose.Cells render worksheet to PNG | C# generate HTML img tag for file | Aspose.Cells ImageOrPrintOptions PNG output | SheetRender ToImage usage C# | embed Excel image in web page Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example creates a workbook, adds data, renders the first worksheet to a PNG file using Aspose.Cells ImageOrPrintOptions, verifies the file was created, and outputs an HTML <img> tag that references the generated image.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (lifecycle rule: create)
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Sample";

            // Optional: add some data to the worksheet
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B1"].PutValue("World");

            // Define the PNG file name (the file will be saved to the application directory)
            string pngFileName = "SampleSheet.png";

            // Configure image options for PNG output
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true,          // Render each sheet as a single page
                HorizontalResolution = 96,
                VerticalResolution = 96
                // Image format is inferred from the file extension, so no need to set ImageFormat explicitly
            };

            // Render the worksheet to an image (lifecycle rule: save)
            SheetRender sheetRender = new SheetRender(sheet, imgOptions);
            sheetRender.ToImage(0, pngFileName); // 0 = first page of the sheet

            // Verify that the image file was created
            if (File.Exists(pngFileName))
            {
                // Generate the HTML <img> tag referencing the saved PNG file
                string imgTag = $"<img src=\"{pngFileName}\" alt=\"Worksheet Image\" />";
                Console.WriteLine(imgTag);
            }
            else
            {
                Console.WriteLine("Failed to create the PNG image.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
