// Title: Compute SHA‑256 Checksum for a TIFF Exported with Aspose.Cells (.NET C#)
// Description: Creates a workbook, adds sample data, renders the first worksheet to a single‑page TIFF using LZW compression, saves the file, and then calculates a SHA‑256 hash of the saved image to verify its integrity.
// Keywords: Aspose.Cells | C# TIFF export | SHA256 checksum | file integrity verification | image hash .NET | LZW compression TIFF | compute file hash | Excel to TIFF conversion | checksum after rendering | global
// Common Searches: C# compute SHA256 of TIFF generated by Aspose.Cells | verify integrity of TIFF file exported from Excel .NET | how to get file hash after Aspose.Cells TIFF export | Aspose.Cells image checksum example | calculate SHA256 for saved TIFF in C#
// Developer Intent: Generate a SHA‑256 hash of the TIFF file produced by Aspose.Cells and use it to confirm that the file has not been altered.
// Use Cases: Store the checksum alongside the exported report for later audit and tamper detection. | Compare the hash after file transfer to ensure the TIFF arrived unchanged. | Log the checksum in a monitoring system to trigger alerts if a regenerated file differs.
// AI Prompts: Provide C# code that renders an Aspose.Cells worksheet to a TIFF file and then returns its SHA256 checksum. | Explain how to compare a computed TIFF checksum with a reference value to detect corruption or tampering.

using System;
using System.IO;
using System.Security.Cryptography;
using System.Drawing.Imaging;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsChecksumDemo
{
    // Creates a workbook, adds sample data, renders the first worksheet to a single‑page TIFF using LZW compression, saves the file, and then calculates a SHA‑256 hash of the saved image to verify its integrity.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet worksheet = workbook.Worksheets[0];

                // Add sample data to the worksheet
                worksheet.Cells["A1"].PutValue("Aspose.Cells TIFF Checksum Demo");
                worksheet.Cells["A2"].PutValue(DateTime.Now);

                // Configure image options for TIFF rendering
                ImageOrPrintOptions options = new ImageOrPrintOptions
                {
                    // Use LZW compression (default) or change as needed
                    TiffCompression = TiffCompression.CompressionLZW,
                    HorizontalResolution = 300,
                    VerticalResolution = 300,
                    OnePagePerSheet = true
                };

                // Render the worksheet to a TIFF file
                string tiffPath = "output.tiff";
                SheetRender renderer = new SheetRender(worksheet, options);
                renderer.ToTiff(tiffPath);
                Console.WriteLine($"TIFF file saved to: {tiffPath}");

                // Compute SHA256 checksum of the saved TIFF file to verify integrity
                if (File.Exists(tiffPath))
                {
                    try
                    {
                        byte[] fileBytes = File.ReadAllBytes(tiffPath);
                        byte[] hashBytes = SHA256.Create().ComputeHash(fileBytes);
                        string checksum = BitConverter.ToString(hashBytes).Replace("-", string.Empty);
                        Console.WriteLine($"SHA256 Checksum: {checksum}");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error computing checksum: {ex.Message}");
                    }
                }
                else
                {
                    Console.WriteLine($"Error: TIFF file not found at {tiffPath}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
