// Title: Increase the brightness of an exported worksheet PNG by 20% using System.Drawing in C# with Aspose.Cells
// AI Prompts: Write C# code that loads a PNG file generated by Aspose.Cells, applies a 20 % brightness boost with System.Drawing's ColorMatrix, and writes the result back to disk. | Create a single method that renders the first worksheet of an Excel workbook to PNG via Aspose.Cells and then adjusts the image brightness by a specified percentage using System.Drawing. | Show how to encapsulate the brightness‑adjustment logic into a reusable function that accepts a source PNG path, a brightness factor, and an output path.
// Common Searches: c# increase brightness of png image exported from aspose.cells | apply 20 percent brightness boost to excel worksheet png using system.drawing | how to adjust brightness of worksheet png after rendering with aspose.cells .net | system.drawing color matrix increase image brightness c# example | aspose.cells export worksheet to png then modify image brightness
// Tags: Aspose.Cells worksheet to PNG export | System.Drawing brightness adjustment C# | PNG image brightness increase 20 percent | C# image processing after Excel rendering | ColorMatrix brightness filter C#

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example demonstrates exporting the first worksheet of an Excel file to a PNG image with Aspose.Cells, then using System.Drawing to increase the image's brightness by 20 % via a ColorMatrix, and finally saving the enhanced PNG.
class Program
{
    static void Main()
    {
        // Paths for input Excel and output image
        string excelPath = "input.xlsx";
        string pngPath = "worksheet.png";

        try
        {
            // Verify that the input Excel file exists
            if (!File.Exists(excelPath))
                throw new FileNotFoundException($"The Excel file '{excelPath}' was not found.");

            // Load the workbook
            Workbook workbook = new Workbook(excelPath);

            // Ensure there is at least one worksheet
            if (workbook.Worksheets.Count == 0)
                throw new InvalidOperationException("The workbook does not contain any worksheets.");

            // Configure image export options (default PNG format, one page per sheet)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
                // ImageFormat defaults to PNG, so explicit setting is unnecessary
            };

            // Render the first worksheet to an image file
            SheetRender sheetRender = new SheetRender(workbook.Worksheets[0], imgOptions);
            sheetRender.ToImage(0, pngPath);

            Console.WriteLine($"Worksheet exported successfully to '{pngPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
