// Title: Insert a rendered worksheet PNG into a Word document using C# Aspose.Cells and OpenXML SDK for automated reporting
// AI Prompts: Write C# code that loads an .xlsx file, renders the first worksheet to a PNG with Aspose.Cells, and embeds the PNG into a new .docx using OpenXML SDK. | Provide a C# example that creates a WordprocessingDocument, adds an image part from a MemoryStream containing the worksheet PNG, and places the picture in the document body. | Show how to combine Aspose.Cells SheetRender and OpenXML SDK to generate an automated report that includes the worksheet image.
// Common Searches: C# insert Excel worksheet image into Word document using OpenXML | Aspose.Cells render worksheet to PNG and add to .docx programmatically | OpenXML SDK add picture from MemoryStream to Word file | automated reporting generate Word report with Excel sheet snapshot C# | how to embed PNG generated by Aspose.Cells into a WordprocessingDocument
// Tags: render worksheet to PNG Aspose.Cells | embed PNG into Word OpenXML SDK | automated Excel to Word reporting C# | add picture part from MemoryStream OpenXML | create Word document with worksheet snapshot

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The example loads an Excel workbook, uses Aspose.Cells to render the first worksheet as a PNG image stored in a MemoryStream, then creates a WordprocessingDocument with OpenXML SDK, adds the PNG as an image part, inserts it into the document body, and saves the .docx for automated reporting.
class InsertWorksheetImageIntoWord
{
    static void Main()
    {
        try
        {
            // Paths for source Excel and output image
            string excelPath = "input.xlsx";
            string imagePath = "worksheet.png";

            // Verify that the Excel file exists
            if (!File.Exists(excelPath))
            {
                Console.WriteLine($"Error: Excel file not found at '{excelPath}'.");
                return;
            }

            // Load the Excel workbook
            Workbook workbook = new Workbook(excelPath);

            // Set rendering options (default image format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
            };

            // Render the first worksheet to an image
            SheetRender sheetRender = new SheetRender(workbook.Worksheets[0], imgOptions);
            using (MemoryStream imageStream = new MemoryStream())
            {
                sheetRender.ToImage(0, imageStream); // 0 = first page of the sheet
                imageStream.Position = 0; // Reset stream position for reading

                // Save the image to a file
                using (FileStream fileStream = new FileStream(imagePath, FileMode.Create, FileAccess.Write))
                {
                    imageStream.CopyTo(fileStream);
                }
            }

            Console.WriteLine($"Worksheet image saved successfully to '{imagePath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
