// Title: How to minify an SVG worksheet exported from Excel using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an .xlsx workbook with Aspose.Cells, exports the first worksheet as SVG to a MemoryStream, then strips XML comments and collapses inter‑tag whitespace using regular expressions before saving the file. | Create a reusable C# method that accepts a Workbook object, generates SVG via Aspose.Cells, and returns a minified SVG string after eliminating comments and redundant spaces. | Show how to configure ImageSaveOptions for SVG export in Aspose.Cells, capture the output in a MemoryStream, and perform lightweight minification without external dependencies.
// Common Searches: C# Aspose.Cells export worksheet to SVG and reduce its size | strip comments from SVG generated by Aspose.Cells in .NET | optimize SVG output from Excel sheet using Aspose.Cells | regex to eliminate extra spaces between SVG tags in C# | capture SVG with MemoryStream from Aspose.Cells before saving
// Tags: Aspose.Cells SVG export minification | C# regex SVG comment removal | ImageSaveOptions SaveFormat.Svg Aspose | MemoryStream processing SVG Aspose.Cells | whitespace collapse in SVG .NET

using Aspose.Cells;
using Aspose.Cells.Saving;
using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

// The example loads an Excel workbook, exports the first worksheet to SVG using Aspose.Cells, then minifies the SVG by stripping XML comments, collapsing whitespace between tags, and trimming the result before writing it to a file.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.svg";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: Input file '{inputPath}' not found.");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputPath);

            // Ensure the workbook contains at least one worksheet
            if (workbook.Worksheets.Count == 0)
            {
                Console.WriteLine("Error: The workbook does not contain any worksheets.");
                return;
            }

            // Export the first worksheet to SVG using a memory stream
            using (MemoryStream svgStream = new MemoryStream())
            {
                // Configure image save options for SVG format
                ImageSaveOptions saveOptions = new ImageSaveOptions(SaveFormat.Svg);
                saveOptions.ImageOrPrintOptions.OnePagePerSheet = true; // export each sheet as one page
                // Note: SheetIndex property is not available in this version; all sheets will be exported.

                try
                {
                    // Save the worksheet(s) as SVG into the memory stream
                    workbook.Save(svgStream, saveOptions);
                }
                catch (Exception saveEx)
                {
                    Console.WriteLine($"Failed to save SVG: {saveEx.Message}");
                    return;
                }

                // Convert the stream content to a UTF‑8 string
                string svgContent = Encoding.UTF8.GetString(svgStream.ToArray());

                // ---------- Minify SVG ----------
                // 1. Remove XML/HTML comments: <!-- comment -->
                svgContent = Regex.Replace(svgContent, @"<!--.*?-->", string.Empty, RegexOptions.Singleline);
                // 2. Collapse whitespace between tags (e.g., >   <  becomes ><
                svgContent = Regex.Replace(svgContent, @">\s+<", "><");
                // 3. Trim leading/trailing whitespace
                svgContent = svgContent.Trim();

                // Write the minified SVG to the output file
                try
                {
                    File.WriteAllText(outputPath, svgContent, Encoding.UTF8);
                    Console.WriteLine($"SVG successfully saved to '{outputPath}'.");
                }
                catch (Exception writeEx)
                {
                    Console.WriteLine($"Failed to write SVG file: {writeEx.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
