// Title: Export an Excel worksheet to SVG and minify it by stripping comments and collapsing whitespace using Aspose.Cells in C#
// AI Prompts: Generate C# code that loads an .xlsx file, renders the first worksheet to SVG with Aspose.Cells, and then minifies the SVG by removing XML comments and excess whitespace. | Create a reusable C# method that accepts a MemoryStream containing SVG from Aspose.Cells and returns a compact SVG string without comments or unnecessary spaces. | Show how to apply regular expressions in C# to collapse inter‑tag whitespace and trim the SVG output after exporting from Aspose.Cells.
// Common Searches: C# how to reduce size of SVG exported from Aspose.Cells | remove XML comments from SVG generated by Aspose.Cells .NET | collapse whitespace between tags in SVG using C# regex | minify worksheet SVG output Aspose.Cells example | export Excel sheet to compact SVG with Aspose.Cells in .NET
// Tags: Aspose.Cells export worksheet to SVG | C# minify SVG with regex | remove XML comments from SVG | collapse inter‑tag whitespace in SVG | reduce SVG file size .NET

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The program loads an Excel workbook, renders the first worksheet to SVG via Aspose.Cells, then minifies the SVG by stripping XML comments, collapsing inter‑tag whitespace, and trimming the result before saving.
class SvgMinifier
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.svg";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file \"{inputPath}\" not found.");
                return;
            }

            // Load the Excel workbook
            var workbook = new Workbook(inputPath);

            // Get the first worksheet (or any specific worksheet)
            var worksheet = workbook.Worksheets[0];

            // Set up image options for SVG export
            var imgOptions = new ImageOrPrintOptions
            {
                SaveFormat = SaveFormat.Svg
            };

            // Render the worksheet to SVG using a memory stream
            using (var svgStream = new MemoryStream())
            {
                var sheetRender = new SheetRender(worksheet, imgOptions);
                // Render the first page (index 0) to the stream
                sheetRender.ToImage(0, svgStream);
                svgStream.Position = 0;

                // Read the SVG content as a UTF‑8 string
                string svgContent = Encoding.UTF8.GetString(svgStream.ToArray());

                // ---------- Minify SVG ----------
                // 1. Remove XML comments: <!-- comment -->
                svgContent = Regex.Replace(svgContent, @"<!--(.*?)-->", string.Empty,
                                          RegexOptions.Singleline);

                // 2. Collapse whitespace between tags: >   <  => ><
                svgContent = Regex.Replace(svgContent, @">\s+<", "><");

                // 3. Trim leading/trailing whitespace
                svgContent = svgContent.Trim();

                // Save the minified SVG to a file
                File.WriteAllText(outputPath, svgContent, Encoding.UTF8);
                Console.WriteLine($"Minified SVG saved to \"{outputPath}\".");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
