// Title: C# – Minify Aspose.Cells‑generated SVG worksheet by stripping comments and whitespace
// Description: Creates a workbook, renders the first worksheet to SVG with Aspose.Cells, then removes XML comments and collapses whitespace using regular expressions, saves a minified SVG and reports the size reduction.
// Keywords: Aspose.Cells | C# | SVG minification | remove XML comments | collapse whitespace | optimize SVG size | SheetRender | SvgImageOptions IsOptimized | reduce SVG file size .NET | compact SVG for web | Aspose.Cells rendering
// Common Searches: minify SVG generated by Aspose.Cells C# | remove comments from Aspose.Cells SVG output | collapse whitespace in SVG file using C# | Aspose.Cells SvgImageOptions IsOptimized effect | compare original and minified SVG size Aspose
// Developer Intent: Reduce the file size of an SVG produced from a worksheet by eliminating XML comments and unnecessary whitespace.
// Use Cases: Embed a lightweight SVG of a spreadsheet in a web page or email. | Automate size‑reduction checks for SVG assets in reporting pipelines. | Prepare compact SVG files for mobile or low‑bandwidth environments.
// AI Prompts: Show C# code that renders an Aspose.Cells worksheet to SVG and then minifies the output by removing XML comments and extra spaces. | Explain how the IsOptimized flag in SvgImageOptions influences the generated SVG and whether additional regex‑based minification adds value. | Suggest .NET alternatives to regex for SVG minification, such as using XmlDocument or third‑party libraries.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Creates a workbook, renders the first worksheet to SVG with Aspose.Cells, then removes XML comments and collapses whitespace using regular expressions, saves a minified SVG and reports the size reduction.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and populate it with sample data
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];
            worksheet.Cells["A1"].PutValue("Product");
            worksheet.Cells["B1"].PutValue("Price");
            worksheet.Cells["A2"].PutValue("Apple");
            worksheet.Cells["B2"].PutValue(1.2);
            worksheet.Cells["A3"].PutValue("Orange");
            worksheet.Cells["B3"].PutValue(0.8);

            // Configure SVG rendering options with optimization enabled
            SvgImageOptions svgOptions = new SvgImageOptions
            {
                IsOptimized = true,   // Enable size optimizations
                FitToViewPort = true  // Fit SVG to viewport (optional)
            };

            // Render the worksheet to an SVG file
            string originalSvgPath = "worksheet.svg";
            SheetRender renderer = new SheetRender(worksheet, svgOptions);
            renderer.ToImage(0, originalSvgPath);

            // Verify that the SVG file was created
            if (!File.Exists(originalSvgPath))
                throw new FileNotFoundException("SVG file was not generated.", originalSvgPath);

            // Read the generated SVG content
            string svgContent = File.ReadAllText(originalSvgPath);

            // Remove XML comments (<!-- comment -->)
            svgContent = Regex.Replace(svgContent, @"<!--.*?-->", string.Empty, RegexOptions.Singleline);

            // Collapse whitespace between tags and normalize spaces
            svgContent = Regex.Replace(svgContent, @">\s+<", "><"); // Remove whitespace between tags
            svgContent = Regex.Replace(svgContent, @"\s+", " ");   // Collapse multiple spaces
            svgContent = svgContent.Trim();

            // Save the minified SVG content
            string minifiedSvgPath = "worksheet.min.svg";
            File.WriteAllText(minifiedSvgPath, svgContent);

            // Output file size comparison
            Console.WriteLine($"Original SVG size: {new FileInfo(originalSvgPath).Length} bytes");
            Console.WriteLine($"Minified SVG size: {new FileInfo(minifiedSvgPath).Length} bytes");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
