// Title: Auto‑delete Aspose.Cells worksheet PNG after 24 hours with a background task (C#)
// Description: Creates a workbook, renders the first worksheet to a temporary PNG file using Aspose.Cells, then launches a fire‑and‑forget background task that waits 24 hours before deleting the image, keeping the main thread responsive and freeing disk space.
// Keywords: Aspose.Cells | C# | .NET | PNG rendering | SheetRender | temporary file cleanup | background task | Task.Delay | file deletion scheduler | auto‑cleanup | worksheet snapshot
// Common Searches: how to delete Aspose.Cells PNG after 24 hours | schedule file deletion in C# .NET | background task to remove temporary image | Aspose.Cells render worksheet to PNG and clean up | auto‑remove temporary files generated by Aspose.Cells
// Developer Intent: Remove a temporary PNG image generated from an Aspose.Cells worksheet after a 24‑hour period without blocking the application.
// Use Cases: Generate a one‑time PNG preview for an email attachment and ensure it is automatically removed after a day. | Provide a web‑service that returns a worksheet snapshot as PNG and schedule cleanup to prevent disk‑space bloat. | Run a background job that periodically deletes old worksheet images created by batch processing.
// AI Prompts: Show C# code that uses Hangfire to schedule deletion of an Aspose.Cells PNG file after 24 hours. | Extend the ScheduleDeletion method to accept multiple file paths and support cancellation tokens. | Explain how to embed the deletion logic in an ASP.NET Core hosted service for recurring temporary image cleanup.

using System;
using System.IO;
using System.Threading.Tasks;
using Aspose.Cells;
using Aspose.Cells.Rendering;
using Aspose.Cells.Drawing;

// Creates a workbook, renders the first worksheet to a temporary PNG file using Aspose.Cells, then launches a fire‑and‑forget background task that waits 24 hours before deleting the image, keeping the main thread responsive and freeing disk space.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample Data");
        sheet.Cells["B1"].PutValue(123);

        // Configure image rendering options for PNG
        ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
        {
            ImageType = ImageType.Png,
            OnePagePerSheet = true
        };

        // Render the worksheet to a PNG file (uses provided SheetRender.ToImage rule)
        string imagePath = Path.Combine(Path.GetTempPath(), "WorksheetImage.png");
        SheetRender renderer = new SheetRender(sheet, imgOptions);
        renderer.ToImage(0, imagePath);
        Console.WriteLine($"Worksheet image saved to: {imagePath}");

        // Schedule automatic deletion after 24 hours (background fire‑and‑forget task)
        ScheduleDeletion(imagePath, TimeSpan.FromHours(24));

        // Dispose resources
        renderer.Dispose();
        workbook.Dispose();

        Console.WriteLine("Deletion scheduled. Press any key to exit.");
        Console.ReadKey();
    }

    // Schedules deletion of a file after the specified delay
    static void ScheduleDeletion(string filePath, TimeSpan delay)
    {
        // Run the deletion logic on a background thread without blocking the main thread
        Task.Run(async () =>
        {
            try
            {
                await Task.Delay(delay);
                if (File.Exists(filePath))
                {
                    File.Delete(filePath);
                    Console.WriteLine($"File deleted after {delay.TotalHours} hours: {filePath}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error during scheduled deletion: {ex.Message}");
            }
        });
    }
}
