// Title: Split Multi‑Page TIFF into Single‑Page TIFFs with Aspose.Cells for .NET (C#)
// Description: Loads an Excel workbook, configures ImageOrPrintOptions (LZW compression, TIFF format), creates a WorkbookRender, and iterates through each rendered page to save it as an individual TIFF file in a target folder. Includes checks for missing source files and error handling for rendering and file I/O.
// Keywords: Aspose.Cells | C# | .NET | split multi page tiff | single page tiff | WorkbookRender | ImageOrPrintOptions | LZW compression | Excel to TIFF | extract tiff pages | tiff pagination
// Common Searches: Aspose.Cells split multi page tiff | C# save each page of a TIFF workbook | How to extract single‑page TIFFs from Excel using Aspose | Render Excel to separate TIFF files .NET | WorkbookRender page by page TIFF output
// Developer Intent: Create separate single‑page TIFF images from a multi‑page TIFF generated by Aspose.Cells.
// Use Cases: Upload individual pages to a document management system that requires one TIFF per file. | Send specific pages to different printers or workflows without re‑rendering the whole workbook. | Break a large TIFF into smaller files for parallel processing, batch conversion, or reduced memory usage.
// AI Prompts: Generate C# code that uses Aspose.Cells to load an Excel file and split the resulting multi‑page TIFF into separate TIFF files with robust error handling. | Refactor the TIFF‑splitting example to use async file operations and log progress to a text file. | Explain how to change ImageOrPrintOptions to use CCITT Group 4 compression or output PNG instead of TIFF when splitting pages.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExamples
{
    // Loads an Excel workbook, configures ImageOrPrintOptions (LZW compression, TIFF format), creates a WorkbookRender, and iterates through each rendered page to save it as an individual TIFF file in a target folder. Includes checks for missing source files and error handling for rendering and file I/O.
    public class SplitMultiPageTiff
    {
        public static void Main()
        {
            try
            {
                Run();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        public static void Run()
        {
            const string sourceFile = "SourceWorkbook.xlsx";

            // Verify source file exists to avoid FileNotFoundException
            if (!File.Exists(sourceFile))
            {
                Console.WriteLine($"Source file \"{sourceFile}\" not found.");
                return;
            }

            Workbook workbook;
            try
            {
                // Load the source Excel workbook
                workbook = new Workbook(sourceFile);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to load workbook: {ex.Message}");
                return;
            }

            // Configure rendering options for TIFF output
            var options = new ImageOrPrintOptions
            {
                // Optional compression
                TiffCompression = TiffCompression.CompressionLZW,
                // Keep original pagination
                OnePagePerSheet = false
                // ImageFormat defaults to TIFF when saving with .tiff extension
            };

            // Create a workbook renderer with the specified options
            var renderer = new WorkbookRender(workbook, options);

            // Ensure the output directory exists
            string outputDir = "SplitTiffPages";
            Directory.CreateDirectory(outputDir);

            // Iterate through each rendered page and save it as an individual TIFF file
            for (int pageIndex = 0; pageIndex < renderer.PageCount; pageIndex++)
            {
                try
                {
                    string pageFile = Path.Combine(outputDir, $"Page_{pageIndex + 1}.tiff");
                    renderer.ToImage(pageIndex, pageFile);
                    Console.WriteLine($"Saved page {pageIndex + 1} to {pageFile}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to save page {pageIndex + 1}: {ex.Message}");
                }
            }

            // Release workbook resources
            workbook?.Dispose();
        }
    }
}
