// Title: Encrypt Aspose.Cells Workbook as TIFF and Upload via FTPS (TLS) in C#
// Description: Creates a workbook, saves it as a TIFF image in a MemoryStream, encrypts the image with AES‑256 CBC (PKCS7), and uploads the encrypted bytes to an FTPS server using FtpWebRequest with TLS enabled.
// Keywords: Aspose.Cells | C# TIFF encryption | AES‑256 CBC | FTPS upload | TLS FTP | Workbook to image | Encrypted file transfer | FtpWebRequest | Secure file upload | MemoryStream
// Common Searches: C# encrypt TIFF generated by Aspose.Cells and send over FTPS | How to upload encrypted workbook image to FTPS with TLS | Save Aspose.Cells workbook as TIFF in memory then encrypt | Upload binary data to FTPS using FtpWebRequest C# | AES encryption of spreadsheet image before FTP transfer
// Developer Intent: Generate a TIFF image from a workbook, encrypt the image with AES‑256, and transfer the encrypted file to an FTPS server using TLS.
// Use Cases: Transmit confidential financial snapshots as encrypted TIFF files over FTPS | Store protected spreadsheet images in an encrypted archive on a secure server | Automate nightly backup of workbook images with AES encryption and TLS‑protected upload | Comply with data‑privacy regulations by encrypting spreadsheet exports before FTP transfer
// AI Prompts: Provide C# code that creates an Aspose.Cells workbook, saves it as a TIFF in a MemoryStream, encrypts the bytes with AES‑256 CBC, and uploads the result to an FTPS server using FtpWebRequest with TLS enabled. | Show best‑practice error handling for FTPS uploads and how to retrieve response status in C#. | Demonstrate generating a cryptographically strong AES key and IV with RandomNumberGenerator and storing them securely. | Explain how to verify server certificate validation when using EnableSsl for FTPS in .NET.

using System;
using System.IO;
using System.Net;
using System.Security.Cryptography;
using Aspose.Cells;

// Creates a workbook, saves it as a TIFF image in a MemoryStream, encrypts the image with AES‑256 CBC (PKCS7), and uploads the encrypted bytes to an FTPS server using FtpWebRequest with TLS enabled.
class UploadEncryptedTiff
{
    static void Main()
    {
        try
        {
            // 1. Create a sample workbook and add some data
            using (Workbook workbook = new Workbook())
            {
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Aspose.Cells encrypted TIFF demo");
                sheet.Cells["A2"].PutValue(DateTime.Now);

                // 2. Save the workbook as a TIFF image into a memory stream
                byte[] tiffBytes;
                using (MemoryStream tiffStream = new MemoryStream())
                {
                    workbook.Save(tiffStream, SaveFormat.Tiff);
                    tiffBytes = tiffStream.ToArray();
                }

                // 3. Encrypt the TIFF bytes using AES (CBC mode with PKCS7 padding)
                byte[] encryptedBytes;
                byte[] key = new byte[32]; // 256‑bit key
                byte[] iv = new byte[16];  // 128‑bit IV
                for (int i = 0; i < key.Length; i++) key[i] = (byte)i;
                for (int i = 0; i < iv.Length; i++) iv[i] = (byte)(i + 1);

                using (Aes aes = Aes.Create())
                {
                    aes.Key = key;
                    aes.IV = iv;
                    aes.Mode = CipherMode.CBC;
                    aes.Padding = PaddingMode.PKCS7;

                    using (MemoryStream encryptedStream = new MemoryStream())
                    using (CryptoStream cryptoStream = new CryptoStream(encryptedStream, aes.CreateEncryptor(), CryptoStreamMode.Write))
                    {
                        cryptoStream.Write(tiffBytes, 0, tiffBytes.Length);
                        cryptoStream.FlushFinalBlock();
                        encryptedBytes = encryptedStream.ToArray();
                    }
                }

                // 4. Upload the encrypted data to a secure FTPS server (TLS/SSL)
                try
                {
                    string ftpUrl = "ftps://your-secure-ftp-server.com/upload/encrypted_image.tiff";
                    FtpWebRequest request = (FtpWebRequest)WebRequest.Create(ftpUrl);
                    request.Method = WebRequestMethods.Ftp.UploadFile;
                    request.EnableSsl = true; // enforce TLS
                    request.Credentials = new NetworkCredential("ftpUser", "ftpPassword");
                    request.ContentLength = encryptedBytes.Length;

                    using (Stream requestStream = request.GetRequestStream())
                    {
                        requestStream.Write(encryptedBytes, 0, encryptedBytes.Length);
                    }

                    using (FtpWebResponse response = (FtpWebResponse)request.GetResponse())
                    {
                        Console.WriteLine($"Upload status: {response.StatusDescription}");
                    }
                }
                catch (Exception ftpEx)
                {
                    Console.Error.WriteLine($"FTP upload error: {ftpEx.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}
