// Title: Validate that an exported chart SVG viewBox matches the original Excel chart dimensions using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an Excel workbook, retrieves the first chart, exports it to SVG with Aspose.Cells, parses the viewBox attribute from the SVG XML, and reports whether the width and height are within a configurable tolerance of the chart's ChartArea dimensions. | Create a reusable C# method named VerifyChartSvgViewBox that accepts a Chart object and a tolerance value, extracts the SVG viewBox, compares it to the chart's size, and returns a boolean indicating a match while logging the details.
// Common Searches: how to verify that an SVG viewBox from an Aspose.Cells chart matches the original chart size | C# compare Excel chart dimensions with exported SVG viewBox using Aspose.Cells | Aspose.Cells export chart to SVG and check viewBox width height tolerance | read viewBox attribute from SVG generated by Aspose.Cells chart | validate chart size after converting Excel chart to SVG in .NET
// Tags: Aspose.Cells export chart to SVG | compare chart area dimensions with SVG viewBox | validate SVG viewBox size C# | chart size tolerance check Aspose.Cells | read SVG viewBox attribute .NET | ChartArea width height API Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;
using System;
using System.IO;
using System.Xml;

// Loads an Excel workbook, extracts the first chart, exports it to SVG, reads the viewBox attribute, and checks whether its width and height match the chart's ChartArea dimensions within a configurable tolerance.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook
            var workbook = new Workbook(inputPath);
            var worksheet = workbook.Worksheets[0];

            // Ensure the worksheet contains at least one chart
            if (worksheet.Charts.Count == 0)
            {
                Console.WriteLine("No charts found in the worksheet.");
                return;
            }

            // Get the first chart in the worksheet
            var chart = worksheet.Charts[0];

            // Retrieve chart dimensions (points) via ChartArea
            double chartWidth = chart.ChartArea.Width;
            double chartHeight = chart.ChartArea.Height;

            // Export the chart to SVG using a memory stream
            using (var ms = new MemoryStream())
            {
                var imgOptions = new ImageOrPrintOptions
                {
                    SaveFormat = SaveFormat.Svg, // Export as SVG
                    OnePagePerSheet = true
                };

                chart.ToImage(ms, imgOptions);
                ms.Position = 0;

                // Load SVG XML
                var xmlDoc = new XmlDocument();
                xmlDoc.Load(ms);
                var svgNode = xmlDoc.DocumentElement; // <svg> element

                if (svgNode == null)
                {
                    Console.WriteLine("Failed to load SVG content.");
                    return;
                }

                // Extract viewBox attribute (format: "minX minY width height")
                var viewBox = svgNode.GetAttribute("viewBox");
                var parts = viewBox.Split(' ');
                if (parts.Length != 4 ||
                    !double.TryParse(parts[2], out double viewBoxWidth) ||
                    !double.TryParse(parts[3], out double viewBoxHeight))
                {
                    Console.WriteLine("Invalid viewBox attribute.");
                    return;
                }

                // Compare dimensions with a tolerance
                const double tolerance = 0.5; // allow minor rounding differences
                bool widthMatch = Math.Abs(chartWidth - viewBoxWidth) <= tolerance;
                bool heightMatch = Math.Abs(chartHeight - viewBoxHeight) <= tolerance;

                // Output results
                Console.WriteLine($"Chart size (points): {chartWidth} x {chartHeight}");
                Console.WriteLine($"SVG viewBox size: {viewBoxWidth} x {viewBoxHeight}");
                Console.WriteLine($"Width match: {widthMatch}");
                Console.WriteLine($"Height match: {heightMatch}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
