// Title: Validate SVG viewBox matches Aspose.Cells chart size in C#
// Description: Creates a workbook, adds a column chart, obtains its pixel dimensions with GetActualSize, renders the chart to SVG using ImageOrPrintOptions (SVGFitToViewPort), reads the SVG file, extracts the viewBox attribute, parses width and height, and checks them against the chart size within a tolerance, reporting success or mismatch.
// Keywords: Aspose.Cells | C# | .NET | SVG export | viewBox validation | chart actual size | GetActualSize | ImageOrPrintOptions | SVGFitToViewPort | chart rendering | dimension comparison
// Common Searches: Aspose.Cells verify SVG viewBox size | C# compare chart pixel size with SVG viewBox | extract viewBox from SVG generated by Aspose.Cells | how to get actual chart dimensions Aspose.Cells | validate SVG viewport matches Excel chart
// Developer Intent: Confirm that the SVG viewBox dimensions accurately reflect the chart's rendered pixel size.
// Use Cases: Automated QA to ensure exported SVG charts retain exact dimensions before embedding in web reports. | CI/CD checks that scaling issues are caught when converting Excel charts to SVG. | Runtime validation for dynamically generated SVG charts to prevent layout overflow.
// AI Prompts: Generate a reusable C# method that accepts an SVG string and returns the viewBox width and height as doubles. | Add logging that warns when the viewBox width or height differs from the chart's GetActualSize values by more than a configurable tolerance. | Write NUnit tests that create a chart, export it to SVG, and assert that the viewBox dimensions equal the values returned by GetActualSize.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Rendering;
using Aspose.Cells.Drawing;

// Creates a workbook, adds a column chart, obtains its pixel dimensions with GetActualSize, renders the chart to SVG using ImageOrPrintOptions (SVGFitToViewPort), reads the SVG file, extracts the viewBox attribute, parses width and height, and checks them against the chart size within a tolerance, reporting success or mismatch.
class ValidateSvgViewBox
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate sample data for the chart
        worksheet.Cells["A1"].PutValue("Category");
        worksheet.Cells["A2"].PutValue("A");
        worksheet.Cells["A3"].PutValue("B");
        worksheet.Cells["A4"].PutValue("C");
        worksheet.Cells["B1"].PutValue("Value");
        worksheet.Cells["B2"].PutValue(10);
        worksheet.Cells["B3"].PutValue(20);
        worksheet.Cells["B4"].PutValue(30);

        // Add a column chart to the worksheet
        int chartIndex = worksheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
        Chart chart = worksheet.Charts[chartIndex];
        chart.NSeries.Add("B2:B4", true);
        chart.NSeries.CategoryData = "A2:A4";

        // Ensure the chart layout is calculated so size properties are populated
        chart.Calculate();

        // Retrieve the actual chart size in pixels (width, height)
        int[] actualSize = chart.GetActualSize(); // actualSize[0] = width, actualSize[1] = height

        // Render the chart to an SVG file using ImageOrPrintOptions
        ImageOrPrintOptions imgOptions = new ImageOrPrintOptions();
        imgOptions.ImageType = ImageType.Svg;
        imgOptions.SVGFitToViewPort = true; // Fit the generated SVG to the viewport

        string svgFilePath = "chart.svg";
        chart.ToImage(svgFilePath, imgOptions);

        // Load the generated SVG content
        string svgContent = File.ReadAllText(svgFilePath);

        // Extract the viewBox attribute (format: "minX minY width height")
        string viewBoxPattern = @"viewBox\s*=\s*""([^""]+)""";
        Match viewBoxMatch = Regex.Match(svgContent, viewBoxPattern);
        if (!viewBoxMatch.Success)
        {
            Console.WriteLine("viewBox attribute not found in the SVG file.");
            return;
        }

        // Split the viewBox values and parse width and height (third and fourth numbers)
        string[] viewBoxValues = viewBoxMatch.Groups[1].Value.Split(new[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
        if (viewBoxValues.Length != 4)
        {
            Console.WriteLine("Invalid viewBox format.");
            return;
        }

        double viewBoxWidth = double.Parse(viewBoxValues[2]);
        double viewBoxHeight = double.Parse(viewBoxValues[3]);

        // Compare the viewBox dimensions with the actual chart size (allow a small tolerance)
        const double tolerance = 0.5; // pixels
        bool widthMatches = Math.Abs(viewBoxWidth - actualSize[0]) <= tolerance;
        bool heightMatches = Math.Abs(viewBoxHeight - actualSize[1]) <= tolerance;

        if (widthMatches && heightMatches)
        {
            Console.WriteLine($"ViewBox matches chart size: {viewBoxWidth}x{viewBoxHeight} pixels.");
        }
        else
        {
            Console.WriteLine($"ViewBox ({viewBoxWidth}x{viewBoxHeight}) does NOT match chart size ({actualSize[0]}x{actualSize[1]}) pixels.");
        }

        // Save the workbook (optional, demonstrates normal save lifecycle)
        workbook.Save("validated_chart.xlsx");
    }
}
