// Title: Validate a worksheet exported as SVG against an XSD schema using Aspose.Cells in C#
// AI Prompts: Write C# code that loads an Excel workbook with Aspose.Cells, saves the first worksheet as an SVG file, and then validates the SVG against a supplied XSD schema using XmlDocument and XmlSchemaSet, outputting any validation errors. | Show how to attach a validation event handler in C# to capture schema validation errors when checking the structural correctness of an SVG generated from Aspose.Cells, and return a boolean indicating overall validity.
// Common Searches: c# aspnet cells export first worksheet to svg and validate with xsd schema | how to perform xml schema validation on svg file generated by Aspose.Cells | checking structural compliance of worksheet svg using .net XmlSchemaSet | sample code for validating Aspose.Cells saved svg against svg.xsd | asp.net core validate exported worksheet svg against schema
// Tags: Aspose.Cells export worksheet to SVG | C# XmlSchemaSet validate SVG | SVG XSD schema validation in .NET | Workbook.Save SaveFormat.Svg usage | XmlDocument schema validation handling

using System;
using System.IO;
using System.Xml;
using System.Xml.Schema;
using Aspose.Cells;

// The example loads an Excel file, uses Aspose.Cells to save the first worksheet as an SVG, then loads an XSD schema and validates the generated SVG with XmlDocument and XmlSchemaSet, reporting any validation errors and indicating whether the SVG conforms to the schema.
class Program
{
    static void Main()
    {
        try
        {
            // Path to the source Excel file
            string excelPath = "sample.xlsx";
            if (!File.Exists(excelPath))
            {
                Console.WriteLine($"Excel file not found: {excelPath}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(excelPath);

            // Export the first worksheet to SVG (Workbook.Save handles the active sheet)
            string svgPath = "Worksheet.svg";
            workbook.Save(svgPath, SaveFormat.Svg);

            // Path to the SVG schema (XSD) file
            string xsdPath = "svg.xsd";
            if (!File.Exists(xsdPath))
            {
                Console.WriteLine($"Schema file not found: {xsdPath}");
                return;
            }

            // Load the generated SVG document
            XmlDocument svgDoc = new XmlDocument();
            svgDoc.Load(svgPath);

            // Prepare the schema set and attach it to the document
            XmlSchemaSet schemaSet = new XmlSchemaSet();
            schemaSet.Add(null, xsdPath);
            svgDoc.Schemas.Add(schemaSet);

            bool isValid = true;

            // Validate the SVG against the schema
            try
            {
                svgDoc.Validate((sender, e) =>
                {
                    Console.WriteLine($"Validation error: {e.Message}");
                    isValid = false;
                });
            }
            catch (XmlSchemaException ex)
            {
                Console.WriteLine($"Schema validation exception: {ex.Message}");
                isValid = false;
            }

            Console.WriteLine(isValid ? "SVG is valid." : "SVG is invalid.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
