// Title: Validate an SVG worksheet exported by Aspose.Cells against the official SVG XSD schema using C# XmlReader
// AI Prompts: Write a C# method that takes the paths of an SVG file and its XSD schema, sets up an XmlSchemaSet and XmlReaderSettings, validates the SVG, and returns a collection of validation messages. | Show how to configure XmlReaderSettings for schema validation of an SVG generated by Aspose.Cells, including processing of inline schemas and schemaLocation attributes. | Create a console program that loads an exported SVG worksheet, validates it against the SVG XSD, and prints either the validation errors/warnings or a success confirmation.
// Common Searches: C# how to validate an SVG file generated by Aspose.Cells with an XSD schema | using XmlReaderSettings to perform SVG schema validation in .NET | check structural correctness of exported SVG worksheet in C# | sample code for validating SVG against official SVG XSD in an Aspose.Cells project
// Tags: C# XmlReader SVG schema validation | Aspose.Cells export SVG validation | XmlSchemaSet validate SVG file | SVG XSD validation .NET | handle validation warnings XmlReaderSettings

using System;
using System.IO;
using System.Xml;
using System.Xml.Schema;

// The example verifies that both the SVG worksheet and its XSD schema exist, loads the schema into an XmlSchemaSet, configures XmlReaderSettings for schema validation (including inline schema and schemaLocation processing), reads the SVG with XmlReader to trigger validation, and outputs any errors or warnings via a ValidationEventHandler, finally confirming that the SVG conforms to the official SVG schema.
class Program
{
    static void Main(string[] args)
    {
        // Path to the SVG file to be validated
        string svgFilePath = "input.svg";

        // Path to the SVG XSD schema file (downloaded beforehand)
        string svgSchemaPath = "svg.xsd";

        // Verify that required files exist before proceeding
        if (!File.Exists(svgFilePath))
        {
            Console.WriteLine($"SVG file not found: {svgFilePath}");
            return;
        }

        if (!File.Exists(svgSchemaPath))
        {
            Console.WriteLine($"Schema file not found: {svgSchemaPath}");
            return;
        }

        try
        {
            // Load the SVG schema into a schema set
            XmlSchemaSet schemaSet = new XmlSchemaSet();
            schemaSet.Add("http://www.w3.org/2000/svg", svgSchemaPath);

            // Configure XML reader settings for schema validation
            XmlReaderSettings settings = new XmlReaderSettings
            {
                ValidationType = ValidationType.Schema,
                Schemas = schemaSet,
                // Enable processing of inline schemas and schema locations if present
                ValidationFlags = XmlSchemaValidationFlags.ProcessInlineSchema |
                                  XmlSchemaValidationFlags.ProcessSchemaLocation |
                                  XmlSchemaValidationFlags.ReportValidationWarnings
            };
            settings.ValidationEventHandler += ValidationEventHandler;

            // Perform validation by reading the SVG file with the configured settings
            using (XmlReader reader = XmlReader.Create(svgFilePath, settings))
            {
                while (reader.Read())
                {
                    // Reading triggers validation; no additional processing required
                }
            }

            Console.WriteLine("SVG file is structurally valid according to the schema.");
        }
        catch (XmlException ex)
        {
            Console.WriteLine($"XML parsing error: {ex.Message}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unexpected error: {ex.Message}");
        }
    }

    // Callback to capture validation warnings and errors
    private static void ValidationEventHandler(object sender, ValidationEventArgs e)
    {
        string severity = e.Severity == XmlSeverityType.Error ? "Error" : "Warning";
        Console.WriteLine($"{severity}: {e.Message}");
    }
}
