// Title: Check that a worksheet rendered to PNG with Aspose.Cells matches expected pixel width and height in C#
// AI Prompts: Write a C# method that loads an Excel workbook, renders a specified worksheet to a PNG MemoryStream using Aspose.Cells, and returns true only when the image's width and height equal the given expected values. | Implement a helper that parses the IHDR chunk of a PNG stream to obtain its width and height without relying on System.Drawing or other image libraries. | Enhance the verification routine with detailed error handling for missing workbook files, out‑of‑range sheet indexes, and corrupted PNG data.
// Common Searches: C# verify pixel dimensions of a worksheet image generated by Aspose.Cells | how to read PNG width and height from a MemoryStream in .NET without System.Drawing | Aspose.Cells render Excel sheet to PNG and compare image size programmatically | validate Excel worksheet image size against expected dimensions using Aspose.Cells
// Tags: Aspose.Cells PNG rendering of Excel sheet | extract PNG IHDR dimensions C# | verify worksheet image size .NET | Excel sheet image dimension validation | memory stream PNG size check Aspose

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Provides a C# routine that renders a selected worksheet to a PNG stream with Aspose.Cells, reads the image's width and height directly from the IHDR chunk, and confirms they match expected pixel dimensions, including robust error handling.
public class WorksheetImageVerifier
{
    /// <param name="workbookPath">Path to the Excel file.</param>
    /// <param name="sheetIndex">Zero‑based index of the worksheet to render.</param>
    /// <param name="expectedWidth">Expected image width in pixels.</param>
    /// <param name="expectedHeight">Expected image height in pixels.</param>
    /// <returns>True if dimensions match; otherwise false.</returns>
    public static bool VerifyWorksheetImageDimensions(string workbookPath, int sheetIndex, int expectedWidth, int expectedHeight)
    {
        try
        {
            // Ensure the workbook file exists to avoid FileNotFoundException
            if (!File.Exists(workbookPath))
                throw new FileNotFoundException($"Workbook file not found: {workbookPath}");

            // Load the workbook (lifecycle rule: load)
            Workbook workbook = new Workbook(workbookPath);

            // Validate sheet index
            if (sheetIndex < 0 || sheetIndex >= workbook.Worksheets.Count)
                throw new ArgumentOutOfRangeException(nameof(sheetIndex), "Sheet index is out of range.");

            // Get the target worksheet
            Worksheet worksheet = workbook.Worksheets[sheetIndex];

            // Set image rendering options (default format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true // render the whole sheet on a single page
            };

            // Render the worksheet to an image (in-memory)
            SheetRender sheetRender = new SheetRender(worksheet, imgOptions);
            using (MemoryStream imageStream = new MemoryStream())
            {
                // Render page 0 (the only page because OnePagePerSheet = true)
                sheetRender.ToImage(0, imageStream);

                // Reset stream position before reading
                imageStream.Position = 0;

                // Extract PNG dimensions without System.Drawing
                (int actualWidth, int actualHeight) = GetPngDimensions(imageStream);

                // Compare actual dimensions with expected values
                return actualWidth == expectedWidth && actualHeight == expectedHeight;
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception as needed; for now, return false indicating verification failed
            Console.Error.WriteLine($"Error verifying worksheet image dimensions: {ex.Message}");
            return false;
        }
    }

    // Reads PNG width and height from the stream (big‑endian format)
    private static (int width, int height) GetPngDimensions(Stream pngStream)
    {
        using (BinaryReader reader = new BinaryReader(pngStream, Encoding.Default, leaveOpen: true))
        {
            // PNG signature (8 bytes)
            reader.BaseStream.Seek(8, SeekOrigin.Begin);

            // IHDR chunk length (4 bytes, should be 13)
            int ihdrLength = ReadInt32BigEndian(reader);

            // IHDR chunk type (4 bytes)
            string chunkType = new string(reader.ReadChars(4));
            if (chunkType != "IHDR")
                throw new InvalidDataException("Invalid PNG file: missing IHDR chunk.");

            // Width and height (each 4 bytes, big‑endian)
            int width = ReadInt32BigEndian(reader);
            int height = ReadInt32BigEndian(reader);

            return (width, height);
        }
    }

    // Reads a 4‑byte big‑endian integer
    private static int ReadInt32BigEndian(BinaryReader reader)
    {
        byte[] bytes = reader.ReadBytes(4);
        if (bytes.Length != 4)
            throw new EndOfStreamException("Unexpected end of stream while reading integer.");
        if (BitConverter.IsLittleEndian)
            Array.Reverse(bytes);
        return BitConverter.ToInt32(bytes, 0);
    }
}

public class Program
{
    // Entry point required for compilation
    public static void Main(string[] args)
    {
        // Expected arguments: <workbookPath> <sheetIndex> <expectedWidth> <expectedHeight>
        if (args.Length != 4)
        {
            Console.WriteLine("Usage: WorksheetImageVerifier <workbookPath> <sheetIndex> <expectedWidth> <expectedHeight>");
            return;
        }

        string workbookPath = args[0];
        if (!int.TryParse(args[1], out int sheetIndex) ||
            !int.TryParse(args[2], out int expectedWidth) ||
            !int.TryParse(args[3], out int expectedHeight))
        {
            Console.WriteLine("Invalid numeric arguments.");
            return;
        }

        bool result = WorksheetImageVerifier.VerifyWorksheetImageDimensions(
            workbookPath, sheetIndex, expectedWidth, expectedHeight);

        Console.WriteLine(result
            ? "Worksheet image dimensions match the expected values."
            : "Worksheet image dimensions do NOT match the expected values.");
    }
}
