// Title: C# – Compute and Verify SHA‑256 Checksum of a Worksheet PNG Using Aspose.Cells
// Description: Creates a workbook, writes data to cell A1, saves the first worksheet as a PNG file, calculates the file's SHA‑256 hash with System.Security.Cryptography, and compares it to a predefined hash to confirm image integrity.
// Keywords: Aspose.Cells | C# | .NET | PNG export | worksheet to image | SHA-256 checksum | file hash verification | image integrity | System.Security.Cryptography | SaveFormat.Png
// Common Searches: C# compute SHA256 of PNG generated by Aspose.Cells | verify worksheet image checksum Aspose.Cells | Aspose.Cells PNG hash comparison .NET | validate PNG export integrity Aspose.Cells | checksum mismatch handling in Aspose.Cells
// Developer Intent: Generate a worksheet PNG and validate its integrity by matching its SHA‑256 hash against an expected value.
// Use Cases: Detect corruption of a financial‑report image after transferring the PNG to a remote server. | Automate regression testing by asserting that the PNG produced from a template workbook matches a baseline checksum. | Add a CI/CD step that fails the build when the exported worksheet image hash differs from the reference value. | Archive regulatory charts securely by storing their SHA‑256 hashes and verifying them during periodic audits.
// AI Prompts: Write C# code that reads an expected SHA‑256 hash from appsettings.json and validates the PNG generated by Aspose.Cells. | Explain how to incorporate PNG checksum verification into a GitHub Actions workflow for Aspose.Cells exports. | Suggest a logging strategy that records hash mismatches and throws a custom exception during image generation.

using System;
using System.IO;
using System.Security.Cryptography;
using Aspose.Cells;

namespace AsposeCellsChecksumDemo
{
    // Creates a workbook, writes data to cell A1, saves the first worksheet as a PNG file, calculates the file's SHA‑256 hash with System.Security.Cryptography, and compares it to a predefined hash to confirm image integrity.
    class Program
    {
        static void Main()
        {
            // Path for the generated PNG image
            string pngPath = "worksheet.png";

            // -----------------------------------------------------------------
            // Create a workbook, add some data and save the first worksheet as PNG
            // -----------------------------------------------------------------
            Workbook workbook = new Workbook();                         // create workbook
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Checksum Demo");                // add sample data
            workbook.Save(pngPath, SaveFormat.Png);                     // save as PNG

            // -----------------------------------------------------------------
            // Compute SHA-256 checksum of the generated PNG file
            // -----------------------------------------------------------------
            string computedHash = ComputeSha256(pngPath);
            Console.WriteLine($"Computed SHA-256: {computedHash}");

            // -----------------------------------------------------------------
            // Expected checksum (replace with the known good value to verify)
            // -----------------------------------------------------------------
            string expectedHash = "REPLACE_WITH_KNOWN_SHA256_HASH";

            // Compare the computed checksum with the expected one
            bool isMatch = string.Equals(computedHash, expectedHash, StringComparison.OrdinalIgnoreCase);
            Console.WriteLine($"Checksum match: {isMatch}");
        }

        // Helper method to compute SHA-256 hash of a file and return it as a hex string
        private static string ComputeSha256(string filePath)
        {
            using (FileStream stream = File.OpenRead(filePath))
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hashBytes = sha256.ComputeHash(stream);
                // Convert byte array to hex string
                return BitConverter.ToString(hashBytes).Replace("-", string.Empty).ToLowerInvariant();
            }
        }
    }
}
