// Title: C# – Compute and Verify SHA‑256 Checksum of a Worksheet PNG Rendered with Aspose.Cells
// Description: This Aspose.Cells for .NET example creates a workbook, renders the first worksheet to a PNG file, calculates the file’s SHA‑256 hash using System.Security.Cryptography, and compares it with an expected checksum to confirm image integrity.
// Keywords: Aspose.Cells PNG export | C# SHA-256 checksum | .NET image integrity | worksheet to PNG | SheetRender checksum | ImageOrPrintOptions verification | GitHub Aspose.Cells example | US developers | European .NET developers
// Common Searches: how to calculate SHA‑256 of a PNG generated by Aspose.Cells | verify worksheet image integrity C# | compare PNG checksum with expected value Aspose.Cells | Aspose.Cells render worksheet to PNG and validate hash | C# compute file hash for exported spreadsheet image
// Developer Intent: Generate a worksheet PNG with Aspose.Cells and ensure the exported image matches a known SHA‑256 hash to detect any corruption or unintended changes.
// Use Cases: Automated regression testing to guarantee consistent PNG output across library versions. | Security‑oriented validation of exported spreadsheet images before archiving or transmission. | CI/CD pipeline step that flags altered or corrupted worksheet images by comparing checksums.
// AI Prompts: Write C# code that renders a worksheet to PNG with Aspose.Cells and returns its SHA‑256 hash. | Show how to load an expected checksum from a configuration file and compare it to the computed hash. | Explain best practices for handling a checksum mismatch, including logging, alerting, and aborting the export.

using System;
using System.IO;
using System.Security.Cryptography;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// This Aspose.Cells for .NET example creates a workbook, renders the first worksheet to a PNG file, calculates the file’s SHA‑256 hash using System.Security.Cryptography, and compares it with an expected checksum to confirm image integrity.
public class VerifyPngIntegrity
{
    public static void Run()
    {
        try
        {
            // Path for the temporary PNG file
            string pngPath = "worksheet.png";

            // Create a simple workbook and add some data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B2"].PutValue(123);

            // Render the first worksheet to a PNG image (default format is PNG)
            ImageOrPrintOptions imgOptions = new ImageOrPrintOptions
            {
                OnePagePerSheet = true
            };
            SheetRender renderer = new SheetRender(sheet, imgOptions);
            renderer.ToImage(0, pngPath);

            // Verify that the PNG file was created
            if (!File.Exists(pngPath))
            {
                Console.WriteLine($"Error: PNG file was not created at '{pngPath}'.");
                return;
            }

            // Compute SHA‑256 checksum of the generated PNG file
            byte[] computedHash;
            using (FileStream fs = File.OpenRead(pngPath))
            using (SHA256 sha256 = SHA256.Create())
            {
                computedHash = sha256.ComputeHash(fs);
            }

            // Convert hash to a readable hex string
            string computedHashString = BitConverter.ToString(computedHash).Replace("-", "").ToLowerInvariant();

            // Expected checksum (replace with the known good value)
            string expectedHashString = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

            // Compare and output the result
            bool isMatch = string.Equals(computedHashString, expectedHashString, StringComparison.OrdinalIgnoreCase);
            Console.WriteLine($"Computed SHA‑256: {computedHashString}");
            Console.WriteLine($"Expected SHA‑256: {expectedHashString}");
            Console.WriteLine($"Integrity check passed: {isMatch}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        VerifyPngIntegrity.Run();
    }
}
