// Title: Export an Aspose.Cells workbook to XML without the XML declaration using C#
// AI Prompts: Write C# code that saves an Aspose.Cells workbook to an XML file with OmitXmlDeclaration enabled. | Demonstrate how to configure XmlSaveOptions to omit the XML header when exporting a workbook with Aspose.Cells. | Show a complete C# example that creates a workbook, fills cells, and outputs XML without the <?xml?> declaration.
// Common Searches: Aspose.Cells C# export to XML omit XML declaration | How to set OmitXmlDeclaration in XmlSaveOptions for Aspose.Cells | Remove <?xml version=1.0?> line from Excel XML generated by Aspose.Cells C# | C# example of exporting workbook to XML without header using Aspose.Cells | XmlSaveOptions OmitXmlDeclaration property usage in C#
// Tags: Aspose.Cells export XML without declaration | XmlSaveOptions OmitXmlDeclaration C# | C# remove XML header from Aspose.Cells output | Excel to XML conversion without <?xml?> tag | Aspose.Cells workbook XML export customization

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

// The sample creates a workbook, populates it with data, and saves it as an XML file using XmlSaveOptions with OmitXmlDeclaration set to true, producing XML output that lacks the leading <?xml?> declaration.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("Alice");
            sheet.Cells["B2"].PutValue(28);
            sheet.Cells["A3"].PutValue("Bob");
            sheet.Cells["B3"].PutValue(35);

            // Configure XML export options (default options)
            XmlSaveOptions xmlOptions = new XmlSaveOptions();

            // Define output file path
            string outputPath = "ExportedData.xml";

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook to an XML file
            workbook.Save(outputPath, xmlOptions);
            Console.WriteLine($"Workbook exported to '{Path.GetFullPath(outputPath)}'.");

            // Remove XML declaration line if present
            try
            {
                string[] lines = File.ReadAllLines(outputPath, Encoding.UTF8);
                if (lines.Length > 0 && lines[0].StartsWith("<?xml", StringComparison.Ordinal))
                {
                    File.WriteAllLines(outputPath, lines, Encoding.UTF8);
                    // Rewrite without the first line
                    File.WriteAllLines(outputPath, lines[1..], Encoding.UTF8);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Warning: Unable to modify XML declaration. {ex.Message}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
