// Title: Add Email Validation with Input Prompt in Aspose.Cells for .NET (C#)
// Description: Creates a new workbook, applies a custom validation formula to a cell (e.g., A1) that checks for a basic email pattern, shows an input message titled "Email Input", configures a stop‑style error alert for invalid entries, and saves the file as EmailValidationDemo.xlsx using Aspose.Cells for C#.
// Keywords: Aspose.Cells | C# | email validation | custom data validation | input message | error alert | Excel workbook | ValidationType.Custom | ValidationAlertType.Stop | CellArea | data entry template
// Common Searches: Aspose.Cells email validation C# example | how to show input message for cell validation in Aspose.Cells | custom validation formula for email address in .NET | set stop error alert for Excel validation using Aspose | apply data validation to a single cell with Aspose.Cells
// Developer Intent: Generate an Excel file that enforces a valid email format in a designated cell and displays a helpful input prompt.
// Use Cases: Guide users to enter correctly formatted email addresses in data‑entry spreadsheets generated by a .NET application. | Prevent malformed email entries in exported reports by providing immediate validation feedback. | Standardize email input across multiple worksheets with a consistent input message and stop‑style error alert.
// AI Prompts: Write C# code with Aspose.Cells to apply the same email validation and input message to the range B2:B15. | Modify the validation formula so the domain part must end with at least two characters (e.g., .com, .org). | Show how to copy the email validation settings to every worksheet in an existing workbook.

using System;
using Aspose.Cells;

namespace AsposeCellsEmailValidation
{
    // Creates a new workbook, applies a custom validation formula to a cell (e.g., A1) that checks for a basic email pattern, shows an input message titled "Email Input", configures a stop‑style error alert for invalid entries, and saves the file as EmailValidationDemo.xlsx using Aspose.Cells for C#.
    public class EmailValidationDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet worksheet = workbook.Worksheets[0];

                // Define the cell (e.g., A1) where the email validation will be applied
                CellArea emailArea = new CellArea
                {
                    StartRow = 0,    // Row 1 (zero‑based)
                    EndRow = 0,
                    StartColumn = 0, // Column A (zero‑based)
                    EndColumn = 0
                };

                // Add a new validation to the worksheet for the defined area
                int validationIndex = worksheet.Validations.Add(emailArea);
                Validation emailValidation = worksheet.Validations[validationIndex];

                // Set validation type to Custom and provide a formula that checks for a basic email pattern
                // The formula ensures the cell contains "@" and "." and that "@" appears before the last "."
                emailValidation.Type = ValidationType.Custom;
                emailValidation.SetFormula1(
                    @"=AND(ISNUMBER(FIND(""@"",A1)), ISNUMBER(FIND(""."",A1)), FIND(""@"",A1) < FIND(""."",A1))",
                    false, // not R1C1 notation
                    false  // not locale‑specific
                );

                // Configure the input message that appears when the cell is selected
                emailValidation.ShowInput = true;
                emailValidation.InputTitle = "Email Input";
                emailValidation.InputMessage = "Please enter a valid email address (e.g., user@example.com)";

                // Configure the error alert that appears when an invalid email is entered
                emailValidation.ShowError = true;
                emailValidation.ErrorTitle = "Invalid Email";
                emailValidation.ErrorMessage = "The value entered is not a valid email address.";
                emailValidation.AlertStyle = ValidationAlertType.Stop;

                // Save the workbook to a file
                workbook.Save("EmailValidationDemo.xlsx");
                Console.WriteLine("Workbook saved successfully as EmailValidationDemo.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            EmailValidationDemo.Run();
        }
    }
}
