// Title: How to deserialize a cell's rich‑text JSON and reapply character formatting with Aspose.Cells for .NET
// AI Prompts: Read the JSON file generated by Cell.ToJson(), deserialize it using System.Text.Json into the custom CellJson classes, and apply the stored character ranges with FontSetting objects to a destination cell. | Modify the example to write the restored rich‑text to a different cell address or to multiple cells across a worksheet. | Enhance the deserialization routine to also process underline, strike‑through, and background color attributes when rebuilding FontSetting objects.
// Common Searches: Aspose.Cells .NET example for restoring rich text from Cell.ToJson output | C# code to apply character formatting from a JSON file to an Excel cell using Aspose.Cells | how to convert HTML color strings to System.Drawing.Color when rebuilding FontSetting in Aspose.Cells
// Tags: deserialize cell JSON Aspose.Cells .NET | reapply rich text character formatting Excel | FontSetting array from deserialized data | HTML color to System.Drawing.Color conversion Aspose | restore cell rich text using Cell.ToJson

using System;
using System.Drawing;
using System.IO;
using System.Text.Json;
using Aspose.Cells;
using Aspose.Cells.Drawing.Texts;

namespace AsposeCellsRichTextJsonDemo
{
    // Classes that match the JSON structure produced by Cell.ToJson()
    // The program creates a workbook, adds rich‑text (bold red "Hello" and italic blue "World!") to cell A1, serializes the cell to JSON, reads and deserializes the JSON into custom classes, rebuilds FontSetting objects for each character range, reapplies the formatting to a new workbook cell, and saves the result as RestoredRichText.xlsx.
    public class CellJson
    {
        public string? Value { get; set; }
        public CharacterJson[]? Characters { get; set; }
    }

    public class CharacterJson
    {
        public int StartIndex { get; set; }
        public int Length { get; set; }
        public FontJson? Font { get; set; }
    }

    public class FontJson
    {
        public bool? IsBold { get; set; }
        public bool? IsItalic { get; set; }
        public string? Color { get; set; } // HTML color string, e.g., "#FF0000"
        public string? Name { get; set; }
        public double? Size { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            try
            {
                // -----------------------------------------------------------------
                // Step 1: Create a workbook with rich‑text in cell A1 and save its JSON
                // -----------------------------------------------------------------
                Workbook wbSource = new Workbook();
                Worksheet wsSource = wbSource.Worksheets[0];
                Cell sourceCell = wsSource.Cells["A1"];
                sourceCell.PutValue("Hello World!");

                // Apply rich formatting: "Hello" bold red, "World!" italic blue
                FontSetting[] sourceSettings = new FontSetting[2];
                sourceSettings[0] = sourceCell.Characters(0, 5); // "Hello"
                sourceSettings[0].Font.IsBold = true;
                sourceSettings[0].Font.Color = Color.Red;

                sourceSettings[1] = sourceCell.Characters(6, 6); // "World!"
                sourceSettings[1].Font.IsItalic = true;
                sourceSettings[1].Font.Color = Color.Blue;

                sourceCell.SetCharacters(sourceSettings);

                // Serialize the cell to JSON and write to a file
                string cellJson = sourceCell.ToJson();
                File.WriteAllText("cell.json", cellJson);

                // -----------------------------------------------------------------
                // Step 2: Load the JSON, deserialize it, and reapply the rich‑text
                //         to the same cell (or another cell) in a new workbook
                // -----------------------------------------------------------------
                if (!File.Exists("cell.json"))
                {
                    Console.WriteLine("Error: cell.json not found.");
                    return;
                }

                string jsonFromFile = File.ReadAllText("cell.json");
                CellJson? deserialized = JsonSerializer.Deserialize<CellJson>(jsonFromFile);

                if (deserialized == null)
                {
                    Console.WriteLine("Error: Failed to deserialize JSON.");
                    return;
                }

                Workbook wbTarget = new Workbook();
                Worksheet wsTarget = wbTarget.Worksheets[0];
                Cell targetCell = wsTarget.Cells["A1"];

                // Put the plain text value first
                targetCell.PutValue(deserialized.Value ?? string.Empty);

                // Recreate the FontSetting objects based on the deserialized data
                if (deserialized.Characters != null && deserialized.Characters.Length > 0)
                {
                    FontSetting[] targetSettings = new FontSetting[deserialized.Characters.Length];

                    for (int i = 0; i < deserialized.Characters.Length; i++)
                    {
                        CharacterJson ch = deserialized.Characters[i];
                        // Obtain a FontSetting for the specific character range
                        FontSetting fs = targetCell.Characters(ch.StartIndex, ch.Length);

                        // Apply font properties if they exist in the JSON
                        if (ch.Font != null)
                        {
                            if (ch.Font.IsBold.HasValue) fs.Font.IsBold = ch.Font.IsBold.Value;
                            if (ch.Font.IsItalic.HasValue) fs.Font.IsItalic = ch.Font.IsItalic.Value;
                            if (!string.IsNullOrEmpty(ch.Font.Color))
                            {
                                // Convert HTML color string to System.Drawing.Color
                                try
                                {
                                    fs.Font.Color = ColorTranslator.FromHtml(ch.Font.Color);
                                }
                                catch
                                {
                                    // ignore invalid color
                                }
                            }
                            if (!string.IsNullOrEmpty(ch.Font.Name)) fs.Font.Name = ch.Font.Name;
                            if (ch.Font.Size.HasValue) fs.Font.Size = (int)ch.Font.Size.Value; // Aspose.Cells expects int size
                        }

                        targetSettings[i] = fs;
                    }

                    // Apply all character settings at once
                    targetCell.SetCharacters(targetSettings);
                }

                // Save the workbook with the restored rich‑text
                wbTarget.Save("RestoredRichText.xlsx");
                Console.WriteLine("Workbook saved as RestoredRichText.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
