// Title: Export a worksheet to PDF with background colors and borders using Aspose.Cells (C#)
// Description: Demonstrates how to create a workbook, style header and data cells, and save it as a PDF while preserving cell background colors and border formatting. The example uses Aspose.Cells PdfSaveOptions with ExportDocumentStructure enabled for exact visual fidelity in .NET applications.
// Keywords: Aspose.Cells PDF export | preserve cell background color | retain borders PDF Aspose | PdfSaveOptions ExportDocumentStructure | C# Excel to PDF formatting | .NET Aspose.Cells styling | export styled worksheet to PDF
// Common Searches: Aspose.Cells keep cell shading when converting to PDF | C# export Excel to PDF with borders intact | PdfSaveOptions ExportDocumentStructure example | How to retain formatting in PDF generated by Aspose.Cells | Export styled worksheet to PDF .NET
// Developer Intent: Generate a PDF from an Aspose.Cells worksheet that maintains all applied background colors and border styles.
// Use Cases: Produce printable price‑list PDFs that keep header shading and border thickness for brand consistency. | Create compliance‑oriented reports where cell shading and borders convey critical information. | Automate batch conversion of formatted Excel sheets to PDFs without losing visual cues.
// AI Prompts: Write C# code with Aspose.Cells to export a workbook to PDF while preserving background colors and borders. | Explain the effect of PdfSaveOptions.ExportDocumentStructure on formatting retention during PDF export. | Show how to extend the example to also keep font styles, number formats, and cell alignment in the PDF.

using System;
using Aspose.Cells;
using System.Drawing;

namespace AsposeCellsPdfExportDemo
{
    // Demonstrates how to create a workbook, style header and data cells, and save it as a PDF while preserving cell background colors and border formatting. The example uses Aspose.Cells PdfSaveOptions with ExportDocumentStructure enabled for exact visual fidelity in .NET applications.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet worksheet = workbook.Worksheets[0];

                // Populate sample data
                worksheet.Cells["A1"].PutValue("Product");
                worksheet.Cells["B1"].PutValue("Price");
                worksheet.Cells["A2"].PutValue("Apple");
                worksheet.Cells["B2"].PutValue(1.20);
                worksheet.Cells["A3"].PutValue("Banana");
                worksheet.Cells["B3"].PutValue(0.80);

                // Apply background color to header row
                Style headerStyle = workbook.CreateStyle();
                headerStyle.ForegroundColor = Color.LightGray;
                headerStyle.Pattern = BackgroundType.Solid;

                // Apply thick borders to header cells
                headerStyle.Borders[BorderType.BottomBorder].LineStyle = CellBorderType.Thick;
                headerStyle.Borders[BorderType.BottomBorder].Color = Color.Black;
                headerStyle.Borders[BorderType.TopBorder].LineStyle = CellBorderType.Thick;
                headerStyle.Borders[BorderType.TopBorder].Color = Color.Black;
                headerStyle.Borders[BorderType.LeftBorder].LineStyle = CellBorderType.Thick;
                headerStyle.Borders[BorderType.LeftBorder].Color = Color.Black;
                headerStyle.Borders[BorderType.RightBorder].LineStyle = CellBorderType.Thick;
                headerStyle.Borders[BorderType.RightBorder].Color = Color.Black;

                // Apply the header style to the header cells
                worksheet.Cells["A1"].SetStyle(headerStyle);
                worksheet.Cells["B1"].SetStyle(headerStyle);

                // Apply thin gray borders to data cells
                Style dataStyle = workbook.CreateStyle();
                dataStyle.Borders[BorderType.BottomBorder].LineStyle = CellBorderType.Thin;
                dataStyle.Borders[BorderType.BottomBorder].Color = Color.Gray;
                dataStyle.Borders[BorderType.TopBorder].LineStyle = CellBorderType.Thin;
                dataStyle.Borders[BorderType.TopBorder].Color = Color.Gray;
                dataStyle.Borders[BorderType.LeftBorder].LineStyle = CellBorderType.Thin;
                dataStyle.Borders[BorderType.LeftBorder].Color = Color.Gray;
                dataStyle.Borders[BorderType.RightBorder].LineStyle = CellBorderType.Thin;
                dataStyle.Borders[BorderType.RightBorder].Color = Color.Gray;

                // Apply the data style to the range A2:B3
                worksheet.Cells.CreateRange("A2:B3").SetStyle(dataStyle);

                // Create PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    // Preserve document structure (helps retain formatting)
                    ExportDocumentStructure = true
                };

                // Save the workbook as PDF with the specified options
                workbook.Save("WorksheetWithFormatting.pdf", pdfOptions);

                Console.WriteLine("PDF exported successfully with background colors and borders preserved.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
