// Title: Enforce unique email addresses in column AK using Aspose.Cells for .NET
// Description: Creates a new workbook, defines a validation range for rows 2‑1000 in column AK, and adds a custom validation that uses the COUNTIF formula "=COUNTIF($AK:$AK,AK1)=1" to guarantee each email is unique. An error alert with a custom title and message is shown for duplicates, and the file is saved as EmailUniqueValidation.xlsx.
// Keywords: Aspose.Cells | C# | .NET | unique email validation | Excel data validation | COUNTIF formula | column AK | duplicate email detection | custom validation | Aspose.Cells API
// Common Searches: Aspose.Cells enforce unique email column | C# data validation duplicate email Excel | COUNTIF custom validation Aspose.Cells | how to prevent duplicate emails in Excel with Aspose | set error alert for duplicate values Aspose.Cells
// Developer Intent: Add a custom validation rule that blocks duplicate email entries in column AK.
// Use Cases: Ensure a mailing‑list workbook contains only distinct email addresses. | Provide immediate feedback in a data‑import template when a user repeats an email. | Automate quality checks for Excel reports generated by .NET applications.
// AI Prompts: Generate C# code with Aspose.Cells that adds a COUNTIF‑based validation to column AK to enforce email uniqueness and shows a custom error message. | Show how to create a data‑validation range for rows 2‑1000 in column AK using Aspose.Cells for .NET. | Explain how to modify the validation formula for case‑insensitive duplicate email detection in Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsEmailUniqueValidation
{
    // Creates a new workbook, defines a validation range for rows 2‑1000 in column AK, and adds a custom validation that uses the COUNTIF formula "=COUNTIF($AK:$AK,AK1)=1" to guarantee each email is unique. An error alert with a custom title and message is shown for duplicates, and the file is saved as EmailUniqueValidation.xlsx.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (lifecycle rule: create)
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet worksheet = workbook.Worksheets[0];

            // Sample data: header and some email addresses in column AK (index 36)
            worksheet.Cells["AK1"].PutValue("Email");
            worksheet.Cells["AK2"].PutValue("alice@example.com");
            worksheet.Cells["AK3"].PutValue("bob@example.com");
            worksheet.Cells["AK4"].PutValue("alice@example.com"); // duplicate for demonstration

            // Add a custom data validation to column AK to enforce uniqueness
            // Define the range for validation (rows 2 to 1000 in column AK)
            CellArea validationArea = CellArea.CreateCellArea(1, 36, 999, 36); // zero‑based indices

            // Create the validation and retrieve it
            ValidationCollection validations = worksheet.Validations;
            int validationIndex = validations.Add(validationArea);
            Validation validation = validations[validationIndex];

            // Set validation type to Custom and provide a formula that returns TRUE only for unique values
            validation.Type = ValidationType.Custom;
            // Formula uses COUNTIF to count occurrences of the current cell's value in the whole column
            // It must evaluate to TRUE for a valid (unique) entry
            validation.Formula1 = "=COUNTIF($AK:$AK,AK1)=1";

            // Configure the error alert that will be shown when a duplicate is entered
            validation.ShowError = true;
            validation.ErrorTitle = "Duplicate Email";
            validation.ErrorMessage = "Email address must be unique.";

            // Save the workbook (lifecycle rule: save)
            workbook.Save("EmailUniqueValidation.xlsx");
        }
    }
}
