// Title: Log Aspose.Cells load warnings (unsupported features) using C# IWarningCallback
// Description: Demonstrates a custom IWarningCallback that captures each WarningInfo (type and description) during Workbook loading and appends it to a log file via LoadOptions. Ideal for auditing unsupported formulas, charts, or other Excel features.
// Keywords: Aspose.Cells load warnings | C# IWarningCallback example | log unsupported Excel features | LoadOptions WarningCallback | Aspose.Cells workbook audit | write load warnings to file | Excel import troubleshooting | GitHub Aspose.Cells sample
// Common Searches: Aspose.Cells log load warnings C# | How to capture unsupported feature warnings in Aspose.Cells | IWarningCallback write warnings to text file | LoadOptions WarningCallback example .NET | Record Excel load warnings with Aspose
// Developer Intent: Capture every load‑time warning generated by Aspose.Cells when opening a workbook and persist the messages to a log file for later analysis.
// Use Cases: Create an audit trail of legacy Excel files that contain formulas or objects not supported by Aspose.Cells. | Automate quality checks in a data‑migration pipeline by flagging workbooks with load warnings before further processing. | Provide developers and support teams with detailed warning logs to speed up troubleshooting of import failures.
// AI Prompts: Show a C# snippet that uses Aspose.Cells LoadOptions with a custom IWarningCallback to write load warnings to a log file. | Explain how to extend the warning logger to include timestamps and categorize warnings by severity level. | Describe how to retrieve and filter specific WarningInfo types (e.g., UnsupportedFormula, MissingFont) within the Warning method.

using System;
using System.IO;
using Aspose.Cells;

// Demonstrates a custom IWarningCallback that captures each WarningInfo (type and description) during Workbook loading and appends it to a log file via LoadOptions. Ideal for auditing unsupported formulas, charts, or other Excel features.
public class LoadWarningLogger : IWarningCallback
{
    private readonly string _logPath;

    public LoadWarningLogger(string logPath)
    {
        _logPath = logPath;
    }

    // Called by Aspose.Cells for each warning encountered during load
    public void Warning(WarningInfo warningInfo)
    {
        string message = $"Warning Type: {warningInfo.Type}, Description: {warningInfo.Description}";
        File.AppendAllText(_logPath, message + Environment.NewLine);
    }
}

public class Program
{
    public static void Main()
    {
        // Paths for input workbook and warning log
        string inputFile = "sample_with_unsupported_features.xlsx";
        string logFile = "load_warnings.log";

        try
        {
            // Ensure the log file exists and is empty
            File.WriteAllText(logFile, string.Empty);

            // If the input workbook does not exist, create an empty one to avoid FileNotFoundException
            if (!File.Exists(inputFile))
            {
                var emptyWb = new Workbook();
                emptyWb.Save(inputFile);
            }

            // Set up load options with the custom warning callback
            var loadOptions = new LoadOptions
            {
                WarningCallback = new LoadWarningLogger(logFile)
            };

            // Load the workbook; any load warnings will be captured by the callback
            var workbook = new Workbook(inputFile, loadOptions);

            // Additional processing on the workbook can be performed here
            // ...

            // Example: save the workbook after processing (optional)
            // workbook.Save("processed_output.xlsx");
        }
        catch (Exception ex)
        {
            // Log unexpected errors to the console (or to a separate error log if desired)
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
