// Title: Load an Excel workbook, set the first worksheet's printer paper size to Letter, and save it as PDF with Aspose.Cells for .NET
// AI Prompts: Load a .xlsx file, change the first worksheet's PageSetup.PaperSize to PaperLetter, and export the workbook to PDF using Aspose.Cells in C#. | Create the output folder if it does not exist, then save the workbook as a PDF while guaranteeing the worksheet uses Letter paper dimensions. | Implement error handling for a missing input Excel file and perform the conversion to PDF with a specific printer paper size via Aspose.Cells. | Provide guidance on inspecting the generated PDF to confirm the expected number of pages after saving the workbook.
// Common Searches: Aspose.Cells C# set worksheet printer paper size to Letter before PDF conversion | Convert Excel to PDF with Letter page size using Aspose.Cells .NET | How to ensure PDF output uses Letter paper size when saving workbook with Aspose.Cells | C# code to create output folder and export Excel workbook to PDF with custom page setup | Check number of pages in PDF generated by Aspose.Cells after saving workbook
// Tags: worksheet page setup with PaperLetter Aspose.Cells | custom paper size PDF export using Aspose.Cells C# | excel workbook conversion to PDF with page setup adjustments | error handling for missing Excel file Aspose.Cells | ensure output directory exists before PDF save Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// // Loads 'input.xlsx', sets the first worksheet's printer paper size to Letter, creates the output directory if needed, and saves the workbook as 'output.pdf' using Aspose.Cells with basic error handling.
class Program
{
    static void Main()
    {
        try
        {
            // Define input and output file paths
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the existing workbook
            Workbook workbook = new Workbook(inputPath);

            // Access the first worksheet (adjust index if needed)
            Worksheet sheet = workbook.Worksheets[0];

            // Set the printer paper size to Letter
            sheet.PageSetup.PaperSize = PaperSizeType.PaperLetter;

            // Optional: ensure the worksheet fits on a single page
            // sheet.PageSetup.FitToPagesWide = 1;
            // sheet.PageSetup.FitToPagesTall = 1;

            // NOTE: Aspose.Cells does not expose a direct GetPagesCount method on PageSetup.
            // If page count verification is required, it can be performed after saving to PDF
            // by inspecting the generated PDF. For this example, we skip the verification.

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as PDF
            workbook.Save(outputPath, SaveFormat.Pdf);
            Console.WriteLine($"Workbook successfully saved as PDF to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
