// Title: Aspose.Cells C# – Compare PDF sizes for A5 vs A3 paper settings
// Description: A C# example that creates an Excel workbook, sets its default printer paper size to A5, saves it as XLSX, converts it to PDF and records the file size. The same XLSX is then re‑loaded with LoadOptions.SetPaperSize(PaperA3), converted to PDF again, and the two PDF sizes are compared and printed to the console.
// Keywords: Aspose.Cells C# paper size | WorkbookSettings.PaperSize A5 | LoadOptions.SetPaperSize A3 | PDF file size comparison Aspose.Cells | Excel to PDF Aspose.Cells | C# Aspose.Cells PDF rendering | printer paper size PDF output
// Common Searches: Aspose.Cells change paper size when loading workbook | compare PDF size A5 and A3 Aspose.Cells | LoadOptions SetPaperSize example C# | WorkbookSettings PaperSize effect on PDF size | C# generate PDF from Excel with different paper sizes
// Developer Intent: Generate PDFs from the same workbook using A5 and A3 paper settings and determine which setting produces a larger file.
// Use Cases: Create an Excel workbook, set WorkbookSettings.PaperSize to A5, save as XLSX, and export to PDF to capture the A5 PDF size. | Reload the saved XLSX with LoadOptions.SetPaperSize(PaperA3), export to PDF, and capture the A3 PDF size. | Print a side‑by‑side size comparison to the console or log for performance or storage analysis.
// AI Prompts: Write C# code that loads an existing Excel file with Aspose.Cells, applies LoadOptions.SetPaperSize(PaperA3), and saves it as a PDF. | Explain how WorkbookSettings.PaperSize and LoadOptions.SetPaperSize influence the dimensions and file size of PDFs generated by Aspose.Cells. | Suggest a loop that iterates over multiple paper sizes (A5, A4, A3) to generate PDFs and automatically log each file’s size.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPaperSizeComparison
{
    // A C# example that creates an Excel workbook, sets its default printer paper size to A5, saves it as XLSX, converts it to PDF and records the file size. The same XLSX is then re‑loaded with LoadOptions.SetPaperSize(PaperA3), converted to PDF again, and the two PDF sizes are compared and printed to the console.
    class Program
    {
        static void Main()
        {
            // Path for intermediate Excel file
            string excelPath = "sample.xlsx";

            // -----------------------------------------------------------------
            // Step 1: Create a workbook, add sample data and set paper size to A5
            // -----------------------------------------------------------------
            Workbook wbA5 = new Workbook();                         // create workbook
            Worksheet wsA5 = wbA5.Worksheets[0];
            // Populate some data
            wsA5.Cells["A1"].PutValue("Item");
            wsA5.Cells["B1"].PutValue("Quantity");
            wsA5.Cells["A2"].PutValue("Apples");
            wsA5.Cells["B2"].PutValue(10);
            wsA5.Cells["A3"].PutValue("Bananas");
            wsA5.Cells["B3"].PutValue(20);
            // Set default print paper size to A5 via WorkbookSettings
            wbA5.Settings.PaperSize = PaperSizeType.PaperA5;       // rule: WorkbookSettings.PaperSize
            // Save the workbook to disk (used for re‑loading later)
            wbA5.Save(excelPath, SaveFormat.Xlsx);                // lifecycle rule: save

            // -----------------------------------------------------------------
            // Step 2: Render the A5 workbook to PDF and record file size
            // -----------------------------------------------------------------
            string pdfA5Path = "output_A5.pdf";
            wbA5.Save(pdfA5Path, SaveFormat.Pdf);                 // save as PDF
            long sizeA5 = new FileInfo(pdfA5Path).Length;

            // -----------------------------------------------------------------
            // Step 3: Load the same workbook with printer paper size set to A3
            // -----------------------------------------------------------------
            LoadOptions loadOpts = new LoadOptions();              // create load options
            loadOpts.SetPaperSize(PaperSizeType.PaperA3);          // rule: LoadOptions.SetPaperSize
            Workbook wbA3 = new Workbook(excelPath, loadOpts);     // load workbook with A3 setting

            // -----------------------------------------------------------------
            // Step 4: Render the A3 workbook to PDF and record file size
            // -----------------------------------------------------------------
            string pdfA3Path = "output_A3.pdf";
            wbA3.Save(pdfA3Path, SaveFormat.Pdf);                 // save as PDF
            long sizeA3 = new FileInfo(pdfA3Path).Length;

            // -----------------------------------------------------------------
            // Step 5: Compare and output the file sizes
            // -----------------------------------------------------------------
            Console.WriteLine($"PDF size with A5 paper: {sizeA5} bytes");
            Console.WriteLine($"PDF size with A3 paper: {sizeA3} bytes");
            if (sizeA3 > sizeA5)
                Console.WriteLine("A3 PDF is larger than A5 PDF.");
            else if (sizeA3 < sizeA5)
                Console.WriteLine("A3 PDF is smaller than A5 PDF.");
            else
                Console.WriteLine("Both PDFs have the same size.");
        }
    }
}
