// Title: C# – Save an Aspose.Cells workbook to PDF without charts, preserving cell formatting
// Description: Demonstrates how to create (or load) an Aspose.Cells workbook, apply bold text and numeric formatting, and export it directly to a PDF file using SaveFormat.Pdf while keeping all cell styles intact and omitting any chart objects.
// Keywords: Aspose.Cells PDF export C# | save workbook as PDF without charts | preserve cell formatting Aspose.Cells | SaveFormat.Pdf Aspose.Cells | Excel to PDF conversion C# | chart‑free PDF Aspose.Cells | cell style retention PDF export
// Common Searches: Aspose.Cells export workbook to PDF without charts | C# save Excel file as PDF preserving formatting | how to keep number format when converting Excel to PDF with Aspose | remove charts from PDF generated by Aspose.Cells | Aspose.Cells PDF options for styling
// Developer Intent: Export a workbook to PDF, keep all cell styles, and ensure no chart objects appear in the output.
// Use Cases: Generate printable reports that contain only data tables with bold headers and precise number formats. | Create PDF invoices from an Excel template while maintaining the original layout and styling. | Archive spreadsheets as PDF documents, stripping out charts but preserving the visual appearance of cells.
// AI Prompts: Write C# code using Aspose.Cells that loads an existing workbook, removes every chart, and saves it as a PDF while retaining all cell formatting. | Explain which Aspose.Cells PDF save options control chart inclusion and style preservation during conversion. | Show how to customize number and font formatting so they survive the Excel‑to‑PDF conversion with Aspose.Cells.

using System;
using Aspose.Cells;

// Demonstrates how to create (or load) an Aspose.Cells workbook, apply bold text and numeric formatting, and export it directly to a PDF file using SaveFormat.Pdf while keeping all cell styles intact and omitting any chart objects.
class SaveWorkbookToPdf
{
    static void Main()
    {
        // Create a new workbook (or load an existing one)
        Workbook workbook = new Workbook(); // lifecycle: create

        // Add some data and apply formatting to demonstrate preservation
        Worksheet ws = workbook.Worksheets[0];
        ws.Cells["A1"].PutValue("Header");
        ws.Cells["A1"].GetStyle().Font.IsBold = true; // bold header
        ws.Cells["A2"].PutValue(123.45);
        ws.Cells["A2"].GetStyle().Number = 2; // two decimal places

        // Save the workbook as PDF while keeping original cell formatting
        workbook.Save("output.pdf", SaveFormat.Pdf); // lifecycle: save
    }
}
