// Title: C# – Export an Aspose.Cells workbook to PDF without charts while preserving cell formatting
// Description: Creates a new Workbook, fills cells A1:B3 with sample data, applies a bold style to the header row, and saves the file as a PDF using SaveFormat.Pdf. The resulting PDF contains no charts and retains all original cell formatting.
// Keywords: Aspose.Cells PDF export C# | save workbook to PDF without charts | preserve cell styles Aspose.Cells | C# Excel to PDF conversion | Aspose.Cells SaveFormat.Pdf example
// Common Searches: Aspose.Cells export to PDF without charts C# | how to keep cell formatting when saving Excel as PDF using Aspose | C# convert workbook to PDF preserving styles | remove charts from PDF generated by Aspose.Cells | save Excel file as PDF with bold headers Aspose
// Developer Intent: Generate a PDF from an Aspose.Cells workbook that excludes charts and keeps the original cell formatting intact.
// Use Cases: Produce printable reports from data tables where visual charts are unnecessary. | Create PDF invoices or statements that require bold headings and styled cells. | Archive Excel worksheets as PDFs for compliance, ensuring all formatting is retained while omitting chart graphics.
// AI Prompts: Write C# code using Aspose.Cells to create a workbook, add data, apply a bold header style, and save it as a PDF without including any charts. | Show how to convert an existing Excel file to PDF with Aspose.Cells while preserving all cell formatting and excluding chart objects. | Explain the impact of SaveFormat.Pdf on cell styles and chart inclusion in Aspose.Cells.

using System;
using Aspose.Cells;

// Creates a new Workbook, fills cells A1:B3 with sample data, applies a bold style to the header row, and saves the file as a PDF using SaveFormat.Pdf. The resulting PDF contains no charts and retains all original cell formatting.
class Program
{
    static void Main()
    {
        // Create a new workbook (lifecycle rule: create)
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];

        // Populate some sample data
        sheet.Cells["A1"].PutValue("Product");
        sheet.Cells["B1"].PutValue("Quantity");
        sheet.Cells["A2"].PutValue("Apples");
        sheet.Cells["B2"].PutValue(150);
        sheet.Cells["A3"].PutValue("Bananas");
        sheet.Cells["B3"].PutValue(200);

        // Apply simple formatting to preserve original cell appearance
        // Make header row bold
        Style headerStyle = workbook.CreateStyle();
        headerStyle.Font.IsBold = true;
        StyleFlag headerFlag = new StyleFlag();
        headerFlag.FontBold = true;
        sheet.Cells.CreateRange("A1:B1").ApplyStyle(headerStyle, headerFlag);

        // Save the workbook to PDF while keeping all cell formatting (lifecycle rule: save)
        workbook.Save("ChartFreeWorkbook.pdf", SaveFormat.Pdf);
    }
}
