// Title: Set PdfSaveOptions.CompressionLevel to High for Small PDFs in Aspose.Cells (C#)
// Description: Demonstrates how to create a workbook, apply PdfSaveOptions with Flate compression and MinimumSize optimization, and save it as a compact PDF while preserving visual quality.
// Keywords: Aspose.Cells PDF compression C# | PdfSaveOptions high compression | Flate PDF compression Aspose | MinimumSize PDF optimization | reduce PDF file size .NET
// Common Searches: Aspose.Cells set PDF compression level | C# save workbook as small PDF | PdfSaveOptions Flate compression example | minimum size PDF export Aspose.Cells | how to shrink PDF generated by Aspose.Cells
// Developer Intent: Apply high‑level compression when exporting a workbook to PDF to minimize file size without losing visual fidelity.
// Use Cases: Email‑friendly PDF reports from large spreadsheets | Compact PDF invoices for archival storage | Web‑ready PDF downloads of data‑heavy worksheets
// AI Prompts: Show C# code that configures PdfSaveOptions for maximum compression in Aspose.Cells. | Explain the impact of PdfCompressionCore.Flate and PdfOptimizationType.MinimumSize on PDF size. | Give step‑by‑step instructions to export a workbook to a high‑compression PDF using Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to create a workbook, apply PdfSaveOptions with Flate compression and MinimumSize optimization, and save it as a compact PDF while preserving visual quality.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample data for PDF compression");

        // Configure PDF save options with high compression
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        // Set the core compression algorithm to Flate (high compression)
        pdfOptions.PdfCompression = PdfCompressionCore.Flate;
        // Optional: further reduce file size by using minimum size optimization
        pdfOptions.OptimizationType = PdfOptimizationType.MinimumSize;

        // Save the workbook as a PDF using the configured options
        workbook.Save("output_high_compression.pdf", pdfOptions);
    }
}
