// Title: Inject a custom CSS class into the <body> tag of HTML generated from an Excel workbook using Aspose.Cells for .NET
// AI Prompts: Write C# code that converts an Excel workbook to HTML with Aspose.Cells and then injects a custom CSS class into the <body> element. | Demonstrate how to read the HTML file saved by Aspose.Cells, apply a regular expression to add a class attribute to the body tag, and save the changes. | Create a helper method that receives the HTML output from Aspose.Cells and returns the markup with an additional CSS class on the body element.
// Common Searches: how to inject a CSS class into the body of HTML exported from Excel using Aspose.Cells C# | Aspose.Cells .NET post‑processing HTML to add custom body class | C# regex replace <body> tag in HTML generated by Aspose.Cells | add class attribute to HTML body after Excel to HTML conversion with Aspose.Cells | modify Aspose.Cells saved HTML for additional styling in .NET
// Tags: Aspose.Cells HTML export add body class | C# regex post‑process generated HTML | inject custom CSS class into HTML body .NET | Excel to HTML conversion styling Aspose.Cells | post‑process Aspose.Cells HTML output

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// Loads an Excel workbook, saves it as HTML using Aspose.Cells, reads the resulting file, uses a regular expression to insert a custom CSS class into the <body> tag, and writes the updated HTML back to disk.
class Program
{
    static void Main()
    {
        // Load the Excel workbook (load rule)
        Workbook workbook = new Workbook("input.xlsx");

        // Convert the workbook to HTML (save rule)
        workbook.Save("output.html", SaveFormat.Html);

        // Read the generated HTML file
        string htmlContent = File.ReadAllText("output.html");

        // Append a custom CSS class to the <body> element
        // This replaces <body> or <body ...> with <body ... class="my-custom-class">
        string pattern = @"<body([^>]*)>";
        string replacement = "<body$1 class=\"my-custom-class\">";
        string updatedHtml = Regex.Replace(htmlContent, pattern, replacement, RegexOptions.IgnoreCase);

        // Write the modified HTML back to the file
        File.WriteAllText("output.html", updatedHtml);
    }
}
