// Title: Apply conditional formatting to cells in Aspose.Cells and verify red background preservation in HTML output with a custom TableCssId (C#)
// AI Prompts: Create a workbook, add a conditional formatting rule that applies a solid red background to cells with values greater than 50, and save the workbook as HTML using HtmlSaveOptions with TableCssId set to a chosen identifier. | Read the generated HTML file, confirm that the <table> element contains the specified id attribute and that the CSS includes the red background color for the formatted cells.
// Common Searches: Aspose.Cells C# export conditional formatting to HTML with custom table id | how to keep cell background colors when converting workbook to HTML using Aspose.Cells | verify that conditional formatting appears in HTML output generated by Aspose.Cells | set a specific id attribute on the HTML table produced by Aspose.Cells | example of conditional formatting rule greater than 50 and HTML conversion in C#
// Tags: conditional formatting export to HTML Aspose.Cells | HTML export options custom table identifier | verify red cell style in generated HTML | C# Aspose.Cells conditional formatting rule example | preserve cell background color during HTML conversion

using System;
using System.IO;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The sample creates a new workbook, fills cells A1:A10 with multiples of ten, adds a conditional formatting rule that gives a solid red background to cells whose values exceed 50, saves the workbook as HTML using HtmlSaveOptions with TableCssId set to "myTable", and then reads the HTML file to ensure the table element has the expected id and that the red background style is present.
class ConditionalFormattingHtmlDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Data";

            // Populate sample data in cells A1:A10
            for (int i = 0; i < 10; i++)
            {
                sheet.Cells[i, 0].PutValue(i * 10); // Values: 0,10,20,...,90
            }

            // Define the range to which the conditional formatting will be applied (A1:A10)
            CellArea area = new CellArea
            {
                StartRow = 0,
                StartColumn = 0,
                EndRow = 9,
                EndColumn = 0
            };

            // Add a conditional formatting rule to the worksheet
            int cfIndex = sheet.ConditionalFormattings.Add();
            var cf = sheet.ConditionalFormattings[cfIndex]; // ConditionalFormatting object
            cf.AddArea(area);

            // Create a condition: Cell value > 50
            int conditionIndex = cf.AddCondition(FormatConditionType.CellValue,
                                                 OperatorType.GreaterThan,
                                                 "50", null);
            FormatCondition condition = cf[conditionIndex];

            // Define the style to apply when the condition is met (red background)
            Style style = workbook.CreateStyle();
            style.ForegroundColor = Color.Red;
            style.Pattern = BackgroundType.Solid;
            condition.Style = style;

            // Prepare HTML save options with a specific TableCssId
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                TableCssId = "myTable" // ID used in the generated HTML table
            };

            string htmlPath = "ConditionalFormattingOutput.html";

            // Save the workbook as HTML
            workbook.Save(htmlPath, htmlOptions);

            // Verify that the HTML file was created and contains expected markers
            if (File.Exists(htmlPath))
            {
                string htmlContent = File.ReadAllText(htmlPath);
                bool hasTableId = htmlContent.Contains("id=\"myTable\"");
                bool hasRedStyle = htmlContent.Contains("background-color:#FF0000"); // Aspose uses hex color

                Console.WriteLine("HTML generated: " + Path.GetFullPath(htmlPath));
                Console.WriteLine("TableCssId present: " + hasTableId);
                Console.WriteLine("Red background style present: " + hasRedStyle);
            }
            else
            {
                Console.WriteLine("Failed to generate HTML file.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
