// Title: Aspose.Cells .NET: Apply Conditional Formatting and Export to HTML with Custom TableCssId
// Description: Shows how to create a workbook, add a conditional formatting rule that colors cells greater than 50 red, export the sheet to HTML using HtmlSaveOptions.TableCssId, and programmatically verify that the custom table ID and the red background style are present in the generated HTML file.
// Keywords: Aspose.Cells | C# | .NET | conditional formatting | HTML export | TableCssId | verify HTML output | Excel to HTML | cell style preservation | HtmlSaveOptions
// Common Searches: Aspose.Cells export conditional formatting to HTML | HtmlSaveOptions TableCssId example C# | Check conditional formatting in HTML generated by Aspose.Cells | C# verify cell background color in exported HTML
// Developer Intent: Add a conditional formatting rule to a worksheet, export the workbook as HTML with a specific CSS identifier for the table, and confirm that the formatting is retained in the HTML output.
// Use Cases: Generate web‑ready Excel reports where values above a threshold are highlighted. | Automate quality checks that HTML exports preserve conditional formatting styles. | Assign distinct CSS selectors to multiple tables on a page for independent styling.
// AI Prompts: Provide C# code using Aspose.Cells to format cells >100 with orange background, export to HTML with TableCssId='sales-table', and assert the CSS appears in the output. | Explain how Aspose.Cells renders conditional formatting in HTML and how to customize the table selector via HtmlSaveOptions.TableCssId. | Create a unit test in C# that verifies the generated HTML contains the expected background‑color rule for cells meeting a conditional formatting condition.

using System;
using System.Drawing;
using System.IO;
using Aspose.Cells;

namespace ConditionalFormattingHtmlDemo
{
    // Shows how to create a workbook, add a conditional formatting rule that colors cells greater than 50 red, export the sheet to HTML using HtmlSaveOptions.TableCssId, and programmatically verify that the custom table ID and the red background style are present in the generated HTML file.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data
            sheet.Cells["A1"].PutValue(10);
            sheet.Cells["A2"].PutValue(60);
            sheet.Cells["A3"].PutValue(30);
            sheet.Cells["A4"].PutValue(80);
            sheet.Cells["A5"].PutValue(45);

            // Add conditional formatting: highlight cells > 50 with red background
            int cfIndex = sheet.ConditionalFormattings.Add();
            FormatConditionCollection fcc = sheet.ConditionalFormattings[cfIndex];

            // Define the range A1:A5
            CellArea area = new CellArea
            {
                StartRow = 0,
                EndRow = 4,
                StartColumn = 0,
                EndColumn = 0
            };
            fcc.AddArea(area);

            // Add the condition
            int conditionIdx = fcc.AddCondition(FormatConditionType.CellValue, OperatorType.GreaterThan, "50", null);
            FormatCondition condition = fcc[conditionIdx];
            condition.Style.BackgroundColor = Color.Red; // Apply red background

            // Configure HTML save options with a custom TableCssId
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            saveOptions.TableCssId = "custom-table-id";

            // Save the workbook as HTML
            string htmlPath = "ConditionalFormattingOutput.html";
            workbook.Save(htmlPath, saveOptions);
            Console.WriteLine($"HTML file saved to: {htmlPath}");

            // Verify that the TableCssId attribute and conditional formatting are present in the HTML
            string htmlContent = File.ReadAllText(htmlPath);

            bool hasTableCssId = htmlContent.Contains($"TableCssId=\"custom-table-id\"");
            bool hasRedBackground = htmlContent.Contains("background-color:#FF0000") || // Hex representation
                                    htmlContent.Contains("background-color:red");   // Named color

            Console.WriteLine($"TableCssId applied: {hasTableCssId}");
            Console.WriteLine($"Conditional formatting (red background) preserved: {hasRedBackground}");
        }
    }
}
