// Title: Exclude Unused Styles When Exporting to HTML with Aspose.Cells (.NET)
// Description: C# example that creates a workbook, defines a named style (red, bold, 12 pt) and applies it to range A1:C3, adds an unused style, saves the file as HTML with HtmlSaveOptions.ExcludeUnusedStyles enabled, and programmatically verifies that only the applied style appears in the generated HTML.
// Keywords: Aspose.Cells HTML export | ExcludeUnusedStyles | custom style range C# | Aspose.Cells style verification | reduce CSS Aspose.Cells | HtmlSaveOptions example | Aspose.Cells .NET styling
// Common Searches: how to exclude unused styles in Aspose.Cells HTML export | apply named style to a cell range Aspose.Cells C# | verify style presence in generated HTML Aspose.Cells | Aspose.Cells reduce CSS size when saving as HTML | HtmlSaveOptions.ExcludeUnusedStyles usage
// Developer Intent: Apply a custom style to a specific range, export the workbook to HTML without emitting unused style definitions, and confirm that only the used style is present in the output.
// Use Cases: Generate clean HTML reports with minimal CSS by exporting only the styles that are actually used. | Create reusable named styles, apply a subset, and ensure unused styles do not bloat the HTML file. | Automate validation of HTML output to guarantee that style names appear or are omitted as expected.
// AI Prompts: Write C# code that defines a red bold style, applies it to A1:C3, saves the workbook as HTML with ExcludeUnusedStyles=true, and checks the HTML for the style name. | Explain the effect of HtmlSaveOptions.ExcludeUnusedStyles on the CSS generated by Aspose.Cells. | Provide a step‑by‑step guide to programmatically verify that unused styles are omitted from the HTML file after export.

using System;
using System.IO;
using System.Drawing;
using Aspose.Cells;
using AsposeRange = Aspose.Cells.Range;

namespace AsposeCellsCustomStyleHtmlDemo
{
    // C# example that creates a workbook, defines a named style (red, bold, 12 pt) and applies it to range A1:C3, adds an unused style, saves the file as HTML with HtmlSaveOptions.ExcludeUnusedStyles enabled, and programmatically verifies that only the applied style appears in the generated HTML.
    class Program
    {
        static void Main()
        {
            try
            {
                // -------------------- Create workbook and worksheet --------------------
                Workbook workbook = new Workbook();                     // create workbook
                Worksheet sheet = workbook.Worksheets[0];              // get first worksheet

                // -------------------- Define and apply a used style --------------------
                Style usedStyle = workbook.CreateStyle();              // create a new style
                usedStyle.Name = "UsedStyle";                          // give it a name (for verification)
                usedStyle.Font.Color = Color.Red;                      // red font
                usedStyle.Font.IsBold = true;                          // bold
                usedStyle.Font.Size = 12;

                // Apply the used style to a range A1:C3
                AsposeRange usedRange = sheet.Cells.CreateRange("A1", "C3");
                usedRange.SetStyle(usedStyle);

                // Fill the range with sample data
                for (int row = 0; row < 3; row++)
                {
                    for (int col = 0; col < 3; col++)
                    {
                        sheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                    }
                }

                // -------------------- Define an unused style (do NOT apply) --------------------
                Style unusedStyle = workbook.CreateStyle();            // create another style
                unusedStyle.Name = "UnusedStyle";                      // name it for later check
                unusedStyle.Font.Color = Color.Blue;                  // blue font
                unusedStyle.Font.IsItalic = true;                     // italic
                unusedStyle.Font.Size = 10;
                // Note: we intentionally do NOT apply this style to any cell.

                // -------------------- Save workbook as HTML with ExcludeUnusedStyles = true --------------------
                HtmlSaveOptions saveOptions = new HtmlSaveOptions
                {
                    ExcludeUnusedStyles = true // ensure unused styles are excluded
                };
                string htmlPath = "StyledOutput.html";

                // Save the workbook
                workbook.Save(htmlPath, saveOptions);

                // -------------------- Verification: ensure only used style appears in HTML --------------------
                if (File.Exists(htmlPath))
                {
                    string htmlContent = File.ReadAllText(htmlPath);

                    bool usedStyleFound = htmlContent.Contains("UsedStyle");
                    bool unusedStyleFound = htmlContent.Contains("UnusedStyle");

                    Console.WriteLine($"Used style present in HTML: {usedStyleFound}");
                    Console.WriteLine($"Unused style present in HTML (should be false): {unusedStyleFound}");

                    if (usedStyleFound && !unusedStyleFound)
                        Console.WriteLine("Verification passed: only used styles are present.");
                    else
                        Console.WriteLine("Verification failed: unused styles were not excluded.");
                }
                else
                {
                    Console.WriteLine($"Error: HTML file '{htmlPath}' was not created.");
                }

                // -------------------- Optional: display style pool counts --------------------
                Console.WriteLine($"Total styles in pool: {workbook.CountOfStylesInPool}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
