// Title: Apply Custom CSS to Table Headers When Exporting an Aspose.Cells Workbook to HTML (C#)
// Description: Demonstrates how to export a workbook as a single HTML file with row/column headings enabled, inject custom CSS for <th> elements and a .heading class, and style tables and cells for consistent appearance.
// Keywords: Aspose.Cells HTML export | custom CSS Aspose.Cells | ExportRowColumnHeadings | SaveAsSingleFile | C# Aspose.Cells example | style table headers HTML | embedded CSS in HTML output
// Common Searches: Aspose.Cells add CSS to th elements | export workbook to single HTML file with styles | how to use ExportRowColumnHeadings in Aspose.Cells | embed custom CSS in Aspose.Cells HTML export | C# Aspose.Cells HTML styling example
// Developer Intent: Inject custom CSS into the HTML generated by Aspose.Cells so that table header cells share a consistent style.
// Use Cases: Create branded HTML reports with uniformly styled table headers. | Generate a self‑contained HTML file for offline viewing or email distribution. | Apply a reusable .heading class to both <th> and custom elements across multiple worksheets.
// AI Prompts: Show how to add a hover effect to header cells in the CssStyles string for Aspose.Cells HTML export. | Provide code to export several worksheets to separate HTML files while referencing a shared external CSS file. | Explain how to set the background color of heading cells dynamically based on column index before saving to HTML.

using System;
using Aspose.Cells;

// Demonstrates how to export a workbook as a single HTML file with row/column headings enabled, inject custom CSS for <th> elements and a .heading class, and style tables and cells for consistent appearance.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Add sample data with a header row
        worksheet.Cells["A1"].PutValue("Header1");
        worksheet.Cells["B1"].PutValue("Header2");
        worksheet.Cells["A2"].PutValue("Data1");
        worksheet.Cells["B2"].PutValue("Data2");

        // Configure HTML save options
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();

        // Export row/column headings so that heading elements are generated in HTML
        saveOptions.ExportRowColumnHeadings = true;

        // Save as a single HTML file to allow custom CSS injection
        saveOptions.SaveAsSingleFile = true;

        // Define CSS classes for heading elements (th) and a generic .heading class
        saveOptions.CssStyles = @"
            th, .heading {
                background-color: #f2f2f2;
                font-weight: bold;
                text-align: center;
                padding: 5px;
            }
            table {
                border-collapse: collapse;
                width: 100%;
            }
            td {
                border: 1px solid #ddd;
                padding: 5px;
            }";

        // Save the workbook as HTML with the custom CSS applied
        workbook.Save("output.html", saveOptions);
    }
}
