// Title: Batch export multiple Excel workbooks to HTML with a shared TableCssId using Aspose.Cells for .NET
// AI Prompts: Write C# code that iterates over a list of .xlsx file paths, loads each workbook with Aspose.Cells, and saves the first worksheet as an HTML file using HtmlSaveOptions with a specified TableCssId. | Create a C# routine that checks for the existence of each Excel file before conversion, logs missing files, and continues processing the remaining workbooks. | Generate a C# example that configures HtmlSaveOptions to export only the active worksheet and applies a common CSS identifier to all generated HTML tables for consistent styling.
// Common Searches: aspnet batch convert excel files to html using shared TableCssId | c# Aspose.Cells export first worksheet to html in a loop | how to apply the same CSS id to multiple html tables generated by Aspose.Cells | skip missing Excel files during batch html export with Aspose.Cells | set TableCssId in HtmlSaveOptions for consistent styling across exported workbooks
// Tags: batch export Excel to HTML Aspose.Cells | shared TableCssId HtmlSaveOptions | export active worksheet only Aspose.Cells | C# workbook loop conversion | consistent HTML table styling Aspose.Cells

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsBatchExport
{
    // The program loops through a predefined list of Excel workbook paths, verifies each file exists, loads it with Aspose.Cells, and saves the first worksheet as an HTML file. HtmlSaveOptions are configured with a shared TableCssId to ensure uniform styling across all generated HTML tables, and errors are logged without stopping the batch process.
    class Program
    {
        static void Main(string[] args)
        {
            // List of workbook files to process.
            List<string> workbookFiles = new List<string>
            {
                @"C:\Input\Book1.xlsx",
                @"C:\Input\Book2.xlsx",
                @"C:\Input\Book3.xlsx"
                // Add more file paths as needed.
            };

            // Output folder for HTML files.
            string outputFolder = @"C:\Output\Html";

            // Ensure the output directory exists.
            Directory.CreateDirectory(outputFolder);

            // Shared TableCssId for uniform styling across all exported HTML tables.
            const string sharedTableCssId = "sharedTableStyle";

            foreach (string workbookPath in workbookFiles)
            {
                // Verify the workbook file exists before attempting to load.
                if (!File.Exists(workbookPath))
                {
                    Console.WriteLine($"File not found: {workbookPath}. Skipping.");
                    continue;
                }

                try
                {
                    // Load the workbook.
                    Workbook workbook = new Workbook(workbookPath);

                    // Configure HTML save options.
                    HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                    {
                        TableCssId = sharedTableCssId,
                        ExportActiveWorksheetOnly = true // Export only the first worksheet.
                    };

                    // Determine the output HTML file path.
                    string fileNameWithoutExt = Path.GetFileNameWithoutExtension(workbookPath);
                    string htmlFilePath = Path.Combine(outputFolder, fileNameWithoutExt + ".html");

                    // Save the workbook as HTML.
                    workbook.Save(htmlFilePath, htmlOptions);
                    Console.WriteLine($"Exported: {workbookPath} -> {htmlFilePath}");
                }
                catch (Exception ex)
                {
                    // Handle any errors that occur during loading or saving.
                    Console.WriteLine($"Error processing '{workbookPath}': {ex.Message}");
                }
            }

            Console.WriteLine("Batch export completed.");
        }
    }
}
