// Title: Batch convert Excel workbooks to HTML with gridlines & comments using Aspose.Cells (.NET)
// Description: C# example that iterates over a list of Excel files, sets HtmlSaveOptions.ExportGridLines and IsExportComments to true, and saves each workbook as an HTML file in a target directory. Includes folder creation, file‑existence checks, and basic error handling.
// Keywords: Aspose.Cells | C# | HTML export | ExportGridLines | IsExportComments | batch processing | multiple workbooks | Excel to HTML | gridlines | cell comments | automated conversion
// Common Searches: Aspose.Cells batch export HTML | Export gridlines and comments with Aspose.Cells | Convert many Excel files to HTML C# | HtmlSaveOptions ExportGridLines example | How to save Excel as HTML with comments .NET | Bulk Excel to HTML conversion Aspose
// Developer Intent: Convert a collection of Excel files to HTML while preserving worksheet gridlines and cell comments.
// Use Cases: Generate web‑ready reports from a set of spreadsheets, keeping the original layout and annotations. | Publish documentation pages that display Excel data together with explanatory comments for end users. | Automate nightly conversion of financial workbooks to HTML for intranet portals, retaining gridlines and comment notes. | Create a batch job that prepares HTML previews of uploaded Excel files for a SaaS platform.
// AI Prompts: Write code to add structured logging (to file or Azure Application Insights) for each workbook processed in the batch HTML export. | Show how to inject a custom CSS stylesheet into the HTML output generated by Aspose.Cells. | Provide a PowerShell wrapper that calls the C# batch processor and passes a folder of Excel files as input. | Explain how to modify HtmlSaveOptions to display formulas instead of calculated values in the exported HTML.

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsBatchProcessing
{
    // C# example that iterates over a list of Excel files, sets HtmlSaveOptions.ExportGridLines and IsExportComments to true, and saves each workbook as an HTML file in a target directory. Includes folder creation, file‑existence checks, and basic error handling.
    public class HtmlExportProcessor
    {
        /// <param name="excelFilePaths">Full paths of the source Excel files.</param>
        /// <param name="outputDirectory">Directory where the HTML files will be saved.</param>
        public void ProcessWorkbooks(IEnumerable<string> excelFilePaths, string outputDirectory)
        {
            // Ensure the output directory exists.
            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            foreach (string excelPath in excelFilePaths)
            {
                // Verify the source file exists before attempting to load.
                if (!File.Exists(excelPath))
                {
                    Console.WriteLine($"File not found: {excelPath}");
                    continue;
                }

                try
                {
                    // Load the workbook from the file system.
                    Workbook workbook = new Workbook(excelPath);

                    // Configure HTML save options to export gridlines and comments.
                    HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                    {
                        ExportGridLines = true,   // Export the worksheet gridlines.
                        IsExportComments = true   // Export cell comments.
                    };

                    // Build the output HTML file path.
                    string htmlFileName = Path.GetFileNameWithoutExtension(excelPath) + ".html";
                    string htmlPath = Path.Combine(outputDirectory, htmlFileName);

                    // Save the workbook as HTML using the configured options.
                    workbook.Save(htmlPath, htmlOptions);
                }
                catch (Exception ex)
                {
                    // Log any errors that occur during processing of the current file.
                    Console.WriteLine($"Error processing '{excelPath}': {ex.Message}");
                }
            }
        }
    }

    // Example usage:
    class Program
    {
        static void Main()
        {
            // Define the source Excel files.
            List<string> sourceFiles = new List<string>
            {
                @"C:\Data\Report1.xlsx",
                @"C:\Data\Report2.xls",
                @"C:\Data\Report3.xlsx"
            };

            // Define where the HTML files should be written.
            string outputFolder = @"C:\Data\HtmlOutputs";

            // Execute the batch processing.
            HtmlExportProcessor processor = new HtmlExportProcessor();
            processor.ProcessWorkbooks(sourceFiles, outputFolder);

            Console.WriteLine("Batch HTML export completed.");
        }
    }
}
