// Title: Export responsive HTML with scalable columns, FitToCell text, and tooltips using Aspose.Cells for .NET
// Description: Shows how to build a workbook, place a long string in a cell, narrow the column, and save the sheet as HTML with HtmlSaveOptions set to WidthScalable, HtmlCrossStringType = FitToCell, and AddTooltipText. The output page scales to the screen, keeps text inside the cell, and displays the full value in a hover tooltip.
// Keywords: Aspose.Cells | .NET | responsive HTML export | WidthScalable | FitToCell | AddTooltipText | HTML tooltip | Excel to HTML | column scaling | cell overflow tooltip
// Common Searches: Aspose.Cells responsive HTML export example | Add tooltip for truncated cell text Aspose.Cells | WidthScalable FitToCell HtmlSaveOptions | Export Excel to HTML with tooltips .NET | HtmlSaveOptions tooltip overflow handling
// Developer Intent: Create an HTML file from an Excel workbook that automatically scales column widths, limits text to cell bounds, and shows a tooltip for overflow content.
// Use Cases: Embedding Excel data in web dashboards where columns must adapt to different screen sizes. | Providing hover tooltips for long cell values in HTML reports without breaking the layout. | Generating printable HTML pages that remain responsive while preserving access to full cell text.
// AI Prompts: How can I customize the CSS style of tooltips generated by Aspose.Cells HTML export? | Show code to disable tooltips but keep WidthScalable and FitToCell settings active. | Provide an example that exports multiple worksheets to one responsive HTML file with tooltips enabled for each sheet.

using System;
using Aspose.Cells;

namespace AsposeCellsResponsiveHtmlDemo
{
    // Shows how to build a workbook, place a long string in a cell, narrow the column, and save the sheet as HTML with HtmlSaveOptions set to WidthScalable, HtmlCrossStringType = FitToCell, and AddTooltipText. The output page scales to the screen, keeps text inside the cell, and displays the full value in a hover tooltip.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Put a long text into a cell to demonstrate overflow handling
            sheet.Cells["A1"].PutValue("This is a very long piece of text that will exceed the column width and should show a tooltip when hovered.");

            // Set a narrow column width so the text overflows
            sheet.Cells.SetColumnWidth(0, 10); // Column A width

            // Configure HTML save options:
            // - WidthScalable = true for responsive column widths
            // - HtmlCrossStringType = FitToCell to limit text within cell bounds
            // - AddTooltipText = true to show tooltip when text is truncated
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            htmlOptions.WidthScalable = true;
            htmlOptions.HtmlCrossStringType = HtmlCrossType.FitToCell;
            htmlOptions.AddTooltipText = true;

            // Save the workbook as an HTML file with the specified options
            string outputPath = "ResponsiveWithTooltip.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"HTML file saved to: {outputPath}");
        }
    }
}
