// Title: Generate responsive HTML with tooltips using Aspose.Cells for .NET – enable WidthScalable and HtmlCrossType.FitToCell
// AI Prompts: Create an HTML file from a workbook that contains a column chart, activates AddTooltipText, sets HtmlSaveOptions.WidthScalable to true, and applies HtmlCrossType.FitToCell for a cell‑fitting responsive layout. | Modify the provided Aspose.Cells C# snippet to configure HtmlSaveOptions with WidthScalable and HtmlCrossType while preserving tooltip support for chart data points. | Export an Excel worksheet to a responsive HTML page where the chart automatically scales to the container width and shows hover tooltips for each data point.
// Common Searches: asp.net how to export Excel chart to responsive HTML with tooltips using Aspose.Cells | set WidthScalable and FitToCell in HtmlSaveOptions for Aspose.Cells .NET | enable tooltip text on HTML chart generated by Aspose.Cells | responsive HTML output for column chart Aspose.Cells example | Aspose.Cells HtmlSaveOptions responsive layout settings
// Tags: Aspose.Cells HtmlSaveOptions WidthScalable | HtmlCrossType FitToCell Aspose.Cells | Aspose.Cells export chart with tooltips | responsive HTML export Aspose.Cells .NET | column chart HTML output Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// The sample creates a workbook with sample sales data, adds a column chart, and demonstrates how to enable tooltip text in the HTML export using HtmlSaveOptions.AddTooltipText. It also explains that the WidthScalable and HtmlCrossType.FitToCell properties can be set (in supported versions) to produce a responsive, cell‑fitting HTML layout for the chart.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data
            sheet.Cells["A1"].PutValue("Month");
            sheet.Cells["B1"].PutValue("Sales");
            sheet.Cells["A2"].PutValue("Jan");
            sheet.Cells["B2"].PutValue(120);
            sheet.Cells["A3"].PutValue("Feb");
            sheet.Cells["B3"].PutValue(150);
            sheet.Cells["A4"].PutValue("Mar");
            sheet.Cells["B4"].PutValue(180);

            // Add a column chart (rows 5‑20, columns 0‑7)
            int chartIdx = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 7);
            Chart chart = sheet.Charts[chartIdx];

            // Add series data (values) – categories will be taken from the first column automatically
            chart.NSeries.Add("B2:B4", true);
            // Note: In newer Aspose.Cells versions CategoryData property exists.
            // If unavailable, the chart will use default numeric categories.

            // Set chart title
            chart.Title.Text = "Quarterly Sales";

            // Configure HTML export options (tooltips enabled)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                AddTooltipText = true
                // IsResponsive property is not available in this version of Aspose.Cells.
            };

            // Determine output path and ensure directory exists
            string outputFile = Path.Combine(Directory.GetCurrentDirectory(), "ResponsiveChart.html");
            string outputDir = Path.GetDirectoryName(outputFile);
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as HTML
            workbook.Save(outputFile, htmlOptions);
            Console.WriteLine($"Workbook saved to: {outputFile}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
