// Title: Measure HTML Size Reduction with Aspose.Cells HtmlSaveOptions.ExcludeUnusedStyles (C#)
// Description: A C# sample that creates a workbook with multiple cell styles, removes a row to leave unused styles, and saves the sheet to HTML twice—once with HtmlSaveOptions.ExcludeUnusedStyles enabled (default) and once disabled. It reads both file sizes, computes the byte and percentage reduction, and prints the results.
// Keywords: Aspose.Cells HtmlSaveOptions | ExcludeUnusedStyles | HTML size reduction | C# Aspose.Cells example | measure HTML output size | unused CSS styles Aspose | compare HTML files Aspose.Cells
// Common Searches: Aspose.Cells ExcludeUnusedStyles size impact | how to reduce HTML output size with Aspose.Cells | C# compare HTML files generated by Aspose.Cells | measure HTML file size difference Aspose.Cells | HTMLSaveOptions ExcludeUnusedStyles example
// Developer Intent: Find out how much the HTML file size shrinks when ExcludeUnusedStyles is turned on in Aspose.Cells.
// Use Cases: Evaluate storage savings for HTML reports generated from Excel workbooks. | Decide whether to enable ExcludeUnusedStyles in production pipelines. | Automate size‑comparison tests for multiple workbooks in CI/CD. | Log HTML size metrics for performance monitoring of web‑based reporting.
// AI Prompts: Generate a function that takes two Aspose.Cells HTML file paths and returns the size reduction in bytes and percentage. | Extend the sample to write the size comparison results to a CSV file for batch processing. | Create a unit test that asserts HtmlSaveOptions.ExcludeUnusedStyles produces a smaller HTML file when unused styles exist.

using System;
using System.IO;
using Aspose.Cells;
using System.Drawing;

namespace AsposeCellsHtmlStyleComparison
{
    // A C# sample that creates a workbook with multiple cell styles, removes a row to leave unused styles, and saves the sheet to HTML twice—once with HtmlSaveOptions.ExcludeUnusedStyles enabled (default) and once disabled. It reads both file sizes, computes the byte and percentage reduction, and prints the results.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add styled data to generate multiple styles
            // Cell A1 – red bold text
            Cell cellA1 = sheet.Cells["A1"];
            cellA1.PutValue("Red Bold");
            Style styleA1 = workbook.CreateStyle();
            styleA1.Font.Color = Color.Red;
            styleA1.Font.IsBold = true;
            cellA1.SetStyle(styleA1);

            // Cell B1 – green italic text
            Cell cellB1 = sheet.Cells["B1"];
            cellB1.PutValue("Green Italic");
            Style styleB1 = workbook.CreateStyle();
            styleB1.Font.Color = Color.Green;
            styleB1.Font.IsItalic = true;
            cellB1.SetStyle(styleB1);

            // Cell C1 – blue underlined text
            Cell cellC1 = sheet.Cells["C1"];
            cellC1.PutValue("Blue Underline");
            Style styleC1 = workbook.CreateStyle();
            styleC1.Font.Color = Color.Blue;
            styleC1.Font.Underline = FontUnderlineType.Single;
            cellC1.SetStyle(styleC1);

            // Delete a row to create unused styles in the workbook
            sheet.Cells.DeleteRows(2, 1); // Removes row 3 (index 2)

            // Prepare paths for the two HTML outputs
            string outputDir = Path.Combine(Environment.CurrentDirectory, "HtmlOutputs");
            Directory.CreateDirectory(outputDir);
            string htmlWithExcludePath = Path.Combine(outputDir, "WithExcludeUnusedStyles.html");
            string htmlWithoutExcludePath = Path.Combine(outputDir, "WithoutExcludeUnusedStyles.html");

            // Save HTML with ExcludeUnusedStyles = true (default)
            HtmlSaveOptions optionsExclude = new HtmlSaveOptions();
            optionsExclude.ExcludeUnusedStyles = true;
            workbook.Save(htmlWithExcludePath, optionsExclude);

            // Save HTML with ExcludeUnusedStyles = false
            HtmlSaveOptions optionsNoExclude = new HtmlSaveOptions();
            optionsNoExclude.ExcludeUnusedStyles = false;
            workbook.Save(htmlWithoutExcludePath, optionsNoExclude);

            // Get file sizes
            long sizeWithExclude = new FileInfo(htmlWithExcludePath).Length;
            long sizeWithoutExclude = new FileInfo(htmlWithoutExcludePath).Length;

            // Calculate reduction
            long reductionBytes = sizeWithoutExclude - sizeWithExclude;
            double reductionPercent = sizeWithoutExclude == 0 ? 0 :
                (double)reductionBytes / sizeWithoutExclude * 100;

            // Output results
            Console.WriteLine($"HTML size with ExcludeUnusedStyles=true : {sizeWithExclude} bytes");
            Console.WriteLine($"HTML size with ExcludeUnusedStyles=false: {sizeWithoutExclude} bytes");
            Console.WriteLine($"Size reduction: {reductionBytes} bytes ({reductionPercent:F2}%)");
        }
    }
}
