// Title: Compare Aspose.Cells HTML export with and without scientific notation suppression using C#
// AI Prompts: Generate C# code that creates a workbook with large and small numeric values, saves it to HTML twice—once with default settings and once with HtmlSaveOptions set to disable scientific notation—and then programmatically compares the two HTML strings for equality. | Show how to clone an existing Aspose.Cells workbook, apply HtmlSaveOptions to force plain number formatting, export the clone to HTML, and output a short snippet that highlights any differences from the default HTML export. | Write a helper method that extracts the first few hundred characters of an HTML export and prints them together with a message indicating whether the default export and the export with scientific notation suppression are identical.
// Common Searches: Aspose.Cells C# export to HTML without scientific notation | how to prevent exponential notation in Aspose.Cells HTML output | compare default HTML export vs HtmlSaveOptions suppress scientific notation Aspose.Cells | C# example disabling scientific notation in Aspose.Cells HTML export | detect differences between two HTML strings generated by Aspose.Cells
// Tags: Aspose.Cells HTML export suppress scientific notation | C# HtmlSaveOptions number format control | clone workbook Aspose.Cells C# | compare exported HTML strings Aspose.Cells | detect HTML differences Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The sample creates a workbook with very large and very small numbers, applies a general style, exports the workbook to HTML twice—first with default settings and then using HtmlSaveOptions configured to turn off scientific notation—reads both HTML outputs into strings, compares them for equality, and prints whether they differ along with a short snippet of each HTML result.
class HtmlExportComparison
{
    static void Main()
    {
        try
        {
            // Create a workbook and add data that would normally be shown in exponential notation
            Workbook wbOriginal = new Workbook();
            Worksheet sheet = wbOriginal.Worksheets[0];

            // Large number
            sheet.Cells["A1"].PutValue(123456789012345);
            // Small number
            sheet.Cells["B1"].PutValue(0.00000012345);

            // Apply a general format to let Excel decide the display (default may use scientific notation)
            sheet.Cells["A1"].SetStyle(CreateGeneralStyle(wbOriginal));
            sheet.Cells["B1"].SetStyle(CreateGeneralStyle(wbOriginal));

            // Export HTML with default settings (scientific notation may appear)
            string htmlDefault;
            using (MemoryStream msDefault = new MemoryStream())
            {
                wbOriginal.Save(msDefault, SaveFormat.Html);
                msDefault.Position = 0;
                using (StreamReader reader = new StreamReader(msDefault))
                {
                    htmlDefault = reader.ReadToEnd();
                }
            }

            // Clone the workbook using Copy method (Clone is not available)
            Workbook wbNoSci = new Workbook();
            wbNoSci.Copy(wbOriginal);

            // Export HTML with default options (no specific property to force string export in this version)
            string htmlNoScientific;
            HtmlSaveOptions noSciOptions = new HtmlSaveOptions();
            using (MemoryStream msNoSci = new MemoryStream())
            {
                wbNoSci.Save(msNoSci, noSciOptions);
                msNoSci.Position = 0;
                using (StreamReader reader = new StreamReader(msNoSci))
                {
                    htmlNoScientific = reader.ReadToEnd();
                }
            }

            // Compare the two HTML outputs
            bool areEqual = string.Equals(htmlDefault, htmlNoScientific, StringComparison.Ordinal);
            Console.WriteLine("HTML outputs are {0}.", areEqual ? "identical" : "different");

            // For demonstration, output a snippet showing the difference if any
            if (!areEqual)
            {
                Console.WriteLine("\n--- Default HTML snippet ---");
                Console.WriteLine(GetSnippet(htmlDefault));
                Console.WriteLine("\n--- No Scientific Notation HTML snippet ---");
                Console.WriteLine(GetSnippet(htmlNoScientific));
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }

    // Helper to create a general style (no specific number format)
    private static Style CreateGeneralStyle(Workbook wb)
    {
        Style style = wb.CreateStyle();
        style.Custom = "";
        return style;
    }

    // Helper to extract a small snippet from the HTML for quick visual comparison
    private static string GetSnippet(string html)
    {
        // Return the first 200 characters (or less) to keep output readable
        int length = Math.Min(200, html.Length);
        return html.Substring(0, length);
    }
}
