// Title: Compare Aspose.Cells HTML output before and after disabling redundant space export in C#
// AI Prompts: Generate C# code that loads a workbook, saves it to HTML with default settings, then saves it again with HtmlSaveOptions.ExportHtmlRedundantSpace set to false (using reflection if the property is unavailable), and compares the two HTML strings to report differences. | Show how to programmatically check for the existence of the ExportHtmlRedundantSpace property on HtmlSaveOptions, apply it conditionally, and produce a simple diff report between the two generated HTML files.
// Common Searches: Aspose.Cells C# save workbook to HTML without redundant spaces | how to detect ExportHtmlRedundantSpace property in Aspose.Cells .NET | compare two HTML files generated by Aspose.Cells for space removal | disable redundant space export in Aspose.Cells HTMLSaveOptions | runtime check for HtmlSaveOptions property before saving as HTML
// Tags: Aspose.Cells HTML redundant space export option | C# compare generated HTML outputs | HtmlSaveOptions ExportHtmlRedundantSpace detection | save workbook to HTML without extra spaces | diff two Aspose.Cells HTML files in .NET

using System;
using System.IO;
using Aspose.Cells;

// The example loads an input workbook, saves it twice to HTML—once with default settings and once with the ExportHtmlRedundantSpace option turned off (using reflection when needed)—then reads both files and reports whether their contents differ.
class HtmlRedundantSpaceComparison
{
    static void Main()
    {
        try
        {
            // Paths to the original HTML file and the output files
            string originalHtmlPath = "input.html";
            string beforeDeletionPath = "output_before.html";
            string afterDeletionPath = "output_after.html";

            // Verify that the input file exists
            if (!File.Exists(originalHtmlPath))
            {
                Console.WriteLine($"Input file not found: {originalHtmlPath}");
                return;
            }

            // Load the HTML file into a Workbook
            Workbook workbook = new Workbook(originalHtmlPath);

            // Save the workbook to HTML without any special settings (baseline)
            workbook.Save(beforeDeletionPath, SaveFormat.Html);

            // Save the workbook to HTML with redundant space deletion disabled (if supported)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            // The ExportHtmlRedundantSpace property may not be available in older versions of Aspose.Cells.
            // If it exists, set it to false to keep redundant spaces; otherwise, default behavior is used.
            var propInfo = typeof(HtmlSaveOptions).GetProperty("ExportHtmlRedundantSpace");
            if (propInfo != null && propInfo.CanWrite)
            {
                propInfo.SetValue(htmlOptions, false);
            }

            workbook.Save(afterDeletionPath, htmlOptions);

            // Ensure the output files were created before attempting to read them
            if (!File.Exists(beforeDeletionPath) || !File.Exists(afterDeletionPath))
            {
                Console.WriteLine("One or both output HTML files were not created.");
                return;
            }

            // Read both HTML files as strings
            string beforeHtml = File.ReadAllText(beforeDeletionPath);
            string afterHtml = File.ReadAllText(afterDeletionPath);

            // Simple comparison to check if the files differ
            if (beforeHtml.Equals(afterHtml))
            {
                Console.WriteLine("No differences detected after enabling redundant space deletion.");
            }
            else
            {
                Console.WriteLine("Differences detected between the HTML files.");
                // Optionally, write a diff report or further analysis here
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
