// Title: How to compare Aspose.Cells HTML export with and without downlevel revealed comments in C#
// AI Prompts: Write C# code that loads an Excel workbook, saves it to HTML twice—once with default HtmlSaveOptions and once with DisableDownlevelRevealedComments enabled—and outputs any line‑by‑line differences. | Create a reusable method that receives two HTML strings generated by Aspose.Cells and returns a formatted diff report showing the differing lines.
// Common Searches: asp.net aspose.cells htmlsaveoptions disabledownlevelrevealedcomments example | c# compare html output from Aspose.Cells before and after turning off conditional comments | how to export Excel to HTML without downlevel revealed comments using Aspose.Cells | detect line differences between two HTML files generated by Aspose.Cells in C#
// Tags: Aspose.Cells HtmlSaveOptions DisableDownlevelRevealedComments | C# compare two HTML strings line by line | export Excel to HTML without conditional comments | Aspose.Cells HTML output comparison | toggle downlevel revealed comments Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The sample loads an Excel workbook, saves it to HTML twice—first with default settings and then with DisableDownlevelRevealedComments set to true—compares the resulting HTML strings, and prints any line‑by‑line differences.
class Program
{
    static void Main()
    {
        // Path to the source Excel file
        string excelPath = "input.xlsx";

        // Load the workbook from the file
        Workbook workbook = new Workbook(excelPath);

        // Export to HTML with default settings (downlevel revealed comments are enabled)
        HtmlSaveOptions defaultOptions = new HtmlSaveOptions(SaveFormat.Html);
        string htmlDefault;
        using (MemoryStream msDefault = new MemoryStream())
        {
            workbook.Save(msDefault, defaultOptions);
            htmlDefault = System.Text.Encoding.UTF8.GetString(msDefault.ToArray());
        }

        // Export to HTML with downlevel revealed comments disabled
        HtmlSaveOptions disabledOptions = new HtmlSaveOptions(SaveFormat.Html);
        disabledOptions.DisableDownlevelRevealedComments = true;
        string htmlDisabled;
        using (MemoryStream msDisabled = new MemoryStream())
        {
            workbook.Save(msDisabled, disabledOptions);
            htmlDisabled = System.Text.Encoding.UTF8.GetString(msDisabled.ToArray());
        }

        // Compare the two HTML outputs
        bool areEqual = string.Equals(htmlDefault, htmlDisabled, StringComparison.Ordinal);
        Console.WriteLine("HTML outputs are equal: " + areEqual);

        // If they differ, output line‑by‑line differences
        if (!areEqual)
        {
            Console.WriteLine("Differences found:");
            string[] linesDefault = htmlDefault.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
            string[] linesDisabled = htmlDisabled.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
            int maxLines = Math.Max(linesDefault.Length, linesDisabled.Length);
            for (int i = 0; i < maxLines; i++)
            {
                string lineDef = i < linesDefault.Length ? linesDefault[i] : string.Empty;
                string lineDis = i < linesDisabled.Length ? linesDisabled[i] : string.Empty;
                if (!lineDef.Equals(lineDis))
                {
                    Console.WriteLine($"Line {i + 1}:\n   Default : {lineDef}\n   Disabled: {lineDis}");
                }
            }
        }
    }
}
