// Title: Compare HTML export file sizes with WidthScalable set to true versus false using Aspose.Cells for .NET
// AI Prompts: Generate C# code that creates a workbook, saves it to HTML with HtmlSaveOptions.WidthScalable = true, then saves the same workbook with WidthScalable = false, and prints the byte size of each file. | Show how to calculate and display the difference in file size between two HTML outputs generated by Aspose.Cells when toggling the WidthScalable property. | Provide a C# example that measures the size of temporary HTML files produced with WidthScalable enabled and disabled, and logs the results to the console.
// Common Searches: Aspose.Cells C# compare HTML file size with WidthScalable true and false | How does HtmlSaveOptions.WidthScalable affect the size of exported HTML in .NET | Measure size difference of HTML output from Aspose.Cells when disabling width scaling | C# code to get byte length of HTML files generated by Aspose.Cells with different WidthScalable settings | Performance impact of WidthScalable flag on Aspose.Cells HTML export size
// Tags: Aspose.Cells HtmlSaveOptions WidthScalable | C# compare HTML export sizes | measure Aspose.Cells HTML file length | temporary HTML output size Aspose.Cells | WidthScalable impact on HTML size .NET

using System;
using System.IO;
using Aspose.Cells;

// // Creates a sample workbook, exports it to HTML twice—once with WidthScalable = true and once with WidthScalable = false—then reads each file's length and writes the byte counts (and optional size difference) to the console.
class Program
{
    static void Main()
    {
        // Create a sample workbook with some data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Item");
        sheet.Cells["B1"].PutValue("Quantity");
        for (int i = 0; i < 100; i++)
        {
            sheet.Cells[i + 2, 0].PutValue($"Product {i + 1}");
            sheet.Cells[i + 2, 1].PutValue((i + 1) * 5);
        }

        // Temporary file paths for the two HTML outputs
        string htmlPathTrue = Path.Combine(Path.GetTempPath(), "workbook_widthscalable_true.html");
        string htmlPathFalse = Path.Combine(Path.GetTempPath(), "workbook_widthscalable_false.html");

        // Save workbook to HTML with WidthScalable = true
        HtmlSaveOptions optionsTrue = new HtmlSaveOptions(SaveFormat.Html);
        optionsTrue.WidthScalable = true;
        workbook.Save(htmlPathTrue, optionsTrue);

        // Save workbook to HTML with WidthScalable = false
        HtmlSaveOptions optionsFalse = new HtmlSaveOptions(SaveFormat.Html);
        optionsFalse.WidthScalable = false;
        workbook.Save(htmlPathFalse, optionsFalse);

        // Retrieve file sizes
        long sizeTrue = new FileInfo(htmlPathTrue).Length;
        long sizeFalse = new FileInfo(htmlPathFalse).Length;

        // Output the comparison results
        Console.WriteLine($"HTML size with WidthScalable = true : {sizeTrue} bytes");
        Console.WriteLine($"HTML size with WidthScalable = false: {sizeFalse} bytes");

        // Optional: delete temporary files
        // File.Delete(htmlPathTrue);
        // File.Delete(htmlPathFalse);
    }
}
