// Title: Aspose.Cells C# – Compare HTML Export With and Without DisableDownlevelRevealedComments
// Description: A C# example that creates a workbook, adds a comment to cell A1, saves the file twice as HTML (default and with DisableDownlevelRevealedComments = true), reads both outputs, and reports whether the generated HTML sources differ.
// Keywords: Aspose.Cells HtmlSaveOptions | DisableDownlevelRevealedComments | C# HTML export comparison | Excel to HTML comment handling | Aspose.Cells regression test
// Common Searches: Aspose.Cells disable downlevel revealed comments | HTML output difference when DisableDownlevelRevealedComments is true | C# compare two HTML files generated by Aspose.Cells | What does DisableDownlevelRevealedComments do | Aspose.Cells HTML export options comparison
// Developer Intent: Find out if setting DisableDownlevelRevealedComments changes the HTML markup produced by Aspose.Cells.
// Use Cases: Verify that comment markup is removed for legacy browsers after disabling the option. | Automate regression testing of HTML export settings by programmatically diffing saved files. | Document the visual impact of the DisableDownlevelRevealedComments flag for technical guides.
// AI Prompts: Show C# code that highlights the differences in comment markup between the two HTML files. | Explain the effect of DisableDownlevelRevealedComments on the generated HTML and suggest when to use it. | Write an MSTest unit test that asserts the HTML outputs are different when the property is toggled.

using System;
using System.IO;
using Aspose.Cells;

// A C# example that creates a workbook, adds a comment to cell A1, saves the file twice as HTML (default and with DisableDownlevelRevealedComments = true), reads both outputs, and reports whether the generated HTML sources differ.
class CompareHtmlDownlevelComments
{
    static void Main()
    {
        // Create a workbook and add a comment to cell A1
        Workbook workbook = new Workbook();                         // create workbook
        Worksheet worksheet = workbook.Worksheets[0];
        Comment comment = worksheet.Comments[worksheet.Comments.Add("A1")];
        comment.Note = "This is a test comment";

        // Save HTML with the default setting (DisableDownlevelRevealedComments = false)
        HtmlSaveOptions optionsDefault = new HtmlSaveOptions();
        optionsDefault.DisableDownlevelRevealedComments = false;
        string defaultHtmlPath = "output_default.html";
        workbook.Save(defaultHtmlPath, optionsDefault);            // save workbook as HTML

        // Save HTML with DisableDownlevelRevealedComments set to true
        HtmlSaveOptions optionsDisabled = new HtmlSaveOptions();
        optionsDisabled.DisableDownlevelRevealedComments = true;
        string disabledHtmlPath = "output_disabled.html";
        workbook.Save(disabledHtmlPath, optionsDisabled);          // save workbook as HTML

        // Load the generated HTML files
        string htmlDefault = File.ReadAllText(defaultHtmlPath);
        string htmlDisabled = File.ReadAllText(disabledHtmlPath);

        // Compare the two HTML sources
        bool areIdentical = string.Equals(htmlDefault, htmlDisabled, StringComparison.Ordinal);
        Console.WriteLine("HTML files are {0} after disabling downlevel revealed comments.", areIdentical ? "identical" : "different");
    }
}
