// Title: Calculate HTML export size reduction by disabling unused styles with Aspose.Cells for .NET
// AI Prompts: Write C# code that creates a workbook, adds an unused style, saves the workbook to HTML twice—once with HtmlSaveOptions.ExcludeUnusedStyles set to false and once set to true—and then prints the byte sizes and percentage reduction. | Show how to measure the difference in file size between two HTML files generated by Aspose.Cells when the ExcludeUnusedStyles option is toggled, including the calculation of reduction bytes and percent.
// Common Searches: asp.net how to compare HTML file sizes generated by Aspose.Cells with ExcludeUnusedStyles true and false | c# Aspose.Cells HtmlSaveOptions exclude unused styles size impact measurement | calculate percentage reduction of HTML export when removing unused styles in Aspose.Cells | measure HTML output size difference using Aspose.Cells HtmlSaveOptions.ExcludeUnusedStyles
// Tags: Aspose.Cells HtmlSaveOptions exclude unused styles | C# calculate HTML export size reduction | Aspose.Cells HTML file size comparison | style omission impact on Aspose.Cells HTML output

using System;
using System.IO;
using Aspose.Cells;

// The program builds a workbook, defines an unused style, saves the workbook to HTML twice—first including all styles and then omitting unused styles—and reports the file sizes and percentage reduction achieved.
class HtmlStyleComparison
{
    static void Main()
    {
        // Create a new workbook and add some data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Name = "Data";

        // Populate cells with sample data
        for (int row = 0; row < 10; row++)
        {
            for (int col = 0; col < 5; col++)
            {
                sheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
            }
        }

        // Create a style that will NOT be used (unused style)
        Style unusedStyle = workbook.CreateStyle();
        unusedStyle.ForegroundColor = System.Drawing.Color.Yellow;
        unusedStyle.Pattern = BackgroundType.Solid;
        // Note: This style is not applied to any cell, making it a candidate for exclusion.

        // Define file paths for the two HTML outputs
        string htmlPathWithAllStyles = "Workbook_WithAllStyles.html";
        string htmlPathWithoutUnused = "Workbook_WithoutUnusedStyles.html";

        // Save HTML with default options (ExcludeUnusedStyles = false)
        HtmlSaveOptions optionsAll = new HtmlSaveOptions(SaveFormat.Html);
        optionsAll.ExcludeUnusedStyles = false; // Include all styles, even unused ones
        workbook.Save(htmlPathWithAllStyles, optionsAll);

        // Save HTML with ExcludeUnusedStyles = true to omit unused styles
        HtmlSaveOptions optionsReduced = new HtmlSaveOptions(SaveFormat.Html);
        optionsReduced.ExcludeUnusedStyles = true; // Omit styles that are not applied to any cell
        workbook.Save(htmlPathWithoutUnused, optionsReduced);

        // Get file sizes
        long sizeAll = new FileInfo(htmlPathWithAllStyles).Length;
        long sizeReduced = new FileInfo(htmlPathWithoutUnused).Length;

        // Calculate reduction
        long reductionBytes = sizeAll - sizeReduced;
        double reductionPercent = sizeAll > 0 ? (reductionBytes * 100.0 / sizeAll) : 0;

        // Output the results
        Console.WriteLine($"HTML size with all styles: {sizeAll} bytes");
        Console.WriteLine($"HTML size without unused styles: {sizeReduced} bytes");
        Console.WriteLine($"Size reduction: {reductionBytes} bytes ({reductionPercent:F2}%)");
    }
}
