// Title: Compare Aspose.Cells HTML export results with and without scientific notation suppression in C#
// AI Prompts: Write a C# program that creates a workbook containing very large and very small numeric values, saves it to HTML using Aspose.Cells default settings, then converts those numeric cells to strings to disable scientific notation, saves a second HTML file, and reports whether the two files differ. | Generate C# code that uses Aspose.Cells HtmlSaveOptions to export a worksheet to HTML twice – first with the default formatter and second after applying string conversion to numeric cells to prevent exponential notation – and prints a snippet of the first mismatched line. | Provide a C# snippet that reads two HTML files produced by Aspose.Cells, compares their contents line‑by‑line, and outputs a message indicating if the HTML outputs are identical or shows the first differing line.
// Common Searches: aspocells c# export html suppress scientific notation example | how to prevent exponential notation when saving Excel to HTML with Aspose.Cells | compare default html output vs string‑converted values Aspose.Cells | c# read and diff two html files generated by Aspose.Cells | aspocells htmlsaveoptions disable scientific notation for large numbers
// Tags: Aspose.Cells HTML export with scientific notation disabled | C# store numeric values as strings before HTML export | HtmlSaveOptions default formatting versus custom | compare Aspose.Cells generated HTML files | avoid scientific notation in HTML export

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving; // Required for HtmlSaveOptions

// Demonstrates creating a workbook with extreme numeric values, exporting it to HTML using Aspose.Cells default settings, then converting those numbers to strings to suppress scientific notation, exporting a second HTML file, and programmatically comparing the two outputs to detect any differences.
class HtmlExportComparison
{
    static void Main()
    {
        try
        {
            // Create a workbook with sample data that would normally be displayed in exponential notation
            Workbook wb = new Workbook();
            Worksheet sheet = wb.Worksheets[0];

            // Large number that triggers scientific notation
            sheet.Cells["A1"].PutValue(12345678901234567890.0);
            // Small number that also triggers scientific notation
            sheet.Cells["A2"].PutValue(0.00000012345);
            // Normal number for control
            sheet.Cells["A3"].PutValue(12345.6789);

            // Export HTML with default settings (exponential notation may appear)
            string defaultHtmlPath = "ExportDefault.html";
            wb.Save(defaultHtmlPath, SaveFormat.Html);

            // Convert each cell's value to a string to avoid scientific notation in HTML output
            for (int row = 0; row <= 2; row++)
            {
                Cell cell = sheet.Cells[row, 0];
                if (cell.Value != null)
                {
                    string formatted = cell.Value.ToString();
                    cell.PutValue(formatted); // Store as string
                }
            }

            // Export HTML for the workbook with values stored as strings
            string suppressedHtmlPath = "ExportSuppressed.html";
            HtmlSaveOptions suppressedOptions = new HtmlSaveOptions(); // default options
            wb.Save(suppressedHtmlPath, suppressedOptions);

            // Verify that the HTML files were created before reading
            if (!File.Exists(defaultHtmlPath) || !File.Exists(suppressedHtmlPath))
                throw new FileNotFoundException("One or both HTML output files were not created.");

            // Read both HTML files into strings
            string defaultHtml = File.ReadAllText(defaultHtmlPath);
            string suppressedHtml = File.ReadAllText(suppressedHtmlPath);

            // Simple comparison: check if the HTML contents are identical
            if (defaultHtml.Equals(suppressedHtml))
            {
                Console.WriteLine("HTML outputs are identical.");
            }
            else
            {
                Console.WriteLine("HTML outputs differ.");
                // Display a diff snippet for illustration
                Console.WriteLine("\n--- Differences snippet ---");
                string[] defaultLines = defaultHtml.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                string[] suppressedLines = suppressedHtml.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                int lineCount = Math.Min(defaultLines.Length, suppressedLines.Length);
                for (int i = 0; i < lineCount; i++)
                {
                    if (!defaultLines[i].Equals(suppressedLines[i]))
                    {
                        Console.WriteLine("Default   : " + defaultLines[i]);
                        Console.WriteLine("Suppressed: " + suppressedLines[i]);
                        break;
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
