// Title: Calculate markup size reduction by disabling CSS in Aspose.Cells HTML export using C#
// AI Prompts: Write C# code that creates a workbook, saves it to HTML twice—once with default CSS and once with ExportHtmlStyle set to false—and prints both file sizes and the percentage reduction. | Demonstrate how to configure Aspose.Cells HtmlSaveOptions to omit embedded style blocks, read the generated HTML files, and compute the size difference in bytes and percent.
// Common Searches: how to compare HTML output size with and without CSS using Aspose.Cells C# | Aspose.Cells HtmlSaveOptions ExportHtmlStyle false size reduction example | C# measure markup reduction after disabling CSS in HTML export | calculate percentage decrease of HTML file generated by Aspose.Cells when CSS is disabled | disable embedded style block in Aspose.Cells HTML export and get file size
// Tags: Aspose.Cells HtmlSaveOptions disable CSS | ExportHtmlStyle false C# | HTML file size comparison Aspose.Cells | markup reduction calculation C# | HTML export without style block Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

// The program creates a workbook, saves it to HTML with default CSS and again with CSS disabled via ExportHtmlStyle = false, then reads the two files, reports their sizes, and calculates the percentage markup reduction.
class HtmlCssComparison
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Data";

            for (int row = 0; row < 100; row++)
            {
                for (int col = 0; col < 10; col++)
                {
                    sheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                }
            }

            // Define output file paths
            string htmlWithCssPath = "output_with_css.html";
            string htmlWithoutCssPath = "output_without_css.html";

            // Ensure output directory exists
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(htmlWithCssPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save HTML with default CSS (styles are placed in a <style> block)
            HtmlSaveOptions optionsWithCss = new HtmlSaveOptions(SaveFormat.Html);
            workbook.Save(htmlWithCssPath, optionsWithCss);

            // Save HTML with CSS disabled (styles are inlined)
            HtmlSaveOptions optionsWithoutCss = new HtmlSaveOptions(SaveFormat.Html);
            // In newer Aspose.Cells versions, disabling CSS is done via ExportHtmlStyle = false.
            // If the property is unavailable, the default behavior will be used.
            // The following line is guarded to avoid compilation errors on older versions.
            try
            {
                // Attempt to set the property via reflection if it exists
                var prop = typeof(HtmlSaveOptions).GetProperty("ExportHtmlStyle");
                if (prop != null && prop.CanWrite)
                {
                    prop.SetValue(optionsWithoutCss, false);
                }
            }
            catch { /* ignore if reflection fails */ }

            workbook.Save(htmlWithoutCssPath, optionsWithoutCss);

            // Verify files exist before accessing their sizes
            long sizeWithCss = File.Exists(htmlWithCssPath) ? new FileInfo(htmlWithCssPath).Length : 0;
            long sizeWithoutCss = File.Exists(htmlWithoutCssPath) ? new FileInfo(htmlWithoutCssPath).Length : 0;

            Console.WriteLine($"HTML size with CSS (default): {sizeWithCss} bytes");
            Console.WriteLine($"HTML size without CSS (inlined): {sizeWithoutCss} bytes");

            if (sizeWithCss > 0)
            {
                double reduction = ((double)(sizeWithCss - sizeWithoutCss) / sizeWithCss) * 100;
                Console.WriteLine($"Markup reduction: {reduction:F2}%");
            }
            else
            {
                Console.WriteLine("Unable to calculate reduction (size with CSS is zero).");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
