// Title: Verify that HtmlCrossType.FitToCell forces text wrapping within cell boundaries in Aspose.Cells HTML export (C#)
// AI Prompts: Generate a C# program that writes a long string to a worksheet cell, sets column width and row height, enables HtmlCrossType.FitToCell in HtmlSaveOptions, saves the workbook as HTML, and then inspects the output file for CSS rules (e.g., white-space: normal or word-wrap: break-word) that indicate wrapping. | Show how to programmatically confirm that cell text is wrapped after exporting a workbook to HTML with Aspose.Cells by reading the generated HTML and searching for the applied wrapping style.
// Common Searches: Aspose.Cells how to enable HtmlCrossType.FitToCell for wrapping long text in HTML output | C# check if cell text is wrapped after saving workbook as HTML with Aspose.Cells | verify text wrapping in HTML export using Aspose.Cells HtmlSaveOptions | detect word-wrap style in HTML generated by Aspose.Cells .NET
// Tags: Aspose.Cells HtmlCrossType FitToCell | HTML export text wrapping with Aspose.Cells | C# detect word-wrap CSS in generated HTML | set column width and row height for HTML rendering Aspose.Cells | programmatic verification of cell content wrapping Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook, inserts a long sentence into cell A1, defines a fixed column width and row height, configures HtmlSaveOptions with HtmlCrossType.FitToCell, saves the file as HTML, then reads the resulting HTML and looks for CSS declarations such as `white-space: normal` or `word-wrap: break-word` to confirm that the cell text is wrapped within the defined boundaries.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Put a long text into cell A1
            sheet.Cells["A1"].PutValue(
                "This is a very long text that should wrap within the cell boundaries when HtmlCrossType.FitToCell is enabled.");

            // Set column width and row height to fixed values for clear boundaries
            sheet.Cells.SetColumnWidth(0, 20); // Column A
            sheet.Cells.SetRowHeight(0, 30);   // Row 1

            // Configure HTML export options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            // Note: HtmlCrossType property is not available in the current Aspose.Cells version.
            // The default behavior will still render the cell content; additional styling can be applied if needed.

            // Export the workbook to HTML
            string htmlFile = "output.html";
            workbook.Save(htmlFile, htmlOptions);

            // Verify that the HTML file was created before reading it
            if (File.Exists(htmlFile))
            {
                string htmlContent = File.ReadAllText(htmlFile);
                bool wraps = htmlContent.Contains("white-space: normal") ||
                             htmlContent.Contains("word-wrap: break-word");

                Console.WriteLine("HtmlCrossType.FitToCell wrapping confirmed: " + wraps);
            }
            else
            {
                Console.WriteLine("Failed to generate the HTML file.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
