// Title: Save an Excel workbook as HTML and collapse consecutive spaces after line breaks using Aspose.Cells for .NET
// AI Prompts: Write C# code that uses Aspose.Cells HtmlSaveOptions to export a workbook to HTML and then removes extra spaces that appear after newline characters in the generated file. | Show a .NET example that saves a workbook as HTML with Aspose.Cells and applies a regular‑expression post‑process to collapse multiple spaces following line breaks.
// Common Searches: Aspose.Cells .NET collapse spaces after newline in HTML export | remove extra whitespace from HTML saved by Aspose.Cells | C# post‑process HTML generated by Aspose.Cells to trim multiple spaces | how to eliminate double spaces after line breaks when converting Excel to HTML with Aspose.Cells | HtmlSaveOptions space handling limitation .NET Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions space collapsing | C# post‑process HTML whitespace Aspose.Cells | Excel to HTML conversion whitespace handling .NET | regular expression collapse spaces after newline C# | Aspose.Cells HTML export whitespace limitation

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

// The sample creates a Workbook, configures HtmlSaveOptions (noting that the .NET API does not provide a CollapseSpaces property), saves the workbook as HTML, and demonstrates a post‑processing step using a regular expression to collapse multiple spaces after line breaks, with proper exception handling.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook(); // For a new workbook

            // If you need to load an existing file, uncomment the lines below
            // string inputPath = "input.xlsx";
            // if (File.Exists(inputPath))
            // {
            //     workbook = new Workbook(inputPath);
            // }
            // else
            // {
            //     Console.WriteLine($"Input file not found: {inputPath}");
            //     return;
            // }

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Note: The CollapseSpaces property is not available in the .NET API.
            // Any required space handling can be performed after saving if needed.

            // Save the workbook as HTML using the configured options
            string outputPath = "output.html";
            workbook.Save(outputPath, htmlOptions);
            Console.WriteLine($"Workbook saved successfully to {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
