// Title: Add <h1> Worksheet Titles Before Tables When Exporting to HTML with Aspose.Cells (.NET)
// Description: Creates a workbook with multiple sheets, saves each sheet as a separate HTML file using HtmlSaveOptions (SaveAsSingleFile = false), then reads the generated files, builds an <h1> tag from the worksheet name, and inserts the tag before the first <table> element (or at the start of the <body> if no table exists). The modified HTML files are written back to disk.
// Keywords: Aspose.Cells | HtmlSaveOptions | C# export HTML | worksheet heading | insert h1 tag | multiple html files | post‑process html Aspose | save workbook as html | add title before table
// Common Searches: Aspose.Cells add h1 before table | export workbook to separate html files C# | insert worksheet name heading in html output | HtmlSaveOptions custom header Aspose.Cells | post process html generated by Aspose.Cells
// Developer Intent: Insert an <h1> element containing the worksheet name before the first table in each HTML file produced by Aspose.Cells.
// Use Cases: Web reports where each worksheet appears with a clear title above its data table. | Documentation pages that list worksheet names as headings to improve readability and SEO. | Automated post‑processing of exported HTML to enforce a consistent heading structure.
// AI Prompts: Show C# code that saves a workbook to separate HTML files with Aspose.Cells and prepends an <h1> tag with the worksheet name before each table. | Explain how to handle HTML files that lack a <table> element and still insert a heading at the start of the body. | Provide a step‑by‑step guide to modify saved HTML files to include custom headings without changing the original workbook.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

namespace AsposeCellsHtmlH1Demo
{
    // Creates a workbook with multiple sheets, saves each sheet as a separate HTML file using HtmlSaveOptions (SaveAsSingleFile = false), then reads the generated files, builds an <h1> tag from the worksheet name, and inserts the tag before the first <table> element (or at the start of the <body> if no table exists). The modified HTML files are written back to disk.
    class Program
    {
        static void Main()
        {
            // Create a workbook with multiple worksheets
            Workbook workbook = new Workbook();
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "FirstSheet";
            sheet1.Cells["A1"].PutValue("Header1");
            sheet1.Cells["B1"].PutValue("Header2");
            sheet1.Cells["A2"].PutValue("Data1");
            sheet1.Cells["B2"].PutValue("Data2");

            Worksheet sheet2 = workbook.Worksheets.Add("SecondSheet");
            sheet2.Cells["A1"].PutValue("ColA");
            sheet2.Cells["B1"].PutValue("ColB");
            sheet2.Cells["A2"].PutValue(100);
            sheet2.Cells["B2"].PutValue(200);

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                // Save each worksheet to a separate HTML file
                SaveAsSingleFile = false,
                // Export all worksheets (default)
                ExportActiveWorksheetOnly = false
            };

            // Define output folder
            string outputFolder = Path.Combine(Environment.CurrentDirectory, "HtmlOutput");
            Directory.CreateDirectory(outputFolder);

            // Save the workbook as HTML (multiple files will be created in the folder)
            string mainHtmlPath = Path.Combine(outputFolder, "Workbook.html");
            workbook.Save(mainHtmlPath, saveOptions);

            // After saving, insert <h1> tags before each worksheet table
            // The generated files are named "sheet0.htm", "sheet1.htm", etc.
            for (int i = 0; i < workbook.Worksheets.Count; i++)
            {
                string sheetFileName = $"sheet{i}.htm";
                string sheetFilePath = Path.Combine(outputFolder, sheetFileName);

                if (!File.Exists(sheetFilePath))
                    continue; // safety check

                // Read the existing HTML content
                string htmlContent = File.ReadAllText(sheetFilePath, Encoding.UTF8);

                // Build the <h1> tag using the worksheet name
                string h1Tag = $"<h1>{workbook.Worksheets[i].Name}</h1>\n";

                // Insert the <h1> tag just before the first <table> element
                int tableIndex = htmlContent.IndexOf("<table", StringComparison.OrdinalIgnoreCase);
                if (tableIndex >= 0)
                {
                    // Insert the <h1> tag before the table tag
                    htmlContent = htmlContent.Insert(tableIndex, h1Tag);
                }
                else
                {
                    // If no table is found, prepend the <h1> at the beginning of the body
                    int bodyIndex = htmlContent.IndexOf("<body", StringComparison.OrdinalIgnoreCase);
                    if (bodyIndex >= 0)
                    {
                        int bodyClose = htmlContent.IndexOf('>', bodyIndex);
                        if (bodyClose >= 0)
                        {
                            htmlContent = htmlContent.Insert(bodyClose + 1, "\n" + h1Tag);
                        }
                    }
                }

                // Write the modified HTML back to the file
                File.WriteAllText(sheetFilePath, htmlContent, Encoding.UTF8);
            }

            Console.WriteLine("HTML files generated with <h1> headings for each worksheet.");
        }
    }
}
