// Title: Convert Excel WordArt to HTML and Minify Generated CSS with Aspose.Cells (C#)
// Description: Creates a workbook, adds a WordArt shape with a gradient fill, saves it as HTML with CSS exported to a separate folder, then minifies each CSS file by removing comments, collapsing whitespace, and tightening syntax.
// Keywords: Aspose.Cells | C# | WordArt HTML export | CSS minification | gradient fill | HtmlSaveOptions | ExportWorksheetCSSSeparately | RemoveUnusedStyles | Excel to HTML conversion | lightweight web reports
// Common Searches: Aspose.Cells export WordArt to HTML C# | how to minify CSS generated by Aspose.Cells | remove unused styles when saving Excel as HTML | minify gradient fill CSS from WordArt | separate CSS folder Aspose.Cells HTML output
// Developer Intent: Export an Excel workbook containing WordArt to HTML and compress the resulting CSS files.
// Use Cases: Publish Excel‑based dashboards with WordArt graphics as fast‑loading web pages. | Create HTML email templates from spreadsheets while keeping CSS size minimal. | Automate batch conversion of multiple workbooks with WordArt, ensuring compact CSS for better performance.
// AI Prompts: Generate C# code that uses Aspose.Cells to save a workbook with WordArt as HTML and then minifies the CSS files. | Explain how HtmlSaveOptions can be configured to export CSS separately and exclude unused styles for WordArt shapes. | Suggest robust CSS minification techniques that safely handle multiline comments and preserve required syntax in Aspose.Cells output.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Creates a workbook, adds a WordArt shape with a gradient fill, saves it as HTML with CSS exported to a separate folder, then minifies each CSS file by removing comments, collapsing whitespace, and tightening syntax.
class WordArtToHtmlWithMinifiedCss
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Add a WordArt shape with a gradient fill (preset style 7)
        // Parameters: style, text, upperLeftRow, top, upperLeftColumn, left, height, width
        Shape wordArt = sheet.Shapes.AddWordArt(
            PresetWordArtStyle.WordArtStyle7, // gradient fill - Blue, Accent 1, Reflection
            "Aspose.Cells WordArt",
            2, 0, 2, 0, 100, 400);

        // Optional: remove any unused styles to keep the CSS small
        workbook.RemoveUnusedStyles();

        // Configure HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            // Export CSS to a separate file so we can minify it later
            ExportWorksheetCSSSeparately = true,
            // Exclude styles that are not used in the HTML
            ExcludeUnusedStyles = true,
            // Keep the default HTML version (compatible with Excel)
            HtmlVersion = HtmlVersion.Default
        };

        // Define output HTML file path
        string htmlPath = "WordArt.html";

        // Save the workbook as HTML
        workbook.Save(htmlPath, htmlOptions);

        // After saving, locate the folder that contains the generated CSS files.
        // Aspose.Cells creates a folder named "<htmlFileName>_files" next to the HTML file.
        string cssFolder = Path.Combine(
            Path.GetDirectoryName(htmlPath) ?? "",
            Path.GetFileNameWithoutExtension(htmlPath) + "_files");

        // Ensure the folder exists before attempting to process CSS files
        if (Directory.Exists(cssFolder))
        {
            // Process each CSS file in the folder
            foreach (string cssFile in Directory.GetFiles(cssFolder, "*.css"))
            {
                // Read the original CSS content
                string cssContent = File.ReadAllText(cssFile);

                // 1. Remove CSS comments (/* ... */)
                cssContent = Regex.Replace(cssContent, @"/\*.*?\*/", string.Empty, RegexOptions.Singleline);

                // 2. Collapse whitespace: replace sequences of whitespace characters with a single space
                cssContent = Regex.Replace(cssContent, @"\s+", " ");

                // 3. Remove spaces before and after braces and semicolons for tighter formatting
                cssContent = cssContent.Replace(" {", "{")
                                       .Replace("{ ", "{")
                                       .Replace(" }", "}")
                                       .Replace("; ", ";")
                                       .Replace(": ", ":")
                                       .Trim();

                // Write the minified CSS back to the same file
                File.WriteAllText(cssFile, cssContent);
            }
        }

        Console.WriteLine("Workbook with WordArt saved as HTML.");
        Console.WriteLine("CSS files have been minified.");
    }
}
