// Title: Convert an HTML file to PDF and digitally sign the PDF with a certificate using Aspose.Cells and Aspose.Pdf in C#
// AI Prompts: Write C# code that loads a local HTML file into an Aspose.Cells Workbook using LoadOptions with LoadFormat.Html and saves it as a PDF. | Add a pre‑conversion check that verifies the HTML file exists and logs any I/O or conversion exceptions. | Extend the sample to load a .pfx certificate and apply a certificate‑based signature to the generated PDF using Aspose.Pdf's PdfFileSignature class. | Provide a complete C# console program that combines HTML‑to‑PDF conversion and PDF signing, handling errors and disposing resources correctly.
// Common Searches: aspocells convert html to pdf c# with digital signature | c# load html into workbook and export as pdf using Aspose.Cells example | how to sign a pdf generated by Aspose.Cells using a .pfx certificate | c# code for applying certificate based PDF signing with Aspose.Pdf | error handling for html to pdf conversion using Aspose.Cells in .NET
// Tags: Aspose.Cells HTML to PDF conversion C# | LoadOptions LoadFormat.Html workbook loading | SaveFormat.Pdf export Aspose.Cells | Aspose.Pdf PdfFileSignature certificate signing | C# file existence validation before conversion | exception handling Aspose.Cells conversion

using System;
using System.IO;
using Aspose.Cells;

// The example checks that the input HTML file exists, loads it into an Aspose.Cells Workbook with LoadOptions set to LoadFormat.Html, saves the workbook as a PDF using SaveFormat.Pdf, and can be extended to apply a certificate‑based digital signature to the resulting PDF via Aspose.Pdf, with comprehensive error handling throughout.
class Program
{
    static void Main()
    {
        try
        {
            // Input HTML file
            string htmlFile = "input.html";

            // Output PDF file
            string pdfFile = "output.pdf";

            // Ensure the HTML file exists
            if (!File.Exists(htmlFile))
            {
                Console.WriteLine($"Input HTML file not found: {htmlFile}");
                return;
            }

            // Load the HTML document into an Aspose.Cells Workbook
            LoadOptions loadOptions = new LoadOptions(LoadFormat.Html);
            Workbook workbook = new Workbook(htmlFile, loadOptions);

            // Save the workbook as PDF
            workbook.Save(pdfFile, SaveFormat.Pdf);

            Console.WriteLine("HTML has been converted to PDF successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
