// Title: C# – Convert HTML with Base64 images to high‑resolution PDF using Aspose.Cells
// Description: Load an HTML file that contains Base64‑encoded images into an Aspose.Cells Workbook, set PdfSaveOptions to 300 PPI and 100 % JPEG quality, and save as PDF so the original image clarity is preserved.
// Keywords: Aspose.Cells HTML to PDF | Base64 images PDF conversion .NET | SetImageResample Aspose | high quality PDF C# | preserve image resolution Aspose.Cells
// Common Searches: How to keep Base64 image quality when converting HTML to PDF with Aspose.Cells | Aspose.Cells PdfSaveOptions SetImageResample example C# | Convert HTML file with embedded images to PDF without losing resolution | C# code to export HTML containing Base64 graphics to PDF
// Developer Intent: Create a PDF from an HTML document that embeds Base64 images, ensuring the output retains the images' original resolution.
// Use Cases: Generate printable invoices from web‑based HTML templates that embed charts as Base64 images. | Archive marketing emails with embedded graphics as high‑clarity PDFs for compliance. | Batch‑process HTML brochures containing embedded pictures into PDF catalogs without pixel loss.
// AI Prompts: Show how to adjust PPI and JPEG quality for HTML‑to‑PDF conversion with Aspose.Cells in C#. | Provide a C# snippet that converts an HTML file with Base64 images to a PDF while preserving image resolution. | Explain the impact of SetImageResample on image scaling in PDF output generated by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsHtmlToPdf
{
    // Load an HTML file that contains Base64‑encoded images into an Aspose.Cells Workbook, set PdfSaveOptions to 300 PPI and 100 % JPEG quality, and save as PDF so the original image clarity is preserved.
    class Program
    {
        static void Main()
        {
            // Load the HTML file (which may contain Base64 images) into a workbook
            Workbook workbook = new Workbook("input.html");

            // Configure PDF save options to keep image resolution
            // Set desired PPI to 300 (high quality) and JPEG quality to 100%
            PdfSaveOptions pdfOptions = new PdfSaveOptions();
            pdfOptions.SetImageResample(300, 100);

            // Save the workbook as PDF; images will retain their original resolution
            workbook.Save("output.pdf", pdfOptions);
        }
    }
}
