// Title: Convert Excel to HTML with _blank links using Aspose.Cells for .NET
// Description: Demonstrates loading an XLSX workbook, configuring HtmlSaveOptions.LinkTargetType to HtmlLinkTargetType.Blank, and converting the file to HTML with ConversionUtility so every hyperlink opens in a new browser tab.
// Keywords: Aspose.Cells | Excel to HTML conversion | HtmlSaveOptions | LinkTargetType blank | C# Excel export | hyperlink target _blank | ConversionUtility | Aspose.Cells HTML export settings
// Common Searches: Aspose.Cells set hyperlink target blank | C# convert xlsx to html with links opening in new tab | HtmlSaveOptions LinkTargetType example | Export Excel as HTML using Aspose.Cells | How to make Excel hyperlinks open in new window after HTML conversion
// Developer Intent: Create an HTML version of an Excel workbook where all embedded hyperlinks open in a new browser tab.
// Use Cases: Publish interactive financial dashboards on a website without losing the current view when users click external links. | Provide HTML previews of uploaded spreadsheets in a web portal, ensuring links open separately to keep the preview page intact. | Generate documentation pages from Excel data where each reference link should launch in its own tab for better navigation.
// AI Prompts: Write C# code with Aspose.Cells that converts an .xlsx file to .html and forces all hyperlinks to use target="_blank". | Explain how HtmlSaveOptions.LinkTargetType influences hyperlink behavior in the HTML output generated by Aspose.Cells. | Show a script to batch‑process multiple Excel files into HTML pages with _blank links using Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Utility;

// Demonstrates loading an XLSX workbook, configuring HtmlSaveOptions.LinkTargetType to HtmlLinkTargetType.Blank, and converting the file to HTML with ConversionUtility so every hyperlink opens in a new browser tab.
class Program
{
    static void Main()
    {
        // Path to the source Excel file
        string sourcePath = "input.xlsx";

        // Desired path for the generated HTML file
        string htmlPath = "output.html";

        // Load options for the Excel file (default format detection can be used as well)
        LoadOptions loadOptions = new LoadOptions(LoadFormat.Xlsx);

        // Create HTML save options and set hyperlinks to open in a new tab/window
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();
        saveOptions.LinkTargetType = HtmlLinkTargetType.Blank; // _blank target

        // Convert the Excel workbook to HTML using the provided conversion utility
        ConversionUtility.Convert(sourcePath, loadOptions, htmlPath, saveOptions);
    }
}
