// Title: Convert HTML to PDF with Roman numeral page footer using Aspose.Cells for .NET
// Description: C# example that loads an HTML file into an Aspose.Cells Workbook, configures a centered footer to display page numbers in upper‑case Roman numerals, and saves the worksheet as a PDF using PdfSaveOptions.
// Keywords: Aspose.Cells HTML to PDF | Roman numeral footer | C# Aspose.Cells page number style | PdfSaveOptions .NET | custom footer Aspose.Cells | convert HTML to PDF C# | page number Roman numerals
// Common Searches: Aspose.Cells add Roman numeral page numbers to PDF | C# convert HTML file to PDF with footer | set footer page number style Roman numerals Aspose.Cells | HTML to PDF conversion with custom footer .NET | how to use PdfSaveOptions with Aspose.Cells
// Developer Intent: Generate a PDF from an HTML document and include a footer that shows page numbers formatted as Roman numerals.
// Use Cases: Produce printable reports from HTML templates that require formal Roman‑numeral pagination. | Automate creation of legal documents or contracts where sections are numbered with Roman numerals. | Batch‑process multiple HTML files into PDFs while applying a consistent Roman‑numeral footer across all worksheets.
// AI Prompts: Write C# code with Aspose.Cells to load an HTML file, set a centered footer displaying upper‑case Roman numeral page numbers, and save the result as a PDF. | Explain how to change the footer placeholder to show lower‑case Roman numerals in a PDF generated by Aspose.Cells. | Show how to apply the same Roman numeral footer to every worksheet in a workbook before exporting to PDF.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace Example
{
    // C# example that loads an HTML file into an Aspose.Cells Workbook, configures a centered footer to display page numbers in upper‑case Roman numerals, and saves the worksheet as a PDF using PdfSaveOptions.
    class HtmlToPdfWithRomanFooter
    {
        static void Main()
        {
            try
            {
                string inputPath = "input.html";
                string outputPath = "output.pdf";

                // Ensure the input HTML file exists
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the HTML file into a workbook
                Workbook workbook = new Workbook(inputPath);

                // Access the first worksheet
                Worksheet worksheet = workbook.Worksheets[0];

                // Set footer with page number placeholder (center section)
                worksheet.PageSetup.SetFooter(1, "Page &P");

                // Configure PDF save options (default settings)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Save the workbook as a PDF file
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
