// Title: C# – Convert HTML to PDF with Aspose.Cells and Sign the Workbook using a PFX Certificate
// Description: Loads an HTML file into an Aspose.Cells Workbook, saves it as a PDF with optional compliance settings, then loads a PFX certificate, creates a timestamped DigitalSignature, adds it to a DigitalSignatureCollection, applies the collection to the workbook, and finally saves the signed Excel file. The signature is stored in the workbook, not the PDF.
// Keywords: Aspose.Cells | HTML to PDF C# | PdfSaveOptions | digital signature C# | PFX certificate | Workbook signing | Excel digital signature | C# .NET | PDF compliance | PdfA1b
// Common Searches: Aspose.Cells convert html to pdf c# example | how to add digital signature to excel workbook c# | load pfx certificate in c# asp.net | set pdf compliance level aspose.cells | sign pdf generated by aspose.cells | c# html to pdf with digital signature
// Developer Intent: The developer needs to transform an HTML document into a PDF and then embed a digital signature into the originating Excel workbook using a supplied PFX certificate.
// Use Cases: Produce PDF reports from HTML templates while retaining a signed Excel version for audit trails. | Convert HTML invoices to PDF and store a signed Excel copy to satisfy regulatory requirements. | Create a timestamped, tamper‑evident Excel workbook derived from HTML content before distribution.
// AI Prompts: Show how to apply the digital signature directly to the PDF instead of the workbook. | Provide code to enable PdfA1b compliance in PdfSaveOptions with Aspose.Cells. | Explain how to verify the digital signature after the signed workbook is saved.

using System;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using Aspose.Cells;
using Aspose.Cells.DigitalSignatures;

namespace HtmlToPdfWithSignature
{
    // Loads an HTML file into an Aspose.Cells Workbook, saves it as a PDF with optional compliance settings, then loads a PFX certificate, creates a timestamped DigitalSignature, adds it to a DigitalSignatureCollection, applies the collection to the workbook, and finally saves the signed Excel file. The signature is stored in the workbook, not the PDF.
    class Program
    {
        static void Main()
        {
            try
            {
                // Path to the source HTML file
                string htmlPath = "input.html";

                if (!File.Exists(htmlPath))
                {
                    Console.WriteLine($"HTML file not found: {htmlPath}");
                    return;
                }

                Workbook workbook;
                try
                {
                    // Load the HTML file into a workbook
                    workbook = new Workbook(htmlPath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to load HTML into workbook: {ex.Message}");
                    return;
                }

                // Configure PDF save options (optional: set compliance level)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();
                // Uncomment the following line if the Aspose.Cells version supports PdfCompliance
                // pdfOptions.Compliance = Aspose.Cells.PdfCompliance.PdfA1b;

                // Save the workbook as PDF
                string pdfPath = "output.pdf";
                try
                {
                    workbook.Save(pdfPath, pdfOptions);
                    Console.WriteLine($"PDF saved to {pdfPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to save PDF: {ex.Message}");
                    return;
                }

                // Load the certificate (PFX file) that will be used for the digital signature
                string certPath = "mycert.pfx";
                string certPassword = "certificatePassword";

                if (!File.Exists(certPath))
                {
                    Console.WriteLine($"Certificate file not found: {certPath}");
                    return;
                }

                X509Certificate2 certificate;
                try
                {
                    // Load certificate (using the recommended constructor)
                    certificate = new X509Certificate2(certPath, certPassword);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to load certificate: {ex.Message}");
                    return;
                }

                try
                {
                    // Create a digital signature with the certificate, a comment, and the current UTC time
                    DigitalSignature digitalSignature = new DigitalSignature(
                        certificate,
                        "Signed HTML to PDF conversion",
                        DateTime.UtcNow);

                    // Add the signature to a collection
                    DigitalSignatureCollection signatureCollection = new DigitalSignatureCollection();
                    signatureCollection.Add(digitalSignature);

                    // Apply the digital signature to the workbook (Excel file)
                    workbook.SetDigitalSignature(signatureCollection);

                    // Save the signed workbook (the signature is stored in the Excel file, not the PDF)
                    string signedWorkbookPath = "signed_workbook.xlsx";
                    workbook.Save(signedWorkbookPath);
                    Console.WriteLine($"Signed workbook saved to {signedWorkbookPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error during digital signing: {ex.Message}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Unexpected error: {ex.Message}");
            }
        }
    }
}
