// Title: Convert Arabic HTML to PDF with right-to-left text direction using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an Arabic HTML file into an Aspose.Cells Workbook and exports it to a PDF while preserving RTL layout. | Explain how to adjust the HTML or CSS of an Arabic document so that Aspose.Cells renders right-to-left text correctly in the generated PDF. | Add comprehensive error handling to the HTML‑to‑PDF conversion sample, covering missing files and conversion exceptions.
// Common Searches: aspocells c# export arabic html to pdf with rtl layout | how to keep right-to-left text when converting html to pdf using Aspose.Cells | c# Aspose.Cells HtmlLoadOptions rtl arabic pdf output | preserve Arabic text direction in PDF generated by Aspose.Cells .NET
// Tags: Aspose.Cells HtmlLoadOptions RTL Arabic | Aspose.Cells PdfSaveOptions one-page-per-sheet | C# HTML to PDF conversion with right-to-left support | Arabic text direction handling in Aspose.Cells PDF export | Aspose.Cells workbook conversion from HTML to PDF

using System;
using System.IO;
using Aspose.Cells;

// The example checks for an input HTML file, loads it into an Aspose.Cells Workbook using HtmlLoadOptions, and saves it as a single‑page PDF via PdfSaveOptions. Right‑to‑left layout for Arabic must be defined in the source HTML/CSS, as Aspose.Cells does not provide a separate RTL flag for PDF output.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.html";
            const string outputPath = "output.pdf";

            // Verify that the input HTML file exists.
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the HTML file into a workbook.
            var loadOptions = new HtmlLoadOptions();
            var workbook = new Workbook(inputPath, loadOptions);

            // Prepare PDF save options.
            var pdfOptions = new PdfSaveOptions
            {
                OnePagePerSheet = true
                // Note: Aspose.Cells does not expose a direct RTL property for PDF output.
                // Right‑to‑left layout can be handled in the source HTML/CSS if required.
            };

            // Save the workbook as PDF.
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
