// Title: Convert HTML to PDF with a Roman‑numeral footer using Aspose.Cells for .NET (C#)
// Description: This Aspose.Cells example loads an HTML file into a Workbook, adds a footer containing a "{RomanPage}" placeholder, and saves the workbook as a PDF. Because Aspose.Cells alone cannot render Roman numerals, the placeholder can be replaced later with Aspose.Pdf or another post‑processing step. The sample also includes a helper method for integer‑to‑Roman conversion.
// Keywords: Aspose.Cells HTML to PDF | C# convert HTML to PDF | custom footer Aspose.Cells | Roman numeral page numbers PDF | placeholder footer token | post‑process PDF Aspose.Pdf | Aspose.Cells page setup footer
// Common Searches: how to add a footer with page numbers when converting HTML to PDF using Aspose.Cells | Aspose.Cells Roman numeral footer | replace placeholder in PDF generated by Aspose.Cells | C# convert HTML file to PDF with custom footer | Aspose.Cells page setup footer tokens
// Developer Intent: Create a PDF from an HTML document and embed a footer that can later be swapped with Roman‑numeral page numbers.
// Use Cases: Load an HTML file into an Aspose.Cells Workbook and generate a PDF. | Insert a footer containing a custom placeholder token for page numbers. | Apply a post‑processing step (e.g., with Aspose.Pdf) to replace the placeholder with Roman numerals. | Validate the source HTML file before conversion to avoid runtime errors.
// AI Prompts: Generate C# code that uses Aspose.Pdf to open the PDF created by Aspose.Cells and replace the "{RomanPage}" placeholder with the correct Roman numeral on each page. | Show how to modify the footer string to use Aspose.Cells built‑in page number tokens instead of a custom placeholder. | Explain how to handle multi‑worksheet HTML conversion so each worksheet becomes a PDF page with a Roman‑numeral footer.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlToPdfWithRomanFooter
{
    // This Aspose.Cells example loads an HTML file into a Workbook, adds a footer containing a "{RomanPage}" placeholder, and saves the workbook as a PDF. Because Aspose.Cells alone cannot render Roman numerals, the placeholder can be replaced later with Aspose.Pdf or another post‑processing step. The sample also includes a helper method for integer‑to‑Roman conversion.
    class Program
    {
        // Helper method to convert an integer to a Roman numeral string.
        static string ToRoman(int number)
        {
            if (number < 1) return string.Empty;
            var map = new (int value, string numeral)[] {
                (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
                (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
                (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")
            };
            var result = string.Empty;
            foreach (var (value, numeral) in map)
            {
                while (number >= value)
                {
                    result += numeral;
                    number -= value;
                }
            }
            return result;
        }

        static void Main()
        {
            // Path to the source HTML file.
            string htmlPath = "input.html";

            // Verify that the input HTML file exists.
            if (!File.Exists(htmlPath))
            {
                Console.WriteLine($"Error: The file '{htmlPath}' was not found.");
                return;
            }

            Workbook workbook = null;
            try
            {
                // Load the HTML file into a Workbook.
                workbook = new Workbook(htmlPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to load HTML file: {ex.Message}");
                return;
            }

            // Access the first worksheet.
            Worksheet sheet = workbook.Worksheets[0];

            // Set a custom footer with a placeholder token.
            // Aspose.Cells does not directly support Roman numerals for page numbers,
            // so we keep the placeholder and will replace it after PDF generation.
            sheet.PageSetup.SetFooter(1, "Page {RomanPage}");

            // Save the workbook to PDF.
            string pdfPath = "output.pdf";
            try
            {
                workbook.Save(pdfPath, SaveFormat.Pdf);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to save PDF: {ex.Message}");
                return;
            }

            // NOTE:
            // The original example attempted to use Aspose.Pdf to replace the placeholder
            // with Roman numerals. Since only Aspose.Cells is guaranteed to be available,
            // the placeholder will remain as-is in the generated PDF.
            // If Aspose.Pdf is added to the project, similar post‑processing can be
            // implemented as shown in the original sample.

            Console.WriteLine("HTML has been converted to PDF. Footer contains placeholder '{RomanPage}'.");
        }
    }
}
