// Title: Convert HTML to an Accessible PDF with Screen‑Reader Tags using Aspose.Cells for .NET (C#)
// Description: C# example that loads an HTML file into an Aspose.Cells Workbook, enables ExportDocumentStructure, sets PdfSecurityOptions.AccessibilityExtractContent, and saves the workbook as a PDF containing accessibility tags for screen‑reader compatibility.
// Keywords: Aspose.Cells | C# | .NET | HTML to PDF | accessible PDF | screen reader | ExportDocumentStructure | PdfSaveOptions | PdfSecurityOptions | AccessibilityExtractContent | WCAG compliance | PDF accessibility tags | PDF/UA | document structure export
// Common Searches: Aspose.Cells add accessibility tags when converting HTML to PDF | ExportDocumentStructure option C# Aspose.Cells | Enable screen reader extraction in PDF generated by Aspose.Cells | PdfSecurityOptions AccessibilityExtractContent example | How to create WCAG‑compliant PDF from HTML using Aspose.Cells | C# convert HTML to PDF with accessibility tags
// Developer Intent: Create a PDF from an HTML source that includes PDF/UA accessibility tags and permits screen‑reader content extraction, optionally applying security settings.
// Use Cases: Generate WCAG‑compliant PDFs from web reports, invoices, or marketing pages. | Provide accessible documentation for visually impaired users. | Distribute secure PDFs that still allow assistive technologies to read text and graphics. | Automate batch conversion of HTML assets to accessible PDFs in enterprise workflows.
// AI Prompts: Provide a step‑by‑step C# code sample to convert an HTML file to an accessible PDF with Aspose.Cells, including ExportDocumentStructure and AccessibilityExtractContent settings. | Show how to protect the PDF with an owner password while keeping screen‑reader extraction enabled. | Explain how to validate the accessibility tags in the generated PDF using open‑source tools or Aspose.Cells APIs. | Give guidance on converting multiple HTML files to accessible PDFs in a loop with Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// C# example that loads an HTML file into an Aspose.Cells Workbook, enables ExportDocumentStructure, sets PdfSecurityOptions.AccessibilityExtractContent, and saves the workbook as a PDF containing accessibility tags for screen‑reader compatibility.
class HtmlToPdfWithAccessibility
{
    static void Main()
    {
        // Load the HTML file into a workbook
        Workbook workbook = new Workbook("input.html");

        // Create PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Export the document structure (tags) to improve accessibility
        pdfOptions.ExportDocumentStructure = true;

        // Configure security options to allow screen‑reader extraction of text and graphics
        PdfSecurityOptions security = new PdfSecurityOptions
        {
            AccessibilityExtractContent = true
            // OwnerPassword = "ownerPwd";   // optional
            // UserPassword = "userPwd";     // optional
        };

        pdfOptions.SecurityOptions = security;

        // Save the workbook as a PDF with the specified options
        workbook.Save("output.pdf", pdfOptions);
    }
}
