// Title: Convert HTML to an Accessible PDF using Aspose.Cells for .NET
// Description: Load an HTML file into an Aspose.Cells Workbook, enable ExportDocumentStructure, set PdfSecurityOptions.AccessibilityExtractContent, and save a PDF that includes screen‑reader tags and allows content extraction without passwords.
// Keywords: Aspose.Cells HTML to PDF | accessible PDF conversion .NET | ExportDocumentStructure | AccessibilityExtractContent | PDF accessibility tags | screen reader friendly PDF | PdfSecurityOptions
// Common Searches: Aspose.Cells add accessibility tags when converting HTML to PDF | ExportDocumentStructure example Aspose.Cells C# | Enable text extraction for screen readers in PDF generated by Aspose.Cells | PdfSecurityOptions AccessibilityExtractContent usage | Create WCAG compliant PDF from HTML with Aspose.Cells
// Developer Intent: Produce a PDF from an HTML source that contains PDF/UA accessibility tags and permits screen‑reader extraction using Aspose.Cells.
// Use Cases: Generate WCAG‑compliant PDFs from HTML reports for regulatory submissions. | Provide assistive‑technology users with searchable, tag‑structured PDFs without applying passwords. | Automate batch conversion of web‑based documentation to accessible PDFs in .NET applications.
// AI Prompts: How do I convert an HTML file to an accessible PDF with Aspose.Cells, enabling ExportDocumentStructure and AccessibilityExtractContent? | Give me a C# snippet that adds PDF accessibility tags while converting HTML to PDF using Aspose.Cells. | Explain the impact of ExportDocumentStructure and AccessibilityExtractContent on screen‑reader compatibility in PDFs created by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsHtmlToPdfAccessibility
{
    // Load an HTML file into an Aspose.Cells Workbook, enable ExportDocumentStructure, set PdfSecurityOptions.AccessibilityExtractContent, and save a PDF that includes screen‑reader tags and allows content extraction without passwords.
    class Program
    {
        static void Main()
        {
            // Path to the source HTML file
            string htmlPath = "input.html";

            // Path for the generated PDF file
            string pdfPath = "output.pdf";

            // Load the HTML file into a Workbook instance
            Workbook workbook = new Workbook(htmlPath);

            // Create PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Enable export of document structure (helps screen readers)
            pdfOptions.ExportDocumentStructure = true;

            // Configure security options to allow accessibility extraction
            PdfSecurityOptions security = new PdfSecurityOptions
            {
                // Allow extraction of text and graphics for accessibility tools
                AccessibilityExtractContent = true,

                // (Optional) Set passwords if needed; leave null for no password
                OwnerPassword = null,
                UserPassword = null
            };

            // Assign the security options to the PDF save options
            pdfOptions.SecurityOptions = security;

            // Save the workbook as a PDF with the specified options
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine("HTML has been converted to PDF with accessibility tags.");
        }
    }
}
