// Title: Convert Excel to HTML with parent‑frame hyperlinks using Aspose.Cells for .NET (C#)
// Description: A concise C# example that loads an Excel workbook, applies the default HtmlSaveOptions, sets HtmlSaveOptions.LinkTargetType to Parent so every hyperlink opens in the surrounding page, and saves the result as an HTML file. Ideal for creating web‑ready reports that preserve navigation to the main site.
// Keywords: Aspose.Cells | C# | Excel to HTML | HtmlSaveOptions | LinkTargetType | Parent | hyperlink target | HTML export | default options | .NET | code snippet | GitHub sample
// Common Searches: Aspose.Cells export Excel to HTML C# example | HtmlSaveOptions LinkTargetType Parent usage | How to set hyperlink target parent in Aspose.Cells HTML output | Convert workbook to HTML with default settings Aspose | C# code to save Excel as HTML with parent link target
// Developer Intent: Generate an HTML version of an Excel workbook where all links open in the parent page.
// Use Cases: Embedding spreadsheet data in an iframe while ensuring links navigate the main document. | Automating batch conversion of Excel files to static HTML reports for documentation portals. | Creating web‑ready HTML dashboards from Excel workbooks with consistent hyperlink behavior.
// AI Prompts: Provide C# code that loads an Excel file with Aspose.Cells, uses default HtmlSaveOptions, sets LinkTargetType to Parent, and saves the workbook as HTML. | Explain the effect of HtmlLinkTargetType.Parent on hyperlinks in HTML generated by Aspose.Cells. | Show how to customize HtmlSaveOptions for HTML export in Aspose.Cells .NET, focusing on hyperlink target settings.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // A concise C# example that loads an Excel workbook, applies the default HtmlSaveOptions, sets HtmlSaveOptions.LinkTargetType to Parent so every hyperlink opens in the surrounding page, and saves the result as an HTML file. Ideal for creating web‑ready reports that preserve navigation to the main site.
    class Program
    {
        static void Main()
        {
            // Path to the source Excel file
            string inputPath = "input.xlsx";

            // Load the workbook from the file system
            Workbook workbook = new Workbook(inputPath);

            // Create HTML save options with default settings
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();

            // Set hyperlink target to open in the parent frame (default value)
            saveOptions.LinkTargetType = HtmlLinkTargetType.Parent;

            // Save the workbook as an HTML file using the specified options
            workbook.Save("output.html", saveOptions);
        }
    }
}
