// Title: C# – Convert Excel to HTML with BestFit layout and export comments using Aspose.Cells
// Description: Load an .xlsx workbook, enable HtmlSaveOptions.PresentationPreference for BestFit rendering, turn on IsExportComments, and save as HTML. The result keeps the spreadsheet’s visual fidelity and includes every cell comment.
// Keywords: Aspose.Cells HTML export | BestFit presentation Aspose | export Excel comments to HTML | HtmlSaveOptions C# | convert .xlsx to HTML .NET | preserve spreadsheet layout HTML | cell notes HTML output
// Common Searches: Aspose.Cells export comments to HTML C# | HTML SaveOptions PresentationPreference example | convert Excel workbook to HTML with BestFit | C# save workbook as HTML with comments | how to keep Excel layout when converting to HTML
// Developer Intent: Generate an HTML file from an Excel workbook that mirrors the original layout (BestFit) and includes all cell comments.
// Use Cases: Web preview of uploaded spreadsheets that shows both data and notes. | HTML‑based reporting from Excel templates while retaining comment annotations. | Online viewer that displays spreadsheet content with embedded comments for documentation.
// AI Prompts: Write C# code using Aspose.Cells to convert an .xlsx file to HTML with BestFit rendering and comment export. | Explain how PresentationPreference affects the HTML output and how to toggle it in Aspose.Cells. | Troubleshoot missing cell comments in HTML generated by Aspose.Cells despite setting IsExportComments to true.

using System;
using Aspose.Cells;

// Load an .xlsx workbook, enable HtmlSaveOptions.PresentationPreference for BestFit rendering, turn on IsExportComments, and save as HTML. The result keeps the spreadsheet’s visual fidelity and includes every cell comment.
class Program
{
    static void Main()
    {
        // Load an existing Excel workbook.
        // Replace "input.xlsx" with the path to your source file.
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options.
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            // Enable presentation preference (BestFit) for a more faithful visual rendering.
            PresentationPreference = true,

            // Export cell comments to the generated HTML.
            IsExportComments = true
        };

        // Save the workbook as an HTML file using the configured options.
        // The output file will contain the best‑fit presentation and all cell comments.
        workbook.Save("output.html", htmlOptions);
    }
}
