// Title: Convert HTML to PDF/A‑2b with AspNet Cells (C#) – embed Windows fonts; add custom ICC profile in post‑process
// Description: This example shows how to load an HTML file into an Aspose.Cells Workbook, configure PdfSaveOptions for PDF/A‑2b compliance, embed standard Windows fonts, and save the result as a PDF. It also explains that Aspose.Cells does not expose a direct API for custom ICC profile embedding, which must be performed with a low‑level PDF library or a post‑processing step.
// Keywords: Aspose.Cells HTML to PDF | C# PDF/A-2b conversion | embed Windows fonts PDF | ICC color profile Aspose.Cells | color management PDF/A | .NET HTML to PDF example | post‑process PDF ICC profile | iTextSharp add ICC profile | low‑level PDF library | Aspose.Cells PdfSaveOptions
// Common Searches: convert html to pdf/a-2b using aspose.cells c# | embed windows fonts when saving pdf with aspose.cells | how to add custom icc profile to pdf generated by aspose.cells | pdf/a-2b compliance options in aspose.cells | post‑process pdf to embed icc color profile c#
// Developer Intent: Create a PDF/A‑2b document from HTML with embedded fonts using Aspose.Cells, then apply a custom ICC profile via a secondary PDF tool.
// Use Cases: Archive marketing webpages as PDF/A‑2b with reliable font rendering for long‑term storage. | Generate PDF reports from HTML templates, then attach a brand‑specific ICC profile for color‑accurate printing. | Automate batch conversion of HTML assets to PDF/A‑2b in a .NET microservice, handling ICC embedding in a separate step.
// AI Prompts: Write C# code that loads an HTML file into an Aspose.Cells Workbook, saves it as PDF/A‑2b with embedded Windows fonts, and then uses iTextSharp to embed a custom ICC profile. | Explain the PDF/A‑2b settings in Aspose.Cells PdfSaveOptions and why custom ICC profile embedding requires post‑processing. | Provide a step‑by‑step guide to post‑process a PDF created by Aspose.Cells to add an ICC color profile using a low‑level PDF library.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace HtmlToPdfWithIccProfile
{
    // This example shows how to load an HTML file into an Aspose.Cells Workbook, configure PdfSaveOptions for PDF/A‑2b compliance, embed standard Windows fonts, and save the result as a PDF. It also explains that Aspose.Cells does not expose a direct API for custom ICC profile embedding, which must be performed with a low‑level PDF library or a post‑processing step.
    class Program
    {
        static void Main()
        {
            // Path to the source HTML file
            string htmlPath = "sample.html";

            // Path for the resulting PDF file
            string pdfPath = "output.pdf";

            // Load the HTML file into a Workbook.
            // Aspose.Cells can import HTML content as a workbook.
            Workbook workbook = new Workbook(htmlPath);

            // Configure PDF save options.
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Set PDF/A compliance to ensure better color management.
            // PDF/A-2b supports embedding ICC profiles for accurate color reproduction.
            pdfOptions.Compliance = PdfCompliance.PdfA2b;

            // Optionally embed standard Windows fonts to improve rendering consistency.
            pdfOptions.EmbedStandardWindowsFonts = true;

            // NOTE:
            // Direct embedding of a custom ICC color profile is not exposed via the
            // Aspose.Cells PDFSaveOptions API. If a specific ICC profile is required,
            // it must be handled through a lower‑level PDF library or by post‑processing
            // the generated PDF. The code below demonstrates the standard approach.

            // Save the workbook as PDF using the configured options.
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine($"HTML file '{htmlPath}' has been converted to PDF '{pdfPath}'.");
        }
    }
}
