// Title: Convert Excel to HTML with BestFit layout and blank hyperlink targets using Aspose.Cells for .NET (C#)
// Description: Demonstrates how to export an Excel workbook to HTML with Aspose.Cells, enabling PresentationPreference for a BestFit layout and configuring HtmlLinkTargetType.Blank so every hyperlink opens in a new browser tab.
// Keywords: Aspose.Cells | C# | .NET | Excel to HTML conversion | HtmlSaveOptions | PresentationPreference | BestFit layout | HtmlLinkTargetType | Blank hyperlink target | hyperlink new tab
// Common Searches: Aspose.Cells export Excel to HTML BestFit | set hyperlink target blank Aspose.Cells C# | HtmlSaveOptions PresentationPreference example | convert workbook to HTML with links opening in new tab | Aspose.Cells HTML export options .NET
// Developer Intent: Generate an HTML file from an Excel workbook that automatically adjusts column widths (BestFit) and forces all embedded hyperlinks to open in a new browser tab.
// Use Cases: Publish a financial dashboard as HTML while preserving column sizing and ensuring external links open separately. | Create web‑ready marketing spreadsheets where each product link launches in its own tab. | Automate batch conversion of multiple Excel reports to responsive HTML with consistent link behavior.
// AI Prompts: Write C# code with Aspose.Cells to save a workbook as HTML using PresentationPreference = true and HtmlLinkTargetType = Blank. | Explain the effect of HtmlLinkTargetType.Blank on hyperlinks in HTML generated by Aspose.Cells. | Provide a step‑by‑step guide to configure HtmlSaveOptions for BestFit layout and blank link targets in a .NET project.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Demonstrates how to export an Excel workbook to HTML with Aspose.Cells, enabling PresentationPreference for a BestFit layout and configuring HtmlLinkTargetType.Blank so every hyperlink opens in a new browser tab.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add sample data
            sheet.Cells["A1"].PutValue("Visit Aspose");
            // Add a hyperlink to cell A1
            sheet.Hyperlinks.Add("A1", 1, 1, "https://www.aspose.com");

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            // Enable presentation preference for a better looking HTML (BestFit)
            htmlOptions.PresentationPreference = true;
            // Set hyperlink target to open in a new window/tab
            htmlOptions.LinkTargetType = HtmlLinkTargetType.Blank;

            // Save the workbook as HTML using the configured options
            string outputPath = "output.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"Workbook successfully saved to {outputPath}");
        }
    }
}
