// Title: C# unit test: Verify CSS custom properties appear inside :root when HtmlSaveOptions.EnableCssCustomProperties is true (Aspose.Cells)
// Description: Creates a workbook, adds the same picture twice to trigger a reusable CSS variable, saves the workbook as single‑file HTML with EnableCssCustomProperties enabled, and asserts that the generated markup contains a :root selector and a CSS custom property such as --AsposeImage defined within it.
// Keywords: Aspose.Cells | HTML export | EnableCssCustomProperties | CSS custom properties | :root selector | C# unit test | single file HTML | image CSS variable | automated verification | Aspose.Cells picture
// Common Searches: Aspose.Cells unit test CSS custom properties | How to check :root selector in Aspose.Cells HTML output | EnableCssCustomProperties example C# | Validate CSS variables generated by Aspose.Cells | Aspose.Cells picture CSS variable test
// Developer Intent: Confirm that Aspose.Cells generates a :root block with CSS custom property definitions when CSS custom properties are enabled.
// Use Cases: CI/CD pipeline validation of HTML export styling | Regression testing for reusable image CSS variables | Ensuring multiple pictures share a single CSS custom property | Automated documentation of HTML export features | Testing interaction between SaveAsSingleFile and CSS custom properties
// AI Prompts: Generate an MSTest method that adds two identical pictures to a worksheet, saves the workbook to HTML with EnableCssCustomProperties = true, and asserts the output contains a ':root {' block with a '--AsposeImage' definition. | Write a NUnit test that creates a workbook, configures HtmlSaveOptions for single‑file output with CSS custom properties enabled, and verifies the presence of the :root selector and the custom property in the resulting HTML string. | Provide an xUnit test example that checks the HTML string from workbook.Save for the '--AsposeImage' syntax inside a ':root' selector when SaveAsSingleFile is true.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsTests
{
    // Creates a workbook, adds the same picture twice to trigger a reusable CSS variable, saves the workbook as single‑file HTML with EnableCssCustomProperties enabled, and asserts that the generated markup contains a :root selector and a CSS custom property such as --AsposeImage defined within it.
    public class Program
    {
        public static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // 1x1 pixel PNG (red) encoded in Base64
                const string base64Png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADUlEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==";

                // Convert Base64 string to a memory stream
                byte[] pngBytes = Convert.FromBase64String(base64Png);
                using (MemoryStream imgStream = new MemoryStream(pngBytes))
                {
                    // Add the same image twice to generate a reusable CSS custom property
                    sheet.Pictures.Add(0, 0, imgStream);
                    imgStream.Position = 0; // reset stream for second addition
                    sheet.Pictures.Add(2, 0, imgStream);
                }

                // Configure HTML save options to enable CSS custom properties
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    EnableCssCustomProperties = true,
                    SaveAsSingleFile = true
                };

                // Save the workbook to a memory stream using the configured options
                using (MemoryStream htmlStream = new MemoryStream())
                {
                    workbook.Save(htmlStream, htmlOptions);
                    htmlStream.Position = 0;

                    // Read the generated HTML content
                    string htmlContent = new StreamReader(htmlStream).ReadToEnd();

                    // Verify that a :root selector exists
                    if (!htmlContent.Contains(":root {"))
                    {
                        Console.WriteLine("FAIL: The HTML does not contain a :root selector.");
                    }
                    else
                    {
                        Console.WriteLine("PASS: :root selector found.");
                    }

                    // Verify that at least one CSS custom property (e.g., --AsposeImage) is defined inside :root
                    if (!htmlContent.Contains("--AsposeImage"))
                    {
                        Console.WriteLine("FAIL: No CSS custom property definitions were found in the :root selector.");
                    }
                    else
                    {
                        Console.WriteLine("PASS: CSS custom property '--AsposeImage' found in :root selector.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
