// Title: C# Unit Test – Verify HtmlSaveOptions.LinkTargetType.Blank Produces target="_blank" in HTML Export
// Description: A concise example that creates an Aspose.Cells workbook, adds a hyperlink, sets HtmlSaveOptions.LinkTargetType to Blank, saves to a MemoryStream as HTML, and asserts that the generated anchor tag contains the target="_blank" attribute.
// Keywords: Aspose.Cells | C# unit test | HtmlSaveOptions | LinkTargetType Blank | target=_blank | HTML export verification | hyperlink attribute test | memory stream | automated regression | continuous integration
// Common Searches: Aspose.Cells unit test for HtmlSaveOptions LinkTargetType | how to assert target="_blank" in exported HTML | C# test hyperlink target attribute Aspose.Cells | verify HTML export hyperlink settings | HtmlLinkTargetType Blank example
// Developer Intent: Confirm that setting HtmlSaveOptions.LinkTargetType to Blank adds a target="_blank" attribute to all hyperlinks in the HTML output generated by Aspose.Cells.
// Use Cases: Automated regression test to ensure external links open in a new tab after HTML conversion. | CI pipeline check that hyperlink target settings are correctly applied in Aspose.Cells HTML exports. | Documentation snippet demonstrating how to validate HTML export behavior programmatically.
// AI Prompts: Generate an MSTest/NUnit/xUnit test that asserts Aspose.Cells HtmlSaveOptions.LinkTargetType.Blank adds target="_blank" to hyperlinks in the saved HTML. | Create a parameterized C# test that verifies each HtmlLinkTargetType (Blank, Self, Parent, Top) produces the correct target attribute in the exported HTML. | Provide a code example that reads HTML from a MemoryStream after saving a workbook and checks for a specific target attribute.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

namespace AsposeCellsTests
{
    // A concise example that creates an Aspose.Cells workbook, adds a hyperlink, sets HtmlSaveOptions.LinkTargetType to Blank, saves to a MemoryStream as HTML, and asserts that the generated anchor tag contains the target="_blank" attribute.
    class Program
    {
        static void Main()
        {
            try
            {
                RunLinkTargetAttributeTest();
                Console.WriteLine("Test passed.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Test failed: {ex.Message}");
            }
        }

        private static void RunLinkTargetAttributeTest()
        {
            // Create a new workbook and add a hyperlink to cell A1
            var workbook = new Workbook();
            var worksheet = workbook.Worksheets[0];
            worksheet.Cells["A1"].PutValue("Visit Aspose");
            worksheet.Hyperlinks.Add("A1", 1, 1, "https://www.aspose.com");

            // Configure HTML save options to use the Blank target type
            var saveOptions = new HtmlSaveOptions
            {
                LinkTargetType = HtmlLinkTargetType.Blank
            };

            // Save the workbook to a memory stream in HTML format
            using (var stream = new MemoryStream())
            {
                workbook.Save(stream, saveOptions);
                stream.Position = 0;

                // Read the generated HTML as a string
                string htmlContent;
                using (var reader = new StreamReader(stream, Encoding.UTF8))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Verify that the anchor tag contains target="_blank"
                if (!htmlContent.Contains("target=\"_blank\""))
                {
                    throw new InvalidOperationException(
                        "The generated HTML does not contain target=\"_blank\" when LinkTargetType is set to Blank.");
                }
            }
        }
    }
}
