// Title: Create a C# unit test to confirm Aspose.Cells HTML export omits <style> tags when HtmlSaveOptions.DisableCss is enabled
// AI Prompts: Generate a C# unit test method that saves a Workbook to HTML with HtmlSaveOptions.DisableCss = true and asserts that the resulting HTML string contains no <style> elements. | Write an NUnit or MSTest test case that loads a workbook, exports it using HtmlSaveOptions with CSS disabled, and fails if any <style> tag is found in the output.
// Common Searches: how to test that Aspose.Cells HtmlSaveOptions.DisableCss removes style tags in C# | C# unit test for Aspose.Cells HTML export without CSS | verify no <style> elements in HTML generated by Aspose.Cells | Aspose.Cells HtmlSaveOptions.DisableCss unit testing example | checking HTML output for style tags when disabling CSS in Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions.DisableCss testing | C# unit test for HTML export without style tags | verify HTML output without CSS in Aspose.Cells | disable CSS generation in Aspose.Cells HTML save | assert no style elements in generated HTML

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

namespace AsposeCellsTests
{
    // The example creates a workbook, populates cells, configures HtmlSaveOptions with DisableCss = true, saves the workbook to a memory stream as HTML, reads the HTML content, and asserts that no <style> tags are present, reporting pass or fail.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add sample data
                var workbook = new Workbook();
                var sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Header");
                sheet.Cells["A2"].PutValue(123);
                sheet.Cells["B1"].PutValue("Date");
                sheet.Cells["B2"].PutValue(DateTime.Now);

                // Configure HTML save options to disable CSS generation
                var htmlOptions = new HtmlSaveOptions
                {
                    DisableCss = true // Prevent <style> tags from being emitted
                };

                // Save the workbook to a memory stream using the configured options
                using (var ms = new MemoryStream())
                {
                    workbook.Save(ms, htmlOptions);
                    ms.Position = 0;

                    // Read the generated HTML as a string
                    string htmlContent = Encoding.UTF8.GetString(ms.ToArray());

                    // Verify that no <style> tags are present in the output
                    if (htmlContent.IndexOf("<style", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        Console.WriteLine("Test Failed: <style> tag found in HTML output.");
                    }
                    else
                    {
                        Console.WriteLine("Test Passed: No <style> tags present in HTML output.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Runtime safety: report any unexpected errors
                Console.WriteLine($"Exception occurred: {ex.Message}");
            }
        }
    }
}
