// Title: C# Unit Test: Verify Aspose.Cells HTML Export Includes Gridline Borders Only When ExportGridLines Is True
// Description: Creates a workbook, saves it to HTML with HtmlSaveOptions.ExportGridLines set to true and false, and asserts that the generated HTML contains border CSS only when the flag is true. Uses MemoryStream for in‑memory validation.
// Keywords: Aspose.Cells | HtmlSaveOptions | ExportGridLines | C# unit test | HTML export validation | border CSS | gridline verification | memory stream
// Common Searches: Aspose.Cells unit test ExportGridLines | check border style in HTML export Aspose.Cells | C# test for gridline visibility in HTML output | validate ExportGridLines option programmatically
// Developer Intent: Confirm that HTML generated by Aspose.Cells contains gridline border styles only when ExportGridLines is enabled.
// Use Cases: Automated CI check to prevent unwanted CSS in HTML reports. | Regression test ensuring visual consistency after library updates. | Quality gate for applications that conditionally display spreadsheet gridlines in web pages.
// AI Prompts: Generate an MSTest method that asserts "border" appears in the HTML when ExportGridLines = true and is absent when false. | Write an NUnit test that saves a workbook to HTML with both ExportGridLines settings and validates the CSS output. | Create a xUnit test using MemoryStream to capture Aspose.Cells HTML and verify gridline border presence based on the ExportGridLines flag.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

namespace AsposeCellsTests
{
    // Creates a workbook, saves it to HTML with HtmlSaveOptions.ExportGridLines set to true and false, and asserts that the generated HTML contains border CSS only when the flag is true. Uses MemoryStream for in‑memory validation.
    public class Program
    {
        public static void Main()
        {
            try
            {
                ExportGridLines_IncludesBorderStylesOnlyWhenEnabled();
                Console.WriteLine("Test completed successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Test failed: {ex.Message}");
            }
        }

        private static void ExportGridLines_IncludesBorderStylesOnlyWhenEnabled()
        {
            // Create a workbook and add simple data
            var workbook = new Workbook();
            var worksheet = workbook.Worksheets[0];
            worksheet.IsGridlinesVisible = true;
            worksheet.Cells["A1"].PutValue("Sample");

            // Save HTML with ExportGridLines = true
            var optionsWithGridLines = new HtmlSaveOptions
            {
                ExportGridLines = true
            };
            string htmlWithGridLines;
            using (var ms = new MemoryStream())
            {
                workbook.Save(ms, optionsWithGridLines);
                htmlWithGridLines = Encoding.UTF8.GetString(ms.ToArray());
            }

            // Save HTML with ExportGridLines = false
            var optionsWithoutGridLines = new HtmlSaveOptions
            {
                ExportGridLines = false
            };
            string htmlWithoutGridLines;
            using (var ms = new MemoryStream())
            {
                workbook.Save(ms, optionsWithoutGridLines);
                htmlWithoutGridLines = Encoding.UTF8.GetString(ms.ToArray());
            }

            // Verify that the HTML containing gridlines has border style definitions
            if (!htmlWithGridLines.Contains("border"))
            {
                throw new InvalidOperationException("HTML should contain border styles when ExportGridLines is true.");
            }

            // Verify that the HTML without gridlines does not contain border style definitions
            if (htmlWithoutGridLines.Contains("border"))
            {
                throw new InvalidOperationException("HTML should not contain border styles when ExportGridLines is false.");
            }
        }
    }
}
