// Title: C# unit test to confirm HtmlSaveOptions.DisableCss removes <style> tags from Aspose.Cells HTML output
// Description: Creates a workbook, applies bold red formatting to cell A1, saves it as HTML with HtmlSaveOptions.DisableCss = true, reads the generated markup, and asserts that no <style> elements are present, reporting pass or fail.
// Keywords: Aspose.Cells | HtmlSaveOptions.DisableCss | C# unit test | HTML export without CSS | assert no style tag | inline styles only | Aspose.Cells HTML validation
// Common Searches: Aspose.Cells test DisableCss no style tag | how to verify HtmlSaveOptions.DisableCss in C# | unit test for Aspose.Cells HTML export | assert HTML output has no <style> with DisableCss | Aspose.Cells HTML inline style test
// Developer Intent: Write an automated test that fails if the HTML generated by Aspose.Cells contains any <style> tags when DisableCss is enabled.
// Use Cases: Validate email‑ready HTML from Aspose.Cells uses only inline styling. | Integrate into CI pipelines to enforce CSS‑free HTML exports. | Prevent regressions after library upgrades that might re‑introduce style blocks.
// AI Prompts: Generate an MSTest method that creates a styled workbook, saves it to HTML with HtmlSaveOptions.DisableCss = true, and asserts the output string lacks <style> tags. | Provide NUnit code that verifies Aspose.Cells HtmlSaveOptions.DisableCss eliminates all CSS blocks from the exported HTML. | Write an xUnit test checking that Aspose.Cells HTML output contains no <style> elements when DisableCss is set.

using System;
using System.IO;
using System.Text;
using System.Drawing;
using Aspose.Cells;

namespace AsposeCellsTests
{
    // Creates a workbook, applies bold red formatting to cell A1, saves it as HTML with HtmlSaveOptions.DisableCss = true, reads the generated markup, and asserts that no <style> elements are present, reporting pass or fail.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add styled content
                var workbook = new Workbook();
                var worksheet = workbook.Worksheets[0];
                var cell = worksheet.Cells["A1"];
                cell.PutValue("Styled Text");

                // Apply bold and red font style
                var style = cell.GetStyle();
                style.Font.IsBold = true;
                style.Font.Color = Color.Red;
                cell.SetStyle(style);

                // Configure HtmlSaveOptions to disable CSS (use only inline styles)
                var htmlOptions = new HtmlSaveOptions
                {
                    DisableCss = true
                };

                // Save the workbook to a memory stream as HTML
                using (var stream = new MemoryStream())
                {
                    workbook.Save(stream, htmlOptions);
                    stream.Position = 0;

                    // Read the generated HTML content
                    string htmlContent;
                    using (var reader = new StreamReader(stream, Encoding.UTF8))
                    {
                        htmlContent = reader.ReadToEnd();
                    }

                    // Verify that no <style> tags are present in the output
                    bool containsStyleTag = htmlContent.IndexOf("<style", StringComparison.OrdinalIgnoreCase) >= 0;
                    if (containsStyleTag)
                    {
                        Console.WriteLine("Test Failed: HTML output contains <style> tags when DisableCss is true.");
                    }
                    else
                    {
                        Console.WriteLine("Test Passed: HTML output does not contain <style> tags when DisableCss is true.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
