// Title: Generate an Excel workbook, apply an unavailable font to a cell, and confirm Arial fallback in the HTML export using Aspose.Cells for .NET
// AI Prompts: Write C# code with Aspose.Cells that inserts text into cell A1, sets the cell's Font.Name to a non‑existent font, saves the workbook as HTML, and programmatically checks that the resulting HTML contains a font‑family declaration for Arial. | Adapt an Aspose.Cells example to assign an invalid font to a worksheet cell, export the workbook to HTML, and verify the fallback to the default Arial font by parsing the generated HTML file.
// Common Searches: Aspose.Cells .NET how to detect fallback font when exporting to HTML | C# set a missing font for an Excel cell and check HTML output | verify default Arial font in HTML generated by Aspose.Cells | export workbook to HTML with unavailable font using Aspose.Cells | Aspose.Cells HTML export font fallback behavior example
// Tags: Aspose.Cells set cell font fallback HTML export | C# Aspose.Cells export workbook to HTML missing font | verify Arial fallback in Aspose.Cells HTML output | nonexistent font handling Aspose.Cells .NET | HTML generation font-family detection Aspose.Cells

using Aspose.Cells;
using System;
using System.IO;

// The example creates a new workbook, writes "Sample Text" to cell A1, assigns a non‑existent font name to the cell's style, saves the workbook as HTML, reads the generated file, and checks for an Arial font‑family declaration, confirming that Aspose.Cells falls back to Arial when the specified font is unavailable.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Get the first worksheet and cell A1
        Worksheet sheet = workbook.Worksheets[0];
        Cell cell = sheet.Cells["A1"];
        cell.PutValue("Sample Text");

        // Assign a non‑existent font to the cell
        Style style = cell.GetStyle();
        style.Font.Name = "NonExistentFontXYZ"; // This font does not exist
        cell.SetStyle(style);

        // Save the workbook as HTML
        string htmlFile = "output.html";
        workbook.Save(htmlFile, SaveFormat.Html);

        // Verify that the default font appears in the generated HTML
        string htmlContent = File.ReadAllText(htmlFile);

        // Aspose.Cells falls back to Arial when the specified font is unavailable
        bool defaultFontFound = htmlContent.Contains("font-family:Arial") ||
                                htmlContent.Contains("font-family: \"Arial\"");

        Console.WriteLine(defaultFontFound
            ? "Default font (Arial) is applied in the HTML output."
            : "Default font not found in the HTML output.");
    }
}
