// Title: Create a C# unit test with Aspose.Cells that checks for CSS custom properties inside the :root selector during HTML export
// AI Prompts: Generate a C# test method (NUnit/MSTest) that builds a Workbook, applies a style, saves it to HTML with HtmlSaveOptions, reads the markup from a MemoryStream, and asserts that a ':root' block containing at least one '--' CSS variable is present. | Write code that uses Aspose.Cells to export a workbook to a MemoryStream as HTML, then scans the resulting string to verify the existence of the ':root' selector and any CSS custom property, throwing an exception if the validation fails.
// Common Searches: how to unit test Aspose.Cells HTML export for CSS variables in C# | C# verify that :root selector is generated by Aspose.Cells HtmlSaveOptions | Aspose.Cells unit test checking custom properties (--variable) in exported HTML | assert CSS custom property presence in HTML saved from Aspose.Cells workbook | C# test for CSS variable '--' generation when exporting workbook to HTML with Aspose.Cells
// Tags: Aspose.Cells HTML export CSS variables verification | C# unit test for :root selector generation | HtmlSaveOptions custom property assertion | validate CSS custom properties in exported HTML | Aspose.Cells workbook style to HTML test

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using System.Drawing;

namespace AsposeCellsTests
{
    // The example creates a workbook, applies a red font style, exports it to HTML via HtmlSaveOptions into a memory stream, reads the HTML string, and throws an exception if the output lacks a ':root {' selector or any CSS custom property prefixed with '--'.
    public class CssCustomPropertiesTests
    {
        public static void Main()
        {
            try
            {
                new CssCustomPropertiesTests().RunTest();
                Console.WriteLine("Test completed successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Test failed: {ex.Message}");
            }
        }

        public void RunTest()
        {
            // Create a new workbook and add some data
            var workbook = new Workbook();
            var sheet = workbook.Worksheets[0];
            var cell = sheet.Cells["A1"];
            cell.PutValue("Test");

            // Apply a style that will be exported
            var style = cell.GetStyle();
            style.Font.Color = Color.Red;
            cell.SetStyle(style);

            // Configure HTML save options
            var htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

            // Save the workbook to a memory stream
            using (var ms = new MemoryStream())
            {
                try
                {
                    workbook.Save(ms, htmlOptions);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to save workbook to HTML.", ex);
                }

                ms.Position = 0;

                // Read the generated HTML as a string
                string htmlContent;
                using (var reader = new StreamReader(ms, Encoding.UTF8))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Verify that the :root selector exists
                if (!htmlContent.Contains(":root {"))
                {
                    throw new InvalidOperationException("The generated HTML does not contain a :root selector.");
                }

                // Verify that at least one CSS custom property is defined inside :root
                if (!htmlContent.Contains("--a"))
                {
                    throw new InvalidOperationException("No CSS custom properties were found inside the :root selector.");
                }
            }
        }
    }
}
