// Title: C# unit test to confirm a worksheet cell value appears in the HTML output generated by Aspose.Cells
// AI Prompts: Write a C# method that puts a value into cell A1, saves the workbook to HTML with HtmlSaveOptions (UTF‑8) via a MemoryStream, and throws an exception when the exported HTML does not contain that value. | Create a self‑contained C# console example that creates a Workbook, assigns a specific string to a cell, exports the sheet to HTML, reads the result as text, and asserts the presence of the string without using external testing frameworks.
// Common Searches: how to write a C# test that checks Aspose.Cells HTML export contains a specific cell value | C# Aspose.Cells verify text in generated HTML using MemoryStream | unit testing Aspose.Cells HtmlSaveOptions for content presence in HTML output | assert that cell A1 value appears in HTML file created by Aspose.Cells in C#
// Tags: Aspose.Cells HtmlSaveOptions content verification | C# unit test workbook to HTML conversion | validate cell value in generated HTML Aspose | memory stream HTML export Aspose.Cells | UTF-8 encoding HTML output Aspose.Cells

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

namespace AsposeCellsTests
{
    // The example creates a new Workbook, writes "TestValue" to cell A1, saves the workbook to HTML using HtmlSaveOptions with UTF‑8 encoding into a MemoryStream, reads the HTML string, and throws an InvalidOperationException if the expected value is not found in the HTML content.
    public class HtmlExportTests
    {
        // Entry point for the console application
        public static void Main()
        {
            try
            {
                new HtmlExportTests().CellValue_ShouldAppearInHtmlOutput();
                Console.WriteLine("Test passed: Expected cell value was found in the HTML output.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Test failed: {ex.Message}");
            }
        }

        // Replicates the original NUnit test logic without NUnit dependencies
        public void CellValue_ShouldAppearInHtmlOutput()
        {
            // Create a new workbook and access the first worksheet
            var workbook = new Workbook();
            var worksheet = workbook.Worksheets[0];

            // Set a specific value in cell A1
            const string expectedValue = "TestValue";
            worksheet.Cells["A1"].PutValue(expectedValue);

            // Save the workbook to HTML using a memory stream
            using (var htmlStream = new MemoryStream())
            {
                // Configure HTML save options (default options are sufficient)
                var saveOptions = new HtmlSaveOptions
                {
                    // Ensure the output is encoded in UTF-8
                    Encoding = Encoding.UTF8
                };

                // Export the workbook to HTML
                workbook.Save(htmlStream, saveOptions);

                // Convert the stream content to a string for verification
                htmlStream.Position = 0;
                string htmlContent;
                using (var reader = new StreamReader(htmlStream, Encoding.UTF8))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Verify that the expected cell value appears in the generated HTML
                if (!htmlContent.Contains(expectedValue))
                {
                    throw new InvalidOperationException(
                        $"The HTML output does not contain the expected cell value '{expectedValue}'.");
                }
            }
        }
    }
}
