// Title: Programmatically create an Excel workbook, add a comment to cell A1, export comments to HTML, and verify the comment with Aspose.Cells for .NET
// AI Prompts: Write C# code using Aspose.Cells to create a new workbook, insert a comment into cell A1, and save the file as HTML with comments exported. | Add logic that reads the generated HTML file, searches for the comment text, and prints a success or failure message.
// Common Searches: Aspose.Cells C# export cell comments to HTML file | How to enable comment export when saving a workbook as HTML using Aspose.Cells | Verify that a worksheet comment appears in the HTML output generated by Aspose.Cells | Programmatically add a comment to an Excel cell and save as HTML with Aspose.Cells for .NET | Read HTML file produced by Aspose.Cells to confirm comment text
// Tags: add worksheet comment Aspose.Cells C# | HtmlSaveOptions IsExportComments setting | save workbook as HTML with comments Aspose.Cells | check HTML output for Excel comment Aspose.Cells | programmatic Excel workbook creation Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example creates a new workbook, adds a comment to cell A1, configures HtmlSaveOptions.IsExportComments to true, saves the workbook as HTML, reads the resulting file, and confirms that the comment text is present in the HTML content.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];

        // Add a comment to cell A1
        int commentIndex = sheet.Comments.Add("A1");
        Comment comment = sheet.Comments[commentIndex];
        comment.Author = "Author";
        comment.Note = "This is a test comment";

        // Configure HTML save options to export comments
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
        htmlOptions.IsExportComments = true;

        // Save the workbook as HTML
        string htmlFile = "output.html";
        workbook.Save(htmlFile, htmlOptions);

        // Verify that the comment appears in the generated HTML
        string htmlContent = File.ReadAllText(htmlFile);
        if (htmlContent.Contains("This is a test comment"))
        {
            Console.WriteLine("Comment successfully exported to HTML.");
        }
        else
        {
            Console.WriteLine("Comment not found in HTML.");
        }
    }
}
