// Title: C# Unit Test – Verify ExportHiddenWorksheet=true Shows Hidden Sheet Titles in Aspose.Cells HTML Export
// Description: Creates a workbook with a visible and a hidden worksheet, saves it to HTML using Aspose.Cells HtmlSaveOptions with ExportHiddenWorksheet set to true, and asserts that the hidden sheet name appears in the generated HTML string. The test runs without external test frameworks, making it suitable for CI pipelines or quick validation.
// Keywords: Aspose.Cells | C# | .NET | HtmlSaveOptions | ExportHiddenWorksheet | hidden worksheet | HTML export unit test | verify hidden sheet title | automated testing | memory stream
// Common Searches: Aspose.Cells unit test hidden worksheet HTML export | ExportHiddenWorksheet true example C# | how to check hidden sheet title in Aspose.Cells HTML output | C# test for Aspose.Cells HtmlSaveOptions ExportHiddenWorksheet | verify hidden sheets are exported with Aspose.Cells
// Developer Intent: Confirm that setting ExportHiddenWorksheet to true causes hidden worksheet titles to be included in the HTML generated by Aspose.Cells.
// Use Cases: Add to CI/CD to prevent regression of hidden‑sheet export behavior. | Validate HTML previews in reporting tools that must list all worksheet names. | Create a quick sanity check for developers customizing HtmlSaveOptions.
// AI Prompts: Generate an NUnit test that asserts hidden worksheet titles appear in the HTML when ExportHiddenWorksheet is true using Aspose.Cells for .NET. | Write a MSTest method that verifies Aspose.Cells HtmlSaveOptions ExportHiddenWorksheet includes hidden sheets and fails if the name is missing. | Provide an xUnit example that checks the HTML string for the hidden sheet name after saving a workbook with ExportHiddenWorksheet enabled.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExample
{
    // Creates a workbook with a visible and a hidden worksheet, saves it to HTML using Aspose.Cells HtmlSaveOptions with ExportHiddenWorksheet set to true, and asserts that the hidden sheet name appears in the generated HTML string. The test runs without external test frameworks, making it suitable for CI pipelines or quick validation.
    class Program
    {
        static void Main()
        {
            try
            {
                ExportHiddenWorksheet_IncludesHiddenSheetTitle_WhenTrue();
                Console.WriteLine("Test passed.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Test failed: {ex.Message}");
            }
        }

        // Replicates the original NUnit test without external dependencies
        static void ExportHiddenWorksheet_IncludesHiddenSheetTitle_WhenTrue()
        {
            // Create a workbook with a visible sheet and a hidden sheet
            var workbook = new Workbook();

            var visibleSheet = workbook.Worksheets[0];
            visibleSheet.Name = "VisibleSheet";
            visibleSheet.Cells["A1"].PutValue("Visible Data");

            var hiddenSheet = workbook.Worksheets.Add("HiddenSheet");
            hiddenSheet.Cells["A1"].PutValue("Hidden Data");
            hiddenSheet.IsVisible = false;

            // Configure HTML save options to export hidden worksheets
            var saveOptions = new HtmlSaveOptions
            {
                ExportHiddenWorksheet = true,
                ExportActiveWorksheetOnly = false
            };

            // Save to a memory stream and read the HTML as a string
            string htmlContent;
            using (var ms = new MemoryStream())
            {
                workbook.Save(ms, saveOptions);
                htmlContent = Encoding.UTF8.GetString(ms.ToArray());
            }

            // Verify that the hidden sheet title appears in the HTML output
            if (!htmlContent.Contains("HiddenSheet"))
            {
                throw new InvalidOperationException(
                    "HTML output should contain the hidden sheet title when ExportHiddenWorksheet is true.");
            }
        }
    }
}
