// Title: C# Unit Test for Aspose.Cells HTML Export – Verify :root Selector & CSS Custom Properties
// Description: Creates a temporary 1×1 PNG, builds a Workbook with styled cells and two pictures, saves it to HTML using HtmlSaveOptions with EnableCssCustomProperties true or false, reads the generated HTML from a MemoryStream, and asserts the presence or absence of the ":root" selector and "--Aspose" custom variables.
// Keywords: Aspose.Cells | HtmlSaveOptions | EnableCssCustomProperties | CSS custom properties | root selector | C# unit test | NUnit | MSTest | xUnit | HTML export | temporary PNG | memory stream
// Common Searches: Aspose.Cells unit test for HTML export | verify :root selector in Aspose.Cells HTML output | EnableCssCustomProperties example C# | check CSS custom properties generated by Aspose.Cells | how to test Aspose.Cells HTMLSaveOptions
// Developer Intent: Create an automated test that confirms the HTML generated by Aspose.Cells includes a :root selector and custom CSS variables when EnableCssCustomProperties is enabled.
// Use Cases: Continuous‑integration validation that CSS custom properties are emitted correctly after library upgrades. | Regression testing to catch accidental removal of the :root selector in HTML exports. | Comparing different HtmlSaveOptions configurations for styling consistency in web reports.
// AI Prompts: Generate an NUnit test that builds a workbook, adds styled cells and images, saves to HTML with EnableCssCustomProperties true, and asserts the HTML contains ":root {" and "--Aspose". | Write a MSTest method that verifies disabling EnableCssCustomProperties removes the :root selector and custom variables from the Aspose.Cells HTML output. | Provide an xUnit test using a temporary PNG to check Aspose.Cells HTML conversion with and without CSS custom properties.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsDemo
{
    // Creates a temporary 1×1 PNG, builds a Workbook with styled cells and two pictures, saves it to HTML using HtmlSaveOptions with EnableCssCustomProperties true or false, reads the generated HTML from a MemoryStream, and asserts the presence or absence of the ":root" selector and "--Aspose" custom variables.
    class Program
    {
        // Path to the temporary PNG image (nullable because it is set at runtime)
        private static string? _tempImagePath;

        static void Main()
        {
            try
            {
                CreateTempImage();

                EnableCssCustomProperties_ShouldGenerateRootSelector();
                DisableCssCustomProperties_ShouldNotGenerateRootSelector();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Unexpected error: {ex.Message}");
            }
            finally
            {
                CleanupTempImage();
            }
        }

        // Create a simple 1x1 PNG image for testing without relying on System.Drawing
        private static void CreateTempImage()
        {
            try
            {
                // Base64‑encoded 1x1 pixel PNG (transparent)
                const string base64Png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADUlEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==";
                byte[] pngBytes = Convert.FromBase64String(base64Png);
                _tempImagePath = Path.Combine(Path.GetTempPath(), $"temp_{Guid.NewGuid()}.png");
                File.WriteAllBytes(_tempImagePath, pngBytes);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to create temp image: {ex.Message}");
            }
        }

        // Delete the temporary image file
        private static void CleanupTempImage()
        {
            try
            {
                if (!string.IsNullOrEmpty(_tempImagePath) && File.Exists(_tempImagePath))
                {
                    File.Delete(_tempImagePath);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to delete temp image: {ex.Message}");
            }
        }

        // Test with CSS custom properties enabled
        private static void EnableCssCustomProperties_ShouldGenerateRootSelector()
        {
            try
            {
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Sample");

                // Apply bold blue font
                var style = sheet.Cells["A1"].GetStyle();
                style.Font.IsBold = true;
                style.Font.Color = System.Drawing.Color.Blue;
                sheet.Cells["A1"].SetStyle(style);

                // Add the same image twice to trigger CSS custom property usage
                int imgIdx1 = sheet.Pictures.Add(1, 1, _tempImagePath);
                int imgIdx2 = sheet.Pictures.Add(5, 5, _tempImagePath);
                sheet.Pictures[imgIdx1].Width = 50;
                sheet.Pictures[imgIdx1].Height = 50;
                sheet.Pictures[imgIdx2].Width = 50;
                sheet.Pictures[imgIdx2].Height = 50;

                // Configure HTML save options
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    EnableCssCustomProperties = true,
                    SaveAsSingleFile = true
                };

                // Save to memory stream and inspect HTML
                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.Save(ms, htmlOptions);
                    ms.Position = 0;
                    string htmlContent = new StreamReader(ms).ReadToEnd();

                    bool hasRoot = htmlContent.Contains(":root {");
                    bool hasCustom = htmlContent.Contains("--Aspose");

                    Console.WriteLine("EnableCssCustomProperties test:");
                    Console.WriteLine($"Contains :root selector: {hasRoot}");
                    Console.WriteLine($"Contains custom property: {hasCustom}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"EnableCssCustomProperties test failed: {ex.Message}");
            }
        }

        // Test with CSS custom properties disabled
        private static void DisableCssCustomProperties_ShouldNotGenerateRootSelector()
        {
            try
            {
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Sample");

                // Apply bold blue font
                var style = sheet.Cells["A1"].GetStyle();
                style.Font.IsBold = true;
                style.Font.Color = System.Drawing.Color.Blue;
                sheet.Cells["A1"].SetStyle(style);

                // Add the same image twice
                sheet.Pictures.Add(1, 1, _tempImagePath);
                sheet.Pictures.Add(5, 5, _tempImagePath);

                // Configure HTML save options with CSS custom properties disabled
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    EnableCssCustomProperties = false,
                    SaveAsSingleFile = true
                };

                // Save to memory stream and inspect HTML
                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.Save(ms, htmlOptions);
                    ms.Position = 0;
                    string htmlContent = new StreamReader(ms).ReadToEnd();

                    bool hasRoot = htmlContent.Contains(":root {");
                    bool hasCustom = htmlContent.Contains("--Aspose");

                    Console.WriteLine("DisableCssCustomProperties test:");
                    Console.WriteLine($"Contains :root selector: {hasRoot}");
                    Console.WriteLine($"Contains custom property: {hasCustom}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"DisableCssCustomProperties test failed: {ex.Message}");
            }
        }
    }
}
