// Title: Create an NUnit unit test in C# to verify that Aspose.Cells HTML export generates CSS custom properties inside a :root selector
// AI Prompts: Write an NUnit test that creates a Workbook, saves it to HTML with Aspose.Cells HtmlSaveOptions, and asserts that the output contains a ':root {' block. | Add an assertion that checks for a CSS variable such as '--a1-bg-color' within the ':root' selector after exporting the workbook to HTML. | Refactor the test to throw an AssertionException with a clear message when the ':root' selector or the expected CSS custom property is missing.
// Common Searches: how to unit test Aspose.Cells HTML output for CSS variables in C# | verify :root selector exists in HTML generated by Aspose.Cells SaveOptions | C# NUnit test for Aspose.Cells ExportImagesAsBase64 and CSS custom properties | check for '--a1-bg-color' variable in Aspose.Cells HTML export result | Aspose.Cells HtmlSaveOptions enable CSS custom properties unit test example
// Tags: Aspose.Cells HtmlSaveOptions CSS custom properties | C# NUnit test Aspose.Cells HTML export | verify :root selector in generated HTML | assert CSS variable '--a1-bg-color' presence | Excel cell style to CSS variable conversion

using System;
using System.IO;
using System.Text;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsCssTests
{
    // This example demonstrates how to write an NUnit unit test in C# that creates an Aspose.Cells workbook, applies styling, saves it to HTML using HtmlSaveOptions, and then validates that the generated HTML includes a ':root' selector with a CSS custom property (e.g., '--a1-bg-color'), providing clear pass/fail assertions.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add some data
                var workbook = new Workbook();
                var sheet = workbook.Worksheets[0];
                var cell = sheet.Cells["A1"];
                cell.PutValue("Test");

                // Apply red font color using the correct style API
                var style = cell.GetStyle();
                style.Font.Color = Color.Red;
                cell.SetStyle(style);

                // Configure HTML save options
                var htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
                {
                    ExportImagesAsBase64 = true,
                    ExportActiveWorksheetOnly = true
                    // Note: EnableCssCustomProperties may not be available in older versions
                };

                // Save the workbook to a memory stream
                using (var ms = new MemoryStream())
                {
                    workbook.Save(ms, htmlOptions);
                    ms.Position = 0;

                    // Read the generated HTML as a string
                    string htmlContent;
                    using (var reader = new StreamReader(ms, Encoding.UTF8))
                    {
                        htmlContent = reader.ReadToEnd();
                    }

                    // Verify that a :root selector exists
                    if (!htmlContent.Contains(":root {"))
                    {
                        Console.WriteLine("FAIL: The :root selector was not found in the generated HTML.");
                    }
                    else
                    {
                        Console.WriteLine("PASS: :root selector found.");
                    }

                    // Verify that at least one CSS custom property is defined inside the :root selector
                    // Example expected pattern: --a1-bg-color: #FF0000;
                    if (!htmlContent.Contains("--a1-bg-color:"))
                    {
                        Console.WriteLine("FAIL: CSS custom property '--a1-bg-color' was not defined within the :root selector.");
                    }
                    else
                    {
                        Console.WriteLine("PASS: CSS custom property '--a1-bg-color' found.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Runtime safety: log any unexpected errors
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
