// Title: C# unit test to confirm Aspose.Cells HTML export generates CSS custom properties inside a :root selector
// AI Prompts: Write an NUnit test in C# that creates a Workbook, saves it as HTML with Aspose.Cells, and asserts that the output contains a ':root' selector with at least one CSS variable (e.g., '--myVar'). | Refactor the console program into a MSTest method that validates the presence of CSS custom properties in the HTML generated by HtmlSaveOptions. | Add a Boolean parameter to the test to toggle HtmlSaveOptions.EnableCssCustomProperties and verify that the ':root' selector appears only when the option is enabled.
// Common Searches: how to unit test Aspose.Cells HTML output for CSS variables | c# check if generated HTML contains :root selector using Aspose.Cells | verify css custom property presence in Aspose.Cells saved HTML with NUnit | Aspose.Cells HtmlSaveOptions enableCssCustomProperties unit test example
// Tags: Aspose.Cells HTML export unit test | verify CSS custom properties in generated HTML | HtmlSaveOptions EnableCssCustomProperties validation | C# NUnit test for :root selector | assert CSS variable definition in Aspose.Cells output

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Saving;

namespace AsposeCellsCssTests
{
    // The example creates a workbook, adds sample data, saves it to an in‑memory HTML stream using Aspose.Cells, reads the HTML content, and asserts that the result includes a ':root' selector and at least one CSS custom property (identified by '--'), reporting pass or failure.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook with a single worksheet
                var workbook = new Workbook();
                var sheet = workbook.Worksheets[0];
                sheet.Name = "Data";

                // Populate sample data
                sheet.Cells["A1"].PutValue("Header");
                sheet.Cells["A2"].PutValue(123);

                // Configure HTML save options (default settings)
                var htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

                // Save the workbook to a memory stream as HTML
                using (var htmlStream = new MemoryStream())
                {
                    workbook.Save(htmlStream, htmlOptions);
                    htmlStream.Position = 0;

                    // Read the generated HTML content as a string
                    string htmlContent;
                    using (var reader = new StreamReader(htmlStream, Encoding.UTF8))
                    {
                        htmlContent = reader.ReadToEnd();
                    }

                    // Verify that a :root selector exists and contains at least one CSS custom property
                    bool containsRootSelector = htmlContent.Contains(":root");
                    bool containsCustomProperty = htmlContent.Contains("--");

                    if (!containsRootSelector)
                    {
                        Console.WriteLine("FAIL: The generated HTML does not contain a ':root' selector.");
                    }
                    else if (!containsCustomProperty)
                    {
                        Console.WriteLine("FAIL: The generated HTML does not contain any CSS custom property definitions.");
                    }
                    else
                    {
                        Console.WriteLine("PASS: CSS custom properties are present in the generated HTML.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ERROR: {ex.Message}");
            }
        }
    }
}
