// Title: Aspose.Cells C# – Save Workbook to HTML with Default Font Fallback for Missing Fonts
// Description: Creates a workbook, writes text to cell A1, applies a style with a non‑existent font, sets HtmlSaveOptions.DefaultFontName to a known fallback (e.g., Arial), saves the file as HTML, and checks the generated CSS for the fallback font declaration.
// Keywords: Aspose.Cells HTML export | HtmlSaveOptions DefaultFontName | fallback font Aspose.Cells | missing font handling C# | verify HTML font-family | C# Aspose.Cells example
// Common Searches: Aspose.Cells set fallback font when saving to HTML | How to use HtmlSaveOptions.DefaultFontName in C# | Detect default font in Aspose.Cells HTML output | Assign unavailable font to a cell Aspose.Cells
// Developer Intent: Generate HTML from a workbook that uses a predefined fallback font when a cell references a font not installed on the system, and confirm the fallback appears in the output.
// Use Cases: Produce HTML reports on servers lacking certain fonts, ensuring consistent appearance with a known fallback like Arial. | Automate regression tests that validate HtmlSaveOptions.DefaultFontName injects the correct CSS rule. | Create sample code for documentation showing how Aspose.Cells handles missing fonts during HTML conversion.
// AI Prompts: Write C# code with Aspose.Cells to assign a non‑existent font to a cell, set HtmlSaveOptions.DefaultFontName to 'Calibri', save as HTML, and verify the CSS contains 'font-family:Calibri'. | Explain the mechanism Aspose.Cells uses to replace unavailable fonts with the DefaultFontName during HTML export. | Provide a step‑by‑step guide for unit testing the default font fallback in HTML generated by Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlDefaultFontDemo
{
    // Creates a workbook, writes text to cell A1, applies a style with a non‑existent font, sets HtmlSaveOptions.DefaultFontName to a known fallback (e.g., Arial), saves the file as HTML, and checks the generated CSS for the fallback font declaration.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Put some text into cell A1
            Cell cell = sheet.Cells["A1"];
            cell.PutValue("Text with a non‑existent font");

            // Create a style and assign a font that does not exist on the system
            Style style = workbook.CreateStyle();
            style.Font.Name = "NonExistentFontXYZ"; // deliberately missing font
            cell.SetStyle(style);

            // Configure HTML save options to use a known default font
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            htmlOptions.DefaultFontName = "Arial"; // fallback font for missing fonts

            // Save the workbook as HTML
            string htmlPath = "output.html";
            workbook.Save(htmlPath, htmlOptions);

            // Verify that the default font appears in the generated HTML
            string htmlContent = File.ReadAllText(htmlPath);
            bool defaultFontUsed = htmlContent.Contains("font-family:Arial");

            Console.WriteLine($"HTML saved to '{htmlPath}'.");
            Console.WriteLine($"Default font 'Arial' detected in HTML: {defaultFontUsed}");
        }
    }
}
