// Title: Set a custom gradient angle for WordArt and embed it in CSS linear‑gradient during HTML export with Aspose.Cells for .NET
// AI Prompts: Generate C# code that creates a rectangular WordArt shape, applies a two‑color linear gradient at a specified angle, and saves the workbook as HTML using Aspose.Cells. | Write a C# routine that reads the HTML produced by Aspose.Cells, finds the linear‑gradient declaration, and replaces it with a CSS gradient that includes the original angle using a regular expression.
// Common Searches: c# asp.net apply gradient angle to WordArt shape when exporting Excel to HTML with Aspose.Cells | preserve WordArt linear gradient direction in HTML output generated by Aspose.Cells | regex replace linear-gradient angle in Aspose.Cells HTML conversion | customize CSS linear-gradient angle based on shape fill in Aspose.Cells export | two‑color gradient fill for shape and HTML export using Aspose.Cells .NET
// Tags: Aspose.Cells shape gradient angle | HTML export CSS linear-gradient angle | C# regex modify Aspose.Cells HTML | WordArt two‑color gradient Aspose.Cells | Excel shape to HTML gradient orientation

using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsWordArtGradient
{
    // The example creates a workbook, adds a rectangular WordArt shape, sets its text and font, applies a two‑color linear gradient with a custom angle, saves the workbook as HTML, then uses a regular expression to replace the generic linear‑gradient CSS with one that includes the specified angle, and finally writes the corrected HTML file.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Add a rectangular shape that will act as WordArt
                Shape wordArt = sheet.Shapes.AddShape(MsoDrawingType.Rectangle, 0, 0, 0, 0, 100, 300);

                // Set the displayed text and its formatting
                wordArt.Text = "Gradient WordArt";
                wordArt.Font.Name = "Arial";
                wordArt.Font.Size = 36;
                wordArt.Font.IsBold = true;

                // Apply a linear two‑color gradient fill (45° angle)
                int gradientAngle = 45;
                FillFormat fill = wordArt.Fill;

                // Use a cast to the enum value for linear gradient (value 0) to avoid version‑specific enum issues
                fill.SetTwoColorGradient(Color.Blue, Color.LightBlue, (GradientStyleType)0, gradientAngle);

                // Save the workbook to a temporary HTML file
                string tempHtmlPath = "WordArtGradient_temp.html";
                workbook.Save(tempHtmlPath, SaveFormat.Html);

                // Read the generated HTML
                string html = File.ReadAllText(tempHtmlPath);

                // Adjust CSS gradient to include the angle (e.g., linear-gradient(45deg, color1, color2))
                string pattern = @"linear-gradient\(\s*([^,]+),\s*([^,]+)\s*\)";
                string replacement = $"linear-gradient({gradientAngle}deg, $1, $2)";
                string updatedHtml = Regex.Replace(html, pattern, replacement, RegexOptions.IgnoreCase);

                // Write the final HTML file
                string finalHtmlPath = "WordArtGradient.html";
                File.WriteAllText(finalHtmlPath, updatedHtml);

                // Clean up temporary file
                if (File.Exists(tempHtmlPath))
                {
                    File.Delete(tempHtmlPath);
                }

                Console.WriteLine($"HTML file generated successfully: {finalHtmlPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
