// Title: How to disable downlevel revealed comments when saving an Excel workbook to HTML with Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an Excel workbook and saves it as HTML with IE‑specific markup disabled using Aspose.Cells. | Show the configuration steps for Aspose.Cells HtmlSaveOptions to turn off legacy conditional comments for better older‑browser compatibility. | Explain how suppressing legacy conditional markup affects the HTML generated by Aspose.Cells.
// Common Searches: Aspose.Cells C# disable downlevel revealed comments HTML export | Turn off conditional comments in HTML output from Aspose.Cells | HtmlSaveOptions.DisableDownlevelRevealedComments usage example | Improve older browser compatibility when converting Excel to HTML with Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions conditional comments | C# export Excel to HTML without downlevel comments | HTML compatibility older browsers Aspose.Cells | Excel to HTML conversion settings C# | Aspose.Cells property to suppress conditional comments

using Aspose.Cells;
using Aspose.Cells.Rendering;

// // Loads an Excel file, configures HtmlSaveOptions.DisableDownlevelRevealedComments to true for better compatibility with legacy browsers, and saves the workbook as an HTML document.
class Program
{
    static void Main()
    {
        // Load an existing workbook
        Workbook workbook = new Workbook("input.xlsx");

        // Set HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
        // Disable downlevel revealed comments to improve compatibility with older browsers
        htmlOptions.DisableDownlevelRevealedComments = true;

        // Save the workbook as HTML using the configured options
        workbook.Save("output.html", htmlOptions);
    }
}
