// Title: How to disable downlevel revealed comments when exporting an Excel workbook to HTML with Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that loads an Excel file and saves it as HTML with HtmlSaveOptions.DisableDownlevelRevealedComments set to true using Aspose.Cells. | Show how to configure Aspose.Cells HtmlSaveOptions to suppress IE conditional comments during HTML export in a .NET application.
// Common Searches: Aspose.Cells HtmlSaveOptions.DisableDownlevelRevealedComments C# example | remove IE conditional comments from HTML output generated by Aspose.Cells | export Excel to HTML without downlevel revealed comments using Aspose.Cells .NET | how to turn off conditional comments in Aspose.Cells HTML export | C# save workbook as HTML compatible with older browsers Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions.DisableDownlevelRevealedComments | export Excel to HTML without conditional comments | HTML export compatibility older browsers Aspose.Cells | C# Aspose.Cells HTML save options | disable downlevel revealed comments .NET

using System;
using System.IO;
using Aspose.Cells;

// The sample loads an Excel workbook, configures HtmlSaveOptions.DisableDownlevelRevealedComments to true to suppress IE conditional comments, and saves the workbook as HTML, including basic file existence checks and exception handling.
class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.html";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook from the existing Excel file
            Workbook workbook = new Workbook(inputPath);

            // Configure HTML save options (default is HTML5 in recent versions)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            // If needed, other options can be set here, e.g., htmlOptions.ExportImagesAsBase64 = true;

            // Save the workbook as HTML
            workbook.Save(outputPath, htmlOptions);
            Console.WriteLine($"Workbook successfully saved to {outputPath}");
        }
        catch (Exception ex)
        {
            // Handle any runtime errors gracefully
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
