// Title: Export an Excel workbook to HTML with Aspose.Cells for .NET and reference an external CSS stylesheet instead of embedded styles
// AI Prompts: Write C# code that saves a Workbook as HTML using Aspose.Cells, disables embedded CSS, and inserts a <link rel="stylesheet" href="styles.css"> tag into the <head> of the generated file. | Show how to modify the HTML output from Aspose.Cells after saving, so the page links to a custom stylesheet rather than using the default inline style definitions.
// Common Searches: Aspose.Cells .NET export Excel to HTML without inline CSS and link external stylesheet | How to add a custom CSS file to HTML generated by Aspose.Cells in C# | Disable embedded style definitions when saving a workbook as HTML using Aspose.Cells | Insert <link> tag into Aspose.Cells HTML output programmatically | C# Aspose.Cells HtmlSaveOptions external CSS linking example
// Tags: Aspose.Cells HTML export external CSS | C# Aspose.Cells disable embedded styles | HtmlSaveOptions link external stylesheet | programmatic insertion of link tag in generated HTML | custom styling Excel to HTML conversion .NET

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook, populates it with data, saves it as HTML using Aspose.Cells HtmlSaveOptions, then reads the generated file, injects a <link rel="stylesheet" href="styles.css"> tag right after the <head> element (or at the top if <head> is missing), and writes the modified HTML back, allowing custom CSS styling instead of the default embedded styles.
class HtmlExportWithExternalCss
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Populate the workbook with sample data (optional)
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Header");
            sheet.Cells["A2"].PutValue("Row 1");
            sheet.Cells["A3"].PutValue("Row 2");

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                // Export images as embedded Base64 strings (optional)
                ExportImagesAsBase64 = true,
                // Export only the active worksheet (optional)
                ExportActiveWorksheetOnly = true
            };

            // Define the output HTML file path
            string htmlPath = "ExportedReport.html";

            // Save the workbook as HTML using the configured options
            workbook.Save(htmlPath, htmlOptions);

            // Ensure the HTML file was created before attempting to modify it
            if (!File.Exists(htmlPath))
                throw new FileNotFoundException("The HTML file was not generated.", htmlPath);

            // Define the external CSS link (relative or absolute URL)
            string externalCssLink = "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\" />";

            // Read the generated HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // Insert the external CSS link right after the <head> tag
            const string headTag = "<head>";
            int headIndex = htmlContent.IndexOf(headTag, StringComparison.OrdinalIgnoreCase);
            if (headIndex != -1)
            {
                int insertPos = headIndex + headTag.Length;
                string insertion = Environment.NewLine + "    " + externalCssLink + Environment.NewLine;
                htmlContent = htmlContent.Insert(insertPos, insertion);
            }
            else
            {
                // If <head> not found, prepend the link at the beginning of the file
                htmlContent = externalCssLink + Environment.NewLine + htmlContent;
            }

            // Write the modified HTML back to the file
            File.WriteAllText(htmlPath, htmlContent);

            Console.WriteLine("HTML export completed. External stylesheet linked.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
