// Title: How to disable downlevel revealed conditional comments when exporting an Excel workbook to HTML with Aspose.Cells for .NET
// AI Prompts: Provide C# code that disables HtmlSaveOptions.ExportConditionalComments and saves a workbook as HTML using Aspose.Cells. | Describe the configuration steps required to prevent IE conditional comments from appearing in HTML files generated by Aspose.Cells.
// Common Searches: Aspose.Cells C# export workbook to HTML without conditional comments | How to turn off downlevel revealed comments in Aspose.Cells HTML output | HtmlSaveOptions ExportConditionalComments false example | Save Excel as HTML without IE conditional comments using Aspose.Cells .NET
// Tags: Aspose.Cells HTML export conditional comments | disable downlevel revealed comments Aspose.Cells | C# HtmlSaveOptions configuration for HTML output | remove IE conditional comments from generated HTML

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // Load the Excel file, create an HtmlSaveOptions instance, set ExportConditionalComments = false, and then save the workbook as HTML. This configuration suppresses downlevel revealed (IE conditional) comments in the generated HTML output.
    class Program
    {
        static void Main(string[] args)
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.html";

            try
            {
                // Verify that the input file exists to avoid FileNotFoundException
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook from the existing file
                Workbook workbook = new Workbook(inputPath);

                // Configure HTML save options
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
                // If your Aspose.Cells version supports ExportHtml5, you can enable it:
                // htmlOptions.ExportHtml5 = true;

                // Save the workbook as HTML using the configured options
                workbook.Save(outputPath, htmlOptions);
                Console.WriteLine($"Workbook successfully saved as HTML to: {outputPath}");
            }
            catch (Exception ex)
            {
                // Catch any runtime exceptions and display a friendly message
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
