// Title: How to disable downlevel revealed conditional comments when exporting Excel to HTML with Aspose.Cells for .NET
// AI Prompts: Write C# code that uses Aspose.Cells to save a workbook as HTML with the DisableDownlevelRevealedComments option enabled. | Show the steps to configure HtmlSaveOptions to suppress IE conditional comment blocks in the generated HTML. | Provide a minimal example that loads an .xlsx file and exports it to HTML without <![if ...]> tags using Aspose.Cells.
// Common Searches: Aspose.Cells C# export Excel to HTML without downlevel revealed comments | How to turn off <![if]> conditional comments in HTML output from Aspose.Cells | HtmlSaveOptions.DisableDownlevelRevealedComments usage example | Remove IE conditional comment blocks from HTML generated by Aspose.Cells .NET | Saving workbook as HTML with no conditional comments using Aspose.Cells
// Tags: Aspose.Cells HTML export without IE conditional comments | HtmlSaveOptions configuration for clean HTML output | C# turn off downlevel revealed comments in HTML export | Excel to HTML conversion settings Aspose.Cells | remove conditional comment blocks Aspose.Cells HTML

using Aspose.Cells;
using Aspose.Cells.Rendering;

// Loads an Excel workbook, sets HtmlSaveOptions.DisableDownlevelRevealedComments to true, and saves the workbook as an HTML file that omits downlevel revealed conditional comment blocks.
class Program
{
    static void Main()
    {
        // Load the workbook you want to convert to HTML
        Workbook workbook = new Workbook("input.xlsx");

        // Create HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

        // Turn off downlevel revealed comments (e.g., <![if ...]> ... <![endif]>)
        htmlOptions.DisableDownlevelRevealedComments = true;

        // Save the workbook as HTML using the configured options
        workbook.Save("output.html", htmlOptions);
    }
}
