// Title: Disable Downlevel‑Revealed Conditional Comments in HTML Export with Aspose.Cells for .NET
// Description: Shows how to turn off downlevel‑revealed conditional comments when saving an Excel workbook to HTML using Aspose.Cells. The example creates a workbook, adds a comment, sets HtmlSaveOptions.DisableDownlevelRevealedComments to true, and writes the file.
// Keywords: Aspose.Cells | HtmlSaveOptions | DisableDownlevelRevealedComments | C# HTML export | remove conditional comments | Excel to HTML .NET | downlevel revealed comments | IE conditional comments | Aspose.Cells HTML options | C# workbook save
// Common Searches: Aspose.Cells disable downlevel revealed comments | HtmlSaveOptions.DisableDownlevelRevealedComments example | C# save Excel as HTML without conditional comments | remove IE conditional comments from Aspose.Cells HTML output | how to turn off downlevel revealed comments Aspose.Cells
// Developer Intent: Turn off downlevel‑revealed conditional comments in the HTML generated by Aspose.Cells.
// Use Cases: Publish Excel data as clean HTML for modern browsers without legacy IE markup. | Create HTML email templates where downlevel‑revealed comments break rendering. | Generate W3C‑validated HTML reports from spreadsheets. | Integrate Excel‑to‑HTML conversion in web apps that require minimal markup.
// AI Prompts: Write C# code using Aspose.Cells to export a workbook to HTML with DisableDownlevelRevealedComments enabled. | Explain the purpose of HtmlSaveOptions.DisableDownlevelRevealedComments and when it should be used. | Show how to verify that the saved HTML file does not contain downlevel‑revealed conditional comments. | Provide a step‑by‑step guide to configure HtmlSaveOptions for clean HTML output in Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Shows how to turn off downlevel‑revealed conditional comments when saving an Excel workbook to HTML using Aspose.Cells. The example creates a workbook, adds a comment, sets HtmlSaveOptions.DisableDownlevelRevealedComments to true, and writes the file.
    public class DisableDownlevelRevealedCommentsDemo
    {
        public static void Main(string[] args)
        {
            try
            {
                Run();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        public static void Run()
        {
            // Create a new workbook (lifecycle: create)
            Workbook workbook = new Workbook();

            // Add a comment to demonstrate that comments exist
            Worksheet sheet = workbook.Worksheets[0];
            int commentIndex = sheet.Comments.Add("A1");
            Comment comment = sheet.Comments[commentIndex];
            comment.Note = "Sample comment";

            // Configure HTML save options to turn off downlevel‑revealed conditional comments
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                // The default value is false; setting to true disables the downlevel‑revealed comments
                DisableDownlevelRevealedComments = true
            };

            // Save the workbook as HTML using the configured options (lifecycle: save)
            string outputPath = "Output_NoDownlevelComments.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine("Workbook saved with downlevel‑revealed comments disabled.");
        }
    }
}
