// Title: Enable CSS custom properties and assign TableCssId when exporting an Aspose.Cells workbook to HTML using C#
// AI Prompts: Insert code to set HtmlSaveOptions.CustomPropertiesEnabled = true and HtmlSaveOptions.TableCssId = "myTable" before calling workbook.Save. | Demonstrate how to write a CSS file that defines variables and applies them to the table identified by the TableCssId generated by Aspose.Cells. | Provide a full C# snippet that creates a ListObject, enables CSS custom properties, sets a TableCssId, and saves the workbook as an HTML file with flexible styling.
// Common Searches: how to enable css variables in aspocells html export c# | aspocells htmlsaveoptions tablecssid example | c# export workbook to html with custom css properties using aspocells | using css custom properties to style tables generated by aspocells | set table id for html output in aspocells c#
// Tags: html export custom css variables aspocells | tablecssid aspocells htmlsaveoptions | enable css custom properties aspocells c# | listobject html styling aspocells | c# aspocells htmlsaveoptions table styling

using System;
using Aspose.Cells;
using Aspose.Cells.Tables;

// The example creates a workbook, adds sample data and a ListObject, enables CSS custom properties, assigns a TableCssId, and saves the workbook as StyledTable.html, allowing flexible styling of the exported HTML table via CSS variables.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data
            sheet.Cells["A1"].PutValue("Product");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apples");
            sheet.Cells["B2"].PutValue(150);
            sheet.Cells["A3"].PutValue("Oranges");
            sheet.Cells["B3"].PutValue(200);

            // Define table range (zero‑based indices)
            int firstRow = 0;
            int firstColumn = 0;
            int totalRows = 3;      // header + 2 data rows
            int totalColumns = 2;   // Product and Quantity columns

            // Add a ListObject (table) to the worksheet
            int tableIndex = sheet.ListObjects.Add(firstRow, firstColumn, firstRow + totalRows, firstColumn + totalColumns, true);
            ListObject table = sheet.ListObjects[tableIndex];

            // Set a display name for the table (used as an identifier in HTML)
            table.DisplayName = "myTable";

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();

            // Save the workbook as an HTML file
            workbook.Save("StyledTable.html", saveOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
