// Title: C# – Export Excel Gridlines to HTML with Aspose.Cells
// Description: Shows how to preserve worksheet gridlines in the HTML output of a workbook by configuring HtmlSaveOptions.ExportGridLines (and optionally ExportActiveWorksheetOnly) using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# | HTML export | gridlines | ExportGridLines | HtmlSaveOptions | Excel to HTML | worksheet gridlines | Aspose.Cells .NET | save workbook as HTML
// Common Searches: Aspose.Cells enable gridlines in HTML | HtmlSaveOptions ExportGridLines example C# | export Excel worksheet with gridlines to HTML | how to show gridlines in HTML generated by Aspose.Cells | save only active worksheet as HTML Aspose.Cells
// Developer Intent: Generate an HTML file from an Excel workbook that displays the original gridlines.
// Use Cases: Web reports that need the familiar Excel grid layout for readability | Embedding a single worksheet in a web page while keeping cell borders visible | Creating HTML snapshots of spreadsheets where the grid structure must be retained
// AI Prompts: Write C# code with Aspose.Cells to export a workbook to HTML with gridlines enabled. | Explain the impact of ExportGridLines and ExportActiveWorksheetOnly on the HTML output. | Provide a step‑by‑step tutorial for preserving Excel gridlines when converting to HTML using Aspose.Cells.

using System;
using Aspose.Cells;

namespace EnableHtmlGridlinesDemo
{
    // Shows how to preserve worksheet gridlines in the HTML output of a workbook by configuring HtmlSaveOptions.ExportGridLines (and optionally ExportActiveWorksheetOnly) using Aspose.Cells for .NET.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Optional: make sure gridlines are visible in the worksheet
            worksheet.IsGridlinesVisible = true;

            // Add some sample data so the HTML output has content
            worksheet.Cells["A1"].PutValue("Item");
            worksheet.Cells["B1"].PutValue("Quantity");
            worksheet.Cells["A2"].PutValue("Apple");
            worksheet.Cells["B2"].PutValue(10);
            worksheet.Cells["A3"].PutValue("Orange");
            worksheet.Cells["B3"].PutValue(15);

            // Create HTML save options and enable gridlines export
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportGridLines = true,               // Enable gridlines in the HTML output
                ExportActiveWorksheetOnly = true      // Export only the active worksheet (optional)
            };

            // Save the workbook as HTML with gridlines enabled
            workbook.Save("OutputWithGridlines.html", htmlOptions);

            Console.WriteLine("HTML file saved with gridlines enabled.");
        }
    }
}
