// Title: Enable IE‑compatible worksheet tab switching when saving to MHTML with Aspose.Cells for .NET
// Description: Demonstrates how to set HtmlSaveOptions.IsIECompatible to true before exporting a workbook to MHTML, allowing users to navigate between worksheet tabs in Internet Explorer using C#.
// Keywords: Aspose.Cells | HtmlSaveOptions.IsIECompatible | MHTML export | Internet Explorer compatibility | worksheet tab navigation | C# Excel to MHTML | legacy browser support | Aspose.Cells .NET
// Common Searches: Aspose.Cells enable IE compatibility for MHTML | HtmlSaveOptions IsIECompatible example C# | MHTML worksheet tabs not switching in IE | Save Excel as MHTML with tab support | How to make MHTML files work in Internet Explorer
// Developer Intent: Configure HtmlSaveOptions.IsIECompatible = true so that an MHTML file generated by Aspose.Cells preserves clickable worksheet tabs in Internet Explorer.
// Use Cases: Create intranet reports in MHTML that retain sheet navigation for users on legacy IE browsers. | Automate batch conversion of Excel workbooks to IE‑compatible MHTML files for corporate portals. | Provide a web‑friendly export of multi‑sheet data where end‑users can switch tabs without leaving the page.
// AI Prompts: Show me the C# code to export an Aspose.Cells workbook to MHTML with worksheet tabs enabled in Internet Explorer. | Explain the impact of HtmlSaveOptions.IsIECompatible on MHTML output and how to verify tab switching in IE. | Give a step‑by‑step guide to test IE compatibility of MHTML files generated by Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsMhtmlExample
{
    // Demonstrates how to set HtmlSaveOptions.IsIECompatible to true before exporting a workbook to MHTML, allowing users to navigate between worksheet tabs in Internet Explorer using C#.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook (or load an existing one)
                Workbook workbook = new Workbook();

                // Add some sample data to demonstrate worksheet tab switching
                Worksheet sheet1 = workbook.Worksheets[0];
                sheet1.Name = "Sheet1";
                sheet1.Cells["A1"].PutValue("First sheet");

                // Add a second worksheet and set its name
                Worksheet sheet2 = workbook.Worksheets.Add("Sheet2");
                sheet2.Cells["A1"].PutValue("Second sheet");

                // Create HTML save options for MHTML format
                HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.MHtml)
                {
                    // Enable IE compatibility to allow worksheet tab switching in Internet Explorer
                    IsIECompatible = true
                };

                // Save the workbook as MHTML using the options
                workbook.Save("WorkbookWithTabs.mht", saveOptions);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
