// Title: Enable CSS Custom Properties and TableCssId in Aspose.Cells HTML Export (C#)
// Description: Demonstrates how to set HtmlSaveOptions.EnableCssCustomProperties to true and assign a TableCssId for an Aspose.Cells workbook. The example creates a simple product sheet, applies header styling, saves two HTML files—one with CSS custom properties enabled and one without—to illustrate styling flexibility and fallback support.
// Keywords: Aspose.Cells HtmlSaveOptions | EnableCssCustomProperties | TableCssId | C# HTML export | custom CSS variables | Excel to HTML styling | Aspose.Cells CSS customization | HTML table ID | save workbook as HTML | compare HTML outputs
// Common Searches: how to enable CSS custom properties in Aspose.Cells HTML export | Aspose.Cells TableCssId usage example | C# export Excel to HTML with custom CSS variables | Aspose.Cells HTML output with and without custom properties | apply custom ID to HTML table generated by Aspose.Cells
// Developer Intent: Generate HTML from a workbook with CSS custom properties activated and a specific table identifier, allowing downstream CSS to style the table precisely.
// Use Cases: Create theme‑able HTML reports where CSS variables control colors, fonts, and spacing. | Provide a modern HTML version with CSS custom properties and a legacy fallback for older browsers. | Embed the exported table into an existing web page by targeting the TableCssId with custom stylesheet rules.
// AI Prompts: Write C# code that exports an Aspose.Cells workbook to HTML with EnableCssCustomProperties=true and TableCssId='my-table'. | Show how to add extra CSS rules via the CssStyles property while keeping CSS custom properties enabled. | Explain how to toggle EnableCssCustomProperties at runtime and compare the resulting HTML files to see the impact on CSS variable usage.

using System;
using System.Drawing;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Demonstrates how to set HtmlSaveOptions.EnableCssCustomProperties to true and assign a TableCssId for an Aspose.Cells workbook. The example creates a simple product sheet, applies header styling, saves two HTML files—one with CSS custom properties enabled and one without—to illustrate styling flexibility and fallback support.
    public class HtmlSaveOptionsEnableCssCustomPropertiesDemo
    {
        public static void Main(string[] args)
        {
            try
            {
                Run();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }

        public static void Run()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add sample data with some formatting
            worksheet.Cells["A1"].PutValue("Product");
            worksheet.Cells["B1"].PutValue("Price");
            worksheet.Cells["A2"].PutValue("Apple");
            worksheet.Cells["B2"].PutValue(1.25);
            worksheet.Cells["A3"].PutValue("Banana");
            worksheet.Cells["B3"].PutValue(0.80);

            // Apply bold style to header row
            Style headerStyle = workbook.CreateStyle();
            headerStyle.Font.IsBold = true;
            headerStyle.Font.Color = Color.Blue;
            worksheet.Cells["A1:B1"].SetStyle(headerStyle);

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                EnableCssCustomProperties = true,
                TableCssId = "custom-table"
                // Uncomment to save as a single file with custom CSS
                // SaveAsSingleFile = true,
                // CssStyles = "table.custom-table { border: 1px solid #ccc; }"
            };

            // Save the workbook as HTML with CSS custom properties enabled
            string outputPath = "HtmlWithCssCustomProperties.html";
            workbook.Save(outputPath, htmlOptions);

            // Save again with CSS custom properties disabled for comparison
            htmlOptions.EnableCssCustomProperties = false;
            string outputPathWithout = "HtmlWithoutCssCustomProperties.html";
            workbook.Save(outputPathWithout, htmlOptions);

            Console.WriteLine($"HTML saved with CSS custom properties: {outputPath}");
            Console.WriteLine($"HTML saved without CSS custom properties: {outputPathWithout}");
        }
    }
}
