// Title: Set HtmlLinkTargetType.Blank in Aspose.Cells C# to make exported HTML hyperlinks open in a new tab
// Description: This C# example creates a workbook, adds a hyperlink to cell A1, configures HtmlSaveOptions.LinkTargetType to HtmlLinkTargetType.Blank, and saves the file as HTML. All hyperlinks in the generated HTML open in a new browser tab (target="_blank").
// Keywords: Aspose.Cells | HtmlSaveOptions | HtmlLinkTargetType | Blank | C# | hyperlink target | export to HTML | open link in new tab | target=_blank | Excel to HTML | Aspose.Cells example
// Common Searches: Aspose.Cells set hyperlink target blank | C# export Excel to HTML with target=_blank | HtmlSaveOptions LinkTargetType usage | Make all links open in new tab Aspose.Cells | How to use HtmlLinkTargetType.Blank
// Developer Intent: Configure Aspose.Cells HTML export so that every hyperlink opens in a new browser tab.
// Use Cases: Publish a financial dashboard as HTML where external references should not navigate away from the report page. | Create a web‑ready version of an Excel‑based product catalog with target="_blank" on all links for seamless user navigation. | Generate interactive documentation from spreadsheets, ensuring linked resources open in separate tabs to preserve context.
// AI Prompts: Show how to set HtmlSaveOptions.LinkTargetType to Blank in Aspose.Cells C# so all hyperlinks open in a new tab. | Provide a C# code snippet that adds a hyperlink to a cell and saves the workbook as HTML with target='_blank' using Aspose.Cells. | Explain the impact of HtmlLinkTargetType on hyperlink behavior in HTML output generated by Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsHyperlinkTargetDemo
{
    // This C# example creates a workbook, adds a hyperlink to cell A1, configures HtmlSaveOptions.LinkTargetType to HtmlLinkTargetType.Blank, and saves the file as HTML. All hyperlinks in the generated HTML open in a new browser tab (target="_blank").
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Put some display text into a cell
            sheet.Cells["A1"].PutValue("Visit Aspose");

            // Add a hyperlink to the cell (A1)
            // Parameters: firstRow, firstColumn, totalRows, totalColumns, hyperlink address
            sheet.Hyperlinks.Add(0, 0, 1, 1, "https://www.aspose.com");

            // Create HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();

            // Set the link target type so that all hyperlinks open in a new tab/window
            saveOptions.LinkTargetType = HtmlLinkTargetType.Blank;

            // Save the workbook as an HTML file using the configured options
            workbook.Save("HyperlinkTargetBlank.html", saveOptions);
        }
    }
}
