// Title: Preserve Conditional Formatting Colors When Exporting to HTML with Aspose.Cells for .NET
// Description: Demonstrates how to keep background colors defined by conditional formatting in the HTML output of a workbook. The example creates sample data, adds two cell‑value rules (greater than 5 → light green, ≤ 5 → light coral), sets HtmlSaveOptions to retain all styles, and saves the file as HTML, ensuring the visual cues remain visible in browsers.
// Keywords: Aspose.Cells HTML export conditional formatting | retain conditional formatting colors .NET | HtmlSaveOptions ExportConditionalFormatting true | exclude unused styles false Aspose.Cells | C# preserve cell background in HTML | Aspose.Cells conditional formatting CSS | export spreadsheet to HTML with colors
// Common Searches: How to keep conditional formatting colors when saving workbook as HTML using Aspose.Cells | Aspose.Cells ExportConditionalFormatting property not showing colors | HTML output missing conditional formatting background Aspose.Cells | Save Excel to HTML with color highlights in .NET | Why are conditional formatting styles excluded in HTML export
// Developer Intent: Ensure that conditional formatting background colors are retained in the HTML file generated by Aspose.Cells.
// Use Cases: Publish a financial dashboard with traffic‑light indicators to a web page while preserving the color cues. | Create an HTML preview of a data‑analysis workbook where threshold‑based highlights must be visible to end users. | Generate an HTML email attachment from a spreadsheet that keeps conditional formatting for clearer communication.
// AI Prompts: Show C# code that sets HtmlSaveOptions.ExportConditionalFormatting = true and keeps conditional formatting colors in the saved HTML. | Explain why HtmlSaveOptions.ExcludeUnusedStyles must be false to retain conditional formatting background colors. | Provide a script to validate that the exported HTML contains CSS rules for the conditional formatting applied to cells.

using System;
using System.Drawing;
using Aspose.Cells;

// Demonstrates how to keep background colors defined by conditional formatting in the HTML output of a workbook. The example creates sample data, adds two cell‑value rules (greater than 5 → light green, ≤ 5 → light coral), sets HtmlSaveOptions to retain all styles, and saves the file as HTML, ensuring the visual cues remain visible in browsers.
class ConditionalFormattingHtmlExport
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Populate sample data in column A (A1:A10)
            for (int i = 0; i < 10; i++)
            {
                worksheet.Cells[i, 0].PutValue(i);
            }

            // Add conditional formatting to the range A1:A10
            int cfIndex = worksheet.ConditionalFormattings.Add();
            FormatConditionCollection cfCollection = worksheet.ConditionalFormattings[cfIndex];

            // Define the range for the conditional formatting
            CellArea area = new CellArea
            {
                StartRow = 0,
                EndRow = 9,
                StartColumn = 0,
                EndColumn = 0
            };
            cfCollection.AddArea(area);

            // Condition 1: values greater than 5 -> light green background
            int condition1 = cfCollection.AddCondition(FormatConditionType.CellValue, OperatorType.GreaterThan, "5", null);
            FormatCondition fc1 = cfCollection[condition1];
            fc1.Style.BackgroundColor = Color.LightGreen;

            // Condition 2: values less than or equal to 5 -> light coral background
            int condition2 = cfCollection.AddCondition(FormatConditionType.CellValue, OperatorType.LessOrEqual, "5", null);
            FormatCondition fc2 = cfCollection[condition2];
            fc2.Style.BackgroundColor = Color.LightCoral;

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                // Keep all styles (do not exclude unused ones) to ensure conditional styles are present
                ExcludeUnusedStyles = false
            };

            // Save the workbook as HTML
            workbook.Save("ConditionalFormatting.html", htmlOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
