// Title: Export Excel workbook to HTML with em‑based column sizing (WidthScalable) using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an .xlsx file and saves it as HTML with the WidthScalable property enabled using Aspose.Cells. | Show how to configure HtmlSaveOptions so that the generated HTML defines column widths in em units with Aspose.Cells for .NET. | Provide an example that exports a workbook to a specific folder while keeping column width scaling active in the HTML output.
// Common Searches: Aspose.Cells enable em based column width scaling when converting Excel to HTML | C# HtmlSaveOptions set column widths in em units for HTML output | Export .xlsx to .html preserving column width scaling with Aspose.Cells .NET | How to keep column width proportions in HTML generated by Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions scalable columns | C# Excel to HTML conversion with em sizing | HTML column width scaling Aspose.Cells | scalable column width setting Aspose.Cells | Export workbook to HTML .NET Aspose.Cells

using System;
using Aspose.Cells;

// // Loads an existing Excel file, enables em‑based column sizing by setting HtmlSaveOptions.WidthScalable to true, and saves the workbook as an HTML document.
class Program
{
    static void Main()
    {
        // Load an existing workbook (replace with your actual file path)
        Workbook workbook = new Workbook("input.xlsx");

        // Set HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

        // Enable em‑based column sizing by making the width scalable
        htmlOptions.WidthScalable = true;

        // Export the workbook to HTML
        workbook.Save("output.html", htmlOptions);
    }
}
