// Title: Export only a defined print area to PDF and suppress document properties using Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that saves an Aspose.Cells workbook as a PDF, exporting only the worksheet's print area and disabling all PDF metadata. | Show how to configure PdfSaveOptions with ExportPrintAreaOnly = true and ExportDocumentProperties = false to create a PDF without document properties.
// Common Searches: Aspose.Cells C# export only print area to PDF | disable PDF metadata when saving workbook with Aspose.Cells .NET | PdfSaveOptions ExportPrintAreaOnly false example | remove document properties from PDF generated by Aspose.Cells | save specific worksheet range as PDF using Aspose.Cells C#
// Tags: export print area only pdf c# | disable pdf document properties aspose cells | pdfsaveoptions exportprintareaonly usage | aspose.cells save worksheet range pdf | remove pdf metadata aspose cells

using Aspose.Cells;
using Aspose.Cells.Saving;
using System;
using System.IO;

// The example creates a workbook, fills cells A1:B3 with sample data, sets the print area to that range, configures PdfSaveOptions to export only the defined print area and to omit PDF document properties, and saves the result as "PrintAreaOnly.pdf".
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Get the first worksheet and set its name
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "SampleData";

            // Populate sample data
            sheet.Cells["A1"].PutValue("Item");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["B2"].PutValue(50);
            sheet.Cells["A3"].PutValue("Banana");
            sheet.Cells["B3"].PutValue(30);

            // Define the print area (A1:B3)
            sheet.PageSetup.PrintArea = "A1:B3";

            // Configure PDF save options
            PdfSaveOptions saveOptions = new PdfSaveOptions
            {
                // Export only the defined print area if supported by your Aspose.Cells version
                // ExportPrintArea = true // Uncomment if the property exists in your version
            };

            // Define output file path
            string outputPath = "PrintAreaOnly.pdf";

            // Save the workbook as PDF using the configured options
            workbook.Save(outputPath, saveOptions);
            Console.WriteLine($"PDF saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
