// Title: Export an Excel workbook to HTML without worksheet properties using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file, sets HtmlSaveOptions.ExportWorksheetProperties to false, and saves it as an .html file with Aspose.Cells. | Show how to configure Aspose.Cells HtmlSaveOptions to omit worksheet properties when converting a workbook to HTML in a .NET application.
// Common Searches: Aspose.Cells .NET export workbook to HTML without sheet properties | disable worksheet properties in HTML output using Aspose.Cells | HtmlSaveOptions ExportWorksheetProperties false example C# | convert Excel file to HTML while hiding worksheet metadata Aspose.Cells | how to remove sheet properties from HTML generated by Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions ExportWorksheetProperties false | export Excel workbook to HTML Aspose.Cells | omit worksheet properties in HTML conversion .NET | C# Aspose.Cells HTML export settings | disable sheet metadata in HTML output Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Rendering;

// Loads an Excel workbook, configures HtmlSaveOptions to set ExportWorksheetProperties to false, and saves the workbook as an HTML file, omitting worksheet property metadata.
class Program
{
    static void Main()
    {
        // Load the workbook from a file (replace with your source file path)
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
        // Omit worksheet properties in the generated HTML
        htmlOptions.ExportWorksheetProperties = false;

        // Save the workbook as HTML using the configured options
        workbook.Save("output.html", htmlOptions);
    }
}
