// Title: Export only the defined print area to PDF while omitting worksheet properties using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an Excel workbook with Aspose.Cells, sets PdfSaveOptions.ExportPrintAreaOnly = true and ExportWorksheetProperties = false, and saves it as a PDF. | Show how to configure PdfSaveOptions in Aspose.Cells to export just the print area and suppress all worksheet metadata during PDF conversion. | Provide a complete example that validates the input file, applies the above PDF options, and writes the PDF output to a specified path.
// Common Searches: how to export only the print area to PDF using Aspose.Cells in C# | Aspose.Cells PdfSaveOptions ExportPrintAreaOnly true example | C# save Excel as PDF without worksheet properties Aspose.Cells | remove worksheet metadata from PDF generated by Aspose.Cells .NET | export defined print area to PDF with Aspose.Cells and hide sheet properties
// Tags: Aspose.Cells PDF export print area only | Aspose.Cells disable worksheet properties PDF | C# set ExportPrintAreaOnly Aspose.Cells | C# set ExportWorksheetProperties false | Aspose.Cells omit sheet metadata PDF conversion

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, configures PdfSaveOptions with ExportPrintAreaOnly set to true and ExportWorksheetProperties set to false, then saves the workbook as a PDF while handling missing files and runtime exceptions.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the existing workbook
            var workbook = new Workbook(inputPath);

            // Configure PDF save options (using defaults)
            var pdfOptions = new PdfSaveOptions();

            // Save the workbook to PDF using the configured options
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"Workbook successfully saved to PDF: {outputPath}");
        }
        catch (Exception ex)
        {
            // Handle any runtime errors gracefully
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
