// Title: Export Excel to HTML with Click‑to‑Sort Columns using Aspose.Cells (C#)
// Description: Loads an Excel workbook, saves it as HTML with HtmlSaveOptions (formulas, active sheet, JS compatibility), injects a custom JavaScript block that adds click‑to‑sort handlers to table headers, and writes the enhanced HTML file. The script is inserted before </head> or </body> to ensure proper placement.
// Keywords: Aspose.Cells HTML export | C# Excel to HTML | embed JavaScript in Aspose.Cells output | sortable HTML table from Excel | click to sort columns | HtmlSaveOptions ExportFormula | active worksheet only | memory stream HTML generation
// Common Searches: Aspose.Cells export Excel to HTML with JavaScript | C# add sortable columns to HTML generated by Aspose.Cells | how to inject script into Aspose.Cells HTML output | export only active worksheet to HTML using Aspose.Cells | interactive Excel HTML report C#
// Developer Intent: Create an HTML file from an Excel workbook and embed a JavaScript routine that enables column sorting when users click table headers.
// Use Cases: Web dashboards that need a lightweight, sortable view of Excel data without server‑side processing. | Self‑service reports where end‑users can reorder columns directly in the browser after export. | Embedding Excel‑derived tables into portals or intranets with client‑side interactivity.
// AI Prompts: Generate C# code that uses Aspose.Cells to export a workbook to HTML and inject a script for click‑to‑sort table columns. | Show how to locate the </head> tag in the generated HTML string and insert a <script> block, falling back to </body> if the head tag is missing. | Explain which HtmlSaveOptions properties enable formula export, active‑worksheet‑only output, and JavaScript compatibility.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

// Loads an Excel workbook, saves it as HTML with HtmlSaveOptions (formulas, active sheet, JS compatibility), injects a custom JavaScript block that adds click‑to‑sort handlers to table headers, and writes the enhanced HTML file. The script is inserted before </head> or </body> to ensure proper placement.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.html";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
                throw new FileNotFoundException($"The input file '{inputPath}' was not found.");

            // Load the workbook from the specified file
            Workbook workbook = new Workbook(inputPath);

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportFormula = true,               // Export formulas as they appear in Excel
                IsJsBrowserCompatible = true,       // Keep JavaScript compatibility flag
                ExportActiveWorksheetOnly = true    // Export only the active sheet (optional)
            };

            // Save the workbook to a memory stream as HTML
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, htmlOptions);
                htmlStream.Position = 0;
                string htmlContent = new StreamReader(htmlStream, Encoding.UTF8).ReadToEnd();

                // Custom JavaScript that enables column sorting when a header cell is clicked
                string sortingScript = @"
<script type='text/javascript'>
function sortTable(tableId, colIndex) {
    var table = document.getElementById(tableId);
    var rows = Array.prototype.slice.call(table.tBodies[0].rows, 0);
    var asc = table.getAttribute('data-sort-dir') !== 'asc';
    rows.sort(function(a, b) {
        var aText = a.cells[colIndex].innerText.trim();
        var bText = b.cells[colIndex].innerText.trim();
        return asc ? aText.localeCompare(bText) : bText.localeCompare(aText);
    });
    for (var i = 0; i < rows.length; i++) {
        table.tBodies[0].appendChild(rows[i]);
    }
    table.setAttribute('data-sort-dir', asc ? 'asc' : 'desc');
}
function addSortHandlers() {
    var tables = document.getElementsByTagName('table');
    for (var t = 0; t < tables.length; t++) {
        var ths = tables[t].getElementsByTagName('th');
        for (var i = 0; i < ths.length; i++) {
            (function(index){
                ths[index].onclick = function(){ sortTable(tables[t].id, index); };
                ths[index].style.cursor = 'pointer';
            })(i);
        }
    }
}
window.onload = addSortHandlers;
</script>";

                // Insert the script just before the closing </head> tag; if not found, use </body>
                string insertTag = "</head>";
                int insertPos = htmlContent.IndexOf(insertTag, StringComparison.OrdinalIgnoreCase);
                if (insertPos >= 0)
                {
                    htmlContent = htmlContent.Insert(insertPos, sortingScript);
                }
                else
                {
                    insertTag = "</body>";
                    insertPos = htmlContent.IndexOf(insertTag, StringComparison.OrdinalIgnoreCase);
                    if (insertPos >= 0)
                    {
                        htmlContent = htmlContent.Insert(insertPos, sortingScript);
                    }
                }

                // Write the final HTML with embedded JavaScript to a file
                File.WriteAllText(outputPath, htmlContent, Encoding.UTF8);
            }

            Console.WriteLine($"HTML file with interactive column sorting has been generated: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
