// Title: Export Active Worksheet to HTML with Custom TableCssId using Aspose.Cells for .NET
// Description: Demonstrates how to save only the active worksheet of a workbook as HTML with Aspose.Cells, applying a custom TableCssId to the generated tables for external CSS styling.
// Keywords: Aspose.Cells | .NET | C# | HtmlSaveOptions | ExportActiveWorksheetOnly | TableCssId | HTML export | custom CSS id | active worksheet | web report
// Common Searches: Aspose.Cells export active sheet to HTML | HtmlSaveOptions TableCssId example | Export only active worksheet Aspose.Cells .NET | Set custom CSS id for HTML tables Aspose.Cells | How to style Aspose.Cells HTML output with CSS
// Developer Intent: Generate an HTML file that contains only the workbook's active worksheet and assign a specific TableCssId to its tables for styling.
// Use Cases: Create a lightweight HTML report that includes just the active sheet, enabling fast page loads. | Apply a predefined CSS selector to all exported tables for consistent branding across reports. | Automate server‑side conversion of Excel workbooks to HTML where only the active sheet is needed and styling is controlled via external CSS.
// AI Prompts: Show me C# code to export only the active worksheet to HTML with a custom TableCssId using Aspose.Cells. | How does TableCssId affect the HTML generated by Aspose.Cells and how can I reference it in my stylesheet? | Provide a step‑by‑step guide to configure HtmlSaveOptions for active‑sheet‑only export and custom table CSS IDs.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Demonstrates how to save only the active worksheet of a workbook as HTML with Aspose.Cells, applying a custom TableCssId to the generated tables for external CSS styling.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Add sample data to the first (active) worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "ActiveSheet";
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("Alice");
            sheet.Cells["B3"].PutValue(25);

            // Ensure the first worksheet is the active one
            workbook.Worksheets.ActiveSheetIndex = 0;

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();
            // Export only the active worksheet
            saveOptions.ExportActiveWorksheetOnly = true;
            // Apply a custom TableCssId to style the generated tables
            saveOptions.TableCssId = "custom-table-style";

            // Save the workbook as HTML using the configured options
            workbook.Save("active_sheet_with_custom_table_css.html", saveOptions);
        }
    }
}
