// Title: Export Aspose.Cells Workbook with 3‑Color Scale Conditional Formatting to HTML and Capture CSS Linear‑Gradient Rules (C#)
// Description: Demonstrates how to create a workbook, apply a three‑color scale (green‑yellow‑red) to cells A1:J10, save the file as HTML with a separate CSS stylesheet, and programmatically extract the generated linear‑gradient definitions for reuse in web projects.
// Keywords: Aspose.Cells HTML export | C# conditional formatting color scale | CSS gradient extraction | ExportWorksheetCSSSeparately | linear-gradient Aspose.Cells | separate CSS file workbook | Aspose.Cells sample code | GitHub Aspose.Cells example | web styling from Excel | .NET Excel to HTML
// Common Searches: Aspose.Cells export color scale to HTML with separate CSS | How to get linear‑gradient CSS from Aspose.Cells HTML output | C# extract gradient definitions from sheet0.css | Save workbook as HTML and keep conditional formatting styles | Aspose.Cells conditional formatting CSS file location
// Developer Intent: Produce an HTML page and its accompanying CSS file that contain the gradient styles for a 3‑color scale conditional formatting rule, then retrieve those gradient definitions via code.
// Use Cases: Generate a web‑ready view of an Excel workbook while preserving color‑scale visual cues. | Reuse the exact gradient CSS in custom web components or dashboards. | Automate documentation of conditional‑formatting styles for design systems. | Integrate Excel‑based styling into a front‑end framework without manual CSS recreation.
// AI Prompts: Write C# code using Aspose.Cells to apply a three‑color scale to a range, export the workbook as HTML with a separate CSS file, and list all linear‑gradient rules. | Create a method that reads the CSS file generated by Aspose.Cells HTML export and returns an array of gradient strings for each conditional formatting rule. | Explain the impact of ExportWorksheetCSSSeparately on file structure and how to locate the CSS file for a saved workbook.

using System;
using System.IO;
using System.Drawing;
using Aspose.Cells;

// Demonstrates how to create a workbook, apply a three‑color scale (green‑yellow‑red) to cells A1:J10, save the file as HTML with a separate CSS stylesheet, and programmatically extract the generated linear‑gradient definitions for reuse in web projects.
class ColorScaleCssExport
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data (10x10 matrix)
        for (int i = 0; i < 10; i++)
        {
            for (int j = 0; j < 10; j++)
            {
                sheet.Cells[i, j].PutValue(i * j);
            }
        }

        // Add a 3‑color scale conditional formatting (rule)
        int cfIndex = sheet.ConditionalFormattings.Add();
        FormatConditionCollection fcc = sheet.ConditionalFormattings[cfIndex];

        // Define the range A1:J10
        CellArea area = new CellArea { StartRow = 0, EndRow = 9, StartColumn = 0, EndColumn = 9 };
        fcc.AddArea(area);

        // Add the ColorScale condition
        int conditionIdx = fcc.AddCondition(FormatConditionType.ColorScale);
        FormatCondition fc = fcc[conditionIdx];

        // Configure the ColorScale (rule)
        fc.ColorScale.Is3ColorScale = true;
        fc.ColorScale.MinColor = Color.Green;
        fc.ColorScale.MidColor = Color.Yellow;
        fc.ColorScale.MaxColor = Color.Red;

        // Set the value objects for min, mid, max
        fc.ColorScale.MinCfvo.Type = FormatConditionValueType.Min;
        fc.ColorScale.MidCfvo.Type = FormatConditionValueType.Percentile;
        fc.ColorScale.MidCfvo.Value = 50;
        fc.ColorScale.MaxCfvo.Type = FormatConditionValueType.Max;

        // Prepare HTML save options with separate CSS (rule)
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();
        saveOptions.ExportWorksheetCSSSeparately = true;

        // Define output folder and file names
        string outputFolder = Path.Combine(Environment.CurrentDirectory, "HtmlOutput");
        Directory.CreateDirectory(outputFolder);
        string htmlPath = Path.Combine(outputFolder, "ColorScale.html");

        // Save the workbook as HTML
        workbook.Save(htmlPath, saveOptions);

        // The CSS file is generated alongside the HTML file with name "sheet0.css"
        string cssPath = Path.Combine(outputFolder, "sheet0.css");

        // Read the CSS content and extract gradient definitions
        if (File.Exists(cssPath))
        {
            string cssContent = File.ReadAllText(cssPath);
            Console.WriteLine("=== Extracted CSS Gradient Definitions ===");
            foreach (string line in cssContent.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
            {
                if (line.Contains("linear-gradient"))
                {
                    Console.WriteLine(line.Trim());
                }
            }
        }
        else
        {
            Console.WriteLine("CSS file not found: " + cssPath);
        }
    }
}
