// Title: Export the active worksheet to HTML with a custom TableCssId using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an Excel file, configures HtmlSaveOptions to export only the active worksheet, sets a TableCssId, and saves the result as HTML using Aspose.Cells. | Show how to use Aspose.Cells HtmlSaveOptions to limit HTML output to the current sheet and assign a specific CSS ID to all tables in a .NET project.
// Common Searches: how to export only the active sheet to HTML with Aspose.Cells C# | setting TableCssId for HTML tables in Aspose.Cells | example of HtmlSaveOptions.ExportActiveWorksheetOnly in C# | apply custom CSS ID to tables generated by Aspose.Cells HTML export | save selected worksheet as HTML using Aspose.Cells .NET
// Tags: Aspose.Cells HtmlSaveOptions ExportActiveWorksheetOnly | Aspose.Cells TableCssId customization | C# export active worksheet as HTML | custom CSS ID for Aspose.Cells tables | Aspose.Cells .NET HTML save options

using System;
using Aspose.Cells;

// // Load an Excel workbook, configure HtmlSaveOptions to export only the active worksheet and assign a custom TableCssId for HTML tables, then save the output as an HTML file.
class ExportActiveWorksheetToHtml
{
    static void Main()
    {
        // Load the workbook from a file (replace with your actual file path)
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options
        HtmlSaveOptions saveOptions = new HtmlSaveOptions
        {
            // Export only the active worksheet (the one currently selected in the workbook)
            ExportActiveWorksheetOnly = true,

            // Assign a specific CSS ID to all tables generated in the HTML
            TableCssId = "MyCustomTableId"
        };

        // Save the active worksheet as an HTML file using the configured options
        workbook.Save("output.html", saveOptions);
    }
}
