// Title: Export Excel Workbook to HTML with Sheet Navigation Tabs using Aspose.Cells (C#)
// Description: Creates a three‑sheet workbook, fills each sheet with sample data, configures HtmlSaveOptions (ExportActiveWorksheetOnly = false, CreateDirectory = true, AttachedFilesDirectory = "HtmlOutput"), and saves the file as HTML. Aspose.Cells generates a main HTML page, separate pages for every worksheet, and a tabstrip.html that provides clickable tabs to switch between sheets.
// Keywords: Aspose.Cells HTML export | C# export Excel to HTML | HTML navigation tabs for worksheets | HtmlSaveOptions tabstrip | multiple worksheets to HTML | attached files directory Aspose.Cells
// Common Searches: Aspose.Cells export Excel to HTML with tabs | How to get a navigation pane when saving workbook as HTML in .NET | Create separate HTML files per sheet using Aspose.Cells | Save Excel workbook to HTML with attached images folder C# | Enable tabstrip navigation for multi‑sheet HTML output Aspose.Cells
// Developer Intent: Produce an HTML version of an Excel workbook that includes clickable tabs for each worksheet.
// Use Cases: Publish a multi‑sheet report on a website where users can switch views via generated tabs. | Distribute an offline HTML copy of a workbook for email or documentation without requiring Excel. | Integrate the HTML files and their assets into a web portal for interactive data browsing.
// AI Prompts: Show how to style the tabstrip navigation generated by Aspose.Cells when exporting to HTML. | Generate C# code that injects custom CSS or JavaScript into the HTML files after saving. | Explain how to embed the exported HTML pages and image folder into an ASP.NET MVC view.

using System;
using Aspose.Cells;

namespace ExportExcelToHtmlWithNavigation
{
    // Creates a three‑sheet workbook, fills each sheet with sample data, configures HtmlSaveOptions (ExportActiveWorksheetOnly = false, CreateDirectory = true, AttachedFilesDirectory = "HtmlOutput"), and saves the file as HTML. Aspose.Cells generates a main HTML page, separate pages for every worksheet, and a tabstrip.html that provides clickable tabs to switch between sheets.
    class Program
    {
        static void Main()
        {
            // Create a new workbook with three worksheets
            Workbook workbook = new Workbook();
            workbook.Worksheets.Add("Sales");
            workbook.Worksheets.Add("Summary");

            // Fill data in the first sheet
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Cells["A1"].PutValue("Employee");
            sheet1.Cells["B1"].PutValue("Hours");
            sheet1.Cells["A2"].PutValue("John");
            sheet1.Cells["B2"].PutValue(40);
            sheet1.Cells["A3"].PutValue("Anna");
            sheet1.Cells["B3"].PutValue(35);

            // Fill data in the second sheet
            Worksheet sheet2 = workbook.Worksheets[1];
            sheet2.Cells["A1"].PutValue("Region");
            sheet2.Cells["B1"].PutValue("Sales");
            sheet2.Cells["A2"].PutValue("North");
            sheet2.Cells["B2"].PutValue(12000);
            sheet2.Cells["A3"].PutValue("South");
            sheet2.Cells["B3"].PutValue(15000);

            // Fill data in the third sheet
            Worksheet sheet3 = workbook.Worksheets[2];
            sheet3.Cells["A1"].PutValue("Summary");
            sheet3.Cells["A2"].PutValue("Total Employees");
            sheet3.Cells["B2"].PutValue(2);
            sheet3.Cells["A3"].PutValue("Total Sales");
            sheet3.Cells["B3"].PutValue(27000);

            // Configure HTML save options.
            // ExportActiveWorksheetOnly = false (default) ensures all sheets are exported.
            // CreateDirectory = true automatically creates the output folder if it does not exist.
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                ExportActiveWorksheetOnly = false,
                CreateDirectory = true,
                // The folder where auxiliary files (e.g., images) will be placed.
                AttachedFilesDirectory = "HtmlOutput"
            };

            // Save the workbook as HTML.
            // Aspose.Cells generates a main HTML file, separate HTML files for each worksheet,
            // and a tabstrip.html file that provides a navigation pane linking to each sheet.
            workbook.Save("HtmlOutput\\Workbook.html", saveOptions);
        }
    }
}
