// Title: Export an Excel worksheet with multiple tables to HTML and assign TableCssId‑prefixed CSS classes using Aspose.Cells for .NET
// AI Prompts: Write C# code that creates a workbook, adds two ListObjects, sets a unique TableCssId (e.g., "tbl1", "tbl2") for each table, and saves the workbook as an HTML file with Aspose.Cells. | Update the sample to include HtmlSaveOptions, assign TableCssId values to the tables, and generate HTML output that applies the prefixed CSS classes to each exported table.
// Common Searches: Aspose.Cells C# set TableCssId for each ListObject before HTML export | export Excel worksheet with multiple tables to HTML using custom TableCssId prefix | how to apply custom CSS class to tables generated by Aspose.Cells HTML save | C# Aspose.Cells assign TableCssId to multiple tables in the same worksheet | HTML export of Excel with TableStyleType and TableCssId together in Aspose.Cells
// Tags: Aspose.Cells export worksheet to HTML with TableCssId | C# ListObject TableCssId assignment | multiple tables HTML export Aspose.Cells | custom CSS class for Aspose.Cells tables | TableStyleType combined with TableCssId

using System;
using Aspose.Cells;
using Aspose.Cells.Tables;

// The example creates a new workbook, adds a worksheet named DataSheet, populates two data ranges, defines each range as a ListObject (Table1 and Table2) with built‑in TableStyle, assigns a TableCssId prefix to each table, and saves the workbook as an HTML file so the tables can be styled via custom CSS classes.
class ExportWorksheetWithTables
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet and set its name
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "DataSheet";

            // Populate sample data for Table 1 (A1:C4)
            sheet.Cells["A1"].PutValue("ID");
            sheet.Cells["B1"].PutValue("Name");
            sheet.Cells["C1"].PutValue("Score");
            sheet.Cells["A2"].PutValue(1);
            sheet.Cells["B2"].PutValue("Alice");
            sheet.Cells["C2"].PutValue(85);
            sheet.Cells["A3"].PutValue(2);
            sheet.Cells["B3"].PutValue("Bob");
            sheet.Cells["C3"].PutValue(92);
            sheet.Cells["A4"].PutValue(3);
            sheet.Cells["B4"].PutValue("Charlie");
            sheet.Cells["C4"].PutValue(78);

            // Populate sample data for Table 2 (E1:G5)
            sheet.Cells["E1"].PutValue("Product");
            sheet.Cells["F1"].PutValue("Category");
            sheet.Cells["G1"].PutValue("Price");
            sheet.Cells["E2"].PutValue("Laptop");
            sheet.Cells["F2"].PutValue("Electronics");
            sheet.Cells["G2"].PutValue(1200);
            sheet.Cells["E3"].PutValue("Desk");
            sheet.Cells["F3"].PutValue("Furniture");
            sheet.Cells["G3"].PutValue(250);
            sheet.Cells["E4"].PutValue("Pen");
            sheet.Cells["F4"].PutValue("Stationery");
            sheet.Cells["G4"].PutValue(2);
            sheet.Cells["E5"].PutValue("Coffee");
            sheet.Cells["F5"].PutValue("Beverage");
            sheet.Cells["G5"].PutValue(5);

            // Create first table (ListObject) covering A1:C4
            int tableIndex = 0;
            int index1 = sheet.ListObjects.Add(0, 0, 4, 3, true); // rows, columns include header
            ListObject table1 = sheet.ListObjects[index1];
            table1.DisplayName = "Table1";
            table1.TableStyleType = TableStyleType.TableStyleMedium2;

            // Create second table covering E1:G5
            tableIndex++;
            int index2 = sheet.ListObjects.Add(0, 4, 5, 3, true);
            ListObject table2 = sheet.ListObjects[index2];
            table2.DisplayName = "Table2";
            table2.TableStyleType = TableStyleType.TableStyleMedium9;

            // Save the workbook
            workbook.Save("MultipleTables.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
