// Title: Export Excel to HTML with Base64‑embedded images using Aspose.Cells for .NET
// Description: Shows how to build a workbook, add sample data and an optional picture, set HtmlSaveOptions to embed images as Base64 data URIs, and generate a single‑file HTML report.
// Keywords: Aspose.Cells | HTML export | Base64 images | C# Aspose.Cells HtmlSaveOptions | ExportImagesAsBase64 | Excel to HTML conversion | inline images | self‑contained HTML | embed picture in HTML | Aspose.Cells .NET
// Common Searches: Aspose.Cells export Excel to HTML with Base64 images | HtmlSaveOptions ExportImagesAsBase64 C# example | How to embed pictures in HTML generated from Excel | Create single‑file HTML from workbook using Aspose.Cells | C# convert spreadsheet to HTML with inline images
// Developer Intent: Produce an HTML file from an Excel workbook where any inserted images are encoded as Base64 data URIs, eliminating external image dependencies.
// Use Cases: Send a complete HTML report via email without attaching separate image files. | Publish a spreadsheet snapshot on a web page or blog where external hosting is unavailable. | Archive a self‑contained HTML version of a workbook for documentation or compliance purposes.
// AI Prompts: How can I apply a custom CSS stylesheet to the HTML table generated by Aspose.Cells? | Show me how to write the HTML output to a MemoryStream while still embedding images as Base64. | What options let me control the size or compression quality of Base64‑encoded images in HtmlSaveOptions?

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Shows how to build a workbook, add sample data and an optional picture, set HtmlSaveOptions to embed images as Base64 data URIs, and generate a single‑file HTML report.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data
                sheet.Cells["A1"].PutValue("Product");
                sheet.Cells["B1"].PutValue("Price");
                sheet.Cells["A2"].PutValue("Apple");
                sheet.Cells["B2"].PutValue(1.2);
                sheet.Cells["A3"].PutValue("Banana");
                sheet.Cells["B3"].PutValue(0.8);

                // Add an image if the file exists
                string imagePath = "example.jpg";
                if (File.Exists(imagePath))
                {
                    // Add picture at row 5, column 0 (zero‑based)
                    sheet.Pictures.Add(5, 0, imagePath);
                }
                else
                {
                    Console.WriteLine($"Image file '{imagePath}' not found. Skipping picture insertion.");
                }

                // Configure HTML save options to embed images as Base64
                HtmlSaveOptions saveOptions = new HtmlSaveOptions
                {
                    ExportImagesAsBase64 = true
                };

                // Save the workbook as an HTML file with embedded images
                string outputPath = "output.html";
                workbook.Save(outputPath, saveOptions);

                Console.WriteLine($"HTML file '{outputPath}' with embedded Base64 images has been created.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
