// Title: Export an Aspose.Cells workbook to HTML without document or worksheet properties using C#
// AI Prompts: Generate C# code that saves an Aspose.Cells Workbook as an HTML file with HtmlSaveOptions configured to set ExportDocumentProperties and ExportWorksheetProperties to false. | Show how to create and apply HtmlSaveOptions in C# to produce minimal HTML output that excludes Excel metadata when exporting with Aspose.Cells.
// Common Searches: how to export Excel to HTML with Aspose.Cells while removing metadata in C# | Aspose.Cells HtmlSaveOptions hide document properties when saving as HTML | C# save workbook as HTML without worksheet properties using Aspose.Cells | remove Excel metadata from HTML output generated by Aspose.Cells | minimal HTML export of workbook with Aspose.Cells C#
// Tags: Aspose.Cells HTML export omit document properties | Aspose.Cells HtmlSaveOptions ExportWorksheetProperties false | C# save workbook as HTML without metadata | minimal HTML output Aspose.Cells | disable workbook properties in HTML export

using System;
using System.IO;
using Aspose.Cells;

// The program creates a workbook, fills it with sample data, configures HtmlSaveOptions to disable ExportDocumentProperties and ExportWorksheetProperties, and saves the workbook as a clean HTML file.
class ExportWorkbookToHtml
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Add sample data to the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Score");
            sheet.Cells["A2"].PutValue("Alice");
            sheet.Cells["B2"].PutValue(85);
            sheet.Cells["A3"].PutValue("Bob");
            sheet.Cells["B3"].PutValue(92);

            // Configure HTML save options to omit document and worksheet properties
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportDocumentProperties = false,   // Do not include document properties in the HTML
                ExportWorksheetProperties = false   // Do not include worksheet properties in the HTML
            };

            // Define output file path
            string outputPath = "ExportedWorkbook.html";

            // Save the workbook as an HTML file using the configured options
            workbook.Save(outputPath, htmlOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
