// Title: Compare embedded vs external CSS when exporting an Aspose.Cells workbook to HTML using C#
// AI Prompts: Generate C# code that saves a Workbook as HTML with the default embedded CSS, then saves another copy intended for an external stylesheet, and prints the byte size of each generated file. | Adjust the Aspose.Cells HTML export to write a separate CSS file (when supported) and compute the combined size of the HTML and CSS files, outputting which approach yields a smaller total.
// Common Searches: how to export Excel to HTML with embedded CSS using Aspose.Cells C# | Aspose.Cells HTML export external stylesheet size comparison | C# measure file size of HTML and CSS generated by Aspose.Cells | difference between embedded and external CSS in Aspose.Cells HTML output | Aspose.Cells HtmlSaveOptions export CSS to separate file C#
// Tags: Aspose.Cells HTML export with embedded CSS | Aspose.Cells external CSS stylesheet generation | HTML file size comparison Aspose.Cells | HtmlSaveOptions CssStyleSheetType usage | calculate total output size Aspose.Cells HTML

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook, exports it to HTML using the default embedded CSS, attempts an export configured for an external stylesheet (if supported), then reads the generated files and prints their byte sizes to show which method produces a smaller total output.
class Program
{
    static void Main()
    {
        try
        {
            // Create a workbook with sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Sample";
            sheet.Cells["A1"].PutValue("Header1");
            sheet.Cells["B1"].PutValue("Header2");
            sheet.Cells["A2"].PutValue(123);
            sheet.Cells["B2"].PutValue(456);
            sheet.Cells["A3"].PutValue(789);
            sheet.Cells["B3"].PutValue(101112);

            // Define output file paths
            string embeddedHtmlPath = "EmbeddedCss.html";
            string externalHtmlPath = "ExternalCss.html";
            string externalCssPath = "ExternalCss.css";

            // Export workbook to HTML with embedded CSS (default behavior)
            HtmlSaveOptions embeddedOptions = new HtmlSaveOptions(SaveFormat.Html);
            // ExportEmbeddedCss property is not available in this version; default is embedded CSS.
            workbook.Save(embeddedHtmlPath, embeddedOptions);

            // Export workbook to HTML with external CSS (if supported)
            HtmlSaveOptions externalOptions = new HtmlSaveOptions(SaveFormat.Html);
            // The following properties are not available in this version, so we rely on default behavior.
            // externalOptions.ExportEmbeddedCss = false;
            // externalOptions.CssStyleSheetType = CssStyleSheetType.External;
            // externalOptions.CssFileName = Path.GetFileName(externalCssPath);
            workbook.Save(externalHtmlPath, externalOptions);

            // Ensure files exist before accessing size
            long embeddedSize = File.Exists(embeddedHtmlPath) ? new FileInfo(embeddedHtmlPath).Length : 0;
            long externalHtmlSize = File.Exists(externalHtmlPath) ? new FileInfo(externalHtmlPath).Length : 0;
            long externalCssSize = File.Exists(externalCssPath) ? new FileInfo(externalCssPath).Length : 0;
            long totalExternalSize = externalHtmlSize + externalCssSize;

            // Output size comparison
            Console.WriteLine($"Embedded CSS HTML size: {embeddedSize} bytes");
            Console.WriteLine($"External CSS HTML size: {externalHtmlSize} bytes");
            Console.WriteLine($"External CSS file size: {externalCssSize} bytes");
            Console.WriteLine($"Total size (HTML + CSS): {totalExternalSize} bytes");

            // Simple comparison result
            if (embeddedSize < totalExternalSize)
                Console.WriteLine("Embedded CSS approach results in a smaller total size.");
            else if (embeddedSize > totalExternalSize)
                Console.WriteLine("External CSS approach results in a smaller total size.");
            else
                Console.WriteLine("Both approaches have the same total size.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
