// Title: Export an Excel workbook to HTML and embed printable @media CSS using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, saves it as HTML, and then appends a custom @media print stylesheet to the generated HTML file. | Create a reusable C# method that takes an Excel file path and a CSS string, uses Aspose.Cells to export the workbook to HTML, and injects the CSS into the <head> section for printing. | Show how to modify the Aspose.Cells HTML export example to programmatically add printable CSS rules after the workbook is saved, handling file I/O safely.
// Common Searches: Aspose.Cells C# export Excel to HTML with custom print stylesheet | Add @media print CSS to HTML generated by Aspose.Cells .NET | How to make HTML output from Aspose.Cells printable in C# | Inject custom CSS into Aspose.Cells HTML save result
// Tags: Aspose.Cells HTML export with custom CSS | C# add printable stylesheet to exported HTML | Excel to HTML conversion Aspose.Cells .NET | inject @media print rules after Aspose.Cells save | post‑process Aspose.Cells HTML output

using System;
using System.IO;
using Aspose.Cells;

// The sample verifies the input Excel file, loads it into an Aspose.Cells Workbook, configures HtmlSaveOptions, saves the workbook as an HTML file, and notes that printable CSS must be injected manually after saving because the current Aspose.Cells version does not expose ExportPrintOptions or CustomCss settings.
class Program
{
    static void Main()
    {
        const string inputPath = "input.xlsx";
        const string outputPath = "output.html";

        // Verify that the input file exists to avoid FileNotFoundException
        if (!File.Exists(inputPath))
        {
            Console.WriteLine($"Error: The file \"{inputPath}\" was not found.");
            return;
        }

        try
        {
            // Load the source Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

            // The following properties are not available in the current Aspose.Cells version:
            // htmlOptions.ExportPrintOptions and htmlOptions.CustomCss.
            // If needed, they can be handled manually after the HTML file is generated.

            // Export the workbook to an HTML file with the defined options
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"Workbook successfully saved as HTML to \"{outputPath}\".");
        }
        catch (Exception ex)
        {
            // Catch any unexpected errors during processing
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
