// Title: Export an Aspose.Cells workbook to HTML and insert a custom <h1> header with the workbook title in C#
// AI Prompts: Write C# code that uses Aspose.Cells to save a workbook as HTML, then modifies the resulting HTML string to insert a <h1> element containing a specified title after the opening <body> tag. | Show how to read the HTML output from a MemoryStream, detect the <body> tag, and prepend a custom header when the tag is missing, using UTF‑8 encoding. | Demonstrate error handling while exporting to HTML and updating the HTML content with a custom workbook title in a C# console application.
// Common Searches: how to add a custom <h1> title to HTML generated by Aspose.Cells in C# | Aspose.Cells export to HTML and insert additional HTML after body tag | C# modify Aspose.Cells HTML output to include workbook name | insert header into HTML when Aspose.Cells does not generate a body element | using MemoryStream to edit Aspose.Cells HTML export in C#
// Tags: Aspose.Cells HTML export with custom header | C# insert HTML after body tag | modify Aspose.Cells generated HTML | memory stream HTML manipulation Aspose.Cells | handle missing body tag Aspose.Cells HTML

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

// The example creates a workbook, fills sample cells, saves it to HTML via HtmlSaveOptions into a MemoryStream, reads the HTML string, inserts a <h1> element containing a custom workbook title after the <body> tag (or prepends it if the tag is absent), and writes the final HTML to a UTF‑8 file with basic error handling.
class ExportExcelToHtmlWithHeader
{
    static void Main()
    {
        try
        {
            // Title to be inserted into the generated HTML
            string workbookTitle = "My Custom Workbook Title";

            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet and add some sample data
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Data");
            sheet.Cells["A2"].PutValue(123);
            sheet.Cells["A3"].PutValue(DateTime.Now);

            // Prepare HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Save to a memory stream first
            using (MemoryStream ms = new MemoryStream())
            {
                workbook.Save(ms, saveOptions);
                ms.Position = 0;

                // Read the generated HTML
                string htmlContent = new StreamReader(ms, Encoding.UTF8).ReadToEnd();

                // Insert custom header after the opening <body> tag
                string headerHtml = $"<h1>{workbookTitle}</h1>";
                int bodyIndex = htmlContent.IndexOf("<body>", StringComparison.OrdinalIgnoreCase);
                if (bodyIndex >= 0)
                {
                    int insertPos = bodyIndex + "<body>".Length;
                    htmlContent = htmlContent.Insert(insertPos, headerHtml);
                }
                else
                {
                    // If <body> tag not found, prepend the header
                    htmlContent = headerHtml + htmlContent;
                }

                // Write the final HTML to a file
                string outputPath = "ExportedWorkbook.html";
                File.WriteAllText(outputPath, htmlContent, Encoding.UTF8);
                Console.WriteLine($"Workbook exported successfully to '{outputPath}'.");
            }
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
