// Title: Export a workbook with a three‑color scale conditional format to HTML and validate gradient colors using Aspose.Cells for .NET
// AI Prompts: Generate C# code that creates a workbook, fills cells A1:A10, applies a three‑color scale (green‑yellow‑red) conditional formatting, and saves the result as an HTML file with Aspose.Cells. | Add logic to read the generated HTML file and use a regular expression to locate CSS background‑color rules containing RGB values, confirming the gradient is rendered. | Modify the example to set custom percentile values for the midpoint of the color scale and update the verification step to ensure the new gradient appears in the HTML output.
// Common Searches: how to add a color scale conditional formatting in Aspose.Cells and export the sheet to HTML | verify that gradient colors from conditional formatting are preserved in Aspose.Cells HTML export | C# example for saving a workbook with a color gradient conditional format as HTML using Aspose.Cells | regex pattern to detect rgb background-color in HTML generated by Aspose.Cells
// Tags: Aspose.Cells conditional formatting color gradient | export workbook to HTML Aspose.Cells | gradient color verification in HTML | C# regex rgb background-color detection | midpoint value customization color scale Aspose.Cells

using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Drawing;
using Aspose.Cells;

// The sample creates a new workbook, populates cells A1:A10 with numeric values, applies a three‑color scale (green, yellow, red) conditional format to that range, saves the workbook as an HTML file, then reads the HTML and uses a regular expression to confirm that CSS background‑color rules with RGB values are present, proving the gradient colors were rendered correctly.
class ThreeColorScaleExport
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data in column A (A1:A10)
            for (int i = 0; i < 10; i++)
            {
                sheet.Cells[i, 0].PutValue(i + 1); // Values 1..10
            }

            // Define the range for the conditional formatting (A1:A10)
            int firstRow = 0, lastRow = 9, firstCol = 0, lastCol = 0;

            // Add a new conditional formatting collection for the sheet
            int cfIndex = sheet.ConditionalFormattings.Add();
            FormatConditionCollection fcc = sheet.ConditionalFormattings[cfIndex];

            // Add a three‑color scale condition
            fcc.AddCondition(FormatConditionType.ColorScale, OperatorType.None, "", "");

            // Configure the color scale
            ColorScale colorScale = fcc[0].ColorScale;
            colorScale.MinColor = Color.Green;   // Minimum (green)
            colorScale.MidColor = Color.Yellow; // Midpoint (yellow)
            colorScale.MaxColor = Color.Red;    // Maximum (red)

            // The midpoint defaults to the 50th percentile, so no explicit MidValue needed

            // Apply the conditional formatting to the desired range
            fcc.AddArea(new CellArea
            {
                StartRow = firstRow,
                EndRow = lastRow,
                StartColumn = firstCol,
                EndColumn = lastCol
            });

            // Save the workbook as HTML
            string htmlPath = "ThreeColorScale.html";
            workbook.Save(htmlPath, SaveFormat.Html);

            // Verify that gradient colors are represented in the generated HTML
            if (File.Exists(htmlPath))
            {
                string htmlContent = File.ReadAllText(htmlPath);
                bool containsBackgroundColor = Regex.IsMatch(
                    htmlContent,
                    @"background-color\s*:\s*rgb\(\d+,\s*\d+,\s*\d+\)",
                    RegexOptions.IgnoreCase);

                Console.WriteLine("HTML file generated at: " + Path.GetFullPath(htmlPath));
                Console.WriteLine("Gradient colors verification result: " + (containsBackgroundColor ? "PASS" : "FAIL"));
            }
            else
            {
                Console.WriteLine("Failed to generate HTML file.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
