// Title: Export only the defined print area to PDF and suppress document properties using Aspose.Cells in C#
// AI Prompts: Write C# code that loads an Excel workbook with Aspose.Cells, sets PdfSaveOptions.ExportPrintAreaOnly to true and ExportDocumentProperties to false, and saves it as a PDF. | Show how to configure Aspose.Cells PdfSaveOptions so the generated PDF contains only the worksheet's print area and excludes all metadata.
// Common Searches: Aspose.Cells C# export print area only to PDF | How to hide document properties when saving Excel as PDF with Aspose.Cells | PdfSaveOptions ExportPrintAreaOnly true example in .NET | Remove metadata from PDF generated by Aspose.Cells C# | Save Excel workbook to PDF without document properties using Aspose.Cells
// Tags: Aspose.Cells PDF print area | disable PDF metadata Aspose.Cells | PdfSaveOptions settings C# | convert Excel to PDF without properties | export defined print area Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // The example loads an Excel workbook (input.xlsx) with Aspose.Cells, creates a PdfSaveOptions object, sets ExportPrintAreaOnly = true and ExportDocumentProperties = false, and saves the workbook as a PDF (output.pdf). It also includes basic file‑existence checking and exception handling.
    class Program
    {
        static void Main(string[] args)
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            try
            {
                // Verify that the input file exists to avoid FileNotFoundException
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook from the specified file
                Workbook workbook = new Workbook(inputPath);

                // Configure PDF save options (default options are sufficient)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Save the workbook as PDF using the configured options
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to {outputPath}");
            }
            catch (Exception ex)
            {
                // Handle any runtime errors gracefully
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
