// Title: Export Defined Print Area to HTML without Worksheet Properties using Aspose.Cells for .NET (C#)
// Description: Demonstrates how to set a print area, enable ExportPrintAreaOnly, disable ExportWorksheetProperties, and keep grid lines visible with HtmlSaveOptions, then save the workbook as a lightweight HTML file.
// Keywords: Aspose.Cells HTML export | ExportPrintAreaOnly | ExportWorksheetProperties false | C# print area to HTML | Aspose.Cells HtmlSaveOptions | remove worksheet metadata HTML | .NET workbook to HTML | grid lines export Aspose.Cells
// Common Searches: Aspose.Cells export only print area to HTML | HTML export without worksheet properties C# | ExportPrintAreaOnly Aspose.Cells example | disable worksheet metadata in HTML output Aspose | C# save workbook as HTML with grid lines
// Developer Intent: Create an HTML representation that contains only the defined print range and excludes all worksheet‑level metadata.
// Use Cases: Generate a compact HTML preview of a specific range for web dashboards. | Produce printable HTML reports that show only the print area while preserving grid lines. | Share cell snippets in documentation without exposing sheet settings or extra markup.
// AI Prompts: Write C# code with Aspose.Cells to export a workbook's print area to HTML while omitting worksheet properties. | Explain how ExportPrintAreaOnly and ExportWorksheetProperties affect the HTML output generated by Aspose.Cells. | Provide step‑by‑step instructions to define a print area, configure HtmlSaveOptions, and save the workbook as HTML with visible grid lines.

using System;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Demonstrates how to set a print area, enable ExportPrintAreaOnly, disable ExportWorksheetProperties, and keep grid lines visible with HtmlSaveOptions, then save the workbook as a lightweight HTML file.
    public class ExportPrintAreaWithoutWorksheetProperties
    {
        public static void Main(string[] args)
        {
            try
            {
                Run();
                Console.WriteLine("HTML file generated successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        public static void Run()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Fill the worksheet with sample data
            for (int i = 0; i < 20; i++)
            {
                for (int j = 0; j < 10; j++)
                {
                    worksheet.Cells[i, j].PutValue($"Cell {i + 1},{j + 1}");
                }
            }

            // Define the print area to be exported
            worksheet.PageSetup.PrintArea = "B2:F10";

            // Set up HTML save options
            HtmlSaveOptions options = new HtmlSaveOptions
            {
                // Export only the defined print area
                ExportPrintAreaOnly = true,
                // Omit worksheet properties from the generated HTML
                ExportWorksheetProperties = false,
                // Keep grid lines visible in the output
                ExportGridLines = true
            };

            // Save the workbook as HTML using the configured options
            string outputPath = "PrintAreaWithoutWorksheetProps.html";
            workbook.Save(outputPath, options);
        }
    }
}
