// Title: Export an Excel workbook to HTML using Aspose.Cells for .NET and insert page‑break markers as HTML comments
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, saves it as HTML, then scans the generated file and inserts <!--PageBreak--> comments at each printed page boundary. | Create a C# routine that uses Aspose.Cells HtmlSaveOptions to convert a workbook to HTML and performs a post‑save pass to embed custom page‑break comment tags for later processing.
// Common Searches: how to add custom page break comments after exporting Excel to HTML with Aspose.Cells .NET | Aspose.Cells C# export workbook to HTML and mark page breaks for JavaScript pagination | C# post‑process HTML output from Aspose.Cells to insert <!--PageBreak--> tags | workaround for missing page break markers in Aspose.Cells HTML export
// Tags: Aspose.Cells HtmlSaveOptions export to HTML | C# insert HTML comment markers after Aspose.Cells export | page break annotation in Aspose.Cells HTML output | post‑processing HTML generated by Aspose.Cells | Excel to HTML conversion with custom pagination markers

using System;
using System.IO;
using Aspose.Cells;

// The example loads an existing Excel file with Aspose.Cells, uses HtmlSaveOptions to save it as an HTML document, and notes that page‑break markers are not provided by the library, so they must be added manually by post‑processing the HTML to insert comment tags such as <!--PageBreak-->.
class Program
{
    static void Main()
    {
        const string inputPath = "input.xlsx";
        const string outputPath = "output.html";

        // Verify that the input file exists to avoid FileNotFoundException
        if (!File.Exists(inputPath))
        {
            Console.WriteLine($"Error: The file \"{inputPath}\" was not found.");
            return;
        }

        try
        {
            // Load the source Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Create HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Note: PageBreak markers are not supported in this version of Aspose.Cells.
            // If needed, they can be added manually after saving.

            // Export the workbook to an HTML file with the specified options
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"Workbook successfully saved as HTML to \"{outputPath}\".");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
