// Title: Export Excel Workbook to HTML with Inline Styles and CSS Custom Properties using Aspose.Cells C#
// Description: Shows how to create or load a workbook, configure HtmlSaveOptions.DisableCss = true and HtmlSaveOptions.EnableCssCustomProperties = true, and save the workbook as HTML that contains only inline styling and CSS variables for a lightweight web output.
// Keywords: Aspose.Cells | C# HtmlSaveOptions | DisableCss | EnableCssCustomProperties | export workbook to HTML | inline CSS | CSS variables | Excel to HTML C# | no external stylesheet | lightweight HTML report
// Common Searches: Aspose.Cells export workbook to HTML without external CSS | HtmlSaveOptions DisableCss true C# example | EnableCssCustomProperties Aspose.Cells HTML output | C# generate HTML from Excel with inline styles | How to use CSS custom properties in Aspose.Cells HTML export
// Developer Intent: Generate HTML from an Excel workbook while disabling external CSS and enabling CSS custom properties.
// Use Cases: Email-friendly HTML reports that rely solely on inline styling. | Web pages that leverage CSS variables to reduce redundancy and improve rendering speed. | Embedding Excel data in web applications without loading separate stylesheet files.
// AI Prompts: Write C# code that loads an existing Excel file and saves it as HTML with DisableCss = true and EnableCssCustomProperties = true using Aspose.Cells. | Explain the benefits of EnableCssCustomProperties in the HTML generated by Aspose.Cells and when to prefer it over standard inline styles. | Show how to extend the HtmlSaveOptions to embed images as Base64 while keeping CSS disabled and custom properties enabled.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Shows how to create or load a workbook, configure HtmlSaveOptions.DisableCss = true and HtmlSaveOptions.EnableCssCustomProperties = true, and save the workbook as HTML that contains only inline styling and CSS variables for a lightweight web output.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Add some sample data to demonstrate the export
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B1"].PutValue("World");
            sheet.Cells["A2"].PutValue(DateTime.Now);
            sheet.Cells["B2"].PutValue(12345);

            // Configure HTML save options:
            // - DisableCss = true  => use only inline styles, no external CSS.
            // - EnableCssCustomProperties = true => enable CSS custom properties for optimization.
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                DisableCss = true,
                EnableCssCustomProperties = true
            };

            // Save the workbook as an HTML file with the specified options
            workbook.Save("output.html", htmlOptions);

            Console.WriteLine("Workbook exported to HTML with CSS disabled and custom properties enabled.");
        }
    }
}
