// Title: How to export an Excel workbook to GZIP‑compressed HTML using Aspose.Cells in C#
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, saves it as HTML into a MemoryStream, and writes the stream to a .gz file using GZipStream. | Show how to pipe the HTML output of Workbook.Save into a GZipStream for efficient transmission in a .NET application.
// Common Searches: Aspose.Cells export workbook to HTML and gzip the result in C# | C# compress HTML generated by Aspose.Cells for web delivery | How to create a .html.gz file from an Excel workbook using Aspose.Cells | Saving Aspose.Cells HTML output to a GZipStream in .NET | Fast transmission of Excel to HTML using GZIP compression with Aspose.Cells
// Tags: Aspose.Cells HTML export with GZipStream | C# compress HTML output stream | Workbook.Save to MemoryStream then GZip | Generate .html.gz from Excel using .NET | GZIP compression for Aspose.Cells HTML files

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;

// Loads 'input.xlsx' with Aspose.Cells, exports it to HTML in a MemoryStream, then compresses the HTML using GZipStream and saves the result as 'output.html.gz' for faster delivery.
class Program
{
    static void Main()
    {
        // Load the source Excel file
        Workbook workbook = new Workbook("input.xlsx");

        // Prepare a memory stream to hold the generated HTML
        using (MemoryStream htmlStream = new MemoryStream())
        {
            // Export the workbook to HTML format
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            workbook.Save(htmlStream, htmlOptions);

            // Reset stream position to the beginning before reading
            htmlStream.Position = 0;

            // Create the output file that will contain the GZIP-compressed HTML
            using (FileStream fileStream = new FileStream("output.html.gz", FileMode.Create, FileAccess.Write))
            // Wrap the file stream with a GZipStream for compression
            using (GZipStream gzipStream = new GZipStream(fileStream, CompressionMode.Compress))
            {
                // Copy the HTML data into the GZipStream, which writes compressed bytes to the file
                htmlStream.CopyTo(gzipStream);
            }
        }
    }
}
