// Title: Export Excel workbook to HTML with Aspose.Cells and inject a custom CSS stylesheet to override cell background colors
// AI Prompts: Write C# code that loads an .xlsx file using Aspose.Cells, saves it as HTML, and inserts a <style> block with custom CSS classes that replace the default cell background colors. | Show how to locate the <head> element in the HTML generated by Aspose.Cells and embed a CSS snippet that overrides the .a0 and .a1 style indexes. | Add comprehensive error handling to a C# program that checks for the source workbook, verifies the generated HTML file, and logs a warning when the <head> tag is missing before injecting custom CSS.
// Common Searches: c# aspocells export workbook to html with custom stylesheet for cell colors | how to add custom css to html output generated by Aspose.Cells in .NET | override Aspose.Cells default cell background colors in exported html file | inject style tag into Aspose.Cells saved html using C# | Aspose.Cells htmlsaveoptions custom css for cell formatting
// Tags: aspose.cells html export with injected css | c# add style element to aspose.cells generated html | change cell background colors in html output | htmlsaveoptions post‑processing for cell formatting | modify style index classes in aspose.cells html

using Aspose.Cells;
using System;
using System.IO;

// The example loads an Excel workbook (input.xlsx) with Aspose.Cells, saves it as HTML (output.html), reads the generated file, injects a <style> tag containing custom CSS classes (.a0, .a1) that override the default cell background colors, and writes the updated HTML back. It includes checks for missing input files and missing <head> tags, providing appropriate error messages.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.html";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                return;
            }

            // Load the source Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Custom CSS that will override the default cell background colors generated by Aspose.Cells
            // The CSS classes (e.g., .a0, .a1) correspond to the style indexes Aspose.Cells creates.
            string customCss = @"
                .a0 { background-color: #FFCCCC !important; } /* Override for style index 0 */
                .a1 { background-color: #CCFFCC !important; } /* Override for style index 1 */
            ";

            // Configure HTML save options (using the default options)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

            // Export the workbook to HTML
            workbook.Save(outputPath, htmlOptions);

            // Inject the custom CSS into the generated HTML file
            if (File.Exists(outputPath))
            {
                string htmlContent = File.ReadAllText(outputPath);
                int headIndex = htmlContent.IndexOf("<head>", StringComparison.OrdinalIgnoreCase);
                if (headIndex >= 0)
                {
                    int insertPos = headIndex + "<head>".Length;
                    string styleTag = $"\n<style type=\"text/css\">\n{customCss}\n</style>\n";
                    htmlContent = htmlContent.Insert(insertPos, styleTag);
                    File.WriteAllText(outputPath, htmlContent);
                }
                else
                {
                    Console.WriteLine("Warning: <head> tag not found in the generated HTML. Custom CSS was not injected.");
                }
            }
            else
            {
                Console.WriteLine($"Error: Failed to generate the HTML file '{outputPath}'.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An unexpected error occurred: {ex.Message}");
        }
    }
}
