// Title: Export Excel to Single HTML with Page‑Break Comments using Aspose.Cells for .NET
// Description: Creates a workbook, fills 20 × 5 cells, adds a horizontal page break after row 10, saves the file as one HTML document with grid lines, then reads the output, finds the <tr id="row_10"> tag via regex, inserts a <!-- PageBreak --> comment before that row, and overwrites the HTML.
// Keywords: Aspose.Cells HTML export | C# Excel to HTML | horizontal page break Aspose.Cells | insert HTML comment after export | post‑process Aspose.Cells HTML | single file HTML save option | regex replace Aspose.Cells row id
// Common Searches: how to add page‑break markers to HTML generated by Aspose.Cells | Aspose.Cells export Excel as single HTML file | C# insert comment before specific row in Aspose.Cells HTML output | regex to locate row_10 in Aspose.Cells HTML | add custom markers to exported Excel HTML
// Developer Intent: Add HTML comment markers at rows where horizontal page breaks are defined after exporting an Excel workbook to a single HTML file with Aspose.Cells.
// Use Cases: Generate printable HTML where <!-- PageBreak --> tags are later replaced with CSS page‑break rules. | Build a web viewer that needs to highlight Excel page‑break locations for navigation or pagination. | Create an automated conversion pipeline that tags HTML with custom markers for downstream processing.
// AI Prompts: Write C# code using Aspose.Cells to export a workbook to one HTML file and prepend a <!-- PageBreak --> comment before the row that contains a horizontal page break. | Provide a regular expression that matches the <tr> element with id="row_10" in Aspose.Cells HTML output and demonstrate how to replace it with a comment plus the original tag. | Explain how to retrieve the zero‑based index of a horizontal page break in Aspose.Cells and use it to annotate the exported HTML with custom markers.

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;

namespace AsposeCellsHtmlExportWithPageBreakComments
{
    // Creates a workbook, fills 20 × 5 cells, adds a horizontal page break after row 10, saves the file as one HTML document with grid lines, then reads the output, finds the <tr id="row_10"> tag via regex, inserts a <!-- PageBreak --> comment before that row, and overwrites the HTML.
    class Program
    {
        static void Main()
        {
            try
            {
                // -------------------------------------------------
                // 1. Create a workbook and populate some sample data
                // -------------------------------------------------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Fill 20 rows and 5 columns with sample values
                for (int row = 0; row < 20; row++)
                {
                    for (int col = 0; col < 5; col++)
                    {
                        sheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                    }
                }

                // -------------------------------------------------
                // 2. Define a horizontal page break after row 10
                // -------------------------------------------------
                // Page breaks are zero‑based, so a break after row 10 means
                // the break is placed before row 11 (index 10).
                sheet.HorizontalPageBreaks.Add(10);

                // -------------------------------------------------
                // 3. Save the workbook as a single HTML file
                // -------------------------------------------------
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    SaveAsSingleFile = true,          // All sheets in one HTML file
                    ExportPageHeaders = false,        // Not needed for this demo
                    ExportPageFooters = false,
                    ExportGridLines = true,           // Makes the HTML easier to read
                    ExportCellCoordinate = false
                };

                string htmlPath = "WorkbookWithPageBreak.html";
                workbook.Save(htmlPath, htmlOptions);

                // -------------------------------------------------
                // 4. Post‑process the generated HTML to insert page‑break comments
                // -------------------------------------------------
                if (File.Exists(htmlPath))
                {
                    string htmlContent = File.ReadAllText(htmlPath, Encoding.UTF8);

                    // Build a regex that matches the opening <tr> tag of the target row.
                    // Aspose.Cells adds an id attribute like id="row_10" (zero‑based) to each <tr>.
                    // We'll use that to find the exact row.
                    string pattern = @"(<tr[^>]*\sid\s*=\s*[""']row_10[""'][^>]*>)";
                    string replacement = "<!-- PageBreak -->\n$1";

                    string updatedHtml = Regex.Replace(htmlContent, pattern, replacement, RegexOptions.IgnoreCase);

                    // Overwrite the original file with the modified content
                    File.WriteAllText(htmlPath, updatedHtml, Encoding.UTF8);
                }
                else
                {
                    Console.WriteLine($"Error: HTML file '{htmlPath}' was not created.");
                }

                Console.WriteLine($"HTML file saved to '{Path.GetFullPath(htmlPath)}' with page‑break comment inserted.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
