// Title: Convert an Excel workbook to HTML and add printable @media CSS with Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file, saves it as HTML using Aspose.Cells HtmlSaveOptions, and injects a <style> block containing @media print rules into the resulting HTML. | Show how to prepend a custom printable stylesheet to the <head> section of the HTML file produced by Aspose.Cells after exporting a workbook.
// Common Searches: Aspose.Cells .NET export Excel to HTML with custom print stylesheet | How to insert @media print CSS into HTML generated by Aspose.Cells | C# add printable CSS to Aspose.Cells HTML output after saving workbook | Inject custom style tag into Aspose.Cells HTML file for printing
// Tags: Aspose.Cells HTML export custom style injection | C# add printable CSS to Aspose.Cells output | HtmlSaveOptions embed print media rules | Excel workbook to printable HTML conversion | Inject @media print block into generated HTML

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // The example loads 'input.xlsx' with Aspose.Cells, saves it as 'output.html' using HtmlSaveOptions, then reads the generated file, inserts a <style> element that defines @media print rules after the <head> tag, and writes the modified HTML back to disk, producing a printable version of the workbook.
    class Program
    {
        static void Main()
        {
            try
            {
                const string inputFile = "input.xlsx";
                const string outputFile = "output.html";

                // Verify that the input workbook exists.
                if (!File.Exists(inputFile))
                {
                    Console.WriteLine($"Input file '{inputFile}' not found.");
                    return;
                }

                // Load the workbook.
                Workbook workbook = new Workbook(inputFile);

                // Custom CSS to be added manually after saving (HtmlSaveOptions does not expose a direct property for this in the current API version).
                string customCss = @"
@media print {
    body { margin: 0; }
    .sheet { page-break-after: always; }
    table { width: 100%; border-collapse: collapse; }
    td, th { border: 1px solid #000; padding: 5px; }
}";

                // Configure HTML save options.
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    ExportActiveWorksheetOnly = false,
                    ExportImagesAsBase64 = true
                };

                // Save the workbook as HTML.
                workbook.Save(outputFile, htmlOptions);
                Console.WriteLine($"Workbook successfully saved to '{outputFile}'.");

                // Optionally, prepend the custom CSS to the generated HTML file.
                if (File.Exists(outputFile))
                {
                    string htmlContent = File.ReadAllText(outputFile);
                    string styleTag = $"<style>{customCss}</style>";
                    // Insert the style tag just after the opening <head> tag.
                    int headIndex = htmlContent.IndexOf("<head>", StringComparison.OrdinalIgnoreCase);
                    if (headIndex != -1)
                    {
                        int insertPos = headIndex + "<head>".Length;
                        htmlContent = htmlContent.Insert(insertPos, styleTag);
                        File.WriteAllText(outputFile, htmlContent);
                        Console.WriteLine("Custom CSS injected into the HTML output.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
