// Title: Export Print Area to HTML without Document Properties – Aspose.Cells for .NET (C#)
// Description: Shows how to build a workbook, set a print area (B2:F10), and save it as HTML using Aspose.Cells for .NET while exporting only that region and stripping all workbook metadata.
// Keywords: Aspose.Cells HTML export | ExportPrintAreaOnly | ExportDocumentProperties false | C# save workbook as HTML | print area only HTML | remove workbook metadata | HtmlSaveOptions Aspose.Cells | lightweight HTML report
// Common Searches: Aspose.Cells export only print area to HTML | Hide document properties when saving HTML with Aspose.Cells | C# HtmlSaveOptions ExportPrintAreaOnly true example | Remove metadata from HTML output Aspose.Cells | Save worksheet print area as HTML .NET
// Developer Intent: Generate an HTML file that contains only the worksheet’s defined print area and excludes every document property.
// Use Cases: Create compact HTML snapshots for web publishing that show only the printable region. | Produce email‑ready reports without exposing workbook metadata such as author or creation date. | Automate batch conversion of multiple sheets, each limited to its print area, while keeping the output lightweight.
// AI Prompts: Provide C# code that saves a workbook as HTML with ExportPrintAreaOnly enabled and ExportDocumentProperties disabled using Aspose.Cells. | Explain the impact of ExportPrintAreaOnly and ExportDocumentProperties on the HTML generated by Aspose.Cells. | Step‑by‑step guide to export a specific print area to HTML while removing all document properties in Aspose.Cells for .NET.

using System;
using Aspose.Cells;

// Shows how to build a workbook, set a print area (B2:F10), and save it as HTML using Aspose.Cells for .NET while exporting only that region and stripping all workbook metadata.
class ExportPrintAreaWithoutDocumentProperties
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Fill the worksheet with sample data
        for (int row = 0; row < 20; row++)
        {
            for (int col = 0; col < 10; col++)
            {
                worksheet.Cells[row, col].PutValue($"Cell {row + 1},{col + 1}");
            }
        }

        // Define the print area that should be exported
        worksheet.PageSetup.PrintArea = "B2:F10";

        // Set up HTML save options:
        // - ExportPrintAreaOnly = true  => only the defined print area is exported
        // - ExportDocumentProperties = false => document properties are omitted from the output
        HtmlSaveOptions options = new HtmlSaveOptions
        {
            ExportPrintAreaOnly = true,
            ExportDocumentProperties = false
        };

        // Save the workbook as HTML using the configured options
        workbook.Save("PrintAreaOnly_NoDocProps.html", options);
    }
}
