// Title: Export Excel workbook to separate HTML files per worksheet using Aspose.Cells C# IStreamProvider
// Description: Shows how to save an Aspose.Cells workbook as individual HTML pages for each worksheet by setting HtmlSaveOptions (SaveAsSingleFile = false, ExportWorksheetCSSSeparately = true) and providing a custom IStreamProvider that creates a file stream for every HTML part.
// Keywords: Aspose.Cells HTML export C# | IStreamProvider custom stream | HtmlSaveOptions SaveAsSingleFile false | ExportWorksheetCSSSeparately | Excel to multiple HTML files | C# workbook to HTML per sheet | Aspose.Cells separate worksheet HTML | stream provider example
// Common Searches: How to export each worksheet to its own HTML file with Aspose.Cells .NET | Aspose.Cells IStreamProvider example for HTML output | Save workbook as multiple HTML files using HtmlSaveOptions | Export Excel to HTML with separate CSS per sheet C# | Aspose.Cells custom stream provider tutorial
// Developer Intent: Generate independent HTML files for every worksheet in an Excel workbook by using a custom IStreamProvider during the Aspose.Cells export process.
// Use Cases: Display each worksheet as a separate web page in a reporting portal. | Create printable HTML versions of individual sheets for email or documentation. | Avoid CSS conflicts when embedding multiple worksheet pages on a single site by isolating styles per file.
// AI Prompts: Write C# code that uses Aspose.Cells HtmlSaveOptions with a custom IStreamProvider to save each worksheet as a distinct HTML file in a target folder. | Explain the impact of ExportWorksheetCSSSeparately and SaveAsSingleFile settings on the HTML output generated by Aspose.Cells. | Provide a step‑by‑step guide to modify WorksheetStreamProvider so that HTML filenames are based on worksheet names.

using System;
using System.IO;
using Aspose.Cells;

// Shows how to save an Aspose.Cells workbook as individual HTML pages for each worksheet by setting HtmlSaveOptions (SaveAsSingleFile = false, ExportWorksheetCSSSeparately = true) and providing a custom IStreamProvider that creates a file stream for every HTML part.
class Program
{
    static void Main()
    {
        // Create a workbook with multiple worksheets and sample data
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Name = "Sheet1";
        workbook.Worksheets[0].Cells["A1"].PutValue("Data in Sheet 1");

        workbook.Worksheets.Add("Sheet2");
        workbook.Worksheets[1].Cells["A1"].PutValue("Data in Sheet 2");

        workbook.Worksheets.Add("Sheet3");
        workbook.Worksheets[2].Cells["A1"].PutValue("Data in Sheet 3");

        // Directory where separate HTML files will be written
        string outputDir = Path.Combine(Path.GetTempPath(), "AsposeHtmlExport");
        Directory.CreateDirectory(outputDir);

        // Configure HTML save options to use a custom stream provider
        HtmlSaveOptions saveOptions = new HtmlSaveOptions
        {
            // Export each worksheet's CSS separately to ensure distinct files
            ExportWorksheetCSSSeparately = true,
            // Do not combine everything into a single file
            SaveAsSingleFile = false,
            // Provide the custom stream provider
            StreamProvider = new WorksheetStreamProvider(outputDir)
        };

        // Save the workbook; the main file can be a placeholder (index.html)
        string mainHtmlPath = Path.Combine(outputDir, "index.html");
        workbook.Save(mainHtmlPath, saveOptions);

        Console.WriteLine("Export completed. HTML files are located at:");
        Console.WriteLine(outputDir);
    }
}

// Custom stream provider that creates a file stream for each requested HTML part
public class WorksheetStreamProvider : IStreamProvider
{
    private readonly string _baseDirectory;

    public WorksheetStreamProvider(string baseDirectory)
    {
        _baseDirectory = baseDirectory;
    }

    // Called by Aspose.Cells before writing each part (e.g., each worksheet HTML file)
    public void InitStream(StreamProviderOptions options)
    {
        // Ensure the target directory exists
        string directory = Path.GetDirectoryName(options.DefaultPath);
        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        // Create a file stream for the given path
        options.Stream = new FileStream(options.DefaultPath, FileMode.Create, FileAccess.Write);
    }

    // Called after the part has been written
    public void CloseStream(StreamProviderOptions options)
    {
        options.Stream?.Close();
    }
}
