// Title: Add a JavaScript page-number footer to HTML exported from an Excel workbook using Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that loads an Excel file with Aspose.Cells, saves the first worksheet as an HTML file, and returns the HTML content. | Write a C# method that inserts a fixed-position footer containing a JavaScript snippet for page numbering into the HTML string before the closing </body> tag, and handles the case where the tag is missing. | Create the JavaScript function that calculates total pages from document height and current page from scroll position, updating the footer on load, resize, and scroll events.
// Common Searches: how to add a dynamic page number footer to HTML generated by Aspose.Cells in C# | C# Aspose.Cells export worksheet to HTML and inject custom JavaScript | insert JavaScript footer into Aspose.Cells HTML output before </body> | calculate total pages in HTML using scroll height JavaScript | Aspose.Cells save active worksheet as HTML with custom footer
// Tags: Aspose.Cells HTML export with custom JavaScript footer | C# inject footer into generated HTML | dynamic page numbering script for HTML view | export active worksheet to HTML Aspose.Cells | fixed footer position page numbers JavaScript

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, uses Aspose.Cells to save only the active worksheet as UTF‑8 HTML, reads the resulting file, injects a fixed‑position footer that contains JavaScript for calculating and displaying the current and total page numbers, inserts the footer before the closing </body> tag (or appends it if missing), and writes the modified HTML back to disk.
class Program
{
    static void Main()
    {
        // Load the source Excel workbook
        string excelPath = "input.xlsx";
        Workbook workbook = new Workbook(excelPath);

        // Configure HTML save options
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions
        {
            ExportActiveWorksheetOnly = true, // export only the first worksheet
            Encoding = System.Text.Encoding.UTF8
        };

        // Export the workbook to an HTML file
        string htmlPath = "output.html";
        workbook.Save(htmlPath, htmlOptions);

        // Read the generated HTML content
        string htmlContent = File.ReadAllText(htmlPath);

        // JavaScript footer that displays page numbers
        string footerHtml = @"
<div id='footer' style='position:fixed;bottom:0;width:100%;text-align:center;background:#f0f0f0;padding:5px;'>
    Page <span id='pageCurrent'>1</span> of <span id='pageTotal'>1</span>
</div>
<script>
function updatePageInfo() {
    var totalPages = Math.ceil(document.body.scrollHeight / window.innerHeight);
    document.getElementById('pageTotal').innerText = totalPages;

    var currentPage = Math.ceil((window.scrollY + window.innerHeight) / window.innerHeight);
    document.getElementById('pageCurrent').innerText = currentPage;
}
window.onload = updatePageInfo;
window.onresize = updatePageInfo;
window.onscroll = updatePageInfo;
</script>";

        // Insert the footer just before the closing </body> tag
        const string bodyCloseTag = "</body>";
        int insertPos = htmlContent.IndexOf(bodyCloseTag, StringComparison.OrdinalIgnoreCase);
        if (insertPos >= 0)
        {
            htmlContent = htmlContent.Insert(insertPos, footerHtml);
        }
        else
        {
            // Fallback: append at the end if </body> is missing
            htmlContent += footerHtml;
        }

        // Write the modified HTML back to the file
        File.WriteAllText(htmlPath, htmlContent);
    }
}
