// Title: Export Excel to HTML with built‑in and custom <meta> tags using Aspose.Cells for .NET (C#)
// Description: Loads an Excel workbook, sets built‑in properties (Author, Title), adds custom properties (ProjectId, Reviewed, Revision), and saves the file as HTML. HtmlSaveOptions.ExportDocumentProperties and ExportWorkbookProperties embed these properties as <meta> tags, while page headers are disabled for clean output.
// Keywords: Aspose.Cells | C# | Excel to HTML | HTML export | meta tags | document properties | custom document properties | HtmlSaveOptions | ExportDocumentProperties | ExportWorkbookProperties | SEO-friendly HTML | workbook metadata
// Common Searches: Aspose.Cells export Excel to HTML with meta tags | How to include custom document properties in HTML output using Aspose.Cells | HtmlSaveOptions ExportDocumentProperties example C# | Add built‑in Excel properties to HTML meta tags Aspose | Remove page headers when saving Excel as HTML Aspose.Cells
// Developer Intent: Generate an HTML file from an Excel workbook that contains <meta> elements for both built‑in and custom document properties.
// Use Cases: Produce SEO‑optimized HTML reports that automatically carry author, title, and other workbook metadata. | Embed project identifiers, review status, and revision numbers in HTML for downstream processing or compliance tracking. | Create clean, header‑free HTML snapshots of Excel data while preserving all workbook‑level metadata for archival purposes.
// AI Prompts: Write C# code with Aspose.Cells to export an Excel workbook to HTML and embed custom document properties as <meta> tags. | Show how to verify the <meta> tags generated by HtmlSaveOptions.ExportDocumentProperties in the resulting HTML file. | Explain how ExportDocumentProperties and ExportWorkbookProperties work together to include both built‑in and custom metadata in HTML output.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExportWithMetadata
{
    // Loads an Excel workbook, sets built‑in properties (Author, Title), adds custom properties (ProjectId, Reviewed, Revision), and saves the file as HTML. HtmlSaveOptions.ExportDocumentProperties and ExportWorkbookProperties embed these properties as <meta> tags, while page headers are disabled for clean output.
    class Program
    {
        static void Main()
        {
            // Load an existing workbook (replace with your file path)
            Workbook workbook = new Workbook("input.xlsx");

            // Set some built‑in document properties
            workbook.BuiltInDocumentProperties.Author = "John Doe";
            workbook.BuiltInDocumentProperties.Title = "Sales Report";

            // Add custom document properties
            workbook.CustomDocumentProperties.Add("ProjectId", "PRJ-2023-001");
            workbook.CustomDocumentProperties.Add("Reviewed", true);
            workbook.CustomDocumentProperties.Add("Revision", 5);

            // Configure HTML save options to include document and workbook properties
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            htmlOptions.ExportDocumentProperties = true;   // export built‑in and custom properties as <meta> tags
            htmlOptions.ExportWorkbookProperties = true;   // export workbook‑level properties
            htmlOptions.ExportPageHeaders = false;        // optional: disable page headers for this example

            // Save the workbook as HTML; the generated file will contain <meta> tags with the properties above
            workbook.Save("output.html", htmlOptions);

            Console.WriteLine("HTML file saved with embedded metadata.");
        }
    }
}
