// Title: C# – Export Aspose.Cells Workbook to HTML without Document Properties
// Description: Shows how to configure Aspose.Cells HtmlSaveOptions with ExportDocumentProperties = false so the saved HTML contains only cell data and no workbook metadata (author, title, etc.).
// Keywords: Aspose.Cells | C# | HtmlSaveOptions | ExportDocumentProperties | HTML export | remove metadata | Excel to HTML | disable document properties | save workbook as HTML | strip workbook metadata
// Common Searches: Aspose.Cells export HTML without metadata | HtmlSaveOptions ExportDocumentProperties false example | C# save Excel as HTML without document properties | how to omit author and title in Aspose.Cells HTML output | remove document properties from HTML generated by Aspose.Cells
// Developer Intent: Create an HTML file from a workbook while excluding all document properties.
// Use Cases: Publish Excel‑derived reports on public websites without revealing author or internal information. | Batch‑process confidential workbooks to HTML for compliance‑driven data sharing. | Generate lightweight HTML snippets for web apps where only cell values are required.
// AI Prompts: Write C# code that uses Aspose.Cells to export a workbook to HTML with ExportDocumentProperties set to false. | Explain what HTML elements are omitted when ExportDocumentProperties is disabled and how to confirm the omission. | Demonstrate combining ExportDocumentProperties = false with other HtmlSaveOptions settings such as ExportImagesAsBase64.

using System;
using Aspose.Cells;

namespace AsposeCellsExportHtmlWithoutDocProps
{
    // Shows how to configure Aspose.Cells HtmlSaveOptions with ExportDocumentProperties = false so the saved HTML contains only cell data and no workbook metadata (author, title, etc.).
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet and add some sample data
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B1"].PutValue("World");

            // Set some document properties (optional, to demonstrate they are omitted)
            workbook.BuiltInDocumentProperties.Author = "John Doe";
            workbook.BuiltInDocumentProperties.Title = "Sample Workbook";

            // Create HTML save options and disable exporting document properties
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            htmlOptions.ExportDocumentProperties = false; // Omit document properties in the output HTML

            // Save the workbook as an HTML file using the specified options
            workbook.Save("output_without_doc_props.html", htmlOptions);

            Console.WriteLine("HTML file saved without document properties.");
        }
    }
}
