// Title: How to export an Excel workbook to HTML with an external CSS stylesheet using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file and saves it as HTML while creating a separate CSS file with Aspose.Cells. | Demonstrate configuring HtmlSaveOptions in Aspose.Cells to disable inline styles and produce an external stylesheet.
// Common Searches: Aspose.Cells export Excel to HTML external CSS file C# | save workbook as HTML without inline styles using Aspose.Cells .NET | generate separate stylesheet when converting Excel to HTML in .NET | HtmlSaveOptions external CSS option Aspose.Cells example
// Tags: Aspose.Cells HTML export with external CSS | C# HtmlSaveOptions external stylesheet | Export Excel to HTML without inline styles | Aspose.Cells generate separate CSS file

using System;
using System.IO;
using Aspose.Cells;

// The example checks for the input.xlsx file, loads it into an Aspose.Cells Workbook, configures HtmlSaveOptions (which defaults to creating an external CSS file when ExportToSingleFile is false), and saves the workbook as output.html. A separate CSS file is generated automatically, and any runtime errors are caught and reported.
class ExportExcelToHtmlWithExternalCss
{
    static void Main()
    {
        const string inputPath = "input.xlsx";
        const string outputHtml = "output.html";

        // Verify that the input workbook exists to avoid FileNotFoundException
        if (!File.Exists(inputPath))
        {
            Console.WriteLine($"Error: The file \"{inputPath}\" was not found.");
            return;
        }

        try
        {
            // Load the source Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure HTML save options; external CSS is generated by default when ExportToSingleFile is false
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);

            // Save the workbook as HTML; this creates "output.html" and a separate CSS file
            workbook.Save(outputHtml, saveOptions);

            Console.WriteLine($"Workbook successfully exported to \"{outputHtml}\" with external CSS.");
        }
        catch (Exception ex)
        {
            // Catch any runtime exceptions and display an informative message
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
