// Title: Export Excel to Responsive HTML with AspNet Aspose.Cells (C#)
// Description: Load an Excel workbook, set HtmlSaveOptions to HTML5, enable mobile compatibility, embed a media‑query CSS rule, and save a single responsive HTML file using Aspose.Cells for .NET.
// Keywords: Aspose.Cells export Excel to HTML | responsive HTML Aspose.Cells C# | mobile friendly HTML5 Excel export | HtmlSaveOptions IsMobileCompatible | .NET Excel to HTML conversion | single file HTML export Aspose | media query CSS Aspose.Cells
// Common Searches: how to create mobile friendly HTML from Excel using Aspose.Cells | Aspose.Cells C# export active worksheet to responsive HTML | HTML5 export with viewport meta tag Aspose.Cells | embed CSS media query in Aspose.Cells HTML export | save Excel as single responsive HTML file .NET
// Developer Intent: Generate a mobile‑optimized, single‑file HTML page from an Excel workbook with Aspose.Cells for .NET.
// Use Cases: Display a financial dashboard on smartphones by exporting the active sheet to a scrollable HTML table. | Provide a lightweight, offline‑viewable version of a spreadsheet for mobile users without external CSS files. | Integrate spreadsheet data into a web portal where the HTML must adapt to various screen sizes.
// AI Prompts: Add a sticky header to the responsive table generated by Aspose.Cells HTML export. | Export each worksheet of a workbook to separate responsive HTML files using Aspose.Cells. | Customize the viewport meta tag and additional CSS when IsMobileCompatible is enabled.

using System;
using Aspose.Cells;

namespace AsposeCellsResponsiveHtmlExport
{
    // Load an Excel workbook, set HtmlSaveOptions to HTML5, enable mobile compatibility, embed a media‑query CSS rule, and save a single responsive HTML file using Aspose.Cells for .NET.
    class Program
    {
        static void Main()
        {
            // Load an existing Excel file (replace with your actual file path)
            string excelPath = "input.xlsx";
            Workbook workbook = new Workbook(excelPath);

            // Configure HTML save options for responsive (mobile‑friendly) output
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

            // Use HTML5 which works well with modern browsers and mobile devices
            htmlOptions.HtmlVersion = HtmlVersion.Html5;

            // Enable built‑in mobile compatibility (adds viewport meta tag, etc.)
            htmlOptions.IsMobileCompatible = true;

            // Export only the active worksheet to keep the HTML lightweight
            htmlOptions.ExportActiveWorksheetOnly = true;

            // Export all data (including formulas, formatting, etc.)
            htmlOptions.ExportDataOptions = HtmlExportDataOptions.All;

            // Optional: add a simple responsive CSS rule (e.g., make tables scrollable on small screens)
            // This CSS will be embedded when SaveAsSingleFile is true.
            htmlOptions.SaveAsSingleFile = true;
            htmlOptions.CssStyles = @"
                @media only screen and (max-width: 600px) {
                    table { width: 100% !important; display: block; overflow-x: auto; }
                }";

            // Save the workbook as a responsive HTML file
            string htmlPath = "output_responsive.html";
            workbook.Save(htmlPath, htmlOptions);

            Console.WriteLine($"Responsive HTML saved to: {htmlPath}");
        }
    }
}
