// Title: Export ColorScale Conditional Formatting to HTML and Extract CSS Gradients with Aspose.Cells (C#)
// Description: Creates a 10×10 workbook, applies a three‑color scale (red‑yellow‑green) conditional format, saves the sheet as HTML with an external style.css file, and reads that CSS to output the generated gradient definitions.
// Keywords: Aspose.Cells HTML export | C# conditional formatting | ColorScale CSS gradient | extract style.css Aspose | separate CSS file Excel | export workbook to HTML | gradient definitions parsing
// Common Searches: Aspose.Cells export workbook with color scale to HTML | how to get CSS gradient from Aspose.Cells HTML output | read style.css generated by Aspose.Cells C# | separate CSS file for conditional formatting Aspose | extract gradient rules from exported Excel HTML
// Developer Intent: Generate HTML from a workbook that contains a ColorScale conditional format, store the styling in an external CSS file, and retrieve the gradient rules from that file.
// Use Cases: Build web‑based reports where Excel conditional colors are managed via external CSS for easy theme updates. | Reuse the extracted gradient definitions in custom web pages or email templates to keep visual consistency with Excel data. | Automate validation of exported CSS to ensure the expected gradient colors and thresholds are applied.
// AI Prompts: Show how to save the Aspose.Cells CSS file to a custom folder and then read gradient definitions from that location. | Provide a C# method that parses the gradient lines in style.css and maps them back to the original ColorScale thresholds. | Explain how to apply the extracted CSS gradients to another HTML document that was not generated by Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;
using System.Drawing;

// Creates a 10×10 workbook, applies a three‑color scale (red‑yellow‑green) conditional format, saves the sheet as HTML with an external style.css file, and reads that CSS to output the generated gradient definitions.
class ColorScaleCssExport
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data (10x10 matrix)
        for (int i = 0; i < 10; i++)
        {
            for (int j = 0; j < 10; j++)
            {
                sheet.Cells[i, j].PutValue(i * j);
            }
        }

        // Add a ColorScale conditional formatting rule
        int cfIndex = sheet.ConditionalFormattings.Add();                     // create conditional formatting collection
        FormatConditionCollection fcc = sheet.ConditionalFormattings[cfIndex];

        // Define the range A1:J10
        CellArea area = new CellArea { StartRow = 0, EndRow = 9, StartColumn = 0, EndColumn = 9 };
        fcc.AddArea(area);

        // Add a ColorScale condition (3‑color scale)
        int conditionIdx = fcc.AddCondition(FormatConditionType.ColorScale);
        FormatCondition fc = fcc[conditionIdx];

        // Configure the ColorScale: Red → Yellow → Green
        fc.ColorScale.Is3ColorScale = true;
        fc.ColorScale.MinCfvo.Type = FormatConditionValueType.Min;
        fc.ColorScale.MinColor = Color.Red;
        fc.ColorScale.MidCfvo.Type = FormatConditionValueType.Percentile;
        fc.ColorScale.MidCfvo.Value = 50;
        fc.ColorScale.MidColor = Color.Yellow;
        fc.ColorScale.MaxCfvo.Type = FormatConditionValueType.Max;
        fc.ColorScale.MaxColor = Color.Green;

        // Save the workbook as HTML with CSS exported separately
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();
        saveOptions.ExportWorksheetCSSSeparately = true; // rule usage
        string htmlPath = "ColorScale.html";
        workbook.Save(htmlPath, saveOptions);

        // Aspose creates a folder "<htmlFileName>_files" containing the CSS file (usually named "style.css")
        string cssFolder = Path.Combine(Path.GetDirectoryName(htmlPath), Path.GetFileNameWithoutExtension(htmlPath) + "_files");
        string cssPath = Path.Combine(cssFolder, "style.css");

        if (File.Exists(cssPath))
        {
            string cssContent = File.ReadAllText(cssPath);
            Console.WriteLine("Extracted CSS gradient definitions:");
            // Simple extraction: output lines that contain gradient definitions
            using (StringReader reader = new StringReader(cssContent))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (line.Contains("gradient"))
                    {
                        Console.WriteLine(line.Trim());
                    }
                }
            }
        }
        else
        {
            Console.WriteLine("CSS file not found at: " + cssPath);
        }
    }
}
