// Title: Generate HTML from an Aspose.Cells workbook and extract all hyperlink URLs using C#
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, adds cells containing hyperlinks, saves the workbook as HTML to a memory stream, and parses the HTML to collect every href value. | Refactor the example to use HtmlAgilityPack for extracting anchor href attributes from the generated HTML instead of a regular expression. | Extend the program to write the list of extracted URLs to a CSV file, ensuring duplicate links are handled gracefully.
// Common Searches: how to export an Aspose.Cells workbook to HTML and get all link URLs in C# | extract href attributes from HTML generated by Aspose.Cells using .NET | parse Aspose.Cells HTML output for hyperlinks with HtmlAgilityPack C#
// Tags: Aspose.Cells HTML export hyperlink extraction C# | parse anchor href with HtmlAgilityPack .NET | memory stream HTML generation from Excel workbook | save extracted URLs to CSV in C# | regular expression hyperlink parsing Aspose.Cells HTML

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The sample creates an Aspose.Cells workbook, inserts cells with hyperlinks, saves the workbook as HTML into a memory stream, reads the HTML content, and extracts all anchor href values using a regular expression. Extracted URLs are printed to the console, with error handling for unexpected issues.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add cells with hyperlinks
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Cell A1 with a hyperlink to Google
            sheet.Cells["A1"].PutValue("Google");
            sheet.Hyperlinks.Add("A1", 0, 0, "https://www.google.com");

            // Cell A2 with a hyperlink to Stack Overflow
            sheet.Cells["A2"].PutValue("StackOverflow");
            sheet.Hyperlinks.Add("A2", 0, 0, "https://stackoverflow.com");

            // Save the workbook as HTML into a memory stream
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, SaveFormat.Html);
                htmlStream.Position = 0; // Reset stream position for reading

                // Read the generated HTML as a string
                string htmlContent;
                using (StreamReader reader = new StreamReader(htmlStream))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Extract all hyperlink URLs using a regular expression
                List<string> hyperlinkUrls = new List<string>();
                Regex hrefRegex = new Regex(@"<a\s+[^>]*href\s*=\s*[""']([^""']+)[""']", RegexOptions.IgnoreCase);
                MatchCollection matches = hrefRegex.Matches(htmlContent);
                foreach (Match match in matches)
                {
                    if (match.Groups.Count > 1)
                    {
                        string href = match.Groups[1].Value;
                        if (!string.IsNullOrEmpty(href))
                        {
                            hyperlinkUrls.Add(href);
                        }
                    }
                }

                // Output the extracted URLs
                Console.WriteLine("Extracted hyperlink URLs:");
                foreach (string url in hyperlinkUrls)
                {
                    Console.WriteLine(url);
                }
            }
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
