// Title: C# – Export Excel to HTML with Column Letters and Row Numbers using Aspose.Cells
// Description: Shows how to build a Workbook, fill cells A1:B3, and save it as an HTML file that displays Excel‑style column letters and row numbers by enabling HtmlSaveOptions.ExportRowColumnHeadings in Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# HTML export | ExportRowColumnHeadings | column letters HTML | row numbers HTML | HtmlSaveOptions | Excel to HTML conversion | display column headers | save workbook as HTML | Aspose.Cells .NET example
// Common Searches: Aspose.Cells show column letters when saving as HTML | C# HtmlSaveOptions ExportRowColumnHeadings example | Export Excel workbook to HTML with row and column headings | How to enable column letters in HTML output using Aspose.Cells | Aspose.Cells HTML export with grid headings
// Developer Intent: Create an HTML representation of a worksheet that retains Excel column letters and row numbers.
// Use Cases: Web‑based spreadsheet viewer that mirrors Excel column labeling. | Generating printable HTML reports with clear column identification. | Embedding Excel data in documentation while preserving grid headings.
// AI Prompts: Modify the code to also export column widths in the HTML output. | Provide a C# snippet that hides row numbers but keeps column letters. | Explain how to style the heading cells generated by ExportRowColumnHeadings.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Shows how to build a Workbook, fill cells A1:B3, and save it as an HTML file that displays Excel‑style column letters and row numbers by enabling HtmlSaveOptions.ExportRowColumnHeadings in Aspose.Cells for .NET.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Product");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["B2"].PutValue(50);
            sheet.Cells["A3"].PutValue("Orange");
            sheet.Cells["B3"].PutValue(30);

            // Configure HTML save options to display row and column headings (e.g., column letters)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportRowColumnHeadings = true   // Enable column letters and row numbers in the HTML output
            };

            // Save the workbook as an HTML file using the configured options
            string outputPath = "WorkbookWithHeadings.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"HTML file saved to '{outputPath}' with column letters displayed.");
        }
    }
}
