// Title: Export Excel to HTML with Column Letters in C# using Aspose.Cells
// Description: Shows how to build a workbook, fill cells, enable ExportRowColumnHeadings in HtmlSaveOptions, and save as HTML so column letters and row numbers are displayed.
// Keywords: Aspose.Cells | C# HTML export | ExportRowColumnHeadings | column letters HTML | row numbers HTML | HtmlSaveOptions example | Excel to HTML .NET | display column headers | Aspose.Cells tutorial
// Common Searches: Aspose.Cells show column letters in HTML | HtmlSaveOptions ExportRowColumnHeadings C# | Export Excel as HTML with row and column headings .NET | C# generate HTML from workbook with column headers | Aspose.Cells HTML export options
// Developer Intent: Create an HTML version of an Excel worksheet that retains Excel‑style column letters and row numbers.
// Use Cases: Web dashboards that need familiar spreadsheet column identifiers | Printable HTML reports where users reference column letters | Embedding Excel data in web pages without requiring the Office viewer | Automated documentation generation that mirrors Excel layout
// AI Prompts: Provide C# code using Aspose.Cells to export a workbook to HTML with column letters and row numbers visible. | Show how to disable column headings while keeping row numbers in HtmlSaveOptions. | Give an example that adds custom CSS to the HTML output generated by Aspose.Cells and retains row/column headings. | Explain the impact of ExportRowColumnHeadings on the generated HTML structure.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Shows how to build a workbook, fill cells, enable ExportRowColumnHeadings in HtmlSaveOptions, and save as HTML so column letters and row numbers are displayed.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Item");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("Orange");
            sheet.Cells["B3"].PutValue(15);

            // Configure HTML save options to display row and column headings (e.g., column letters)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportRowColumnHeadings = true   // Enables column letters and row numbers in the HTML output
            };

            // Save the workbook as an HTML file
            workbook.Save("output_with_headings.html", htmlOptions);

            Console.WriteLine("HTML file saved with column letters displayed.");
        }
    }
}
