// Title: Export Excel to Plain HTML without Conditional Formatting using Aspose.Cells for .NET
// Description: Loads an .xlsx file, clears all ConditionalFormattings from each worksheet, and saves the workbook as minimal HTML with only inline styles by setting HtmlSaveOptions.DisableCss and ExcludeUnusedStyles.
// Keywords: Aspose.Cells HTML export | C# Excel to HTML | remove conditional formatting Aspose.Cells | DisableCss HtmlSaveOptions | ExcludeUnusedStyles | plain HTML from Excel | inline styles only | batch Excel to HTML conversion | Aspose.Cells .NET example
// Common Searches: Aspose.Cells export Excel to HTML without conditional formatting | How to disable CSS when saving workbook as HTML in C# | Clear conditional formatting before HTML conversion Aspose.Cells | Generate plain HTML from Excel using Aspose.Cells | C# code to remove conditional formatting and save as HTML
// Developer Intent: Create a plain‑style HTML file from an Excel workbook by stripping all conditional formatting and using only inline CSS.
// Use Cases: Embedding a clean HTML preview of a financial report in email newsletters. | Serving lightweight HTML pages where conditional formatting adds no value. | Automating bulk conversion of Excel files to minimal HTML for archival or web publishing.
// AI Prompts: Write C# code with Aspose.Cells that loads an .xlsx, removes all conditional formatting, and saves it as HTML using only inline styles. | Explain the impact of HtmlSaveOptions.DisableCss and ExcludeUnusedStyles on the HTML output generated by Aspose.Cells. | Provide a step‑by‑step guide to batch‑process a directory of Excel files, clearing conditional formatting and exporting each to plain HTML with Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;

// Loads an .xlsx file, clears all ConditionalFormattings from each worksheet, and saves the workbook as minimal HTML with only inline styles by setting HtmlSaveOptions.DisableCss and ExcludeUnusedStyles.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.html";

            // Verify that the input workbook exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: Input file \"{inputPath}\" not found.");
                return;
            }

            // Load the source workbook
            Workbook workbook = new Workbook(inputPath);

            // Remove all conditional formatting from every worksheet
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Correct API: ConditionalFormattings collection
                sheet.ConditionalFormattings.Clear();
            }

            // Configure HTML save options for a plain visual representation
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                // Use only inline styles (makes the HTML independent of CSS files)
                DisableCss = true,
                // Exclude any unused styles to keep the output minimal
                ExcludeUnusedStyles = true
            };

            // Save the workbook as an HTML file with the specified options
            workbook.Save(outputPath, htmlOptions);
            Console.WriteLine($"Workbook successfully saved as \"{outputPath}\".");
        }
        catch (Exception ex)
        {
            // Catch any unexpected errors and display a friendly message
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
