// Title: How to assign a custom <title> tag when saving an Excel workbook to HTML with Aspose.Cells for .NET
// AI Prompts: Create a C# program that builds a workbook, populates cells, sets HtmlSaveOptions.HtmlTitle to a desired string, and saves the workbook as an HTML file. | Update the provided Aspose.Cells example to include a custom page title and describe how to verify the <title> element in the resulting HTML.
// Common Searches: Aspose.Cells set HTML title attribute when exporting workbook C# | C# HtmlSaveOptions HtmlTitle property example for Excel to HTML conversion | How to change the <title> tag in HTML output generated by Aspose.Cells | Saving Excel as HTML with custom page title using Aspose.Cells .NET
// Tags: Aspose.Cells HtmlSaveOptions HtmlTitle | C# export Excel to HTML with custom title | set HTML <title> using Aspose.Cells | custom page title in Aspose.Cells HTML output

using Aspose.Cells;
using System;

// The example creates a workbook, fills it with sample data, configures HtmlSaveOptions.HtmlTitle to specify a custom page title, and saves the workbook as an HTML file, resulting in an <title> element that reflects the provided string.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Get the first worksheet and give it a name
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Sample";

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Item");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apples");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("Oranges");
            sheet.Cells["B3"].PutValue(20);

            // Set up HTML save options (Title property not available in this version)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

            // Save the workbook as an HTML file using the specified options
            workbook.Save("output.html", htmlOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
