// Title: Create an HTML file from an Aspose.Cells workbook containing hyperlinks and extract all href URLs with C#
// AI Prompts: Write a C# console application that adds hyperlink cells to an Aspose.Cells workbook, saves the workbook as HTML, reads the generated file, and prints every href value found in the <a> tags. | Refactor the program to use HtmlAgilityPack instead of regular expressions for parsing the HTML and collecting hyperlink URLs. | Extend the solution to write the extracted URLs to a text file and optionally remove duplicate entries.
// Common Searches: how to export an Aspose.Cells workbook to HTML and get the list of hyperlinks in C# | extract anchor href values from HTML generated by Aspose.Cells using .NET | C# regex pattern to find all <a> tags in an Excel‑to‑HTML conversion | using HtmlAgilityPack to parse Aspose.Cells HTML output for link analysis | save Excel hyperlinks as HTML and retrieve them programmatically in C#
// Tags: Aspose.Cells save workbook as HTML C# | extract href attributes from generated HTML | hyperlink extraction using C# regex | HtmlAgilityPack parse Aspose.Cells HTML output | link analysis of Excel‑to‑HTML conversion

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The program creates an Aspose.Cells workbook, inserts cells with hyperlink text, assigns actual URLs to those cells, saves the workbook as an HTML file, reads the HTML content, uses a regular expression to locate all <a> tags and capture their href attributes, collects the URLs into a list, and outputs each extracted link to the console.
class Program
{
    static void Main()
    {
        try
        {
            // 1. Create a new workbook and add some data with hyperlinks
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Add plain text header
            cells["A1"].PutValue("Example Links");

            // Add hyperlink for Google
            cells["A2"].PutValue("Google");
            // Add hyperlink to the cell range (A2)
            sheet.Hyperlinks.Add(1, 0, 1, 1, "https://www.google.com");

            // Add hyperlink for Microsoft
            cells["A3"].PutValue("Microsoft");
            // Add hyperlink to the cell range (A3)
            sheet.Hyperlinks.Add(2, 0, 1, 1, "https://www.microsoft.com");

            // 2. Save the workbook as HTML
            string htmlPath = "output.html";
            workbook.Save(htmlPath, SaveFormat.Html);

            // 3. Verify that the HTML file was created
            if (!File.Exists(htmlPath))
            {
                Console.WriteLine($"Error: HTML file '{htmlPath}' was not created.");
                return;
            }

            // 4. Read the HTML content
            string htmlContent;
            try
            {
                htmlContent = File.ReadAllText(htmlPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to read HTML file: {ex.Message}");
                return;
            }

            // 5. Extract all hyperlink URLs using Regex (no external library)
            List<string> urls = new List<string>();
            var matches = Regex.Matches(htmlContent, "<a[^>]+href\\s*=\\s*\"([^\"]*)\"", RegexOptions.IgnoreCase);
            foreach (Match match in matches)
            {
                string href = match.Groups[1].Value;
                if (!string.IsNullOrEmpty(href))
                {
                    urls.Add(href);
                }
            }

            // 6. Output the extracted URLs
            Console.WriteLine("Extracted hyperlink URLs:");
            foreach (string url in urls)
            {
                Console.WriteLine(url);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An unexpected error occurred: {ex.Message}");
        }
    }
}
