// Title: Export a Multi‑Sheet Workbook to IE‑Compatible MHTML with Tab Navigation (C# Aspose.Cells)
// Description: Demonstrates how to create a workbook with several worksheets, configure HtmlSaveOptions (IsIECompatible, SaveAsSingleFile, ShowAllSheets) and save it as a single .mht file that displays each sheet as a clickable tab in Internet Explorer. Includes error handling and verification steps.
// Keywords: Aspose.Cells | C# | MHTML | IE compatible HTML | HtmlSaveOptions | IsIECompatible | SaveAsSingleFile | ShowAllSheets | multi‑sheet export | tab navigation | Internet Explorer | mht file
// Common Searches: Aspose.Cells export workbook to MHTML IE | C# save multiple worksheets as single .mht file | How to enable tab navigation in MHTML generated by Aspose.Cells | HtmlSaveOptions IsIECompatible example | Create IE‑compatible HTML from Excel using Aspose
// Developer Intent: Produce a single‑file MHTML document that works in Internet Explorer and lets users switch between worksheets via tabs.
// Use Cases: Generate a consolidated report for legacy intranet portals that must be viewable in IE without separate HTML files. | Automate email attachments containing all workbook sheets in one .mht file for corporate distribution. | Create printable, tab‑enabled documentation for internal tools that rely on Internet Explorer.
// AI Prompts: Write C# code with Aspose.Cells to export a workbook with three sheets to an IE‑compatible MHTML file that shows each sheet as a tab. | Explain the role of HtmlSaveOptions properties IsIECompatible, SaveAsSingleFile, ShowAllSheets, and ExportActiveWorksheetOnly when saving to .mht. | Provide a step‑by‑step guide to test the generated MHTML file in different versions of Internet Explorer.

using System;
using Aspose.Cells;

// Demonstrates how to create a workbook with several worksheets, configure HtmlSaveOptions (IsIECompatible, SaveAsSingleFile, ShowAllSheets) and save it as a single .mht file that displays each sheet as a clickable tab in Internet Explorer. Includes error handling and verification steps.
class GenerateIECompatibleMhtml
{
    static void Main()
    {
        try
        {
            // Create a new workbook with multiple worksheets
            Workbook workbook = new Workbook();

            // First sheet (default sheet)
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "Sheet1";
            sheet1.Cells["A1"].PutValue("Data in Sheet 1");

            // Add second sheet
            Worksheet sheet2 = workbook.Worksheets.Add("Sheet2");
            sheet2.Cells["A1"].PutValue("Data in Sheet 2");

            // Add third sheet
            Worksheet sheet3 = workbook.Worksheets.Add("Sheet3");
            sheet3.Cells["A1"].PutValue("Data in Sheet 3");

            // Configure HTML save options for IE‑compatible MHTML with tab navigation
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            saveOptions.IsIECompatible = true;          // Enable IE compatibility mode
            saveOptions.SaveAsSingleFile = true;        // Export as a single file (MHTML‑like)
            saveOptions.ShowAllSheets = true;           // Include all worksheets
            saveOptions.ExportActiveWorksheetOnly = false; // Export the whole workbook

            // Save the workbook as IE‑compatible MHTML (using .mht extension)
            workbook.Save("MultiSheet_IE_Compatible.mht", saveOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
