// Title: Export Excel to HTML with scalable columns and hover tooltips using Aspose.Cells for .NET
// Description: C# example that creates a workbook, inserts long text, narrows a column to force truncation, and saves as HTML with HtmlSaveOptions.WidthScalable and AddTooltipText enabled, producing responsive columns and tooltips for overflow cells.
// Keywords: Aspose.Cells | HtmlSaveOptions | WidthScalable | AddTooltipText | C# HTML export | responsive columns | cell tooltip | Excel to HTML | overflow text tooltip
// Common Searches: Aspose.Cells enable WidthScalable | AddTooltipText option C# | HTML export with tooltips Aspose | responsive HTML table from Excel .NET | show full cell text on hover Aspose.Cells
// Developer Intent: Export an Excel workbook to HTML where column widths adapt to the browser and truncated cell values are displayed via hover tooltips.
// Use Cases: Responsive web reports that automatically adjust column size | Displaying lengthy descriptions in HTML tables without breaking layout | Interactive dashboards where users can view full cell content on hover
// AI Prompts: Provide C# code to set a custom CSS style for tooltips generated by AddTooltipText. | Show how to disable WidthScalable while keeping AddTooltipText active. | Explain the effect of WidthScalable on column width calculations in HTML output.

using System;
using Aspose.Cells;

// C# example that creates a workbook, inserts long text, narrows a column to force truncation, and saves as HTML with HtmlSaveOptions.WidthScalable and AddTooltipText enabled, producing responsive columns and tooltips for overflow cells.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Add sample data that will exceed the column width
        worksheet.Cells["A1"].PutValue("This is a very long text that will exceed the column width and should show a tooltip.");
        // Set a narrow column width to force truncation
        worksheet.Cells.SetColumnWidth(0, 10);

        // Configure HTML save options
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();
        saveOptions.WidthScalable = true;      // Enable scalable column widths
        saveOptions.AddTooltipText = true;     // Enable tooltip for truncated cell content

        // Save the workbook as an HTML file with the specified options
        workbook.Save("ScalableWithTooltip.html", saveOptions);
    }
}
