// Title: Export an Aspose.Cells workbook with a pie chart to HTML and count the generated <img> tags using C#
// AI Prompts: Write C# code that saves a workbook containing a pie chart as HTML and returns the total number of <img> elements in the resulting markup. | Enhance the program to iterate over each <img> tag in the exported HTML and print its src attribute value. | Swap the regular‑expression approach for HtmlAgilityPack to reliably enumerate image nodes in the Aspose.Cells HTML output.
// Common Searches: how to count image tags in HTML generated by Aspose.Cells C# | Aspose.Cells export chart to HTML and retrieve image count | C# extract src attribute from <img> tags in Aspose.Cells HTML export | using HtmlAgilityPack to parse Aspose.Cells generated HTML for images | memory stream conversion to HTML with Aspose.Cells and image detection
// Tags: Aspose.Cells export workbook to HTML | image element detection in Aspose.Cells HTML | C# HtmlAgilityPack for parsing image nodes | pie chart rendered as image in HTML export | memory stream HTML generation with Aspose.Cells

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts; // Added for Chart and ChartType

// The example creates a workbook with a pie chart, saves it to an HTML string via a memory stream, and counts the <img> tags in the generated markup using a regular expression.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some data for the chart
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B4"].PutValue(30);

            // Add a pie chart (charts are rendered as images in HTML)
            int chartIndex = sheet.Charts.Add(ChartType.Pie, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Save the workbook to an HTML string using a memory stream
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, SaveFormat.Html);
                htmlStream.Position = 0;

                // Read the HTML content as a string
                string htmlContent;
                using (StreamReader reader = new StreamReader(htmlStream))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Count the number of <img> tags using a simple regex
                int imgTagCount = Regex.Matches(htmlContent, "<img\\b", RegexOptions.IgnoreCase).Count;

                // Output the result
                Console.WriteLine($"Number of <img> tags in the generated HTML: {imgTagCount}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
