// Title: Generate HTML from an Aspose.Cells workbook and ensure a :root CSS block with custom properties is present using C#
// AI Prompts: Write C# code that saves an Aspose.Cells workbook as HTML, then parses the file to guarantee a <style> element containing a :root rule with the required CSS custom properties. | Create a method that reads the generated HTML, adds a <head> tag if missing, and injects or updates a :root selector with variables such as --primary-color and --font-family. | Implement string‑based manipulation in C# to locate an existing <style> block in the HTML head and replace its :root definition with a new set of custom properties.
// Common Searches: C# how to add a :root CSS block to HTML generated by Aspose.Cells | inject custom CSS variables into Aspose.Cells HTML output using .NET | ensure <style> element with CSS custom properties exists in workbook HTML file | modify generated HTML head section to include CSS variables in C#
// Tags: Aspose.Cells HTML export with CSS variable injection | C# insert :root selector into HTML head | ensure custom CSS properties in workbook HTML | string manipulation of HTML style block in .NET | add CSS custom properties to generated HTML file

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlCssDemo
{
    // The example creates a simple workbook, exports it to HTML with Aspose.Cells, then reads the HTML file, guarantees a <head> element, and injects or updates a <style> block containing a :root selector that defines custom CSS variables such as --primary-color and --font-family, finally saving the modified HTML.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // 1. Create a simple workbook with sample data
                var workbook = new Workbook();
                var sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Name");
                sheet.Cells["B1"].PutValue("Score");
                sheet.Cells["A2"].PutValue("Alice");
                sheet.Cells["B2"].PutValue(85);
                sheet.Cells["A3"].PutValue("Bob");
                sheet.Cells["B3"].PutValue(92);

                // 2. Export the workbook to HTML
                string htmlPath = "output.html";
                workbook.Save(htmlPath, SaveFormat.Html);

                // 3. Load the generated HTML file safely
                if (!File.Exists(htmlPath))
                {
                    Console.WriteLine($"Error: HTML file '{htmlPath}' was not found.");
                    return;
                }

                string htmlContent = File.ReadAllText(htmlPath);

                // 4. Define the required CSS custom properties
                string[] customProperties = new[]
                {
                    "--primary-color: #4CAF50;",
                    "--secondary-color: #FFC107;",
                    "--font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
                };

                // Build the :root CSS block
                string rootCss = $":root {{{Environment.NewLine}    {string.Join(Environment.NewLine + "    ", customProperties)}{Environment.NewLine}}}";

                // 5. Ensure a <style> element with a :root selector exists
                // Simple string‑based manipulation (avoids external HTML parser)

                // Ensure <head> tag exists
                if (!htmlContent.Contains("<head>", StringComparison.OrdinalIgnoreCase))
                {
                    int htmlIdx = htmlContent.IndexOf("<html", StringComparison.OrdinalIgnoreCase);
                    if (htmlIdx >= 0)
                    {
                        int closeTagIdx = htmlContent.IndexOf('>', htmlIdx);
                        if (closeTagIdx >= 0)
                        {
                            // Insert <head></head> right after the opening <html> tag
                            htmlContent = htmlContent.Insert(closeTagIdx + 1, $"{Environment.NewLine}<head>{Environment.NewLine}</head>{Environment.NewLine}");
                        }
                    }
                }

                // Locate existing <style> block inside <head>
                int headStart = htmlContent.IndexOf("<head>", StringComparison.OrdinalIgnoreCase);
                int headEnd = htmlContent.IndexOf("</head>", StringComparison.OrdinalIgnoreCase);
                if (headStart >= 0 && headEnd > headStart)
                {
                    string headContent = htmlContent.Substring(headStart, headEnd - headStart + "</head>".Length);
                    int styleStart = headContent.IndexOf("<style", StringComparison.OrdinalIgnoreCase);
                    if (styleStart < 0)
                    {
                        // No <style> block – insert one with the :root selector
                        string styleTag = $"<style>{Environment.NewLine}{rootCss}{Environment.NewLine}</style>{Environment.NewLine}";
                        headContent = headContent.Replace("</head>", styleTag + "</head>");
                    }
                    else
                    {
                        int styleEnd = headContent.IndexOf("</style>", styleStart, StringComparison.OrdinalIgnoreCase);
                        if (styleEnd > styleStart)
                        {
                            string styleBlock = headContent.Substring(styleStart, styleEnd - styleStart + "</style>".Length);
                            if (!styleBlock.Contains(":root", StringComparison.OrdinalIgnoreCase))
                            {
                                // Append :root block to existing styles
                                string newStyleBlock = styleBlock.Replace("</style>", $"{Environment.NewLine}{rootCss}{Environment.NewLine}</style>");
                                headContent = headContent.Replace(styleBlock, newStyleBlock);
                            }
                            else
                            {
                                // Replace existing :root block with our definition
                                int rootIdx = styleBlock.IndexOf(":root", StringComparison.OrdinalIgnoreCase);
                                int braceOpen = styleBlock.IndexOf('{', rootIdx);
                                int braceClose = styleBlock.IndexOf('}', braceOpen);
                                if (braceOpen >= 0 && braceClose > braceOpen)
                                {
                                    string beforeRoot = styleBlock.Substring(0, rootIdx);
                                    string afterRoot = styleBlock.Substring(braceClose + 1);
                                    string replacedRoot = beforeRoot + rootCss + afterRoot;
                                    headContent = headContent.Replace(styleBlock, replacedRoot);
                                }
                            }
                        }
                    }

                    // Reconstruct the full HTML with modified head
                    htmlContent = htmlContent.Substring(0, headStart) + headContent + htmlContent.Substring(headEnd + "</head>".Length);
                }

                // 6. Save the modified HTML back to file
                File.WriteAllText(htmlPath, htmlContent);
                Console.WriteLine($"HTML file '{htmlPath}' has been processed and ensured to contain the required CSS custom properties.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
