// Title: Create an Aspose.Cells workbook with a column chart, export it to HTML, and count the generated <img> tags using C#
// AI Prompts: Write a C# console program that builds a workbook, adds a column chart, saves the workbook as HTML, reads the resulting HTML file, and returns the number of <img> elements using a case‑insensitive regular expression. | Refactor the program to use HtmlAgilityPack for parsing the exported HTML and counting <img> tags instead of a regex. | Extend the example to iterate over each <img> tag in the HTML and output its src attribute value.
// Common Searches: asp.net count image tags in HTML generated by Aspose.Cells workbook | c# get number of chart images after saving workbook as html with Aspose.Cells | using regex to count <img> elements in Aspose.Cells HTML export | replace regex with HtmlAgilityPack for img tag counting in C# | extract src attribute from images in Aspose.Cells HTML output c#
// Tags: Aspose.Cells HTML export with chart images | C# count img tags in generated HTML | regex image tag detection .NET | HtmlAgilityPack parse Aspose.Cells HTML | extract img src attributes C#

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts;   // Required for Chart and ChartType

// The sample creates a workbook, inserts a column chart, saves the workbook as HTML (which generates chart images in a subfolder), reads the HTML file, and counts the <img> tags using a case‑insensitive regex. It demonstrates how to verify that chart images are correctly exported.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["B4"].PutValue(30);

            // Add a column chart (will be rendered as an image in HTML)
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Define the HTML output path
            string htmlPath = Path.Combine(Path.GetTempPath(), "workbook.html");

            // Save the workbook as HTML (images will be generated in a subfolder)
            workbook.Save(htmlPath, SaveFormat.Html);

            // Ensure the HTML file was created
            if (!File.Exists(htmlPath))
                throw new FileNotFoundException("HTML file was not generated.", htmlPath);

            // Read the generated HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // Count the number of <img> tags using a simple regex (case‑insensitive)
            int imgTagCount = Regex.Matches(htmlContent, "<img\\b", RegexOptions.IgnoreCase).Count;

            // Output the result
            Console.WriteLine($"Number of <img> tags in the HTML: {imgTagCount}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
