// Title: Export Aspose.Cells Workbook to HTML with External CSS and Verify No Inline Styles (C#)
// Description: Creates a workbook, applies bold red formatting, saves it as HTML using HtmlSaveOptions with external CSS (DisableCss = false), reads the output file, and uses regular expressions to confirm that no inline style attributes remain.
// Keywords: Aspose.Cells HTML export | C# external CSS | HtmlSaveOptions DisableCss false | validate HTML no inline styles | regex detect style attribute | Aspose.Cells workbook to HTML | clean HTML from Excel
// Common Searches: Aspose.Cells save workbook as HTML with external CSS | C# check generated HTML for style attributes | HtmlSaveOptions DisableCss example | remove inline styles from Aspose.Cells HTML output | regex to find style attribute in HTML C#
// Developer Intent: Confirm that the HTML generated by Aspose.Cells uses only external CSS and does not contain any inline style attributes.
// Use Cases: Publish Excel data as clean, stylesheet‑driven web pages. | Automated test in CI pipeline to ensure HTML export compliance. | Utility to audit existing HTML files for unwanted inline styles. | Integration where corporate style guidelines forbid inline CSS.
// AI Prompts: Generate C# code that exports an Aspose.Cells workbook to HTML using external CSS and then scans the file for any remaining 'style' attributes. | Create a method that returns a list of HTML element names that contain a 'style' attribute using regular expressions. | Explain how HtmlSaveOptions.DisableCss influences the presence of inline styles in the exported HTML.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

namespace AsposeCellsHtmlValidation
{
    // Creates a workbook, applies bold red formatting, saves it as HTML using HtmlSaveOptions with external CSS (DisableCss = false), reads the output file, and uses regular expressions to confirm that no inline style attributes remain.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add some formatted data
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Bold Red Text");
                Style style = sheet.Cells["A1"].GetStyle();
                style.Font.IsBold = true;
                style.Font.Color = System.Drawing.Color.Red;
                sheet.Cells["A1"].SetStyle(style);

                // Configure HTML save options to use external CSS (no inline styles)
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    DisableCss = false // Use external CSS, not inline style attributes
                };

                // Save the workbook as HTML
                string htmlPath = "output.html";
                workbook.Save(htmlPath, htmlOptions);

                // Verify the HTML file exists before processing
                if (!File.Exists(htmlPath))
                {
                    Console.WriteLine($"Error: HTML file '{htmlPath}' was not created.");
                    return;
                }

                // Load the generated HTML content
                string htmlContent = File.ReadAllText(htmlPath);

                // Search for any 'style' attribute using a simple regex
                bool hasInlineStyle = Regex.IsMatch(htmlContent, @"\bstyle\s*=", RegexOptions.IgnoreCase);

                // Optionally, list occurrences (simple approach)
                if (hasInlineStyle)
                {
                    Console.WriteLine("Inline style attributes found in the generated HTML:");
                    foreach (Match match in Regex.Matches(htmlContent, @"<[^>]*\bstyle\s*=\s*[""'][^""']*[""'][^>]*>", RegexOptions.IgnoreCase))
                    {
                        // Extract the tag name for reporting
                        string tag = Regex.Match(match.Value, @"^<\s*([a-zA-Z0-9]+)").Groups[1].Value;
                        Console.WriteLine($"< {tag} > contains inline style.");
                    }
                }

                // Report the validation result
                if (hasInlineStyle)
                {
                    Console.WriteLine("Validation failed: Inline style attributes exist when CSS is disabled.");
                }
                else
                {
                    Console.WriteLine("Validation passed: No inline style attributes found when CSS is disabled.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
        }
    }
}
