// Title: Aspose.Cells for .NET: Export Workbook to HTML with and without Excluding Unused Styles (C#)
// Description: Demonstrates how to save an Excel workbook as HTML twice using Aspose.Cells: once with HtmlSaveOptions.ExcludeUnusedStyles set to false to keep every defined style, and once with the default true setting to omit unused styles, enabling a direct comparison of full‑style versus reduced‑style HTML output.
// Keywords: Aspose.Cells HTML export | ExcludeUnusedStyles false | C# Excel to HTML | Aspose.Cells HtmlSaveOptions | full style HTML Aspose | reduced style HTML Aspose | compare HTML size Aspose.Cells | .NET Excel to web | style optimization Aspose.Cells | generate HTML from workbook C#
// Common Searches: Aspose.Cells export HTML all styles C# | HtmlSaveOptions ExcludeUnusedStyles example | How to keep unused styles in HTML output Aspose | Compare full and minimized HTML from Excel using Aspose.Cells | C# generate HTML from workbook with full CSS
// Developer Intent: Create two HTML files from the same workbook—one preserving every cell style and another omitting unused styles—to evaluate style completeness and file size differences.
// Use Cases: Visual regression testing of HTML exports with full versus optimized CSS | Documentation showing the impact of ExcludeUnusedStyles on generated HTML | Performance tuning by measuring file‑size reduction when unused styles are excluded
// AI Prompts: Write C# code that uses Aspose.Cells to export a workbook to HTML while retaining all cell styles, then export again with unused styles excluded. | Explain the effect of HtmlSaveOptions.ExcludeUnusedStyles on the CSS generated by Aspose.Cells HTML export. | Provide a step‑by‑step guide to compare file size and CSS content of full_styles.html and reduced_styles.html produced by Aspose.Cells.

using System;
using Aspose.Cells;
using System.Drawing;

// Demonstrates how to save an Excel workbook as HTML twice using Aspose.Cells: once with HtmlSaveOptions.ExcludeUnusedStyles set to false to keep every defined style, and once with the default true setting to omit unused styles, enabling a direct comparison of full‑style versus reduced‑style HTML output.
class HtmlExportExample
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet worksheet = workbook.Worksheets[0];

        // Add sample data with different styles
        Cell cellA1 = worksheet.Cells["A1"];
        cellA1.PutValue("Styled Text 1");
        Style style1 = workbook.CreateStyle();
        style1.Font.Color = Color.Red;
        style1.Font.IsBold = true;
        cellA1.SetStyle(style1);

        Cell cellA2 = worksheet.Cells["A2"];
        cellA2.PutValue("Styled Text 2");
        Style style2 = workbook.CreateStyle();
        style2.Font.Name = "Times New Roman";
        style2.Font.Size = 14;
        style2.Font.IsItalic = true;
        cellA2.SetStyle(style2);

        // Save HTML with all styles retained (ExcludeUnusedStyles = false)
        HtmlSaveOptions fullStyleOptions = new HtmlSaveOptions();
        fullStyleOptions.ExcludeUnusedStyles = false;
        workbook.Save("full_styles.html", fullStyleOptions);

        // Save HTML with unused styles excluded (default behavior)
        HtmlSaveOptions reducedStyleOptions = new HtmlSaveOptions();
        reducedStyleOptions.ExcludeUnusedStyles = true; // can be omitted as true is default
        workbook.Save("reduced_styles.html", reducedStyleOptions);
    }
}
