// Title: Export Excel to HTML with a Custom TableCssId and Isolated CSS Using Aspose.Cells for .NET
// Description: C# sample that creates a workbook, assigns a custom TableCssId ("customTable") via HtmlSaveOptions, injects prefixed CSS rules, saves the file as HTML, and uses regular expressions to confirm the custom ID appears and generic .td/.tr selectors are absent, preventing style collisions on shared pages.
// Keywords: Aspose.Cells | HtmlSaveOptions | TableCssId | custom CSS | prevent CSS collisions | C# export Excel to HTML | HTML table identifier | regex validation | unique table id
// Common Searches: Aspose.Cells set TableCssId | HTML export avoid CSS class conflict | Add custom CSS to Aspose.Cells HTML output | Validate custom TableCssId in generated HTML | C# example export Excel to HTML with unique table id
// Developer Intent: Assign a custom TableCssId when exporting Excel to HTML and ensure default CSS classes do not clash with user‑defined styles.
// Use Cases: Generate HTML reports where the table needs a unique identifier to coexist with other page styles. | Apply project‑specific CSS by targeting prefixed selectors such as .customTable‑td and .customTable‑th. | Automate testing of the exported HTML to verify that only prefixed CSS classes exist. | Integrate Excel‑to‑HTML conversion into web applications without risking global style overrides.
// AI Prompts: Write C# code that uses Aspose.Cells HtmlSaveOptions to set TableCssId = "myTable" and adds custom CSS for .myTable‑td and .myTable‑th. | Create a method that loads the saved HTML file and uses regex to confirm the custom TableCssId is present and generic .td/.tr selectors are missing. | Explain how TableCssId influences the CSS selectors generated by Aspose.Cells during HTML export and why it helps avoid style collisions.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // C# sample that creates a workbook, assigns a custom TableCssId ("customTable") via HtmlSaveOptions, injects prefixed CSS rules, saves the file as HTML, and uses regular expressions to confirm the custom ID appears and generic .td/.tr selectors are absent, preventing style collisions on shared pages.
    class Program
    {
        static void Main()
        {
            // 1. Create a new workbook and add some sample data.
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("Alice");
            sheet.Cells["B3"].PutValue(25);

            // 2. Configure HTML save options.
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Set a custom TableCssId to avoid class name collisions.
            saveOptions.TableCssId = "customTable";

            // Optional: add a custom CSS rule that uses the TableCssId prefix.
            // This demonstrates that the generated HTML will reference the custom prefix.
            saveOptions.CssStyles = @"
                .customTable-td {
                    background-color: #e8f4ff;
                    padding: 5px;
                }
                .customTable-th {
                    background-color: #c0d8ff;
                    font-weight: bold;
                }";

            // 3. Save the workbook as HTML.
            string outputPath = "output.html";
            workbook.Save(outputPath, saveOptions);
            Console.WriteLine($"HTML file saved to: {Path.GetFullPath(outputPath)}");

            // 4. Verify that the TableCssId attribute is present and that no default CSS class names collide.
            string htmlContent = File.ReadAllText(outputPath);

            // Check for the TableCssId attribute.
            bool hasTableCssId = Regex.IsMatch(htmlContent, @"TableCssId\s*=\s*[""']customTable[""']", RegexOptions.IgnoreCase);
            Console.WriteLine($"TableCssId attribute present: {hasTableCssId}");

            // Simple collision check: ensure that the custom prefix is used in CSS class names.
            bool usesCustomPrefixInCss = Regex.IsMatch(htmlContent, @"\.customTable-(td|th)", RegexOptions.IgnoreCase);
            Console.WriteLine($"Custom CSS prefix used in generated styles: {usesCustomPrefixInCss}");

            // Ensure that generic class names like '.tr' or '.td' without the prefix are not present.
            bool genericTdExists = Regex.IsMatch(htmlContent, @"\.td\s*{", RegexOptions.IgnoreCase);
            bool genericTrExists = Regex.IsMatch(htmlContent, @"\.tr\s*{", RegexOptions.IgnoreCase);
            Console.WriteLine($"Generic .td class found (should be false): {genericTdExists}");
            Console.WriteLine($"Generic .tr class found (should be false): {genericTrExists}");
        }
    }
}
