// Title: Add a custom CSS class to the header row when exporting an Aspose.Cells worksheet to a single‑file HTML document in C#
// AI Prompts: Generate HTML from a workbook using HtmlSaveOptions with ExportActiveWorksheetOnly and ExportImagesAsBase64, then capture the output as a string. | Apply a regular expression to the first <tr> element after the <table> tag and inject a custom CSS class attribute. | Insert a <style> block that defines the custom header class before the closing </head> tag and save the modified HTML to a file.
// Common Searches: how to add a CSS class to the first table row in HTML generated by Aspose.Cells C# | Aspose.Cells export worksheet to single HTML file with embedded CSS | C# regex replace first <tr> tag in Aspose.Cells HTML output | embed custom header style in HTML export from Aspose.Cells workbook
// Tags: Aspose.Cells HTML export custom header class | C# regex modify exported HTML table row | embed CSS in single-file HTML from Excel | HtmlSaveOptions ExportActiveWorksheetOnly single file | add CSS class to Excel header row in HTML

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The program creates a workbook, fills header and data cells, exports the active worksheet to a single HTML string using HtmlSaveOptions, uses a regex to add a custom CSS class to the first <tr>, injects a style block for that class before </head>, and writes the modified HTML to disk.
class HtmlExportWithHeaderClass
{
    static void Main()
    {
        try
        {
            // Create a new workbook and access the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate header row
            sheet.Cells["A1"].PutValue("Product");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["C1"].PutValue("Price");

            // Populate some sample data
            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["C2"].PutValue(0.5);

            sheet.Cells["A3"].PutValue("Banana");
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["C3"].PutValue(0.3);

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportActiveWorksheetOnly = true,
                // Keep the HTML in a single file (no external CSS or images)
                ExportImagesAsBase64 = true
                // ExportChartImageFormat and ExportImagesToDisk are not required for this scenario
            };

            // Save the workbook to HTML using a memory stream
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, htmlOptions);
                htmlStream.Position = 0;

                // Read the generated HTML into a string
                string htmlContent = new StreamReader(htmlStream, Encoding.UTF8).ReadToEnd();

                // Add a custom CSS class to the first <tr> (header row)
                // This regex finds the first <tr> that follows a <table> tag
                string pattern = @"(<table[^>]*>\s*)(<tr\b[^>]*>)";
                string replacement = "$1<tr class=\"custom-header\">";
                string modifiedHtml = Regex.Replace(htmlContent, pattern, replacement, RegexOptions.IgnoreCase, TimeSpan.FromSeconds(1));

                // Optionally, embed a simple CSS rule for the custom class
                string styleBlock = "<style>.custom-header { background-color:#f0f0f0; font-weight:bold; }</style>";
                // Insert the style block just before the closing </head> tag
                modifiedHtml = Regex.Replace(modifiedHtml, @"</head>", styleBlock + "\n</head>", RegexOptions.IgnoreCase);

                // Write the modified HTML to a file
                string outputPath = "ExportedWithHeaderClass.html";
                File.WriteAllText(outputPath, modifiedHtml, Encoding.UTF8);
                Console.WriteLine($"HTML export completed with custom header class. File saved to: {Path.GetFullPath(outputPath)}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred during HTML export:");
            Console.WriteLine(ex.Message);
        }
    }
}
