// Title: Add a custom CSS class to header rows of an HTML file exported from Aspose.Cells in C#
// AI Prompts: Generate C# code that saves a Workbook as HTML with Aspose.Cells, then uses a regular expression to add a specified CSS class to any <tr> element that contains <th> cells. | Write a method that accepts the HTML string produced by Aspose.Cells and returns a modified version where header rows (<tr> with <th>) have a class attribute injected. | Show how to export an Excel worksheet to HTML, apply a custom CSS class to the header row, and write both the original and styled HTML files to disk using C#.
// Common Searches: how to inject a CSS class into header rows of HTML generated by Aspose.Cells using C# | C# regex pattern to add class attribute to <tr> that contains <th> in exported HTML | Aspose.Cells SaveFormat.Html customize table header styling programmatically | modify Aspose.Cells HTML output to style the first row with a custom class | add custom CSS to Excel header row after exporting to HTML with Aspose.Cells
// Tags: Aspose.Cells HTML export custom header class | C# regex inject class into <tr> with <th> | SaveFormat.Html workbook export styling | modify Aspose.Cells generated HTML using Regex | custom CSS for header rows in Aspose.Cells HTML

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The example creates a workbook, populates a header row and data rows, saves it as HTML, reads the generated markup, and uses a case‑insensitive regular expression to locate <tr> elements that contain <th> cells. It then injects a custom CSS class (my‑header) into those rows, writes the modified HTML to a new file, and outputs the paths of both the original and modified files.
class HtmlExportWithHeaderClass
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate header row (row 0) and some data rows
        sheet.Cells["A1"].PutValue("ID");
        sheet.Cells["B1"].PutValue("Name");
        sheet.Cells["C1"].PutValue("Score");

        sheet.Cells["A2"].PutValue(1);
        sheet.Cells["B2"].PutValue("Alice");
        sheet.Cells["C2"].PutValue(85);

        sheet.Cells["A3"].PutValue(2);
        sheet.Cells["B3"].PutValue("Bob");
        sheet.Cells["C3"].PutValue(92);

        // Save the workbook as HTML to a temporary file
        string htmlPath = Path.Combine(Path.GetTempPath(), "ExportedTable.html");
        workbook.Save(htmlPath, SaveFormat.Html);

        // Read the generated HTML content
        string htmlContent = File.ReadAllText(htmlPath, Encoding.UTF8);

        // Define a CSS class name to be added to header rows
        const string headerCssClass = "my-header";

        // Use a regular expression to find <tr> elements that contain <th> cells
        // and add the CSS class to the <tr> tag.
        // This pattern matches a <tr> tag that directly contains a <th> tag.
        string pattern = @"<tr(?=[^>]*>\s*<th)";
        string replacement = $"<tr class=\"{headerCssClass}\"";

        string modifiedHtml = Regex.Replace(htmlContent, pattern, replacement, RegexOptions.IgnoreCase);

        // Optionally, write the modified HTML back to a new file
        string modifiedHtmlPath = Path.Combine(Path.GetTempPath(), "ExportedTable_WithHeaderClass.html");
        File.WriteAllText(modifiedHtmlPath, modifiedHtml, Encoding.UTF8);

        // Output paths for verification
        Console.WriteLine("Original HTML saved to: " + htmlPath);
        Console.WriteLine("Modified HTML saved to: " + modifiedHtmlPath);
    }
}
