// Title: Export Workbook with Frozen Panes to HTML and Verify Pane Positions – Aspose.Cells for .NET
// Description: Creates a 20×10 worksheet, freezes panes at cell C3 (2 rows, 2 columns), retrieves the freeze settings with GetFreezedPanes, and saves the workbook as an HTML file that preserves the frozen rows and columns.
// Keywords: Aspose.Cells | C# | freeze panes | HTML export | GetFreezedPanes | worksheet freeze verification | save as HTML | frozen rows and columns
// Common Searches: Aspose.Cells freeze panes and export to HTML | GetFreezedPanes example C# | how to verify frozen pane coordinates in Aspose.Cells | save workbook with frozen rows as HTML | C# export Excel with frozen panes to web page
// Developer Intent: Generate an HTML view of a worksheet that keeps header rows and columns fixed, and programmatically confirm the freeze configuration before publishing.
// Use Cases: Web‑based reports where header rows/columns stay visible while scrolling. | Automated tests that ensure the correct rows and columns are frozen before distribution. | Providing an Excel‑like experience in browsers for users without Office installed.
// AI Prompts: Write C# code to freeze panes at D5 with three rows and three columns, then export the workbook to HTML using Aspose.Cells. | Show how to call GetFreezedPanes after loading a workbook to validate freeze settings before HTML conversion. | Explain how the frozen pane information appears in the HTML output generated by Aspose.Cells SaveFormat.Html.

using System;
using Aspose.Cells;

namespace AsposeCellsFreezePaneHtmlDemo
{
    // Creates a 20×10 worksheet, freezes panes at cell C3 (2 rows, 2 columns), retrieves the freeze settings with GetFreezedPanes, and saves the workbook as an HTML file that preserves the frozen rows and columns.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            for (int row = 0; row < 20; row++)
            {
                for (int col = 0; col < 10; col++)
                {
                    sheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                }
            }

            // Freeze panes at cell C3 (row index 2, column index 2) with 2 frozen rows and 2 frozen columns
            sheet.FreezePanes("C3", 2, 2);

            // Verify the frozen pane information
            int frozenRow, frozenColumn, frozenRows, frozenColumns;
            bool hasFreeze = sheet.GetFreezedPanes(out frozenRow, out frozenColumn, out frozenRows, out frozenColumns);

            Console.WriteLine($"Has frozen panes: {hasFreeze}");
            if (hasFreeze)
            {
                Console.WriteLine($"Freeze position - Row: {frozenRow}, Column: {frozenColumn}");
                Console.WriteLine($"Frozen rows: {frozenRows}, Frozen columns: {frozenColumns}");
            }

            // Save the workbook as HTML to visualize the frozen panes in a web page
            workbook.Save("FrozenPanesDemo.html", SaveFormat.Html);

            Console.WriteLine("Workbook saved as HTML with frozen panes.");
        }
    }
}
