// Title: Convert an Excel workbook to a self‑contained HTML file with embedded CSS using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, saves it as HTML, and then inserts a custom <style> block into the generated file to embed CSS. | Show how to verify the source Excel file exists, export it to HTML with Aspose.Cells, and programmatically add inline style rules after the save operation. | Demonstrate a try‑catch pattern for converting Excel to HTML in C#, and explain where to place custom CSS when ExportExternalStyleSheets is unavailable.
// Common Searches: how to embed custom CSS into HTML generated by Aspose.Cells in C# | Aspose.Cells .NET export Excel to HTML without external stylesheet | add style tag to Aspose.Cells HTML output after saving workbook | C# check file existence before converting Excel to HTML with Aspose.Cells
// Tags: Aspose.Cells HTMLSaveOptions embed CSS | C# Excel to HTML conversion Aspose.Cells | inject custom stylesheet Aspose.Cells HTML output | disable external CSS Aspose.Cells export | post‑save HTML modification Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExample
{
    // The example checks that input.xlsx exists, loads it into an Aspose.Cells Workbook, uses HtmlSaveOptions to save the workbook as output.html, and notes that the current Aspose.Cells version lacks ExportExternalStyleSheets and CustomCss support, so custom CSS must be injected into the saved HTML file manually. Errors are caught and reported to the console.
    class Program
    {
        static void Main()
        {
            try
            {
                const string inputPath = "input.xlsx";
                const string outputPath = "output.html";

                // Verify that the input file exists to avoid FileNotFoundException
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook from the specified file
                Workbook workbook = new Workbook(inputPath);

                // Set up HTML export options
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
                // The properties ExportExternalStyleSheets and CustomCss are not available in this version of Aspose.Cells.
                // If custom CSS is required, it can be injected into the generated HTML after saving.

                // Save the workbook as an HTML file
                workbook.Save(outputPath, htmlOptions);
                Console.WriteLine($"Workbook successfully saved as HTML to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                // Catch any unexpected errors and display a friendly message
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
