// Title: Export an Aspose.Cells worksheet to HTML and detect inline style attributes with C#
// AI Prompts: Create a C# console program that builds a workbook with Aspose.Cells, saves the active sheet as HTML, reads the HTML into a string, and uses a regular expression to enumerate any "style" attributes present. | Adjust the HtmlSaveOptions in Aspose.Cells to prefer CSS class output, then write code that confirms the resulting HTML contains no inline style definitions and logs the verification result. | Develop a C# routine that loads an HTML file produced by Aspose.Cells, parses it with a lightweight HTML parser, and asserts that no element carries a "style" attribute when CSS export is disabled.
// Common Searches: how to export Aspose.Cells worksheet to HTML without inline style attributes in C# | C# regex to find style= attribute in HTML generated by Aspose.Cells | Aspose.Cells HtmlSaveOptions disable inline CSS and verify output | detect inline CSS in HTML saved from Aspose.Cells workbook using C#
// Tags: Aspose.Cells HTML export style attribute check | C# regular expression HTML style detection | HtmlSaveOptions ExportActiveWorksheetOnly usage | verify CSS class generation Aspose.Cells | remove inline styling from Aspose.Cells HTML output

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using System.Drawing;

// The example creates a Workbook, adds data and formatting, saves the active worksheet as HTML with HtmlSaveOptions, reads the HTML into a string, applies a regular expression to locate any inline style attributes, reports the findings, and optionally writes the HTML to a file for further inspection.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add some data
            var workbook = new Workbook();
            var sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Hello World");
            sheet.Cells["B1"].PutValue(12345);

            // Apply formatting to generate style information
            var style = sheet.Cells["A1"].GetStyle();
            style.Font.Color = Color.Red;
            sheet.Cells["A1"].SetStyle(style);

            // Configure HTML save options (inline styles will be present if the API version does not support CSS class export)
            var htmlOptions = new HtmlSaveOptions
            {
                ExportActiveWorksheetOnly = true
                // Note: ExportHtmlAsCssClass is not available in this version of Aspose.Cells.
            };

            // Save the workbook to a memory stream as HTML
            using (var ms = new MemoryStream())
            {
                workbook.Save(ms, htmlOptions);
                ms.Position = 0;

                // Read the generated HTML into a string
                string html;
                using (var reader = new StreamReader(ms))
                {
                    html = reader.ReadToEnd();
                }

                // Simple check for any inline style attributes using regex
                var styleMatches = Regex.Matches(html, @"\sstyle\s*=\s*[""'][^""']*[""']", RegexOptions.IgnoreCase);
                if (styleMatches.Count > 0)
                {
                    Console.WriteLine("Inline style attributes were found:");
                    foreach (Match match in styleMatches)
                    {
                        // Show a snippet around the match for context
                        int start = Math.Max(0, match.Index - 30);
                        int length = Math.Min(html.Length - start, match.Length + 60);
                        Console.WriteLine(html.Substring(start, length).Replace("\r", "").Replace("\n", " "));
                    }
                }
                else
                {
                    Console.WriteLine("No inline style attributes present.");
                }

                // Optionally write the HTML to a file for inspection
                string outputPath = "output.html";
                try
                {
                    File.WriteAllText(outputPath, html);
                    Console.WriteLine($"HTML written to {Path.GetFullPath(outputPath)}");
                }
                catch (Exception writeEx)
                {
                    Console.WriteLine($"Failed to write HTML file: {writeEx.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
