// Title: Export Workbook to HTML with a Custom TableCssId and Verify CSS Class Uniqueness (C# Aspose.Cells)
// Description: Shows how to set HtmlSaveOptions.TableCssId, add custom CSS, save a workbook as HTML, and programmatically confirm the TableCssId attribute and unique CSS selectors to prevent style collisions.
// Keywords: Aspose.Cells | C# | HtmlSaveOptions | TableCssId | custom CSS | HTML export | CSS class collision | regex verification | workbook to HTML | style uniqueness
// Common Searches: Aspose.Cells set custom TableCssId | add custom CSS to HTML export Aspose.Cells | prevent CSS name collisions when saving workbook as HTML | verify HTML table id in Aspose.Cells output | C# regex check for CSS selectors in generated HTML
// Developer Intent: Configure a unique TableCssId and custom CSS while exporting a workbook to HTML, then validate that the generated selectors appear exactly once and do not conflict with other page styles.
// Use Cases: Export a spreadsheet to HTML with a prefixed table ID to isolate styles on a shared page. | Inject project‑specific CSS rules into the Aspose.Cells HTML output and ensure they are applied correctly. | Automate a test that reads the saved HTML, checks for the TableCssId attribute, and confirms that custom CSS selectors are defined only once. | Combine multiple Aspose.Cells HTML exports on a single web page without style interference by using distinct TableCssId values.
// AI Prompts: Write C# code using Aspose.Cells to export a workbook to HTML with a custom TableCssId and add custom CSS rules, then verify the selectors with regex. | Create a unit test in C# that loads the HTML generated by Aspose.Cells, asserts the presence of the TableCssId attribute on the <table> element, and ensures custom CSS classes are not duplicated. | Explain how HtmlSaveOptions.TableCssId and CssStyles work together in Aspose.Cells to avoid CSS naming conflicts in the resulting HTML.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// Shows how to set HtmlSaveOptions.TableCssId, add custom CSS, save a workbook as HTML, and programmatically confirm the TableCssId attribute and unique CSS selectors to prevent style collisions.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];
        worksheet.Cells["A1"].PutValue("Name");
        worksheet.Cells["B1"].PutValue("Age");
        worksheet.Cells["A2"].PutValue("John");
        worksheet.Cells["B2"].PutValue(30);
        worksheet.Cells["A3"].PutValue("Alice");
        worksheet.Cells["B3"].PutValue(25);

        // Configure HTML save options with a custom TableCssId to avoid CSS name collisions
        HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
        saveOptions.TableCssId = "customTable"; // custom prefix for generated CSS selectors

        // Add additional CSS that uses the custom prefix; this ensures uniqueness
        saveOptions.CssStyles = @"
            .customTable-tr { background-color:#e0f7fa; }
            .customTable-td { border:1px solid #006064; }
        ";

        // Save the workbook as HTML using the configured options
        string htmlPath = "output.html";
        workbook.Save(htmlPath, saveOptions);

        // ----- Verification -----
        // Load the generated HTML file
        string htmlContent = File.ReadAllText(htmlPath);

        // Verify that the TableCssId attribute is present in the <table> element
        bool hasTableCssId = htmlContent.Contains($"TableCssId=\"{saveOptions.TableCssId}\"");
        Console.WriteLine($"TableCssId attribute present: {hasTableCssId}");

        // Verify that the custom CSS classes are defined and do not collide with other styles
        int customTrClassCount = Regex.Matches(htmlContent, @"\.customTable-tr\b").Count;
        int customTdClassCount = Regex.Matches(htmlContent, @"\.customTable-td\b").Count;
        Console.WriteLine($".customTable-tr occurrences: {customTrClassCount}");
        Console.WriteLine($".customTable-td occurrences: {customTdClassCount}");

        // Simple collision check: ensure each custom class appears at least once and only once in the style block
        bool noCollision = customTrClassCount == 1 && customTdClassCount == 1;
        Console.WriteLine($"No CSS class name collisions detected: {noCollision}");
    }
}
