// Title: Create an HTML file from a workbook with a list‑type data validation dropdown and confirm it renders as a <select> element using Aspose.Cells for C#
// AI Prompts: Write a C# console program that builds a workbook, adds a list validation referencing cells A1:A3 to cell B1, saves the workbook as HTML, and returns true if the generated HTML contains a <select> tag. | Generate C# code using Aspose.Cells to populate a range, apply a dropdown data validation, export the sheet to HTML, and output whether the dropdown appears as a <select> element.
// Common Searches: asp.net aspose.cells export list validation to html and detect select tag | c# verify dropdown rendered as <select> in html generated by Aspose.Cells | how to save Excel workbook with data validation list as html using Aspose.Cells | c# check aspose.cells html output for data validation dropdown element | aspose.cells list validation html export example c#
// Tags: Aspose.Cells export workbook to HTML with list validation | C# add data validation list to worksheet | HTML output verify select element from Excel validation | Aspose.Cells render data validation as HTML select | C# workbook to HTML dropdown verification

using System;
using System.IO;
using Aspose.Cells;

// Demonstrates creating a workbook, filling A1‑A3, applying a list‑type data validation to B1, saving the workbook as HTML, and checking the generated file for a <select> element.
class DataValidationHtmlDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook.
            Workbook workbook = new Workbook();

            // Access the first worksheet.
            Worksheet sheet = workbook.Worksheets[0];

            // Populate a range with list items for the dropdown.
            sheet.Cells["A1"].PutValue("Option 1");
            sheet.Cells["A2"].PutValue("Option 2");
            sheet.Cells["A3"].PutValue("Option 3");

            // Add a data validation of type List to cell B1, referencing the list range A1:A3.
            ValidationCollection validations = sheet.Validations;

            // Define the validation area for cell B1.
            CellArea validationArea = new CellArea
            {
                StartRow = 0,
                StartColumn = 1,
                EndRow = 0,
                EndColumn = 1
            };

            // Add validation using the CellArea overload.
            int validationIndex = validations.Add(validationArea);
            Validation validation = validations[validationIndex];

            // Configure validation as a dropdown list.
            validation.Type = ValidationType.List;
            validation.Operator = OperatorType.Between; // Required but not used for List type.
            validation.Formula1 = "=$A$1:$A$3"; // Source range for the dropdown.
            validation.ShowError = true;
            validation.ErrorTitle = "Invalid Selection";
            validation.ErrorMessage = "Please select a value from the list.";
            validation.AlertStyle = ValidationAlertType.Stop;

            // Input (prompt) settings.
            validation.ShowInput = true;
            validation.InputTitle = "Select an option";
            validation.InputMessage = "Choose a value from the dropdown.";

            // Define the output HTML file path.
            string htmlPath = Path.Combine(Directory.GetCurrentDirectory(), "WorkbookWithDropdown.html");

            // Save the workbook as HTML. Aspose.Cells will render the data validation as a <select> element.
            workbook.Save(htmlPath, SaveFormat.Html);

            // Load the generated HTML content if the file exists.
            string htmlContent = File.Exists(htmlPath) ? File.ReadAllText(htmlPath) : string.Empty;

            // Verify that the HTML contains a <select> element (case‑insensitive search).
            bool containsSelect = htmlContent.IndexOf("<select", StringComparison.OrdinalIgnoreCase) >= 0;

            // Output verification result.
            Console.WriteLine("HTML file generated at: " + htmlPath);
            Console.WriteLine("Dropdown rendered as <select> element: " + (containsSelect ? "YES" : "NO"));
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
