// Title: Export an Excel workbook to HTML with a custom TableCssId and hide overlaid content using CrossHideRight in Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an .xlsx file, enables HtmlSaveOptions.CrossHideRight, sets HtmlSaveOptions.TableCssId to a specific identifier, and saves the workbook as an HTML document with Aspose.Cells. | Show a step‑by‑step example of applying a custom CSS ID to the generated HTML table while suppressing overlaid cells during Excel‑to‑HTML conversion using Aspose.Cells.
// Common Searches: Aspose.Cells CrossHideRight export to HTML example C# | how to set TableCssId in HtmlSaveOptions for Aspose.Cells | hide overlaid cells when converting Excel to HTML with Aspose.Cells | custom CSS ID for HTML table generated by Aspose.Cells .NET | export workbook to HTML with custom table identifier and hidden overlays Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions TableCssId | Aspose.Cells CrossHideRight HTML export | C# export Excel to HTML with custom table id | hide overlaid cells Aspose.Cells HTML | custom CSS styling for Aspose.Cells HTML table

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // The example loads an Excel workbook, configures HtmlSaveOptions to assign a custom CSS ID (myTableStyle) to the output HTML table, enables CrossHideRight to suppress overlaid content, and saves the result as an HTML file using Aspose.Cells for .NET.
    class ExportHtmlWithCrossHideRight
    {
        static void Main()
        {
            try
            {
                string inputPath = "input.xlsx";
                string outputPath = "output.html";

                // Verify that the input workbook exists
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook
                Workbook workbook = new Workbook(inputPath);

                // Configure HTML save options
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions
                {
                    // Apply a custom CSS ID to the generated HTML table for styling
                    TableCssId = "myTableStyle"
                };

                // Export the workbook to HTML
                workbook.Save(outputPath, htmlOptions);
                Console.WriteLine($"Workbook successfully exported to HTML: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
