// Title: Use a custom IFilePathProvider to generate safe per‑worksheet HTML file names when exporting a workbook with Aspose.Cells for .NET
// AI Prompts: Implement a class that inherits IFilePathProvider and returns sanitized file names for each worksheet during HTML export. | Set HtmlSaveOptions.IsFullPathLink to true and assign the custom IFilePathProvider to preserve navigation links between worksheet HTML files. | Modify the export routine to load the workbook, apply the custom file path provider, and save the workbook as a main HTML file with linked worksheet pages.
// Common Searches: Aspose.Cells how to rename worksheet HTML files during export | C# custom IFilePathProvider example for HTML save options | preserve navigation links between generated HTML pages Aspose.Cells | replace invalid characters in HTML file names when exporting Excel with Aspose.Cells
// Tags: IFilePathProvider implementation for Aspose.Cells HTML export | per‑worksheet HTML file naming Aspose.Cells | full‑path link preservation Aspose.Cells HTML | sanitize HTML file names .NET | HtmlSaveOptions FilePathProvider configuration

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Custom implementation of IFilePathProvider to control HTML file names per worksheet
    // Loads an Excel workbook, configures HtmlSaveOptions to export all worksheets with full‑path links, assigns a CustomFilePathProvider that sanitizes each worksheet's HTML file name, and saves the workbook as a main HTML file containing navigation links to the generated per‑worksheet pages.
    public class CustomFilePathProvider : IFilePathProvider
    {
        // Called for each generated HTML file; returns a safe file name in the current directory.
        public string GetFullName(string fileName)
        {
            string safeName = MakeSafeFileName(Path.GetFileNameWithoutExtension(fileName));
            string extension = Path.GetExtension(fileName);
            return $"{safeName}{extension}";
        }

        // Replace invalid file name characters with an underscore.
        private string MakeSafeFileName(string name)
        {
            foreach (char invalidChar in Path.GetInvalidFileNameChars())
            {
                name = name.Replace(invalidChar, '_');
            }
            return name;
        }
    }

    class Program
    {
        static void Main()
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.html";

            try
            {
                // Verify that the input workbook exists.
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file \"{inputPath}\" not found.");
                    return;
                }

                // Load the workbook.
                Workbook workbook = new Workbook(inputPath);

                // Configure HTML save options.
                HtmlSaveOptions saveOptions = new HtmlSaveOptions
                {
                    // Export all worksheets (default behavior).
                    ExportActiveWorksheetOnly = false,

                    // Preserve relative links between generated HTML files.
                    IsFullPathLink = true,

                    // Assign the custom file path provider.
                    FilePathProvider = new CustomFilePathProvider()
                };

                // Save the workbook as HTML. The main file (output.html) will contain
                // navigation links to the per‑worksheet files generated by the provider.
                workbook.Save(outputPath, saveOptions);
                Console.WriteLine($"Workbook successfully exported to \"{outputPath}\".");
            }
            catch (Exception ex)
            {
                // Catch any unexpected errors.
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
