// Title: Export an Excel workbook to HTML with cell comments and a custom TableCssId using Aspose.Cells for .NET
// AI Prompts: Write C# code that saves a Workbook as HTML, includes cell comments, and sets the TableCssId property so the table can be styled with CSS. | Show how to use Aspose.Cells HtmlSaveOptions to embed comments in the HTML output and define a CSS identifier for the generated table.
// Common Searches: Aspose.Cells C# export workbook to HTML with comments visible | How to set TableCssId in HtmlSaveOptions for custom CSS styling | Include cell comments when saving Excel as HTML using Aspose.Cells .NET | Apply custom CSS ID to HTML table generated by Aspose.Cells export
// Tags: html export cell comments Aspose.Cells | HTML table identifier Aspose.Cells HtmlSaveOptions | apply CSS styling to exported HTML table Aspose.Cells | preserve comments in HTML output Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook, adds sample data and a comment to cell B2, configures HtmlSaveOptions with TableCssId set to "myTable" (comments are included by default), and saves the workbook as ExportedWithComments.html.
class ExportWithComments
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet and set its name
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "DataSheet";

            // Populate some cells with sample data
            sheet.Cells["A1"].PutValue("ID");
            sheet.Cells["B1"].PutValue("Name");
            sheet.Cells["A2"].PutValue(1);
            sheet.Cells["B2"].PutValue("Alice");
            sheet.Cells["A3"].PutValue(2);
            sheet.Cells["B3"].PutValue("Bob");

            // Add a comment to cell B2
            int commentIndex = sheet.Comments.Add("B2");
            Comment comment = sheet.Comments[commentIndex];
            comment.Note = "Employee name";

            // Configure HTML save options
            HtmlSaveOptions options = new HtmlSaveOptions
            {
                // Assign an ID to the generated HTML table
                TableCssId = "myTable"
                // Note: IncludeCellComments and CommentsCssClass are not available in this version of Aspose.Cells.
                // Comments are included by default in the exported HTML.
            };

            // Define output file path
            string outputPath = "ExportedWithComments.html";

            // Save the workbook to HTML
            workbook.Save(outputPath, options);

            Console.WriteLine($"Workbook successfully exported to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
