// Title: Export Excel to HTML with timestamped filename & custom TableCssId using Aspose.Cells for .NET
// Description: Shows how to build a workbook, set HtmlSaveOptions.TableCssId, create a yyyyMMdd_HHmmss timestamp, and save the file as WorkbookExport_<timestamp>.html.
// Keywords: Aspose.Cells HTML export | C# timestamped filename | TableCssId prefix | HtmlSaveOptions example | Excel to HTML .NET | versioned HTML export
// Common Searches: Aspose.Cells add timestamp to HTML file name | Set TableCssId for HTML export Aspose.Cells C# | Generate versioned HTML from Excel workbook | HtmlSaveOptions TableCssId usage example | C# save workbook as HTML with date time suffix
// Developer Intent: Generate an HTML file from an Excel workbook that includes a unique timestamp in the filename and a custom TableCssId for version tracking.
// Use Cases: Automated daily reports with distinct filenames to avoid overwrites. | Emailing HTML exports where each attachment is uniquely identified by export time. | Applying a consistent CSS ID prefix across multiple HTML exports for centralized styling and version control.
// AI Prompts: Write C# code that saves an Aspose.Cells workbook as HTML with a custom TableCssId and a filename containing the current date and time. | Explain how to modify the timestamp format in the HTML filename generated by Aspose.Cells. | Demonstrate how to confirm that the TableCssId prefix appears correctly in the exported HTML file.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Shows how to build a workbook, set HtmlSaveOptions.TableCssId, create a yyyyMMdd_HHmmss timestamp, and save the file as WorkbookExport_<timestamp>.html.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("Alice");
            sheet.Cells["B3"].PutValue(25);

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);

            // Set a prefix for CSS IDs to track export versions (e.g., "export_v1")
            saveOptions.TableCssId = "export_v1";

            // Generate a timestamp string for the output file name
            string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");

            // Build the output file name with the timestamp
            string outputFile = $"WorkbookExport_{timestamp}.html";

            // Save the workbook as HTML using the configured options
            workbook.Save(outputFile, saveOptions);

            Console.WriteLine($"HTML file saved as: {outputFile}");
            Console.WriteLine($"TableCssId prefix applied: {saveOptions.TableCssId}");
        }
    }
}
