// Title: Convert Excel header row to <h1> tags when exporting the active worksheet to HTML using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an Excel file with Aspose.Cells, saves only the active sheet as HTML, and transforms the first row cells into <h1> elements. | Show how to locate the first <tr> element in the HTML generated by Aspose.Cells and replace each <td> in that row with an <h1> tag using regular expressions. | Provide a complete example that writes the modified HTML (with header cells as <h1>) to an output file after exporting from Aspose.Cells.
// Common Searches: aspnet convert first row of exported Excel HTML to h1 tags | how to change header cells to heading tags in Aspose.Cells HTML output | export only active worksheet to HTML and customize header row C# | replace td elements with h1 in Aspose.Cells generated HTML | map Excel column titles to HTML h1 using Aspose.Cells for .NET
// Tags: Aspose.Cells export active worksheet to HTML | replace first row cells with h1 tags C# | modify Aspose.Cells HTML output using regex | map Excel header to HTML heading Aspose.Cells | custom HTML save options Aspose.Cells .NET

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The program loads an Excel workbook with Aspose.Cells, saves only the active worksheet as HTML, uses a regular expression to locate the first <tr> row, replaces each <td> in that row with an <h1> tag, and writes the resulting HTML to an output file.
class Program
{
    static void Main()
    {
        // Load the workbook from a file.
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options to export only the active worksheet.
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
        htmlOptions.ExportActiveWorksheetOnly = true;

        // Save the workbook to a memory stream as HTML.
        using (MemoryStream htmlStream = new MemoryStream())
        {
            workbook.Save(htmlStream, htmlOptions);
            string htmlContent = Encoding.UTF8.GetString(htmlStream.ToArray());

            // Locate the first <tr> element (the first row) in the generated HTML.
            Regex firstRowRegex = new Regex(@"<tr[^>]*>(.*?)</tr>", RegexOptions.Singleline);
            Match firstRowMatch = firstRowRegex.Match(htmlContent);

            if (firstRowMatch.Success)
            {
                // Extract the inner HTML of the first row.
                string rowInnerHtml = firstRowMatch.Groups[1].Value;

                // Replace each <td>...</td> with <h1>...</h1> to turn headings into <h1> tags.
                string transformedRow = Regex.Replace(
                    rowInnerHtml,
                    @"<td[^>]*>(.*?)</td>",
                    m => $"<h1>{m.Groups[1].Value}</h1>",
                    RegexOptions.Singleline);

                // Rebuild the HTML with the transformed first row.
                htmlContent = htmlContent.Substring(0, firstRowMatch.Index) +
                              $"<tr>{transformedRow}</tr>" +
                              htmlContent.Substring(firstRowMatch.Index + firstRowMatch.Length);
            }

            // Write the final HTML to an output file.
            File.WriteAllText("output.html", htmlContent, Encoding.UTF8);
        }
    }
}
