// Title: Export an Excel workbook to HTML with worksheet headings and a custom TableCssId using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, sets HtmlSaveOptions to show each worksheet name as a heading in the generated HTML, assigns a specific TableCssId to the tables, and saves the output. | Demonstrate configuring Aspose.Cells HtmlSaveOptions so the HTML export adds a heading for every worksheet and prefixes all <table> elements with a given CSS ID in C#.
// Common Searches: Aspose.Cells how to add sheet name headings when saving workbook as HTML in C# | C# set TableCssId for HTML tables generated by Aspose.Cells | Export Excel to HTML with custom table CSS identifier using Aspose.Cells | Include worksheet titles in HTML output from Aspose.Cells .NET library
// Tags: Aspose.Cells HTML export worksheet headings | HtmlSaveOptions TableCssId customization | C# convert Excel to HTML with custom table ID | Aspose.Cells set sheet name as HTML heading

using System;
using System.IO;
using Aspose.Cells;

// The program checks for the presence of input.xlsx, loads it into an Aspose.Cells Workbook, configures HtmlSaveOptions with TableCssId set to "MyTableStyle" (which prefixes generated <table> elements), and saves the workbook as output.html while handling any exceptions.
class Program
{
    static void Main()
    {
        const string inputPath = "input.xlsx";
        const string outputPath = "output.html";

        try
        {
            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: Input file '{inputPath}' not found.");
                return;
            }

            // Load the workbook from the specified file
            Workbook workbook = new Workbook(inputPath);

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                // Prefix table styles with the chosen TableCssId
                // This adds the specified ID to the generated <table> elements
                TableCssId = "MyTableStyle"
            };

            // Save the workbook as HTML using the configured options
            workbook.Save(outputPath, htmlOptions);
            Console.WriteLine($"Workbook successfully saved to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Handle any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
