// Title: Aspose.Cells for .NET – Export Excel Cell Comments to HTML with TableCssId Styling (C#)
// Description: C# example that creates a workbook, adds a comment to cell A1, and saves the file as HTML. The HtmlSaveOptions are set to export comments in‑place, enable comment output, and apply a TableCssId prefix so the generated table and comment elements inherit custom CSS selectors.
// Keywords: Aspose.Cells export comments HTML | HtmlSaveOptions TableCssId | PrintCommentsType PrintInPlace | C# export Excel to HTML with comments | custom CSS ID for Aspose.Cells HTML output | .NET Excel to HTML conversion | Aspose.Cells HTML styling USA | Aspose.Cells Europe developers
// Common Searches: export Excel comments to HTML using Aspose.Cells | how to set TableCssId in HtmlSaveOptions | Aspose.Cells C# export comments in place | apply custom CSS to HTML tables generated by Aspose.Cells | include cell notes in HTML output Aspose
// Developer Intent: Generate an HTML file from an Excel workbook where cell comments appear next to their cells and the table uses a custom CSS ID prefix.
// Use Cases: Building web‑based reports that display Excel comments inline with styled tables. | Creating documentation portals where each worksheet is rendered as HTML with a consistent CSS theme. | Automating conversion of spreadsheets to HTML emails that require visible comments and custom styling.
// AI Prompts: Show how to change HtmlSaveOptions to export comments as tooltip pop‑ups while keeping TableCssId. | Provide CSS rules that target the TableCssId prefix to style comment cells and table rows. | Explain how to programmatically verify that the exported HTML contains the expected TableCssId class on comment elements.

using System;
using Aspose.Cells;

// C# example that creates a workbook, adds a comment to cell A1, and saves the file as HTML. The HtmlSaveOptions are set to export comments in‑place, enable comment output, and apply a TableCssId prefix so the generated table and comment elements inherit custom CSS selectors.
class ExportCommentsWithTableCssId
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate some cells with data
        worksheet.Cells["A1"].PutValue("Hello");
        worksheet.Cells["B2"].PutValue("World");

        // Add a comment to cell A1
        int commentIndex = worksheet.Comments.Add("A1");
        Comment comment = worksheet.Comments[commentIndex];
        comment.Note = "This is a sample comment.";

        // Configure HTML save options
        HtmlSaveOptions saveOptions = new HtmlSaveOptions
        {
            // Enable exporting of comments
            IsExportComments = true,
            // Export comments in place (visible next to the cell)
            ExportCommentsType = PrintCommentsType.PrintInPlace,
            // Prefix for CSS classes generated for table elements
            TableCssId = "custom-table"
        };

        // Save the workbook as an HTML file with the specified options
        workbook.Save("output.html", saveOptions);
    }
}
