// Title: How to return an Excel‑to‑HTML conversion as a downloadable FileResult in an ASP.NET MVC controller using Aspose.Cells
// AI Prompts: Create an ASP.NET MVC action that accepts an uploaded Excel file, loads it with Aspose.Cells Workbook, applies HtmlSaveOptions (export active worksheet only, embed images as Base64, Html5), and returns the generated HTML bytes via FileResult for download. | Refactor the console ExportToHtml method into a reusable service that returns a byte[] and invoke it from a controller action that streams the HTML as a .html file using FileContentResult. | Add an optional query‑string parameter to the MVC action to let the caller specify a worksheet index, adjust HtmlSaveOptions accordingly, and return the selected sheet as HTML.
// Common Searches: asp.net mvc download html generated by aspose.cells workbook | export specific worksheet to html using aspose.cells in mvc controller | aspose.cells HtmlSaveOptions base64 images mvc file result example | stream in‑memory html file from asp.net mvc action | convert excel to html on the fly and return as file in asp.net core
// Tags: Aspose.Cells HtmlSaveOptions MVC | export worksheet to HTML Aspose.Cells | download generated HTML FileResult | embed images Base64 Aspose.Cells HTML | ASP.NET MVC stream Aspose.Cells output

using System;
using System.IO;
using Aspose.Cells;

namespace MyApp
{
    // The example shows how to move the console‑based Excel‑to‑HTML conversion into an ASP.NET MVC controller. It loads a workbook with Aspose.Cells, configures HtmlSaveOptions to export only the active worksheet, embed images as Base64, and produce HTML5. The HTML is written to a MemoryStream, converted to a byte array, and returned to the client as a downloadable .html file via FileResult, with optional support for selecting a worksheet index.
    class Program
    {
        static void Main(string[] args)
        {
            // Expect the Excel file name (or full path) as the first argument
            if (args.Length == 0)
            {
                Console.WriteLine("Usage: ExportToHtml <ExcelFileName>");
                return;
            }

            string fileName = args[0];

            try
            {
                // Convert Excel to HTML and obtain the HTML bytes
                byte[] htmlBytes = ExportToHtml(fileName);

                // Determine output HTML file path (same folder, .html extension)
                string outputPath = Path.ChangeExtension(Path.GetFullPath(fileName), ".html");

                // Write HTML to disk
                File.WriteAllBytes(outputPath, htmlBytes);
                Console.WriteLine($"HTML file generated: {outputPath}");
            }
            catch (Exception ex)
            {
                // Log any errors that occur during processing
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        /// <param name="fileName">Excel file name or full path.</param>
        /// <returns>HTML content as a byte array.</returns>
        private static byte[] ExportToHtml(string fileName)
        {
            // Resolve full path and verify the file exists
            string excelPath = Path.GetFullPath(fileName);
            if (!File.Exists(excelPath))
                throw new FileNotFoundException("Excel file not found.", excelPath);

            // Load the workbook using Aspose.Cells
            Workbook workbook = new Workbook(excelPath);

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                ExportActiveWorksheetOnly = true, // export only the first worksheet
                ExportImagesAsBase64 = true,      // embed images as Base64
                HtmlVersion = HtmlVersion.Html5   // generate HTML5 output
            };

            // Save workbook to a memory stream in HTML format
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, saveOptions);
                return htmlStream.ToArray();
            }
        }
    }
}
