// Title: Serve Aspose.Cells HTML Export via ASP.NET Core Web API Using IFilePathProvider
// Description: Learn how to replace file‑system writes with a custom IFilePathProvider so Aspose.Cells can stream full‑workbook or single‑sheet HTML directly from ASP.NET Core controller actions. The guide covers routing, HtmlSaveOptions configuration, and in‑memory response handling for dynamic Excel‑to‑HTML delivery.
// Keywords: Aspose.Cells | IFilePathProvider | ASP.NET Core | Web API | HTML export | streaming response | HtmlSaveOptions | Excel to HTML | in‑memory file provider | .NET 6 | .NET 7
// Common Searches: Aspose.Cells IFilePathProvider example | ASP.NET Core return Excel HTML from controller | stream Aspose.Cells HTML without saving file | dynamic routing for Excel HTML export | HtmlSaveOptions IsFullPathLink with Web API
// Developer Intent: Implement a custom IFilePathProvider that feeds Aspose.Cells HTML output to ASP.NET Core endpoints, eliminating physical file creation and enabling real‑time streaming of workbook or worksheet HTML.
// Use Cases: Expose GET /api/workbook/html that returns the complete workbook HTML as an IActionResult. | Create GET /api/workbook/{sheet}/html to stream HTML for a specific worksheet without writing .html files. | Configure IFilePathProvider to resolve virtual links generated by IsFullPathLink, ensuring navigation between worksheets works in streamed content. | Integrate the solution into a microservice that serves Excel reports as HTML on demand.
// AI Prompts: Generate an ASP.NET Core controller that uses a custom IFilePathProvider to return GetWorkbookHtml() output as a FileResult. | Write a C# implementation of IFilePathProvider that maps Aspose.Cells virtual file references to MemoryStream objects for Web API usage. | Show how to register the custom IFilePathProvider in the ASP.NET Core DI container and configure HtmlSaveOptions for in‑memory streaming.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

namespace AsposeCellsConsoleApp
{
    // Learn how to replace file‑system writes with a custom IFilePathProvider so Aspose.Cells can stream full‑workbook or single‑sheet HTML directly from ASP.NET Core controller actions. The guide covers routing, HtmlSaveOptions configuration, and in‑memory response handling for dynamic Excel‑to‑HTML delivery.
    class Program
    {
        // Path to the source workbook
        private const string WorkbookPath = "sample.xlsx";

        static void Main(string[] args)
        {
            try
            {
                // Ensure the workbook file exists before proceeding
                if (!File.Exists(WorkbookPath))
                {
                    Console.WriteLine($"Error: Workbook file '{WorkbookPath}' not found.");
                    return;
                }

                // Generate and save the main HTML that references each worksheet
                string mainHtml = GetWorkbookHtml();
                if (!string.IsNullOrEmpty(mainHtml))
                {
                    File.WriteAllText("Workbook.html", mainHtml);
                    Console.WriteLine("Main workbook HTML saved as 'Workbook.html'.");
                }

                // Example: generate HTML for a specific sheet (replace with actual sheet name)
                string sheetName = "Sheet1";
                string sheetHtml = GetSheetHtml(sheetName);
                if (!string.IsNullOrEmpty(sheetHtml))
                {
                    string sheetFileName = $"{sheetName}.html";
                    File.WriteAllText(sheetFileName, sheetHtml);
                    Console.WriteLine($"Sheet '{sheetName}' HTML saved as '{sheetFileName}'.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Unexpected error: {ex.Message}");
            }
        }

        // Generates HTML for the entire workbook, with each worksheet saved as a separate file reference
        private static string GetWorkbookHtml()
        {
            try
            {
                if (!File.Exists(WorkbookPath))
                {
                    Console.WriteLine($"Error: Workbook file '{WorkbookPath}' not found.");
                    return string.Empty;
                }

                var workbook = new Workbook(WorkbookPath);

                var saveOptions = new HtmlSaveOptions
                {
                    // Export all worksheets (default behavior)
                    IsFullPathLink = true // Use full paths for sheet links
                };

                using var ms = new MemoryStream();
                workbook.Save(ms, saveOptions);
                ms.Position = 0;

                using var reader = new StreamReader(ms);
                return reader.ReadToEnd();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error generating workbook HTML: {ex.Message}");
                return string.Empty;
            }
        }

        // Generates HTML for a single worksheet identified by its name
        private static string GetSheetHtml(string sheetName)
        {
            try
            {
                if (!File.Exists(WorkbookPath))
                {
                    Console.WriteLine($"Error: Workbook file '{WorkbookPath}' not found.");
                    return string.Empty;
                }

                var workbook = new Workbook(WorkbookPath);

                var sheet = workbook.Worksheets[sheetName];
                if (sheet == null)
                {
                    Console.WriteLine($"Worksheet '{sheetName}' not found.");
                    return string.Empty;
                }

                // Set the desired worksheet as the active one
                workbook.Worksheets.ActiveSheetIndex = sheet.Index;

                var saveOptions = new HtmlSaveOptions
                {
                    ExportActiveWorksheetOnly = true,
                    SaveAsSingleFile = true,
                    IsFullPathLink = false // Relative links are sufficient for a single sheet
                };

                using var ms = new MemoryStream();
                workbook.Save(ms, saveOptions);
                ms.Position = 0;

                using var reader = new StreamReader(ms);
                return reader.ReadToEnd();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error generating HTML for sheet '{sheetName}': {ex.Message}");
                return string.Empty;
            }
        }
    }
}
