// Title: Add an external CSS stylesheet to HTML generated by Aspose.Cells in C# for styling TableCssId‑prefixed elements
// AI Prompts: Write C# code that saves a Workbook as HTML with Aspose.Cells, then programmatically inserts a <link rel="stylesheet" href="styles.css"> tag into the generated file so the page uses an external stylesheet. | Show how to create a separate CSS file that defines rules for selectors beginning with .TableCssId and ensure the saved HTML references this file for site‑wide styling.
// Common Searches: how to reference an external CSS file in HTML output from Aspose.Cells C# | Aspose.Cells C# export worksheet to HTML with custom stylesheet link | add <link> tag to Aspose.Cells generated HTML for TableCssId classes | C# modify output.html after Aspose.Cells save to include stylesheet | styling Aspose.Cells HTML export using external CSS file
// Tags: Aspose.Cells HTML export external stylesheet | C# add link tag to generated HTML | TableCssId CSS styling with Aspose.Cells | custom CSS for Aspose.Cells HTML output | modify saved HTML workbook C#

using System;
using Aspose.Cells;

// The example creates a workbook, fills two rows of data, configures HtmlSaveOptions to disable Base64 image embedding and export only the active worksheet, and saves the result as output.html. Since the current Aspose.Cells version lacks built‑in CSS export options, you must manually add a <link> element pointing to an external stylesheet that defines styles for the .TableCssId‑prefixed selectors.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Add sample data to the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Header1");
            sheet.Cells["B1"].PutValue("Header2");
            sheet.Cells["A2"].PutValue("Data1");
            sheet.Cells["B2"].PutValue("Data2");

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                // Do not embed images as Base64 strings
                ExportImagesAsBase64 = false,
                // Export only the active worksheet
                ExportActiveWorksheetOnly = true
                // Note: ExportHtmlAsCss, CssStyleSheetFile, and CssClassPrefix are not available in this version of Aspose.Cells.
            };

            // Save the workbook as HTML; this creates output.html
            workbook.Save("output.html", htmlOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
