// Title: Load HTML, Edit a Cell, and Save as HTML with Aspose.Cells for .NET
// Description: Demonstrates how to open an existing HTML file as a Workbook, change the value of a specific cell, and export the workbook back to HTML using the default HtmlSaveOptions in C#.
// Keywords: Aspose.Cells load HTML | modify cell Aspose.Cells C# | save workbook to HTML | HtmlSaveOptions default | C# edit HTML spreadsheet
// Common Searches: Aspose.Cells edit cell in HTML file | C# load HTML workbook and save as HTML | How to change a cell value in an HTML spreadsheet using Aspose | Default HtmlSaveOptions example Aspose.Cells
// Developer Intent: Update a cell in an HTML‑based workbook and re‑export it unchanged except for the edited value.
// Use Cases: Replace placeholder text in an HTML template before publishing a report. | Automate status updates in HTML dashboards generated by Aspose.Cells. | Batch‑process HTML workbooks to inject dynamic values and save them with default HTML settings.
// AI Prompts: Generate C# code that opens an HTML file with Aspose.Cells, sets cell B2 to the current timestamp, and saves the result as HTML using default options. | Explain how to customize HtmlSaveOptions after loading an HTML workbook with Aspose.Cells for .NET. | Provide a step‑by‑step tutorial for loading an HTML workbook, modifying multiple cells, and exporting the updated workbook back to HTML.

using System;
using Aspose.Cells;

// Demonstrates how to open an existing HTML file as a Workbook, change the value of a specific cell, and export the workbook back to HTML using the default HtmlSaveOptions in C#.
class Program
{
    static void Main()
    {
        // Load an existing HTML file into a workbook
        Workbook workbook = new Workbook("input.html");

        // Access the first worksheet's cells
        Cells cells = workbook.Worksheets[0].Cells;

        // Modify the value of cell A1 (you can change the address as needed)
        cells["A1"].PutValue("Modified Value");

        // Create HTML save options with default settings
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

        // Save the workbook back to HTML using the default options
        workbook.Save("output.html", htmlOptions);
    }
}
