// Title: Convert HTML String to PDF with Embedded Fonts using Aspose.Cells for .NET
// Description: Shows how to load an HTML string into an Aspose.Cells Workbook, configure PdfSaveOptions to embed Windows fonts (e.g., Arial, Times New Roman), and save the PDF in memory.
// Keywords: Aspose.Cells | HTML to PDF conversion | embed fonts PDF | PdfSaveOptions | HtmlLoadOptions | C# Aspose.Cells example | Identity font encoding | standard Windows fonts | in‑memory PDF generation | temporary HTML file | font embedding | .NET PDF export
// Common Searches: Aspose.Cells embed fonts PDF | convert HTML string to PDF C# | HtmlLoadOptions load from string | PdfSaveOptions embed Windows fonts | Aspose.Cells generate PDF without file | C# HTML to PDF with font embedding | Aspose.Cells PDF export font encoding identity
// Developer Intent: Create a PDF from an HTML snippet while preserving the original fonts by embedding them in the output file.
// Use Cases: Generate printable PDFs from dynamic HTML reports with exact font fidelity. | Expose a web API that receives HTML payloads and returns PDF bytes with embedded fonts. | Batch‑process email templates or invoices into PDFs for archiving, ensuring all used fonts are embedded.
// AI Prompts: Write C# code that converts an HTML string to a PDF with embedded fonts using Aspose.Cells without creating a temporary file. | Explain how to configure PdfSaveOptions to embed custom TrueType fonts and specify a fallback font when converting HTML to PDF with Aspose.Cells. | Show how to stream the PDF generated by Aspose.Cells directly to an ASP.NET Core response while preserving embedded fonts.

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Shows how to load an HTML string into an Aspose.Cells Workbook, configure PdfSaveOptions to embed Windows fonts (e.g., Arial, Times New Roman), and save the PDF in memory.
class HtmlToPdfWithEmbeddedFonts
{
    static void Main()
    {
        // Sample HTML content to be converted
        string htmlContent = @"
            <html>
                <head><title>Sample</title></head>
                <body>
                    <p style='font-family:Arial; font-size:14pt;'>This is a test paragraph with Arial font.</p>
                    <p style='font-family:Times New Roman; font-size:12pt;'>Another line using Times New Roman.</p>
                </body>
            </html>";

        // Write HTML string to a temporary file (required by the load API)
        string tempHtmlPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".html");
        File.WriteAllText(tempHtmlPath, htmlContent, Encoding.UTF8);

        // Create HTML load options (default constructor)
        HtmlLoadOptions loadOptions = new HtmlLoadOptions();
        // Enable auto‑fit of rows/columns and support for <div> tags (optional but useful)
        loadOptions.AutoFitColsAndRows = true;
        loadOptions.SupportDivTag = true;

        // Load the HTML file into a Workbook using the provided constructor
        Workbook workbook = new Workbook(tempHtmlPath, loadOptions);

        // Configure PDF save options to embed fonts
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        pdfOptions.FontEncoding = PdfFontEncoding.Identity;          // Use Identity encoding for all fonts
        pdfOptions.EmbedStandardWindowsFonts = true;                // Embed standard Windows fonts (e.g., Arial, Times New Roman)
        pdfOptions.DefaultFont = "Arial";                           // Fallback font if a specific font is missing
        pdfOptions.CheckWorkbookDefaultFont = true;                 // Try workbook's default font first

        // Save the workbook to a PDF in memory
        using (MemoryStream pdfStream = new MemoryStream())
        {
            workbook.Save(pdfStream, pdfOptions);

            // Optionally write the PDF to a file for verification
            string outputPdfPath = Path.Combine(Environment.CurrentDirectory, "Result.pdf");
            File.WriteAllBytes(outputPdfPath, pdfStream.ToArray());

            Console.WriteLine("PDF generated successfully with embedded fonts at: " + outputPdfPath);
        }

        // Clean up the temporary HTML file
        if (File.Exists(tempHtmlPath))
        {
            File.Delete(tempHtmlPath);
        }
    }
}
