// Title: C# – Load Excel, modify cell B4, and export to HTML with a custom default font using Aspose.Cells
// Description: Demonstrates how to open an Excel workbook with Aspose.Cells, update the value of cell B4, set HtmlSaveOptions.DefaultFontName to a custom font (e.g., Arial), and save the workbook as an HTML file that uses the specified default font.
// Keywords: Aspose.Cells C# HTML export | HtmlSaveOptions DefaultFontName | modify Excel cell C# | Excel to HTML conversion | custom default font HTML | Aspose.Cells example | C# workbook save as HTML | change cell value Aspose
// Common Searches: Aspose.Cells set default font when saving as HTML | C# update specific cell in Excel and export to HTML | HtmlSaveOptions example with custom font | How to change cell B4 value using Aspose.Cells | Export Excel to HTML with Arial font
// Developer Intent: Edit a particular cell in an Excel workbook and generate an HTML file that uses a specified default font.
// Use Cases: Generate web‑ready reports from Excel templates while enforcing a consistent typography style. | Automate data updates in spreadsheets and produce HTML output for dashboards or email newsletters. | Create lightweight HTML versions of Excel files for browsers that require a specific fallback font.
// AI Prompts: Write C# code with Aspose.Cells that opens an Excel file, changes cell C5 to a numeric value, and saves the workbook as HTML using "Times New Roman" as the default font. | Explain how HtmlSaveOptions.DefaultFontName affects the CSS generated by Aspose.Cells and how to specify multiple fallback fonts for HTML export.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Demonstrates how to open an Excel workbook with Aspose.Cells, update the value of cell B4, set HtmlSaveOptions.DefaultFontName to a custom font (e.g., Arial), and save the workbook as an HTML file that uses the specified default font.
    class Program
    {
        static void Main()
        {
            // Path to the source Excel file
            string sourcePath = "input.xlsx";

            // Load the workbook from the file
            Workbook workbook = new Workbook(sourcePath);

            // Modify the text of cell B4 in the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["B4"].PutValue("Updated Text");

            // Create HTML save options and set a custom default font
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
            htmlOptions.DefaultFontName = "Arial"; // Custom default font for the HTML output

            // Save the modified workbook as an HTML file using the specified options
            string outputPath = "output.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"Workbook saved as HTML to '{outputPath}' with default font '{htmlOptions.DefaultFontName}'.");
        }
    }
}
