// Title: Convert an Excel workbook to HTML with a custom TableCssId using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file with Aspose.Cells, sets HtmlSaveOptions.TableCssId to a user‑defined value, and saves the workbook as an HTML file. | Show how to apply a specific CSS identifier to the table element generated by Aspose.Cells when exporting a workbook to HTML. | Provide a minimal example that demonstrates configuring Aspose.Cells HTML export options to include a custom table ID in the resulting HTML markup.
// Common Searches: Aspose.Cells how to assign a CSS id to the HTML table when saving an Excel file | C# export XLSX to HTML with a specific table identifier using Aspose.Cells | set HtmlSaveOptions.TableCssId property in Aspose.Cells .NET example | save workbook as HTML with custom table CSS selector Aspose.Cells | Aspose.Cells HTML conversion custom table id tutorial
// Tags: Aspose.Cells HtmlSaveOptions TableCssId | export Excel to HTML Aspose.Cells | C# configure HTML export table ID Aspose.Cells | custom table CSS ID Aspose.Cells | save workbook as HTML .NET

using System;
using Aspose.Cells;

// // Loads 'input.xlsx' into a Workbook, sets HtmlSaveOptions.TableCssId to 'myCustomTableId', and saves the workbook as 'output.html' using Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        // Load the workbook from an existing Excel file
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options with a custom CSS ID for the generated table
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
        htmlOptions.TableCssId = "myCustomTableId";

        // Export the workbook to HTML using the specified options
        workbook.Save("output.html", htmlOptions);
    }
}
