// Title: Load an HTML file with DIV layout using Aspose.Cells for .NET, re‑save to HTML, and confirm the DIV hierarchy stays intact
// AI Prompts: Open an HTML workbook with Aspose.Cells HtmlLoadOptions while retaining its DIV layout, then save it to a new HTML file using HtmlSaveOptions. | Read the original and saved HTML files, collapse consecutive whitespace into a single space, and compare the normalized strings to ensure the DIV structure has not changed.
// Common Searches: how to keep div tags unchanged when loading and saving HTML with Aspose.Cells .NET | Aspose.Cells .NET compare original and exported HTML for div layout consistency | verify that Aspose.Cells does not modify HTML div hierarchy after export | C# normalize whitespace and compare two HTML files generated by Aspose.Cells
// Tags: html load retain div layout Aspose.Cells .NET | html save retain div layout Aspose.Cells .NET | whitespace normalization compare html C# | verify div hierarchy after Aspose.Cells export | Aspose.Cells HtmlLoadOptions default behavior

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The example loads an HTML file into an Aspose.Cells Workbook using default HtmlLoadOptions, saves it back to HTML with default HtmlSaveOptions, reads both files, normalizes whitespace, and checks whether the DIV structure remains unchanged, outputting the verification result.
class HtmlDivPreserveDemo
{
    static void Main()
    {
        // Paths to the source and destination HTML files
        string inputHtmlPath = "input.html";
        string outputHtmlPath = "output.html";

        // Verify that the input file exists
        if (!File.Exists(inputHtmlPath))
        {
            Console.WriteLine($"Input file not found: {inputHtmlPath}");
            return;
        }

        try
        {
            // Load the HTML file (default options)
            HtmlLoadOptions loadOptions = new HtmlLoadOptions();
            Workbook workbook = new Workbook(inputHtmlPath, loadOptions);

            // Save the workbook back to HTML (default options)
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();
            workbook.Save(outputHtmlPath, saveOptions);

            // Read both HTML contents for verification
            string originalHtml = File.ReadAllText(inputHtmlPath);
            string exportedHtml = File.ReadAllText(outputHtmlPath);

            // Simple normalization: collapse whitespace to a single space and trim
            string Normalize(string html) => Regex.Replace(html, @"\s+", " ").Trim();

            string normalizedOriginal = Normalize(originalHtml);
            string normalizedExported = Normalize(exportedHtml);

            // Verify that the DIV structure remains unchanged
            bool divStructureUnchanged = normalizedOriginal == normalizedExported;

            Console.WriteLine(divStructureUnchanged
                ? "DIV structure is unchanged after re-export."
                : "DIV structure has changed after re-export.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
