// Title: Load an HTML file into an Aspose.Cells workbook and re‑export it to HTML with a new TableCssId in C#
// AI Prompts: Import an HTML document into a Workbook, set HtmlSaveOptions.TableCssId to a custom value, and save the workbook as HTML using Aspose.Cells for .NET. | Change the CSS identifier of the generated HTML table when converting a workbook back to HTML with Aspose.Cells in C#. | Use Aspose.Cells HtmlSaveOptions to apply a different TableCssId while re‑saving an imported HTML workbook.
// Common Searches: Aspose.Cells C# set TableCssId property when saving workbook to HTML | how to change the id attribute of the table generated by Aspose.Cells HTML export | load html file into Aspose.Cells workbook and export with custom table css id
// Tags: Aspose.Cells HtmlSaveOptions TableCssId | C# import HTML workbook Aspose.Cells | re‑export workbook to HTML with custom table id | custom CSS id for Aspose.Cells HTML output

using System;
using Aspose.Cells;

// Loads input.html into a Workbook, sets HtmlSaveOptions.TableCssId to "newTableId", and saves the workbook as output.html.
class Program
{
    static void Main()
    {
        // Load the source HTML file into a workbook.
        // The constructor automatically detects the HTML format.
        Workbook workbook = new Workbook("input.html");

        // Configure HTML save options.
        HtmlSaveOptions saveOptions = new HtmlSaveOptions();

        // Apply a new CSS ID to the generated HTML table.
        saveOptions.TableCssId = "newTableId";

        // Save the workbook back to HTML using the specified options.
        workbook.Save("output.html", saveOptions);
    }
}
