// Title: How to stop exponential notation for large numbers when exporting Excel to HTML with Aspose.Cells for .NET
// AI Prompts: Generate C# code that applies a "0" custom number format to every numeric cell before saving the workbook as HTML using Aspose.Cells. | Show me how to loop through all cells in a worksheet and enforce plain number display during HTML conversion with Aspose.Cells .NET. | Provide a snippet that disables scientific (exponential) notation in the HTML output of an Excel file using Aspose.Cells.
// Common Searches: Aspose.Cells .NET export Excel to HTML without exponential notation | C# set custom numeric format for all numeric cells before HTML save | prevent scientific notation in HTML output generated by Aspose.Cells | how to force plain numbers when converting XLSX to HTML using Aspose.Cells
// Tags: apply numeric format style Aspose.Cells | prevent exponential notation HTML export | iterate worksheet cells set style .NET | HTML save options number display | plain number custom format Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, iterates through each cell in the first worksheet, applies a custom numeric format "0" to numeric cells to suppress exponential notation, and then saves the workbook as an HTML file using Aspose.Cells HtmlSaveOptions.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.html";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                return;
            }

            // Load the workbook from the existing file
            var workbook = new Workbook(inputPath);

            // Apply a custom number format to all numeric cells to avoid scientific notation
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Iterate through all used cells in the worksheet
            foreach (Cell cell in cells)
            {
                if (cell.Type == CellValueType.IsNumeric)
                {
                    // Retrieve the current style
                    Style style = cell.GetStyle();

                    // Set a custom format that forces plain number display (no exponent)
                    style.Custom = "0";

                    // Apply the modified style back to the cell
                    cell.SetStyle(style);
                }
            }

            // Configure HTML export options (default options are sufficient for number formats)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

            // Save the workbook as an HTML file with the specified options
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"Workbook successfully saved as HTML to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
