// Title: Add TableCssId Prefix to Self‑Closing HTML Tags (e.g., <img/>) with Aspose.Cells for .NET
// Description: Demonstrates how to set HtmlSaveOptions.TableCssId, generate an optional image that creates a self‑closing <img/> tag, save a workbook as HTML, and verify that the TableCssId prefix appears in the markup.
// Keywords: Aspose.Cells | HtmlSaveOptions | TableCssId | self‑closing tags | C# HTML export | verify img tag | custom CSS prefix | .NET workbook to HTML
// Common Searches: Aspose.Cells TableCssId example | how to add custom CSS id to HTML output | detect <img/> tag in Aspose.Cells HTML | prefix self‑closing tags with TableCssId | C# save workbook as HTML with custom class
// Developer Intent: Show how to apply a custom TableCssId to the HTML generated by Aspose.Cells and confirm that self‑closing tags inherit the prefix.
// Use Cases: Export a worksheet to HTML and ensure table elements carry a unique CSS identifier. | Insert an image into a worksheet, generate a self‑closing <img/> tag, and validate its presence in the saved HTML. | Automate testing of HTML output by searching for the TableCssId string and self‑closing tags.
// AI Prompts: Write a C# method that parses Aspose.Cells HTML output and adds the TableCssId prefix to any missing self‑closing tags. | Explain how HtmlSaveOptions.TableCssId influences the class or id attributes of generated HTML elements, including <img>, <br>, and <hr>. | Create a unit test in C# that asserts the saved HTML contains both the custom TableCssId and a self‑closing <img/> tag.

using System;
using System.IO;
using Aspose.Cells;

// Demonstrates how to set HtmlSaveOptions.TableCssId, generate an optional image that creates a self‑closing <img/> tag, save a workbook as HTML, and verify that the TableCssId prefix appears in the markup.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Populate some sample data
            worksheet.Cells["A1"].PutValue("Name");
            worksheet.Cells["B1"].PutValue("Age");
            worksheet.Cells["A2"].PutValue("John");
            worksheet.Cells["B2"].PutValue(30);

            // OPTIONAL: Add an image to generate a self‑closing <img/> tag in the HTML output.
            // Ensure that "sample.png" exists in the executable directory or provide a full path.
            string imagePath = "sample.png";
            if (File.Exists(imagePath))
            {
                try
                {
                    worksheet.Pictures.Add(2, 2, imagePath);
                }
                catch (CellsException)
                {
                    // Image could not be added – continue without it.
                }
            }

            // Configure HTML save options.
            // TableCssId adds a prefix to CSS class names for table elements (tr, td, etc.).
            // This helps identify self‑closing tags that belong to the generated table.
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                TableCssId = "customTable"
            };

            // Save the workbook as HTML.
            string htmlFile = "output.html";
            workbook.Save(htmlFile, saveOptions);

            // Load the generated HTML to verify that self‑closing tags exist
            // and that the TableCssId prefix is present in the markup.
            string htmlContent = File.ReadAllText(htmlFile);

            // Check for a typical self‑closing tag (<img/>). Adjust if you did not add an image.
            bool hasSelfClosingImg = htmlContent.Contains("<img");
            // Verify that the TableCssId prefix appears in the HTML (e.g., as an attribute or class name).
            bool hasTableCssId = htmlContent.Contains("customTable");

            Console.WriteLine($"Self‑closing <img> tag detected: {hasSelfClosingImg}");
            Console.WriteLine($"TableCssId prefix applied: {hasTableCssId}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
