// Title: C# – Verify TableCssId Prefix on Self‑Closing Tags in Aspose.Cells HTML Export
// Description: A complete C# example that creates an Aspose.Cells workbook, adds data and an image (producing <img/>), saves it as HTML with HtmlSaveOptions.TableCssId set to a custom prefix, then uses a regular expression to locate self‑closing tags (img, br, input, hr, meta, link) and confirms each tag’s class attribute contains the TableCssId value. The code logs missing prefixes for quick correction.
// Keywords: Aspose.Cells | C# | .NET | HTML export | TableCssId | self‑closing tags | img tag validation | regex HTML parsing | class attribute check | Aspose.Cells HtmlSaveOptions | web styling consistency
// Common Searches: Aspose.Cells C# verify TableCssId on img tag | regex find self‑closing tags in Aspose.Cells HTML output | how to add custom class prefix to HTML generated by Aspose.Cells | C# check class attribute of <img/> after saving workbook to HTML | TableCssId usage in Aspose.Cells HTML export
// Developer Intent: Ensure every self‑closing HTML element generated by Aspose.Cells includes the custom TableCssId class for consistent styling.
// Use Cases: Post‑export validation of HTML to guarantee CSS selectors apply to images, line breaks, inputs, etc. | Automated reporting of missing TableCssId prefixes before publishing workbook‑derived web pages. | Programmatic correction of self‑closing tags that lack the required class, enabling a clean, styled HTML output.
// AI Prompts: Generate C# code that saves an Aspose.Cells workbook as HTML with a custom TableCssId and then validates each self‑closing tag’s class attribute using regex. | Write a method that scans an HTML string for <img>, <br>, <input>, <hr>, <meta>, and <link> tags and appends the TableCssId class when it is absent. | Explain how HtmlSaveOptions.TableCssId influences CSS selectors for tables and self‑closing elements in the HTML produced by Aspose.Cells.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

namespace AsposeCellsHtmlSelfClosingTagDemo
{
    // A complete C# example that creates an Aspose.Cells workbook, adds data and an image (producing <img/>), saves it as HTML with HtmlSaveOptions.TableCssId set to a custom prefix, then uses a regular expression to locate self‑closing tags (img, br, input, hr, meta, link) and confirms each tag’s class attribute contains the TableCssId value. The code logs missing prefixes for quick correction.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("Alice");
            sheet.Cells["B3"].PutValue(25);

            // Insert an image to generate a self‑closing <img/> tag in the HTML output
            // (Assumes a valid image file "logo.png" exists in the executable directory)
            string imagePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "logo.png");
            if (File.Exists(imagePath))
            {
                int pictureIndex = sheet.Pictures.Add(1, 1, imagePath);
                sheet.Pictures[pictureIndex].Width = 100;
                sheet.Pictures[pictureIndex].Height = 100;
            }

            // Configure HTML save options with a TableCssId prefix
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            saveOptions.TableCssId = "customTable"; // Prefix for CSS class names of table elements

            // Save the workbook as HTML
            string htmlPath = "output.html";
            workbook.Save(htmlPath, saveOptions);
            Console.WriteLine($"Workbook saved to HTML at: {htmlPath}");
            Console.WriteLine($"TableCssId set to: {saveOptions.TableCssId}");

            // Load the generated HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // Define a regex to find self‑closing tags (e.g., <img />, <br />, <input />, <hr />, <meta />, <link />)
            string pattern = @"<\s*(img|br|input|hr|meta|link)(\s+[^>]*?)?\/>";
            MatchCollection matches = Regex.Matches(htmlContent, pattern, RegexOptions.IgnoreCase);

            Console.WriteLine($"Found {matches.Count} self‑closing tag(s) in the HTML output.");

            // Verify that each self‑closing tag contains the TableCssId prefix in its class attribute (if present)
            foreach (Match match in matches)
            {
                string tag = match.Value;
                // Extract the class attribute value, if any
                string classPattern = @"class\s*=\s*[""']([^""']+)[""']";
                Match classMatch = Regex.Match(tag, classPattern, RegexOptions.IgnoreCase);
                if (classMatch.Success)
                {
                    string classValue = classMatch.Groups[1].Value;
                    bool containsPrefix = classValue.Contains(saveOptions.TableCssId);
                    Console.WriteLine($"{tag} -> class=\"{classValue}\" contains prefix: {containsPrefix}");
                }
                else
                {
                    Console.WriteLine($"{tag} -> no class attribute");
                }
            }

            // Example of how to enforce the prefix (optional):
            // If a self‑closing tag lacks the prefix, you could modify the HTML string here.
            // For demonstration, we simply output a notice.
            foreach (Match match in matches)
            {
                string tag = match.Value;
                if (!Regex.IsMatch(tag, @"class\s*=\s*[""'][^""']*" + Regex.Escape(saveOptions.TableCssId) + @"[^""']*[""']", RegexOptions.IgnoreCase))
                {
                    Console.WriteLine($"Notice: Self‑closing tag does not contain the TableCssId prefix: {tag}");
                }
            }
        }
    }
}
