// Title: Aspose.Cells .NET – Render WordArt Gradient Fill in HTML with Solid‑Color Fallback
// Description: C# example that creates an Excel workbook, adds a WordArt text box using PresetWordArtStyle.WordArtStyle7 (gradient fill), saves the sheet as HTML, then injects a solid‑color fallback before any CSS linear‑gradient declarations via a regular‑expression replace. Ensures the gradient appears in modern browsers while older browsers display a consistent solid color.
// Keywords: Aspose.Cells | .NET | C# | WordArt gradient | HTML export | fallback solid color | linear-gradient CSS | regex replace | PresetWordArtStyle | cross‑browser compatibility | legacy browsers | GitHub example | Excel to HTML conversion
// Common Searches: Aspose.Cells render WordArt gradient in HTML | add solid color fallback to Aspose.Cells HTML output | C# regex replace linear-gradient with fallback color | PresetWordArtStyle.WordArtStyle7 example | Excel shape to HTML with gradient fallback
// Developer Intent: Generate HTML from an Excel workbook that preserves WordArt gradient fills and adds a solid‑color fallback for browsers that do not support CSS gradients.
// Use Cases: Creating HTML reports with visually rich WordArt headings that work across modern and legacy browsers. | Automating an Excel‑to‑HTML pipeline where gradient fills must degrade gracefully to a single color. | Programmatically applying preset WordArt styles to shapes and post‑processing the exported HTML for cross‑browser CSS compatibility.
// AI Prompts: Write C# code using Aspose.Cells to add a WordArt text box with a gradient fill, export to HTML, and prepend a solid fallback color before any linear‑gradient CSS rule. | Provide a regular expression pattern and replacement string that inserts a fallback background‑color before linear‑gradient definitions in an HTML file generated by Aspose.Cells. | Explain how PresetWordArtStyle.WordArtStyle7 works in Aspose.Cells and how to ensure the resulting HTML displays correctly in browsers lacking gradient support.

using System;
using System.Drawing;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Drawing;
using Aspose.Cells.Drawing.Texts;

// C# example that creates an Excel workbook, adds a WordArt text box using PresetWordArtStyle.WordArtStyle7 (gradient fill), saves the sheet as HTML, then injects a solid‑color fallback before any CSS linear‑gradient declarations via a regular‑expression replace. Ensures the gradient appears in modern browsers while older browsers display a consistent solid color.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Add a text box shape to the worksheet
        // Parameters: upperLeftRow, top, upperLeftColumn, left, height, width
        Shape textBox = worksheet.Shapes.AddTextBox(2, 0, 2, 0, 300, 100);
        textBox.Text = "Gradient WordArt";

        // Apply a preset WordArt style that contains a gradient fill (WordArtStyle7)
        // WordArtStyle7: Gradient Fill - Blue, Accent 1, Reflection
        textBox.TextBody.SetWordArtStyle(PresetWordArtStyle.WordArtStyle7);

        // Save the workbook as HTML (temporary file)
        string htmlPath = "WordArtGradient.html";
        workbook.Save(htmlPath, SaveFormat.Html);

        // Load the generated HTML content
        string htmlContent = File.ReadAllText(htmlPath);

        // Define a solid fallback color (hex) that will be used by older browsers
        // Here we use a typical Accent 1 blue color
        string fallbackColor = "#4F81BD";

        // Insert the fallback background-color before any linear-gradient definitions
        // This regex finds CSS rules that contain a linear-gradient and prepends the solid color
        string pattern = @"(background\s*:\s*)(linear-gradient[^;]+);";
        string replacement = $"$1{fallbackColor}; $2;";

        string updatedHtml = Regex.Replace(htmlContent, pattern, replacement, RegexOptions.IgnoreCase);

        // Overwrite the HTML file with the modified content that includes the fallback color
        File.WriteAllText(htmlPath, updatedHtml);
    }
}
