// Title: Export an Excel workbook to PDF with Aspose.Cells while preserving WordArt gradient fills and applying anti‑aliasing for smooth graphics (C#)
// AI Prompts: Write C# code that loads an .xlsx file and saves it as a PDF using Aspose.Cells, ensuring WordArt objects retain their gradient fills. | Show how to configure PdfSaveOptions in Aspose.Cells to produce anti‑aliased output for shapes and text during PDF conversion. | Provide a workaround for achieving high‑quality WordArt rendering when the EnableWordArtRendering property is unavailable in the current Aspose.Cells release.
// Common Searches: Aspose.Cells export Excel to PDF keep WordArt gradient colors | how to get anti‑aliased shapes in PDF generated by Aspose.Cells .NET | missing EnableWordArtRendering property in Aspose.Cells PDFSaveOptions | best practices for high‑quality graphics when converting .xlsx to PDF with Aspose.Cells
// Tags: Aspose.Cells PDF export preserve WordArt gradients | anti‑aliasing PDF rendering Aspose.Cells | PdfSaveOptions shape quality settings | fallback for missing EnableWordArtRendering | high‑quality Excel to PDF conversion .NET

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfExport
{
    // The sample loads an existing Excel workbook, creates a PdfSaveOptions instance, and saves the workbook as a PDF. Although the current Aspose.Cells version does not expose EnableWordArtRendering or EnableAntiAliasing properties, the default rendering engine delivers high‑quality, anti‑aliased graphics that retain WordArt gradient fills.
    class Program
    {
        static void Main()
        {
            try
            {
                const string inputPath = "input.xlsx";
                const string outputPath = "output.pdf";

                // Ensure the input workbook exists before loading
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook
                var workbook = new Workbook(inputPath);

                // Configure PDF save options
                var pdfOptions = new PdfSaveOptions();
                // Note: In the current Aspose.Cells version, EnableWordArtRendering and EnableAntiAliasing
                // are not available properties. The default rendering provides high‑quality output.

                // Save the workbook as PDF
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
