// Title: How to save an Excel workbook as HTML without downlevel revealed comments using Aspose.Cells in C#
// AI Prompts: Generate C# code that loads an .xlsx file with Aspose.Cells, configures HtmlSaveOptions to suppress downlevel revealed comments, and saves the result as .html. | Demonstrate setting HtmlSaveOptions.DisableDownlevelRevealedComments = true before calling Workbook.Save in a .NET project. | Provide a complete example that validates the source Excel file, applies HTML save options to remove IE conditional comments, and writes the output HTML file.
// Common Searches: Aspose.Cells disable downlevel revealed comments when exporting to HTML in C# | C# export Excel to HTML without IE conditional comments using Aspose.Cells | HtmlSaveOptions.DisableDownlevelRevealedComments usage Aspose.Cells .NET | Remove conditional comments from HTML generated by Aspose.Cells | Save workbook as HTML without downlevel revealed comment syntax Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions disable downlevel revealed comments | C# export Excel to HTML without conditional comments | Aspose.Cells HTML save options IE conditional comments | Workbook.Save HTML options Aspose.Cells | Aspose.Cells omit downlevel revealed comments

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

namespace AsposeCellsExample
{
    // The example loads an existing Excel workbook, creates HtmlSaveOptions for HTML output, optionally disables downlevel revealed (IE conditional) comments, and saves the workbook as an HTML file while handling missing input files and runtime errors.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string inputPath = "input.xlsx";
                string outputPath = "output.html";

                // Ensure the input workbook exists before loading
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook from the specified file
                Workbook workbook = new Workbook(inputPath);

                // Configure HTML save options (default settings omit downlevel revealed comments)
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);

                // Save the workbook as an HTML file using the configured options
                workbook.Save(outputPath, htmlOptions);
                Console.WriteLine($"Workbook successfully saved as HTML to: {outputPath}");
            }
            catch (Exception ex)
            {
                // Handle any runtime exceptions gracefully
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
