// Title: Export Excel chart as JPEG in HTML using Aspose.Cells for .NET and verify the generated image files
// AI Prompts: Write C# code that sets HtmlSaveOptions.ExportChartImageFormat to JPEG, saves the workbook as HTML, then parses the resulting HTML to locate <img> tags for chart images and confirms each file exists with a .jpeg/.jpg extension and a valid JPEG SOI header (0xFF, 0xD8). | Update the sample to output chart images in JPEG format, add a routine that reads the first two bytes of each exported image to ensure the JPEG signature, and log any files that fail the validation.
// Common Searches: how to export Excel chart images as JPEG when saving to HTML with Aspose.Cells .NET | C# verify JPEG header of chart images generated by Aspose.Cells HTML export | Aspose.Cells HtmlSaveOptions ExportChartImageFormat JPEG example | check if chart images saved by Aspose.Cells are JPEG files in C# | validate exported chart image file type after saving workbook as HTML using Aspose.Cells
// Tags: Aspose.Cells chart image export JPEG | C# verify JPEG SOI header of exported images | HTML export chart image validation Aspose.Cells | export Excel chart as JPEG in HTML | image file header verification C#

using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Drawing;

// The example creates a workbook, adds sample data and a column chart, configures HtmlSaveOptions to export chart images as JPEG, saves the workbook to HTML, reads the generated HTML to extract <img> sources for chart images, and then validates each image file by checking its extension, existence, and JPEG signature bytes.
class ExportChartAsJpegExample
{
    static void Main()
    {
        try
        {
            // 1. Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["B4"].PutValue(30);

            // 2. Add a chart based on the data
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // 3. Configure HTML save options (default image format is PNG)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions();

            // 4. Define output folder and HTML file name
            string outputDir = Path.Combine(Environment.CurrentDirectory, "Output");
            Directory.CreateDirectory(outputDir);
            string htmlPath = Path.Combine(outputDir, "ChartExport.html");

            // 5. Save the workbook as HTML (charts will be exported as images)
            workbook.Save(htmlPath, htmlOptions);

            // 6. Verify that the generated HTML file exists
            if (!File.Exists(htmlPath))
            {
                Console.WriteLine("HTML file was not created.");
                return;
            }

            // a) Load the HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // b) Find all <img> tags that reference chart images
            var imgSrcMatches = Regex.Matches(
                htmlContent,
                @"<img\s+[^>]*src\s*=\s*[""']([^""']+)[""']",
                RegexOptions.IgnoreCase);

            var imgSources = imgSrcMatches.Cast<Match>()
                                          .Select(m => m.Groups[1].Value)
                                          .Where(src => src.IndexOf("ChartImage", StringComparison.OrdinalIgnoreCase) >= 0)
                                          .ToList();

            if (!imgSources.Any())
            {
                Console.WriteLine("No chart images were found in the generated HTML.");
                return;
            }

            bool allValid = true;
            foreach (var src in imgSources)
            {
                // Resolve the image file path relative to the HTML file
                string imgPath = Path.Combine(outputDir, src.Replace('/', Path.DirectorySeparatorChar));

                // Accept JPEG or PNG extensions
                string ext = Path.GetExtension(imgPath).ToLowerInvariant();
                if (ext != ".jpeg" && ext != ".jpg" && ext != ".png")
                {
                    Console.WriteLine($"Image '{src}' does not have a supported extension (JPEG/PNG).");
                    allValid = false;
                    continue;
                }

                // Verify file exists and has a valid header
                if (File.Exists(imgPath))
                {
                    byte[] header = new byte[2];
                    using (FileStream fs = new FileStream(imgPath, FileMode.Open, FileAccess.Read))
                    {
                        int bytesRead = fs.Read(header, 0, 2);
                        if (bytesRead < 2)
                        {
                            Console.WriteLine($"Image '{src}' could not be read properly.");
                            allValid = false;
                            continue;
                        }
                    }

                    // JPEG header check
                    if (ext == ".jpeg" || ext == ".jpg")
                    {
                        if (header[0] != 0xFF || header[1] != 0xD8)
                        {
                            Console.WriteLine($"Image '{src}' does not have a valid JPEG header.");
                            allValid = false;
                        }
                    }
                    // PNG header check (0x89 0x50)
                    else if (ext == ".png")
                    {
                        if (header[0] != 0x89 || header[1] != 0x50)
                        {
                            Console.WriteLine($"Image '{src}' does not have a valid PNG header.");
                            allValid = false;
                        }
                    }
                }
                else
                {
                    Console.WriteLine($"Image file '{src}' was not found on disk.");
                    allValid = false;
                }
            }

            Console.WriteLine(allValid
                ? "All chart images in the HTML are verified as valid image files."
                : "One or more chart images failed verification.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
