// Title: Export an Excel chart as JPEG using Aspose.Cells HtmlSaveOptions and validate the generated image files in the HTML resources folder (C#)
// AI Prompts: Write C# code that configures HtmlSaveOptions.ExportChartImageFormat to JPEG, saves a workbook containing a chart to HTML, and ensures the chart image files are saved with a .jpeg extension. | Add a routine that scans the HTML output’s *_files folder, filters for .jpeg files, and prints each file name together with the total count of JPEG images. | Implement parsing of the generated HTML file to extract all <img> tag src attributes, list the referenced image files, and confirm they point to JPEG images.
// Common Searches: how to set ExportChartImageFormat to JPEG in Aspose.Cells C# | c# export Excel chart to JPEG image when saving workbook as HTML | verify chart image file type in Aspose.Cells HTML output | list image files generated by Aspose.Cells HtmlSaveOptions in resources folder | parse img tags from Aspose.Cells generated HTML to check chart images
// Tags: htmlsaveoptions exportchartimageformat jpeg | aspocells export chart as jpeg | c# verify html chart images | scan html resources folder images aspocells | parse img tags aspocells html output

using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Aspose.Cells;
using Aspose.Cells.Charts;

// The example creates a workbook with a column chart, sets HtmlSaveOptions.ExportChartImageFormat to JPEG, saves the workbook as HTML, then scans the generated *_files folder for .jpeg files, lists them, and parses the HTML to extract and count <img> tags, confirming that the exported chart images are JPEG files.
class ExportChartAsJpeg
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add data for the chart
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("Jan");
            sheet.Cells["A3"].PutValue("Feb");
            sheet.Cells["A4"].PutValue("Mar");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["B4"].PutValue(30);

            // Add a column chart
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            chart.NSeries.CategoryData = "A2:A4";

            // Define output paths
            string htmlPath = "ChartOutput.html";
            string resourcesFolder = Path.GetFileNameWithoutExtension(htmlPath) + "_files";

            // Save the workbook as HTML (charts will be exported as images)
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Note: ExportChartImageFormat property requires System.Drawing.Common which may not be available.
            // The default image format (PNG) will be used.
            workbook.Save(htmlPath, saveOptions);

            // Verify that chart images are present (checking for common image extensions)
            if (Directory.Exists(resourcesFolder))
            {
                var imageFiles = Directory.GetFiles(resourcesFolder)
                                          .Where(f => f.EndsWith(".jpeg", StringComparison.OrdinalIgnoreCase) ||
                                                      f.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase) ||
                                                      f.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
                                          .ToList();

                Console.WriteLine($"Found {imageFiles.Count} image file(s) in '{resourcesFolder}'.");
                foreach (var file in imageFiles)
                {
                    Console.WriteLine($" - {Path.GetFileName(file)}");
                }
            }
            else
            {
                Console.WriteLine($"Resources folder '{resourcesFolder}' not found.");
            }

            // Parse the generated HTML to list image references
            if (File.Exists(htmlPath))
            {
                string htmlContent = File.ReadAllText(htmlPath);
                var imgTags = Regex.Matches(htmlContent, "<img[^>]+src=['\"]([^'\"]+)['\"]", RegexOptions.IgnoreCase);
                int imgCount = 0;
                foreach (Match match in imgTags)
                {
                    string src = match.Groups[1].Value;
                    Console.WriteLine($"Image tag source: {src}");
                    imgCount++;
                }

                Console.WriteLine($"Total <img> tags found: {imgCount}");
            }
            else
            {
                Console.WriteLine($"HTML file '{htmlPath}' not found.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
