// Title: Set all hyperlinks to open in a new tab with Aspose.Cells HTML export (C#)
// Description: Shows how to configure HtmlSaveOptions.LinkTargetType = HtmlLinkTargetType.Blank so that every hyperlink in the HTML file produced by Aspose.Cells includes target="_blank" and opens in a new browser tab.
// Keywords: Aspose.Cells C# HTML export | HtmlSaveOptions LinkTargetType | target=_blank hyperlinks | export Excel to HTML | set hyperlink target blank | Aspose.Cells hyperlink new tab | C# save workbook as HTML | Aspose.Cells HTML options
// Common Searches: Aspose.Cells set hyperlink target to _blank | HtmlSaveOptions LinkTargetType example C# | make Excel hyperlinks open in new tab when saved as HTML | C# Aspose.Cells export workbook with blank link target | how to use HtmlLinkTargetType.Blank in Aspose.Cells
// Developer Intent: The developer wants all hyperlinks in the HTML output generated by Aspose.Cells to open in a new browser tab without editing each link individually.
// Use Cases: Publishing an Excel‑based report on a website where external references must stay on the report page. | Creating interactive documentation from a spreadsheet that keeps the main content visible while linked resources open separately. | Building a web‑ready dashboard where users can explore linked data sources without losing the dashboard view.
// AI Prompts: Generate C# code that saves an Aspose.Cells workbook to HTML with every hyperlink rendered with target="_blank". | Explain how HtmlSaveOptions.LinkTargetType influences hyperlink behavior in the HTML produced by Aspose.Cells. | Provide a sample that adds several hyperlinks to a worksheet and configures HtmlSaveOptions so all links open in new tabs when the workbook is exported to HTML.

using System;
using Aspose.Cells;

namespace AsposeCellsLinkTargetDemo
{
    // Shows how to configure HtmlSaveOptions.LinkTargetType = HtmlLinkTargetType.Blank so that every hyperlink in the HTML file produced by Aspose.Cells includes target="_blank" and opens in a new browser tab.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add some text and a hyperlink to cell A1
            sheet.Cells["A1"].PutValue("Visit Aspose");
            sheet.Hyperlinks.Add("A1", 1, 1, "https://www.aspose.com");

            // Create HTML save options and set the link target to open in a new window/tab
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();
            saveOptions.LinkTargetType = HtmlLinkTargetType.Blank; // equivalent to target="_blank"

            // Save the workbook as an HTML file with the specified options
            workbook.Save("AsposeLinkTargetBlank.html", saveOptions);
        }
    }
}
