// Title: Export an Aspose.Cells workbook to HTML without grid lines and verify the result using C#
// AI Prompts: Generate C# code that creates a workbook with Aspose.Cells, saves it as HTML using HtmlSaveOptions with ExportGridLines set to false, and then reads the file to confirm the 'gridlines' CSS class is not present. | Write a .NET example that disables grid line rendering in an Aspose.Cells HTML export and programmatically validates that the output HTML contains no grid line markup.
// Common Searches: C# Aspose.Cells how to disable grid lines when saving to HTML | verify that exported HTML from Aspose.Cells does not contain gridlines class | Aspose.Cells HtmlSaveOptions ExportGridLines false sample code | remove grid line CSS from Aspose.Cells HTML output programmatically | check for absence of gridlines in HTML generated by Aspose.Cells workbook
// Tags: Aspose.Cells HtmlSaveOptions ExportGridLines false | C# export workbook to HTML without gridlines | disable grid line rendering in Aspose.Cells HTML export | verify HTML output for missing gridlines class | gridlines CSS class absence check in generated HTML

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook, adds sample data, saves it as HTML with ExportGridLines disabled, reads the generated file, and confirms that the 'gridlines' CSS class is absent, outputting a verification message.
class ExportGridLinesDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and access the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "DataSheet";

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Header1");
            sheet.Cells["B1"].PutValue("Header2");
            sheet.Cells["A2"].PutValue(123);
            sheet.Cells["B2"].PutValue(456);

            // Configure HTML save options: disable grid lines
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportGridLines = false // Grid lines will not be rendered
            };

            // Define output HTML file path
            string htmlPath = "ExportGridLinesFalse.html";

            // Save the workbook as HTML with the specified options
            workbook.Save(htmlPath, htmlOptions);

            // Verify that the file was created before reading
            if (!File.Exists(htmlPath))
                throw new FileNotFoundException("The HTML output file was not created.", htmlPath);

            // Read generated HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // Simple verification: check that the HTML does not contain the CSS class for grid lines
            // Aspose.Cells uses "gridlines" class when ExportGridLines is true
            bool gridLinesPresent = htmlContent.Contains("gridlines");

            if (gridLinesPresent)
                Console.WriteLine("Verification failed: Grid line elements were found in the HTML output.");
            else
                Console.WriteLine("Verification succeeded: No grid line elements are present in the HTML output.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
