// Title: How to set Arial as the default font when exporting an Excel workbook to HTML with Aspose.Cells in C#
// AI Prompts: Write C# code that loads an .xlsx file, assigns HtmlSaveOptions.DefaultFontName = "Arial", and saves the workbook as an .html file using Aspose.Cells. | Show how to change the font used in HTML output by configuring the DefaultFontName property of HtmlSaveOptions before calling Workbook.Save.
// Common Searches: How to export an Excel workbook to HTML with Arial using Aspose.Cells in C# | Aspose.Cells HtmlSaveOptions property to specify font for HTML export | C# example for setting font name when converting Excel to HTML with Aspose.Cells | Changing the default font in HTML output generated by Aspose.Cells | Using Aspose.Cells to force a specific font in HTML conversion .NET
// Tags: Aspose.Cells HtmlSaveOptions font name | C# export Excel to HTML Arial | set HtmlSaveOptions.DefaultFontName Aspose.Cells | HTML conversion font customization .NET | configure font for HTML output Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Rendering;

// Loads an Excel workbook, sets HtmlSaveOptions.DefaultFontName to "Arial", and saves the workbook as an HTML file.
class Program
{
    static void Main()
    {
        // Load the workbook (replace with your source file)
        Workbook workbook = new Workbook("input.xlsx");

        // Configure HTML save options to use Arial as the default font
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions();
        htmlOptions.DefaultFontName = "Arial";

        // Save the workbook as HTML using the configured options
        workbook.Save("output.html", htmlOptions);
    }
}
