// Title: Generate HTML from an Excel workbook with heading anchors using Aspose.Cells for .NET and verify the navigation links
// AI Prompts: Write C# code that creates bold, colored heading rows in a workbook, saves it as HTML with automatic navigation anchors via Aspose.Cells, and prints the total number of anchors found. | Adjust the HtmlSaveOptions to export only the active worksheet, then use a regular expression to confirm that each heading has a corresponding "#_Toc" link in the generated HTML.
// Common Searches: how to export Excel headings as clickable links in HTML with Aspose.Cells C# | Aspose.Cells HtmlSaveOptions navigation anchors example | C# regex to find #_Toc links in HTML generated by Aspose.Cells | verify heading navigation is included when saving workbook to HTML using Aspose.Cells | export only active worksheet to HTML with Aspose.Cells and include table of contents
// Tags: Aspose.Cells HTML navigation anchors | C# export workbook to HTML with headings | validate Aspose.Cells generated TOC links | styled Excel headings for HTML export | HtmlSaveOptions active worksheet only

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The program creates a workbook with three styled heading rows, saves it as an HTML file using Aspose.Cells (exporting only the active worksheet), then reads the HTML and uses a regular expression to count "#_Toc" navigation anchors, confirming that heading navigation links were correctly generated.
class HtmlHeadingNavigationTest
{
    static void Main()
    {
        try
        {
            // -------------------- Create Workbook --------------------
            // Create a new workbook instance.
            Workbook workbook = new Workbook();

            // Access the first worksheet.
            Worksheet sheet = workbook.Worksheets[0];

            // Insert headings at different rows.
            sheet.Cells["A1"].PutValue("Heading 1");
            sheet.Cells["A6"].PutValue("Heading 2");
            sheet.Cells["A11"].PutValue("Heading 3");

            // Apply a simple style to make them look like headings.
            Style headingStyle = workbook.CreateStyle();
            headingStyle.Font.IsBold = true;
            headingStyle.Font.Size = 14;
            headingStyle.Font.Color = System.Drawing.Color.Blue;

            // Apply the style to the heading cells.
            sheet.Cells["A1"].SetStyle(headingStyle);
            sheet.Cells["A6"].SetStyle(headingStyle);
            sheet.Cells["A11"].SetStyle(headingStyle);

            // -------------------- Save as HTML with Navigation --------------------
            // Configure HTML save options.
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportActiveWorksheetOnly = true,    // Export only the active sheet.
                ExportImagesAsBase64 = true          // Embed images as Base64 (optional).
                // Navigation links are exported by default; no explicit property needed.
            };

            // Save the workbook to an HTML file.
            string htmlPath = "ExportedWithHeadings.html";
            workbook.Save(htmlPath, htmlOptions);

            // -------------------- Load and Verify Navigation --------------------
            // Ensure the HTML file exists before reading.
            if (!File.Exists(htmlPath))
                throw new FileNotFoundException("The HTML file was not created.", htmlPath);

            // Read the generated HTML content.
            string htmlContent = File.ReadAllText(htmlPath);

            // Aspose.Cells creates navigation anchors with the pattern: href="#_Toc..."
            // Use a regular expression to find all navigation links.
            Regex navLinkRegex = new Regex(@"href\s*=\s*""#_Toc[^""]+""", RegexOptions.IgnoreCase);
            MatchCollection matches = navLinkRegex.Matches(htmlContent);

            // Output verification results.
            Console.WriteLine($"Total navigation links found: {matches.Count}");
            if (matches.Count >= 3)
            {
                Console.WriteLine("Navigation between headings is correctly exported.");
            }
            else
            {
                Console.WriteLine("Navigation links are missing or incomplete.");
            }

            // Optionally, list the found navigation anchors for debugging.
            foreach (Match match in matches)
            {
                Console.WriteLine($"Found link: {match.Value}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
