// Title: Generate HTML from an Excel workbook with SimilarBorderStyle enabled and extract the CSS to validate Firefox border fallback (C# Aspose.Cells)
// AI Prompts: Write C# code that creates a workbook, applies thick borders to a range, saves the worksheet as HTML with HtmlSaveOptions.SimilarBorderStyle set to true, and prints the CSS block extracted from the <style> tag. | Update an Aspose.Cells example to enable the SimilarBorderStyle option in HtmlSaveOptions, read the generated HTML from a memory stream, extract the CSS, and output it for inspecting border rendering in Firefox.
// Common Searches: Aspose.Cells C# export worksheet to HTML with SimilarBorderStyle for Firefox border testing | how to extract CSS from Aspose.Cells HTML output in .NET | verify thick cell borders rendering in Firefox using Aspose.Cells HTML export | enable SimilarBorderStyle option in HtmlSaveOptions C# example | debug border fallback styles in HTML generated by Aspose.Cells
// Tags: Aspose.Cells HTML similar border style option | C# extract CSS from generated HTML | Firefox border rendering verification | HtmlSaveOptions SimilarBorderStyle configuration | thick cell borders HTML output

using System;
using System.IO;
using Aspose.Cells;

// The sample creates a workbook, fills cells A1:B2, applies thick borders, saves the active worksheet as HTML with the SimilarBorderStyle flag enabled, reads the HTML from a memory stream, extracts the CSS defined inside <style> tags, and writes the CSS to the console for manual inspection of Firefox border fallback behavior.
class SimilarBorderStyleTest
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some data
            sheet.Cells["A1"].PutValue("Header 1");
            sheet.Cells["B1"].PutValue("Header 2");
            sheet.Cells["A2"].PutValue("Data 1");
            sheet.Cells["B2"].PutValue("Data 2");

            // Apply thick borders to the range A1:B2
            Style style = workbook.CreateStyle();
            style.Borders[BorderType.TopBorder].LineStyle = CellBorderType.Thick;
            style.Borders[BorderType.BottomBorder].LineStyle = CellBorderType.Thick;
            style.Borders[BorderType.LeftBorder].LineStyle = CellBorderType.Thick;
            style.Borders[BorderType.RightBorder].LineStyle = CellBorderType.Thick;
            // Horizontal and vertical inner borders are not required for this example

            // Apply the style to the range
            Aspose.Cells.Range range = sheet.Cells.CreateRange("A1:B2");
            range.ApplyStyle(style, new StyleFlag { Borders = true });

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                ExportActiveWorksheetOnly = true
            };

            // Save to a memory stream to avoid file I/O for inspection
            using (MemoryStream htmlStream = new MemoryStream())
            {
                workbook.Save(htmlStream, saveOptions);
                htmlStream.Position = 0;

                // Read the generated HTML as text
                string htmlContent;
                using (StreamReader reader = new StreamReader(htmlStream))
                {
                    htmlContent = reader.ReadToEnd();
                }

                // Extract CSS block (between <style> tags)
                string css = ExtractCss(htmlContent);

                // Output CSS to console for inspection
                Console.WriteLine("=== Extracted CSS ===");
                Console.WriteLine(css);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }

    // Helper method to extract CSS from HTML content
    private static string ExtractCss(string html)
    {
        const string styleStartTag = "<style type=\"text/css\">";
        const string styleEndTag = "</style>";

        int startIdx = html.IndexOf(styleStartTag, StringComparison.OrdinalIgnoreCase);
        if (startIdx == -1) return string.Empty;
        startIdx += styleStartTag.Length;

        int endIdx = html.IndexOf(styleEndTag, startIdx, StringComparison.OrdinalIgnoreCase);
        if (endIdx == -1) return string.Empty;

        return html.Substring(startIdx, endIdx - startIdx).Trim();
    }
}
