// Title: Aspose.Cells C# – Export Workbook to MHTML with IsIECompatible = false for Chrome
// Description: Creates a workbook, sets HtmlSaveOptions.IsIECompatible to false, and saves it as an .mht file so the output renders with standard HTML in Google Chrome and other modern browsers.
// Keywords: Aspose.Cells MHTML export | HtmlSaveOptions IsIECompatible false | C# save workbook as .mht | Chrome MHTML rendering | disable IE compatibility Aspose | standard HTML output | Excel to MHTML conversion
// Common Searches: Aspose.Cells export to MHTML without IE mode | IsIECompatible false C# Aspose example | How to view .mht generated by Aspose.Cells in Chrome | MHTML output options Aspose.Cells | Save Excel as .mht C#
// Developer Intent: Generate an MHTML file from an Excel workbook while turning off IE‑specific markup to achieve clean, standards‑compliant rendering in Chrome.
// Use Cases: Embed workbook data in email bodies using MHTML that displays correctly in modern browsers. | Produce cross‑browser reports (Chrome, Firefox, Edge) without IE conditional comments. | Automated testing of MHTML output to verify absence of IE‑only meta tags.
// AI Prompts: Write C# code that loads an existing Excel file and saves it as MHTML with HtmlSaveOptions.IsIECompatible set to false. | Explain how to programmatically inspect a saved .mht file for IE‑specific meta tags or conditional comments. | Show how to launch Google Chrome from C# to open the generated MHTML file and capture a screenshot for verification.

using System;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Creates a workbook, sets HtmlSaveOptions.IsIECompatible to false, and saves it as an .mht file so the output renders with standard HTML in Google Chrome and other modern browsers.
    public class MhtmlIsIECompatibleDemo
    {
        public static void Main()
        {
            try
            {
                Run();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        public static void Run()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add sample data to the worksheet
            sheet.Cells["A1"].PutValue("MHTML Output Test");
            sheet.Cells["A2"].PutValue(DateTime.Now);

            // Configure HTML save options for MHTML output
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                // Disable IE compatibility mode to ensure standard rendering
                IsIECompatible = false
                // No need to set SaveFormat; the file extension determines MHTML output
            };

            // Save the workbook as MHTML using the specified options
            workbook.Save("MhtmlOutput.mht", saveOptions);

            Console.WriteLine("MHTML file saved with IsIECompatible = false");
        }
    }
}
