// Title: Export Excel to HTML with fallback border styles using HtmlSaveOptions.ExportSimilarBorderStyle (C#)
// Description: Demonstrates how to create a workbook, apply double, medium dash‑dot‑dot, and thin borders, enable ExportSimilarBorderStyle and IsIECompatible, and save the file as HTML that gracefully degrades unsupported border types for legacy browsers.
// Keywords: Aspose.Cells ExportSimilarBorderStyle | HtmlSaveOptions C# | HTML border fallback | .NET Excel to HTML | legacy browser compatibility | IsIECompatible | border style mapping
// Common Searches: Aspose.Cells ExportSimilarBorderStyle example | C# save Excel as HTML with IE compatible borders | how to fallback double border in HTML export | HtmlSaveOptions similar border style legacy browsers | generate HTML from workbook with border fallback
// Developer Intent: Export an Excel workbook to HTML while providing fallback border styles that render correctly in older browsers.
// Use Cases: Produce HTML reports that preserve visual layout when browsers lack support for complex border types. | Ensure HTML output works in Internet Explorer 8‑11 by enabling IE‑compatible rendering. | Automatically map unsupported borders (e.g., Double, MediumDashDotDot) to the nearest supported style during export.
// AI Prompts: Show how to customize the CSS generated by ExportSimilarBorderStyle for specific border types. | Create a unit test that confirms the HTML contains fallback border styles for double and medium dash‑dot‑dot borders. | Explain the algorithm Aspose.Cells uses to select a similar border style when ExportSimilarBorderStyle is true.

using System;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Demonstrates how to create a workbook, apply double, medium dash‑dot‑dot, and thin borders, enable ExportSimilarBorderStyle and IsIECompatible, and save the file as HTML that gracefully degrades unsupported border types for legacy browsers.
    public class ExportSimilarBorderStyleDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Add sample data with borders that are not widely supported by older browsers
                // (e.g., Double and MediumDashDotDot)
                sheet.Cells["A1"].PutValue("Double Border");
                sheet.Cells["A1"].SetStyle(CreateBorderStyle(workbook, CellBorderType.Double));

                sheet.Cells["B2"].PutValue("MediumDashDotDot Border");
                sheet.Cells["B2"].SetStyle(CreateBorderStyle(workbook, CellBorderType.MediumDashDotDot));

                sheet.Cells["C3"].PutValue("Thin Border (supported)");
                sheet.Cells["C3"].SetStyle(CreateBorderStyle(workbook, CellBorderType.Thin));

                // Configure HTML save options
                HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
                {
                    // Enable fallback (similar) border style for browsers that don't support the original style
                    ExportSimilarBorderStyle = true,

                    // Optional: make the output compatible with legacy IE browsers
                    IsIECompatible = true
                };

                // Save the workbook as HTML using the configured options
                workbook.Save("ExportSimilarBorderStyle.html", htmlOptions);
                Console.WriteLine("HTML file 'ExportSimilarBorderStyle.html' has been created successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }

        // Helper method to create a style with the same border type on all sides
        private static Style CreateBorderStyle(Workbook wb, CellBorderType borderType)
        {
            Style style = wb.CreateStyle();
            style.Borders[BorderType.TopBorder].LineStyle = borderType;
            style.Borders[BorderType.BottomBorder].LineStyle = borderType;
            style.Borders[BorderType.LeftBorder].LineStyle = borderType;
            style.Borders[BorderType.RightBorder].LineStyle = borderType;
            return style;
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            ExportSimilarBorderStyleDemo.Run();
        }
    }
}
