// Title: Aspose.Cells C# – Export to HTML with HtmlCrossType.Default and AddTooltipText for full cell tooltips
// Description: Demonstrates how to save an Excel workbook as HTML using HtmlCrossType.Default while enabling AddTooltipText. The example inserts a long string, narrows the column to force overflow, and generates HTML that keeps the overflow appearance and shows the complete text in a hover tooltip.
// Keywords: Aspose.Cells HtmlCrossType.Default | AddTooltipText | C# HTML export | cell tooltip overflow | Excel to HTML Aspose | preserve cell overflow
// Common Searches: Aspose.Cells enable tooltip for truncated cells | HtmlCrossType.Default vs Css overflow Aspose | AddTooltipText example C# | export Excel to HTML with hover tooltip | keep Excel overflow behavior in HTML
// Developer Intent: Add hover tooltips that reveal the full text of overflowed cells while retaining the original overflow layout in the generated HTML.
// Use Cases: Web reports that need compact columns but still allow users to read full values on hover. | Interactive dashboards where long cell content is hidden by default but accessible via tooltips. | Generating HTML versions of spreadsheets that mimic Excel’s overflow rendering for better UX.
// AI Prompts: Create C# code to customize the CSS style of tooltips generated by AddTooltipText in Aspose.Cells HTML export. | Show how to produce a single self‑contained HTML file with embedded resources while keeping AddTooltipText active. | Explain how to conditionally enable AddTooltipText only for cells whose text length exceeds a given limit.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlTooltipDemo
{
    // Demonstrates how to save an Excel workbook as HTML using HtmlCrossType.Default while enabling AddTooltipText. The example inserts a long string, narrows the column to force overflow, and generates HTML that keeps the overflow appearance and shows the complete text in a hover tooltip.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Put a long text into a cell that will exceed the column width
            worksheet.Cells["A1"].PutValue("This is a very long text that will exceed the column width and we want to see the full content via tooltip.");

            // Set a narrow column width to force overflow
            worksheet.Cells.SetColumnWidth(0, 10); // width in characters

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Use the default HTML cross type (behaves like Excel)
            htmlOptions.HtmlCrossStringType = HtmlCrossType.Default;
            // Enable tooltip text for cells where content is truncated
            htmlOptions.AddTooltipText = true;

            // Save the workbook as HTML with the specified options
            string outputPath = "output_with_tooltip.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"HTML file saved to: {outputPath}");
        }
    }
}
