// Title: Export an Excel workbook to HTML with full‑cell tooltips while preserving column overflow using Aspose.Cells HtmlSaveOptions (AddTooltipText)
// AI Prompts: Write a C# console program that creates a Workbook, inserts long strings into cells, narrows column widths, sets HtmlSaveOptions.HtmlCrossType to Default, enables AddTooltipText, and saves the workbook as an HTML file so the complete cell value appears as a hover tooltip without changing the overflow layout. | Update an existing Aspose.Cells HTML export routine to keep the original cell overflow and add hover tooltips that reveal the full cell content by configuring HtmlCrossType.Default and setting AddTooltipText = true.
// Common Searches: Aspose.Cells C# export to HTML keep cell overflow and show tooltip with full text | how to enable AddTooltipText in HtmlSaveOptions for HTML export | HtmlCrossType.Default tooltip example Aspose.Cells | preserve column width overflow when converting Excel to HTML using Aspose | show full cell content on hover in HTML generated by Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions AddTooltipText | HtmlCrossType.Default configuration | preserve cell overflow in HTML export | full cell tooltip on hover | C# export Excel to HTML with tooltip | long text cells HTML rendering Aspose

using System;
using Aspose.Cells;

// // Demonstrates creating a workbook, adding long text to cells, adjusting column widths to cause overflow, enabling AddTooltipText with HtmlCrossType.Default, and saving as HTML so the full cell content is displayed in a tooltip while the original overflow appearance is retained.
class HtmlExportWithTooltip
{
    static void Main()
    {
        try
        {
            // Create a new workbook and access the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate cells with long text to demonstrate overflow and tooltip
            sheet.Cells["A1"].PutValue("This is a very long text that will overflow the cell width when exported to HTML.");
            sheet.Cells["B2"].PutValue("Another lengthy piece of content that exceeds the default column width.");

            // Adjust column widths to cause overflow (optional)
            sheet.Cells.SetColumnWidth(0, 15); // Column A
            sheet.Cells.SetColumnWidth(1, 15); // Column B

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                // Enable tooltip text to show full cell content on hover
                AddTooltipText = true
            };

            // Save the workbook as an HTML file with the specified options
            string outputPath = "ExportWithTooltip.html";
            workbook.Save(outputPath, saveOptions);
            Console.WriteLine($"HTML file saved to {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
