// Title: C# – Export Excel to HTML with FitToCell and Tooltip using Aspose.Cells
// Description: Demonstrates how to create a workbook, insert a long string into a cell, narrow the column to force overflow, and save the sheet as HTML with HtmlCrossType.FitToCell and AddTooltipText enabled so the visible text fits the cell while the full content appears on mouse‑over.
// Keywords: Aspose.Cells | C# HTML export | HtmlCrossType.FitToCell | AddTooltipText | cell overflow tooltip | Excel to HTML | compact HTML report
// Common Searches: Aspose.Cells FitToCell tooltip example | show full cell text on hover HTML export | prevent overflow in HTML output Aspose.Cells | C# export Excel to HTML with tooltip | HtmlSaveOptions AddTooltipText usage
// Developer Intent: Export a worksheet to HTML where long cell values are truncated to the cell width but displayed in a tooltip when the user hovers over the cell.
// Use Cases: Compact HTML dashboards with narrow columns while keeping detailed data accessible via hover. | Product catalogs where long descriptions are hidden in the table view but revealed on mouse‑over. | Invoice or report HTML files that hide notes/comments in cells yet allow quick viewing through tooltips.
// AI Prompts: Generate C# code that saves an Aspose.Cells workbook to HTML using HtmlCrossType.FitToCell and AddTooltipText. | Explain the interaction between HtmlCrossType.FitToCell and AddTooltipText for handling overflow text. | Suggest HtmlSaveOptions settings to style or position the tooltip generated by Aspose.Cells.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlFitToCellTooltipDemo
{
    // Demonstrates how to create a workbook, insert a long string into a cell, narrow the column to force overflow, and save the sheet as HTML with HtmlCrossType.FitToCell and AddTooltipText enabled so the visible text fits the cell while the full content appears on mouse‑over.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Put a long text into a cell that will exceed the column width
            worksheet.Cells["A1"].PutValue("This is a very long text that will not fit into the cell width and we want to see the full content on hover.");

            // Set a narrow column width to force overflow
            worksheet.Cells.SetColumnWidth(0, 10); // Column A width

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            // Use FitToCell to display only the part of the text that fits inside the cell
            saveOptions.HtmlCrossStringType = HtmlCrossType.FitToCell;
            // Enable tooltip so the full text appears when the user hovers over the cell
            saveOptions.AddTooltipText = true;

            // Save the workbook as HTML with the specified options
            string outputPath = "FitToCellWithTooltip.html";
            workbook.Save(outputPath, saveOptions);

            Console.WriteLine("HTML file saved with HtmlCrossType.FitToCell and tooltip enabled: " + outputPath);
        }
    }
}
