// Title: C# Export Excel to HTML with Embedded CSS using Aspose.Cells (ExportWorksheetCSSSeparately = false)
// Description: Shows how to create a workbook, set HtmlSaveOptions.ExportWorksheetCSSSeparately to false, save it as HTML, and programmatically confirm that the output contains a <style> block and no external CSS <link> reference.
// Keywords: Aspose.Cells | C# HTML export | embedded CSS | ExportWorksheetCSSSeparately | inline CSS | verify HTML output | no external CSS file | Aspose.Cells HtmlSaveOptions | Excel to HTML | self‑contained HTML report
// Common Searches: Aspose.Cells embed CSS in HTML | ExportWorksheetCSSSeparately false example | C# save workbook as HTML with inline CSS | check for <style> tag in Aspose.Cells HTML output | prevent external CSS file Aspose.Cells
// Developer Intent: Generate a single HTML file with all worksheet styling embedded, eliminating separate CSS files.
// Use Cases: Create a portable HTML report for email or offline viewing without external resources. | Automate validation that Aspose.Cells HTML export embeds CSS correctly. | Deploy self‑contained HTML snapshots of Excel worksheets in web applications.
// AI Prompts: Write C# code using Aspose.Cells to export a workbook to HTML with embedded CSS (ExportWorksheetCSSSeparately = false) and verify the presence of a <style> tag and absence of <link> tags. | Explain how to programmatically check that the HTML generated by Aspose.Cells contains inline CSS and does not create external CSS files. | Show how to locate the saved HTML file, read its contents, and confirm CSS embedding using Aspose.Cells in a .NET console application.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlExportDemo
{
    // Shows how to create a workbook, set HtmlSaveOptions.ExportWorksheetCSSSeparately to false, save it as HTML, and programmatically confirm that the output contains a <style> block and no external CSS <link> reference.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Embedded CSS Test");

            // Initialize HtmlSaveOptions and ensure CSS is not exported separately
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(); // create HtmlSaveOptions
            saveOptions.ExportWorksheetCSSSeparately = false;   // set property as required

            // Define output HTML path
            string htmlPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "EmbeddedCssOutput.html");

            // Save the workbook as HTML using the options
            workbook.Save(htmlPath, saveOptions); // save workbook

            // Load the generated HTML file as text
            string htmlContent = File.ReadAllText(htmlPath);

            // Verify that CSS is embedded (look for a <style> block)
            bool hasEmbeddedCss = htmlContent.Contains("<style") && htmlContent.Contains("</style>");

            // Verify that there is no separate CSS file reference (e.g., link tag)
            bool hasSeparateCssLink = htmlContent.Contains("<link") && htmlContent.Contains(".css");

            Console.WriteLine($"HTML file saved to: {htmlPath}");
            Console.WriteLine($"Embedded CSS detected: {hasEmbeddedCss}");
            Console.WriteLine($"Separate CSS link detected: {hasSeparateCssLink}");
            Console.WriteLine("Result: " + (hasEmbeddedCss && !hasSeparateCssLink
                ? "CSS is correctly embedded within the HTML."
                : "CSS embedding verification failed."));
        }
    }
}
