// Title: Export Each Worksheet to Separate CSS Files with Aspose.Cells HtmlSaveOptions in C#
// Description: Demonstrates how to create a multi‑sheet workbook, enable HtmlSaveOptions.ExportWorksheetCSSSeparately, save the workbook as HTML on the desktop, and verify that each worksheet generates its own CSS file (e.g., sheet001.css, sheet002.css).
// Keywords: Aspose.Cells | HtmlSaveOptions | ExportWorksheetCSSSeparately | C# | separate CSS per worksheet | Excel to HTML | sheet001.css | multi‑sheet workbook export | .NET Excel HTML conversion | verify generated CSS files
// Common Searches: Aspose.Cells export each worksheet to its own CSS file | HtmlSaveOptions ExportWorksheetCSSSeparately C# example | how to generate sheet001.css sheet002.css with Aspose.Cells | verify CSS file count after saving workbook as HTML | C# code to export Excel workbook to HTML with separate CSS per sheet
// Developer Intent: Produce HTML output where every worksheet has an individual CSS file and programmatically confirm that the number of CSS files matches the worksheet count.
// Use Cases: Export a multi‑sheet Excel workbook to HTML with distinct styling files for each sheet. | Automate validation that each worksheet creates a corresponding CSS file after HTML export. | List or process the generated HTML and CSS files for publishing or further manipulation.
// AI Prompts: Write C# code using Aspose.Cells to save a workbook as HTML with ExportWorksheetCSSSeparately set to true and then check that the number of sheet*.css files equals the worksheet count. | Explain the naming convention of CSS files generated by Aspose.Cells when ExportWorksheetCSSSeparately is enabled and how to locate them on the file system. | Create a C# unit test that asserts the count of generated sheet*.css files matches the workbook's worksheet count after HTML export.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlExportDemo
{
    // Demonstrates how to create a multi‑sheet workbook, enable HtmlSaveOptions.ExportWorksheetCSSSeparately, save the workbook as HTML on the desktop, and verify that each worksheet generates its own CSS file (e.g., sheet001.css, sheet002.css).
    class Program
    {
        static void Main()
        {
            // Create a new workbook with two worksheets
            Workbook workbook = new Workbook();
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "FirstSheet";
            sheet1.Cells["A1"].PutValue("Data in first sheet");

            Worksheet sheet2 = workbook.Worksheets.Add("SecondSheet");
            sheet2.Cells["B2"].PutValue("Data in second sheet");

            // Configure HTML save options to export CSS for each worksheet separately
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();
            saveOptions.ExportWorksheetCSSSeparately = true; // each sheet gets its own .css file

            // Define output folder (desktop) and ensure it exists
            string outputFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.Desktop),
                "AsposeHtmlExport");
            Directory.CreateDirectory(outputFolder);

            // Save the workbook as HTML (multiple files will be created)
            string htmlPath = Path.Combine(outputFolder, "Workbook.html");
            workbook.Save(htmlPath, saveOptions);

            // Verify that each worksheet has its own CSS file
            // CSS files are named like sheet001.css, sheet002.css, etc.
            string[] cssFiles = Directory.GetFiles(outputFolder, "sheet*.css");
            int expectedCssCount = workbook.Worksheets.Count;

            Console.WriteLine($"Expected CSS files: {expectedCssCount}");
            Console.WriteLine($"Found CSS files: {cssFiles.Length}");

            if (cssFiles.Length == expectedCssCount)
            {
                Console.WriteLine("Verification succeeded: each worksheet has its own CSS file.");
                foreach (string cssFile in cssFiles)
                {
                    Console.WriteLine($" - {Path.GetFileName(cssFile)}");
                }
            }
            else
            {
                Console.WriteLine("Verification failed: CSS file count does not match worksheet count.");
            }

            // Optionally, list the generated HTML files
            string[] htmlFiles = Directory.GetFiles(outputFolder, "*.html");
            Console.WriteLine("\nGenerated HTML files:");
            foreach (string file in htmlFiles)
            {
                Console.WriteLine($" - {Path.GetFileName(file)}");
            }
        }
    }
}
