// Title: How to embed worksheet CSS directly into HTML using Aspose.Cells HtmlSaveOptions in C#
// AI Prompts: Generate C# code that creates an Aspose.Cells workbook, fills it with data, and saves it as an HTML file with CSS embedded by setting HtmlSaveOptions.ExportWorksheetCSSSeparately to false. | Add logic to read the saved HTML file and programmatically confirm that a <style> element containing the worksheet CSS is present. | Modify the example to export several worksheets into one HTML document while keeping all CSS inline. | Show how to customize the embedded CSS (e.g., change fonts or colors) before saving the workbook as HTML.
// Common Searches: Aspose.Cells C# export workbook to HTML with inline CSS | HtmlSaveOptions ExportWorksheetCSSSeparately false sample code | verify embedded style tag in HTML generated by Aspose.Cells | prevent external CSS files when converting Excel to HTML using Aspose.Cells | save multiple worksheets to a single HTML file with embedded styles Aspose.Cells
// Tags: Aspose.Cells HtmlSaveOptions embed CSS | ExportWorksheetCSSSeparately false inline styles | C# save workbook as HTML with embedded stylesheet | verify style tag in Aspose.Cells HTML output | multiple worksheets single HTML Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The program creates an Aspose.Cells workbook, populates sample data, and saves it as an HTML file with the worksheet CSS embedded by setting ExportWorksheetCSSSeparately = false. It then reads the generated HTML to confirm that a <style> block is present, demonstrating how to produce inline CSS and optionally combine multiple worksheets into one HTML document.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Name = "SampleSheet";

        // Populate cells with data
        sheet.Cells["A1"].PutValue("Header 1");
        sheet.Cells["B1"].PutValue("Header 2");
        sheet.Cells["A2"].PutValue(123);
        sheet.Cells["B2"].PutValue(456.78);
        sheet.Cells["A3"].PutValue(DateTime.Now);
        sheet.Cells["B3"].PutValue(true);

        // Configure HTML save options to embed CSS within the HTML
        HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html);
        htmlOptions.ExportWorksheetCSSSeparately = false; // CSS will be embedded

        // Define output HTML file path
        string outputPath = "EmbeddedCssOutput.html";

        // Save the workbook as HTML with the specified options
        workbook.Save(outputPath, htmlOptions);

        // Verify that CSS is embedded by checking for a <style> tag in the generated HTML
        string htmlContent = File.ReadAllText(outputPath);
        bool cssEmbedded = htmlContent.Contains("<style") && htmlContent.Contains("</style>");

        // Output verification result
        Console.WriteLine($"HTML file saved to: {Path.GetFullPath(outputPath)}");
        Console.WriteLine($"CSS embedded within HTML: {cssEmbedded}");
    }
}
