// Title: C# – Validate TableCssId prefix in Aspose.Cells HTML export
// Description: Creates a workbook, sets HtmlSaveOptions.TableCssId to a custom value, saves as HTML, reads the file and uses a case‑insensitive regular expression to confirm the <table> element contains the expected TableCssId attribute, then prints the result.
// Keywords: Aspose.Cells | HtmlSaveOptions.TableCssId | C# HTML export validation | regex TableCssId check | HTML validation Aspose.Cells
// Common Searches: Aspose.Cells verify TableCssId in exported HTML | C# regex to check table CSS id in Aspose.Cells HTML | How to validate TableCssId attribute after saving workbook as HTML | Automated HTML validation for Aspose.Cells output
// Developer Intent: Ensure the HTML generated by Aspose.Cells includes the specified TableCssId prefix on the <table> element.
// Use Cases: Add an automated test that fails when the exported HTML lacks the custom TableCssId, ensuring consistent styling identifiers. | Integrate a validation step into CI/CD pipelines to detect missing or incorrect TableCssId values after workbook export. | Debug styling issues by programmatically confirming the TableCssId attribute in the generated HTML.
// AI Prompts: Generate a C# unit test (NUnit/MSTest) that asserts the TableCssId attribute in the exported HTML matches a given prefix. | Write a PowerShell script that runs an HTML validator on the Aspose.Cells output and reports missing TableCssId attributes. | Create a reusable C# method that takes an HTML file path and a TableCssId prefix and returns a boolean indicating presence of the prefix on the <table> element.

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

namespace AsposeCellsHtmlTableCssIdValidation
{
    // Creates a workbook, sets HtmlSaveOptions.TableCssId to a custom value, saves as HTML, reads the file and uses a case‑insensitive regular expression to confirm the <table> element contains the expected TableCssId attribute, then prints the result.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);

            // Configure HTML save options with a custom TableCssId prefix
            HtmlSaveOptions saveOptions = new HtmlSaveOptions(SaveFormat.Html);
            saveOptions.TableCssId = "custom-table-style";

            // Define the output HTML file path
            string htmlPath = Path.Combine(Environment.CurrentDirectory, "output.html");

            // Save the workbook as HTML using the configured options
            workbook.Save(htmlPath, saveOptions);

            // Read the generated HTML content
            string htmlContent = File.ReadAllText(htmlPath);

            // Define a regex to locate the <table> element that contains the TableCssId attribute
            string pattern = @"<table[^>]*\bTableCssId\s*=\s*[""']custom-table-style[""']";
            bool isValid = Regex.IsMatch(htmlContent, pattern, RegexOptions.IgnoreCase);

            // Output validation result
            Console.WriteLine(isValid
                ? "Validation passed: Table element contains the correct TableCssId prefix."
                : "Validation failed: Table element does not contain the expected TableCssId prefix.");
        }
    }
}
