// Title: Export an Aspose.Cells workbook to HTML without downlevel revealed comments and verify Base64 images and table data
// AI Prompts: Write C# code that creates a workbook, adds sample data and a chart, and saves it as HTML using Aspose.Cells HtmlSaveOptions with downlevel revealed comments turned off and images embedded as Base64. | Add logic to read the generated HTML file and assert that no <![if] comments are present, that image tags contain data:image Base64 strings, and that the original worksheet cell values appear in the HTML.
// Common Searches: Aspose.Cells how to turn off downlevel revealed comments when saving to HTML | C# verify Base64 chart images in HTML output from Aspose.Cells | Check that table data is exported correctly in HTML generated by Aspose.Cells | Example of using HtmlSaveOptions.DisableDownlevelRevealedComments in .NET
// Tags: Aspose.Cells HtmlSaveOptions DisableDownlevelRevealedComments | Aspose.Cells HtmlSaveOptions ExportImagesAsBase64 | Validate HTML output for missing downlevel comments Aspose.Cells | C# verify table data in HTML generated by Aspose.Cells | Chart image embedding as Base64 in Aspose.Cells HTML export

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// The program builds a workbook with sample data and a column chart, saves it to HTML using HtmlSaveOptions with downlevel revealed comments disabled and images embedded as Base64, then reads the output file to confirm that no downlevel comments exist, Base64 images are present, and the original table data is correctly exported.
class DownlevelCommentValidation
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Value");
            sheet.Cells["A2"].PutValue("A");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["A3"].PutValue("B");
            sheet.Cells["B3"].PutValue(20);
            sheet.Cells["A4"].PutValue("C");
            sheet.Cells["B4"].PutValue(30);

            // Add a simple column chart
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 15, 5);
            Chart chart = sheet.Charts[chartIndex];
            chart.NSeries.Add("B2:B4", true);
            // Category data line removed – not required for this example

            // Configure HTML save options: disable downlevel revealed comments
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions(SaveFormat.Html)
            {
                DisableDownlevelRevealedComments = true, // Omit downlevel comments
                ExportImagesAsBase64 = true               // Embed images as Base64
            };

            // Define output HTML file path
            string htmlPath = "output.html";

            // Save the workbook as HTML
            workbook.Save(htmlPath, htmlOptions);

            // Verify that the HTML file was created
            if (!File.Exists(htmlPath))
            {
                Console.WriteLine($"Error: The file '{htmlPath}' was not found.");
                return;
            }

            // Load the generated HTML content for validation
            string htmlContent;
            try
            {
                htmlContent = File.ReadAllText(htmlPath);
            }
            catch (Exception readEx)
            {
                Console.WriteLine($"Failed to read HTML file: {readEx.Message}");
                return;
            }

            // Validate that downlevel revealed comments are not present
            if (htmlContent.Contains("<![if"))
                Console.WriteLine("Validation Failed: Downlevel revealed comments are present.");
            else
                Console.WriteLine("Validation Passed: Downlevel revealed comments are disabled.");

            // Validate that embedded images are present
            if (htmlContent.Contains("data:image"))
                Console.WriteLine("Validation Passed: Embedded images are present.");
            else
                Console.WriteLine("Validation Failed: Embedded images are missing.");

            // Ensure that table data is exported
            if (htmlContent.Contains("Category") && htmlContent.Contains("Value"))
                Console.WriteLine("Validation Passed: Table data is present.");
            else
                Console.WriteLine("Validation Failed: Table data is missing.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An unexpected error occurred: {ex.Message}");
        }
    }
}
