// Title: Verify that Aspose.Cells HTML export uses only standard comment tags and excludes downlevel-revealed conditional comments in C#
// AI Prompts: Write a C# program that saves an Aspose.Cells workbook as HTML, reads the generated markup, and checks that it contains only regular <!-- --> comments. | Create a C# method that uses a regular expression to detect IE downlevel-revealed conditional comments (<!--[if ...]> ... <![endif]-->) in HTML produced by Aspose.Cells. | Develop a C# snippet that streams an Aspose.Cells workbook to HTML, scans the output for conditional comment patterns, and outputs a verification result to the console.
// Common Searches: c# how to ensure Aspose.Cells HTML export does not include IE conditional comments | detect downlevel-revealed conditional comments in HTML generated by Aspose.Cells using regex | verify standard HTML comment tags in Aspose.Cells saved HTML file c#
// Tags: Aspose.Cells HTML export comment validation | C# regex downlevel conditional comments | standard HTML comment detection in generated markup | save workbook to HTML without IE conditional comments | verify HTML output from Aspose.Cells

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The example creates a workbook, saves it to HTML via Aspose.Cells into a memory stream, reads the HTML as a string, applies a regular expression to detect downlevel-revealed conditional comments, and writes to the console whether only standard comment tags are present.
class HtmlCommentVerifier
{
    static void Main()
    {
        // Create a new workbook and add some data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Hello");
        sheet.Cells["B1"].PutValue("World");

        // Save the workbook to HTML in a memory stream
        using (MemoryStream htmlStream = new MemoryStream())
        {
            workbook.Save(htmlStream, SaveFormat.Html);
            htmlStream.Position = 0;

            // Read the generated HTML as a string
            string htmlContent;
            using (StreamReader reader = new StreamReader(htmlStream, Encoding.UTF8))
            {
                htmlContent = reader.ReadToEnd();
            }

            // Define a regex pattern for downlevel-revealed conditional comments
            // Pattern matches <!--[if ...]> ... <![endif]-->
            string downlevelPattern = @"<!--\s*\[if[^\]]*\]>.*?<!\s*\[endif\]\s*-->";
            bool containsDownlevel = Regex.IsMatch(htmlContent, downlevelPattern, RegexOptions.Singleline | RegexOptions.IgnoreCase);

            // Verify that only standard comment tags are present
            if (containsDownlevel)
            {
                Console.WriteLine("HTML contains downlevel-revealed comment tags.");
            }
            else
            {
                Console.WriteLine("HTML contains only standard comment tags.");
            }
        }
    }
}
