// Title: Validate that HTML produced by Aspose.Cells in C# contains only standard comment tags and excludes downlevel revealed conditional comments
// AI Prompts: Create a C# program using Aspose.Cells to save a workbook as HTML in a MemoryStream, then use a regular expression to confirm the markup has no <![if ...]> conditional comment blocks. | Write C# code that generates an HTML file from an Aspose.Cells workbook, reads the HTML string, and reports whether only regular <!-- comment --> tags are present.
// Common Searches: c# aspocells save workbook as html without conditional comments | detect downlevel revealed comments in html generated by Aspose.Cells using regex | how to verify standard HTML comment tags in Aspose.Cells HTML output | remove <![if]> conditional comment sections from Aspose.Cells exported HTML
// Tags: validate Aspose.Cells HTML comments | C# regex for conditional comment detection | inspect HTML from MemoryStream | standard comment tag verification | export workbook to HTML without downlevel tags

using System;
using System.IO;
using System.Text.RegularExpressions;
using Aspose.Cells;

// The example creates a new Aspose.Cells workbook, adds sample data, saves it as HTML into a MemoryStream, reads the HTML content as a string, and uses regular expressions to detect any downlevel revealed conditional comment patterns (e.g., <!--[if ...]> or <![endif]-->). It then writes to the console whether only standard <!-- comment --> tags are present.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some data
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].PutValue("Sample Text");

        // Save the workbook as HTML into a memory stream
        using (MemoryStream htmlStream = new MemoryStream())
        {
            workbook.Save(htmlStream, SaveFormat.Html);
            htmlStream.Position = 0;

            // Read the HTML content as a string
            string htmlContent;
            using (StreamReader reader = new StreamReader(htmlStream))
            {
                htmlContent = reader.ReadToEnd();
            }

            // Check for downlevel revealed comment tags (e.g., <!--[if ...]> ... <![endif]-->)
            bool containsDownlevelComments = Regex.IsMatch(htmlContent, @"<!--\s*\[if", RegexOptions.IgnoreCase) ||
                                             Regex.IsMatch(htmlContent, @"<!\s*\[endif\]-->", RegexOptions.IgnoreCase);

            if (containsDownlevelComments)
            {
                Console.WriteLine("HTML output contains downlevel revealed comment tags.");
            }
            else
            {
                Console.WriteLine("HTML output contains only standard comment tags.");
            }
        }
    }
}
