// Title: Validate that HTML export with ExportImagesAsBase64 = false creates only one image file in Aspose.Cells for .NET (C#)
// Description: This C# example builds a workbook, inserts a 10×10 PNG picture, and saves it as HTML using Aspose.Cells with HtmlSaveOptions.ExportImagesAsBase64 set to false and IsExpImageToTempDir disabled. After conversion it scans the output directory for files matching the default pattern (image*.*) and confirms that exactly one image file was generated, reporting success or failure.
// Keywords: Aspose.Cells HTML export | ExportImagesAsBase64 false | duplicate image files | C# Aspose.Cells example | .NET workbook to HTML | image0.* naming | verify image count | prevent image duplication
// Common Searches: Aspose.Cells HTML export single image file | ExportImagesAsBase64 false duplicate images | how to check image files after saving workbook as HTML | C# verify image count Aspose.Cells HTML conversion | prevent multiple image files Aspose.Cells
// Developer Intent: Ensure that converting a workbook to HTML with ExportImagesAsBase64 disabled produces exactly one image file and no duplicates.
// Use Cases: Automated unit test that asserts a single image file after HTML export of a worksheet containing one picture. | CI/CD validation step that fails the build if more than one image file appears in the export folder. | Diagnostic script for troubleshooting unexpected duplicate images during Aspose.Cells HTML conversion.
// AI Prompts: Generate an xUnit test that confirms Aspose.Cells HTML export with ExportImagesAsBase64 = false creates only one image file. | Write a PowerShell snippet to run the compiled program, locate the output directory, and report any duplicate image files named image*.*. | Explain the impact of setting IsExpImageToTempDir to false on image file location and duplication during HTML conversion.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// This C# example builds a workbook, inserts a 10×10 PNG picture, and saves it as HTML using Aspose.Cells with HtmlSaveOptions.ExportImagesAsBase64 set to false and IsExpImageToTempDir disabled. After conversion it scans the output directory for files matching the default pattern (image*.*) and confirms that exactly one image file was generated, reporting success or failure.
class VerifyNoDuplicateImages
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Red 10x10 PNG image (base64 encoded)
            const string base64Png = "iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFklEQVQoU2NkYGD4z0AEYBxVSFIAAQAA//8DAF6cB6cAAAAASUVORK5CYII=";
            byte[] pngBytes = Convert.FromBase64String(base64Png);

            // Add the image to the worksheet (row 0, column 0)
            using (MemoryStream imgStream = new MemoryStream(pngBytes))
            {
                sheet.Pictures.Add(0, 0, imgStream);
            }

            // Configure HTML save options: export images as separate files (not Base64)
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                ExportImagesAsBase64 = false,
                // Ensure images are written to the same folder as the HTML file
                IsExpImageToTempDir = false
            };

            // Define output HTML file path
            string htmlPath = "output.html";

            // Save the workbook as HTML using the configured options
            workbook.Save(htmlPath, htmlOptions);

            // Determine the folder where images are saved (same as HTML file folder)
            string outputFolder = Path.GetDirectoryName(Path.GetFullPath(htmlPath));
            if (outputFolder == null)
                outputFolder = Directory.GetCurrentDirectory();

            // Find all image files generated by the conversion (default naming: image0.*, image1.*, …)
            string[] imageFiles = Directory.GetFiles(outputFolder, "image*.*");
            int imageCount = imageFiles.Length;

            // Verify that only one image file exists (no duplicates)
            if (imageCount == 1)
            {
                Console.WriteLine("Success: Only one image file was created.");
            }
            else
            {
                Console.WriteLine($"Failure: Expected 1 image file, but found {imageCount}.");
                foreach (string file in imageFiles)
                {
                    Console.WriteLine(" - " + Path.GetFileName(file));
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}
