// Title: Disable downlevel‑revealed comments in Aspose.Cells HTML export and verify standard <!-- --> tags (C#)
// Description: Creates a workbook, adds a comment to cell A1, saves it as HTML with HtmlSaveOptions.IsExportComments = true and HtmlSaveOptions.DisableDownlevelRevealedComments = true, then reads the file to confirm that only regular <!-- --> comments are present and no conditional "<![if" or "<!--[if" markup remains.
// Keywords: Aspose.Cells HTML export comments | DisableDownlevelRevealedComments C# | HtmlSaveOptions IsExportComments example | remove conditional comments Aspose.Cells | .NET workbook to HTML clean markup | Aspose.Cells .NET US | Aspose.Cells .NET Europe
// Common Searches: Aspose.Cells prevent conditional comments in HTML output | How to export cell comments to HTML without downlevel‑revealed syntax | Verify standard HTML comment tags after saving workbook with Aspose.Cells | DisableDownlevelRevealedComments property usage
// Developer Intent: Ensure that the HTML generated by Aspose.Cells contains only standard <!-- --> comments and excludes any downlevel‑revealed conditional comment syntax.
// Use Cases: Export worksheets with cell comments while guaranteeing clean comment markup for browsers. | Automate a post‑export check that scans the HTML for "<![if" or "<!--[if" patterns. | Integrate the verification step into CI/CD pipelines to fail builds if prohibited comment syntax is detected.
// AI Prompts: Generate C# code that saves an Aspose.Cells workbook to HTML with comments exported and downlevel‑revealed comments disabled, then validates the output for prohibited patterns. | Explain how HtmlSaveOptions.DisableDownlevelRevealedComments influences the HTML markup produced by Aspose.Cells. | Write an MSTest unit test that asserts the saved HTML file contains only standard <!-- --> comments when IsExportComments is true.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsHtmlCommentCheck
{
    // Creates a workbook, adds a comment to cell A1, saves it as HTML with HtmlSaveOptions.IsExportComments = true and HtmlSaveOptions.DisableDownlevelRevealedComments = true, then reads the file to confirm that only regular <!-- --> comments are present and no conditional "<![if" or "<!--[if" markup remains.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add a comment to cell A1
            int commentIndex = sheet.Comments.Add("A1");
            Comment comment = sheet.Comments[commentIndex];
            comment.Note = "Sample comment for HTML export";

            // Configure HTML save options:
            // - Export comments so they appear in the HTML.
            // - Disable downlevel-revealed conditional comments.
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                IsExportComments = true,
                DisableDownlevelRevealedComments = true
            };

            // Save the workbook as HTML
            string htmlPath = "output.html";
            workbook.Save(htmlPath, htmlOptions);

            // Read the generated HTML file
            string htmlContent = File.ReadAllText(htmlPath);

            // Verify that no downlevel-revealed comment syntax is present.
            // Downlevel-revealed comments typically contain the pattern "<![if" or "<!--[if".
            bool containsDownlevel = htmlContent.Contains("<![if") || htmlContent.Contains("<!--[if");

            Console.WriteLine("Downlevel-revealed comments present: " + containsDownlevel);
            Console.WriteLine("HTML contains only standard comment tags: " + !containsDownlevel);
        }
    }
}
