// Title: Exclude Unused Named Styles from HTML Export with Aspose.Cells for .NET
// Description: Demonstrates how to create a used and an unused named style in a workbook, enable HtmlSaveOptions.ExcludeUnusedStyles, save the workbook as HTML, and verify that the unused style is not emitted in the generated CSS.
// Keywords: Aspose.Cells | HtmlSaveOptions | ExcludeUnusedStyles | named style omission | C# HTML export | remove unused CSS | Aspose.Cells .NET example
// Common Searches: Aspose.Cells exclude unused styles HTML | remove unused named styles when saving to HTML | HtmlSaveOptions.ExcludeUnusedStyles C# example | verify style not in generated HTML Aspose.Cells | how to reduce HTML size with Aspose.Cells
// Developer Intent: Confirm that HTML generated by Aspose.Cells does not contain CSS definitions for named styles that were never applied.
// Use Cases: Export workbooks to clean HTML by automatically stripping unused style definitions, reducing file size. | Automated CI check that ensures no orphaned CSS appears after HTML conversion. | Create a reusable utility that saves a workbook as HTML with unused styles excluded and logs the result.
// AI Prompts: Write C# code that saves an Aspose.Cells workbook as HTML with ExcludeUnusedStyles enabled and asserts that a specific unused style name is absent. | Explain the algorithm Aspose.Cells uses to detect and omit unused named styles during HTML export. | Generate a unit test in C# that creates used and unused named styles, exports to HTML with exclusion, and fails if the unused style appears.

using System;
using System.IO;
using Aspose.Cells;
using System.Drawing;

namespace AsposeCellsHtmlUnusedStylesDemo
{
    // Demonstrates how to create a used and an unused named style in a workbook, enable HtmlSaveOptions.ExcludeUnusedStyles, save the workbook as HTML, and verify that the unused style is not emitted in the generated CSS.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // -------------------------------------------------
            // Create a named style that will be used in the sheet
            // -------------------------------------------------
            Style usedStyle = workbook.CreateStyle();
            usedStyle.Name = "UsedStyle";
            usedStyle.Font.Color = Color.Blue;
            usedStyle.Font.IsBold = true;
            // Apply the used style to cell A1
            sheet.Cells["A1"].PutValue("Cell with used style");
            sheet.Cells["A1"].SetStyle(usedStyle);

            // -------------------------------------------------
            // Create a named style that will NOT be applied
            // -------------------------------------------------
            Style unusedStyle = workbook.CreateStyle();
            unusedStyle.Name = "UnusedStyle";
            unusedStyle.Font.Color = Color.Red;
            unusedStyle.Font.IsItalic = true;
            // NOTE: Do NOT apply this style to any cell

            // -------------------------------------------------
            // Configure HTML save options to exclude unused styles
            // -------------------------------------------------
            HtmlSaveOptions saveOptions = new HtmlSaveOptions();
            saveOptions.ExcludeUnusedStyles = true; // Ensure unused styles are omitted

            // Define output HTML file path
            string htmlPath = "output.html";

            // Save the workbook as HTML using the configured options
            workbook.Save(htmlPath, saveOptions);

            // -------------------------------------------------
            // Verify that the unused style is not present in the HTML
            // -------------------------------------------------
            string htmlContent = File.ReadAllText(htmlPath);

            // Simple check: look for the name of the unused style in the generated CSS
            bool containsUnusedStyle = htmlContent.Contains("UnusedStyle");

            Console.WriteLine("HTML saved to: " + Path.GetFullPath(htmlPath));
            Console.WriteLine("Contains 'UnusedStyle' in HTML? " + (containsUnusedStyle ? "Yes" : "No"));
            Console.WriteLine("Verification complete.");
        }
    }
}
