// Title: Stream Aspose.Cells HTML export directly to an ASP.NET response for instant download (C#)
// AI Prompts: Generate C# code that saves an Aspose.Cells Workbook as HTML into a MemoryStream, sets the proper Content-Type and Content-Disposition headers, and streams the bytes to HttpResponse for immediate download. | Demonstrate how to asynchronously copy a MemoryStream containing HTML from Aspose.Cells to the ASP.NET Core HttpResponse.Body, flush the stream, and complete the response.
// Common Searches: how to download Aspose.Cells workbook as html in ASP.NET MVC | stream html generated by Aspose.Cells to browser without saving to disk | Aspose.Cells export to html and send as file download in ASP.NET Core | write memory stream to HttpResponse output stream c# asp.net | set content-disposition header for html file download asp.net response
// Tags: aspose.cells export workbook to html stream | c# asp.net response write memory stream | async copy memory stream to httpresponse body | set content-disposition header for html download | asp.net core file download from generated html

using System;
using System.IO;
using System.Threading.Tasks;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // The sample creates a Workbook, populates cells, saves it as HTML into a MemoryStream, resets the stream position, then asynchronously copies the HTML bytes to a provided output stream such as HttpResponse.Body, flushes the stream, and wraps any errors in an InvalidOperationException.
    public class HtmlExportHandler
    {
        /// <param name="outputStream">The stream to which the HTML content will be written.</param>
        /// <param name="fileName">Optional file name for the Content-Disposition header (unused in this implementation).</param>
        public async Task ExportWorkbookAsHtmlAsync(Stream outputStream, string fileName = "Workbook.html")
        {
            if (outputStream == null)
                throw new ArgumentNullException(nameof(outputStream));

            try
            {
                // Create a workbook and add sample data
                var workbook = new Workbook();
                var sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Hello");
                sheet.Cells["B1"].PutValue("World");

                // Save the workbook to a memory stream in HTML format
                using (var htmlStream = new MemoryStream())
                {
                    workbook.Save(htmlStream, SaveFormat.Html);
                    htmlStream.Position = 0;

                    // Copy HTML bytes to the provided output stream
                    await htmlStream.CopyToAsync(outputStream).ConfigureAwait(false);
                    await outputStream.FlushAsync().ConfigureAwait(false);
                }
            }
            catch (Exception ex)
            {
                // Wrap and rethrow for caller handling
                throw new InvalidOperationException("Failed to export workbook as HTML.", ex);
            }
        }
    }

    class Program
    {
        // Entry point for the console application
        static async Task Main(string[] args)
        {
            try
            {
                var handler = new HtmlExportHandler();
                string outputPath = "output.html";

                // Ensure the output directory exists
                string directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                // Write the HTML output to a file
                using (var fileStream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.None))
                {
                    await handler.ExportWorkbookAsHtmlAsync(fileStream);
                }

                Console.WriteLine($"HTML workbook exported successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
