// Title: C# – Apply a Custom Currency Number Format to Smart‑Marker Cells with Aspose.Cells
// Description: Creates a workbook template with smart markers for product names and prices, defines a Euro currency style (red for negatives), processes the markers, detects the last populated row, and applies the custom number format only to the price column using a StyleFlag before saving the file.
// Keywords: Aspose.Cells | C# | smart markers | custom number format | currency formatting | Euro style | StyleFlag | apply style to range | Excel export | dynamic last row
// Common Searches: Aspose.Cells custom currency format for smart markers | C# apply number format after smart marker processing | How to use StyleFlag to set only number format in Aspose.Cells | Set Euro currency style in Excel with Aspose.Cells | Determine last data row after processing smart markers
// Developer Intent: Format price values generated by smart markers with a custom currency number format while preserving other cell styles.
// Use Cases: Define a reusable Euro currency style and apply it exclusively to the number format of a column after smart‑marker processing. | Use StyleFlag to modify only the number format, leaving existing fonts, borders, and alignment untouched. | Automatically locate the last row of populated data and apply the style to the exact range of price cells.
// AI Prompts: Generate C# code that creates a custom Euro currency number format and applies it to the price column of cells populated by Aspose.Cells smart markers, using a StyleFlag to affect only the number format. | Explain how to retrieve the last data row after processing smart markers in Aspose.Cells and apply a style to a specific range without altering other cell attributes.

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;
using AsposeRange = Aspose.Cells.Range;

namespace AsposeCellsSmartMarkerNumberFormat
{
    // Creates a workbook template with smart markers for product names and prices, defines a Euro currency style (red for negatives), processes the markers, detects the last populated row, and applies the custom number format only to the price column using a StyleFlag before saving the file.
    public class Program
    {
        public static void Main()
        {
            try
            {
                // -------------------------------------------------
                // 1. Create a workbook that will act as a template
                // -------------------------------------------------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Insert smart markers into the template.
                // "&=Products.Name" and "&=Products.Price" will be replaced by data source values.
                cells["A1"].PutValue("Product");
                cells["B1"].PutValue("Price");
                cells["A2"].PutValue("&=Products.Name");
                cells["B2"].PutValue("&=Products.Price");

                // Name the range that contains the smart markers.
                // This is required when processing a specific range.
                AsposeRange smartRange = cells.CreateRange("A2:B2");
                smartRange.Name = "_CellsSmartMarkers";

                // -------------------------------------------------
                // 2. Prepare the data source
                // -------------------------------------------------
                var products = new List<Product>
                {
                    new Product { Name = "Apple",  Price = 1.23 },
                    new Product { Name = "Banana", Price = 0.99 },
                    new Product { Name = "Cherry", Price = 2.50 }
                };

                // -------------------------------------------------
                // 3. Define a custom currency number format
                // -------------------------------------------------
                // Create a style that contains only the custom number format.
                Style currencyStyle = workbook.CreateStyle();
                // Example: Euro currency, two decimal places, red for negative values.
                currencyStyle.Custom = "_-€ #,##0.00;[Red]_-€ -#,##0.00";

                // Use a StyleFlag to apply only the number format part of the style.
                StyleFlag flag = new StyleFlag { NumberFormat = true };

                // -------------------------------------------------
                // 4. Process smart markers
                // -------------------------------------------------
                WorkbookDesigner designer = new WorkbookDesigner { Workbook = workbook };
                designer.SetDataSource("Products", products);
                designer.Process(); // Populate the template with data

                // -------------------------------------------------
                // 5. Apply the custom number format to the populated cells
                // -------------------------------------------------
                // After processing, determine the last row that contains data.
                int lastDataRow = sheet.Cells.MaxDataRow; // zero‑based index
                // The price values are in column B (index 1), starting from row 2 (index 1).
                // Create a range that covers all populated price cells.
                AsposeRange priceRange = cells.CreateRange(1, 1, lastDataRow - 1, 1);
                priceRange.ApplyStyle(currencyStyle, flag);

                // -------------------------------------------------
                // 6. Save the resulting workbook
                // -------------------------------------------------
                string outputPath = "SmartMarkerCurrency.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"An error occurred: {ex.Message}");
            }
        }

        // Simple POCO class used as the data source for the smart markers.
        public class Product
        {
            public string Name { get; set; } = string.Empty;
            public double Price { get; set; }
        }
    }
}
