// Title: Use Aspose.Cells Smart Markers in C# to filter out rows with null values via AutoFilter before saving
// AI Prompts: Write C# code that creates a WorkbookDesigner, fills smart markers from a List<Product> with nullable fields, and then applies an AutoFilter to hide rows where the Name column is blank. | Show how to configure Aspose.Cells to call MatchNonBlanks on the first column after processing smart markers to exclude null or empty entries. | Provide a complete example that defines a smart‑marker range, populates it with products that have null Name or Price, and removes those rows using the worksheet AutoFilter before exporting to Excel.
// Common Searches: asp.net aspocells apply autofilter to remove blank rows after smart marker processing | c# filter null values in Excel generated by smart markers using WorkbookDesigner | how to hide rows with empty product names when using Aspose.Cells smart markers | exclude rows with null price column after populating smart markers in Aspose.Cells
// Tags: smart markers autofilter null rows | Aspose.Cells matchnonblanks column filter | C# workbookdesigner nullable data source | Excel output exclude blank cells Aspose | auto filter after smart marker processing

using System;
using System.Collections.Generic;
using Aspose.Cells;
using AsposeRange = Aspose.Cells.Range;

namespace SmartMarkerFilterExample
{
    // Sample data class with possible null values
    // Demonstrates creating a workbook with smart markers, populating it from a List<Product> that may contain null Name or Price values, and then using the worksheet AutoFilter (MatchNonBlanks) to hide rows with blank Name cells before saving the file.
    public class Product
    {
        public string? Name { get; set; }          // May be null
        public double? Price { get; set; }        // Nullable double
    }

    class Program
    {
        static void Main()
        {
            try
            {
                // 1. Create a new workbook (template) and add smart markers
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Header row
                cells["A1"].PutValue("Product Name");
                cells["B1"].PutValue("Price");

                // Smart marker range (starting at row 2)
                // &=$Products.Name and &=$Products.Price will be replaced by data source values
                cells["A2"].PutValue("&=$Products.Name");
                cells["B2"].PutValue("&=$Products.Price");

                // Define the range that contains smart markers and give it the special name
                AsposeRange smRange = cells.CreateRange("A2:B2");
                smRange.Name = "_CellsSmartMarkers";

                // 2. Prepare data source with some null entries
                List<Product> products = new List<Product>
                {
                    new Product { Name = "Apple", Price = 1.20 },
                    new Product { Name = null,   Price = 0.80 },   // Null name
                    new Product { Name = "Banana", Price = null }, // Null price
                    new Product { Name = "Orange", Price = 1.00 }
                };

                // 3. Set up WorkbookDesigner, assign data source and process smart markers
                WorkbookDesigner designer = new WorkbookDesigner
                {
                    Workbook = workbook,
                    // Convert empty strings to null (optional, not needed for this example)
                    UpdateEmptyStringAsNull = true
                };
                designer.SetDataSource("Products", products);
                designer.Process(); // Populate the smart markers

                // 4. After processing, apply an AutoFilter to exclude rows where the Name column is blank/null
                // Determine the data range (including header)
                int startRow = 0;               // Header row index (0‑based)
                int startColumn = 0;            // Column A (0‑based)
                int totalRows = sheet.Cells.MaxDataRow + 1; // Total rows after processing
                int totalColumns = sheet.Cells.MaxDataColumn + 1;

                // Build the address string for the AutoFilter range, e.g., "A1:B5"
                string endCellAddress = CellsHelper.CellIndexToName(totalRows - 1, totalColumns - 1);
                sheet.AutoFilter.Range = $"A1:{endCellAddress}";

                // Apply filter to show only non‑blank cells in the Name column (field index 0)
                sheet.AutoFilter.MatchNonBlanks(0);
                sheet.AutoFilter.Refresh(); // Hide rows with null/blank names

                // 5. Save the resulting workbook
                workbook.Save("SmartMarkerFilteredOutput.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
