// Title: Format smart‑marker generated dates with the "MMMM dd, yyyy" pattern in an Aspose.Cells C# workbook
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, inserts smart markers for a name and a DateTime column, binds a DataTable as the data source, processes the markers, and then applies a custom number format "MMMM dd, yyyy" to every cell containing a date. | Show how to iterate through the used range of an Aspose.Cells worksheet after processing smart markers and set a style with Custom = "MMMM dd, yyyy" on cells whose current style is a DateTime. | Demonstrate using WorkbookDesigner to populate a template with smart markers and then programmatically apply a month‑day‑year date format to all populated date cells before saving the file.
// Common Searches: aspnet c# apply custom date format to smart marker dates in Aspose.Cells workbook | how to change date style to 'MMMM dd, yyyy' after processing smart markers in Aspose.Cells | iterate over used cells in Aspose.Cells and set custom date format in C# | Aspose.Cells smart marker example with DateTime formatting | C# code to format dates generated by smart markers in Excel file
// Tags: smart markers date styling Aspose.Cells | date style MMMM dd yyyy C# | set data source for smart markers | traverse worksheet used cells Aspose.Cells | apply style to DateTime cells

using System;
using System.Data;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsSmartMarkerDateFormat
{
    // The example creates a workbook, adds smart markers for Name and Date, binds a DataTable as the data source, processes the markers, then defines a style with the custom format "MMMM dd, yyyy" and applies it to every cell whose existing style is a DateTime, finally saving the result as SmartMarkerDateFormattedReport.xlsx.
    class Program
    {
        static void Main()
        {
            // -------------------------------------------------
            // 1. Create a new workbook and get the first sheet
            // -------------------------------------------------
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // -------------------------------------------------
            // 2. Insert smart markers into the template.
            //    &=[Date] will be replaced by the date values from the data source.
            // -------------------------------------------------
            cells["A1"].PutValue("Name");
            cells["B1"].PutValue("Date");
            cells["A2"].PutValue("&=$Name");
            cells["B2"].PutValue("&=$Date");   // smart marker for date column

            // -------------------------------------------------
            // 3. Prepare a data source (DataTable) containing dates.
            // -------------------------------------------------
            DataTable dt = new DataTable("Employees");
            dt.Columns.Add("Name", typeof(string));
            dt.Columns.Add("Date", typeof(DateTime));
            dt.Rows.Add("Alice", new DateTime(2023, 5, 12));
            dt.Rows.Add("Bob",   new DateTime(2023, 6, 23));
            dt.Rows.Add("Carol", new DateTime(2023, 7, 4));

            // -------------------------------------------------
            // 4. Set the data source for the designer and process the smart markers.
            // -------------------------------------------------
            WorkbookDesigner designer = new WorkbookDesigner(workbook);
            designer.SetDataSource(dt);
            designer.Process();   // populates the cells with data

            // -------------------------------------------------
            // 5. Apply the desired date format ("MMMM dd, yyyy") to all cells that contain dates.
            //    We iterate over the used range, check if the cell's style is a date,
            //    and then set a custom number format.
            // -------------------------------------------------
            Style dateStyle = workbook.CreateStyle();
            dateStyle.Custom = "MMMM dd, yyyy";

            int maxRow = cells.MaxDataRow;
            int maxCol = cells.MaxDataColumn;

            for (int row = 0; row <= maxRow; row++)
            {
                for (int col = 0; col <= maxCol; col++)
                {
                    Cell cell = cells[row, col];
                    // Skip empty cells
                    if (cell.Type == CellValueType.IsNull) continue;

                    // Determine if the cell already has a date style
                    Style curStyle = cell.GetStyle();
                    if (curStyle.IsDateTime)
                    {
                        // Apply the custom date format
                        cell.SetStyle(dateStyle);
                    }
                }
            }

            // -------------------------------------------------
            // 6. Save the resulting workbook.
            // -------------------------------------------------
            workbook.Save("SmartMarkerDateFormattedReport.xlsx");
        }
    }
}
