// Title: Create a drop‑down list data validation for the Department column after filling an Excel sheet with Aspose.Cells smart markers in C#
// AI Prompts: Write C# code that loads an Excel template containing smart markers, uses WorkbookDesigner to populate employee data, then adds a list‑type Validation to the Department column (B) for the generated rows, using a predefined department array and custom error messages. | Show how to compute the dynamic cell range for the populated rows, create a CellArea, add a Validation of type List, set Formula1 to a comma‑separated list, enable InCellDropDown, and configure an error title and message with Aspose.Cells.
// Common Searches: asp.net core add dropdown validation to Excel column generated by Aspose.Cells smart markers | c# Aspose.Cells configure dropdown for column after WorkbookDesigner.Process | how to restrict department input in smart marker generated worksheet using Aspose.Cells | dynamic data validation range for Excel table created with Aspose.Cells smart markers | Aspose.Cells custom error message for smart marker populated cells
// Tags: Aspose.Cells WorkbookDesigner dropdown validation | C# Excel drop-down validation after smart markers | dynamic cell area validation Aspose.Cells | department column data validation Aspose.Cells | smart markers generated worksheet validation

using Aspose.Cells;
using Aspose.Cells.Tables;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;

// The program loads a SmartMarkerTemplate.xlsx, fills it with employee data via WorkbookDesigner, then creates a list‑type data validation on the Department column (B2:B{lastRow}) using a predefined department list, enables an in‑cell dropdown, sets a custom error title and message, and saves the result as SmartMarkerResult.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            const string templatePath = "SmartMarkerTemplate.xlsx";
            const string resultPath = "SmartMarkerResult.xlsx";

            // Ensure the template file exists
            if (!File.Exists(templatePath))
                throw new FileNotFoundException($"Template file not found: {templatePath}");

            // Load the template workbook that contains smart markers
            Workbook workbook = new Workbook(templatePath);

            // Prepare the data source for the smart markers
            var employees = new List<Employee>
            {
                new Employee { Name = "John", Department = "HR", Age = 30 },
                new Employee { Name = "Jane", Department = "IT", Age = 28 },
                new Employee { Name = "Bob", Department = "Finance", Age = 35 }
            };

            var departments = new List<string> { "HR", "IT", "Finance", "Marketing" };

            // Convert the data to a DataSet (required by older WorkbookDesigner API)
            DataSet dataSet = new DataSet();

            // Employees table
            DataTable empTable = new DataTable("Employees");
            empTable.Columns.Add("Name", typeof(string));
            empTable.Columns.Add("Department", typeof(string));
            empTable.Columns.Add("Age", typeof(int));
            foreach (var e in employees)
                empTable.Rows.Add(e.Name, e.Department, e.Age);
            dataSet.Tables.Add(empTable);

            // Departments table (single column)
            DataTable deptTable = new DataTable("Departments");
            deptTable.Columns.Add("Department", typeof(string));
            foreach (var d in departments)
                deptTable.Rows.Add(d);
            dataSet.Tables.Add(deptTable);

            // Apply the smart markers to fill the workbook
            WorkbookDesigner designer = new WorkbookDesigner(workbook);
            designer.SetDataSource(dataSet);
            designer.Process(); // Smart markers are replaced with data

            // After processing, apply data validation to the Department column (column B)
            Worksheet sheet = workbook.Worksheets[0];

            // Determine the range that contains the department values (assumes header in row 1)
            int startRow = 2; // first data row (1‑based)
            int endRow = startRow + employees.Count - 1;

            // Create validation for the range B2:B{endRow}
            ValidationCollection validations = sheet.Validations;
            CellArea area = new CellArea
            {
                StartRow = startRow - 1,
                StartColumn = 1, // column B index = 1
                EndRow = endRow - 1,
                EndColumn = 1
            };
            int validationIndex = validations.Add(area);
            Validation validation = validations[validationIndex];
            validation.Type = ValidationType.List;
            // List items as a comma‑separated string
            validation.Formula1 = string.Join(",", departments);
            validation.InCellDropDown = true;
            validation.ShowError = true;
            validation.ErrorTitle = "Invalid Department";
            validation.ErrorMessage = "Please select a department from the predefined list.";

            // Ensure the output directory exists
            string resultDir = Path.GetDirectoryName(resultPath);
            if (!string.IsNullOrEmpty(resultDir) && !Directory.Exists(resultDir))
                Directory.CreateDirectory(resultDir);

            // Save the generated workbook with validation applied
            workbook.Save(resultPath);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }

    // Simple POCO class used by the smart markers
    public class Employee
    {
        public string Name { get; set; } = string.Empty;
        public string Department { get; set; } = string.Empty;
        public int Age { get; set; }
    }
}
