// Title: Repeat Smart‑Marker Formulas per Row with WorkbookDesigner in Aspose.Cells for .NET
// Description: Demonstrates how to set WorkbookDesigner.RepeatFormulasWithSubtotal to true so a formula placed in a smart‑marker template (e.g., "=C2*D2") automatically updates for every inserted data row. The example creates a workbook, defines smart markers for ID, Name, Qty and Price, binds a DataTable, processes the markers, and saves the result with correctly adjusted formulas in column E.
// Keywords: Aspose.Cells | .NET | C# | smart markers | repeat formulas | RepeatFormulasWithSubtotal | Excel formula per row | dynamic rows | template processing | WorkbookDesigner
// Common Searches: Aspose.Cells repeat smart marker formulas | WorkbookDesigner RepeatFormulasWithSubtotal example | C# smart marker formula adjusts per row | How to copy formulas with smart markers in Aspose.Cells | Dynamic Excel rows with formulas using Aspose
// Developer Intent: Use Aspose.Cells to automatically copy and adjust an Excel formula for each row generated by smart markers.
// Use Cases: Generate a product catalog where each row calculates total price (Qty × Price) without manual formula copying. | Create an invoice template that repeats line‑item totals for any number of items. | Build a financial report with subtotal rows while ensuring all formulas stay correctly referenced.
// AI Prompts: Write C# code that uses Aspose.Cells to repeat a formula column for each smart‑marker row, including subtotal rows. | Show how to enable WorkbookDesigner.RepeatFormulasWithSubtotal and verify the resulting formulas in the worksheet. | Explain step‑by‑step how to design a smart‑marker template with a calculated column that updates automatically for every data row.

using System;
using System.Data;
using Aspose.Cells;

namespace SmartMarkerFormulaDemo
{
    // Demonstrates how to set WorkbookDesigner.RepeatFormulasWithSubtotal to true so a formula placed in a smart‑marker template (e.g., "=C2*D2") automatically updates for every inserted data row. The example creates a workbook, defines smart markers for ID, Name, Qty and Price, binds a DataTable, processes the markers, and saves the result with correctly adjusted formulas in column E.
    class Program
    {
        static void Main()
        {
            // 1. Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();                     // create
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // 2. Define the template with smart markers.
            //    Columns A‑D will be filled with data from the data source.
            //    Column E contains a formula that multiplies Qty (C) by Price (D).
            //    The formula is written for the first data row (row 2) and will be
            //    automatically adjusted for each inserted row when the designer processes.
            cells["A1"].PutValue("&=$ID");        // smart marker for column ID
            cells["B1"].PutValue("&=$Name");      // smart marker for column Name
            cells["C1"].PutValue("&=$Qty");       // smart marker for column Qty
            cells["D1"].PutValue("&=$Price");     // smart marker for column Price
            cells["E1"].PutValue("=C2*D2");        // formula to be repeated per row

            // 3. Prepare a data source (DataTable) that matches the smart markers.
            DataTable dt = new DataTable("Products");
            dt.Columns.Add("ID", typeof(int));
            dt.Columns.Add("Name", typeof(string));
            dt.Columns.Add("Qty", typeof(double));
            dt.Columns.Add("Price", typeof(double));

            dt.Rows.Add(1, "Apple", 10, 0.5);
            dt.Rows.Add(2, "Banana", 20, 0.3);
            dt.Rows.Add(3, "Cherry", 15, 0.8);

            // 4. Create a WorkbookDesigner, assign the workbook and the data source.
            WorkbookDesigner designer = new WorkbookDesigner(workbook);
            // Enable repeating of formulas for each inserted row (including subtotal rows if any)
            designer.RepeatFormulasWithSubtotal = true;               // important for formula adjustment
            designer.SetDataSource(dt);

            // 5. Process the smart markers – this inserts rows and copies the formula.
            designer.Process();                                       // process

            // 6. Verify that the formula has been adjusted for each data row.
            //    After processing, rows 2‑4 contain the data; column E should have
            //    formulas "=C2*D2", "=C3*D3", "=C4*D4" respectively.
            for (int row = 1; row <= 3; row++) // rows are zero‑based; data starts at row index 1
            {
                Console.WriteLine($"Row {row + 1} – Qty: {cells[row, 2].Value}, Price: {cells[row, 3].Value}");
                Console.WriteLine($"          Formula in E{row + 1}: {cells[row, 4].Formula}");
                Console.WriteLine($"          Calculated Value: {cells[row, 4].Value}");
            }

            // 7. Save the resulting workbook.
            workbook.Save("SmartMarkerFormulaResult.xlsx");           // save
        }
    }
}
