// Title: Aspose.Cells C# – Skip Empty Rows in Smart Marker Detail Lists with UpdateEmptyStringAsNull & DeleteBlankRows
// Description: Learn how to configure Aspose.Cells Smart Markers to ignore blank data entries. The example sets WorkbookDesigner.UpdateEmptyStringAsNull, processes the markers, then removes fully empty rows using DeleteBlankRows with DeleteBlankOptions, preserving formula references and saving the workbook.
// Keywords: Aspose.Cells | Smart Markers | C# | ignore empty rows | skip blank records | UpdateEmptyStringAsNull | DeleteBlankRows | DeleteBlankOptions | Excel report generation | blank row removal
// Common Searches: Aspose.Cells ignore empty rows smart markers | DeleteBlankRows after smart marker processing C# | UpdateEmptyStringAsNull example Aspose.Cells | C# smart markers skip blank records | remove blank rows generated by smart markers
// Developer Intent: Eliminate rows created from empty or null items when processing smart markers, while keeping formulas and references intact.
// Use Cases: Generate an employee roster that automatically omits records with missing names or ages. | Create an invoice where line items with zero quantity or empty description are not displayed, ensuring totals remain correct. | Produce a sales summary that discards placeholder rows in the source list, preserving chart data ranges after deletion.
// AI Prompts: Show me a C# Aspose.Cells example that skips empty rows in a smart‑marker detail list using UpdateEmptyStringAsNull and DeleteBlankRows. | How can I remove completely blank rows after processing smart markers while keeping formula references updated? | Provide code to configure DeleteBlankOptions so that empty strings are treated as blank and references are refreshed.

using System;
using System.Collections.Generic;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // Learn how to configure Aspose.Cells Smart Markers to ignore blank data entries. The example sets WorkbookDesigner.UpdateEmptyStringAsNull, processes the markers, then removes fully empty rows using DeleteBlankRows with DeleteBlankOptions, preserving formula references and saving the workbook.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook (template) and set up smart markers for a detail list
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Header row
                cells["A1"].PutValue("Name");
                cells["B1"].PutValue("Age");

                // Detail row with smart markers (line‑by‑line processing is default)
                cells["A2"].PutValue("&=Employees.Name");
                cells["B2"].PutValue("&=Employees.Age");

                // Initialize the WorkbookDesigner and assign the workbook
                WorkbookDesigner designer = new WorkbookDesigner
                {
                    Workbook = workbook,
                    // Treat empty strings as null to help identify blank rows
                    UpdateEmptyStringAsNull = true
                };

                // Sample data list containing gaps (empty strings or nulls)
                List<Employee> employees = new List<Employee>
                {
                    new Employee { Name = "John", Age = 30 },
                    new Employee { Name = "", Age = 0 },          // Treated as empty
                    new Employee { Name = "Alice", Age = 25 },
                    new Employee { Name = null, Age = 0 }        // Treated as empty
                };

                // Set the data source for the smart markers
                designer.SetDataSource("Employees", employees);

                // Process the smart markers – this will expand the detail rows
                designer.Process();

                // Delete rows that are completely blank.
                DeleteBlankOptions deleteOptions = new DeleteBlankOptions
                {
                    EmptyStringAsBlank = true,
                    UpdateReference = true   // Keep formulas consistent after deletion
                };
                sheet.Cells.DeleteBlankRows(deleteOptions);

                // Save the resulting workbook
                string outputPath = "Result.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }

    // Simple data class used for the example
    public class Employee
    {
        public string? Name { get; set; }
        public int Age { get; set; }
    }
}
