// Title: Aspose.Cells for .NET – Map Pivot Table Detail Rows to a Pre‑Created ListObject (DetailTable) in C#
// Description: Demonstrates how to create a workbook, add a pivot table, and use the ShowDetail method to write the pivot's drill‑through rows directly into an existing ListObject named DetailTable on another worksheet, preserving table headers and style.
// Keywords: Aspose.Cells ShowDetail | pivot detail to ListObject | DetailTable parameter | C# map pivot rows to table | Excel table drill‑through | Aspose.Cells pivot drill‑through | populate existing Excel table | Aspose.Cells .NET example
// Common Searches: Aspose.Cells map pivot detail rows to existing table | ShowDetail destination ListObject C# | How to fill a predefined Excel table with pivot drill‑through data | DetailTable parameter Aspose.Cells example | Write pivot drill‑through rows into a named ListObject
// Developer Intent: Transfer the detail rows generated by a pivot table into a pre‑created ListObject named DetailTable on a target worksheet using Aspose.Cells for .NET.
// Use Cases: Export a pivot's drill‑through data into a styled Excel table for detailed reporting. | Combine a summary pivot with a transaction‑level table without losing formatting or column headers. | Reuse an existing ListObject as the destination for ShowDetail to maintain consistent table styles across multiple reports.
// AI Prompts: Generate C# code with Aspose.Cells that maps ShowDetail rows into an existing ListObject called DetailTable at a specific start cell. | Explain the ShowDetail parameters (rowOffset, columnOffset, newSheet, destRow, destColumn) needed to write detail data into a predefined table instead of a new sheet. | Show how to verify that DetailTable is populated after calling ShowDetail and how to handle potential exceptions.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;
using Aspose.Cells.Tables;

namespace AsposeCellsExamples
{
    // Demonstrates how to create a workbook, add a pivot table, and use the ShowDetail method to write the pivot's drill‑through rows directly into an existing ListObject named DetailTable on another worksheet, preserving table headers and style.
    public class DetailTableMappingDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet (source data)
                Workbook workbook = new Workbook();
                Worksheet dataSheet = workbook.Worksheets[0];

                // Populate sample data for the pivot table
                dataSheet.Cells["A1"].PutValue("Category");
                dataSheet.Cells["B1"].PutValue("SubCategory");
                dataSheet.Cells["C1"].PutValue("Amount");

                dataSheet.Cells["A2"].PutValue("Food");
                dataSheet.Cells["B2"].PutValue("Fruit");
                dataSheet.Cells["C2"].PutValue(120);

                dataSheet.Cells["A3"].PutValue("Food");
                dataSheet.Cells["B3"].PutValue("Vegetable");
                dataSheet.Cells["C3"].PutValue(80);

                dataSheet.Cells["A4"].PutValue("Beverage");
                dataSheet.Cells["B4"].PutValue("Tea");
                dataSheet.Cells["C4"].PutValue(50);

                dataSheet.Cells["A5"].PutValue("Beverage");
                dataSheet.Cells["B5"].PutValue("Coffee");
                dataSheet.Cells["C5"].PutValue(70);

                // Add a pivot table based on the data range A1:C5, placed at E3
                int pivotIndex = dataSheet.PivotTables.Add("A1:C5", "E3", "SalesPivot");
                PivotTable pivotTable = dataSheet.PivotTables[pivotIndex];

                // Configure pivot fields: Category as row, SubCategory as column, Amount as data
                pivotTable.AddFieldToArea(PivotFieldType.Row, "Category");
                pivotTable.AddFieldToArea(PivotFieldType.Column, "SubCategory");
                pivotTable.AddFieldToArea(PivotFieldType.Data, "Amount");

                // Refresh the pivot table to populate data
                pivotTable.RefreshData();

                // Create a target worksheet for the detail table
                Worksheet detailSheet = workbook.Worksheets.Add("DetailData");

                // Add a placeholder ListObject (Excel table) at A1 with headers
                int placeholderTableIndex = detailSheet.ListObjects.Add(0, 0, 1, 3, true);
                ListObject detailTable = detailSheet.ListObjects[placeholderTableIndex];
                detailTable.DisplayName = "DetailTable";

                // Map detail rows from the pivot to the placeholder table
                pivotTable.ShowDetail(rowOffset: 1, columnOffset: 0, newSheet: false, destRow: 0, destColumn: 0);

                // Save the workbook
                workbook.Save("DetailTableMappingDemo.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        // Entry point
        public static void Main()
        {
            Run();
        }
    }
}
