using System;
using System.Collections.Generic;
using Aspose.Cells;

class Program
{
    static void Main()
    {
        // Load the template workbook that contains smart markers
        Workbook workbook = new Workbook("Template.xlsx");

        // Prepare a detail list with gaps (null entries represent empty rows)
        List<Person> persons = new List<Person>
        {
            new Person { Name = "John Doe", Age = 30 },
            null, // intentional gap – should be ignored
            new Person { Name = "Jane Smith", Age = 28 }
        };

        // Initialize the WorkbookDesigner with the loaded workbook
        WorkbookDesigner designer = new WorkbookDesigner(workbook);

        // Bind the data source to the smart marker name used in the template
        designer.SetDataSource("Persons", persons);

        // Process the smart markers – this will expand the list and create rows for each item
        designer.Process();

        // After processing, delete rows that are completely blank (generated by the gaps)
        DeleteBlankOptions deleteOptions = new DeleteBlankOptions
        {
            // Treat cells with empty strings as blank so they are removed
            EmptyStringAsBlank = true,
            // Update any formulas/references that may be affected by the deletion
            UpdateReference = true
        };

        // Apply the deletion to the first worksheet (adjust index if needed)
        workbook.Worksheets[0].Cells.DeleteBlankRows(deleteOptions);

        // Save the final workbook
        workbook.Save("Result.xlsx");
    }

    // Simple data class used for the detail list
    public class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}