// Title: Aspose.Cells Smart Markers: Skip Blank Rows When Data Contains Gaps (C#)
// Description: Demonstrates how to use WorkbookDesigner with a named smart‑marker range, supply a list that includes null or default values, process the markers, and then call DeleteBlankRows to remove any completely empty rows before saving the workbook.
// Keywords: Aspose.Cells | Smart Markers | C# | .NET | WorkbookDesigner | DeleteBlankRows | ignore empty rows | skip null values | gap handling in smart markers | named range smart markers | employee report Excel
// Common Searches: Aspose.Cells ignore empty rows smart marker | DeleteBlankRows after WorkbookDesigner.Process | C# smart marker skip null entries | remove blank rows generated by smart markers | process smart marker range with gaps
// Developer Intent: Prevent the creation of blank rows when a smart‑marker detail list contains null or default values, and clean up any resulting empty rows automatically.
// Use Cases: Generate an employee roster where records with missing names are omitted. | Create financial statements that exclude rows for empty transaction entries. | Automate Excel reports from collections that may contain gaps without leaving blank rows in the final file.
// AI Prompts: Provide C# code that processes a smart‑marker range with Aspose.Cells and removes rows that are completely blank. | Explain how DeleteBlankRows works after WorkbookDesigner.Process to clean up empty rows caused by null data. | Show an example of configuring a named smart‑marker range and handling gaps in the source list without leaving empty rows in the output workbook.

using System;
using System.Collections.Generic;
using Aspose.Cells;

// Demonstrates how to use WorkbookDesigner with a named smart‑marker range, supply a list that includes null or default values, process the markers, and then call DeleteBlankRows to remove any completely empty rows before saving the workbook.
class SmartMarkerIgnoreEmptyRows
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook wb = new Workbook();
        Worksheet ws = wb.Worksheets[0];

        // Set up header cells
        ws.Cells["A1"].PutValue("Name");
        ws.Cells["B1"].PutValue("Age");

        // Insert smart markers for the detail list
        ws.Cells["A2"].PutValue("&=Employees.Name");
        ws.Cells["B2"].PutValue("&=Employees.Age");

        // Define the range that contains the smart markers
        ws.Cells.CreateRange("A2:B2").Name = "_CellsSmartMarkers";

        // Prepare data source with gaps (null/empty values)
        List<Employee> employees = new List<Employee>
        {
            new Employee { Name = "John", Age = 30 },
            new Employee { Name = null, Age = 0 },   // This will generate an empty row
            new Employee { Name = "Alice", Age = 25 }
        };

        // Configure the WorkbookDesigner
        WorkbookDesigner designer = new WorkbookDesigner
        {
            Workbook = wb
        };
        designer.SetDataSource("Employees", employees);

        // Process only the smart marker range
        designer.Process(true);

        // Remove any blank rows that were created due to gaps
        ws.Cells.DeleteBlankRows();

        // Save the resulting workbook
        wb.Save("SmartMarkerIgnoreEmptyRows.xlsx");
    }

    // Simple data class used as the data source
    public class Employee
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
}
