// Title: C# – Aspose.Cells Master Smart Marker with Nested Employee Detail Markers (Department‑Employee Example)
// Description: Demonstrates how to create a master smart marker that repeats for each department and nests employee detail markers inside. The sample builds a template workbook, adds the master marker "&=\"Departments\"" and child markers "&=$Employees.Name" / "&=$Employees.Age", constructs a DataSet with related Departments and Employees tables, sets the DataSet as the data source for WorkbookDesigner, processes the markers, and saves the populated Excel file.
// Keywords: Aspose.Cells | C# smart markers | master smart marker | nested smart markers | department employee report | DataSet relation | WorkbookDesigner | .NET Excel automation | hierarchical Excel output
// Common Searches: Aspose.Cells master smart marker example C# | nested smart markers department employee Aspose.Cells | repeat rows for each master record Aspose.Cells | how to use DataSet relations with smart markers | generate hierarchical Excel report using Aspose.Cells
// Developer Intent: Create an Excel worksheet where each department row is generated by a master smart marker and the related employee rows are filled by nested child markers, using a DataSet with a master‑detail relationship.
// Use Cases: Generate department‑wise employee rosters in a single sheet. | Build dynamic, hierarchical Excel reports from relational data sources. | Automate production of master‑detail spreadsheets for HR, sales, or inventory dashboards.
// AI Prompts: Write C# code with Aspose.Cells that defines a master smart marker for a Departments table and nested employee markers for the related Employees table, using a DataSet with a defined relation. | Explain the role of the "&=\"Departments\"" syntax for repeating master rows and how "&=$Employees.Name" accesses child table fields in Aspose.Cells smart markers.

using System;
using System.Data;
using Aspose.Cells;

namespace AsposeCellsSmartMarkerDemo
{
    // Demonstrates how to create a master smart marker that repeats for each department and nests employee detail markers inside. The sample builds a template workbook, adds the master marker "&=\"Departments\"" and child markers "&=$Employees.Name" / "&=$Employees.Age", constructs a DataSet with related Departments and Employees tables, sets the DataSet as the data source for WorkbookDesigner, processes the markers, and saves the populated Excel file.
    class Program
    {
        static void Main()
        {
            // 1. Create a new workbook that will serve as the template
            Workbook template = new Workbook();
            Worksheet sheet = template.Worksheets[0];
            Cells cells = sheet.Cells;

            // 2. Insert smart markers:
            //    - Master smart marker that repeats for each department
            //    - Nested smart markers for employee details inside the master block
            //    The master marker uses the syntax &="Departments"
            //    Nested markers reference the child table "Employees" (related to Departments)
            cells["A1"].PutValue("Department");
            cells["B1"].PutValue("Employee Name");
            cells["C1"].PutValue("Employee Age");

            // Master block starts at row 2
            cells["A2"].PutValue("&=\"Departments\"");               // Master repeat marker
            cells["B2"].PutValue("&=$Employees.Name");               // Child marker
            cells["C2"].PutValue("&=$Employees.Age");                // Child marker

            // 3. Build the data source (DataSet with two related tables)
            DataSet ds = new DataSet();

            // Departments table (master)
            DataTable dtDept = new DataTable("Departments");
            dtDept.Columns.Add("DeptID", typeof(int));
            dtDept.Columns.Add("DeptName", typeof(string));
            dtDept.Rows.Add(1, "Sales");
            dtDept.Rows.Add(2, "HR");
            ds.Tables.Add(dtDept);

            // Employees table (detail)
            DataTable dtEmp = new DataTable("Employees");
            dtEmp.Columns.Add("EmpID", typeof(int));
            dtEmp.Columns.Add("DeptID", typeof(int));
            dtEmp.Columns.Add("Name", typeof(string));
            dtEmp.Columns.Add("Age", typeof(int));
            dtEmp.Rows.Add(1, 1, "John", 30);
            dtEmp.Rows.Add(2, 1, "Alice", 28);
            dtEmp.Rows.Add(3, 2, "Bob", 35);
            ds.Tables.Add(dtEmp);

            // Define relation between Departments and Employees
            ds.Relations.Add("Dept_Employees",
                dtDept.Columns["DeptID"],
                dtEmp.Columns["DeptID"]);

            // 4. Initialize WorkbookDesigner with the template
            WorkbookDesigner designer = new WorkbookDesigner();
            designer.Workbook = template;

            // 5. Set the DataSet as the data source
            designer.SetDataSource(ds);

            // 6. Process the smart markers
            designer.Process();

            // 7. Save the result
            designer.Workbook.Save("MasterSmartMarkerOutput.xlsx");
        }
    }
}
