// Title: Add a summary worksheet with SUM formulas that total data from multiple smart‑marker worksheets using Aspose.Cells for .NET (C#)
// AI Prompts: Create a new worksheet named "Summary", write header cells, and insert Excel SUM formulas that reference the populated SalesData and ExpensesData sheets. | After WorkbookDesigner processes all smart markers, force formula calculation and save the workbook as AggregatedSummary.xlsx. | Build a DataSet containing SalesData and ExpensesData tables, bind it to WorkbookDesigner, and generate a consolidated totals sheet automatically.
// Common Searches: Aspose.Cells C# how to add a summary sheet that sums values from smart marker worksheets | C# aggregate totals from multiple smart marker sheets into one worksheet using WorkbookDesigner | calculate cross‑sheet SUM after processing smart markers with Aspose.Cells .NET | add a totals worksheet to an Excel file generated by Aspose.Cells smart markers
// Tags: Aspose.Cells WorkbookDesigner add summary worksheet | smart markers cross‑sheet SUM formulas | C# aggregate totals from multiple worksheets | Excel SUM formula generation with Aspose.Cells | populate summary sheet after smart marker processing

using System;
using System.Data;
using Aspose.Cells;

// The example loads a template workbook that contains smart markers on several sheets, creates a DataSet with SalesData and ExpensesData tables, binds the DataSet to a WorkbookDesigner, and processes all smart markers. It then adds a new "Summary" worksheet, writes header labels, inserts SUM formulas that reference the populated data ranges on the SalesData and ExpensesData sheets, forces formula calculation, and saves the final workbook as AggregatedSummary.xlsx.
class SummaryFromSmartMarkers
{
    static void Main()
    {
        // Load the template workbook that contains smart markers in multiple worksheets
        Workbook template = new Workbook("TemplateWithSmartMarkers.xlsx");

        // Prepare data sources for the smart markers
        DataSet dataSet = new DataSet();

        // First data source – will be used by smart markers in the first worksheet
        DataTable salesTable = new DataTable("SalesData");
        salesTable.Columns.Add("Region", typeof(string));
        salesTable.Columns.Add("Sales", typeof(double));
        salesTable.Rows.Add("North", 1200);
        salesTable.Rows.Add("South", 1500);
        salesTable.Rows.Add("East",  900);
        salesTable.Rows.Add("West", 1100);
        dataSet.Tables.Add(salesTable);

        // Second data source – will be used by smart markers in the second worksheet
        DataTable expensesTable = new DataTable("ExpensesData");
        expensesTable.Columns.Add("Category", typeof(string));
        expensesTable.Columns.Add("Amount", typeof(double));
        expensesTable.Rows.Add("Travel",   300);
        expensesTable.Rows.Add("Supplies", 450);
        expensesTable.Rows.Add("Rent",     800);
        dataSet.Tables.Add(expensesTable);

        // Initialize WorkbookDesigner with the loaded template
        WorkbookDesigner designer = new WorkbookDesigner();
        designer.Workbook = template;

        // Bind the DataSet (containing both tables) to the designer
        designer.SetDataSource(dataSet);

        // Process all smart markers in the workbook
        designer.Process();

        // After processing, add a new worksheet that will hold the aggregated summary
        Worksheet summarySheet = designer.Workbook.Worksheets.Add("Summary");

        // Write header labels
        summarySheet.Cells["A1"].PutValue("Sheet");
        summarySheet.Cells["B1"].PutValue("Total Sales");
        summarySheet.Cells["C1"].PutValue("Total Expenses");

        // Row index for the first data row (zero‑based, so 1 = Excel row 2)
        int dataRow = 1;

        // ----- Summary for SalesData worksheet -----
        summarySheet.Cells[dataRow, 0].PutValue("SalesData");
        // Sum the Sales column (B) from row 2 to a sufficiently large row number
        summarySheet.Cells[dataRow, 1].Formula = "=SUM(SalesData!B2:B1000)";

        // ----- Summary for ExpensesData worksheet -----
        summarySheet.Cells[dataRow, 2].Formula = "=SUM(ExpensesData!B2:B1000)";

        // Force calculation of the formulas so that the workbook contains the results
        designer.Workbook.CalculateFormula();

        // Save the final workbook with the summary sheet
        designer.Workbook.Save("AggregatedSummary.xlsx");
    }
}
