// Title: Aspose.Cells C# – Insert Blank Rows Between Grouped Smart Marker Rows (group:normal,skip:1)
// Description: Demonstrates how to create a workbook, define smart marker expressions with the (group:normal,skip:1) option, and automatically insert an empty row after each data group. The example uses a List<Item> as the data source, processes the markers with WorkbookDesigner, and saves the result as GroupedSmartMarkers.xlsx.
// Keywords: Aspose.Cells | C# | smart markers | group:normal | skip:1 | blank row insertion | grouped rows | WorkbookDesigner | Excel report generation | data source list
// Common Searches: add empty row after each smart marker group Aspose.Cells C# | Aspose.Cells group normal skip 1 example | generate grouped Excel output with spacer rows using Aspose.Cells
// Developer Intent: Create an Excel workbook where each smart‑marker group is automatically followed by a blank row, using Aspose.Cells for .NET.
// Use Cases: Sales summary where product categories are grouped and a visual gap separates each category. | Inventory sheet that clusters items by warehouse section and inserts a spacer row for readability. | Financial ledger that groups transactions by type and adds an empty row between groups to improve layout.
// AI Prompts: Show how to change the group type or skip count in the smart marker expression for different spacing needs. | Provide a C# snippet that adds a subtotal row after each grouped block while still using (group:normal,skip:1). | Explain how to set row height and apply a style to the blank rows generated by the group:normal,skip:1 option.

using System;
using System.Collections.Generic;
using Aspose.Cells;

// Demonstrates how to create a workbook, define smart marker expressions with the (group:normal,skip:1) option, and automatically insert an empty row after each data group. The example uses a List<Item> as the data source, processes the markers with WorkbookDesigner, and saves the result as GroupedSmartMarkers.xlsx.
class Program
{
    static void Main()
    {
        // Create a new workbook (template)
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        Cells cells = sheet.Cells;

        // Header row
        cells["A1"].PutValue("Category");
        cells["B1"].PutValue("Amount");

        // Smart marker row with grouping.
        // (group:normal,skip:1) inserts a blank row after each group.
        cells["A2"].PutValue("&Items.Category(group:normal,skip:1)");
        cells["B2"].PutValue("&Items.Amount(group:normal,skip:1)");

        // Sample data source
        List<Item> items = new List<Item>
        {
            new Item { Category = "Fruits",      Amount = 120 },
            new Item { Category = "Fruits",      Amount = 150 },
            new Item { Category = "Vegetables", Amount = 200 },
            new Item { Category = "Vegetables", Amount = 180 },
            new Item { Category = "Fruits",      Amount = 130 }
        };

        // Set up the designer and process smart markers
        WorkbookDesigner designer = new WorkbookDesigner();
        designer.Workbook = workbook;
        designer.SetDataSource("Items", items);
        designer.Process(); // processes all smart markers in the workbook

        // Save the resulting workbook
        workbook.Save("GroupedSmartMarkers.xlsx");
    }

    // Simple data class used as the smart marker data source
    public class Item
    {
        public string Category { get; set; }
        public double Amount { get; set; }
    }
}
