// Title: Group master‑detail rows with Aspose.Cells Smart Marker GroupBy in C#
// Description: Demonstrates how to create a new Workbook, define smart markers using the `GroupBy=CustomerName` syntax, bind a List<Order> (each with a List<OrderDetail>) as the data source, process the markers, and save an Excel file that displays hierarchical master‑detail rows.
// Keywords: Aspose.Cells | smart markers | GroupBy syntax | C# | master detail | hierarchical table | Excel export | WorkbookDesigner | group rows | data binding | Excel report | Aspose.Cells example
// Common Searches: Aspose.Cells GroupBy smart marker example | C# master detail grouping with smart markers | how to create hierarchical tables in Excel using Aspose.Cells | group rows by customer name Aspose.Cells | smart marker grouping syntax tutorial
// Developer Intent: Create an Excel workbook that automatically groups master‑detail data into hierarchical rows using Aspose.Cells smart marker GroupBy.
// Use Cases: Sales report that groups orders by customer with product lines listed underneath. | Inventory shipment list grouped by warehouse location with item details per warehouse. | Financial statement that groups transactions by account category and shows individual entries.
// AI Prompts: Add a subtotal row for each CustomerName group in the GroupBy smart marker layout. | Apply conditional formatting to the grouped rows generated by the smart marker. | Export the grouped workbook to PDF while preserving the hierarchy created by the GroupBy smart marker.

using System;
using System.Collections.Generic;
using Aspose.Cells;

namespace AsposeCellsSmartMarkerGroupingDemo
{
    // Master (order) class
    // Demonstrates how to create a new Workbook, define smart markers using the `GroupBy=CustomerName` syntax, bind a List<Order> (each with a List<OrderDetail>) as the data source, process the markers, and save an Excel file that displays hierarchical master‑detail rows.
    public class Order
    {
        public string CustomerName { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
    }

    // Detail (order line) class
    public class OrderDetail
    {
        public string Product { get; set; }
        public int Quantity { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            try
            {
                // Create a new workbook (lifecycle rule: create)
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Define smart markers with grouping syntax.
                // The first column groups rows by CustomerName.
                // Subsequent columns display detail fields.
                cells["A1"].PutValue("&=$Orders.GroupBy=CustomerName");
                cells["B1"].PutValue("&=$Orders.OrderDetails.Product");
                cells["C1"].PutValue("&=$Orders.OrderDetails.Quantity");

                // Prepare master‑detail data.
                List<Order> orders = new List<Order>
                {
                    new Order
                    {
                        CustomerName = "Alice",
                        OrderDetails = new List<OrderDetail>
                        {
                            new OrderDetail { Product = "Pen", Quantity = 10 },
                            new OrderDetail { Product = "Notebook", Quantity = 5 }
                        }
                    },
                    new Order
                    {
                        CustomerName = "Bob",
                        OrderDetails = new List<OrderDetail>
                        {
                            new OrderDetail { Product = "Pencil", Quantity = 12 },
                            new OrderDetail { Product = "Eraser", Quantity = 7 },
                            new OrderDetail { Product = "Ruler", Quantity = 3 }
                        }
                    },
                    new Order
                    {
                        CustomerName = "Charlie",
                        OrderDetails = new List<OrderDetail>
                        {
                            new OrderDetail { Product = "Marker", Quantity = 8 }
                        }
                    }
                };

                // Set the data source for the smart markers (lifecycle rule: set data source)
                WorkbookDesigner designer = new WorkbookDesigner(workbook);
                designer.SetDataSource("Orders", orders);

                // Process the smart markers (lifecycle rule: process)
                designer.Process();

                // Save the result workbook (lifecycle rule: save)
                string outputPath = "GroupedMasterDetail.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
