// Title: C# – Paginate Smart Marker Output in Aspose.Cells by Limiting Rows per Sheet and Adding New Worksheets
// Description: Shows how to create a workbook with range smart markers, populate it from a List<Person>, and automatically split the data into multiple worksheets when a configurable row limit is exceeded, while preserving cell values and styles.
// Keywords: Aspose.Cells | C# | smart markers | range smart markers | pagination | split worksheet | Excel row limit | auto create sheets | data overflow handling | WorkbookDesigner
// Common Searches: Aspose.Cells paginate smart marker rows | split smart marker output into multiple sheets .NET | limit rows per worksheet Aspose.Cells | auto create new worksheets for overflow data | C# example smart marker pagination
// Developer Intent: The developer needs to restrict the number of rows generated by smart markers on a single worksheet and have the library automatically create additional worksheets for any excess rows.
// Use Cases: Create a personnel report where each sheet contains no more than 20 records, with extra records moved to Part2, Part3, etc. | Generate printable Excel workbooks that require a fixed row count per page, using smart markers for data binding. | Process large data sets with range smart markers while keeping original formatting across paginated sheets.
// AI Prompts: Refactor PaginateWorksheet to use Worksheet.CopyRows for better performance. | Modify the code so the header row is copied to every newly created worksheet. | Add a footer row to each paginated sheet and adjust the row‑limit logic accordingly.

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPaginationDemo
{
    // Sample data class for smart markers
    // Shows how to create a workbook with range smart markers, populate it from a List<Person>, and automatically split the data into multiple worksheets when a configurable row limit is exceeded, while preserving cell values and styles.
    public class Person
    {
        public string Name { get; set; } = string.Empty;
        public int Age { get; set; }
    }

    class Program
    {
        // Maximum number of data rows per worksheet (excluding header)
        private const int MaxRowsPerSheet = 20;

        static void Main()
        {
            try
            {
                // -------------------------------------------------
                // 1. Create a workbook and set up smart markers
                // -------------------------------------------------
                Workbook workbook = new Workbook();                     // create workbook
                Worksheet sheet = workbook.Worksheets[0];               // first worksheet
                Cells cells = sheet.Cells;

                // Header row
                cells["A1"].PutValue("Name");
                cells["B1"].PutValue("Age");

                // Smart marker row (range smart markers)
                cells["A2"].PutValue("&=Persons.Name");
                cells["B2"].PutValue("&=Persons.Age");

                // Define the range that contains smart markers
                Aspose.Cells.Range smRange = cells.CreateRange("A2:B2");
                smRange.Name = "_CellsSmartMarkers";

                // -------------------------------------------------
                // 2. Prepare data source (more rows than MaxRowsPerSheet)
                // -------------------------------------------------
                List<Person> persons = new List<Person>();
                for (int i = 1; i <= 55; i++)          // 55 rows to force overflow
                {
                    persons.Add(new Person { Name = $"Person {i}", Age = 20 + i });
                }

                // -------------------------------------------------
                // 3. Process smart markers
                // -------------------------------------------------
                WorkbookDesigner designer = new WorkbookDesigner
                {
                    Workbook = workbook
                    // LineByLine is obsolete; range smart markers are used by default
                };
                designer.SetDataSource("Persons", persons);
                designer.Process();                  // populate data into the sheet

                // -------------------------------------------------
                // 4. Paginate the populated worksheet
                // -------------------------------------------------
                PaginateWorksheet(workbook, sheet, MaxRowsPerSheet);

                // -------------------------------------------------
                // 5. Save the result
                // -------------------------------------------------
                string outputPath = "PaginatedOutput.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved to {Path.GetFullPath(outputPath)}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        /// <param name="workbook">Parent workbook.</param>
        /// <param name="sourceSheet">Worksheet that contains the populated data.</param>
        /// <param name="maxRows">Maximum rows per sheet (including header).</param>
        private static void PaginateWorksheet(Workbook workbook, Worksheet sourceSheet, int maxRows)
        {
            // Determine the last used row and column
            int lastRow = sourceSheet.Cells.MaxDataRow;
            int lastCol = sourceSheet.Cells.MaxDataColumn;

            // If the data fits within the limit, nothing to do
            if (lastRow + 1 <= maxRows) return;   // +1 because rows are zero‑based

            // Row index where overflow starts (skip header row)
            int overflowStartRow = maxRows - 1;    // header is row 0, data starts at row 1

            int part = 2; // part number for naming new sheets
            while (overflowStartRow <= lastRow)
            {
                // Create a new worksheet for the overflow part
                int newSheetIdx = workbook.Worksheets.Add();
                Worksheet newSheet = workbook.Worksheets[newSheetIdx];
                newSheet.Name = $"{sourceSheet.Name}_Part{part}";

                // Number of rows to copy in this iteration
                int rowsToCopy = Math.Min(maxRows - 1, lastRow - overflowStartRow + 1);

                // Copy rows from source to the new sheet
                for (int r = 0; r < rowsToCopy; r++)
                {
                    for (int c = 0; c <= lastCol; c++)
                    {
                        Cell srcCell = sourceSheet.Cells[overflowStartRow + r, c];
                        if (srcCell.Value != null)
                        {
                            Cell destCell = newSheet.Cells[r, c];
                            destCell.PutValue(srcCell.Value);
                            destCell.SetStyle(srcCell.GetStyle());
                        }
                    }
                }

                // Advance to the next block of rows
                overflowStartRow += rowsToCopy;
                part++;
            }

            // Optional: clear overflow rows from the original sheet to keep it tidy
            for (int r = maxRows - 1; r <= lastRow; r++)
            {
                sourceSheet.Cells.DeleteRow(r);
            }
        }
    }
}
