// Title: Use a Formula parameter in an Aspose.Cells smart marker to calculate a SUM after data population (C#)
// AI Prompts: Write C# code that adds a smart marker with a Formula=SUM(...) parameter, binds a DataTable, processes it with WorkbookDesigner, and saves the result. | Show how to embed an Excel formula inside a smart marker so the formula is evaluated after the data source is applied in Aspose.Cells. | Create an example that demonstrates dynamic total calculation using a smart marker formula and outputs the workbook to a file.
// Common Searches: aspnet add formula parameter to Aspose.Cells smart marker for sum calculation | c# workbookdesigner evaluate smart marker formula after populating datatable | dynamic excel formula in smart markers using Aspose.Cells .NET | how to compute totals with smart markers and formula parameter in Aspose.Cells
// Tags: smart marker formula parameter | WorkbookDesigner evaluate formula | Aspose.Cells dynamic sum calculation | populate DataTable into smart markers | Excel formula evaluation C# Aspose.Cells

using System;
using System.Data;
using Aspose.Cells;

// The example creates a workbook, inserts smart markers for data values, adds a smart marker with a Formula=SUM(B2:B5) in cell A1, binds a DataTable as the data source, processes the markers with WorkbookDesigner, and saves the populated file as SmartMarkerFormula.xlsx.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Insert smart markers for data values in column B (rows 2‑5)
        sheet.Cells["B2"].PutValue("${Value}");
        sheet.Cells["B3"].PutValue("${Value}");
        sheet.Cells["B4"].PutValue("${Value}");
        sheet.Cells["B5"].PutValue("${Value}");

        // Insert a smart marker with a Formula parameter in cell A1.
        // The formula will be evaluated after data population.
        sheet.Cells["A1"].PutValue("Total: ${Total:Formula=SUM(B2:B5)}");

        // Prepare the data source (a DataTable) that matches the smart marker fields
        DataTable dt = new DataTable("Data");
        dt.Columns.Add("Value", typeof(double));
        dt.Columns.Add("Total", typeof(string)); // placeholder; value will be generated by the formula

        // Add sample rows for the "Value" field
        dt.Rows.Add(10);
        dt.Rows.Add(20);
        dt.Rows.Add(30);
        dt.Rows.Add(40);

        // Use WorkbookDesigner to process the smart markers
        WorkbookDesigner designer = new WorkbookDesigner(workbook);
        designer.SetDataSource(dt);
        designer.Process();

        // Save the populated workbook
        workbook.Save("SmartMarkerFormula.xlsx");
    }
}
