// Title: Create a Multi‑Sheet Excel Report with Distinct Smart Markers Using Aspose.Cells for .NET (C#)
// Description: Load an Excel template that contains smart markers on several worksheets, bind each sheet to its own DataTable (Employees, Products, SalesSummary) via WorkbookDesigner.SetDataSource, call designer.Process() to populate all markers, and save the result as a multi‑sheet report.
// Keywords: Aspose.Cells C# smart markers | WorkbookDesigner set data source | multi sheet Excel report .NET | populate multiple worksheets from template | process smart markers workbook | Excel automation Aspose.Cells | generate report from Excel template | Aspose.Cells multi‑sheet example | C# data tables to Excel smart markers | Aspose.Cells smart marker tutorial
// Common Searches: Aspose.Cells fill smart markers on multiple sheets | C# WorkbookDesigner process all worksheets | set different data sources for each Excel sheet using smart markers | generate multi‑sheet report from template Aspose.Cells | smart markers example with several worksheets .NET | how to bind DataTable to smart marker in Aspose.Cells
// Developer Intent: Generate a multi‑sheet Excel report by processing smart markers on each worksheet of a template workbook with separate data sources.
// Use Cases: Populate an Employees sheet with Name, Age, and Department columns from a DataTable. | Fill a Products sheet with Title, Price, and Stock values using a second DataTable. | Create a SalesSummary sheet that lists Region and TotalSales from a third DataTable.
// AI Prompts: Show how to add a fourth worksheet with its own smart marker and data source using WorkbookDesigner. | Explain how to apply conditional formatting to cells generated by smart markers across all sheets. | Provide robust error‑handling patterns for processing large workbooks with many smart markers.

using System;
using System.Data;
using System.IO;
using Aspose.Cells;

namespace MultiSheetSmartMarkerDemo
{
    // Load an Excel template that contains smart markers on several worksheets, bind each sheet to its own DataTable (Employees, Products, SalesSummary) via WorkbookDesigner.SetDataSource, call designer.Process() to populate all markers, and save the result as a multi‑sheet report.
    public class ReportGenerator
    {
        public static void Run()
        {
            try
            {
                string templatePath = "TemplateWithSmartMarkers.xlsx";

                // Ensure the template file exists before loading.
                if (!File.Exists(templatePath))
                {
                    Console.WriteLine($"Template file not found: {templatePath}");
                    return;
                }

                // Load the template workbook containing smart markers.
                Workbook templateWorkbook = new Workbook(templatePath);

                // Create a WorkbookDesigner and assign the loaded workbook.
                WorkbookDesigner designer = new WorkbookDesigner(templateWorkbook);

                // -------------------------------------------------
                // Prepare data source for the first worksheet (Employees)
                // -------------------------------------------------
                DataTable employeesTable = new DataTable("Employees");
                employeesTable.Columns.Add("Name", typeof(string));
                employeesTable.Columns.Add("Age", typeof(int));
                employeesTable.Columns.Add("Department", typeof(string));

                employeesTable.Rows.Add("John Doe", 30, "Sales");
                employeesTable.Rows.Add("Jane Smith", 28, "Marketing");
                employeesTable.Rows.Add("Bob Johnson", 45, "HR");

                designer.SetDataSource("Employees", employeesTable);

                // -------------------------------------------------
                // Prepare data source for the second worksheet (Products)
                // -------------------------------------------------
                DataTable productsTable = new DataTable("Products");
                productsTable.Columns.Add("Title", typeof(string));
                productsTable.Columns.Add("Price", typeof(decimal));
                productsTable.Columns.Add("Stock", typeof(int));

                productsTable.Rows.Add("Laptop", 1200.50m, 15);
                productsTable.Rows.Add("Smartphone", 799.99m, 40);
                productsTable.Rows.Add("Tablet", 450.00m, 25);

                designer.SetDataSource("Products", productsTable);

                // -------------------------------------------------
                // Prepare data source for the third worksheet (SalesSummary)
                // -------------------------------------------------
                DataTable summaryTable = new DataTable("SalesSummary");
                summaryTable.Columns.Add("Region", typeof(string));
                summaryTable.Columns.Add("TotalSales", typeof(double));

                summaryTable.Rows.Add("North", 150000);
                summaryTable.Rows.Add("South", 120000);
                summaryTable.Rows.Add("East", 95000);
                summaryTable.Rows.Add("West", 110000);

                designer.SetDataSource("SalesSummary", summaryTable);

                // Process all smart markers across the entire workbook.
                designer.Process();

                // Save the populated workbook as the final multi‑sheet report.
                string outputPath = "MultiSheetReport.xlsx";
                designer.Workbook.Save(outputPath);
                Console.WriteLine($"Report generated successfully: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error generating report: {ex.Message}");
            }
        }
    }

    // Entry point for the application.
    public class Program
    {
        public static void Main(string[] args)
        {
            ReportGenerator.Run();
        }
    }
}
