// Title: Use Parallel.For to Process Aspose.Cells Smart Markers on Large DataTables and Merge Results in C#
// AI Prompts: Generate C# code that splits a DataTable into 10,000‑row chunks, clones an Excel template, and runs WorkbookDesigner.Process() on each chunk in parallel. | Show how to combine the first worksheet from each processed workbook into a single workbook and save it as an XLSX file. | Add per‑task exception handling and logging while ensuring the template workbook is safely cloned for concurrent smart‑marker processing.
// Common Searches: how to speed up Aspose.Cells smart marker processing for 100k rows in C# | parallel processing of Excel smart markers using WorkbookDesigner and Parallel.For | merge worksheets generated by multiple Aspose.Cells tasks into one workbook | thread‑safe cloning of Excel template for concurrent smart marker execution
// Tags: parallel WorkbookDesigner execution | data chunking for smart markers | consolidate processed worksheets | thread‑safe template copy Aspose.Cells | scalable Excel output C#

using System;
using System.Data;
using System.IO;
using System.Threading.Tasks;
using Aspose.Cells;

// The example loads an Excel template containing smart markers, divides a massive DataTable into 10,000‑row chunks, and processes each chunk concurrently by cloning the template, assigning the chunk as a DataSet source, and invoking WorkbookDesigner.Process(). Processed workbooks are collected, their first worksheets are consolidated into a final workbook, and the merged file is saved as Result.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Path to the template workbook (contains smart markers)
            const string templatePath = "Template.xlsx";

            // Ensure the template file exists to avoid FileNotFoundException
            if (!File.Exists(templatePath))
                throw new FileNotFoundException($"Template file not found: {templatePath}");

            // Load the template workbook
            Workbook template = new Workbook(templatePath);

            // Obtain the massive data set to populate (replace with actual data source)
            DataTable massiveTable = GetMassiveData();

            // Define chunk size for parallel processing
            const int chunkSize = 10000;
            int totalRows = massiveTable.Rows.Count;
            int chunkCount = (totalRows + chunkSize - 1) / chunkSize;

            // Array to hold processed workbooks from each thread
            Workbook[] processedWorkbooks = new Workbook[chunkCount];

            // Process each chunk in parallel
            Parallel.For(0, chunkCount, chunkIndex =>
            {
                try
                {
                    // Clone the template for thread‑safe processing
                    Workbook wb = new Workbook();
                    wb.Copy(template);

                    // Create a slice of the massive data for this chunk
                    DataTable slice = massiveTable.Clone();
                    int startRow = chunkIndex * chunkSize;
                    int endRow = Math.Min(startRow + chunkSize, totalRows);
                    for (int r = startRow; r < endRow; r++)
                        slice.ImportRow(massiveTable.Rows[r]);

                    // Wrap the slice in a DataSet (required by the designer)
                    DataSet ds = new DataSet();
                    ds.Tables.Add(slice);

                    // Execute smart marker processing on the cloned workbook
                    WorkbookDesigner designer = new WorkbookDesigner(wb);
                    designer.SetDataSource(ds);
                    designer.Process();

                    // Store the processed workbook for later merging
                    processedWorkbooks[chunkIndex] = wb;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error processing chunk {chunkIndex}: {ex.Message}");
                }
            });

            // Merge all processed worksheets into a single final workbook
            Workbook finalWorkbook = new Workbook();
            // Remove the default empty sheet
            if (finalWorkbook.Worksheets.Count > 0)
                finalWorkbook.Worksheets.RemoveAt(0);

            foreach (Workbook wb in processedWorkbooks)
            {
                if (wb != null && wb.Worksheets.Count > 0)
                {
                    // Copy the first worksheet (where smart markers were processed) into the final workbook
                    finalWorkbook.Worksheets.AddCopy(wb.Worksheets[0].Name);
                }
            }

            // Save the merged result
            finalWorkbook.Save("Result.xlsx");
            Console.WriteLine("Processing completed successfully. Result saved as Result.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Fatal error: {ex.Message}");
        }
    }

    // Example method to generate a massive DataTable; replace with real data retrieval logic
    static DataTable GetMassiveData()
    {
        DataTable dt = new DataTable("Data");
        dt.Columns.Add("Name", typeof(string));
        dt.Columns.Add("Value", typeof(double));

        // Simulate 100,000 rows of data
        for (int i = 0; i < 100000; i++)
        {
            dt.Rows.Add("Item " + i, i * 1.1);
        }

        return dt;
    }
}
