// Title: Sort a C# collection by a property and feed it to Aspose.Cells smart markers to generate rows in the required order
// AI Prompts: Sort a List<Person> by Age using LINQ and set the sorted list as the data source for WorkbookDesigner smart markers in C#. | Create an Excel workbook with smart markers that automatically expand rows based on a pre‑sorted collection in Aspose.Cells. | Replace an unsorted data source with an ordered collection before calling WorkbookDesigner.Process to control row order. | Generate a spreadsheet where smart marker rows appear in ascending Age by applying OrderBy to the data source.
// Common Searches: C# Aspose.Cells smart markers how to sort data before processing | order rows generated by smart markers using WorkbookDesigner | use LINQ OrderBy with Aspose.Cells smart markers data source | generate Excel rows in specific sequence with Aspose.Cells smart markers | Aspose.Cells smart markers sorted output example C#
// Tags: linq orderby for WorkbookDesigner data source | aspocells smart markers with sorted rows | c# sort collection before smart marker processing | excel output ordered by property using Aspose.Cells | set ordered data source for smart markers

using System;
using System.Collections.Generic;
using System.Linq;
using Aspose.Cells;

namespace SmartMarkerSortingDemo
{
    // Sample data class
    // The example creates a List<Person>, sorts it by Age with LINQ, assigns the sorted list to WorkbookDesigner as the data source for smart markers, processes the markers so rows are generated in ascending Age order, and saves the workbook as SortedSmartMarkersOutput.xlsx.
    public class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }

    public class Program
    {
        public static void Main()
        {
            // 1. Prepare unsorted data
            List<Person> people = new List<Person>
            {
                new Person { Name = "Alice", Age = 30 },
                new Person { Name = "Bob",   Age = 25 },
                new Person { Name = "Carol", Age = 35 }
            };

            // 2. Sort the collection by the required property (Age ascending)
            List<Person> sortedPeople = people.OrderBy(p => p.Age).ToList();

            // 3. Create a workbook and define smart markers
            Workbook workbook = new Workbook();                     // create workbook
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("&=$Name");                 // smart marker for Name
            sheet.Cells["B1"].PutValue("&=$Age");                  // smart marker for Age

            // 4. Initialize WorkbookDesigner with the workbook
            WorkbookDesigner designer = new WorkbookDesigner(workbook);

            // 5. Set the sorted data source (the name "People" can be any identifier)
            designer.SetDataSource("People", sortedPeople);

            // 6. Process smart markers – rows will be generated in the sorted order
            designer.Process();

            // 7. Save the result
            workbook.Save("SortedSmartMarkersOutput.xlsx");
        }
    }
}
