// Title: C# – Generate a Variable‑Length Milestone List with foreach Smart Markers and Add an Excel Timeline using Aspose.Cells
// Description: This example shows how to create a workbook, store milestone data in a hidden sheet, place foreach smart markers on a timeline sheet, expand rows automatically, build a PivotTable from the hidden data, attach a Timeline control linked to the PivotTable, and save the result as an Excel file.
// Keywords: Aspose.Cells | C# | foreach smart marker | dynamic rows | project milestones | Excel timeline control | PivotTable from DataTable | smart markers variable length | Excel automation | timeline report
// Common Searches: foreach smart marker Aspose.Cells example | create timeline control from PivotTable C# | dynamic milestone list Excel using Aspose | how to use smart markers to generate rows | Aspose.Cells timeline with hidden data sheet
// Developer Intent: Automatically expand rows for each milestone using foreach smart markers and display the data on an interactive timeline linked to a PivotTable.
// Use Cases: Populate a timeline sheet with any number of project milestones stored in a DataTable. | Generate a PivotTable on the fly from hidden data and connect it to a Timeline control for date filtering. | Produce an Excel report that adjusts its row count without manual editing.
// AI Prompts: Add a status column to the milestone list using foreach smart markers. | Apply conditional formatting to rows generated by the foreach smart marker. | Export the workbook with the timeline control to PDF while preserving interactivity.

using System;
using System.Data;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Pivot;
using Aspose.Cells.Timelines;

namespace AsposeCellsSmartMarkerTimelineDemo
{
    // This example shows how to create a workbook, store milestone data in a hidden sheet, place foreach smart markers on a timeline sheet, expand rows automatically, build a PivotTable from the hidden data, attach a Timeline control linked to the PivotTable, and save the result as an Excel file.
    class Program
    {
        static void Main()
        {
            try
            {
                // ------------------------------------------------------------
                // 1. Create a new workbook and add two worksheets:
                //    - Sheet0: will contain the smart markers and the timeline.
                //    - DataSheet: holds the raw milestone data.
                // ------------------------------------------------------------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0]; // Timeline sheet
                Worksheet dataSheet = workbook.Worksheets[workbook.Worksheets.Add()];
                dataSheet.Name = "Data";

                // ------------------------------------------------------------
                // 2. Prepare the raw milestone data in a DataTable.
                // ------------------------------------------------------------
                DataTable milestonesTable = new DataTable("Milestones");
                milestonesTable.Columns.Add("Milestone", typeof(string));
                milestonesTable.Columns.Add("Date", typeof(DateTime));

                milestonesTable.Rows.Add("Project Kick‑off", new DateTime(2023, 1, 15));
                milestonesTable.Rows.Add("Requirement Sign‑off", new DateTime(2023, 2, 10));
                milestonesTable.Rows.Add("Design Completion", new DateTime(2023, 3, 5));
                milestonesTable.Rows.Add("Development Start", new DateTime(2023, 4, 1));
                milestonesTable.Rows.Add("First Release", new DateTime(2023, 6, 20));

                // ------------------------------------------------------------
                // 3. Write the same data into the hidden Data sheet.
                // ------------------------------------------------------------
                dataSheet.Cells["A1"].PutValue("Milestone");
                dataSheet.Cells["B1"].PutValue("Date");
                for (int i = 0; i < milestonesTable.Rows.Count; i++)
                {
                    dataSheet.Cells[i + 1, 0].PutValue(milestonesTable.Rows[i]["Milestone"]);
                    dataSheet.Cells[i + 1, 1].PutValue((DateTime)milestonesTable.Rows[i]["Date"]);
                }

                // ------------------------------------------------------------
                // 4. Set up the smart markers on the Timeline sheet.
                // ------------------------------------------------------------
                sheet.Cells["A1"].PutValue("Milestone");
                sheet.Cells["B1"].PutValue("Date");
                sheet.Cells["A2"].PutValue("&=Milestones.Milestone"); // foreach marker
                sheet.Cells["B2"].PutValue("&=Milestones.Date");     // foreach marker

                // ------------------------------------------------------------
                // 5. Process the smart markers.
                // ------------------------------------------------------------
                WorkbookDesigner designer = new WorkbookDesigner(workbook);
                designer.SetDataSource(milestonesTable);
                designer.Process(); // expands rows based on the foreach markers

                // ------------------------------------------------------------
                // 6. Create a PivotTable that uses the data from the hidden Data sheet.
                // ------------------------------------------------------------
                int lastRow = dataSheet.Cells.MaxDataRow;
                int lastCol = dataSheet.Cells.MaxDataColumn;
                string dataRange = $"Data!A1:{CellIndexToName(lastRow, lastCol)}";

                // Add the PivotTable to the Timeline sheet (e.g., starting at C5).
                int pivotIndex = sheet.PivotTables.Add(dataRange, "C5", "MilestonesPivot");
                PivotTable pivot = sheet.PivotTables[pivotIndex];

                // Add the Date field to the Row area (base field) and Milestone to Data area.
                pivot.AddFieldToArea(PivotFieldType.Row, "Date");
                pivot.AddFieldToArea(PivotFieldType.Data, "Milestone");

                // Refresh and calculate the PivotTable.
                pivot.RefreshData();
                pivot.CalculateData();

                // ------------------------------------------------------------
                // 7. Add a Timeline control linked to the PivotTable.
                // ------------------------------------------------------------
                sheet.Timelines.Add(pivot, "E1", "Date");

                // ------------------------------------------------------------
                // 8. Save the workbook.
                // ------------------------------------------------------------
                string outputPath = "MilestonesTimeline.xlsx";
                string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
                if (!Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }

        // Helper method to convert zero‑based row/column indexes to Excel cell name (e.g., 0,0 -> A1).
        private static string CellIndexToName(int rowIndex, int columnIndex)
        {
            // Convert column index to letters.
            int dividend = columnIndex + 1;
            string columnName = string.Empty;
            while (dividend > 0)
            {
                int modulo = (dividend - 1) % 26;
                columnName = Convert.ToChar(65 + modulo) + columnName;
                dividend = (dividend - modulo) / 26;
            }

            // Row index is zero‑based; Excel rows start at 1.
            int rowNumber = rowIndex + 1;
            return $"{columnName}{rowNumber}";
        }
    }
}
