// Title: C# – Compute Weighted Average with Smart Markers Using the Formula Parameter in Aspose.Cells
// Description: This example creates a workbook, inserts smart markers for Item, Value, and Weight, binds a DataTable as the data source, processes the markers, then adds a SUMPRODUCT formula via the Formula parameter to calculate the weighted average, evaluates all formulas, prints the result, and saves the file.
// Keywords: Aspose.Cells weighted average | smart markers formula parameter | C# SUMPRODUCT Aspose | calculate weighted average Excel | dynamic formula after smart marker processing
// Common Searches: Aspose.Cells formula parameter weighted average | C# smart markers SUMPRODUCT example | how to compute weighted average after processing smart markers | Aspose.Cells calculate average from DataTable rows
// Developer Intent: Insert a formula that automatically calculates the weighted average of values generated by smart markers.
// Use Cases: Generate a financial report where line‑item values and weights are filled via smart markers and the sheet returns the overall weighted average. | Build a dynamic pricing sheet that populates product data with smart markers and derives a weighted discount without manual cell references. | Create a statistical dashboard that imports a DataTable, populates rows through smart markers, and computes a weighted mean for analysis.
// AI Prompts: Show how to adapt the formula for an unknown number of rows after smart marker processing. | Generate C# code that calculates a weighted average only for rows where weight > 0 using Aspose.Cells. | Explain how to retrieve the computed weighted average value programmatically after calling Workbook.CalculateFormula().

using System;
using System.Data;
using Aspose.Cells;

// This example creates a workbook, inserts smart markers for Item, Value, and Weight, binds a DataTable as the data source, processes the markers, then adds a SUMPRODUCT formula via the Formula parameter to calculate the weighted average, evaluates all formulas, prints the result, and saves the file.
class WeightedAverageWithSmartMarkers
{
    static void Main()
    {
        try
        {
            // 1. Create a new workbook (lifecycle: create)
            Workbook wb = new Workbook();
            Worksheet ws = wb.Worksheets[0];
            Cells cells = ws.Cells;

            // 2. Define a simple template with smart markers for values and weights
            // Header
            cells["A1"].PutValue("Item");
            cells["B1"].PutValue("Value");
            cells["C1"].PutValue("Weight");

            // Smart marker rows (starting from row 2)
            // &="Data.Item"   &="Data.Value"   &="Data.Weight"
            cells["A2"].PutValue("&=Data.Item");
            cells["B2"].PutValue("&=Data.Value");
            cells["C2"].PutValue("&=Data.Weight");

            // 3. Prepare data source (DataTable) matching the smart markers
            DataTable dt = new DataTable("Data");
            dt.Columns.Add("Item", typeof(string));
            dt.Columns.Add("Value", typeof(double));
            dt.Columns.Add("Weight", typeof(double));

            dt.Rows.Add("A", 10, 2);
            dt.Rows.Add("B", 20, 3);
            dt.Rows.Add("C", 30, 5);

            // 4. Bind data source to the workbook designer and process smart markers (lifecycle: process)
            WorkbookDesigner designer = new WorkbookDesigner(wb);
            designer.SetDataSource(dt);
            designer.Process(); // populates rows 2-4 with the data

            // 5. After processing, add a formula to calculate the weighted average
            // Weighted Average = SUMPRODUCT(ValueRange,WeightRange) / SUM(WeightRange)
            // ValueRange: B2:B4, WeightRange: C2:C4
            cells["A5"].PutValue("Weighted Average");
            cells["B5"].Formula = "=SUMPRODUCT(B2:B4,C2:C4)/SUM(C2:C4)";

            // 6. Calculate all formulas in the workbook (lifecycle: calculate)
            wb.CalculateFormula();

            // 7. Output the calculated weighted average to console (optional verification)
            Console.WriteLine("Weighted Average: " + cells["B5"].StringValue);

            // 8. Save the workbook (lifecycle: save)
            wb.Save("WeightedAverageResult.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
