using System;
using Aspose.Cells;

namespace AsposeCellsHeaderFooterDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet worksheet = workbook.Worksheets[0];

            // Get the PageSetup object for the worksheet
            PageSetup pageSetup = worksheet.PageSetup;

            // -------------------------------------------------
            // 1. Enable different headers/footers for the first page
            // -------------------------------------------------
            pageSetup.IsHFDiffFirst = true;

            // Set first page header (left, center, right sections)
            pageSetup.SetFirstPageHeader(0, "&LFirst Page Left Header");
            pageSetup.SetFirstPageHeader(1, "&CFirst Page Center Header");
            pageSetup.SetFirstPageHeader(2, "&RFirst Page Right Header");

            // Set first page footer (center section)
            pageSetup.SetFirstPageFooter(1, "First Page Footer - Page &P of &N");

            // -------------------------------------------------
            // 2. Enable different headers/footers for odd and even pages
            // -------------------------------------------------
            pageSetup.IsHFDiffOddEven = true;

            // Odd page header (center section)
            pageSetup.SetHeader(1, "Odd Page Header - &A");

            // Even page header (center section)
            pageSetup.SetEvenHeader(1, "Even Page Header - &A");

            // Odd page footer (center section)
            pageSetup.SetFooter(1, "Odd Footer - &D");

            // Even page footer (center section)
            pageSetup.SetEvenFooter(1, "Even Footer - &D");

            // -------------------------------------------------
            // 3. Standard (default) header/footer for all other pages
            // -------------------------------------------------
            pageSetup.SetHeader(0, "&F"); // Left: file name
            pageSetup.SetHeader(2, "&P"); // Right: page number
            pageSetup.SetFooter(0, "Generated by Aspose.Cells");
            pageSetup.SetFooter(2, "Confidential");

            // Save the workbook to a file
            workbook.Save("HeadersFootersDemo.xlsx");
        }
    }
}