// Title: Aspose.Cells PdfSaveOptions.TextCrossType – control overflow text when converting Excel to PDF (C#)
// Description: Demonstrates how to use PdfSaveOptions.TextCrossType in Aspose.Cells for .NET to define the rendering of text that exceeds cell boundaries. The example creates a workbook, inserts a long string, narrows the column to force overflow, sets TextCrossType (CrossKeep, CrossOverride, StrictInCell) and saves the result as a PDF with precise layout control.
// Keywords: Aspose.Cells PdfSaveOptions TextCrossType | C# Excel to PDF overflow text | CrossKeep PDF layout Aspose | CrossOverride Aspose.Cells | StrictInCell PDF conversion | control text crossing Excel PDF | Aspose.Cells PDF rendering options | column width overflow Aspose
// Common Searches: Aspose.Cells TextCrossType example | How to prevent text overflow in PDF with Aspose.Cells | PdfSaveOptions CrossKeep vs CrossOverride | Set TextCrossType in C# Aspose.Cells | Excel cell overflow handling when saving to PDF
// Developer Intent: Apply the PdfSaveOptions.TextCrossType property to specify how text that exceeds a cell’s width is rendered in the PDF output generated by Aspose.Cells for .NET.
// Use Cases: Keep long text inside its original cell (CrossKeep) to maintain column alignment. | Allow overflow text to flow into the next cell (CrossOverride) for continuous reading. | Truncate overflow and keep strict cell boundaries (StrictInCell) for exact layout constraints.
// AI Prompts: Generate C# code that saves an Excel workbook to PDF using Aspose.Cells with TextCrossType.CrossOverride so overflow text appears in the adjacent cell. | Explain the differences between CrossKeep, CrossOverride, and StrictInCell in Aspose.Cells PdfSaveOptions.TextCrossType and suggest best‑practice scenarios. | Provide a step‑by‑step tutorial for adjusting column widths and applying TextCrossType.CrossKeep to achieve precise PDF layout in Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfTextCrossDemo
{
    // Demonstrates how to use PdfSaveOptions.TextCrossType in Aspose.Cells for .NET to define the rendering of text that exceeds cell boundaries. The example creates a workbook, inserts a long string, narrows the column to force overflow, sets TextCrossType (CrossKeep, CrossOverride, StrictInCell) and saves the result as a PDF with precise layout control.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add long text that would normally overflow cell boundaries
            sheet.Cells["A1"].PutValue("This is a very long piece of text that will exceed the width of the cell and demonstrate the TextCrossType setting.");
            sheet.Cells["B1"].PutValue("Adjacent cell content");

            // Reduce column width to force text crossing
            sheet.Cells.SetColumnWidth(0, 5); // Column A width

            // Create PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Activate TextCrossType to control how overflowing text is handled.
            // Options: Default, CrossKeep, CrossOverride, StrictInCell
            pdfOptions.TextCrossType = TextCrossType.CrossKeep;

            // Save the workbook as PDF with the configured options
            workbook.Save("TextCrossTypeDemo.pdf", pdfOptions);

            Console.WriteLine("PDF saved with TextCrossType.CrossKeep applied.");
        }
    }
}
