// Title: Add PDF security and simulate a digital signature with PdfSaveOptions in Aspose.Cells for .NET (C#)
// Description: Shows how to create a workbook, configure owner and user passwords, set printing and editing permissions via PdfSecurityOptions, attach them to PdfSaveOptions, and save the workbook as a protected PDF using Aspose.Cells for .NET.
// Keywords: Aspose.Cells PDF security | PdfSaveOptions C# | PdfSecurityOptions owner password | restrict PDF editing Aspose.Cells | digital signature simulation PDF | protect PDF Aspose.Cells | C# generate secured PDF | Aspose.Cells PDF permissions
// Common Searches: Aspose.Cells set PDF password C# | How to restrict PDF editing when saving workbook as PDF with Aspose.Cells | PdfSaveOptions security options example | Add simulated digital signature to PDF using Aspose.Cells | C# protect PDF generated from Excel with Aspose.Cells
// Developer Intent: The developer wants to protect a PDF generated from a workbook by applying passwords and permission restrictions, effectively simulating a digital signature.
// Use Cases: Create a confidential financial report that only authorized users can open, using owner and user passwords. | Distribute a PDF that permits printing but blocks content extraction and modifications to meet compliance requirements. | Provide external partners with a secured PDF version of an Excel workbook, ensuring the document cannot be altered without the owner password.
// AI Prompts: Show me how to apply a real X.509 certificate digital signature to a PDF using Aspose.Cells for .NET. | Explain how to configure PdfSecurityOptions to customize PDF permissions and passwords when saving a workbook as PDF in C#. | Provide example code to embed a visible signature image in a PDF generated by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsPdfSignatureDemo
{
    // Shows how to create a workbook, configure owner and user passwords, set printing and editing permissions via PdfSecurityOptions, attach them to PdfSaveOptions, and save the workbook as a protected PDF using Aspose.Cells for .NET.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some content
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Document with PDF security (digital signature simulation)");

            // Create PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Configure PDF security options (owner/user passwords and permissions)
            PdfSecurityOptions security = new PdfSecurityOptions
            {
                OwnerPassword = "OwnerSecret123",
                UserPassword = "UserSecret123",
                PrintPermission = true,                 // Allow printing
                ModifyDocumentPermission = false,       // Disallow modifications
                ExtractContentPermission = false        // Disallow content extraction
            };

            // Assign the security options to the PDF save options
            pdfOptions.SecurityOptions = security;

            // Save the workbook as a PDF with the configured security (digital signature like protection)
            workbook.Save("SecureSignedDocument.pdf", pdfOptions);

            Console.WriteLine("PDF saved with security options applied.");
        }
    }
}
