// Title: Add a PKCS#12 digital signature to a PDF created from an Excel workbook using Aspose.Cells PdfSaveOptions in C#
// AI Prompts: Write C# code that loads an Excel file, converts it to PDF with Aspose.Cells, and applies a digital signature using a .pfx (PKCS#12) certificate via PdfSaveOptions. | Explain how to configure PdfSaveOptions to embed a digital signature, including loading the certificate, setting the Signature property, and saving the signed PDF.
// Common Searches: c# aspnet add digital signature to pdf created from excel using aspose.cells | aspose.cells pdfsaveoptions sign pdf with pfx certificate | how to embed pkcs12 signature in pdf generated by aspose.cells | sign pdf output from workbook conversion aspose cells c# example | pdf digital signature aspose.cells pdfsaveoptions c# tutorial
// Tags: Aspose.Cells PDF digital signature with PdfSaveOptions | C# sign PDF using PKCS#12 certificate Aspose.Cells | PdfSaveOptions certificate signing for Excel to PDF conversion | embed digital signature in PDF generated by Aspose.Cells | Aspose.Cells signed PDF output C#

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, configures PdfSaveOptions with a PKCS#12 (.pfx) certificate to digitally sign the resulting PDF, and saves the signed document. It demonstrates certificate loading, setting the Signature property, and includes basic error handling for missing files and exceptions.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Verify that the input Excel file exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                return;
            }

            // Load the Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure PDF save options (default options are sufficient for basic conversion)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF file
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"Workbook successfully saved as PDF to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Log any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
