// Title: Add a Diagonal Text Watermark to a PDF with Aspose.Cells for .NET (Times New Roman, 24 pt, 30 % opacity)
// Description: This example creates a workbook, adds sample data, defines a 24‑point Times New Roman font, and applies a 45° rotated, 30 % opaque, centered text watermark behind the page content using RenderingWatermark. The watermark is attached to PdfSaveOptions and the workbook is saved as a PDF.
// Keywords: Aspose.Cells PDF watermark | RenderingWatermark diagonal text | watermark opacity Aspose.Cells | Times New Roman PDF watermark | PdfSaveOptions example | C# add watermark to PDF | .NET Aspose.Cells tutorial
// Common Searches: how to add a diagonal text watermark to a PDF with Aspose.Cells .NET | set watermark rotation and opacity using RenderingWatermark | center background watermark in PDF generated by Aspose.Cells | Aspose.Cells C# PDF watermark example
// Developer Intent: Generate a PDF from an Excel workbook that includes a semi‑transparent, diagonal text watermark with custom font settings.
// Use Cases: Create confidential reports where the watermark appears behind all worksheet data. | Brand marketing PDFs with a subtle diagonal label across each page. | Automate batch conversion of Excel files to PDFs while enforcing a consistent watermark.
// AI Prompts: Show how to change the watermark text, font size, and opacity dynamically based on workbook values. | Explain how to assign different watermarks to multiple worksheets when exporting each as a separate PDF. | Provide code to rotate the watermark at a custom angle and position it in the top‑right corner instead of centered.

using System;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsWatermarkDemo
{
    // This example creates a workbook, adds sample data, defines a 24‑point Times New Roman font, and applies a 45° rotated, 30 % opaque, centered text watermark behind the page content using RenderingWatermark. The watermark is attached to PdfSaveOptions and the workbook is saved as a PDF.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Add some sample data to visualize the watermark effect
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample data for watermark demonstration");

            // Create a rendering font with Times New Roman, 24‑point size
            RenderingFont font = new RenderingFont("Times New Roman", 24);

            // Create a text watermark using the font
            RenderingWatermark watermark = new RenderingWatermark("CONFIDENTIAL", font)
            {
                // Set diagonal orientation
                Rotation = 45f,
                // Set opacity to 30%
                Opacity = 0.3f,
                // Place the watermark behind the page contents
                IsBackground = true,
                // Center the watermark on the page
                HAlignment = TextAlignmentType.Center,
                VAlignment = TextAlignmentType.Center
            };

            // Configure PDF save options with the watermark
            PdfSaveOptions options = new PdfSaveOptions
            {
                Watermark = watermark
            };

            // Save the workbook as PDF with the diagonal watermark
            workbook.Save("DiagonalWatermark.pdf", options);
        }
    }
}
