// Title: Sign a PDF generated by Aspose.Cells with PdfSaveOptions and an X.509 certificate (C#)
// Description: Create a Workbook, add content, load a .pfx certificate, build a DigitalSignature, attach it to the workbook, configure PdfSaveOptions (including security settings), and save a tamper‑evident PDF that carries the digital signature.
// Keywords: Aspose.Cells PDF digital signature C# | PdfSaveOptions sign PDF | X509Certificate2 Aspose.Cells | C# add digital signature to PDF | Aspose.Cells PDF security options | sign PDF with .pfx certificate | Aspose.Cells workbook to signed PDF
// Common Searches: How to add a digital signature to a PDF using Aspose.Cells | Aspose.Cells PdfSaveOptions certificate signing example | C# sign PDF generated from Excel with Aspose.Cells | Set owner and user passwords when saving PDF with Aspose.Cells | Apply digital signature and permissions to PDF in .NET
// Developer Intent: Add an X.509 digital signature to a PDF produced from an Aspose.Cells workbook and optionally apply PDF security settings.
// Use Cases: Generate tamper‑evident PDF reports or invoices that must be signed with a corporate certificate. | Enforce printing and editing restrictions while embedding a digital seal for regulatory compliance. | Automate batch conversion of Excel files to signed PDFs for secure distribution to clients or auditors.
// AI Prompts: Provide C# code that signs a PDF created by Aspose.Cells using a .pfx certificate and sets owner/user passwords with PdfSaveOptions. | Show how to add multiple digital signatures to an Aspose.Cells workbook before exporting it as a signed PDF. | Explain how to verify the digital signature in the PDF after saving it with PdfSaveOptions in a .NET application.

using System;
using System.Security.Cryptography.X509Certificates;
using Aspose.Cells;
using Aspose.Cells.DigitalSignatures;
using Aspose.Cells.Rendering.PdfSecurity;

// Create a Workbook, add content, load a .pfx certificate, build a DigitalSignature, attach it to the workbook, configure PdfSaveOptions (including security settings), and save a tamper‑evident PDF that carries the digital signature.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some content
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].PutValue("Document with digital signature");

        // Load the signing certificate (replace with your actual .pfx file and password)
        X509Certificate2 certificate = new X509Certificate2("myCertificate.pfx", "certPassword");

        // Create a digital signature using the certificate
        DigitalSignature digitalSignature = new DigitalSignature(
            certificate,
            "Signed by Aspose.Cells",
            DateTime.UtcNow);

        // Add the signature to a collection and attach it to the workbook
        DigitalSignatureCollection signatureCollection = new DigitalSignatureCollection();
        signatureCollection.Add(digitalSignature);
        workbook.SetDigitalSignature(signatureCollection);

        // Configure PDF save options
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();

        // Optional: set PDF security options (owner/user passwords, permissions)
        PdfSecurityOptions securityOptions = new PdfSecurityOptions
        {
            OwnerPassword = "ownerPwd",
            UserPassword = "userPwd",
            PrintPermission = true,
            FullQualityPrintPermission = true
        };
        pdfSaveOptions.SecurityOptions = securityOptions;

        // Save the workbook as a PDF; the digital signature is carried over to the PDF
        workbook.Save("SignedDocument.pdf", pdfSaveOptions);
    }
}
