// Title: Embed Files as Attachments in PDF with Aspose.Cells PdfSaveOptions (C#)
// Description: Creates a workbook, writes a cell, generates a temporary DOCX file, enables PdfSaveOptions.EmbedAttachments, adds the DOCX to the PdfSaveOptions.Attachments collection (using reflection when the property is unavailable), saves the workbook as a PDF, and cleans up the temporary file.
// Keywords: Aspose.Cells | PdfSaveOptions | EmbedAttachments | PDF attachment | C# | .NET | reflection | Attachments collection | embed docx in PDF | add file to PDF
// Common Searches: How to add a file attachment to a PDF generated by Aspose.Cells | Aspose.Cells PdfSaveOptions Attachments property example | Enable EmbedAttachments in Aspose.Cells PDF export | Use reflection to add PDF attachments with Aspose.Cells | C# embed Word document in PDF using Aspose.Cells
// Developer Intent: Add external documents to the PDF produced by Aspose.Cells.
// Use Cases: Attach the original Excel workbook to a financial report PDF for audit purposes. | Include terms‑and‑conditions or warranty documents with an invoice PDF. | Bundle specification sheets or design files with product manual PDFs.
// AI Prompts: Generate C# code that adds multiple files to PdfSaveOptions.Attachments without using reflection. | Show how to verify that attachments are present in the saved PDF. | Explain version‑specific handling when the Attachments property is missing in Aspose.Cells.

using System;
using System.IO;
using System.Reflection;
using Aspose.Cells;

namespace AsposeCellsAttachmentDemo
{
    // Creates a workbook, writes a cell, generates a temporary DOCX file, enables PdfSaveOptions.EmbedAttachments, adds the DOCX to the PdfSaveOptions.Attachments collection (using reflection when the property is unavailable), saves the workbook as a PDF, and cleans up the temporary file.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add some content
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("PDF with embedded attachments");

                // Prepare a sample file to embed
                string samplePath = "sample.docx";
                if (!File.Exists(samplePath))
                {
                    File.WriteAllText(samplePath, "This is a sample document for attachment.");
                }

                // Create PDF save options and enable attachment embedding if supported
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    EmbedAttachments = true
                };

                // Attempt to add attachment via reflection (covers versions without direct Attachments property)
                try
                {
                    PropertyInfo attachmentsProp = typeof(PdfSaveOptions).GetProperty("Attachments");
                    if (attachmentsProp != null)
                    {
                        object attachments = attachmentsProp.GetValue(pdfOptions);
                        MethodInfo addMethod = attachments?.GetType().GetMethod("Add", new[] { typeof(string), typeof(byte[]) });
                        if (addMethod != null && File.Exists(samplePath))
                        {
                            byte[] fileData = File.ReadAllBytes(samplePath);
                            addMethod.Invoke(attachments, new object[] { "sample.docx", fileData });
                        }
                    }
                }
                catch (Exception ex)
                {
                    // Log any reflection-related issues and continue without attachment
                    Console.WriteLine($"Attachment embedding not supported via reflection: {ex.Message}");
                }

                // Save the workbook as PDF
                string pdfPath = "PdfWithAttachments.pdf";
                workbook.Save(pdfPath, pdfOptions);

                // Clean up the temporary sample file
                if (File.Exists(samplePath))
                {
                    File.Delete(samplePath);
                }

                Console.WriteLine($"PDF saved to {pdfPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
