// Title: Add PDF Bookmarks with Named Destinations to Cell Ranges using Aspose.Cells for .NET (C#)
// Description: Demonstrates how to create a workbook with three worksheets, assign each worksheet a destination cell, build a hierarchical PdfBookmarkEntry structure, set optional named destinations, enable ExportDocumentStructure for accessibility, and save the workbook as a PDF that contains clickable bookmarks.
// Keywords: Aspose.Cells PDF bookmarks C# | named destinations PDF Aspose | PdfSaveOptions bookmark hierarchy | export Excel to PDF with outline | .NET PDF navigation bookmarks | accessibility ExportDocumentStructure | Aspose.Cells example GitHub | C# workbook PDF table of contents
// Common Searches: how to add PDF bookmarks in Aspose.Cells C# | Aspose.Cells named destination for PDF bookmark | create hierarchical PDF outline from Excel .NET | export Excel to PDF with clickable table of contents Aspose | Aspose.Cells PDF accessibility ExportDocumentStructure
// Developer Intent: Generate a PDF from an Excel workbook that includes a multi‑level bookmark outline linked to specific cells.
// Use Cases: Build a PDF report with a clickable table of contents that jumps to Summary, Details, and Analysis sections. | Improve screen‑reader navigation by exporting document structure alongside custom bookmarks. | Provide fast navigation in large PDFs by mapping bookmarks to key cells across multiple worksheets.
// AI Prompts: Write C# code using Aspose.Cells to add PDF bookmarks with custom named destinations for several worksheets and save the file. | Show how to extend the bookmark tree with nested sub‑bookmarks and set their default open/closed state. | Explain how to modify an existing PDF generated by Aspose.Cells to update bookmark destinations or insert new entries.

using System;
using System.Collections;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfBookmarks
{
    // Demonstrates how to create a workbook with three worksheets, assign each worksheet a destination cell, build a hierarchical PdfBookmarkEntry structure, set optional named destinations, enable ExportDocumentStructure for accessibility, and save the workbook as a PDF that contains clickable bookmarks.
    class Program
    {
        static void Main()
        {
            // Create a new workbook with three worksheets
            Workbook workbook = new Workbook();
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "Summary";
            Worksheet sheet2 = workbook.Worksheets.Add("Details");
            Worksheet sheet3 = workbook.Worksheets.Add("Analysis");

            // Populate some cells that will serve as bookmark destinations
            sheet1.Cells["A1"].PutValue("Summary Overview");
            sheet2.Cells["B2"].PutValue("Detailed Data");
            sheet3.Cells["C3"].PutValue("Analytical Results");

            // ----- Create PDF bookmark hierarchy -----
            // Root bookmark (will appear at top level)
            PdfBookmarkEntry rootBookmark = new PdfBookmarkEntry
            {
                Text = "Workbook Bookmarks",
                Destination = sheet1.Cells["A1"],          // Destination cell for root
                DestinationName = "SummaryStart",          // Named destination (optional)
                IsOpen = true,                             // Expand root by default
                SubEntry = new ArrayList()
            };

            // First child bookmark pointing to sheet2
            PdfBookmarkEntry detailsBookmark = new PdfBookmarkEntry
            {
                Text = "Details Section",
                Destination = sheet2.Cells["B2"],
                DestinationName = "DetailsStart",
                IsOpen = false
            };

            // Second child bookmark pointing to sheet3
            PdfBookmarkEntry analysisBookmark = new PdfBookmarkEntry
            {
                Text = "Analysis Section",
                Destination = sheet3.Cells["C3"],
                DestinationName = "AnalysisStart",
                IsOpen = false
            };

            // Add child entries to the root
            rootBookmark.SubEntry.Add(detailsBookmark);
            rootBookmark.SubEntry.Add(analysisBookmark);

            // Configure PDF save options with the bookmark hierarchy
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                Bookmark = rootBookmark,
                ExportDocumentStructure = true   // Preserve document structure for accessibility
            };

            // Save the workbook as PDF with the defined bookmarks
            workbook.Save("WorkbookWithBookmarks.pdf", pdfOptions);
        }
    }
}
