// Title: Apply conditional formatting to an Excel column and preserve the colors when converting to PDF with Aspose.Cells for .NET
// AI Prompts: Create a workbook, add a conditional formatting rule that colors cells red when the value is greater than 50, and export the sheet to PDF using Aspose.Cells. | Define a second rule that fills cells light‑green for values less than 20, recalculate formulas, and save the workbook as a PDF while keeping the formatting intact. | Generate sample data in column A, apply both conditional formatting styles, and produce a PDF that displays the conditional colors correctly.
// Common Searches: Aspose.Cells .NET how to keep conditional formatting colors in PDF output | C# convert Excel to PDF with cell background colors based on value | Preserve conditional formatting when saving workbook as PDF using Aspose.Cells | Apply red background for values > 50 and green for < 20 in PDF conversion C# | Conditional formatting not appearing in PDF generated by Aspose.Cells
// Tags: conditional-formatting pdf export Aspose.Cells | cell-value based color rule .NET | excel to pdf conversion preserving formatting | red background for values greater than 50 Aspose.Cells | light green background for values less than 20 C#

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// The example loads or creates an Excel workbook, fills column A with incremental numbers, defines a conditional formatting range (A1:A20), adds two rules (red background with white font for values > 50 and light‑green background with black font for values < 20), recalculates formulas, and saves the workbook as a PDF where the conditional colors are rendered.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "Input.xlsx";
            const string outputPath = "Output.pdf";

            // Ensure the input file exists; create a simple workbook if it does not.
            Workbook workbook;
            if (File.Exists(inputPath))
            {
                workbook = new Workbook(inputPath);
            }
            else
            {
                workbook = new Workbook();
                Worksheet ws = workbook.Worksheets[0];
                // Populate sample data for demonstration.
                for (int i = 0; i < 20; i++)
                {
                    ws.Cells[i, 0].PutValue(i * 5); // Values: 0,5,10,...
                }
                workbook.Save(inputPath);
            }

            // Access the first worksheet.
            Worksheet sheet = workbook.Worksheets[0];

            // Define the range A1:A20 (zero‑based indices).
            int firstRow = 0;
            int firstColumn = 0;
            int totalRows = 20;
            int totalColumns = 1;
            CellArea area = new CellArea
            {
                StartRow = firstRow,
                StartColumn = firstColumn,
                EndRow = firstRow + totalRows - 1,
                EndColumn = firstColumn + totalColumns - 1
            };

            // Add a new conditional formatting collection for the defined range.
            int cfIndex = sheet.ConditionalFormattings.Add();
            FormatConditionCollection cfCollection = sheet.ConditionalFormattings[cfIndex];
            cfCollection.AddArea(area);

            // Condition: cells with value > 50.
            int condIndex = cfCollection.AddCondition(FormatConditionType.CellValue, OperatorType.GreaterThan, "50", null);
            FormatCondition condition = cfCollection[condIndex];
            Style style = workbook.CreateStyle();
            style.ForegroundColor = System.Drawing.Color.Red;
            style.Pattern = BackgroundType.Solid;
            style.Font.Color = System.Drawing.Color.White;
            condition.Style = style;

            // Additional condition: cells with value < 20.
            int condIndex2 = cfCollection.AddCondition(FormatConditionType.CellValue, OperatorType.LessThan, "20", null);
            FormatCondition condition2 = cfCollection[condIndex2];
            Style style2 = workbook.CreateStyle();
            style2.ForegroundColor = System.Drawing.Color.LightGreen;
            style2.Pattern = BackgroundType.Solid;
            style2.Font.Color = System.Drawing.Color.Black;
            condition2.Style = style2;

            // Recalculate formulas and apply conditional formatting.
            workbook.CalculateFormula();

            // Save the workbook as PDF; conditional formatting colors will be rendered.
            workbook.Save(outputPath, SaveFormat.Pdf);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
