using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

class Program
{
    static void Main()
    {
        // Create a new workbook and add some content
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].Value = "PDF protected with AES‑256 and user password";

        // Set AES‑256 encryption for the workbook (applies to PDF output as well)
        // EncryptionType.EnhancedCryptographicProviderV1 supports 256‑bit key length
        workbook.SetEncryptionOptions(EncryptionType.EnhancedCryptographicProviderV1, 256);

        // Configure PDF security: only a user password (no owner password)
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();
        PdfSecurityOptions securityOptions = new PdfSecurityOptions
        {
            UserPassword = "userPassword123"   // password required to open the PDF
            // OwnerPassword left null => no owner password set
        };
        pdfSaveOptions.SecurityOptions = securityOptions;

        // Save the workbook as a protected PDF
        workbook.Save("ProtectedAES256.pdf", pdfSaveOptions);

        Console.WriteLine("PDF created with AES‑256 encryption and user password protection.");
    }
}
// Author: Generated by Aspose.Cells expert – demonstrates AES‑256 PDF protection with only a user password.