// Title: Encrypt PDF with AES‑256 using only a user password in Aspose.Cells for .NET
// Description: Shows how to create a workbook, configure PdfSaveOptions with PdfSecurityOptions that contain only a UserPassword, and save the workbook as an AES‑256 encrypted PDF. The resulting file can be opened only with the supplied password, while the owner password is omitted.
// Keywords: Aspose.Cells PDF encryption | AES-256 PDF C# | user password only PDF | PdfSecurityOptions | protect PDF Aspose | C# PDF password protection | PdfSaveOptions security | Aspose.Cells PDF security
// Common Searches: Aspose.Cells set user password for PDF | AES‑256 PDF encryption C# Aspose.Cells | protect PDF with only a user password Aspose | PdfSecurityOptions example without owner password | how to encrypt PDF generated by Aspose.Cells
// Developer Intent: Apply AES‑256 encryption to a PDF generated by Aspose.Cells, requiring only a user password to open the document.
// Use Cases: Export confidential Excel reports to PDF that can be opened only with a shared password. | Automate batch conversion of workbooks to password‑protected PDFs in a web service. | Distribute legal documents where opening is restricted but default permissions are sufficient.
// AI Prompts: Provide C# code that saves an Aspose.Cells workbook as an AES‑256 encrypted PDF protected solely by a user password. | Show how to use PdfSecurityOptions in Aspose.Cells to set a user password while leaving the owner password unset. | Explain how to adjust PDF permissions when only a user password is defined in Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// Shows how to create a workbook, configure PdfSaveOptions with PdfSecurityOptions that contain only a UserPassword, and save the workbook as an AES‑256 encrypted PDF. The resulting file can be opened only with the supplied password, while the owner password is omitted.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].Value = "PDF protected with user password only";

        // Prepare PDF save options
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();

        // Configure security: set only the user password (owner password left null)
        PdfSecurityOptions securityOptions = new PdfSecurityOptions();
        securityOptions.UserPassword = "UserSecret123"; // password required to open the PDF
        // OwnerPassword is not set, so no owner password is required
        // Permissions can be left at defaults or customized as needed
        pdfSaveOptions.SecurityOptions = securityOptions;

        // Save the workbook as a PDF with the specified security settings
        workbook.Save("UserPasswordProtected.pdf", pdfSaveOptions);
    }
}
