// Title: Aspose.Cells C# – Compare MinimumSize vs Standard PDF Optimization
// Description: C# sample that creates a workbook with many cells, saves it twice as PDF (default Standard and MinimumSize), reads the file sizes and prints a verification that the MinimumSize PDF is smaller.
// Keywords: Aspose.Cells PDF MinimumSize | PdfSaveOptions OptimizationType | C# reduce PDF size Aspose | compare PDF file size Aspose.Cells | minimum size PDF Aspose .NET | Aspose.Cells PDF optimization US | Aspose.Cells PDF compression Europe
// Common Searches: Aspose.Cells MinimumSize PDF example | How to shrink PDF generated by Aspose.Cells | C# verify PDF size after optimization | PdfSaveOptions Standard vs MinimumSize | Aspose.Cells PDF size comparison code
// Developer Intent: Generate two PDFs with different optimization settings and programmatically confirm that the MinimumSize option produces a smaller file than the default Standard setting.
// Use Cases: Create lightweight PDFs for email attachments using MinimumSize optimization. | Produce high‑quality PDFs for printing with Standard optimization while measuring size impact. | Automate size validation in CI/CD pipelines to ensure MinimumSize PDFs are consistently smaller.
// AI Prompts: Add code to calculate and display the percentage reduction between Standard and MinimumSize PDFs. | Generate an xUnit test that asserts the MinimumSize PDF is at least 10 % smaller than the Standard PDF. | Explain how ImageCompression, FontEmbedding, and other PdfSaveOptions settings can further reduce PDF size.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfOptimizationDemo
{
    // C# sample that creates a workbook with many cells, saves it twice as PDF (default Standard and MinimumSize), reads the file sizes and prints a verification that the MinimumSize PDF is smaller.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add sample data to increase PDF size
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate the worksheet with a large amount of data
            for (int row = 0; row < 500; row++)
            {
                for (int col = 0; col < 20; col++)
                {
                    sheet.Cells[row, col].PutValue($"R{row}C{col}");
                }
            }

            // Define file names for the two PDF outputs
            string standardPdfPath = "StandardSize.pdf";
            string minimumPdfPath = "MinimumSize.pdf";

            // Save with default (Standard) optimization
            PdfSaveOptions standardOptions = new PdfSaveOptions(); // OptimizationType defaults to Standard
            workbook.Save(standardPdfPath, standardOptions);

            // Save with MinimumSize optimization
            PdfSaveOptions minimumOptions = new PdfSaveOptions();
            minimumOptions.OptimizationType = PdfOptimizationType.MinimumSize;
            workbook.Save(minimumPdfPath, minimumOptions);

            // Get file sizes
            long standardSize = new FileInfo(standardPdfPath).Length;
            long minimumSize = new FileInfo(minimumPdfPath).Length;

            // Output the sizes and verification result
            Console.WriteLine($"Standard optimization PDF size: {standardSize} bytes");
            Console.WriteLine($"MinimumSize optimization PDF size: {minimumSize} bytes");

            if (minimumSize < standardSize)
            {
                Console.WriteLine("Verification passed: MinimumSize PDF is smaller than StandardSize PDF.");
            }
            else
            {
                Console.WriteLine("Verification failed: MinimumSize PDF is not smaller than StandardSize PDF.");
            }
        }
    }
}
