// Title: Preserve Conditional Formatting Colors When Converting Excel to PDF with Aspose.Cells for .NET
// Description: Demonstrates how to add conditional formatting rules to an Excel worksheet, configure PdfSaveOptions (MergeAreas, CalculateFormula), and export the workbook so that background and font colors appear correctly in the resulting PDF.
// Keywords: Aspose.Cells | C# | conditional formatting | Excel to PDF conversion | preserve cell colors | PdfSaveOptions | MergeAreas | CalculateFormula | PDF export | cell styling
// Common Searches: Aspose.Cells keep conditional formatting in PDF | C# export Excel with colors to PDF | PdfSaveOptions MergeAreas example | How to render conditional formatting when saving as PDF | Aspose.Cells conditional formatting PDF conversion
// Developer Intent: Apply conditional formatting to worksheet cells and ensure the formatting is rendered in the PDF generated by Aspose.Cells for .NET.
// Use Cases: Create a PDF report that highlights values within a range using background colors. | Generate financial statements where high‑value cells are bolded and colored for quick visual analysis. | Produce invoices in PDF where amounts exceeding a threshold appear in green with white bold text.
// AI Prompts: Show C# code that adds multiple conditional formatting rules and exports the workbook to PDF with colors preserved using Aspose.Cells. | Explain how PdfSaveOptions.MergeAreas and CalculateFormula affect the rendering of conditional formatting in a PDF. | Provide a step‑by‑step guide to configure Aspose.Cells so that conditional formatting appears correctly after Excel‑to‑PDF conversion.

using System.Drawing;
using Aspose.Cells;

// Demonstrates how to add conditional formatting rules to an Excel worksheet, configure PdfSaveOptions (MergeAreas, CalculateFormula), and export the workbook so that background and font colors appear correctly in the resulting PDF.
class ConditionalFormattingPdfDemo
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate sample numeric data in column A
        worksheet.Cells["A1"].PutValue(10);
        worksheet.Cells["A2"].PutValue(30);
        worksheet.Cells["A3"].PutValue(60);
        worksheet.Cells["A4"].PutValue(90);

        // Add a conditional formatting collection to the worksheet
        int cfIndex = worksheet.ConditionalFormattings.Add();
        FormatConditionCollection cfCollection = worksheet.ConditionalFormattings[cfIndex];

        // Define the range A1:A4 for the conditional formatting
        CellArea area = new CellArea
        {
            StartRow = 0,
            EndRow = 3,
            StartColumn = 0,
            EndColumn = 0
        };
        cfCollection.AddArea(area);

        // Condition 1: values between 20 and 70 -> yellow background, black font
        int conditionIndex1 = cfCollection.AddCondition(
            FormatConditionType.CellValue,
            OperatorType.Between,
            "20",
            "70");
        FormatCondition condition1 = cfCollection[conditionIndex1];
        condition1.Style.BackgroundColor = Color.Yellow;
        condition1.Style.Font.Color = Color.Black;

        // Condition 2: values greater than 70 -> green background, white bold font
        int conditionIndex2 = cfCollection.AddCondition(
            FormatConditionType.CellValue,
            OperatorType.GreaterThan,
            "70",
            null);
        FormatCondition condition2 = cfCollection[conditionIndex2];
        condition2.Style.BackgroundColor = Color.Green;
        condition2.Style.Font.Color = Color.White;
        condition2.Style.Font.IsBold = true;

        // Prepare PDF save options; enable merging of conditional formatting before rendering
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            MergeAreas = true,
            CalculateFormula = true
        };

        // Save the workbook as PDF; conditional formatting colors will be reflected
        workbook.Save("ConditionalFormattingDemo.pdf", pdfOptions);
    }
}
