// Title: Encrypt PDF with User Password and Block Printing using Aspose.Cells PdfSaveOptions in C#
// Description: Shows how to create a workbook, configure PdfSaveOptions.SecurityOptions with a user password, an owner password, and disabled print permissions, then save the workbook as an encrypted PDF that cannot be printed.
// Keywords: Aspose.Cells PDF encryption C# | PdfSaveOptions security options | PdfSecurityOptions print permission false | user password PDF Aspose | disable PDF printing C# | owner password Aspose.Cells | high‑quality print restriction | encrypt PDF Aspose.Cells | C# PDF security Aspose
// Common Searches: Aspose.Cells set user password for PDF | disable printing in PDF generated by Aspose.Cells C# | how to encrypt PDF with Aspose.Cells | PdfSecurityOptions print permission false example | save workbook as encrypted PDF Aspose.Cells C#
// Developer Intent: Apply password protection and prevent printing when saving a workbook as a PDF with Aspose.Cells.
// Use Cases: Distribute confidential reports that require a password to open and cannot be printed. | Protect internal documents from unauthorized copying by disabling print functionality. | Meet regulatory compliance by delivering PDFs with both user and owner passwords and no printing rights.
// AI Prompts: Show how to also restrict text copying in the encrypted PDF using Aspose.Cells. | Provide code that enables form filling while keeping printing disabled and uses a custom owner password. | Explain how to apply the same security settings when saving the PDF to a MemoryStream instead of a file.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// Shows how to create a workbook, configure PdfSaveOptions.SecurityOptions with a user password, an owner password, and disabled print permissions, then save the workbook as an encrypted PDF that cannot be printed.
class PdfEncryptionDemo
{
    static void Main()
    {
        // Create a new workbook and add some content
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].Value = "Secure PDF with User Password";

        // Create PDF save options
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();

        // Configure security options
        PdfSecurityOptions securityOptions = new PdfSecurityOptions
        {
            // Password required to open the PDF
            UserPassword = "user123",
            // Owner password grants full access
            OwnerPassword = "owner123",
            // Disallow printing
            PrintPermission = false,
            // Ensure high‑quality printing is also disabled
            FullQualityPrintPermission = false
        };

        // Assign security options to the save options
        pdfSaveOptions.SecurityOptions = securityOptions;

        // Save the workbook as an encrypted PDF
        workbook.Save("EncryptedNoPrint.pdf", pdfSaveOptions);
    }
}
