// Title: Encrypt PDF with AES‑256, Owner & User Passwords using Aspose.Cells for .NET (C#)
// Description: Create a workbook, configure PdfSecurityOptions with owner and user passwords, enable printing, disable editing, attach the options to PdfSaveOptions, and save the file as an AES‑256 encrypted PDF.
// Keywords: Aspose.Cells PDF encryption | AES-256 PDF C# | PdfSecurityOptions | owner password PDF | user password PDF | C# PDF protection | PdfSaveOptions secure PDF | print permission PDF | disable edit PDF | Aspose.Cells secure export
// Common Searches: Aspose.Cells encrypt PDF AES-256 C# | Set owner and user passwords when saving PDF with Aspose.Cells | Enable print but block edit in PDF generated by Aspose.Cells | How to apply PDF security options in .NET using Aspose.Cells | Save workbook as password‑protected PDF with Aspose.Cells
// Developer Intent: Generate a PDF from a workbook and protect it with AES‑256 encryption, using distinct owner and user passwords and specific permissions.
// Use Cases: Distribute confidential reports that require a password to open while still allowing printing. | Provide read‑only PDFs for external partners where editing is blocked but printing is permitted. | Automate creation of regulatory‑compliant documents that must be encrypted and password‑protected.
// AI Prompts: Show how to add copy‑text permission to PdfSecurityOptions while keeping AES‑256 encryption. | Generate C# code to encrypt a PDF with a 128‑bit key instead of the default AES‑256 using Aspose.Cells. | Explain how to read existing PDF security settings (owner/user passwords, permissions) with Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// Create a workbook, configure PdfSecurityOptions with owner and user passwords, enable printing, disable editing, attach the options to PdfSaveOptions, and save the file as an AES‑256 encrypted PDF.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some content
        Workbook workbook = new Workbook();
        workbook.Worksheets[0].Cells["A1"].Value = "Secure PDF with AES‑256 encryption";

        // Set up PDF security options with owner and user passwords
        PdfSecurityOptions securityOptions = new PdfSecurityOptions
        {
            OwnerPassword = "ownerPassword123",   // full‑access password
            UserPassword = "userPassword123",     // password required to open the PDF
            PrintPermission = true,               // allow printing
            ModifyDocumentPermission = false      // disallow modifications
        };

        // Attach the security options to PDF save options
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions
        {
            SecurityOptions = securityOptions
        };

        // Save the workbook as a PDF; the PDF will be encrypted (AES‑256 by default)
        workbook.Save("SecureDocument.pdf", pdfSaveOptions);
    }
}
