// Title: C# – Minimize PDF size with MinimumSize optimization and font subsetting in Aspose.Cells
// Description: The sample builds a workbook, adds text, sets PdfSaveOptions to PdfOptimizationType.MinimumSize and turns on character‑level font subsetting (IsFontSubstitutionCharGranularity), then saves a compact PDF.
// Keywords: Aspose.Cells PDF compression | MinimumSize optimization .NET | font subsetting C# | PdfSaveOptions character granularity | reduce PDF file size Aspose | C# Aspose.Cells export PDF | PDF size reduction techniques
// Common Searches: Aspose.Cells set MinimumSize for PDF export | Enable font subsetting when saving workbook to PDF in C# | How to shrink PDF generated by Aspose.Cells | C# code for PDF size optimization Aspose.Cells | Character‑level font substitution Aspose.Cells PDF
// Developer Intent: Configure PdfSaveOptions to produce the smallest possible PDF by applying MinimumSize optimization and enabling per‑character font subsetting.
// Use Cases: Deliver lightweight PDF reports on web portals where bandwidth is limited. | Email invoices or statements as PDFs that stay under attachment size limits. | Archive large spreadsheets as PDFs while minimizing storage consumption.
// AI Prompts: Show how to set PdfSaveOptions in Aspose.Cells for MinimumSize optimization and character‑level font subsetting in C#. | Provide C# code that saves a workbook to PDF with font subsetting enabled and reports the resulting file size. | Explain the effect of PdfOptimizationType.MinimumSize and IsFontSubstitutionCharGranularity on PDF output quality and size.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// The sample builds a workbook, adds text, sets PdfSaveOptions to PdfOptimizationType.MinimumSize and turns on character‑level font subsetting (IsFontSubstitutionCharGranularity), then saves a compact PDF.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample text for PDF optimization with MinimumSize and font subsetting.");

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        // Optimize for minimum file size
        pdfOptions.OptimizationType = PdfOptimizationType.MinimumSize;
        // Enable font subsetting (character‑level font substitution)
        pdfOptions.IsFontSubstitutionCharGranularity = true;

        // Save the workbook as a PDF with the specified options
        workbook.Save("OptimizedFontSubset.pdf", pdfOptions);
    }
}
