using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsPdfEncryptionDemo
{
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Secure PDF generated by Aspose.Cells");

            // ---------- Workbook level encryption (Excel file) ----------
            // Set a strong password for the workbook file itself
            workbook.Settings.Password = "StrongPassword123!";

            // Apply strong encryption algorithm (256‑bit AES) to the workbook
            workbook.SetEncryptionOptions(EncryptionType.StrongCryptographicProvider, 256);

            // ---------- PDF level encryption ----------
            // Create PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Configure security options for the PDF
            PdfSecurityOptions pdfSecurity = new PdfSecurityOptions
            {
                // Owner password grants full permissions
                OwnerPassword = "StrongPassword123!",
                // User password is required to open the PDF
                UserPassword = "StrongPassword123!",
                // Allow printing but restrict other modifications
                PrintPermission = true,
                ModifyDocumentPermission = false,
                ExtractContentPermission = false,
                AnnotationsPermission = false,
                FillFormsPermission = false,
                FullQualityPrintPermission = true
            };

            // Assign the security options to the PDF save options
            pdfOptions.SecurityOptions = pdfSecurity;

            // Save the workbook as a password‑protected PDF
            workbook.Save("SecureOutput.pdf", pdfOptions);

            Console.WriteLine("PDF saved with strong password protection.");
        }
    }
}