// Title: C# – Limit PDF pages with Aspose.Cells using IPageSavingCallback (MaxPages check)
// Description: Demonstrates how to enforce a maximum page count when converting an Aspose.Cells workbook to PDF. A custom IPageSavingCallback records the total pages, stops pagination after the defined MaxPages, and prints verification data to confirm the limit was respected.
// Keywords: Aspose.Cells PDF page limit | C# IPageSavingCallback | max pages PDF Aspose | verify PDF page count | limit PDF pagination | Aspose.Cells PdfSaveOptions | page count callback
// Common Searches: limit number of pages when saving workbook to PDF Aspose.Cells | C# IPageSavingCallback stop PDF pagination after N pages | how to check total pages generated by Aspose.Cells PDF export | Aspose.Cells restrict PDF page count | C# verify PDF page count does not exceed max
// Developer Intent: Confirm that the PDF created from a workbook contains no more pages than the specified MaxPages value.
// Use Cases: Cap PDF size for large workbooks to meet file‑size or processing constraints. | Ensure exported PDFs comply with contractual or regulatory page limits. | Generate preview PDFs that include only the first few pages for faster delivery.
// AI Prompts: Write C# code using Aspose.Cells IPageSavingCallback to stop PDF generation after 10 pages and log the total page count. | Explain how to modify the PageCountCallback to throw an exception when the page limit is exceeded instead of silently stopping. | Show an alternative way to obtain the total number of pages after saving a PDF with Aspose.Cells without using a callback.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfPageCheck
{
    // Callback to monitor page saving and enforce a maximum page limit
    // Demonstrates how to enforce a maximum page count when converting an Aspose.Cells workbook to PDF. A custom IPageSavingCallback records the total pages, stops pagination after the defined MaxPages, and prints verification data to confirm the limit was respected.
    public class PageCountCallback : IPageSavingCallback
    {
        private readonly int _maxPages;
        public int SavedPages { get; private set; }
        public int TotalPages { get; private set; }

        public PageCountCallback(int maxPages)
        {
            _maxPages = maxPages;
        }

        // Called before a page is saved
        public void PageStartSaving(PageStartSavingArgs args)
        {
            // Capture the total number of pages that would be generated
            TotalPages = args.PageCount;
        }

        // Called after a page is saved
        public void PageEndSaving(PageEndSavingArgs args)
        {
            // Update the count of pages that have been saved so far
            SavedPages = args.PageIndex + 1;

            // If the saved page count reaches the maximum, stop further pagination
            if (SavedPages >= _maxPages)
            {
                args.HasMorePages = false;
            }
        }
    }

    class Program
    {
        static void Main()
        {
            // Define the maximum number of pages allowed in the PDF
            const int maxPages = 5;

            // Create a new workbook and populate it with enough data to span multiple pages
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            for (int i = 0; i < 500; i++)
            {
                sheet.Cells[i, 0].Value = $"Row {i + 1}";
            }

            // Configure PDF save options with the page limit and the custom callback
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                PageIndex = 0,               // Start from the first page
                PageCount = maxPages,        // Request up to maxPages (optional, reinforces limit)
                PageSavingCallback = new PageCountCallback(maxPages)
            };

            // Save the workbook to PDF using the configured options
            string pdfPath = "LimitedPagesOutput.pdf";
            workbook.Save(pdfPath, pdfOptions);

            // Retrieve the callback instance to examine the results
            var callback = (PageCountCallback)pdfOptions.PageSavingCallback;

            // Output verification information
            Console.WriteLine($"Total pages generated by workbook: {callback.TotalPages}");
            Console.WriteLine($"Maximum pages allowed (MaxPages): {maxPages}");
            Console.WriteLine($"Pages actually saved to PDF: {callback.SavedPages}");

            // Confirm that the saved page count does not exceed the limit
            if (callback.SavedPages <= maxPages)
            {
                Console.WriteLine("PDF page count is within the expected limit.");
            }
            else
            {
                Console.WriteLine("PDF page count exceeds the expected limit.");
            }
        }
    }
}
