// Title: Set 300 DPI chart image quality when saving Excel to PDF with Aspose.Cells for .NET
// Description: Learn how to export an Excel workbook to PDF with crystal‑clear charts by using Aspose.Cells' PdfSaveOptions.SetImageResample(300, 100). The C# example creates a column chart, configures the image resample to 300 PPI and 100 % JPEG quality, and saves a high‑resolution PDF suitable for printing and high‑DPI displays.
// Keywords: Aspose.Cells | PdfSaveOptions | SetImageResample | high resolution PDF | 300 DPI | chart image quality | C# Excel to PDF | Aspose.Cells chart export | JPEG quality 100 | Excel chart PDF conversion
// Common Searches: Aspose.Cells export chart to PDF 300 DPI | SetImageResample high quality PDF Aspose | C# save Excel workbook as high‑resolution PDF | Increase chart resolution in PDF using Aspose.Cells | Configure JPEG quality for PDF export Aspose
// Developer Intent: Configure PDF export so Excel charts are rendered at 300 PPI with maximum JPEG quality.
// Use Cases: Produce printable sales reports where column charts remain sharp on professional printers. | Generate client‑facing PDFs with multiple charts that look crisp on Retina and 4K displays. | Automate batch conversion of Excel files to PDFs while preserving chart clarity for archival records.
// AI Prompts: Show C# code that sets PdfSaveOptions.SetImageResample to 300 DPI and JPEG quality 100% for chart export with Aspose.Cells. | Explain how the SetImageResample parameters affect chart rendering quality in a PDF generated by Aspose.Cells. | Provide a step‑by‑step guide to create a chart in an Excel workbook and save it as a high‑resolution PDF using Aspose.Cells for .NET.

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Learn how to export an Excel workbook to PDF with crystal‑clear charts by using Aspose.Cells' PdfSaveOptions.SetImageResample(300, 100). The C# example creates a column chart, configures the image resample to 300 PPI and 100 % JPEG quality, and saves a high‑resolution PDF suitable for printing and high‑DPI displays.
class HighResolutionChartPdf
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate sample data for the chart
        worksheet.Cells["A1"].PutValue("Category");
        worksheet.Cells["A2"].PutValue("Apple");
        worksheet.Cells["A3"].PutValue("Banana");
        worksheet.Cells["A4"].PutValue("Cherry");
        worksheet.Cells["B1"].PutValue("Value");
        worksheet.Cells["B2"].PutValue(120);
        worksheet.Cells["B3"].PutValue(80);
        worksheet.Cells["B4"].PutValue(150);

        // Add a column chart and bind it to the data range
        int chartIndex = worksheet.Charts.Add(ChartType.Column, 5, 0, 20, 8);
        Chart chart = worksheet.Charts[chartIndex];
        chart.NSeries.Add("B2:B4", true);
        chart.NSeries.CategoryData = "A2:A4";
        chart.Title.Text = "Fruit Sales";

        // Configure PDF save options for high‑resolution image quality
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        // Desired PPI = 300 (high quality), JPEG quality = 100%
        pdfOptions.SetImageResample(300, 100);

        // Save the workbook as PDF; the chart will be rendered using the high‑resolution settings
        workbook.Save("HighResolutionChart.pdf", pdfOptions);
    }
}
