// Title: Render Solid (Hair) Gridlines in PDF with Aspose.Cells for .NET
// Description: Shows how to enable worksheet gridlines, activate PrintGridlines, set PdfSaveOptions.GridlineType to Hair and specify a color, then save the workbook so the resulting PDF displays solid black gridlines.
// Keywords: Aspose.Cells PDF export | solid gridlines | Hair gridline type | PrintGridlines | PdfSaveOptions | C# Excel to PDF | gridline color | .NET spreadsheet rendering | Aspose.Cells documentation
// Common Searches: Aspose.Cells render solid gridlines in PDF | PDF export with hair‑type gridlines using Aspose.Cells | Why gridlines disappear when saving Excel as PDF | Set gridline color for PDF output in Aspose.Cells .NET | Enable PrintGridlines for PDF generation
// Developer Intent: Confirm that the PDF generated by Aspose.Cells contains solid (hair) gridlines as configured in the save options.
// Use Cases: Create printable reports where Excel gridlines must appear as clear solid lines. | Generate invoices or forms that rely on visible cell borders for readability. | Automated testing of PDF output to ensure gridline styling matches design specifications.
// AI Prompts: Write a unit test that opens the saved PDF and verifies the presence of solid black gridlines. | Provide code for Aspose.Cells 23.10+ that uses the RenderGridlines property to achieve the same result. | Explain how to switch from Hair to Dotted gridlines and change the color while keeping them visible in the PDF.

using System;
using System.Drawing;
using Aspose.Cells;

// Shows how to enable worksheet gridlines, activate PrintGridlines, set PdfSaveOptions.GridlineType to Hair and specify a color, then save the workbook so the resulting PDF displays solid black gridlines.
class RenderSolidGridlinesDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some data so gridlines are visible
            sheet.Cells["A1"].PutValue("Header");
            sheet.Cells["A2"].PutValue("Row 1");
            sheet.Cells["B2"].PutValue(123);
            sheet.Cells["A3"].PutValue("Row 2");
            sheet.Cells["B3"].PutValue(456);

            // Ensure gridlines are visible in the worksheet and printed
            sheet.IsGridlinesVisible = true;
            sheet.PageSetup.PrintGridlines = true;

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Set the gridline type to Hair (solid line)
                GridlineType = GridlineType.Hair,
                // Optional: set a specific gridline color
                GridlineColor = Color.Black
                // Note: RenderGridlines property is not available in this version;
                // gridlines will be rendered because PrintGridlines is enabled.
            };

            // Save the workbook as PDF; solid gridlines should appear
            string outputPath = "SolidGridlinesDemo.pdf";
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"PDF saved with solid gridlines at '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}
