// Title: How to stop Aspose.Cells from creating a blank PDF page when saving an empty workbook using PdfSaveOptions in C#
// AI Prompts: Generate C# code that configures PdfSaveOptions so Aspose.Cells does not add a blank page when exporting an empty workbook to PDF. | Explain the steps to prevent Aspose.Cells from inserting a default first page in a PDF when the workbook contains no printable content. | Show how to use Aspose.Cells PDF export settings to omit pages with no data in a C# application.
// Common Searches: Aspose.Cells C# export empty workbook to PDF without extra page | PdfSaveOptions avoid blank page when workbook has no data | How to disable automatic first page in PDF generated by Aspose.Cells | C# Aspose.Cells PDF export blank page issue solution
// Tags: Aspose.Cells PDFSaveOptions disable blank page | C# export empty workbook to PDF Aspose.Cells | prevent empty page generation Aspose.Cells PDF | Aspose.Cells PDF export without default page | PdfSaveOptions configuration for empty content

using Aspose.Cells;
using Aspose.Cells.Rendering;
using System;
using System.IO;

// The sample creates an empty Workbook, sets up PdfSaveOptions, ensures the output directory exists, and saves the workbook to PDF, illustrating how to prevent Aspose.Cells from adding a blank page when the workbook has no printable content.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new (empty) workbook
            Workbook workbook = new Workbook();

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();
            // The DisablePageBreaks property is not available in this version of Aspose.Cells.
            // Additional PDF options can be set here if required.

            string outputPath = "output.pdf";

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook to PDF using the configured options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF saved successfully to {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
