// Title: Set high‑resolution chart images when converting an Excel workbook to PDF with Aspose.Cells for .NET
// AI Prompts: Write C# code that checks whether PdfSaveOptions.ImageResolution is supported and, if so, sets it to 300 DPI to improve chart image quality during PDF export. | Show how to detect the Aspose.Cells version at runtime and gracefully fall back when the ImageResolution property is unavailable, preserving default DPI handling. | Provide a complete example that loads an .xlsx file, configures PdfSaveOptions for high‑resolution chart rendering, ensures the output directory exists, and saves the workbook as a PDF.
// Common Searches: how to increase chart DPI in PDF generated by Aspose.Cells .NET | Aspose.Cells PdfSaveOptions ImageResolution property not found | set high resolution images for Excel charts when exporting to PDF using C# | fallback code for missing ImageResolution in older Aspose.Cells versions | best practice for preserving chart quality in PDF conversion with Aspose.Cells
// Tags: Aspose.Cells PdfSaveOptions image resolution | high‑resolution chart export PDF .NET | Excel to PDF chart DPI setting | version check Aspose.Cells ImageResolution | C# workbook save PDF with chart quality

using Aspose.Cells;
using System;
using System.IO;

// The example loads an Excel workbook, creates PdfSaveOptions (noting that the ImageResolution property may be unavailable in some Aspose.Cells versions), ensures the output folder exists, and saves the workbook as a PDF while handling exceptions and providing guidance for high‑resolution chart rendering.
class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the Excel workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();
            // Note: ImageResolution property is not available in this version.
            // Default image DPI will be used. Adjust the property here if supported by your Aspose.Cells version.

            // Ensure the output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as PDF
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
