// Title: Convert a CSV file to PDF with Aspose.Cells for .NET and assign a custom creation date
// AI Prompts: Write C# code that loads a CSV file into an Aspose.Cells Workbook and saves it as a PDF while setting the PDF's CreationDate to a specific past date. | Show how to configure PdfSaveOptions.PdfDocumentInfo in Aspose.Cells to embed custom metadata such as a creation timestamp. | Add robust error handling for missing CSV input files when performing the conversion to PDF.
// Common Searches: asp.net convert csv to pdf with aspose.cells and set creation date | c# how to set pdf creation timestamp using aspose.cells pdfsaveoptions | load csv workbook and export to pdf preserving custom metadata in .net | example of setting historical creation date on pdf generated by aspose.cells | error handling file not found during csv to pdf conversion aspose.cells
// Tags: csv to pdf conversion Aspose.Cells | Aspose.Cells PdfSaveOptions creation date | C# load CSV workbook Aspose.Cells | set PDF metadata Aspose.Cells | file not found handling Aspose.Cells | custom PDF document info Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example checks for the presence of a CSV file, loads it into an Aspose.Cells Workbook using CSV load options, configures PdfSaveOptions (including optional PdfDocumentInfo to set a historical CreationDate), and saves the workbook as a PDF, with error handling for missing input files.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.csv";
            const string outputPath = "output.pdf";

            // Verify that the input CSV file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                return;
            }

            // Load the CSV file into a workbook
            var loadOptions = new LoadOptions(LoadFormat.Csv);
            var workbook = new Workbook(inputPath, loadOptions);

            // Configure PDF save options (metadata setting removed as PdfDocumentInfo is not available)
            var pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Handle any unexpected errors
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
