// Title: C# – Convert TSV to PDF/A‑2b with Aspose.Cells
// Description: Loads a tab‑separated values (TSV) file into an Aspose.Cells Workbook, configures PdfSaveOptions.Compliance to PdfA2b, and saves the workbook as an archival PDF/A‑2b document. Includes checks for missing files and exception handling.
// Keywords: Aspose.Cells | C# | TSV to PDF conversion | PDF/A-2b | PdfSaveOptions | archival PDF | PDF compliance | Aspose.Cells example | working with PDF
// Common Searches: Aspose.Cells convert TSV to PDF | PDF/A-2b export C# Aspose.Cells | set PDF/A-2b compliance in Aspose.Cells | save workbook as PDF/A-2b | C# code for TSV to PDF/A-2b
// Developer Intent: Create an archival PDF/A‑2b file from a TSV document using Aspose.Cells for .NET.
// Use Cases: Long‑term preservation of spreadsheet data exported as TSV. | Automated batch generation of PDF/A‑2b reports from TSV sources. | Integrating TSV‑to‑PDF/A‑2b conversion into document management workflows. | Graceful handling of missing input files during conversion.
// AI Prompts: Write C# code that reads a TSV file with Aspose.Cells and saves it as a PDF/A‑2b document, including error handling. | Show how to configure PdfSaveOptions for PDF/A‑2b compliance when converting delimited text files using Aspose.Cells. | Explain how to verify that the PDF generated by Aspose.Cells meets PDF/A‑2b standards.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExamples
{
    // Loads a tab‑separated values (TSV) file into an Aspose.Cells Workbook, configures PdfSaveOptions.Compliance to PdfA2b, and saves the workbook as an archival PDF/A‑2b document. Includes checks for missing files and exception handling.
    public class TsvToPdfA2b
    {
        public static void Run()
        {
            // Path to the source TSV file
            string sourcePath = "input.tsv";

            // Path for the resulting PDF file
            string outputPath = "output.pdf";

            // Verify that the source file exists
            if (!File.Exists(sourcePath))
            {
                Console.WriteLine($"Error: Source file '{sourcePath}' not found.");
                return;
            }

            try
            {
                // Load the TSV document into a workbook.
                // The Workbook constructor automatically detects the format from the file extension.
                Workbook workbook = new Workbook(sourcePath);

                // Create PDF save options and set the compliance level to PDF/A‑2b.
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    Compliance = PdfCompliance.PdfA2b
                };

                // Save the workbook as a PDF with the specified compliance.
                workbook.Save(outputPath, pdfOptions);

                Console.WriteLine($"TSV file '{sourcePath}' has been converted to PDF/A‑2b at '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during conversion: {ex.Message}");
            }
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            TsvToPdfA2b.Run();
        }
    }
}
