// Title: Convert a CSV file to PDF in C# with Aspose.Cells while preserving column alignment
// AI Prompts: Write C# code that loads a CSV using Aspose.Cells LoadOptions, auto‑fits all worksheet columns, and saves the workbook as a PDF. | Demonstrate how to keep the original CSV column widths when exporting to PDF with Aspose.Cells in a .NET application.
// Common Searches: asp.net convert csv to pdf with aspose.cells preserving column widths | c# aspose.cells auto fit columns before pdf export example | how to maintain csv column alignment in pdf generated by aspose.cells | load csv using LoadOptions and save as pdf aspose.cells tutorial | aspose.cells pdf output column alignment issue and fix
// Tags: convert csv to pdf Aspose.Cells | auto‑fit worksheet columns Aspose.Cells | preserve column alignment PDF Aspose.Cells | load csv with LoadOptions Aspose.Cells | save workbook as pdf C# Aspose.Cells | Aspose.Cells column width handling

using Aspose.Cells;
using System;

// The example loads a CSV file into an Aspose.Cells Workbook using LoadOptions, auto‑fits the worksheet columns to match the source layout, and then saves the workbook as a PDF, ensuring the PDF column alignment mirrors the original CSV.
class Program
{
    static void Main()
    {
        // Load the CSV file into a workbook
        LoadOptions loadOptions = new LoadOptions(LoadFormat.Csv);
        Workbook workbook = new Workbook("input.csv", loadOptions);

        // Auto‑fit columns so the PDF layout matches the CSV alignment
        Worksheet sheet = workbook.Worksheets[0];
        sheet.AutoFitColumns();

        // Save the workbook as a PDF document
        workbook.Save("output.pdf", SaveFormat.Pdf);
    }
}
