// Title: Convert XLSX to PDF with Aspose.Cells for .NET (C#) and Verify File Size
// Description: A concise C# example that checks for an existing .xlsx file, creates a simple workbook when missing, converts the workbook to PDF using Aspose.Cells default settings, and logs the generated PDF's byte size for validation.
// Keywords: Aspose.Cells | C# PDF conversion | XLSX to PDF | SaveFormat.Pdf | default conversion settings | PDF file size verification | create sample workbook | .NET Excel to PDF
// Common Searches: Aspose.Cells convert Excel to PDF C# example | How to get PDF size after Aspose.Cells conversion | Create Excel file if not found before PDF conversion Aspose | Default PDF export with Aspose.Cells for .NET | C# code to save workbook as PDF and check file length
// Developer Intent: Generate a PDF from an Excel workbook with Aspose.Cells using default options and confirm the output size programmatically.
// Use Cases: Automatically generate a placeholder Excel file when the source is absent, then convert it to PDF. | Perform quick PDF export of any .xlsx document without custom conversion parameters. | Log or compare the byte size of the resulting PDF for quality checks or downstream processing.
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, creates a sample workbook if the file is missing, saves it as a PDF using default settings, and prints the PDF's byte size. | Provide an Aspose.Cells for .NET snippet that demonstrates default PDF conversion and includes a file‑size verification step. | Explain how to retrieve the size of a PDF generated by Aspose.Cells and how to adjust conversion options after the default export.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsConversionDemo
{
    // A concise C# example that checks for an existing .xlsx file, creates a simple workbook when missing, converts the workbook to PDF using Aspose.Cells default settings, and logs the generated PDF's byte size for validation.
    class Program
    {
        static void Main()
        {
            // Define source Excel file and destination PDF file paths
            string sourcePath = "sample.xlsx";
            string destPath = "sample.pdf";

            // If the source Excel file does not exist, create a simple workbook for demonstration
            if (!File.Exists(sourcePath))
            {
                Workbook tempWorkbook = new Workbook(); // Workbook() constructor
                Worksheet sheet = tempWorkbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Hello, Aspose.Cells!");
                sheet.Cells["A2"].PutValue("This workbook will be converted to PDF.");
                tempWorkbook.Save(sourcePath, SaveFormat.Xlsx); // Save as XLSX
                Console.WriteLine($"Created sample Excel file: {sourcePath}");
            }

            // Load the existing workbook from the file
            Workbook workbook = new Workbook(sourcePath); // Workbook(string) constructor

            // Save the workbook to PDF using default settings
            workbook.Save(destPath, SaveFormat.Pdf); // Save(string, SaveFormat) method

            // Verify the output PDF file size
            FileInfo pdfInfo = new FileInfo(destPath);
            Console.WriteLine($"PDF conversion completed. File size: {pdfInfo.Length} bytes");
        }
    }
}
