using System;
using Aspose.Cells;
using Aspose.Cells.Saving;

class Program
{
    static void Main()
    {
        // Load the TSV file into a workbook
        LoadOptions loadOptions = new LoadOptions(LoadFormat.Tsv);
        Workbook workbook = new Workbook("input.tsv", loadOptions);

        // Apply custom page margins (values are in inches)
        Worksheet sheet = workbook.Worksheets[0];
        sheet.PageSetup.LeftMargin = 0.5;    // left margin
        sheet.PageSetup.RightMargin = 0.5;   // right margin
        sheet.PageSetup.TopMargin = 0.75;    // top margin
        sheet.PageSetup.BottomMargin = 0.75; // bottom margin

        // Save the workbook as PDF
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        workbook.Save("output.pdf", pdfOptions);
    }
}
// Author: Generated by Aspose.Cells .NET example for TSV‑to‑PDF conversion with custom margins.