// Title: Convert an Excel workbook with sparklines to PDF (inline graphics) using Aspose.Cells for .NET
// Description: Loads an XLSX file that contains sparkline groups, optionally logs each worksheet's sparkline count, and saves the workbook as a PDF. Aspose.Cells automatically renders sparklines as inline graphics in the PDF, with basic file‑existence checks and exception handling.
// Keywords: Aspose.Cells sparkline PDF conversion | Excel sparklines to PDF .NET | inline sparkline graphics PDF | save workbook as PDF Aspose | render sparklines in PDF automatically
// Common Searches: export Excel file with sparklines to PDF using Aspose.Cells | sparklines missing in PDF generated by Aspose.Cells | C# code to convert workbook with sparklines to PDF | Aspose.Cells PDF output includes sparkline images | how to preserve sparklines when saving Excel as PDF
// Developer Intent: Create a PDF from an Excel workbook that contains sparklines, ensuring the sparklines appear as embedded images.
// Use Cases: Convert a pre‑populated .xlsx file that uses sparkline groups into a PDF for reporting. | Log the number of sparkline groups per worksheet before conversion to aid debugging. | Validate input file existence and handle runtime errors during Excel‑to‑PDF conversion.
// AI Prompts: Generate C# code with Aspose.Cells that converts an Excel workbook containing sparklines to a PDF, confirming inline rendering. | Explain why Aspose.Cells renders sparklines as inline graphics when saving to PDF and whether any settings affect this behavior. | Suggest customization options for sparkline appearance in the resulting PDF using Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsSparklinePdfDemo
{
    // Loads an XLSX file that contains sparkline groups, optionally logs each worksheet's sparkline count, and saves the workbook as a PDF. Aspose.Cells automatically renders sparklines as inline graphics in the PDF, with basic file‑existence checks and exception handling.
    class Program
    {
        static void Main()
        {
            // Path to the source workbook that already contains sparklines
            string inputPath = "input_with_sparklines.xlsx";

            // Verify that the input file exists before attempting to load it
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            try
            {
                // Load the workbook
                Workbook workbook = new Workbook(inputPath);

                // Optional: verify that sparkline groups exist
                foreach (Worksheet sheet in workbook.Worksheets)
                {
                    if (sheet.SparklineGroups.Count > 0)
                    {
                        Console.WriteLine($"Worksheet '{sheet.Name}' contains {sheet.SparklineGroups.Count} sparkline group(s).");
                    }
                }

                // Save the workbook as PDF.
                // Aspose.Cells renders sparklines as inline graphics in the PDF automatically.
                string outputPath = "output_sparklines.pdf";
                workbook.Save(outputPath, SaveFormat.Pdf);

                Console.WriteLine($"Workbook saved to PDF with inline sparklines at: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
