// Title: Convert an Excel workbook containing sparklines to PDF with inline graphics using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file with sparklines and saves it as a PDF, ensuring the sparklines are rendered as inline images using Aspose.Cells. | Show how to configure PdfSaveOptions in Aspose.Cells so that sparklines appear as graphics when exporting an Excel workbook to PDF.
// Common Searches: Aspose.Cells C# export Excel file with sparklines to PDF preserving graphics | How to keep sparklines visible as images in PDF generated by Aspose.Cells | PdfSaveOptions settings for rendering sparklines in PDF using Aspose.Cells .NET | Convert workbook with sparklines to PDF inline graphics Aspose.Cells example | C# code to save Excel workbook containing sparklines as PDF with Aspose
// Tags: Aspose.Cells PDFSaveOptions sparklines | C# convert sparklines to PDF graphics | inline graphic rendering PDF Aspose.Cells | Excel workbook to PDF with sparklines | preserve sparklines images Aspose.Cells

using Aspose.Cells;
using Aspose.Cells.Rendering;
using System;
using System.IO;

// Loads an Excel workbook that includes sparklines, applies Aspose.Cells PdfSaveOptions (default behavior) to render sparklines as inline graphics, and saves the workbook as a PDF file.
class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook that contains sparklines
            Workbook workbook = new Workbook(inputPath);

            // Configure PDF save options (default settings render sparklines as graphics)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF with the specified options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF successfully saved to: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
