// Title: C# – Convert TSV Workbook to PDF with One Page per Sheet and No Blank Pages using Aspose.Cells
// Description: Load a TSV file into an Aspose.Cells Workbook, configure PdfSaveOptions (OnePagePerSheet = true, PrintingPageType = IgnoreBlank, OutputBlankPageWhenNothingToPrint = false) and save as PDF, guaranteeing a single page for each worksheet while suppressing empty pages.
// Keywords: Aspose.Cells TSV to PDF | C# PDFSaveOptions OnePagePerSheet | ignore blank pages Aspose.Cells | OutputBlankPageWhenNothingToPrint | convert TSV file to PDF .NET | Aspose.Cells export multi‑sheet PDF | skip empty worksheets PDF
// Common Searches: Aspose.Cells convert TSV to PDF C# | PDF export one page per sheet Aspose.Cells | how to ignore blank pages when saving PDF with Aspose.Cells | remove empty pages from PDF generated by Aspose.Cells | C# Aspose.Cells PDFSaveOptions examples
// Developer Intent: Create a PDF from a TSV workbook where each worksheet is rendered on a single page and no blank or empty pages are generated.
// Use Cases: Generate a clean PDF report from a multi‑sheet TSV source for client distribution. | Automate batch conversion of TSV files to PDFs while preserving sheet boundaries and eliminating blank pages. | Integrate TSV‑to‑PDF conversion into a .NET backend service that produces printable documents on demand.
// AI Prompts: Write C# code that loads a TSV file with Aspose.Cells and saves it as a PDF using OnePagePerSheet and blank‑page suppression options. | Explain the effect of OnePagePerSheet, PrintingPageType = IgnoreBlank, and OutputBlankPageWhenNothingToPrint on PDF output in Aspose.Cells. | Provide a step‑by‑step guide to batch‑process multiple TSV files into PDFs, ensuring each sheet gets its own page and empty pages are omitted.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsTsvToPdf
{
    // Load a TSV file into an Aspose.Cells Workbook, configure PdfSaveOptions (OnePagePerSheet = true, PrintingPageType = IgnoreBlank, OutputBlankPageWhenNothingToPrint = false) and save as PDF, guaranteeing a single page for each worksheet while suppressing empty pages.
    class Program
    {
        static void Main()
        {
            // Load the TSV file into a workbook.
            // Aspose.Cells can infer the format from the file extension.
            Workbook workbook = new Workbook("input.tsv");

            // Configure PDF save options:
            // - OnePagePerSheet ensures each sheet is rendered on a single page.
            // - PrintingPageType.IgnoreBlank skips completely blank pages.
            // - OutputBlankPageWhenNothingToPrint = false prevents a blank page when a sheet has no printable content.
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                OnePagePerSheet = true,
                PrintingPageType = PrintingPageType.IgnoreBlank,
                OutputBlankPageWhenNothingToPrint = false
            };

            // Save the workbook as PDF.
            workbook.Save("output.pdf", pdfOptions);
        }
    }
}
