// Title: Convert CSV to PDF with Aspose.Cells C# and set a custom CreatedTime
// Description: C# example that loads a CSV file using Aspose.Cells LoadOptions, configures PdfSaveOptions.CreatedTime to a historic date, and converts the CSV to PDF with ConversionUtility while preserving the specified creation timestamp.
// Keywords: Aspose.Cells | C# CSV to PDF | PdfSaveOptions CreatedTime | set PDF creation date | ConversionUtility | PDF metadata Aspose | load CSV Aspose.Cells
// Common Searches: Aspose.Cells set PDF CreatedTime C# | convert CSV file to PDF with custom timestamp | how to change PDF creation date using Aspose.Cells | C# example for CSV to PDF conversion Aspose | PDF metadata custom date Aspose.Cells
// Developer Intent: The developer needs to transform a CSV document into a PDF and embed a specific historical creation date in the PDF metadata using Aspose.Cells.
// Use Cases: Archiving legacy CSV reports as PDFs with a fixed creation date for compliance. | Batch converting daily CSV exports to PDFs while keeping metadata uniform across all files. | Generating version‑controlled documentation where the PDF timestamp must reflect a predetermined release date.
// AI Prompts: Show how to also set the ModifiedTime property in PdfSaveOptions while converting CSV to PDF. | Provide code to process a folder of CSV files, convert each to PDF, and apply the same historical CreatedTime. | Explain how to read the CreatedTime value from a PDF generated by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Utility;

namespace CsvToPdfExample
{
    // C# example that loads a CSV file using Aspose.Cells LoadOptions, configures PdfSaveOptions.CreatedTime to a historic date, and converts the CSV to PDF with ConversionUtility while preserving the specified creation timestamp.
    class Program
    {
        static void Main()
        {
            // Path to the source CSV file
            string csvPath = "input.csv";

            // Path for the output PDF file
            string pdfPath = "output.pdf";

            // Create load options for CSV format
            LoadOptions loadOptions = new LoadOptions(LoadFormat.Csv);

            // Create PDF save options and set a specific creation time
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Example historical date: January 1, 2000 at 00:00:00
                CreatedTime = new DateTime(2000, 1, 1, 0, 0, 0)
            };

            // Convert CSV to PDF using the utility method with load and save options
            ConversionUtility.Convert(csvPath, loadOptions, pdfPath, pdfOptions);

            Console.WriteLine($"CSV file '{csvPath}' has been converted to PDF '{pdfPath}' with CreatedTime set to {pdfOptions.CreatedTime}.");
        }
    }
}
