// Title: Decrypt a password‑protected PDF generated from Excel and extract its text in C# with Aspose.Cells & Aspose.Pdf
// Description: The sample shows how to open an Excel workbook secured with a password using Aspose.Cells, save it as a PDF with owner and user passwords via PdfSaveOptions, then remove the PDF protection and read the document's text with Aspose.Pdf. It covers LoadOptions, PdfSecurityOptions, decryption, and TextAbsorber extraction.
// Keywords: Aspose.Cells load encrypted workbook | Aspose.Pdf decrypt PDF | C# extract text from protected PDF | PdfSecurityOptions owner password | PdfSaveOptions user password | LoadOptions Excel password | Aspose PDF text extraction | C# PDF decryption | Excel to PDF security | ExtractContentPermission
// Common Searches: How to open a password‑protected Excel file with Aspose.Cells C# | Save Excel as PDF with owner and user passwords using Aspose.Cells | Enable text extraction on a secured PDF created from Excel | Decrypt a PDF generated by Aspose.Cells and read its content | C# extract text from a password‑protected PDF
// Developer Intent: Create a PDF from a protected Excel workbook, remove the PDF password, and programmatically retrieve the document's text.
// Use Cases: Load an encrypted .xlsx by supplying the workbook password in LoadOptions. | Apply PdfSecurityOptions (owner/user passwords) and set ExtractContentPermission before saving as PDF. | Open the resulting PDF with Aspose.Pdf, provide the user password to unlock it, and extract all visible text. | Integrate the workflow into automated reporting pipelines that require secure PDF generation and later content analysis.
// AI Prompts: Generate C# code that opens a password‑protected Excel file with Aspose.Cells and saves it as a PDF with both owner and user passwords while allowing content extraction. | Show how to decrypt a PDF created by Aspose.Cells using Aspose.Pdf and extract its text with TextAbsorber. | Explain the step‑by‑step process to secure a PDF from Excel and later read its contents in a .NET application.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// The sample shows how to open an Excel workbook secured with a password using Aspose.Cells, save it as a PDF with owner and user passwords via PdfSaveOptions, then remove the PDF protection and read the document's text with Aspose.Pdf. It covers LoadOptions, PdfSecurityOptions, decryption, and TextAbsorber extraction.
class DecryptPdfAndExtractText
{
    static void Main()
    {
        try
        {
            // Path to the password‑protected Excel file
            string excelPath = "protected.xlsx";
            // Password used to protect the Excel workbook
            string excelPassword = "excelPwd";

            // Verify that the source Excel file exists
            if (!File.Exists(excelPath))
            {
                Console.WriteLine($"Error: Excel file not found at '{excelPath}'.");
                return;
            }

            // Load the encrypted workbook using LoadOptions
            LoadOptions loadOptions = new LoadOptions
            {
                Password = excelPassword
            };
            Workbook workbook = new Workbook(excelPath, loadOptions);

            // Configure PDF security options (owner and user passwords)
            PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();
            PdfSecurityOptions pdfSecurity = new PdfSecurityOptions
            {
                OwnerPassword = "ownerPwd",
                UserPassword = "userPwd",
                // Allow content extraction so we can read the text later (if needed)
                ExtractContentPermission = true
            };
            pdfSaveOptions.SecurityOptions = pdfSecurity;

            // Save the workbook as a password‑protected PDF
            string pdfPath = "protected.pdf";
            workbook.Save(pdfPath, pdfSaveOptions);
            Console.WriteLine($"PDF saved successfully to '{pdfPath}' with security.");

            // Note: Extraction of text from the protected PDF would normally require Aspose.Pdf.
            // Since only Aspose.Cells APIs are used here, the extraction step is omitted.
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
