// Title: Hide Gridlines When Converting XLSM to PDF with Aspose.Cells for .NET (C#)
// Description: Loads an XLSM workbook, turns off both visible and printable gridlines on the target worksheet, configures PdfSaveOptions to use a hair‑type gridline and a transparent color, and saves the file as a PDF. The resulting PDF contains no solid gridlines.
// Keywords: Aspose.Cells | C# | PDF conversion | gridlines | hide gridlines | disable gridlines | PdfSaveOptions | GridlineType.Hair | transparent gridlines | XLSM to PDF | .NET | worksheet gridlines | PrintGridlines false
// Common Searches: How to hide gridlines in PDF using Aspose.Cells C# | Aspose.Cells remove gridlines from PDF export | Disable solid gridlines when converting XLSM to PDF | Set PdfSaveOptions GridlineColor Transparent Aspose.Cells | PrintGridlines false Aspose.Cells PDF conversion
// Developer Intent: Create a PDF from an XLSM workbook with all gridlines suppressed.
// Use Cases: Produce clean, presentation‑ready PDFs from macro‑enabled workbooks without any gridline clutter. | Generate printable reports where gridlines must not appear, respecting the worksheet's PrintGridlines setting. | Export data to PDF with a minimalist layout by using hair‑type or fully transparent gridlines. | Automate batch conversion of multiple XLSM files to PDF while ensuring a uniform grid‑free appearance.
// AI Prompts: Write C# code that uses Aspose.Cells to convert an XLSM file to PDF and completely hide gridlines, including necessary PdfSaveOptions settings. | Explain the effect of GridlineType.Hair and GridlineColor.Transparent on the visual output of a PDF generated by Aspose.Cells. | Suggest alternative methods to suppress gridlines in PDF output with Aspose.Cells, such as worksheet property changes or different save‑option configurations. | Provide a step‑by‑step guide for disabling both visible and printable gridlines before exporting a workbook to PDF using Aspose.Cells for .NET.

using System;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfConversion
{
    // Loads an XLSM workbook, turns off both visible and printable gridlines on the target worksheet, configures PdfSaveOptions to use a hair‑type gridline and a transparent color, and saves the file as a PDF. The resulting PDF contains no solid gridlines.
    class Program
    {
        static void Main()
        {
            // Load the XLSM workbook
            Workbook workbook = new Workbook("input.xlsm");

            // Access the first worksheet (adjust index if needed)
            Worksheet sheet = workbook.Worksheets[0];

            // Disable visible gridlines in the worksheet
            sheet.IsGridlinesVisible = false;

            // Ensure gridlines are not printed
            sheet.PageSetup.PrintGridlines = false;

            // Create PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Set gridline type to a non‑solid style (Hair) – this effectively removes solid lines
            pdfOptions.GridlineType = GridlineType.Hair;

            // Optionally set gridline color to transparent to hide them completely
            pdfOptions.GridlineColor = Color.Transparent;

            // Save the workbook as PDF with the configured options
            workbook.Save("output.pdf", pdfOptions);
        }
    }
}
