// Title: C# – Export an Aspose.Cells Workbook to a PDF without Gridlines (RenderSolidGridlines = false)
// Description: This C# sample shows how to produce a clean PDF from an Aspose.Cells workbook by adding data, turning off worksheet gridline visibility, setting PdfSaveOptions.RenderSolidGridlines to false, and saving the file as GridFree.pdf. The result is a grid‑free PDF ideal for reports, invoices, or presentations.
// Keywords: Aspose.Cells PDF export C# | hide gridlines Aspose.Cells | PdfSaveOptions.RenderSolidGridlines false | C# generate PDF without gridlines | Aspose.Cells workbook to PDF | grid‑free PDF Aspose | Excel to PDF without gridlines | Aspose.Cells .NET | PDF export options | Aspose.Cells USA | Aspose.Cells Europe
// Common Searches: How to hide gridlines when saving Excel to PDF with Aspose.Cells C# | Aspose.Cells PdfSaveOptions.RenderSolidGridlines example | Export workbook to PDF without gridlines .NET | C# remove solid gridlines in PDF generated by Aspose.Cells | Aspose.Cells PDF gridline visibility settings
// Developer Intent: Export an Aspose.Cells workbook to a PDF that contains no visible or solid gridlines.
// Use Cases: Generate printable PDF reports from Excel data without distracting gridlines. | Create invoice PDFs where gridlines would interfere with the layout. | Automate batch conversion of spreadsheets to clean PDFs for client distribution. | Produce PDF documentation for regulatory submissions that require a grid‑free appearance.
// AI Prompts: Provide C# code that sets PdfSaveOptions.RenderSolidGridlines = false and disables Worksheet.IsGridlinesVisible before saving to PDF with Aspose.Cells. | Explain the difference between Worksheet.IsGridlinesVisible and PdfSaveOptions.RenderSolidGridlines when exporting to PDF. | Show a step‑by‑step guide to create a grid‑free PDF from an Aspose.Cells workbook in .NET. | What are the performance considerations when disabling solid gridlines in large workbooks?

using System;
using Aspose.Cells;

// This C# sample shows how to produce a clean PDF from an Aspose.Cells workbook by adding data, turning off worksheet gridline visibility, setting PdfSaveOptions.RenderSolidGridlines to false, and saving the file as GridFree.pdf. The result is a grid‑free PDF ideal for reports, invoices, or presentations.
class DisableSolidGridlinesPdf
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add some sample data so the worksheet has content
            worksheet.Cells["A1"].PutValue("Sample Data");
            worksheet.Cells["B2"].PutValue(123);

            // Hide gridlines so they are not rendered in the PDF
            worksheet.IsGridlinesVisible = false;

            // Create PDF save options (default settings)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF using the configured options
            workbook.Save("GridFree.pdf", pdfOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
