// Title: C# – Export Aspose.Cells Workbook to PDF without Gridlines (RenderSolidGridlines = false)
// Description: Demonstrates how to generate a grid‑free PDF from an Aspose.Cells workbook in C#. The example creates a workbook, adds sample data, disables worksheet gridlines, sets PdfSaveOptions.RenderSolidGridlines to false, and saves the file as a PDF with no visible gridlines.
// Keywords: Aspose.Cells C# PDF export | RenderSolidGridlines false | hide gridlines PDF | disable solid gridlines Aspose | Worksheet.IsGridlinesVisible false | grid‑free PDF | Excel to PDF without gridlines | Aspose.Cells PDF options | US developers | European .NET community
// Common Searches: Aspose.Cells hide gridlines when saving PDF | C# export Excel to PDF without gridlines | PdfSaveOptions.RenderSolidGridlines property | disable solid gridlines Aspose.Cells PDF | how to remove gridlines from PDF generated by Aspose
// Developer Intent: Produce a PDF from an Aspose.Cells workbook that contains no gridlines.
// Use Cases: Create clean, printable reports or invoices where cell borders are unnecessary. | Generate PDF versions of dashboards or charts without the default spreadsheet grid background. | Prepare legal or compliance documents from Excel data that must appear grid‑free for a professional look.
// AI Prompts: Show C# code that sets PdfSaveOptions.RenderSolidGridlines = false and saves an Aspose.Cells workbook as a PDF without gridlines. | Explain the difference between Worksheet.IsGridlinesVisible and PdfSaveOptions.RenderSolidGridlines when exporting to PDF. | Provide a step‑by‑step guide to hide gridlines in an Excel worksheet and ensure they are not rendered in the resulting PDF using Aspose.Cells.

using System;
using Aspose.Cells;

// Demonstrates how to generate a grid‑free PDF from an Aspose.Cells workbook in C#. The example creates a workbook, adds sample data, disables worksheet gridlines, sets PdfSaveOptions.RenderSolidGridlines to false, and saves the file as a PDF with no visible gridlines.
class DisableGridlinesPdf
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Data");
            sheet.Cells["B2"].PutValue(123);
            sheet.Cells["C3"].PutValue(DateTime.Now);

            // Hide gridlines in the worksheet; they will not appear in the PDF
            sheet.IsGridlinesVisible = false;

            // PDF save options (no gridline-specific option needed)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF without gridlines
            workbook.Save("GridlinesDisabled.pdf", pdfOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
