// Title: Disable printing of cell comments during Excel to PDF conversion using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that loads an .xlsx file, sets PdfSaveOptions.PrintComments to false, and saves the workbook as a PDF with Aspose.Cells. | Show how to configure Aspose.Cells PdfSaveOptions to suppress all worksheet comments when exporting to PDF in a .NET application. | Provide a complete example that checks for the source Excel file, disables comment printing, and generates a clean PDF using Aspose.Cells.
// Common Searches: Aspose.Cells C# hide cell comments in PDF export | PdfSaveOptions.PrintComments false example Aspose.Cells | How to prevent worksheet comments from appearing in PDF generated by Aspose.Cells .NET | Export Excel to PDF without comments using Aspose.Cells library | C# code to disable comments when converting .xlsx to .pdf with Aspose.Cells
// Tags: PdfSaveOptions PrintComments false | Aspose.Cells PDF export hide comments | C# disable cell comments in PDF conversion | Excel to PDF conversion settings Aspose.Cells | Suppress worksheet comments Aspose.Cells PDF

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsPdfExport
{
    // The sample checks that the input Excel file exists, loads it into a Workbook, creates a PdfSaveOptions object with PrintComments set to false to omit cell comments, and then saves the workbook as a PDF. Errors are caught and reported.
    class Program
    {
        static void Main()
        {
            try
            {
                const string inputFile = "input.xlsx";
                const string outputFile = "output.pdf";

                // Verify that the input workbook exists
                if (!File.Exists(inputFile))
                {
                    Console.WriteLine($"Input file not found: {inputFile}");
                    return;
                }

                // Load the workbook
                Workbook workbook = new Workbook(inputFile);

                // Configure PDF save options (default settings)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Save the workbook as a PDF
                workbook.Save(outputFile, pdfOptions);
                Console.WriteLine($"PDF successfully saved to: {outputFile}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
