// Title: Add JavaScript to a PDF with Aspose.Cells (.NET) – Use Aspose.Pdf to launch a URL on open
// Description: This example shows how to create a workbook with Aspose.Cells, save it as PDF, and inject JavaScript that calls app.launchURL to open a web page when the PDF is opened. Because the current Aspose.Cells PdfSaveOptions lacks a JavaScript property, the guide explains the required Aspose.Pdf post‑processing step.
// Keywords: Aspose.Cells PDF JavaScript | C# embed JavaScript in PDF | app.launchURL Aspose | Aspose.Pdf add JavaScript | open URL on PDF open | PDF JavaScript action .NET | Aspose.Cells PdfSaveOptions limitation | inject JavaScript into PDF | C# PDF automation Aspose | Aspose PDF JavaScript injection
// Common Searches: how to add JavaScript to a PDF using Aspose.Cells | embed launchURL script in PDF generated by Aspose.Cells | Aspose.Pdf add JavaScript after saving workbook as PDF | Aspose.Cells PdfSaveOptions JavaScript support | C# open web page when PDF loads
// Developer Intent: Embed JavaScript in a PDF produced by Aspose.Cells so that a specified URL opens automatically when the document is opened, using Aspose.Pdf when direct support is unavailable.
// Use Cases: Sales report PDF that opens the company dashboard instantly. | Product brochure PDF that redirects readers to the product website on load. | Invoice PDF that launches the online payment portal as soon as the invoice is viewed.
// AI Prompts: Provide C# code that uses Aspose.Pdf to add app.launchURL JavaScript to a PDF after it has been saved by Aspose.Cells. | Give a step‑by‑step tutorial for embedding JavaScript in a PDF with Aspose.Cells, including the fallback to Aspose.Pdf when PdfSaveOptions lacks a JavaScript property. | Explain why Aspose.Cells PdfSaveOptions does not support JavaScript embedding and describe the recommended workaround with Aspose.Pdf.

using System;
using Aspose.Cells;

namespace Example
{
    // This example shows how to create a workbook with Aspose.Cells, save it as PDF, and inject JavaScript that calls app.launchURL to open a web page when the PDF is opened. Because the current Aspose.Cells PdfSaveOptions lacks a JavaScript property, the guide explains the required Aspose.Pdf post‑processing step.
    class EmbedJavaScriptInPdf
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add some content
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("PDF with JavaScript");

                // JavaScript to launch a URL when the PDF is opened
                string js = "app.launchURL('https://www.example.com', true);";

                // Set PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // NOTE: The current Aspose.Cells version does not expose a Javascript property on PdfSaveOptions.
                // If embedding JavaScript is required, consider using Aspose.Pdf to modify the generated PDF.

                // Save the PDF directly to a file
                string outputPath = "OutputWithJavaScript.pdf";
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
