// Title: Embed a CSV file as an attachment in a PDF using Aspose.Cells (C#)
// Description: The sample creates a workbook, writes a temporary CSV file, inserts it as an OLE object shown as an icon, enables PdfSaveOptions.EmbedAttachments, saves the workbook as a PDF that contains the CSV attachment, and finally deletes the temporary CSV file.
// Keywords: Aspose.Cells PDF attachment C# | embed CSV in PDF Aspose.Cells | PdfSaveOptions EmbedAttachments | add OLE object CSV Aspose.Cells | export Excel to PDF with attachment | C# embed file in PDF Aspose.Cells | PDF with embedded files C#
// Common Searches: Aspose.Cells embed CSV in PDF C# | PdfSaveOptions EmbedAttachments example | Add OLE object to worksheet and export as PDF | How to attach files to PDF generated by Aspose.Cells | C# save workbook as PDF with embedded CSV
// Developer Intent: I want to embed a CSV file as an attachment inside a PDF produced from an Aspose.Cells workbook.
// Use Cases: Generate a financial report PDF that includes the original CSV data for audit verification. | Distribute a spreadsheet package where the supporting CSV files are bundled inside the exported PDF for easy extraction. | Automate regulatory document creation that must contain source CSV files as embedded attachments. | Create a product catalog PDF that carries a CSV of SKU details for downstream processing.
// AI Prompts: Write C# code with Aspose.Cells to embed a CSV file as an OLE attachment in a PDF and ensure the attachment is saved. | Explain the role of PdfSaveOptions.EmbedAttachments and list other properties that affect attachment visibility or behavior. | Provide troubleshooting steps when the CSV attachment does not appear in the PDF generated by Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;   // Required for OleObject

namespace AsposeCellsCsvAttachmentDemo
{
    // The sample creates a workbook, writes a temporary CSV file, inserts it as an OLE object shown as an icon, enables PdfSaveOptions.EmbedAttachments, saves the workbook as a PDF that contains the CSV attachment, and finally deletes the temporary CSV file.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Add a title cell (optional)
                sheet.Cells["A1"].PutValue("PDF with CSV Attachment Example");

                // Path to the temporary CSV file
                string csvPath = "sample.csv";

                // Create a simple CSV file for demonstration if it does not exist
                if (!File.Exists(csvPath))
                {
                    try
                    {
                        File.WriteAllText(csvPath, "Name,Score\nAlice,85\nBob,92");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Failed to create CSV file: {ex.Message}");
                        return;
                    }
                }

                // Read CSV bytes (required by OleObjects.Add overload)
                byte[] csvData;
                try
                {
                    csvData = File.ReadAllBytes(csvPath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to read CSV file: {ex.Message}");
                    return;
                }

                // Add the CSV as an OLE object (attachment) to the worksheet
                // OleObjects.Add returns the index of the newly added object
                int oleIndex = sheet.OleObjects.Add(10, 10, 200, 200, csvData);
                OleObject ole = sheet.OleObjects[oleIndex];
                ole.FileFormatType = FileFormatType.Csv;   // Specify CSV format
                ole.DisplayAsIcon = true;                  // Show as an icon in the sheet

                // Configure PDF save options to embed OLE attachments
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    EmbedAttachments = true
                };

                // Save the workbook as PDF with the embedded CSV attachment
                string pdfPath = "WorkbookWithCsvAttachment.pdf";
                workbook.Save(pdfPath, pdfOptions);

                // Clean up the temporary CSV file
                if (File.Exists(csvPath))
                {
                    try
                    {
                        File.Delete(csvPath);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Failed to delete temporary CSV file: {ex.Message}");
                    }
                }

                Console.WriteLine($"PDF saved to '{pdfPath}' with CSV attachment embedded.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
