// Title: Embed a Text File as a PDF Attachment with Aspose.Cells PdfSaveOptions (C#)
// Description: Creates a workbook, adds sample content, writes a temporary .txt file, embeds it as an OLE object displayed as an icon, enables attachment embedding via PdfSaveOptions, saves the workbook as a PDF with the text file attached, and cleans up the temporary file.
// Keywords: Aspose.Cells embed text file PDF | PdfSaveOptions EmbedAttachments C# | add OLE object to worksheet C# | save workbook as PDF with attachment | C# embed OLE object in PDF | Aspose.Cells PDF attachment | embed txt as PDF attachment
// Common Searches: embed txt file in PDF using Aspose.Cells C# | Aspose.Cells PdfSaveOptions attach files | add OLE object to Excel sheet and export to PDF | C# generate PDF with embedded document Aspose.Cells | how to include attachments in PDF generated by Aspose.Cells
// Developer Intent: Add a .txt document as an embedded attachment in a PDF produced from an Aspose.Cells workbook using C#.
// Use Cases: Distribute a financial report PDF that carries a terms‑and‑conditions text file for compliance. | Create a product catalog PDF with a specifications text file attached to each product sheet. | Generate an invoice PDF that includes a separate text file containing payment instructions.
// AI Prompts: Show how to embed a CSV file as an attachment in a PDF with Aspose.Cells and PdfSaveOptions (C#). | Explain how to attach multiple files (TXT, DOCX, PDF) to a single PDF generated by Aspose.Cells. | Provide C# code to embed a text file as an OLE object, display it as an icon, and ensure it appears as an attachment in the saved PDF.

using System;
using System.IO;
using Aspose.Cells;

namespace EmbedTextAsPdfAttachment
{
    // Creates a workbook, adds sample content, writes a temporary .txt file, embeds it as an OLE object displayed as an icon, enables attachment embedding via PdfSaveOptions, saves the workbook as a PDF with the text file attached, and cleans up the temporary file.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Add some visible content so the PDF is not empty
                sheet.Cells["A1"].PutValue("PDF with Embedded Text Attachment");

                // Path of the text file to embed
                string txtFilePath = "SampleText.txt";

                // Create a simple text file (in a real scenario the file may already exist)
                File.WriteAllText(txtFilePath, "This is the content of the embedded text document.");

                // Ensure the text file exists before embedding
                if (!File.Exists(txtFilePath))
                    throw new FileNotFoundException("The text file to embed was not found.", txtFilePath);

                // Embed the text file as an OLE object
                // Parameters: upper-left row, upper-left column, height, width, file bytes
                int oleIndex = sheet.OleObjects.Add(5, 0, 200, 200, File.ReadAllBytes(txtFilePath));

                // Display the OLE object as an icon
                sheet.OleObjects[oleIndex].DisplayAsIcon = true;

                // Configure PDF save options to embed OLE attachments
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    EmbedAttachments = true
                };

                // Save the workbook as a PDF file with the embedded text attachment
                string outputPdf = "WorkbookWithEmbeddedText.pdf";
                workbook.Save(outputPdf, pdfOptions);

                // Clean up the temporary text file if it exists
                if (File.Exists(txtFilePath))
                {
                    File.Delete(txtFilePath);
                }

                Console.WriteLine($"PDF saved to '{outputPdf}' with the text file embedded as an attachment.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
