// Title: How to add JavaScript to a PDF generated by Aspose.Cells in C# to open a URL on document open
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, saves it as a PDF, and then uses a .NET PDF library (e.g., Aspose.PDF) to embed a JavaScript launch script that opens a specified URL when the PDF is opened. | Provide a step‑by‑step C# example that post‑processes a PDF produced by Aspose.Cells and injects an open‑action JavaScript to redirect the viewer to a web page.
// Common Searches: Aspose.Cells C# add open action JavaScript to exported PDF | C# inject JavaScript into PDF created by Aspose.Cells to open a website | How to launch a URL when a PDF generated from Aspose.Cells opens | Post‑process Aspose.Cells PDF with Aspose.PDF to add JavaScript open action
// Tags: Aspose.Cells PDF export with JavaScript open-action | C# post‑process PDF to embed JavaScript | Aspose.PDF embed JavaScript launch script | open‑action script PDF C# | launch URL on PDF load Aspose

using System;
using Aspose.Cells;

namespace AsposeCellsPdfJavaScriptExample
{
    // The example shows how to create a workbook with Aspose.Cells, save it as a PDF, and explains that direct JavaScript injection is not supported in the current Aspose.Cells version. It recommends a post‑processing step using a .NET PDF library (such as Aspose.PDF) to add an open‑action JavaScript that opens a given URL when the PDF is opened.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Add sample data to the first worksheet
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Sample data");

                // Configure PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Note: Embedding JavaScript in PDF is not supported directly via PdfSaveOptions in this version.

                // Save the workbook as a PDF
                workbook.Save("Output.pdf", pdfOptions);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
