// Title: How to embed image and CSV files into a PDF generated from an Aspose.Cells workbook using C# (Aspose.Pdf post‑processing)
// AI Prompts: Generate C# code that creates a workbook, saves it as PDF with Aspose.Cells, then uses Aspose.Pdf to attach a PNG image and a CSV file to the resulting PDF. | Write C# logic to verify the existence of specified attachment files before converting a workbook to PDF and log the outcome.
// Common Searches: C# attach files to PDF after saving Aspose.Cells workbook | Aspose.Cells PdfSaveOptions embed attachments not supported | use Aspose.Pdf to add image attachment to PDF created from Excel | verify file existence before adding attachments to PDF in C# | workaround for adding CSV as attachment to PDF generated by Aspose.Cells
// Tags: Aspose.Cells PDF generation C# | Aspose.Pdf add attachment C# | embed image into PDF Aspose.Pdf | attach CSV file to PDF Aspose.Pdf | file existence check before PDF conversion C#

using System;
using System.IO;
using Aspose.Cells;

// Demonstrates creating a workbook, checking for an image and a CSV file, saving the workbook as PDF with PdfSaveOptions, and explains that Aspose.Cells cannot embed attachments directly, recommending a post‑processing step with Aspose.Pdf to add the files.
class EmbedAttachmentsToPdf
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Data");
            sheet.Cells["A2"].PutValue(123);
            sheet.Cells["A3"].PutValue(DateTime.Now);

            // Prepare PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // NOTE: Aspose.Cells PdfSaveOptions does not provide a direct API to embed file attachments.
            // The following code checks for the existence of files that could be attached in other contexts.
            // If attachment support is required, consider using Aspose.Pdf to add them after the PDF is generated.

            // ----- Check an image file -----
            string imagePath = "sampleImage.png";
            if (File.Exists(imagePath))
            {
                Console.WriteLine($"Image file found: {imagePath} (attachment not added – not supported by Aspose.Cells).");
            }
            else
            {
                Console.WriteLine($"Image file not found: {imagePath}");
            }

            // ----- Check a CSV file -----
            string csvPath = "dataFile.csv";
            if (File.Exists(csvPath))
            {
                Console.WriteLine($"CSV file found: {csvPath} (attachment not added – not supported by Aspose.Cells).");
            }
            else
            {
                Console.WriteLine($"CSV file not found: {csvPath}");
            }

            // Save the workbook as PDF
            string outputPdf = "WorkbookWithAttachments.pdf";
            workbook.Save(outputPdf, pdfOptions);

            Console.WriteLine($"PDF saved to '{outputPdf}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
