// Title: C# – Embed Multiple OLE Attachments (Image & CSV) into a PDF with Aspose.Cells PdfSaveOptions
// Description: Creates a workbook, adds a PNG image and a CSV file as OLE objects, sets them to display as icons, enables PdfSaveOptions.EmbedAttachments, and saves the result as a PDF containing both attachments.
// Keywords: Aspose.Cells PDF embed attachments | PdfSaveOptions EmbedAttachments C# | add OLE objects Aspose.Cells | multiple file attachments PDF .NET | C# embed image CSV in PDF | Aspose.Cells example PDF with OLE | export workbook to PDF with attachments | Aspose.Cells PdfSaveOptions sample code
// Common Searches: How to embed several files in a PDF generated by Aspose.Cells | Aspose.Cells C# embed PNG and CSV as OLE objects in PDF | Enable EmbedAttachments option in PdfSaveOptions | Save workbook as PDF with attached files using Aspose.Cells | Aspose.Cells example for multiple PDF attachments
// Developer Intent: Add image and CSV OLE objects to a worksheet and produce a PDF that carries those files as embedded attachments.
// Use Cases: Distribute a financial report PDF that includes the original data CSV and company logo as clickable attachments. | Create compliance PDFs where auditors can open supporting documents (e.g., policy PDFs, spreadsheets) embedded directly in the file. | Automate batch generation of product datasheets where each PDF bundles related images and data extracts for easy reference. | Provide end‑users with a single PDF package that contains supplemental resources such as charts, tables, and raw data files.
// AI Prompts: Generate C# code that adds multiple OLE objects (e.g., PNG, CSV) to an Aspose.Cells worksheet and saves the workbook as a PDF with embedded attachments. | Explain the PdfSaveOptions.EmbedAttachments property, its default behavior, and which file formats can be embedded as OLE objects. | Troubleshoot why embedded attachments are not appearing in the PDF produced by Aspose.Cells and suggest corrective steps.

using System;
using System.IO;
using Aspose.Cells;

// Creates a workbook, adds a PNG image and a CSV file as OLE objects, sets them to display as icons, enables PdfSaveOptions.EmbedAttachments, and saves the result as a PDF containing both attachments.
class EmbedAttachmentsDemo
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];
            worksheet.Cells["A1"].PutValue("PDF with multiple embedded attachments");

            // ---------- Create sample files to embed ----------
            // 1. Sample image file (1x1 pixel PNG)
            string imagePath = "sample.png";
            string base64Png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+XK6cAAAAASUVORK5CYII=";
            File.WriteAllBytes(imagePath, Convert.FromBase64String(base64Png));

            // 2. Sample CSV file
            string csvPath = "sample.csv";
            File.WriteAllText(csvPath, "Name,Score\nAlice,85\nBob,92");

            // ---------- Add OLE objects (attachments) ----------
            // Add image as OLE object
            if (File.Exists(imagePath))
            {
                int oleImgIndex = worksheet.OleObjects.Add(5, 0, 200, 200, File.ReadAllBytes(imagePath));
                worksheet.OleObjects[oleImgIndex].FileFormatType = FileFormatType.Png;
                worksheet.OleObjects[oleImgIndex].DisplayAsIcon = true;
            }

            // Add CSV as OLE object
            if (File.Exists(csvPath))
            {
                int oleCsvIndex = worksheet.OleObjects.Add(25, 0, 200, 200, File.ReadAllBytes(csvPath));
                worksheet.OleObjects[oleCsvIndex].FileFormatType = FileFormatType.Csv;
                worksheet.OleObjects[oleCsvIndex].DisplayAsIcon = true;
            }

            // ---------- Configure PDF save options ----------
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                EmbedAttachments = true // Enable embedding of OLE attachments
            };

            // Save the workbook as PDF with embedded attachments
            workbook.Save("MultipleAttachments.pdf", pdfOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
        finally
        {
            // Clean up temporary files if they exist
            try
            {
                if (File.Exists("sample.png"))
                    File.Delete("sample.png");
                if (File.Exists("sample.csv"))
                    File.Delete("sample.csv");
            }
            catch (Exception cleanupEx)
            {
                Console.WriteLine($"Cleanup error: {cleanupEx.Message}");
            }
        }
    }
}
