// Title: How to embed multiple external files as attachments when converting an Excel workbook to PDF using Aspose.Cells for .NET
// AI Prompts: Write C# code that sets PdfSaveOptions.EmbedAttachments to true and adds a collection of file paths to embed as PDF attachments during workbook.Save. | Create a method that validates each external file exists before adding it to the PdfSaveOptions attachment list for an Excel‑to‑PDF conversion with Aspose.Cells. | Show how to configure Aspose.Cells PdfSaveOptions to embed several documents (e.g., PDFs, images) into the generated PDF while preserving workbook data.
// Common Searches: Aspose.Cells C# embed multiple files as attachments in PDF export | add file paths for PDF attachments using Aspose.Cells | convert Excel workbook to PDF with embedded documents in .NET | include external PDFs and images as attachments when saving Excel as PDF | C# example of embedding external files in PDF generated by Aspose.Cells
// Tags: aspocells pdfsaveoptions embedattachments c# | excel to pdf with embedded attachments | add external file paths to pdf export aspocells | c# embed multiple documents in pdf conversion | pdf attachment embedding using aspocells

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, enables PdfSaveOptions.EmbedAttachments, optionally adds external file paths to embed as attachments, and saves the workbook as a PDF file.
class Program
{
    static void Main()
    {
        try
        {
            const string inputFile = "input.xlsx";
            const string outputFile = "output.pdf";

            // Ensure the source workbook exists
            if (!File.Exists(inputFile))
            {
                Console.WriteLine($"Source file not found: {inputFile}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputFile);

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Embed external files referenced in the workbook as attachments
                EmbedAttachments = true
            };

            // Save the workbook as PDF
            workbook.Save(outputFile, pdfOptions);
            Console.WriteLine($"Workbook successfully saved as PDF: {outputFile}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
