// Title: Secure PDF Export with Aspose.Cells: Set User Password and Disable Printing (C#)
// Description: Shows how to encrypt a PDF created from an Aspose.Cells workbook using PdfSecurityOptions, assign user and owner passwords, and block printing, modification, and content extraction in a .NET application.
// Keywords: Aspose.Cells PDF encryption | C# PdfSecurityOptions | user password PDF Aspose | disable PDF printing | owner password Aspose.Cells | secure PDF export .NET | Excel to PDF security | PDF permission settings C#
// Common Searches: Aspose.Cells set PDF password C# | prevent printing in PDF exported from Aspose.Cells | PdfSecurityOptions example .NET | encrypt PDF with user password using Aspose.Cells | disable copy and print in PDF generated by Aspose.Cells
// Developer Intent: Apply PDF security when saving a workbook: add a user password and block printing (plus other permissions) via Aspose.Cells.
// Use Cases: Distribute confidential reports that require a password to open and cannot be printed. | Send secure invoices that are view‑only, preventing printing, editing, or copying. | Provide partners with protected PDFs where only authorized users can access the content.
// AI Prompts: Show how to enable form filling while keeping printing disabled with PdfSecurityOptions. | Give an example of setting copy‑and‑paste restriction in addition to printing block. | Explain how to validate the user password when opening the encrypted PDF using Aspose.Pdf. | Convert the static passwords to values read from a configuration file or user input.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsPdfSecurityDemo
{
    // Shows how to encrypt a PDF created from an Aspose.Cells workbook using PdfSecurityOptions, assign user and owner passwords, and block printing, modification, and content extraction in a .NET application.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            workbook.Worksheets[0].Cells["A1"].Value = "Secure PDF Example";

            // Configure PDF save options
            PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();

            // Create and configure PDF security options
            PdfSecurityOptions securityOptions = new PdfSecurityOptions();
            securityOptions.UserPassword = "UserSecret123";   // Password required to open the PDF
            securityOptions.OwnerPassword = "OwnerSecret456"; // Owner password with full rights
            securityOptions.PrintPermission = false;          // Disallow printing
            // Optional: tighten other permissions as needed
            securityOptions.ModifyDocumentPermission = false;
            securityOptions.ExtractContentPermission = false;
            securityOptions.FullQualityPrintPermission = false;

            // Assign the security options to the PDF save options
            pdfSaveOptions.SecurityOptions = securityOptions;

            // Save the workbook as a secured PDF
            workbook.Save("SecuredOutput.pdf", pdfSaveOptions);

            Console.WriteLine("PDF saved with user password and printing disabled.");
        }
    }
}
