// Title: Aspose.Cells for .NET – Export Excel to PDF with Embedded OLE Attachment and Minimum‑Size Optimization
// Description: Demonstrates how to create a workbook, add a text file as an OLE object, configure PdfSaveOptions to embed the attachment, apply MinimumSize optimization, use Flate compression, optionally export the document structure, save as PDF, and display the final file size that includes the embedded attachment.
// Keywords: Aspose.Cells PDF attachment | embed OLE in PDF .NET | minimum size PDF Aspose | Flate compression Aspose.Cells | ExportDocumentStructure PDF | C# Excel to PDF with attachment | reduce PDF file size Aspose | PDF file size after embedding OLE | Aspose.Cells PDF optimization options
// Common Searches: How to embed a text file as an attachment when saving Excel to PDF with Aspose.Cells | Aspose.Cells PDF minimum size optimization settings | Include OLE objects in PDF generated by Aspose.Cells without large file growth | What compression types does Aspose.Cells support for PDF export | Does ExportDocumentStructure affect PDF size in Aspose.Cells
// Developer Intent: Generate a PDF from an Excel workbook that contains an embedded OLE attachment while keeping the output file as small as possible using specific Aspose.Cells PDF save options.
// Use Cases: Attach supporting documents (e.g., contracts, terms) to a PDF report generated from Excel without significantly increasing size. | Create lightweight, distribution‑ready PDFs that bundle reference files for regulatory or audit purposes. | Automate invoice PDF creation with attached policy documents, applying maximum compression to meet email attachment limits.
// AI Prompts: Write C# code with Aspose.Cells to embed multiple OLE files into a PDF and apply the highest compression level. | Explain the impact of ExportDocumentStructure on PDF size in Aspose.Cells and when it should be disabled for size‑critical scenarios. | Provide a step‑by‑step verification method to confirm that OLE attachments are present in the exported PDF.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsPdfExportDemo
{
    // Demonstrates how to create a workbook, add a text file as an OLE object, configure PdfSaveOptions to embed the attachment, apply MinimumSize optimization, use Flate compression, optionally export the document structure, save as PDF, and display the final file size that includes the embedded attachment.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate some data
                sheet.Cells["A1"].PutValue("PDF Export with Attachments and Optimization");
                sheet.Cells["A2"].PutValue("Value 1");
                sheet.Cells["B2"].PutValue(123);
                sheet.Cells["A3"].PutValue("Value 2");
                sheet.Cells["B3"].PutValue(456);

                // Create a temporary file to embed as an OLE object
                string tempFilePath = Path.Combine(Path.GetTempPath(), "sample.txt");
                File.WriteAllText(tempFilePath, "This is a sample attachment for PDF export.");

                // Add the OLE object (attachment) to the worksheet
                int oleIndex = sheet.OleObjects.Add(5, 0, 200, 200, File.ReadAllBytes(tempFilePath));
                // Optional: display as an icon
                sheet.OleObjects[oleIndex].DisplayAsIcon = true;

                // Configure PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    // Embed the OLE attachment into the PDF
                    EmbedAttachments = true,

                    // Optimize for minimum file size (more important than print quality)
                    OptimizationType = PdfOptimizationType.MinimumSize,

                    // Use Flate compression to further reduce size
                    PdfCompression = PdfCompressionCore.Flate,

                    // Export document structure (optional, may affect size)
                    ExportDocumentStructure = true
                };

                // Define output PDF path
                string outputPdf = "ExportedWithAttachment.pdf";

                // Save the workbook as PDF with the specified options
                workbook.Save(outputPdf, pdfOptions);

                // Display the resulting file size
                long fileSize = new FileInfo(outputPdf).Length;
                Console.WriteLine($"PDF saved to '{outputPdf}' with size {fileSize} bytes.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
            finally
            {
                // Clean up temporary attachment file if it exists
                string tempFilePath = Path.Combine(Path.GetTempPath(), "sample.txt");
                if (File.Exists(tempFilePath))
                {
                    try
                    {
                        File.Delete(tempFilePath);
                    }
                    catch
                    {
                        // Ignored – best effort cleanup
                    }
                }
            }
        }
    }
}
