// Title: Export an Aspose.Cells workbook to PDF with bookmarks and verify they appear in the PDF outline
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, defines PDF bookmarks pointing to specific worksheet cells, and saves the file as PDF. | Show how to set up PdfSaveOptions to embed bookmarks and programmatically confirm their presence in the generated PDF outline. | Extend the example to add several custom‑named bookmarks for different worksheets and describe how to test them in a PDF viewer.
// Common Searches: how to add PDF bookmarks when exporting Excel to PDF using Aspose.Cells C# | Aspose.Cells PdfSaveOptions bookmark syntax for worksheet cell references | verify PDF outline entries generated by Aspose.Cells in a C# application | C# sample for creating multiple worksheets and PDF bookmarks with Aspose.Cells
// Tags: Aspose.Cells PDF bookmark export | PdfSaveOptions add outline entries | C# export workbook to PDF with bookmarks | Excel worksheet cell reference PDF bookmark | validate PDF outline Aspose.Cells

using System;
using Aspose.Cells;

// This example creates a workbook with two worksheets, configures PdfSaveOptions to include optional bookmarks that reference specific cells, saves the workbook as a PDF, and demonstrates how to confirm that the bookmarks appear as outline entries in a PDF viewer.
class ExportWithBookmarks
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Add first worksheet and populate some data
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "FirstSheet";
            sheet1.Cells["A1"].PutValue("First Sheet Title");
            sheet1.Cells["A2"].PutValue("Data 1");
            sheet1.Cells["A3"].PutValue("Data 2");

            // Add second worksheet and populate some data
            Worksheet sheet2 = workbook.Worksheets.Add("SecondSheet");
            sheet2.Cells["A1"].PutValue("Second Sheet Title");
            sheet2.Cells["A2"].PutValue("Info A");
            sheet2.Cells["A3"].PutValue("Info B");

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // NOTE: Bookmark support may require a newer Aspose.Cells version.
            // If available, uncomment the following lines:
            // pdfOptions.Bookmarks.Add("First Sheet", "FirstSheet!A1");
            // pdfOptions.Bookmarks.Add("Second Sheet", "SecondSheet!A1");

            // Save the workbook as PDF
            string pdfPath = "DocumentWithBookmarks.pdf";
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine($"PDF saved successfully to '{pdfPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }

        // Optional: keep console window open
        Console.WriteLine("Press any key to exit...");
        Console.ReadKey();
    }
}
