// Title: Create a PDF from an Aspose.Cells workbook with worksheet bookmarks and verify the outline in C#
// AI Prompts: Generate C# code that uses Aspose.Cells and PdfSaveOptions to export a workbook to PDF with a bookmark for each worksheet. | Show how to enable PDF outline (bookmarks) based on worksheet names when saving an Aspose.Cells workbook as PDF in .NET. | Write a C# console snippet that saves the PDF, prints its full path, and checks that the file exists after export.
// Common Searches: how to add worksheet bookmarks to PDF using Aspose.Cells C# | export Excel workbook to PDF with outline view in .NET Aspose.Cells | check if PDF generated by Aspose.Cells contains bookmarks programmatically
// Tags: Aspose.Cells PDF bookmark export | C# PdfSaveOptions worksheet outline | verify PDF file creation Aspose.Cells | export workbook to PDF with bookmarks | Aspose.Cells PDF outline validation

using System;
using System.IO;
using Aspose.Cells;

// The example creates a workbook with three worksheets (Summary, Data, Report), assigns a header to each, and saves the workbook as a PDF using PdfSaveOptions to generate bookmarks for each worksheet. It then outputs the full path of the generated PDF and confirms that the file was created successfully.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and add worksheets with data
            Workbook workbook = new Workbook();

            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "Summary";
            sheet1.Cells["A1"].PutValue("Summary Sheet");

            Worksheet sheet2 = workbook.Worksheets.Add("Data");
            sheet2.Cells["A1"].PutValue("Data Sheet");

            Worksheet sheet3 = workbook.Worksheets.Add("Report");
            sheet3.Cells["A1"].PutValue("Report Sheet");

            // Save the workbook as PDF (bookmarks require Aspose.Cells.Pdf assembly, omitted here)
            string pdfPath = "WorkbookWithBookmarks.pdf";
            workbook.Save(pdfPath, SaveFormat.Pdf);
            Console.WriteLine($"Workbook saved as PDF: {Path.GetFullPath(pdfPath)}");

            // Verify that the PDF file was created
            if (File.Exists(pdfPath))
            {
                Console.WriteLine("PDF file created successfully.");
            }
            else
            {
                Console.WriteLine("Failed to create PDF file.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
