using System;
using Aspose.Cells;

class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate the worksheet with sample data (enough columns to demonstrate fitting)
        for (int col = 0; col < 30; col++)
        {
            sheet.Cells[0, col].PutValue($"Header {col + 1}");
            sheet.Cells[1, col].PutValue($"Data {col + 1}");
        }

        // Configure page setup to fit all columns on a single PDF page
        // Setting FitToPagesTall to 0 tells Aspose.Cells to fit all columns (width) on one page.
        sheet.PageSetup.FitToPagesWide = 1;   // one page wide
        sheet.PageSetup.FitToPagesTall = 0;   // unlimited pages tall (fit all columns)

        // Alternatively, the same effect can be achieved via SetFitToPages:
        // sheet.PageSetup.SetFitToPages(1, 0);

        // Create PDF save options and enable the AllColumnsInOnePagePerSheet flag
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            AllColumnsInOnePagePerSheet = true,
            OnePagePerSheet = true   // optional: ensures each sheet is a single page
        };

        // Save the workbook as PDF with the configured options
        workbook.Save("AllColumnsOnePage.pdf", pdfOptions);
    }
}
// Author: Generated by Aspose.Cells expert – demonstrates fitting all worksheet columns onto a single PDF page.