// Title: Add List Validation to Cell A1 and Export as Static Text PDF with Aspose.Cells for .NET (C#)
// Description: Demonstrates how to create a list‑type data validation on cell A1, enable the in‑cell dropdown, set an input message, and save the workbook as a PDF where the dropdown is rendered as plain text using Aspose.Cells.
// Keywords: Aspose.Cells C# | list validation Excel | PDF static dropdown | InCellDropDown PDF rendering | PdfSaveOptions Aspose | export Excel to PDF with validation | cell constraints PDF | Aspose.Cells data validation list | C# generate PDF from workbook | static text dropdown PDF
// Common Searches: Aspose.Cells render data validation as text in PDF | C# add list validation to Excel and save as PDF | how to show dropdown values in PDF generated by Aspose.Cells | export Excel validation list to PDF static text | InCellDropDown effect on PDF output Aspose
// Developer Intent: Create a list‑based validation on a specific cell and produce a PDF where the dropdown appears as non‑interactive text.
// Use Cases: Print‑ready reports that display allowed values without interactive controls. | Static PDF forms that show validation options for review or audit purposes. | Documentation of spreadsheet constraints when sharing Excel data as PDF.
// AI Prompts: Generate C# code with Aspose.Cells to add a list validation to a cell range and export the workbook to PDF showing the dropdown as plain text. | Explain how the InCellDropDown property influences PDF rendering and how to customize the input title and message. | Provide an example of applying the same list validation to multiple cells and preserving static dropdown text in the exported PDF.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to create a list‑type data validation on cell A1, enable the in‑cell dropdown, set an input message, and save the workbook as a PDF where the dropdown is rendered as plain text using Aspose.Cells.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Define the cell area (A1) where the validation will be applied
        CellArea validationArea = new CellArea
        {
            StartRow = 0,      // Row 0 (A)
            StartColumn = 0,   // Column 0 (1)
            EndRow = 0,
            EndColumn = 0
        };

        // Add a validation to the collection for the defined area
        int validationIndex = worksheet.Validations.Add(validationArea);
        Validation validation = worksheet.Validations[validationIndex];

        // Configure the validation as a list with predefined options
        validation.Type = ValidationType.List;
        validation.Formula1 = "Option1,Option2,Option3";

        // Enable the in‑cell dropdown arrow (will appear as static text in PDF)
        validation.InCellDropDown = true;

        // Show an input message that lists the allowed values (appears as static text)
        validation.ShowInput = true;
        validation.InputTitle = "Select an Option";
        validation.InputMessage = "Choose one: Option1, Option2, Option3";

        // Save the workbook as a PDF; the dropdown will be rendered as static text
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        workbook.Save("ValidationDropdown.pdf", pdfOptions);
    }
}
