// Title: Add row and column headings to every page when converting Excel to PDF with Aspose.Cells for .NET
// AI Prompts: Write C# code that iterates through all worksheets, enables PageSetup.PrintHeadings, and saves the workbook as a PDF using PdfSaveOptions. | Demonstrate how to export an Excel file to PDF using Aspose.Cells while keeping the row numbers and column letters visible on each page.
// Common Searches: C# Aspose.Cells export Excel to PDF with row and column headings displayed | Enable page headings for every sheet before PDF conversion in .NET | How to keep Excel worksheet headings in PDF generated by Aspose.Cells | PdfSaveOptions usage for preserving headings during Excel to PDF conversion | Set PrintHeadings for all worksheets programmatically in Aspose.Cells
// Tags: Aspose.Cells PrintHeadings PDF export | C# set worksheet page setup headings | PdfSaveOptions include row column headings | Excel to PDF with page headings .NET | enable page headings for each worksheet Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsPdfHeadingExample
{
    // // Loads an Excel workbook, turns on PrintHeadings for every worksheet, and saves it as a PDF using PdfSaveOptions.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                const string inputPath = "input.xlsx";
                const string outputPath = "output.pdf";

                // Verify that the input workbook exists to avoid FileNotFoundException
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                    return;
                }

                // Load the existing workbook
                Workbook workbook = new Workbook(inputPath);

                // Enable printing of row and column headings for each worksheet
                foreach (Worksheet sheet in workbook.Worksheets)
                {
                    sheet.PageSetup.PrintHeadings = true;
                }

                // Configure PDF save options (no PrintHeadings property here)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Save the workbook as PDF with the specified options
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                // Handle any unexpected errors
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
