// Title: Configure Aspose.Cells PdfSaveOptions to export Excel workbook images at 300 DPI for sharper PDF output (C#)
// AI Prompts: Write C# code that sets a three‑hundred‑dpi image scaling option before saving an Excel file to PDF with Aspose.Cells. | Show how to adjust the visual fidelity of PDFs generated from workbooks using Aspose.Cells in .NET. | Explain the impact of the image resolution option on PDF conversion in Aspose.Cells and how to set it to three hundred DPI.
// Common Searches: Aspose.Cells C# set PDF image DPI to 300 | How to increase image quality when converting Excel to PDF with Aspose.Cells | C# sample for exporting Excel images at higher DPI to PDF with Aspose.Cells | Default DPI for images in PDFs generated by Aspose.Cells and steps to modify it | Generate PDFs from Excel with improved image clarity via Aspose.Cells .NET
// Tags: Aspose.Cells PDF raster image resolution | PdfSaveOptions high‑resolution export | C# workbook to PDF image sharpness | image resampling DPI Aspose.Cells | high‑resolution PDF generation Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example loads an Excel workbook, creates a PdfSaveOptions object (which uses a 300 DPI image resolution by default), and saves the workbook as a PDF, resulting in sharper images in the generated PDF file.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Ensure the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the source workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure PDF save options (default image resolution is 300 DPI)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as PDF with the specified options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
