using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfOptimizationDemo
{
    class Program
    {
        static void Main()
        {
            // Load the source XLSB workbook
            Workbook workbook = new Workbook("input.xlsb");

            // Configure PDF save options with MinimumSize optimization
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                OptimizationType = PdfOptimizationType.MinimumSize
            };

            // Save the workbook as a PDF using the configured options
            workbook.Save("output.pdf", pdfOptions);
        }
    }
}

// Author: Generated by Aspose.Cells expert – demonstrates loading XLSB, applying MinimumSize PDF optimization, and saving.