// Title: Log PDF bookmark names created during Excel to PDF export with Aspose.Cells for .NET
// AI Prompts: Write C# code that saves an Excel Workbook as a PDF with Aspose.Cells and returns a collection of all bookmark titles added during the export. | Demonstrate how to gather worksheet names and defined range names as PDF bookmarks and write the list to a log file after the conversion. | Extend the export routine to capture the page number of each bookmark using Aspose.Cells PDF save options and output it alongside the bookmark name.
// Common Searches: aspose.cells c# export excel to pdf and retrieve bookmark titles | how to get list of pdf bookmarks generated by Aspose.Cells workbook save | c# log worksheet and named range bookmarks after converting Excel to PDF | extract pdf bookmark names and page numbers from Aspose.Cells conversion | audit pdf bookmarks created from Excel workbook using Aspose.Cells .NET
// Tags: export workbook to pdf with aspose.cells | collect pdf bookmark names during conversion | log worksheet and defined name bookmarks c# | aspose.cells pdfsaveoptions bookmark extraction | audit pdf bookmarks generated by excel export

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;

// // Loads an Excel file, gathers worksheet names and defined range names as bookmark identifiers, saves the workbook as a PDF using Aspose.Cells, and writes the collected bookmark titles (optionally with page numbers) to the console or a log file.
class PdfBookmarkLogger
{
    static void Main()
    {
        try
        {
            // Input and output paths
            string inputPath = @"C:\Input\Sample.xlsx";
            string outputPath = @"C:\Output\Sample.pdf";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            string? outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Load the workbook
            var workbook = new Workbook(inputPath);

            // Collect bookmark names (worksheet names and defined names)
            var bookmarkNames = new List<string>();

            // Worksheet names are added as PDF bookmarks by default
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                bookmarkNames.Add(sheet.Name);
            }

            // Include defined names (named ranges) as bookmarks
            foreach (Name definedName in workbook.Worksheets.Names)
            {
                // Use the Text property to get the name string
                bookmarkNames.Add(definedName.Text);
            }

            // Configure PDF save options (default settings already generate bookmarks)
            var pdfOptions = new PdfSaveOptions();

            // Export the workbook to PDF
            workbook.Save(outputPath, pdfOptions);

            // Log the collected bookmark names for audit purposes
            Console.WriteLine("PDF Bookmarks created during export:");
            foreach (string name in bookmarkNames)
            {
                Console.WriteLine($"- {name}");
            }

            // Optional: write the log to a file
            // File.WriteAllLines(@"C:\Logs\PdfBookmarks.log", bookmarkNames);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
