// Title: Export an Excel workbook to PDF while preserving cell background colors using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, configures PdfSaveOptions to keep cell fill shading, and saves the workbook as a PDF. | Describe the steps to set up Aspose.Cells PdfSaveOptions in C# so that background colors are retained during Excel‑to‑PDF conversion.
// Common Searches: Aspose.Cells C# preserve cell fill when converting Excel to PDF | PDF export from .xlsx retaining background colors using Aspose.Cells | How to keep worksheet shading in PDF generated by Aspose.Cells .NET | PdfSaveOptions keep background color Aspose.Cells example
// Tags: Aspose.Cells preserve background colors PDF | C# configure PdfSaveOptions for shading | Excel to PDF conversion with formatting Aspose.Cells | save workbook as PDF retaining fill colors

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // The example loads an Excel file with Aspose.Cells, creates a PdfSaveOptions object (which retains cell background colors by default), ensures the output folder exists, and saves the workbook as a PDF while handling possible exceptions.
    class Program
    {
        static void Main(string[] args)
        {
            string inputPath = "input.xlsx";
            string outputPath = "output.pdf";

            try
            {
                // Verify that the input file exists to avoid FileNotFoundException
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the workbook from the input file
                Workbook workbook = new Workbook(inputPath);

                // Configure PDF save options (default options preserve cell background)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Ensure the output directory exists
                string outputDir = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the workbook as a PDF file
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"Workbook successfully saved to PDF: {outputPath}");
            }
            catch (Exception ex)
            {
                // Catch any runtime exceptions and display an error message
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
