// Title: Aspose.Cells .NET – Export Excel to PDF with solid hair‑thin gridlines
// Description: C# example that creates a workbook, enables gridlines, sets PdfSaveOptions.GridlineType to Hair and GridlineColor to Black, and saves the sheet as a PDF where the gridlines appear as continuous solid lines.
// Keywords: Aspose.Cells | C# PDF export | PdfSaveOptions | GridlineType Hair | solid gridlines PDF | continuous lines Excel to PDF | .NET workbook to PDF | gridline color Aspose.Cells | Excel rendering PDF | hair‑thin gridlines
// Common Searches: Aspose.Cells export Excel to PDF with solid gridlines | PdfSaveOptions GridlineType Hair example C# | how to make gridlines continuous in PDF using Aspose.Cells | set gridline color when saving workbook as PDF | C# code for solid gridlines in PDF output
// Developer Intent: Generate a PDF from an Excel workbook where the cell gridlines are rendered as uninterrupted solid lines.
// Use Cases: Printing reports that require clear, unbroken cell borders. | Creating PDF invoices or statements where gridlines must separate line items distinctly. | Producing documentation PDFs that preserve the visual layout of the original spreadsheet.
// AI Prompts: Write C# code with Aspose.Cells to save a worksheet as PDF using GridlineType.Hair and black gridlines. | Explain the visual effect of GridlineType.Hair on PDF gridlines generated by Aspose.Cells. | List steps to verify that the exported PDF contains continuous solid gridlines.

using System;
using Aspose.Cells;
using System.Drawing;

// C# example that creates a workbook, enables gridlines, sets PdfSaveOptions.GridlineType to Hair and GridlineColor to Black, and saves the sheet as a PDF where the gridlines appear as continuous solid lines.
class SolidGridlinesPdfDemo
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Add sample data so gridlines are visible
        sheet.Cells["A1"].PutValue("Solid Gridlines Demo");
        sheet.Cells["A2"].PutValue(1);
        sheet.Cells["B2"].PutValue(2);
        sheet.Cells["C2"].PutValue(3);
        sheet.Cells["A3"].PutValue(4);
        sheet.Cells["B3"].PutValue(5);
        sheet.Cells["C3"].PutValue(6);

        // Enable gridlines visibility
        sheet.IsGridlinesVisible = true;

        // Configure PDF save options to render gridlines as a continuous (hair‑thin) line
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        pdfOptions.GridlineType = GridlineType.Hair; // thin line appears solid
        pdfOptions.GridlineColor = Color.Black;     // optional: set gridline color

        // Save the workbook as PDF with the specified options
        workbook.Save("SolidGridlines.pdf", pdfOptions);
    }
}
