// Title: Render solid gridlines when converting an XLSX workbook to PDF using Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an Excel workbook, activates gridline printing for every worksheet, and saves the file as a PDF with Aspose.Cells so the gridlines appear as solid lines. | Show how to set up PdfSaveOptions in Aspose.Cells to preserve solid gridlines during Excel‑to‑PDF conversion in a .NET application.
// Common Searches: Aspose.Cells C# export Excel to PDF with visible gridlines | Enable solid gridlines in PDF output from an XLSX file using Aspose.Cells .NET | Print gridlines in PDF generated by Aspose.Cells workbook.Save | How to keep Excel gridlines when saving as PDF with Aspose.Cells | Aspose.Cells PDFSaveOptions gridlines not showing
// Tags: Aspose.Cells enable gridline printing | PDF export gridline rendering Aspose.Cells | C# workbook save as PDF with gridlines | Worksheet page setup gridline option | PdfSaveOptions configuration for gridlines

using Aspose.Cells;
using System;
using System.IO;

// The example loads an XLSX workbook, sets PageSetup.PrintGridlines = true on each worksheet, and saves the workbook as a PDF using PdfSaveOptions, producing solid gridlines in the resulting PDF.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Verify that the input file exists before attempting to load it
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {inputPath}");
                return;
            }

            // Load the workbook from the specified file
            Workbook workbook = new Workbook(inputPath);

            // Enable printing of gridlines for every worksheet
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                sheet.PageSetup.PrintGridlines = true;
            }

            // Configure PDF save options (gridlines will be rendered as solid lines by default)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF file
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
