// Title: Aspose.Cells .NET: Render Solid Gridlines When Saving to PDF
// Description: Shows how to produce a PDF with solid gridlines from an Excel workbook using Aspose.Cells for .NET by enabling worksheet gridlines and setting PdfSaveOptions.RenderSolidGridlines to true.
// Keywords: Aspose.Cells | PDF gridlines | RenderSolidGridlines | PdfSaveOptions | C# Excel to PDF | solid gridlines | worksheet.IsGridlinesVisible | .NET code example
// Common Searches: Aspose.Cells render solid gridlines PDF C# | PdfSaveOptions.RenderSolidGridlines example | how to keep gridlines in PDF generated by Aspose.Cells | enable gridlines when converting Excel to PDF .NET | solid gridlines in PDF using Aspose.Cells
// Developer Intent: Generate a PDF that displays solid gridlines by configuring PdfSaveOptions.RenderSolidGridlines and worksheet gridline visibility in Aspose.Cells for .NET.
// Use Cases: Create printable reports where spreadsheet gridlines must appear as solid lines in the PDF. | Maintain visual consistency of Excel layouts when sharing documents as PDFs. | Automate batch conversion of workbooks to PDFs with gridline styling preserved.
// AI Prompts: Write C# code that saves an Aspose.Cells workbook to PDF with PdfSaveOptions.RenderSolidGridlines set to true. | Compare worksheet.IsGridlinesVisible and PdfSaveOptions.RenderSolidGridlines for PDF generation. | Explain how to combine gridline visibility settings and PDF save options to produce solid gridlines in the output PDF.

using System;
using Aspose.Cells;

namespace AsposeCellsPdfGridlinesDemo
{
    // Shows how to produce a PDF with solid gridlines from an Excel workbook using Aspose.Cells for .NET by enabling worksheet gridlines and setting PdfSaveOptions.RenderSolidGridlines to true.
    public class Program
    {
        public static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet worksheet = workbook.Worksheets[0];

                // Populate some sample data so gridlines are visible
                worksheet.Cells["A1"].PutValue("Solid Gridlines Demo");
                worksheet.Cells["B2"].PutValue(123);
                worksheet.Cells["C3"].PutValue(DateTime.Now);

                // Ensure gridlines are visible in the worksheet
                worksheet.IsGridlinesVisible = true;

                // Save the workbook as a PDF. Gridlines will be rendered because they are visible in the worksheet.
                workbook.Save("SolidGridlinesOutput.pdf");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
