// Title: C# – Export Excel to PDF with Continuous Solid (Hair) Gridlines using Aspose.Cells
// Description: Shows how to create a workbook, enable gridlines, set PdfSaveOptions.GridlineType to Hair (solid black lines), and save the file as a PDF so the gridlines appear as continuous lines.
// Keywords: Aspose.Cells | C# | PdfSaveOptions | GridlineType | Hair gridlines | solid gridlines PDF | export Excel to PDF | gridline color | continuous gridlines | Aspose.Cells PDF export
// Common Searches: Aspose.Cells export PDF solid gridlines | How to make gridlines solid in PDF with Aspose.Cells | PdfSaveOptions GridlineType Hair example C# | Set gridline color when saving workbook to PDF Aspose.Cells | C# code to export Excel with visible gridlines to PDF
// Developer Intent: Generate a PDF from an Excel workbook where the worksheet gridlines are rendered as continuous solid (hair) lines.
// Use Cases: Print‑ready reports that require clear cell separation without adding explicit borders. | Invoices or financial statements where gridlines must remain visible for auditability. | Documentation sheets that need to match the on‑screen Excel layout when distributed as PDF.
// AI Prompts: Provide C# code to change the gridline color and thickness when saving a workbook to PDF with Aspose.Cells. | Explain how to programmatically verify that a PDF generated by Aspose.Cells contains solid (hair) gridlines. | Show examples of using different GridlineType values (Dotted, Dashed, Hair) and their visual impact in the resulting PDF.

using System;
using System.Drawing;
using Aspose.Cells;

// Shows how to create a workbook, enable gridlines, set PdfSaveOptions.GridlineType to Hair (solid black lines), and save the file as a PDF so the gridlines appear as continuous lines.
class SolidGridlinesPdfDemo
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Add sample data to make gridlines visible
        sheet.Cells["A1"].PutValue("Solid Gridlines Demo");
        sheet.Cells["A2"].PutValue(1);
        sheet.Cells["B2"].PutValue(2);
        sheet.Cells["C2"].PutValue(3);
        sheet.Cells["A3"].PutValue(4);
        sheet.Cells["B3"].PutValue(5);
        sheet.Cells["C3"].PutValue(6);

        // Enable gridlines visibility
        sheet.IsGridlinesVisible = true;

        // Configure PDF save options to use a solid (hair) gridline style
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            GridlineType = GridlineType.Hair,   // Hair line appears as a continuous solid line
            GridlineColor = Color.Black         // Optional: set gridline color
        };

        // Save the workbook as PDF with the specified gridline settings
        workbook.Save("SolidGridlines.pdf", pdfOptions);
    }
}
