// Title: Convert a CSV file to PDF in C# using Aspose.Cells LoadOptions and PdfSaveOptions
// AI Prompts: Generate C# code that loads a CSV file into an Aspose.Cells Workbook with LoadOptions set to CSV format and saves it as a PDF using PdfSaveOptions. | Update the conversion script to set the PDF page orientation to landscape and embed all fonts in the output PDF. | Add comprehensive error handling that logs a missing CSV file warning and records any conversion exceptions to a log file.
// Common Searches: asp.net convert csv to pdf using aspose.cells workbook | c# load csv with aspose.cells LoadOptions and export to pdf | how to set landscape orientation in Aspose.Cells PdfSaveOptions c# | embed fonts in pdf generated by Aspose.Cells c# | handle file not found error when converting csv to pdf with Aspose.Cells
// Tags: Aspose.Cells CSV to PDF conversion | LoadOptions CSV format .NET | PdfSaveOptions landscape orientation | embedding fonts in PDF Aspose.Cells | file not found error handling Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The example checks for the presence of an input CSV file, loads it into an Aspose.Cells Workbook using LoadOptions configured for CSV, and then saves the workbook as a PDF with default PdfSaveOptions, while providing basic exception handling.
class CsvToPdfConverter
{
    static void Main()
    {
        // Path to the source CSV file
        string csvPath = "input.csv";

        // Verify that the CSV file exists before attempting to load it
        if (!File.Exists(csvPath))
        {
            Console.WriteLine($"Error: The file \"{csvPath}\" was not found.");
            return;
        }

        try
        {
            // Load the CSV file into a Workbook using LoadOptions for CSV format
            LoadOptions loadOptions = new LoadOptions(LoadFormat.Csv);
            Workbook workbook = new Workbook(csvPath, loadOptions);

            // Configure PDF save options (no special properties needed for CSV)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Path to the output PDF file
            string pdfPath = "output.pdf";

            // Save the workbook as PDF
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine("CSV has been successfully converted to PDF.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred during conversion: {ex.Message}");
        }
    }
}
