// Title: C# – Use a Custom Font for Unicode Characters When Saving Excel to PDF with Aspose.Cells
// Description: Demonstrates how to configure Aspose.Cells PdfSaveOptions to apply a specific TrueType font (e.g., MingLiu) for Unicode ranges, enable workbook default‑font fallback, and perform font‑compatibility checks before exporting an Excel workbook to PDF.
// Keywords: Aspose.Cells PDF export | PdfSaveOptions DefaultFont | Unicode font fallback C# | Chinese characters PDF Aspose | CheckFontCompatibility | Excel to PDF custom font | .NET Aspose.Cells Unicode
// Common Searches: Aspose.Cells set custom font for Unicode PDF export | C# export Excel to PDF with Chinese characters | PdfSaveOptions CheckFontCompatibility example | How to use DefaultFont in Aspose.Cells | Fallback font for missing glyphs Aspose.Cells
// Developer Intent: Apply a designated TrueType font to render Unicode glyphs correctly during Excel‑to‑PDF conversion.
// Use Cases: Create multilingual PDF reports from Excel where non‑Latin scripts (e.g., Chinese) are displayed using a reliable fallback font. | Maintain the workbook’s original font for standard text while automatically switching to a Unicode‑compatible font for unsupported characters. | Ensure PDF output contains embedded fonts to prevent missing glyphs on client machines.
// AI Prompts: Show how to set PdfSaveOptions.DefaultFont and enable CheckWorkbookDefaultFont in Aspose.Cells for C#. | Provide sample code that replaces missing Unicode glyphs with MingLiu when saving an Excel file to PDF. | Explain how to embed a custom TrueType font in the PDF generated by Aspose.Cells and verify Unicode rendering.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to configure Aspose.Cells PdfSaveOptions to apply a specific TrueType font (e.g., MingLiu) for Unicode ranges, enable workbook default‑font fallback, and perform font‑compatibility checks before exporting an Excel workbook to PDF.
class ReplaceUnicodeWithCustomFontPdf
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Add some text, including Unicode characters that may not be rendered correctly by default fonts
        worksheet.Cells["A1"].PutValue("Sample English Text");
        worksheet.Cells["A2"].PutValue("如果默认字体支持中文，这将显示正确"); // Chinese characters

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            // Set a font that supports the required Unicode range
            DefaultFont = "MingLiu",
            // Try to use the workbook's default font first
            CheckWorkbookDefaultFont = true,
            // Ensure font compatibility checking so fallback fonts are applied when needed
            CheckFontCompatibility = true
        };

        // Save the workbook to PDF using the configured options
        workbook.Save("UnicodeWithCustomFont.pdf", pdfOptions);
    }
}
