// Title: Validate Aspose.Cells PdfSaveOptions in C# by Inspecting the Generated PDF
// Description: A C# sample that creates a workbook, configures a comprehensive PdfSaveOptions object (compliance, metadata, layout, fonts, optimization, printing, and misc settings), saves the workbook as a PDF, reads the file as raw bytes, and programmatically confirms that the custom Producer string and PDF/A‑1b compliance marker are embedded. The example also prints key option values for quick manual verification.
// Keywords: Aspose.Cells PdfSaveOptions verification | C# PDF/A-1b compliance check | read PDF producer metadata C# | Aspose.Cells PDF generation settings | validate PDF options .NET | Aspose.Cells PDF font embedding | verify OnePagePerSheet Aspose.Cells
// Common Searches: How to confirm PDF/A-1b compliance after saving with Aspose.Cells | Read Producer metadata from a PDF generated by Aspose.Cells in C# | Check if OnePagePerSheet option was applied in Aspose.Cells PDF output | Verify font embedding in PDFs created with Aspose.Cells | Inspect raw PDF bytes for Aspose.Cells save options
// Developer Intent: The developer needs to ensure that every property set in PdfSaveOptions is accurately reflected in the resulting PDF file.
// Use Cases: Extract the PDF byte stream and search for the '/Producer (MyCompany PDF Generator)' entry to validate custom metadata. | Detect the '/PDF/A-1b' tag in the PDF content to confirm PDF/A‑1b compliance. | Log selected option values (e.g., OnePagePerSheet, AllColumnsInOnePagePerSheet, OptimizationType) after saving for manual cross‑checking of layout and size optimizations. | Automate regression tests that compare expected PDF markers against actual output after code changes.
// AI Prompts: Generate C# code that reads a PDF created with Aspose.Cells and returns the PDF/A compliance level. | Provide a method to programmatically verify that all fonts are embedded in a PDF saved using PdfSaveOptions. | Suggest a robust alternative to ASCII string search for validating PDF metadata and compliance markers in .NET.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// A C# sample that creates a workbook, configures a comprehensive PdfSaveOptions object (compliance, metadata, layout, fonts, optimization, printing, and misc settings), saves the workbook as a PDF, reads the file as raw bytes, and programmatically confirms that the custom Producer string and PDF/A‑1b compliance marker are embedded. The example also prints key option values for quick manual verification.
class PdfOptionsVerification
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];
        worksheet.Cells["A1"].PutValue("Verification");
        worksheet.Cells["A2"].PutValue("Check options");

        // Configure PDF save options with a variety of settings
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            // Compliance and metadata
            Compliance = PdfCompliance.PdfA1b,
            Producer = "MyCompany PDF Generator",

            // Layout options
            OnePagePerSheet = true,
            AllColumnsInOnePagePerSheet = true,

            // Font handling
            CheckFontCompatibility = true,
            CheckWorkbookDefaultFont = true,
            DefaultFont = "Arial",
            FontEncoding = PdfFontEncoding.Identity,
            EmbedStandardWindowsFonts = true,
            EmbedAttachments = true,

            // Optimization and structure
            OptimizationType = PdfOptimizationType.MinimumSize,
            ExportDocumentStructure = true,
            DisplayDocTitle = true,

            // Error handling and printing
            IgnoreError = true,
            OutputBlankPageWhenNothingToPrint = true,
            PageIndex = 0,
            PageCount = 1,
            PrintingPageType = PrintingPageType.IgnoreBlank,
            GridlineType = GridlineType.Dotted,
            TextCrossType = TextCrossType.CrossKeep,
            DefaultEditLanguage = DefaultEditLanguage.English,
            SheetSet = SheetSet.Visible,

            // Miscellaneous
            ClearData = false,
            CachedFileFolder = Path.GetTempPath(),
            ValidateMergedAreas = true,
            MergeAreas = true,
            SortNames = true,
            SortExternalNames = true,
            RefreshChartCache = true
        };

        // Save the workbook as a PDF using the configured options
        string pdfFilePath = "VerificationOutput.pdf";
        workbook.Save(pdfFilePath, pdfOptions);

        // Simple verification: read the PDF as text and look for known markers
        byte[] pdfBytes = File.ReadAllBytes(pdfFilePath);
        string pdfContent = System.Text.Encoding.ASCII.GetString(pdfBytes);

        // Verify that the Producer string was embedded
        bool producerVerified = pdfContent.Contains("/Producer (MyCompany PDF Generator)");

        // Verify that the PDF/A-1b compliance marker is present
        bool complianceVerified = pdfContent.Contains("/PDF/A-1b");

        Console.WriteLine($"Producer verification: {(producerVerified ? "Passed" : "Failed")}");
        Console.WriteLine($"Compliance verification: {(complianceVerified ? "Passed" : "Failed")}");

        // Output selected option values for manual inspection
        Console.WriteLine($"OnePagePerSheet: {pdfOptions.OnePagePerSheet}");
        Console.WriteLine($"AllColumnsInOnePagePerSheet: {pdfOptions.AllColumnsInOnePagePerSheet}");
        Console.WriteLine($"OptimizationType: {pdfOptions.OptimizationType}");
        Console.WriteLine($"ExportDocumentStructure: {pdfOptions.ExportDocumentStructure}");
    }
}
