// Title: C# – Save Aspose.Cells Workbook to PDF with Document Structure, One‑Page‑Per‑Sheet, Compression, and Formula Evaluation
// Description: Demonstrates how to create a workbook, populate cells, configure PdfSaveOptions (ExportDocumentStructure, OnePagePerSheet, PdfCompression, CalculateFormula) and save the file as a compressed, accessible PDF using Aspose.Cells in C#.
// Keywords: Aspose.Cells PDF export C# | PdfSaveOptions document structure | One page per sheet PDF | Flate compression Aspose | Calculate formulas before PDF save | Aspose.Cells SaveFormat.Pdf
// Common Searches: Aspose.Cells save workbook as PDF with document structure | C# export Excel to PDF one page per sheet | Compress PDF generated by Aspose.Cells | Calculate formulas when converting Excel to PDF Aspose | Enable accessibility tags in PDF from Aspose.Cells
// Developer Intent: The developer needs to export an Excel workbook to PDF using Aspose.Cells while applying specific PDF options such as document structure, single‑page layout, compression, and formula calculation.
// Use Cases: Create a compact PDF report from an Excel file for email distribution. | Generate accessible PDFs that retain the workbook’s logical structure for screen readers. | Produce PDFs that show the latest calculated values from complex formulas.
// AI Prompts: Show how to set PDF page orientation to landscape with PdfSaveOptions in Aspose.Cells C#. | Provide code to export each worksheet to a separate PDF file while keeping OnePagePerSheet enabled. | Explain how to enable PDF/A‑1b compliance when saving a workbook to PDF with Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;   // For PdfCompressionCore enum

// Demonstrates how to create a workbook, populate cells, configure PdfSaveOptions (ExportDocumentStructure, OnePagePerSheet, PdfCompression, CalculateFormula) and save the file as a compressed, accessible PDF using Aspose.Cells in C#.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample");
        sheet.Cells["B1"].PutValue("PDF Export");

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        pdfOptions.ExportDocumentStructure = true;   // retain document structure
        pdfOptions.OnePagePerSheet = true;          // output each sheet on a single page
        pdfOptions.PdfCompression = PdfCompressionCore.Flate; // enable compression
        pdfOptions.CalculateFormula = true;        // calculate formulas before saving

        // Save the workbook to PDF using the Save(string, SaveOptions) overload
        string outputPath = "output.pdf";
        workbook.Save(outputPath, pdfOptions);
    }
}
