// Title: How to keep Excel worksheet page breaks when converting a workbook to PDF using Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that converts an .xlsx file to PDF while preserving the original worksheet page breaks with Aspose.Cells. | Show how to configure Aspose.Cells PDF save options to turn off the single‑page‑per‑sheet mode and keep Excel pagination. | Provide a step‑by‑step example of loading a workbook, applying pagination settings, and saving as PDF in C#. | Explain how to align PDF pages with the Excel print area using Aspose.Cells.
// Common Searches: Aspose.Cells C# keep Excel print page breaks when saving as PDF | example of disabling single‑page‑per‑sheet to retain pagination | convert workbook to PDF preserving worksheet pagination .NET | retain Excel pagination in PDF generated by Aspose.Cells | C# export Excel to PDF with original page breaks using Aspose
// Tags: excel-to-pdf pagination Aspose.Cells | PdfSaveOptions OnePagePerSheet false | keep worksheet page breaks during PDF export | Aspose.Cells PDF export retain print layout | maintain Excel pagination in PDF conversion

// Load the Excel workbook that contains the original page breaks
Aspose.Cells.Workbook workbook = new Aspose.Cells.Workbook("input.xlsx");

// Configure PDF save options to preserve the Excel pagination
Aspose.Cells.PdfSaveOptions pdfOptions = new Aspose.Cells.PdfSaveOptions
{
    // Do not force each sheet onto a single PDF page; keep the original page breaks
    OnePagePerSheet = false
};

// Save the workbook as PDF while maintaining the original page breaks
workbook.Save("output.pdf", pdfOptions);
