// Title: Export an Aspose.Cells workbook to a PDF/A‑3u file with embedded XMP XML metadata using C#
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, populates cells, and saves it as a PDF/A‑3u compliant document with custom XMP metadata embedded. | Show how to configure PdfSaveOptions.Compliance to PdfA3u and attach an XML metadata stream to the PDF generated by Aspose.Cells. | Provide a step‑by‑step example that sets PDF/A‑3u compliance, adds accessibility‑focused XMP metadata, and writes the workbook to a PDF file.
// Common Searches: Aspose.Cells C# export workbook to PDF/A-3u with XMP metadata | How to embed custom XML metadata in PDF created by Aspose.Cells .NET | Set PDF compliance to PDF/A-3u using PdfSaveOptions in C# | Add accessibility metadata to PDF/A-3u file generated from Excel with Aspose.Cells | C# sample for PDF/A-3u compliance and XMP metadata in Aspose.Cells
// Tags: aspocells pdfsaveoptions pdfa-3u compliance c# | embed xmp metadata aspocells pdf | export workbook to pdfa-3u aspocells | c# add xml metadata to pdf aspocells | accessible pdf generation aspocells .net

using System;
using System.IO;
using System.Text;
using Aspose.Cells;

// The example creates an Aspose.Cells Workbook, writes sample data to the first worksheet, configures PdfSaveOptions with PDF/A‑3u compliance, adds an XMP XML metadata stream for accessibility, ensures the output directory exists, and saves the workbook as a PDF/A‑3u file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Populate the workbook with sample data
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;
            cells["A1"].PutValue("Sample");
            cells["B1"].PutValue("Data");

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // If the current Aspose.Cells version supports PDF/A compliance, set it.
            // Uncomment the following line if PdfCompliance enum is available.
            // pdfOptions.Compliance = PdfCompliance.PdfA3u;

            // Define output file path
            string outputPath = "SampleOutput.pdf";

            // Ensure the directory for the output file exists (if a directory is specified)
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as a PDF file using the configured options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
