// Title: Create PDF/A‑1a compliant PDF from Excel using Aspose.Cells for .NET (C#)
// Description: Demonstrates how to set PdfSaveOptions.Compliance to PdfCompliance.PdfA1a so that a Workbook saved as PDF meets the PDF/A‑1a archival standard. The example writes a value to cell A1, configures the compliance level, and saves the file as output_PdfA1a.pdf.
// Keywords: Aspose.Cells | C# | PdfSaveOptions | PdfCompliance | PDF/A-1a | archival PDF | Excel to PDF | document preservation | PDF/A compliance
// Common Searches: Aspose.Cells save workbook as PDF/A-1a | C# set PDF compliance to PDF/A-1a | How to generate archival PDF from Excel .NET | PdfSaveOptions Compliance PDF/A-1a example | Create PDF/A-1a file with Aspose.Cells
// Developer Intent: Generate a PDF/A‑1a archival PDF when exporting an Excel workbook with Aspose.Cells.
// Use Cases: Legal or regulatory submissions that require PDF/A‑1a preservation | Long‑term storage of financial reports in a standards‑compliant format | Integration with document management systems that enforce PDF/A‑1a compliance
// AI Prompts: Write C# code that uses Aspose.Cells to export an Excel sheet to a PDF/A‑1a compliant document. | Explain which additional metadata (e.g., XMP, document information) is needed for full PDF/A‑1a compliance in Aspose.Cells. | Show how to programmatically validate that a PDF generated by Aspose.Cells conforms to the PDF/A‑1a standard. | Troubleshoot common errors when setting PdfSaveOptions.Compliance to PdfA1a.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to set PdfSaveOptions.Compliance to PdfCompliance.PdfA1a so that a Workbook saved as PDF meets the PDF/A‑1a archival standard. The example writes a value to cell A1, configures the compliance level, and saves the file as output_PdfA1a.pdf.
class Program
{
    static void Main()
    {
        // Create a new workbook and add sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("PDF/A-1a compliance example");

        // Initialize PDF save options and set compliance to PDF/A-1a
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            Compliance = PdfCompliance.PdfA1a
        };

        // Save the workbook as a PDF file with the specified compliance level
        workbook.Save("output_PdfA1a.pdf", pdfOptions);
    }
}
