// Title: Aspose.Cells PdfSaveOptions – Keep Long Cell Text on One Line in PDF (C#)
// Description: This C# example shows how to export an Excel workbook to PDF using Aspose.Cells while preventing long strings from breaking across lines. The sample writes a lengthy value to cell A1, demonstrates the default behavior (the CrossStringInPdf property is unavailable in the current version), and explains how adjusting column width or layout settings can ensure text stays on a single line before saving the file as Output.pdf.
// Keywords: Aspose.Cells PDF export C# | PdfSaveOptions prevent text wrap | keep long text on one line PDF | Excel to PDF without line breaks | Aspose.Cells column width adjustment
// Common Searches: Aspose.Cells keep text on one line when saving to PDF | PdfSaveOptions prevent string wrapping .NET | How to stop text splitting in PDF generated by Aspose.Cells | Adjust column width for PDF export Aspose.Cells | CrossStringInPdf property missing Aspose.Cells
// Developer Intent: Export an Excel worksheet to PDF without splitting long cell strings across multiple lines.
// Use Cases: Create PDF invoices where product descriptions must remain on a single line. | Generate PDF reports with fixed‑width tables that should not wrap text. | Produce printable PDFs of contracts where clause numbers need to stay unbroken.
// AI Prompts: Provide C# code that uses Aspose.Cells to export a workbook to PDF while ensuring long cell text does not wrap. | Explain why the CrossStringInPdf property may be missing and what alternative settings can be used to keep text on one line. | Show how to programmatically adjust column widths in Aspose.Cells before saving to PDF to avoid line breaks.

using System;
using Aspose.Cells;

namespace AsposeCellsPdfExample
{
    // This C# example shows how to export an Excel workbook to PDF using Aspose.Cells while preventing long strings from breaking across lines. The sample writes a lengthy value to cell A1, demonstrates the default behavior (the CrossStringInPdf property is unavailable in the current version), and explains how adjusting column width or layout settings can ensure text stays on a single line before saving the file as Output.pdf.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet worksheet = workbook.Worksheets[0];

                // Put a long text value that should stay on a single line in the PDF
                worksheet.Cells["A1"].PutValue(
                    "This is a very long piece of text that should stay on a single line in the generated PDF and not be split across multiple lines.");

                // Create PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // The CrossStringInPdf option is not available in the current Aspose.Cells version.
                // By default, Aspose.Cells keeps the text on a single line unless it exceeds the cell width.
                // If needed, adjust column width or other layout settings here.

                // Save the workbook as PDF with the specified options
                workbook.Save("Output.pdf", pdfOptions);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
