// Title: Create PDF/A‑3u with Embedded XML Accessibility Metadata using Aspise.Cells C#
// Description: This C# example demonstrates how to generate a PDF/A‑3u file from an Aspose.Cells workbook, embed XML accessibility metadata via a custom document property, export the document structure, and configure security to allow content extraction for assistive technologies.
// Keywords: Aspose.Cells | C# | .NET | PDF/A-3u | PDF compliance | XML metadata | accessibility | ExportDocumentStructure | PdfSecurityOptions | custom document property | XMP | assistive technology
// Common Searches: Aspose.Cells PDF/A-3u C# example | embed XML metadata in PDF with Aspose.Cells | enable accessibility in PDF generated by Aspose.Cells | set PDF compliance to PDF/A-3u using Aspose.Cells | allow content extraction for accessibility Aspose.Cells PDF
// Developer Intent: Generate a PDF/A‑3u compliant PDF from a workbook and embed XML metadata to support accessibility.
// Use Cases: Compliance‑driven reports that must meet PDF/A‑3u and accessibility standards. | Archiving documents with embedded XMP metadata for searchable, accessible archives. | Creating PDFs that retain logical structure for screen readers while permitting content extraction. | Automated production of accessible PDFs for regulatory submissions.
// AI Prompts: Write C# code with Aspose.Cells to save a workbook as PDF/A‑3u, embed custom XML metadata, enable ExportDocumentStructure, and set PdfSecurityOptions.AccessibilityExtractContent = true. | Explain step‑by‑step how to add XMP‑style XML metadata as a custom document property and ensure it is embedded in a PDF/A‑3u file using Aspose.Cells. | Show how to configure PdfSaveOptions for PDF/A‑3u compliance and accessibility features in a .NET application.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;
using Aspose.Cells.Rendering.PdfSecurity;

namespace AsposeCellsPdfA3uExample
{
    // This C# example demonstrates how to generate a PDF/A‑3u file from an Aspose.Cells workbook, embed XML accessibility metadata via a custom document property, export the document structure, and configure security to allow content extraction for assistive technologies.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Aspose.Cells PDF/A‑3u Example");
            sheet.Cells["A2"].PutValue("This PDF includes accessibility metadata.");

            // Add a custom document property that holds XML metadata for accessibility
            // (In a real scenario this XML would follow the XMP or other accessibility schema)
            string xmlMetadata = @"<Metadata><Accessibility><Tag>Example</Tag></Accessibility></Metadata>";
            workbook.CustomDocumentProperties.Add("XMLMetadata", xmlMetadata);

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Set compliance level to PDF/A‑3u
                Compliance = PdfCompliance.PdfA3u,

                // Enable export of document structure (helps accessibility tools)
                ExportDocumentStructure = true
            };

            // Configure security options to allow content extraction for accessibility
            PdfSecurityOptions securityOptions = new PdfSecurityOptions
            {
                AccessibilityExtractContent = true
            };
            pdfOptions.SecurityOptions = securityOptions;

            // Save the workbook as a PDF with the specified options
            workbook.Save("Output_PdfA3u.pdf", pdfOptions);
        }
    }
}
