// Title: Add PDF Title, Author, and Subject with Aspose.Cells for .NET (C#) before saving
// Description: Demonstrates how to assign the built‑in document properties Title, Author, and Subject in a Workbook, configure PdfSaveOptions to display the title, and save the workbook as a PDF so the metadata is embedded in the output file.
// Keywords: Aspose.Cells PDF metadata C# | set PDF title author subject Aspose.Cells | PdfSaveOptions DisplayDocTitle | Aspose.Cells built‑in document properties | export workbook to PDF with metadata | C# add PDF document properties Aspose.Cells
// Common Searches: Aspose.Cells set PDF title and author C# | How to add subject metadata to PDF generated by Aspose.Cells | PdfSaveOptions DisplayDocTitle example | Export Excel to PDF with metadata using Aspose.Cells | C# embed PDF metadata with Aspose.Cells
// Developer Intent: Set the PDF document’s title, author, and subject via built‑in properties and PdfSaveOptions before saving the workbook.
// Use Cases: Create PDF reports that include searchable metadata for document management systems. | Generate compliance‑ready PDFs that record author and subject information automatically. | Produce PDFs where the viewer window shows a custom title defined in the source workbook.
// AI Prompts: Show C# code to add custom document properties and export them to a PDF with Aspose.Cells. | Provide an example of reading PDF metadata after saving a workbook using Aspose.Cells. | Explain how to disable the document title display in the PDF viewer with PdfSaveOptions.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;
using Aspose.Cells.Properties;

// Demonstrates how to assign the built‑in document properties Title, Author, and Subject in a Workbook, configure PdfSaveOptions to display the title, and save the workbook as a PDF so the metadata is embedded in the output file.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Add sample data (optional)
        workbook.Worksheets[0].Cells["A1"].PutValue("Sample PDF with metadata");

        // Set built‑in document properties that will become PDF metadata
        workbook.BuiltInDocumentProperties.Title = "Sample PDF Title";
        workbook.BuiltInDocumentProperties.Author = "John Doe";
        workbook.BuiltInDocumentProperties.Subject = "Demo of PDF metadata";

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        pdfOptions.DisplayDocTitle = true; // Use the document title for the PDF window title
        pdfOptions.CustomPropertiesExport = PdfCustomPropertiesExport.Standard; // Export custom properties if any

        // Save the workbook as PDF with the specified metadata
        workbook.Save("Output.pdf", pdfOptions);
    }
}
