// Title: How to keep long strings on a single line in PDF output using Aspose.Cells C# by enabling CrossStringInPdf
// AI Prompts: Write a C# snippet that creates an Aspose.Cells workbook, inserts a lengthy text into a cell, enables the PDF option that stops string wrapping, and saves the file as a PDF. | Show how to configure Aspose.Cells PDF save settings in C# to keep cell content on one line during PDF export. | Provide a minimal example demonstrating the use of Aspose.Cells to export Excel data to PDF without breaking long strings across lines.
// Common Searches: Aspose.Cells C# prevent text wrapping when exporting to PDF | How to keep long cell values on a single line in PDF generated by Aspose.Cells | PDF export options in Aspose.Cells to avoid line breaks for long strings | C# Aspose.Cells save workbook as PDF without splitting strings | Disable line breaks for long text in Excel to PDF conversion using Aspose.Cells
// Tags: Aspose.Cells PdfSaveOptions CrossStringInPdf | C# export Excel to PDF without text wrapping | prevent string splitting in PDF using Aspose.Cells | configure PDF save options for long text continuity | Aspose.Cells PDF line break control

using System;
using Aspose.Cells;

// The example creates a new Aspose.Cells Workbook, writes a long sentence into cell A1, configures PdfSaveOptions to disable string splitting across lines, and saves the workbook as output.pdf, with error handling.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Add sample data
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("This is a long string that should stay on a single line when exported to PDF.");

            // Configure PDF save options (default options are sufficient for this scenario)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF using the configured options
            workbook.Save("output.pdf", pdfOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
