// Title: Create a PDF from an Excel file in C# while keeping the original Excel page breaks using Aspose.Cells
// AI Prompts: Write C# code that loads an .xlsx workbook with Aspose.Cells, sets PdfSaveOptions.OnePagePerSheet to false, and saves it as a PDF preserving the Excel pagination. | Show how to verify the input Excel file exists, generate a minimal workbook when it is missing, and then convert it to a paginated PDF with Aspose.Cells. | Demonstrate configuring the output directory and adding exception handling while converting an Excel workbook to a PDF that respects Excel page breaks.
// Common Searches: Aspose.Cells C# preserve Excel page breaks when exporting to PDF | How to keep Excel pagination in PDF generated by Aspose.Cells | PdfSaveOptions OnePagePerSheet false example in .NET | Convert .xlsx to PDF with same page layout using Aspose.Cells | C# code to create PDF from Excel while maintaining printed page breaks
// Tags: Aspose.Cells PDF export preserving pagination | PdfSaveOptions OnePagePerSheet configuration | C# Excel workbook to PDF conversion | auto-create sample workbook if missing | ensure output directory exists Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The sample checks for an existing .xlsx file, creates a simple workbook if absent, loads it with Aspose.Cells, sets PdfSaveOptions.OnePagePerSheet to false to retain Excel page breaks, ensures the output folder exists, and saves the workbook as a paginated PDF while handling potential errors.
class ExcelToPdfWithPageBreaks
{
    static void Main()
    {
        // Paths for input Excel and output PDF
        string excelPath = @"C:\Input\SourceWorkbook.xlsx";
        string pdfPath   = @"C:\Output\ResultDocument.pdf";

        try
        {
            // Ensure the input workbook exists; create a simple one if missing
            if (!File.Exists(excelPath))
            {
                // Create directory if it does not exist
                string? excelDir = Path.GetDirectoryName(excelPath);
                if (!string.IsNullOrEmpty(excelDir))
                {
                    Directory.CreateDirectory(excelDir);
                }

                // Build a minimal workbook with sample data
                Workbook tempWb = new Workbook();
                Worksheet sheet = tempWb.Worksheets[0];
                sheet.Name = "Sample";

                // Populate some data
                sheet.Cells["A1"].PutValue("Header");
                for (int i = 2; i <= 50; i++)
                {
                    sheet.Cells[$"A{i}"].PutValue($"Row {i - 1}");
                }

                // Save the temporary workbook
                tempWb.Save(excelPath);
            }

            // Load the Excel workbook
            Workbook workbook = new Workbook(excelPath);

            // Configure PDF save options to preserve Excel page breaks
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // When false, each printed page in Excel becomes a separate PDF page,
                // preserving the original pagination defined by Excel page breaks.
                OnePagePerSheet = false
            };

            // Ensure the output directory exists
            string? pdfDir = Path.GetDirectoryName(pdfPath);
            if (!string.IsNullOrEmpty(pdfDir))
            {
                Directory.CreateDirectory(pdfDir);
            }

            // Save the workbook as PDF using the configured options
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine("PDF generated successfully at: " + pdfPath);
        }
        catch (Exception ex)
        {
            // Log or display the error details
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
