// Title: How to save an Aspose.Cells workbook as a PDF/A‑1a compliant PDF using PdfSaveOptions in C#
// AI Prompts: Write C# code that creates a Workbook, sets PdfSaveOptions.Compliance to PdfA1a, and saves the file as a PDF/A‑1a document. | Modify existing Aspose.Cells PDF export logic to enable PDF/A‑1a compliance by configuring the PdfSaveOptions object. | Provide a C# example that checks whether the PDF generated by Aspose.Cells meets PDF/A‑1a standards after saving.
// Common Searches: Aspose.Cells C# set PDF/A-1a compliance when saving workbook to PDF | PdfSaveOptions PdfACompliance property usage example | How to generate PDF/A-1a files from Excel using Aspose.Cells in .NET | C# code to export Excel to PDF/A-1a with Aspose.Cells library | Enable PDF/A-1a compliance in Aspose.Cells PDF export
// Tags: Aspose.Cells PDF/A-1a export C# | PdfSaveOptions compliance setting | set PdfACompliance PdfA1a | save workbook as PDF/A-1a | C# generate PDF/A-1a from Excel

using System;
using System.IO;
using Aspose.Cells;

// The example creates a new Workbook, adds sample data, configures PdfSaveOptions with PDF/A‑1a compliance (when supported), ensures the output directory exists, and saves the workbook as a PDF/A‑1a file, confirming successful export.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Add sample data to the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B1"].PutValue("World");

            // Configure PDF save options (PDF/A‑1a compliance can be set if supported)
            PdfSaveOptions saveOptions = new PdfSaveOptions();
            // Uncomment the following line if the PdfCompliance enum is available in your Aspose.Cells version
            // saveOptions.Compliance = PdfCompliance.PdfA1a;

            // Define output file path
            string outputPath = "output.pdf";

            // Ensure the directory for the output file exists
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as a PDF (PDF/A‑1a compliant if compliance is set)
            workbook.Save(outputPath, saveOptions);
            Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
