// Title: C# – Embed a QR Code at (200,300) in a PDF with Aspose.Cells RenderingWatermark
// Description: Creates an empty workbook, loads a QR‑code PNG, configures a RenderingWatermark with left/top alignment and OffsetX = 200, OffsetY = 300, assigns it to PdfSaveOptions, and saves the workbook as a PDF containing the QR code at the exact coordinates.
// Keywords: Aspose.Cells C# PDF watermark | RenderingWatermark QR code | position image PDF Aspose | offset X Y Aspose.Cells | embed QR code in PDF | PdfSaveOptions image overlay | C# generate PDF with QR code
// Common Searches: Aspose.Cells place QR code at specific coordinates | C# RenderingWatermark offset X Y example | Add image watermark to PDF generated by Aspose.Cells | Set absolute position for QR code in PDF using Aspose
// Developer Intent: Add a QR‑code image as a watermark positioned at (200,300) in the PDF generated from a workbook.
// Use Cases: Generate a sales report PDF that includes a scannable QR code at a fixed spot for tracking. | Create invoices with a QR code placed precisely for quick payment processing. | Produce certificates where a QR code appears at a designated location for verification.
// AI Prompts: Show how to rotate the QR‑code watermark 45° with Aspose.Cells. | Provide code that loads the QR image from a MemoryStream and positions it at (150,250). | Explain how to apply the QR‑code watermark only to the first page of the PDF.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsQrPdfDemo
{
    // Creates an empty workbook, loads a QR‑code PNG, configures a RenderingWatermark with left/top alignment and OffsetX = 200, OffsetY = 300, assigns it to PdfSaveOptions, and saves the workbook as a PDF containing the QR code at the exact coordinates.
    public class Program
    {
        public static void Main()
        {
            try
            {
                // Create a new workbook (empty worksheet)
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Optional: put some sample data
                sheet.Cells["A1"].PutValue("QR Code embedded at (200,300)");

                // Path to QR code image
                string qrImagePath = "qr_code.png";

                // Prepare PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Load QR code image bytes if the file exists
                if (File.Exists(qrImagePath))
                {
                    byte[] qrImageData = File.ReadAllBytes(qrImagePath);

                    // Create an image watermark using the QR code bytes
                    RenderingWatermark watermark = new RenderingWatermark(qrImageData)
                    {
                        // Align to top‑left corner of the page
                        HAlignment = TextAlignmentType.Left,
                        VAlignment = TextAlignmentType.Top,
                        // Set absolute offsets (in points) to position the image at (200,300)
                        OffsetX = 200f,
                        OffsetY = 300f,
                        // Make the watermark fully opaque and treat it as background
                        Opacity = 1.0f,
                        IsBackground = true
                    };

                    pdfOptions.Watermark = watermark;
                }
                else
                {
                    Console.WriteLine($"Warning: QR code image not found at '{qrImagePath}'. The PDF will be generated without a watermark.");
                }

                // Save the workbook as PDF with the optional QR code watermark
                workbook.Save("output_with_qr.pdf", pdfOptions);
                Console.WriteLine("PDF generated successfully: output_with_qr.pdf");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
