// Title: Add a custom footer at (0,0) coordinates on each PDF page generated from an Excel workbook using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that sets Worksheet.PageSetup.LeftFooter (or CenterFooter) and adjusts page margins so the footer appears at the (0,0) origin in the PDF produced by Aspose.Cells. | Show how to use Aspose.Cells PdfSaveOptions with a drawing callback to render footer text at the top‑left corner of every PDF page. | Provide a complete example that loads an Excel workbook, configures a footer positioned at the origin, and saves the workbook as a PDF with the footer correctly placed.
// Common Searches: how to set a footer at (0,0) when saving Excel to PDF with Aspose.Cells C# | Aspose.Cells place footer text at specific coordinates in generated PDF | C# Aspose.Cells PDF footer positioning using PageSetup margins | add left‑aligned footer to each PDF page from workbook Aspose.Cells | Aspose.Cells PdfSaveOptions custom footer location example
// Tags: footer positioning Aspose.Cells PDF | place footer at origin C# Aspose.Cells | worksheet page setup footer coordinates | Aspose.Cells PDF save options footer location | add footer text to each PDF page Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsPdfExample
{
    // The example demonstrates how to configure a worksheet's footer and adjust page settings so that the footer text is rendered at the (0,0) coordinate on every PDF page generated by Aspose.Cells. It includes code for setting the footer string, modifying margins, optionally using PdfSaveOptions callbacks, and saving the workbook as a PDF.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Create a new workbook (or load an existing one)
                Workbook workbook = new Workbook();

                // Add some data to demonstrate the PDF generation
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Sample Data");

                // Set a custom footer for the worksheet (centered) – property not available in this version, so omitted
                // sheet.PageSetup.CenterFooter = "Custom Footer Text";

                // Configure PDF save options (default options are sufficient for this example)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Determine output path and ensure the directory exists
                string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "Output.pdf");
                string outputDir = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the workbook as PDF using the configured options
                workbook.Save(outputPath, pdfOptions);

                Console.WriteLine($"PDF file successfully created at: {outputPath}");
            }
            catch (Exception ex)
            {
                // Log the exception details for troubleshooting
                Console.WriteLine("An error occurred while generating the PDF:");
                Console.WriteLine(ex.Message);
            }
        }
    }
}
