// Title: Validate PDF Page Count After Export with Aspose.Cells (C#)
// Description: Creates a workbook that spans multiple pages, uses SheetPrintingPreview to get the expected page count, saves the workbook to PDF while capturing the actual page count via a custom IPageSavingCallback, and compares the two values to confirm correct pagination.
// Keywords: Aspose.Cells PDF page count | C# PDF pagination validation | SheetPrintingPreview page count | PdfSaveOptions callback | Aspose.Cells .NET export verification | IPageSavingCallback example | PDF pagination testing
// Common Searches: how to check number of pages in PDF generated by Aspose.Cells | Aspose.Cells C# get expected PDF pages before save | use IPageSavingCallback to retrieve PDF page count | compare preview page count with saved PDF Aspose.Cells | validate PDF pagination after export .NET
// Developer Intent: Confirm that a PDF produced from an Aspose.Cells workbook contains the exact number of pages anticipated.
// Use Cases: Pre‑flight check of pagination before delivering a PDF report. | Logging actual page count during PDF generation for audit trails. | Automated detection of layout changes that affect page breaks.
// AI Prompts: Generate C# code that opens the saved PDF with a PDF inspection library (e.g., iTextSharp) and asserts the page count matches the expected value from SheetPrintingPreview. | Explain how to extend the sample to aggregate page counts across multiple worksheets in a single workbook. | Provide a step‑by‑step guide to embed this validation into an NUnit test suite for continuous integration.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfValidation
{
    // Callback to capture page count during PDF generation (optional)
    // Creates a workbook that spans multiple pages, uses SheetPrintingPreview to get the expected page count, saves the workbook to PDF while capturing the actual page count via a custom IPageSavingCallback, and compares the two values to confirm correct pagination.
    internal class PageCountCallback : IPageSavingCallback
    {
        public int TotalPages { get; private set; } = 0;

        public void PageStartSaving(PageStartSavingArgs args)
        {
            // args.PageCount gives total pages for the workbook at this point
            TotalPages = args.PageCount;
        }

        public void PageEndSaving(PageEndSavingArgs args)
        {
            // No additional handling needed
        }
    }

    public class PdfPageValidationDemo
    {
        public static void Run()
        {
            try
            {
                // ---------- Create workbook with data that spans multiple pages ----------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate many rows to force pagination
                for (int i = 0; i < 500; i++)
                {
                    sheet.Cells[i, 0].PutValue($"Row {i + 1}");
                }

                // Configure page setup (optional, influences pagination)
                sheet.PageSetup.PrintArea = "A1:A500";
                sheet.PageSetup.FitToPagesWide = 1;   // Fit width, allow multiple pages vertically
                sheet.PageSetup.FitToPagesTall = 0;   // No height restriction

                // ---------- Determine expected page count using rendering preview ----------
                ImageOrPrintOptions previewOptions = new ImageOrPrintOptions();
                SheetPrintingPreview preview = new SheetPrintingPreview(sheet, previewOptions);
                int expectedPageCount = preview.EvaluatedPageCount; // Expected pages according to Aspose.Cells

                // ---------- Save workbook to PDF ----------
                PdfSaveOptions pdfOptions = new PdfSaveOptions();
                PageCountCallback callback = new PageCountCallback();
                pdfOptions.PageSavingCallback = callback; // Capture page count during save (optional)

                string pdfPath = "ExportedDocument.pdf";

                // Ensure any existing file is overwritten safely
                try
                {
                    if (File.Exists(pdfPath))
                    {
                        File.Delete(pdfPath);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Warning: Unable to delete existing PDF file. {ex.Message}");
                }

                workbook.Save(pdfPath, pdfOptions);

                // Use callback value if available; otherwise fall back to preview count
                int generatedPageCount = callback.TotalPages > 0 ? callback.TotalPages : expectedPageCount;

                // ---------- Validation ----------
                Console.WriteLine($"Expected page count (preview): {expectedPageCount}");
                Console.WriteLine($"Generated page count (callback): {generatedPageCount}");

                if (generatedPageCount == expectedPageCount)
                {
                    Console.WriteLine("Validation succeeded: PDF contains the expected number of pages.");
                }
                else
                {
                    Console.WriteLine("Validation failed: PDF page count does not match the expected value.");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during PDF page validation: {ex.Message}");
            }
        }
    }

    // Entry point for demonstration
    class Program
    {
        static void Main()
        {
            PdfPageValidationDemo.Run();
        }
    }
}
