// Title: Render Emoji and Other Unicode Supplementary Characters in PDF with Aspose.Cells for .NET
// Description: This example creates a workbook, writes emojis (🌍🚀) into a cell, and saves the sheet as a PDF. By selecting a font that supports emoji (e.g., Segoe UI Emoji) and configuring PdfSaveOptions with Identity encoding and font‑compatibility checks, the generated PDF retains the original symbols.
// Keywords: Aspose.Cells PDF emoji | Unicode characters PDF .NET | PdfSaveOptions Identity encoding | default font emoji Aspose.Cells | render emojis in PDF | supplementary Unicode Aspose | C# Aspose.Cells PDF export
// Common Searches: how to keep emojis in PDF generated by Aspose.Cells | Aspose.Cells PdfSaveOptions Unicode support | set default font for emoji in Aspose.Cells PDF export | enable Identity encoding for Unicode in Aspose.Cells | Aspose.Cells PDF emoji rendering issues
// Developer Intent: Verify that emojis and other supplementary Unicode symbols are displayed correctly in PDFs produced by Aspose.Cells.
// Use Cases: Create a customer‑facing PDF report that includes user comments with emojis, ensuring the symbols are visible on all devices. | Export an invoice spreadsheet containing status icons (✅, ❌) as a PDF while preserving the exact glyphs. | Generate multilingual marketing materials with regional symbols and emojis, using fallback fonts when the primary emoji font is unavailable.
// AI Prompts: Write C# code that checks the rendered PDF for the presence of specific emoji glyphs after saving with Aspose.Cells. | Suggest fallback‑font strategies for environments that do not have Segoe UI Emoji installed. | Explain how to programmatically validate that the PDF file contains the expected Unicode code points for the inserted emojis.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering; // Required for PdfFontEncoding

// This example creates a workbook, writes emojis (🌍🚀) into a cell, and saves the sheet as a PDF. By selecting a font that supports emoji (e.g., Segoe UI Emoji) and configuring PdfSaveOptions with Identity encoding and font‑compatibility checks, the generated PDF retains the original symbols.
public class VerifyUnicodeEmojiPdf
{
    public static void Run()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Insert Unicode supplementary characters (emoji) into a cell
            sheet.Cells["A1"].PutValue("Hello 🌍🚀"); // Earth globe and rocket emoji

            // Configure PDF save options to handle Unicode characters correctly
            PdfSaveOptions saveOptions = new PdfSaveOptions
            {
                // Set a font that supports emoji characters (e.g., Segoe UI Emoji)
                DefaultFont = "Segoe UI Emoji",
                // Ensure the workbook's default font is considered first
                CheckWorkbookDefaultFont = true,
                // Keep font compatibility checking enabled to allow fallback fonts if needed
                CheckFontCompatibility = true,
                // Use Identity encoding to preserve all Unicode characters in the PDF
                FontEncoding = PdfFontEncoding.Identity
            };

            // Save the workbook as a PDF file
            string outputPath = "UnicodeEmojiOutput.pdf";
            workbook.Save(outputPath, saveOptions);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        VerifyUnicodeEmojiPdf.Run();
    }
}
