// Title: Verify embedded OLE attachment accessibility in a PDF generated from an Aspose.Cells workbook (C#)
// AI Prompts: Insert a temporary text file as an OLE object into cell A1 of a new workbook, save the workbook as PDF, and programmatically read the PDF to list embedded files to ensure the attachment is present. | Create a C# script that adds an OLE attachment to a worksheet using Aspose.Cells, exports the workbook to PDF, then uses a PDF library or viewer to confirm the attachment can be opened.
// Common Searches: how to check embedded OLE objects in PDF created with Aspose.Cells .NET | Aspose.Cells C# export workbook to PDF with attached file verification | programmatically verify PDF attachment after saving workbook as PDF using Aspose.Cells | C# example for adding OLE object to worksheet and confirming its presence in the PDF | test PDF viewer for embedded attachment generated by Aspose.Cells
// Tags: Aspose.Cells OLEObjects.Add example | export workbook to PDF with embedded OLE attachment | verify PDF embedded file accessibility C# | add text file as OLE object worksheet | PDF attachment validation using Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace EmbeddedAttachmentVerification
{
    // The sample creates a temporary text file, reads it into a byte array, embeds it as an OLE object at cell A1 of a new workbook, saves the workbook as a PDF, and then cleans up the temporary files, allowing verification that the attachment remains accessible in the generated PDF.
    class Program
    {
        static void Main()
        {
            try
            {
                // Prepare a temporary file to embed as an attachment
                string attachmentPath = Path.Combine(Path.GetTempPath(), "SampleAttachment.txt");
                File.WriteAllText(attachmentPath, "This is a sample attachment content.");

                // Verify the attachment file exists
                if (!File.Exists(attachmentPath))
                {
                    Console.WriteLine($"Attachment file not found: {attachmentPath}");
                    return;
                }

                // Load attachment data as byte array (required by OleObjects.Add overload)
                byte[] attachmentData;
                try
                {
                    attachmentData = File.ReadAllBytes(attachmentPath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to read attachment file: {ex.Message}");
                    return;
                }

                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet sheet = workbook.Worksheets[0];

                // Add the attachment as an OLE object to the worksheet at cell A1
                try
                {
                    // Parameters: row, column, height (pixels), width (pixels), data
                    sheet.OleObjects.Add(0, 0, 100, 100, attachmentData);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to add OLE object: {ex.Message}");
                    return;
                }

                // Define the output PDF file path
                string pdfPath = Path.Combine(Path.GetTempPath(), "WorkbookWithAttachment.pdf");

                // Save the workbook as PDF
                try
                {
                    workbook.Save(pdfPath, SaveFormat.Pdf);
                    Console.WriteLine($"Workbook saved as PDF: {pdfPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to save PDF: {ex.Message}");
                }

                // Clean up temporary attachment file (optional)
                try
                {
                    File.Delete(attachmentPath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to delete attachment file: {ex.Message}");
                }

                // Uncomment the following block if you want to delete the PDF after verification
                /*
                try
                {
                    File.Delete(pdfPath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to delete PDF file: {ex.Message}");
                }
                */
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
