// Title: ExportDocumentStructure = true: Generate PDF bookmarks that follow Excel sheet hierarchy and outline groups with Aspose.Cells C#
// Description: Shows how to create a workbook with three worksheets, apply row and column outline groups, enable outline visibility, set PdfSaveOptions.ExportDocumentStructure to true, and save the file as PDF. The saved PDF contains a bookmark tree that mirrors the worksheet order and the defined outline levels, allowing you to verify that the PDF outline matches the Excel structure.
// Keywords: Aspose.Cells | ExportDocumentStructure | PDF outline | PDF bookmarks | C# | .NET | worksheet grouping | row groups | column groups | PdfSaveOptions | Excel to PDF | outline hierarchy | code example | Aspose.Cells PDF export
// Common Searches: Aspose.Cells ExportDocumentStructure example | Create PDF bookmarks from Excel outline groups C# | Export Excel row groups as PDF outline Aspose.Cells | PdfSaveOptions ExportDocumentStructure true | Verify PDF bookmark hierarchy generated by Aspose.Cells
// Developer Intent: Confirm that setting ExportDocumentStructure to true produces a PDF whose bookmark tree reflects the workbook’s sheet order and any row/column outline groups.
// Use Cases: Produce a PDF report where each worksheet appears as a top‑level bookmark and grouped rows or columns become nested bookmarks for quick navigation. | Generate financial PDFs where SalesData row groups and Budget column groups are represented as hierarchical bookmarks. | Validate that a workbook without outline groups results in a PDF containing only worksheet‑level bookmarks.
// AI Prompts: Write a C# unit test that opens WorkbookWithOutline.pdf, extracts its bookmark tree, and asserts that the hierarchy matches the three worksheets and their row/column groups. | Provide sample code using a PDF library (e.g., iTextSharp or PdfSharp) to read the outline from the generated PDF and compare it with the expected structure defined in the Aspose.Cells workbook. | Explain how to disable ExportDocumentStructure, regenerate the PDF, and programmatically verify that the resulting PDF contains no bookmarks.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfOutlineDemo
{
    // Shows how to create a workbook with three worksheets, apply row and column outline groups, enable outline visibility, set PdfSaveOptions.ExportDocumentStructure to true, and save the file as PDF. The saved PDF contains a bookmark tree that mirrors the worksheet order and the defined outline levels, allowing you to verify that the PDF outline matches the Excel structure.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // -------------------------------------------------
                // Sheet 1 – simple data with row outline grouping
                // -------------------------------------------------
                Worksheet sheet1 = workbook.Worksheets[0];
                sheet1.Name = "SalesData";

                // Populate some rows
                for (int i = 0; i < 10; i++)
                {
                    sheet1.Cells[$"A{i + 1}"].PutValue($"Item {i + 1}");
                    sheet1.Cells[$"B{i + 1}"].PutValue((i + 1) * 100);
                }

                // Group rows 1‑5 and 6‑10 (creates outline levels)
                sheet1.Cells.GroupRows(0, 4, false);   // rows 1‑5
                sheet1.Cells.GroupRows(5, 9, false);   // rows 6‑10

                // Show outline in the worksheet
                sheet1.IsOutlineShown = true;

                // -------------------------------------------------
                // Sheet 2 – column outline grouping
                // -------------------------------------------------
                Worksheet sheet2 = workbook.Worksheets.Add("Budget");

                // Populate columns
                for (int i = 0; i < 5; i++)
                {
                    sheet2.Cells[0, i].PutValue($"Q{i + 1}");
                    sheet2.Cells[1, i].PutValue((i + 1) * 2500);
                }

                // Group columns A‑C and D‑E
                sheet2.Cells.GroupColumns(0, 2, false);
                sheet2.Cells.GroupColumns(3, 4, false);
                sheet2.IsOutlineShown = true;

                // -------------------------------------------------
                // Sheet 3 – no outline (to verify hierarchy handling)
                // -------------------------------------------------
                Worksheet sheet3 = workbook.Worksheets.Add("Summary");
                sheet3.Cells["A1"].PutValue("Overall Summary");
                sheet3.Cells["A2"].PutValue("Total Sales");
                sheet3.Cells["B2"].PutValue(12500);

                // -------------------------------------------------
                // Configure PDF save options to export document structure
                // -------------------------------------------------
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    // When true, the generated PDF will contain an outline (bookmarks)
                    // that mirrors the worksheet hierarchy and outline levels.
                    ExportDocumentStructure = true
                };

                // Optional: set PDF title via workbook's built‑in properties
                workbook.BuiltInDocumentProperties.Title = "Workbook Outline Demo";

                // Save the workbook as PDF
                string pdfPath = "WorkbookWithOutline.pdf";

                // Ensure the directory exists
                string pdfDir = Path.GetDirectoryName(pdfPath);
                if (!string.IsNullOrEmpty(pdfDir) && !Directory.Exists(pdfDir))
                {
                    Directory.CreateDirectory(pdfDir);
                }

                workbook.Save(pdfPath, pdfOptions);

                Console.WriteLine($"PDF saved to '{pdfPath}'.");
                Console.WriteLine("ExportDocumentStructure = true ensures the PDF contains an outline");
                Console.WriteLine("matching the worksheet hierarchy and outline groups.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }
}
