// Title: How to export a worksheet with emojis and other Unicode supplementary characters to PDF using Aspose.Cells for .NET (C#)
// AI Prompts: Generate C# code that writes a string containing emojis into a cell, applies an emoji‑compatible font, and saves the workbook as a PDF with Aspose.Cells. | Show how to configure a cell style in Aspose.Cells to use a font that supports Unicode supplementary characters before converting to PDF. | Provide a method to programmatically verify that emojis appear correctly in the PDF produced by Aspose.Cells.
// Common Searches: Aspose.Cells C# export worksheet to PDF with emoji support | How to display Unicode surrogate pair characters in PDF generated by Aspose.Cells | Set font for emoji rendering in Excel to PDF conversion using Aspose.Cells .NET | Verify emoji rendering in PDF output from Aspose.Cells workbook | Unicode supplementary characters not showing in Aspose.Cells PDF export
// Tags: emoji font setting Aspose.Cells PDF export | Unicode supplementary characters Aspose.Cells .NET | cell style configuration for PDF conversion Aspose.Cells | PDF generation with surrogate pairs Aspose.Cells | Aspose.Cells C# emoji rendering

using Aspose.Cells;
using System.Drawing;

// Creates a workbook, writes a string with emojis into cell A1, applies the Segoe UI Emoji font, and saves the workbook as a PDF named EmojiOutput.pdf, demonstrating correct rendering of Unicode supplementary characters.
class Program
{
    static void Main()
    {
        // Create a new workbook
        var workbook = new Workbook();

        // Get the first worksheet
        var sheet = workbook.Worksheets[0];

        // Write Unicode supplementary characters (e.g., emojis) into a cell
        // Example includes a globe and a smiling face emoji
        sheet.Cells["A1"].PutValue("Hello 🌍! 😀");

        // Apply a font that supports emoji rendering (Segoe UI Emoji)
        var style = sheet.Cells["A1"].GetStyle();
        style.Font.Name = "Segoe UI Emoji";
        style.Font.Size = 14;
        sheet.Cells["A1"].SetStyle(style);

        // Save the workbook as a PDF file
        workbook.Save("EmojiOutput.pdf", SaveFormat.Pdf);
    }
}
