// Title: ExportDocumentStructure: Generate PDF outline with nested row and column groups using Aspose.Cells for .NET (C#)
// Description: Creates a workbook with two worksheets, adds hierarchical row groups on the first sheet and column groups on the second, enables ExportDocumentStructure in PdfSaveOptions, and saves the file as a PDF. The resulting PDF contains bookmarks that mirror the nested groups defined in the spreadsheet.
// Keywords: Aspose.Cells | ExportDocumentStructure | PDF outline | nested row groups | nested column groups | C# | .NET | bookmark generation | worksheet outline | group rows | group columns
// Common Searches: Aspose.Cells ExportDocumentStructure nested groups | How to create PDF bookmarks from row groups in Aspose.Cells | C# export worksheet outline to PDF | PDF outline for grouped rows Aspose | Generate PDF bookmarks for column groups using Aspose.Cells
// Developer Intent: Confirm that the PDF produced by Aspose.Cells includes an outline (bookmarks) that accurately reflects the nested row and column groups defined in the workbook.
// Use Cases: Produce technical reports where grouped rows become navigable PDF bookmarks. | Export spreadsheets with hierarchical column groups to PDF for documentation purposes. | Automate validation that the PDF outline matches worksheet grouping after saving. | Create multi‑sheet PDFs with a consistent outline structure for end‑user manuals.
// AI Prompts: Write C# code that creates a workbook with nested row and column groups and saves it as a PDF with ExportDocumentStructure enabled. | Show how to read and verify the bookmarks/outlines from a PDF generated by Aspose.Cells in C#. | Provide troubleshooting steps when ExportDocumentStructure does not produce the expected PDF outline. | Create a C# unit test that asserts specific outline entries exist in the exported PDF.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsExamples
{
    // Creates a workbook with two worksheets, adds hierarchical row groups on the first sheet and column groups on the second, enables ExportDocumentStructure in PdfSaveOptions, and saves the file as a PDF. The resulting PDF contains bookmarks that mirror the nested groups defined in the spreadsheet.
    public class ExportDocumentStructureOutlineDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook with two worksheets
                Workbook workbook = new Workbook();
                Worksheet sheet1 = workbook.Worksheets[0];
                sheet1.Name = "First";

                Worksheet sheet2 = workbook.Worksheets.Add("Second");

                // Populate sample data in both sheets
                for (int i = 0; i < 20; i++)
                {
                    sheet1.Cells[$"A{i + 1}"].PutValue($"Item {i + 1}");
                    sheet1.Cells[$"B{i + 1}"].PutValue((i + 1) * 10);

                    sheet2.Cells[$"A{i + 1}"].PutValue($"Record {i + 1}");
                    sheet2.Cells[$"B{i + 1}"].PutValue((i + 1) * 5);
                }

                // Create nested row groups in the first sheet
                // Level 1 group (rows 1-10)
                sheet1.Cells.GroupRows(0, 9, false);
                // Level 2 nested group inside the first group (rows 3-6)
                sheet1.Cells.GroupRows(2, 5, true);

                // Create nested column groups in the second sheet
                // Level 1 group (columns A-C)
                sheet2.Cells.GroupColumns(0, 2, false);
                // Level 2 nested group inside the first group (columns B-C)
                sheet2.Cells.GroupColumns(1, 2, true);

                // Ensure outline summary rows appear below detail rows (optional)
                sheet1.Outline.SummaryRowBelow = true;
                sheet2.Outline.SummaryRowBelow = true;

                // Configure PDF save options to export document structure (outlines)
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    ExportDocumentStructure = true
                };

                // Save the workbook as PDF; the resulting PDF will contain an outline
                // reflecting the nested row/column groups created above.
                string outputPath = "NestedOutlineDemo.pdf";
                workbook.Save(outputPath, pdfOptions);

                Console.WriteLine($"PDF saved to '{outputPath}' with ExportDocumentStructure enabled.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }

    // Entry point for the console application
    public class Program
    {
        public static void Main(string[] args)
        {
            ExportDocumentStructureOutlineDemo.Run();
        }
    }
}
