// Title: Stream an Aspose.Cells workbook as a downloadable XLSX attachment (Content‑Disposition: attachment) in C#
// Description: Creates or opens an Aspose.Cells Workbook, writes data, sets the HTTP response headers for a file download, and streams the workbook directly to the client as an XLSX attachment without saving it to disk.
// Keywords: Aspose.Cells stream workbook to HTTP response | C# download Excel file attachment | ContentDisposition attachment Aspose.Cells | ASP.NET Core return XLSX file | Aspose.Cells export to browser | downloadable Excel from API
// Common Searches: how to send Aspose.Cells workbook as file download in C# | Aspose.Cells ContentDisposition attachment example | ASP.NET Core return Excel file generated by Aspose | stream XLSX to browser using Aspose.Cells | C# export Excel without saving to disk
// Developer Intent: Generate an Excel workbook with Aspose.Cells and deliver it to the user's browser as a downloadable attachment via an HTTP response.
// Use Cases: Web application offering on‑the‑fly report export in Excel format. | REST API endpoint that returns dynamically created spreadsheets. | Single‑page application needing a button to download generated data as XLSX. | Enterprise portal providing user‑specific Excel downloads without intermediate files.
// AI Prompts: Show how to modify the code to write the workbook to an ASP.NET Core MVC action result with Content‑Disposition set to attachment. | Provide an example of streaming an Aspose.Cells workbook from a Web API controller using HttpResponseMessage. | Explain how to set the correct MIME type and file name when returning the XLSX file in ASP.NET Web Forms. | Give a snippet that compresses the workbook into a zip stream before sending it as a download.

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsExample
{
    // Creates or opens an Aspose.Cells Workbook, writes data, sets the HTTP response headers for a file download, and streams the workbook directly to the client as an XLSX attachment without saving it to disk.
    public class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                // Create a new workbook and add sample data.
                Workbook workbook = new Workbook();
                workbook.Worksheets[0].Cells["A1"].PutValue("Hello, Aspose.Cells!");

                // Define output file path.
                string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "Sample.xlsx");

                // Ensure the directory exists.
                string outputDir = Path.GetDirectoryName(outputPath);
                if (!Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the workbook to the file system using XLSX format.
                workbook.Save(outputPath, SaveFormat.Xlsx);

                Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
