// Title: High‑Resolution PDF Export from Excel with Aspose.Cells for .NET (C#)
// Description: Loads an XLSX file, applies PdfSaveOptions with 300 DPI image resampling, JPEG quality 90, standard optimization, and formula calculation, then saves the workbook as a PDF while handling missing files and runtime errors.
// Keywords: Aspose.Cells PDF export | C# high DPI PDF | PdfSaveOptions SetImageResample | Standard optimization Aspose.Cells | calculate formulas PDF conversion | 300 DPI Excel to PDF | JPEG quality PDF Aspose | .NET Excel to PDF | Aspose.Cells Save as PDF | high quality PDF from workbook
// Common Searches: Aspose.Cells export Excel to PDF 300 DPI | Set JPEG quality when saving PDF with Aspose.Cells | Enable formula calculation during PDF conversion Aspose.Cells .NET | Standard vs Minimum PDF optimization Aspose.Cells | C# check file existence before PDF export | Save workbook as high‑resolution PDF using Aspose.Cells
// Developer Intent: Create a high‑quality PDF from an Excel workbook with calculated formulas using Aspose.Cells in C#.
// Use Cases: Generate print‑ready financial statements with crisp charts | Archive regulatory spreadsheets as searchable PDFs with exact calculations | Produce marketing brochures from Excel data with high‑resolution images | Deliver client reports that meet 300 DPI printing standards
// AI Prompts: Provide C# code that opens an XLSX file, verifies its presence, sets PdfSaveOptions to 300 DPI and JPEG quality 90, enables CalculateFormula, and saves as PDF using Aspose.Cells. | Explain how PdfOptimizationType.Standard influences file size and image quality in PDFs generated by Aspose.Cells. | Show how to handle missing input files and exceptions when converting Excel to PDF with Aspose.Cells. | Compare SetImageResample DPI values for different printing requirements in Aspose.Cells PDF export.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering; // For PdfOptimizationType enum

// Loads an XLSX file, applies PdfSaveOptions with 300 DPI image resampling, JPEG quality 90, standard optimization, and formula calculation, then saves the workbook as a PDF while handling missing files and runtime errors.
class PdfExportHighResolution
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Verify that the input workbook exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file \"{inputPath}\" was not found.");
                return;
            }

            // Load the existing workbook
            Workbook workbook = new Workbook(inputPath);

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Use standard optimization (high quality)
                OptimizationType = PdfOptimizationType.Standard,
                // Ensure formulas are calculated before saving
                CalculateFormula = true
            };

            // Set image resolution (300 DPI) and JPEG quality (0‑100). 90 gives good quality.
            pdfOptions.SetImageResample(300, 90);

            // Save the workbook as a PDF
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"PDF successfully saved to \"{outputPath}\".");
        }
        catch (Exception ex)
        {
            // Catch any unexpected errors and display a friendly message
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
