// Title: How to embed a Power Query M merge formula into an Excel workbook created with Aspose.Cells for .NET (API limitation and workarounds)
// AI Prompts: Generate C# code that uses Aspose.Cells to create a new workbook, saves it, and then adds a Power Query M merge script as a custom XML part. | Explain a step‑by‑step manual process for inserting a Power Query merge query into the saved Excel file after Aspose.Cells generation. | Provide a C# snippet that creates a placeholder worksheet named "PowerQuery" and writes a comment containing the M formula for later editing in Excel. | Show how to use Aspose.Cells CustomXmlPartCollection to embed a Power Query definition XML that references two external data sources.
// Common Searches: asp.net aspose.cells add power query merge query programmatically | why aspose.cells .net cannot create Power Query M formula in workbook | workaround to embed power query M script in excel file generated by aspose.cells | add custom xml part for power query in excel using c# aspose.cells | merge two external data sources with power query after creating workbook with aspose.cells
// Tags: aspose.cells custom xml part power query | c# add power query m script to excel workbook | power query merge formula embedding workaround | excel workbook generation with aspose.cells | manual power query addition after aspose.cells export

using System;
using Aspose.Cells;

// The example creates a new Workbook with Aspose.Cells for .NET, highlights that the library does not expose a Queries collection for adding Power Query M formulas directly, and saves the file. It also discusses possible work‑arounds such as inserting a custom XML part or adding a placeholder sheet for later manual insertion of a Power Query merge query.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (lifecycle rule: create)
            Workbook workbook = new Workbook();

            // NOTE: Aspose.Cells for .NET does not expose a direct API to add Power Query M formulas.
            // If Power Query support is required, it must be added manually in Excel after the file is generated.
            // The following line is omitted because the 'Queries' collection does not exist in the API:
            // workbook.Queries.Add("MergedData", powerQueryFormula.Trim());

            // Save the workbook (lifecycle rule: save)
            workbook.Save("MergedDataWorkbook.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
