// Title: Set Default External Connection String for an Aspose.Cells PivotTable (C#)
// Description: Demonstrates how to create a workbook, add sample data, build a PivotTable, retrieve its external data connections with GetSourceDataConnections, assign a default OLEDB connection string to the first ExternalConnection, and save the file using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# | PivotTable | ExternalConnection | ConnectionString | default data source | OLEDB | GetSourceDataConnections | Excel automation | programmatic pivot
// Common Searches: Aspose.Cells set default connection string for pivot table | GetSourceDataConnections example C# | Change external data source of a PivotTable with Aspose | Assign OLEDB connection string to PivotTable in .NET | Update PivotTable external connection programmatically
// Developer Intent: Configure a PivotTable’s external data connection to use a predefined default connection string via Aspose.Cells.
// Use Cases: Create a new workbook, add a PivotTable, and point its external connection to a shared Excel file using a standard OLEDB string. | Modify an existing workbook so all PivotTables reference a central data source before distribution. | Automate compliance by enforcing a company‑wide connection string on every PivotTable generated by an application.
// AI Prompts: Generate C# code that loops through all PivotTables in a workbook and sets each ExternalConnection.ConnectionString to a given default using Aspose.Cells. | Provide a robust example that creates a PivotTable, checks for existing external connections, and applies a Microsoft ACE OLEDB connection string, handling the case where no connections are present.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;
using Aspose.Cells.ExternalConnections;

// Demonstrates how to create a workbook, add sample data, build a PivotTable, retrieve its external data connections with GetSourceDataConnections, assign a default OLEDB connection string to the first ExternalConnection, and save the file using Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook wb = new Workbook();
            Worksheet ws = wb.Worksheets[0];

            // Populate sample data for the pivot table
            ws.Cells["A1"].PutValue("Category");
            ws.Cells["B1"].PutValue("Amount");
            ws.Cells["A2"].PutValue("Food");
            ws.Cells["B2"].PutValue(120);
            ws.Cells["A3"].PutValue("Travel");
            ws.Cells["B3"].PutValue(300);
            ws.Cells["A4"].PutValue("Food");
            ws.Cells["B4"].PutValue(80);

            // Add a pivot table based on the sample data
            int ptIndex = ws.PivotTables.Add("A1:B4", "D1", "SalesPivot");
            PivotTable pt = ws.PivotTables[ptIndex];
            pt.AddFieldToArea(PivotFieldType.Row, 0);   // Category as row field
            pt.AddFieldToArea(PivotFieldType.Data, 1);  // Amount as data field

            // Retrieve external data connections used by the pivot table
            ExternalConnection[] connections = pt.GetSourceDataConnections();

            // Ensure connections array is not null before accessing its members
            if (connections != null && connections.Length > 0)
            {
                // Configure the first connection with a default connection string
                // (Replace the string with the actual default you need)
                connections[0].ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=DefaultDataSource.xlsx;Persist Security Info=False;";
            }

            // Save the workbook with the configured pivot table
            wb.Save("PivotWithDefaultConnection.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
