// Title: Hide PivotTable wizard ribbon and field list toolbar in ODS output with Aspose.Cells for .NET
// AI Prompts: Generate C# code using Aspose.Cells that creates a pivot table and disables the PivotTable wizard ribbon and field list toolbar before saving as an ODS file. | Show the Aspose.Cells settings required to suppress all pivot‑table UI elements when exporting a workbook to OpenDocument Spreadsheet format.
// Common Searches: asp.net hide pivot table wizard ribbon in ods export using aspose.cells | disable pivot field list toolbar for open document spreadsheet generated by Aspose.Cells | minimal UI for pivot tables in ODS files with Aspose.Cells .NET | how to suppress pivot table UI elements when saving workbook as ODS | Aspose.Cells ODS export without pivot table toolbar
// Tags: aspose.cells hide pivot ribbon | aspose.cells suppress pivot UI | ods export minimal pivot interface | pivot table UI suppression asp.net | aspose.cells pivot configuration ods

using Aspose.Cells;
using Aspose.Cells.Pivot;

// The example creates a workbook, adds sample data, builds a pivot table, disables the PivotTable wizard ribbon and field list toolbar using EnableWizard, EnableFieldList, and HidePivotFieldList settings, and saves the result as an ODS file with a minimal user interface.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data for the pivot table
        sheet.Cells["A1"].PutValue("Category");
        sheet.Cells["B1"].PutValue("Product");
        sheet.Cells["C1"].PutValue("Sales");

        sheet.Cells["A2"].PutValue("Fruit");
        sheet.Cells["B2"].PutValue("Apple");
        sheet.Cells["C2"].PutValue(120);

        sheet.Cells["A3"].PutValue("Fruit");
        sheet.Cells["B3"].PutValue("Banana");
        sheet.Cells["C3"].PutValue(150);

        sheet.Cells["A4"].PutValue("Vegetable");
        sheet.Cells["B4"].PutValue("Carrot");
        sheet.Cells["C4"].PutValue(80);

        // Add a pivot table to the worksheet
        int pivotIndex = sheet.PivotTables.Add("A1:C4", "E1", "PivotTable1");
        PivotTable pivotTable = sheet.PivotTables[pivotIndex];

        // Configure the pivot table fields
        pivotTable.AddFieldToArea(PivotFieldType.Row, 0);   // Category
        pivotTable.AddFieldToArea(PivotFieldType.Row, 1);   // Product
        pivotTable.AddFieldToArea(PivotFieldType.Data, 2);  // Sales

        // Disable UI elements related to the pivot table
        pivotTable.EnableWizard = false;          // Hide the PivotTable wizard ribbon
        pivotTable.EnableFieldList = false;       // Hide the field list toolbar
        workbook.Settings.HidePivotFieldList = true; // Globally hide the pivot field list

        // Save the workbook as ODS with minimal UI for the pivot table
        workbook.Save("PivotTable_MinimalUI.ods", SaveFormat.Ods);
    }
}
