// Title: Enable row header captions in an Aspose.Cells PivotTable using C#
// AI Prompts: Create a PivotTable with Aspose.Cells, add a row field, set ShowRowHeaderCaption = true, and save the workbook as XLSX. | Use C# to turn on row header labels for a PivotTable generated by Aspose.Cells and export the file. | Configure an Aspose.Cells PivotTable to display row header captions and persist the changes in a .xlsx workbook.
// Common Searches: C# Aspose.Cells how to show row header captions in a pivot table | Enable ShowRowHeaderCaption property for Excel pivot tables with Aspose.Cells .NET | Aspose.Cells pivot table row header label not displaying | Set row header caption in generated Excel pivot using C# Aspose.Cells | Display row field captions in Aspose.Cells PivotTable example
// Tags: Aspose.Cells ShowRowHeaderCaption | C# pivot table row header caption | Enable row header labels Aspose.Cells | Excel pivot table row header visibility .NET | Aspose.Cells pivot table formatting C#

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsExamples
{
    // The example creates a workbook, populates sample data, adds a PivotTable with a row field, enables the ShowRowHeaderCaption property to display row header labels, and saves the result as PivotTable_ShowRowHeaderCaption.xlsx.
    public class EnableShowRowHeaderCaption
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data for the pivot table
                sheet.Cells["A1"].PutValue("Category");
                sheet.Cells["B1"].PutValue("Amount");
                sheet.Cells["A2"].PutValue("Fruit");
                sheet.Cells["B2"].PutValue(120);
                sheet.Cells["A3"].PutValue("Vegetable");
                sheet.Cells["B3"].PutValue(80);

                // Add a pivot table to the worksheet
                int pivotIndex = sheet.PivotTables.Add("A1:B3", "D5", "PivotTable1");
                PivotTable pivotTable = sheet.PivotTables[pivotIndex];

                // Configure pivot fields: Category as row, Amount as data
                pivotTable.AddFieldToArea(PivotFieldType.Row, 0);
                pivotTable.AddFieldToArea(PivotFieldType.Data, 1);

                // Enable the display of row header captions
                pivotTable.ShowRowHeaderCaption = true;

                // Save the workbook to a file
                workbook.Save("PivotTable_ShowRowHeaderCaption.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        // Entry point for the application
        public static void Main()
        {
            Run();
        }
    }
}
