// Title: Aspose.Cells C# – Enable ShowValuesRow on a PivotTable to Add a Separate Values Row
// Description: Demonstrates how to create a workbook with sample data, add a PivotTable, assign row and data fields, and set the PivotTable.ShowValuesRow property to true so the generated Excel file displays a distinct row that aggregates the values for clearer reporting.
// Keywords: Aspose.Cells ShowValuesRow | C# PivotTable ShowValuesRow | Aspose.Cells pivot table values row | Excel pivot table separate values row | .NET Aspose.Cells example | display aggregated values row | pivot table readability
// Common Searches: how to show a separate values row in Aspose.Cells pivot table | Aspose.Cells ShowValuesRow property C# example | add values row to Excel pivot table using Aspose | enable ShowValuesRow for PivotTable in .NET | Aspose.Cells pivot table layout options
// Developer Intent: Activate the ShowValuesRow flag on a PivotTable so Excel renders an extra row that summarizes data values.
// Use Cases: Financial dashboards where each category’s total appears in its own row for instant comparison. | Sales reports that need a clear, aggregated values row without expanding the pivot hierarchy. | Audit‑ready workbooks that display summed amounts in a dedicated row for compliance reviewers.
// AI Prompts: Generate C# code with Aspose.Cells that creates a PivotTable and sets ShowValuesRow to true. | Explain the visual effect of the ShowValuesRow property on an Excel pivot table generated by Aspose.Cells. | Show how to toggle ShowValuesRow on an existing PivotTable and re‑save the workbook.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsExamples
{
    // Demonstrates how to create a workbook with sample data, add a PivotTable, assign row and data fields, and set the PivotTable.ShowValuesRow property to true so the generated Excel file displays a distinct row that aggregates the values for clearer reporting.
    public class PivotTableShowValuesRowDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data
                Cells cells = sheet.Cells;
                cells["A1"].Value = "Category";
                cells["B1"].Value = "Amount";
                cells["A2"].Value = "Food";
                cells["B2"].Value = 120;
                cells["A3"].Value = "Food";
                cells["B3"].Value = 80;
                cells["A4"].Value = "Drink";
                cells["B4"].Value = 150;
                cells["A5"].Value = "Drink";
                cells["B5"].Value = 70;

                // Add a pivot table covering the data range
                int pivotIndex = sheet.PivotTables.Add("A1:B5", "D3", "PivotTable1");
                PivotTable pivotTable = sheet.PivotTables[pivotIndex];

                // Configure the pivot table: Category as row field, Amount as data field
                pivotTable.AddFieldToArea(PivotFieldType.Row, 0);   // Column 0 -> Category
                pivotTable.AddFieldToArea(PivotFieldType.Data, 1);  // Column 1 -> Amount

                // Enable the separate values row for better readability
                pivotTable.ShowValuesRow = true;

                // Save the workbook
                string outputPath = "PivotTableShowValuesRowDemo.xlsx";
                workbook.Save(outputPath, SaveFormat.Xlsx);
                Console.WriteLine($"Workbook saved to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        // Entry point for the application
        public static void Main(string[] args)
        {
            Run();
        }
    }
}
