// Title: Aspose.Cells C# – Enable ShowValuesRow to Add a Separate Values Row in a PivotTable
// Description: This example creates a workbook, fills cells A1:B5 with Category and Amount data, builds a PivotTable at D3, assigns Category as a row field and Amount as a data field, sets pivotTable.ShowValuesRow to true to generate a distinct values row, refreshes and calculates the pivot, and saves the file as PivotTableShowValuesRowDemo.xlsx.
// Keywords: Aspose.Cells ShowValuesRow | PivotTable ShowValuesRow C# | Aspose.Cells pivot table values row | C# Aspose.Cells PivotTable example | display separate values row Excel | .NET Excel pivot table readability
// Common Searches: How to add a values row to an Aspose.Cells pivot table in C# | Aspose.Cells ShowValuesRow property usage | Enable separate values row for PivotTable with Aspose.Cells | C# code sample for Aspose.Cells PivotTable ShowValuesRow | Aspose.Cells pivot table subtotal row example
// Developer Intent: Activate the ShowValuesRow property on a PivotTable to insert a dedicated row that aggregates the data values.
// Use Cases: Generate financial reports where each category’s total appears in its own values row for quick summary. | Create sales dashboards that separate subtotals for product groups, improving readability for end users. | Export analytical data to Excel with a clear values row that highlights aggregated figures in the pivot table.
// AI Prompts: Write C# code using Aspose.Cells to build a pivot table and enable ShowValuesRow for a dataset with categories and amounts. | Explain the effect of the ShowValuesRow property on the layout of a pivot table generated by Aspose.Cells. | Provide step‑by‑step instructions to add a values row to an existing Aspose.Cells PivotTable and refresh the data.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsExamples
{
    // This example creates a workbook, fills cells A1:B5 with Category and Amount data, builds a PivotTable at D3, assigns Category as a row field and Amount as a data field, sets pivotTable.ShowValuesRow to true to generate a distinct values row, refreshes and calculates the pivot, and saves the file as PivotTableShowValuesRowDemo.xlsx.
    public class PivotTableShowValuesRowDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data for the pivot table
                Cells cells = sheet.Cells;
                cells["A1"].Value = "Category";
                cells["B1"].Value = "Amount";
                cells["A2"].Value = "Food";
                cells["B2"].Value = 120;
                cells["A3"].Value = "Food";
                cells["B3"].Value = 80;
                cells["A4"].Value = "Beverage";
                cells["B4"].Value = 150;
                cells["A5"].Value = "Beverage";
                cells["B5"].Value = 70;

                // Add a pivot table based on the data range
                int pivotIndex = sheet.PivotTables.Add("A1:B5", "D3", "PivotTable1");
                PivotTable pivotTable = sheet.PivotTables[pivotIndex];

                // Configure the pivot table: Category as row field, Amount as data field
                pivotTable.AddFieldToArea(PivotFieldType.Row, 0);   // Column 0 -> Category
                pivotTable.AddFieldToArea(PivotFieldType.Data, 1);  // Column 1 -> Amount

                // Enable the separate values row for better readability
                pivotTable.ShowValuesRow = true;

                // Refresh pivot cache and calculate the pivot data
                pivotTable.RefreshData();
                pivotTable.CalculateData();

                // Save the workbook to a file
                workbook.Save("PivotTableShowValuesRowDemo.xlsx", SaveFormat.Xlsx);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }

    // Entry point for the application
    public class Program
    {
        public static void Main(string[] args)
        {
            PivotTableShowValuesRowDemo.Run();
        }
    }
}
