// Title: C# – Enable Drill‑Down and Expand/Collapse Buttons in an Aspose.Cells Pivot Table
// Description: This example shows how to create a workbook with sample sales data, add a pivot table on range A1:C5, assign Category, SubCategory and Sales fields, activate drill‑down (EnableDrilldown = true) and display expand/collapse icons (ShowDrill = true), then refresh, calculate, and save the file as PivotTableDrilldownDemo.xlsx.
// Keywords: Aspose.Cells C# pivot table drill down | EnableDrilldown Aspose.Cells | ShowDrill Aspose.Cells | programmatic pivot table refresh | Excel pivot expand collapse buttons | Aspose.Cells .NET example | pivot table underlying records
// Common Searches: how to enable drill down in Aspose.Cells pivot table | show expand collapse icons in Aspose.Cells pivot | Aspose.Cells C# refresh pivot after enabling drilldown | sample code for drill‑down pivot table Aspose.Cells | Aspose.Cells pivot table double click to view source rows
// Developer Intent: Add a pivot table to a workbook and turn on drill‑down with visible expand/collapse controls.
// Use Cases: Provide a sales summary where users can double‑click a cell to see the original transactions. | Display interactive expand/collapse buttons so analysts can explore categories without leaving Excel. | Ensure pivot calculations are up‑to‑date after enabling drill‑down before distributing the workbook.
// AI Prompts: Write C# code using Aspose.Cells to build a pivot table from a data range and enable drill‑down with ShowDrill set to true. | Show how to refresh and recalculate an Aspose.Cells pivot table after activating EnableDrilldown. | Explain how to customize drill‑down behavior, such as handling double‑click events, in a workbook generated by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsDrilldownDemo
{
    // This example shows how to create a workbook with sample sales data, add a pivot table on range A1:C5, assign Category, SubCategory and Sales fields, activate drill‑down (EnableDrilldown = true) and display expand/collapse icons (ShowDrill = true), then refresh, calculate, and save the file as PivotTableDrilldownDemo.xlsx.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Get the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the pivot table
            sheet.Cells["A1"].Value = "Category";
            sheet.Cells["B1"].Value = "SubCategory";
            sheet.Cells["C1"].Value = "Sales";

            sheet.Cells["A2"].Value = "Electronics";
            sheet.Cells["B2"].Value = "Phones";
            sheet.Cells["C2"].Value = 1200;

            sheet.Cells["A3"].Value = "Electronics";
            sheet.Cells["B3"].Value = "Laptops";
            sheet.Cells["C3"].Value = 2500;

            sheet.Cells["A4"].Value = "Furniture";
            sheet.Cells["B4"].Value = "Chairs";
            sheet.Cells["C4"].Value = 800;

            sheet.Cells["A5"].Value = "Furniture";
            sheet.Cells["B5"].Value = "Tables";
            sheet.Cells["C5"].Value = 1500;

            // Add a pivot table based on the data range
            int pivotIndex = sheet.PivotTables.Add("A1:C5", "E3", "SalesPivot");
            PivotTable pivot = sheet.PivotTables[pivotIndex];

            // Configure the pivot table fields
            pivot.AddFieldToArea(PivotFieldType.Row, "Category");      // Row field
            pivot.AddFieldToArea(PivotFieldType.Column, "SubCategory"); // Column field
            pivot.AddFieldToArea(PivotFieldType.Data, "Sales");       // Data field

            // Enable drill‑down functionality and show drill indicators
            pivot.EnableDrilldown = true; // Allows users to double‑click a cell to see underlying records
            pivot.ShowDrill = true;       // Displays expand/collapse buttons in the UI

            // Refresh and calculate the pivot table data
            pivot.RefreshData();
            pivot.CalculateData();

            // Save the workbook to a file
            workbook.Save("PivotTableDrilldownDemo.xlsx");
        }
    }
}
