// Title: C# – ShowDrill and EnableDrilldown on Aspose.Cells PivotTable to display expand/collapse buttons
// Description: This example creates a new Workbook, adds sample data, builds a PivotTable on range A1:B5, assigns "Category" to rows and "Value" to data, then enables drill‑down by setting EnableDrilldown = true and ShowDrill = true. The pivot cache is refreshed, data is calculated, and the file is saved as PivotTableShowDrillDemo.xlsx.
// Keywords: Aspose.Cells C# | .NET PivotTable example | ShowDrill property | EnableDrilldown property | expand collapse buttons | drill down buttons Excel | pivot cache refresh | Aspose.Cells sample code | GitHub Aspose.Cells PivotTable | interactive PivotTable
// Common Searches: Aspose.Cells show drill buttons | Enable drilldown in PivotTable C# | ShowDrill property Aspose.Cells .NET | How to add expand collapse icons to PivotTable | Refresh pivot cache after enabling drilldown | Aspose.Cells PivotTable interactive example
// Developer Intent: Activate the expand/collapse (drill‑down) buttons on a PivotTable so end users can drill into aggregated rows.
// Use Cases: Generate Excel reports with interactive PivotTables that let users expand summary rows directly. | Automate workbook creation where drill‑down functionality is required for hierarchical data analysis. | Integrate Aspose.Cells PivotTable settings into a .NET reporting service that outputs files with ready‑to‑use drill‑down controls.
// AI Prompts: Write C# code using Aspose.Cells to create a PivotTable and enable ShowDrill and EnableDrilldown. | Explain the effect of ShowDrill and EnableDrilldown on the user interface of an Excel PivotTable generated by Aspose.Cells. | Provide step‑by‑step instructions to refresh the pivot cache after turning on drill‑down in Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsExamples
{
    // This example creates a new Workbook, adds sample data, builds a PivotTable on range A1:B5, assigns "Category" to rows and "Value" to data, then enables drill‑down by setting EnableDrilldown = true and ShowDrill = true. The pivot cache is refreshed, data is calculated, and the file is saved as PivotTableShowDrillDemo.xlsx.
    public class PivotTableShowDrillDemo
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Get the first worksheet and name it "Data"
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Name = "Data";

                // Populate sample data for the pivot table
                sheet.Cells["A1"].Value = "Category";
                sheet.Cells["B1"].Value = "Value";
                sheet.Cells["A2"].Value = "A";
                sheet.Cells["B2"].Value = 100;
                sheet.Cells["A3"].Value = "B";
                sheet.Cells["B3"].Value = 200;
                sheet.Cells["A4"].Value = "A";
                sheet.Cells["B4"].Value = 150;
                sheet.Cells["A5"].Value = "B";
                sheet.Cells["B5"].Value = 250;

                // Add a pivot table based on the data range A1:B5, place it at D3
                int pivotIndex = sheet.PivotTables.Add("A1:B5", "D3", "PivotTable1");
                PivotTable pivotTable = sheet.PivotTables[pivotIndex];

                // Configure the pivot table fields
                pivotTable.AddFieldToArea(PivotFieldType.Row, "Category");
                pivotTable.AddFieldToArea(PivotFieldType.Data, "Value");

                // Enable drilldown functionality and show expand/collapse buttons
                pivotTable.EnableDrilldown = true; // Allows users to drill down into aggregated cells
                pivotTable.ShowDrill = true;       // Displays the expand/collapse (drill) buttons

                // Refresh the pivot cache and calculate the pivot data
                pivotTable.RefreshData();   // Correct API to refresh pivot cache
                pivotTable.CalculateData();

                // Save the workbook
                string outputPath = "PivotTableShowDrillDemo.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        // Entry point for the application
        public static void Main(string[] args)
        {
            Run();
        }
    }
}
