// Title: Log the row count of a PivotTable after RefreshData using Aspose.Cells in C#
// AI Prompts: Write C# code that loads an Excel workbook with Aspose.Cells, refreshes the first PivotTable, and writes the resulting TableRange2 row count to a log file with a timestamp. | Create a reusable C# method that takes a PivotTable object, calls RefreshData and CalculateData, and returns the number of rows occupied by the PivotTable. | Generate a console application that verifies a PivotTable exists, refreshes it, captures the row count, and appends the count to a diagnostics log for performance monitoring.
// Common Searches: Aspose.Cells C# get row count of PivotTable after RefreshData | how to log pivot table size after refresh using Aspose.Cells .NET | C# Aspose.Cells TableRange2 row count for performance monitoring | retrieve number of rows generated by a refreshed PivotTable in Aspose.Cells | diagnose pivot table refresh performance by counting rows in C#
// Tags: Aspose.Cells RefreshData PivotTable row count | C# TableRange2 row measurement | PivotTable performance logging Aspose.Cells | Excel workbook diagnostics with Aspose.Cells | calculate PivotTable size after refresh C#

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Pivot;

// The example loads an existing Excel file, checks for a PivotTable on the first worksheet, refreshes and recalculates the PivotTable, determines the number of rows in its full occupied range via TableRange2, logs the row count for diagnostics, and saves the workbook, handling missing files and exceptions.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.xlsx";

            // Verify that the input file exists to avoid FileNotFoundException
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Error: The file '{inputPath}' was not found.");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputPath);

            // Access the first worksheet (adjust index if needed)
            Worksheet worksheet = workbook.Worksheets[0];

            // Ensure the worksheet contains at least one PivotTable
            if (worksheet.PivotTables.Count == 0)
            {
                Console.WriteLine("Error: No PivotTables found on the first worksheet.");
                return;
            }

            // Get the first PivotTable on the worksheet
            PivotTable pivotTable = worksheet.PivotTables[0];

            // Refresh the PivotTable data (using the available API)
            pivotTable.RefreshData();

            // Recalculate the PivotTable
            pivotTable.CalculateData();

            // Determine the number of rows generated by the PivotTable
            // TableRange2 represents the full range occupied by the PivotTable.
            CellArea tableRange = pivotTable.TableRange2;
            int rowCount = tableRange.EndRow - tableRange.StartRow + 1;

            Console.WriteLine($"PivotTable rows after refresh: {rowCount}");

            // Save the workbook with the updated PivotTable
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            // Catch any unexpected exceptions and display a friendly message
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
