// Title: Programmatically expand all collapsed rows and columns in an Aspose.Cells PivotTable using C# (HideDetail or ExpandAll)
// AI Prompts: Write C# code that iterates through a PivotTable's RowFields and ColumnFields and calls HideDetail(false) to fully expand the pivot. | Show how to invoke the Aspose.Cells PivotTable.ExpandAll() method (when available) to reveal every item and then save the workbook. | Create a reusable C# method that expands all collapsed items in a PivotTable, refreshes and recalculates the data, and returns the updated Workbook. | Demonstrate enabling drill buttons, expanding all fields, and verifying the expanded state in an Aspose.Cells workbook.
// Common Searches: C# Aspose.Cells expand all items in a pivot table programmatically | How to uncollapse rows and columns in an Aspose.Cells PivotTable using HideDetail | Aspose.Cells PivotTable ExpandAll method example in .NET | Refresh and recalculate pivot after expanding fields with Aspose.Cells | Show all drill‑down items in a pivot table generated by Aspose.Cells
// Tags: Aspose.Cells PivotTable ExpandAll method | HideDetail false for PivotField C# | programmatic pivot table expansion Aspose.Cells | refresh pivot after expanding items .NET | save expanded pivot workbook Aspose.Cells | enable drill buttons Aspose.Cells pivot

using System;
using Aspose.Cells;
using Aspose.Cells.Pivot;

namespace AsposeCellsPivotExpandAllDemo
{
    // The example creates a workbook with sample data, adds a PivotTable, and then expands every collapsed row and column by setting each PivotField's HideDetail to false (or calling PivotTable.ExpandAll when supported). After expanding, the pivot is refreshed and recalculated, and the workbook is saved as PivotTableExpanded.xlsx.
    public class Program
    {
        public static void Main()
        {
            // Create a new workbook and add sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "Data";

            // Sample data for the pivot table
            sheet.Cells["A1"].PutValue("Category");
            sheet.Cells["B1"].PutValue("Product");
            sheet.Cells["C1"].PutValue("Sales");

            sheet.Cells["A2"].PutValue("Electronics");
            sheet.Cells["B2"].PutValue("Laptop");
            sheet.Cells["C2"].PutValue(1200);

            sheet.Cells["A3"].PutValue("Electronics");
            sheet.Cells["B3"].PutValue("Phone");
            sheet.Cells["C3"].PutValue(800);

            sheet.Cells["A4"].PutValue("Furniture");
            sheet.Cells["B4"].PutValue("Chair");
            sheet.Cells["C4"].PutValue(150);

            sheet.Cells["A5"].PutValue("Furniture");
            sheet.Cells["B5"].PutValue("Table");
            sheet.Cells["C5"].PutValue(300);

            // Add a pivot table on the same worksheet
            int pivotIndex = sheet.PivotTables.Add("A1:C5", "E3", "PivotTable1");
            PivotTable pivotTable = sheet.PivotTables[pivotIndex];

            // Configure the pivot table
            pivotTable.AddFieldToArea(PivotFieldType.Row, "Category");
            pivotTable.AddFieldToArea(PivotFieldType.Row, "Product");
            pivotTable.AddFieldToArea(PivotFieldType.Data, "Sales");

            // Ensure drill buttons are visible (optional, helps visual verification)
            pivotTable.ShowDrill = true;
            pivotTable.EnableDrilldown = true;

            // Refresh and calculate the pivot table before expanding
            pivotTable.RefreshData();
            pivotTable.CalculateData();

            // -------- Expand all collapsed items ----------
            // Aspose.Cells provides the HideDetail method on PivotField.
            // Setting HideDetail to false expands the field.
            // Iterate through all row and column fields and expand them.
            foreach (PivotField rowField in pivotTable.RowFields)
            {
                rowField.HideDetail(false); // expand row field
            }

            foreach (PivotField columnField in pivotTable.ColumnFields)
            {
                columnField.HideDetail(false); // expand column field
            }

            // If a direct ExpandAll method exists on PivotTable, it can be called as:
            // pivotTable.ExpandAll();
            // The above loop achieves the same effect when ExpandAll is not available.

            // Refresh again to reflect the expanded state
            pivotTable.RefreshData();
            pivotTable.CalculateData();

            // Save the workbook with the expanded pivot table
            workbook.Save("PivotTableExpanded.xlsx");
        }
    }
}
