// Title: Aspose.Cells C# – Display calculation errors in a PivotTable with DisplayErrorString
// Description: A concise C# example that builds a workbook, inserts sample data, creates a PivotTable, and enables the DisplayErrorString (or ShowErrorValues) flag so that any calculation errors (e.g., #DIV/0!) are shown directly in the pivot cells. Includes optional custom error text before recalculating and saving the file.
// Keywords: Aspose.Cells | C# | .NET | PivotTable | DisplayErrorString | ShowErrorValues | calculation error | error values | Excel automation | custom error string
// Common Searches: Aspose.Cells show pivot table errors | DisplayErrorString property C# | ShowErrorValues Aspose.Cells example | pivot table #DIV/0! Aspose | how to display errors in Aspose pivot table
// Developer Intent: Enable a PivotTable to reveal calculation failures directly within its cells.
// Use Cases: Financial dashboards where division‑by‑zero or invalid formulas must be visible to auditors. | Automated reporting that highlights missing or malformed data with a custom error label. | Data‑validation tools that rely on error visibility to prompt users for correction before publishing. | Compliance reports that require explicit display of calculation issues for regulatory review.
// AI Prompts: Generate C# code using Aspose.Cells to create a PivotTable and set DisplayErrorString to true with a custom error string. | Explain the difference between DisplayErrorString and ShowErrorValues in Aspose.Cells and when each should be used. | Provide a step‑by‑step tutorial for handling #DIV/0! errors in a PivotTable generated by Aspose.Cells. | Write a unit test that verifies error values appear in the pivot cells after enabling DisplayErrorString.

using Aspose.Cells;
using Aspose.Cells.Pivot;

// A concise C# example that builds a workbook, inserts sample data, creates a PivotTable, and enables the DisplayErrorString (or ShowErrorValues) flag so that any calculation errors (e.g., #DIV/0!) are shown directly in the pivot cells. Includes optional custom error text before recalculating and saving the file.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // Populate sample data for the pivot table
        sheet.Cells["A1"].Value = "Category";
        sheet.Cells["B1"].Value = "Amount";
        sheet.Cells["A2"].Value = "A";
        sheet.Cells["B2"].Value = 100;
        sheet.Cells["A3"].Value = "B";
        sheet.Cells["B3"].Value = 200;
        sheet.Cells["A4"].Value = "A";
        sheet.Cells["B4"].Value = 150;
        sheet.Cells["A5"].Value = "B";
        sheet.Cells["B5"].Value = 250;

        // Add a pivot table covering the data range and place it at D2
        int pivotIndex = sheet.PivotTables.Add("A1:B5", "D2", "PivotTable1");
        PivotTable pivotTable = sheet.PivotTables[pivotIndex];

        // Add fields to the pivot table (Category as row, Amount as data)
        pivotTable.AddFieldToArea(PivotFieldType.Row, 0);
        pivotTable.AddFieldToArea(PivotFieldType.Data, 1);

        // Enable display of calculation errors directly within pivot cells
        pivotTable.DisplayErrorString = true;          // Show errors
        pivotTable.ErrorString = "#ERROR";             // Custom error text (optional)

        // Recalculate the pivot table to apply the settings
        pivotTable.CalculateData();

        // Save the workbook
        workbook.Save("PivotShowErrorValues.xlsx");
    }
}
