// Title: Set built‑in Excel document properties and export to PDF with embedded metadata using Aspose.Cells in C#
// AI Prompts: Create a new Workbook, assign Title, Subject, Author, Keywords, and Comments built‑in properties, then save it as a PDF. | Demonstrate assigning built‑in properties to a workbook and generating a PDF that contains those properties in C#. | Add sample data to the first worksheet and export the workbook to PDF while preserving the built‑in properties.
// Common Searches: C# Aspose.Cells set workbook built‑in properties before saving as PDF | How to embed Excel metadata into PDF using Aspose.Cells | Saving an Aspose.Cells workbook to PDF with title and author metadata | Add custom document properties to Excel file and export to PDF in C#
// Tags: Aspose.Cells configure built‑in document properties | PDF export with embedded document properties | C# generate PDF from Excel with metadata | Workbook.BuiltInDocumentProperties usage | SaveFormat.Pdf preserving metadata

using System;
using Aspose.Cells;

// The example creates a new Workbook, sets built‑in document properties (Title, Subject, Author, Keywords, Comments), optionally adds sample data, and saves the file as a PDF where the metadata is automatically embedded.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new empty workbook with a default worksheet
            Workbook workbook = new Workbook();

            // Set built‑in document properties (metadata) – use the Value property of each BuiltInDocumentProperty
            workbook.BuiltInDocumentProperties["Title"].Value = "Quarterly Sales Report";
            workbook.BuiltInDocumentProperties["Subject"].Value = "Sales Data Q1";
            workbook.BuiltInDocumentProperties["Author"].Value = "John Doe";
            workbook.BuiltInDocumentProperties["Keywords"].Value = "Sales,Quarterly,Report";
            workbook.BuiltInDocumentProperties["Comments"].Value = "Generated by Aspose.Cells";

            // Add sample data to the first worksheet (optional)
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Data");
            sheet.Cells["A2"].PutValue(12345);

            // Save the workbook as PDF; the built‑in properties are embedded automatically
            workbook.Save("ReportWithMetadata.pdf", SaveFormat.Pdf);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
