using System;
using Aspose.Cells;
using Aspose.Cells.Metadata;
using Aspose.Cells.Rendering;

class EmbedMetadataToPdf
{
    static void Main()
    {
        // Step 1: Create a simple workbook and save it as XLSX (required for metadata manipulation)
        string xlsxPath = "temp.xlsx";
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Sample data for PDF export");
        workbook.Save(xlsxPath); // lifecycle: create -> save

        // Step 2: Load workbook metadata, adjust built‑in and custom properties, then save metadata
        MetadataOptions metaOptions = new MetadataOptions(MetadataType.DocumentProperties);
        WorkbookMetadata metadata = new WorkbookMetadata(xlsxPath, metaOptions); // lifecycle: create (load)

        // Adjust built‑in document properties
        metadata.BuiltInDocumentProperties.Author = "Aspose Developer";
        metadata.BuiltInDocumentProperties.Title = "Metadata Demo PDF";
        metadata.BuiltInDocumentProperties.Subject = "Embedding metadata in PDF";
        metadata.BuiltInDocumentProperties.Company = "Aspose Ltd.";
        metadata.BuiltInDocumentProperties.Comments = "Generated by Aspose.Cells";

        // Add a custom document property
        metadata.CustomDocumentProperties.Add("Project", "MetadataEmbeddingDemo");

        // Save the modified metadata back to the same XLSX file
        metadata.Save(xlsxPath); // lifecycle: save

        // Step 3: Load the workbook again (now containing updated metadata) and save as PDF
        Workbook workbookForPdf = new Workbook(xlsxPath);
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Export custom document properties to the PDF file
        pdfOptions.CustomPropertiesExport = PdfCustomPropertiesExport.Standard;

        // Save the workbook as PDF with the specified options (metadata will be embedded)
        workbookForPdf.Save("output.pdf", pdfOptions); // lifecycle: save
    }
}