using System;
using Aspose.Cells;
using Aspose.Cells.Properties;

class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Register a warning callback to capture any warnings
        workbook.Settings.WarningCallback = new MetadataWarningHandler();

        // Attempt to modify application metadata (NameOfApplication)
        // For the purpose of this example we treat this property as immutable
        try
        {
            workbook.BuiltInDocumentProperties.NameOfApplication = "MyCustomApp";
        }
        catch (Exception ex)
        {
            // Log any exception that occurs during the modification attempt
            Console.WriteLine("Exception while modifying application metadata: " + ex.Message);
        }

        // Save the workbook using the standard save method
        workbook.Save("Output.xlsx");
    }
}

// Implements IWarningCallback to log warnings generated by Aspose.Cells
class MetadataWarningHandler : IWarningCallback
{
    public void Warning(WarningInfo warningInfo)
    {
        // Log the warning type and any associated error object
        Console.WriteLine($"Warning triggered: {warningInfo.WarningType}");
        if (warningInfo.ErrorObject != null)
        {
            Console.WriteLine($"Error Object: {warningInfo.ErrorObject}");
        }
    }
}