// Title: Convert an Excel workbook to PDF without embedding external linked images using Aspose.Cells for .NET
// AI Prompts: Write C# code that loads an Excel file and saves it as a PDF, disabling attachment embedding to keep linked images out of the output. | Show how to configure Aspose.Cells PdfSaveOptions to skip blank pages and reduce the resulting PDF size while preventing OLE attachment inclusion.
// Common Searches: Aspose.Cells .NET export Excel to PDF without embedding linked pictures | C# save workbook as PDF excluding external images using PdfSaveOptions | How to reduce PDF size when converting Excel with Aspose.Cells by disabling attachment embedding | PdfSaveOptions EmbedAttachments false example for Excel to PDF conversion | Ignore blank pages in PDF output generated by Aspose.Cells C#
// Tags: Aspose.Cells PdfSaveOptions embedattachments false | Excel to PDF conversion without linked images | minimize PDF size Aspose.Cells C# | ignore blank pages Aspose.Cells PDF export | disable OLE attachment embedding Aspose.Cells

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering; // Required for ImageOrPrintOptions if needed

namespace WorkbookToPdfExample
{
    // The example loads or creates an Excel workbook, configures PdfSaveOptions with EmbedAttachments set to false and PrintingPageType set to IgnoreBlank, and saves the workbook as a PDF. This prevents external linked images from being embedded and reduces the final PDF file size.
    class Program
    {
        static void Main(string[] args)
        {
            // Initialize a new workbook (or load an existing one)
            // Example: load from an existing file
            // Workbook workbook = new Workbook("input.xlsx");
            // For demonstration, we create a workbook with sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Sample Data");
            sheet.Cells["B1"].PutValue(123);
            sheet.Cells["A2"].PutValue("Another Row");
            sheet.Cells["B2"].PutValue(456);

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Ensure that external linked images (OLE attachments) are NOT embedded.
            // The default value is false, but we set it explicitly for clarity.
            pdfOptions.EmbedAttachments = false;

            // Optional: reduce PDF size by ignoring blank pages and styles
            pdfOptions.PrintingPageType = PrintingPageType.IgnoreBlank;

            // Save the workbook as PDF using the configured options
            string outputPath = "output.pdf";
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"Workbook successfully saved to PDF at: {outputPath}");
        }
    }
}
