// Title: C# – Convert Aspose.Cells Workbook to PDF with Custom Header & Footer
// Description: Demonstrates how to add left, center, and right sections to page headers and footers in an Aspose.Cells workbook, enable document‑structure export, and save the workbook as a PDF where the header/footer appears on every page.
// Keywords: Aspose.Cells PDF header footer C# | set page header Aspose.Cells | set page footer Aspose.Cells | Workbook to PDF with header | Workbook to PDF with footer | ExportDocumentStructure PdfSaveOptions | Excel to PDF custom header | Excel to PDF custom footer
// Common Searches: Aspose.Cells add header and footer before PDF export | C# set left center right header in Excel workbook | C# add page numbers and date to PDF generated by Aspose.Cells | How to enable document structure in Aspose.Cells PDF output | Save Excel as PDF with custom footer using Aspose.Cells
// Developer Intent: Add personalized header and footer content to each page of a PDF created from an Aspose.Cells workbook.
// Use Cases: Generate a sales report PDF that shows company name, report title, and date in the header and page numbers, confidentiality note, and time in the footer. | Create an invoice PDF where the header contains the vendor logo and invoice number while the footer displays page numbers and generation timestamp. | Produce an accessible PDF with document‑structure metadata for compliance reporting, ensuring consistent header/footer across all pages.
// AI Prompts: Provide C# code to set left, center, and right sections of a header and footer in Aspose.Cells before exporting to PDF. | Show how to add page numbers, current date, and custom text to the footer of a PDF generated from an Aspose.Cells workbook. | Explain how to enable ExportDocumentStructure in PdfSaveOptions to improve accessibility when converting an Excel workbook to PDF.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsPdfWithHeaderFooter
{
    // Demonstrates how to add left, center, and right sections to page headers and footers in an Aspose.Cells workbook, enable document‑structure export, and save the workbook as a PDF where the header/footer appears on every page.
    class Program
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Item");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apples");
            sheet.Cells["B2"].PutValue(120);
            sheet.Cells["A3"].PutValue("Bananas");
            sheet.Cells["B3"].PutValue(85);
            sheet.Cells["A4"].PutValue("Cherries");
            sheet.Cells["B4"].PutValue(60);

            // Set custom header (left, center, right sections)
            // Left: Company name, Center: Report title, Right: Current date
            sheet.PageSetup.SetHeader(0, "My Company");
            sheet.PageSetup.SetHeader(1, "Sales Report");
            sheet.PageSetup.SetHeader(2, "&D"); // Date

            // Set custom footer (left, center, right sections)
            // Left: Page number, Center: Confidential note, Right: Current time
            sheet.PageSetup.SetFooter(0, "Page &P of &N");
            sheet.PageSetup.SetFooter(1, "Confidential");
            sheet.PageSetup.SetFooter(2, "&T"); // Time

            // Configure PDF save options (optional)
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Preserve document structure in the PDF (helps with accessibility)
                ExportDocumentStructure = true
            };

            // Save the workbook as PDF with the defined header/footer
            string outputPath = "ReportWithHeaderFooter.pdf";
            workbook.Save(outputPath, pdfOptions);

            Console.WriteLine($"Workbook successfully saved to PDF: {outputPath}");
        }
    }
}
