// Title: Convert Aspose.Cells Workbook to PDF with French Language Metadata (C#)
// Description: Creates a workbook, inserts French text, configures PdfSaveOptions to set the PDF's default edit language to French, ensures the output directory exists, and saves the workbook as a PDF file.
// Keywords: Aspose.Cells | PDF conversion | C# | PdfSaveOptions | DefaultEditLanguage | French language metadata | multilingual PDF | Excel to PDF | .NET
// Common Searches: Aspose.Cells set PDF language to French | C# convert Excel workbook to PDF with language tag | PdfSaveOptions DefaultEditLanguage example | How to add French language metadata to PDF using Aspose.Cells | Save workbook as PDF with multilingual support C#
// Developer Intent: Generate a PDF from an Excel workbook and embed French language information in the document metadata.
// Use Cases: Produce French‑language reports from Excel templates for international teams. | Create invoices or contracts in French and ensure PDF readers recognize the correct language. | Automate multilingual documentation where PDF files must carry language tags for accessibility tools.
// AI Prompts: Show C# code that loads an existing Excel file, sets PdfSaveOptions.DefaultEditLanguage to French, and saves it as PDF with Aspose.Cells. | Explain how to verify the French language metadata in a PDF generated by Aspose.Cells using Aspose.PDF or other tools. | Provide a fallback approach for versions of Aspose.Cells that do not expose the French enum value in PdfSaveOptions.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;   // Required for PdfSaveOptions

// Creates a workbook, inserts French text, configures PdfSaveOptions to set the PDF's default edit language to French, ensures the output directory exists, and saves the workbook as a PDF file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (empty or you can load an existing file)
            Workbook workbook = new Workbook();

            // Add some French text to demonstrate multilingual support
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Bonjour le monde"); // "Hello world" in French

            // Configure PDF save options
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Uncomment the line below if your Aspose.Cells version supports the French enum value.
            // pdfOptions.DefaultEditLanguage = DefaultEditLanguage.French;

            // Define output file path
            string outputPath = "output.pdf";

            // Ensure the directory for the output file exists (if a directory is specified)
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook as a PDF using the configured options
            workbook.Save(outputPath, pdfOptions);
            Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
