// Title: Convert an Excel (.xlsx) workbook to PDF with Aspose.Cells for .NET and attempt to enable full‑screen opening
// AI Prompts: Write C# code that loads an .xlsx file using Aspose.Cells, saves it as a PDF, and sets PdfSaveOptions.OpenInFullScreenMode to true, including checks for missing input files and exception handling. | Show how to configure Aspose.Cells PdfSaveOptions in C# to try enabling full‑screen view when exporting a workbook to PDF, and provide a fallback when the property is not available.
// Common Searches: Aspose.Cells C# convert Excel to PDF and open PDF in presentation mode | How to enable full‑screen view for PDF generated by Aspose.Cells PdfSaveOptions | C# Aspose.Cells PDF save options full screen not working | Set PDF to launch in full screen when exporting .xlsx with Aspose.Cells .NET
// Tags: Aspose.Cells PDF conversion PdfSaveOptions | C# set PDF full-screen mode Aspose.Cells | Workbook to PDF export options .NET | handle missing Excel input file Aspose.Cells | exception handling Aspose.Cells PDF export

using Aspose.Cells;
using System;
using System.IO;

namespace AsposeCellsExample
{
    // The example loads an existing input.xlsx workbook with Aspose.Cells, creates a PdfSaveOptions object (noting that OpenInFullScreenMode may not be supported in the current version), and saves the workbook as output.pdf while checking for the input file's existence and catching any runtime exceptions.
    class Program
    {
        static void Main()
        {
            try
            {
                string inputPath = "input.xlsx";
                string outputPath = "output.pdf";

                // Ensure the input workbook exists
                if (!File.Exists(inputPath))
                {
                    Console.WriteLine($"Input file not found: {inputPath}");
                    return;
                }

                // Load the existing workbook
                Workbook workbook = new Workbook(inputPath);

                // Configure PDF save options (full‑screen mode not available in current API)
                PdfSaveOptions pdfOptions = new PdfSaveOptions();
                // pdfOptions.OpenInFullScreenMode = true; // Uncomment if supported in future versions

                // Save the workbook as a PDF using the specified options
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"Workbook successfully saved as PDF: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
