// Title: C# – Convert Aspose.Cells Workbook to CSV and GZIP‑compress the output
// Description: Demonstrates how to create an Aspose.Cells Workbook, populate it, save it directly to a MemoryStream in CSV format, and then write the CSV data to a GZIP file using .NET GZipStream with optimal compression. Includes proper stream handling and exception management.
// Keywords: Aspose.Cells CSV export C# | C# GZIP compression | SaveFormat.Csv Aspose | MemoryStream to GZipStream | Excel to gzipped CSV .NET | Aspose.Cells workbook to CSV | C# file compression example
// Common Searches: Aspose.Cells save workbook as CSV and gzip in C# | C# code to export Excel to gzipped CSV | How to compress CSV generated by Aspose.Cells | Convert Excel to CSV then GZIP using .NET | Aspose.Cells CSV compression example
// Developer Intent: Export an Aspose.Cells workbook to CSV format and immediately compress the CSV into a GZIP archive using C#.
// Use Cases: Deliver lightweight CSV reports over HTTP or FTP. | Archive Excel data with reduced storage footprint. | Stream CSV output directly to a compressed file to avoid temporary uncompressed files.
// AI Prompts: Generate C# code that uses Aspose.Cells to save a workbook as CSV and compress it with GZipStream, including error handling. | Show how to loop through all worksheets and create separate gzipped CSV files for each using Aspose.Cells. | Explain how to modify the sample to write the gzipped CSV to a MemoryStream for further processing or uploading.

using System;
using System.IO;
using System.IO.Compression;
using Aspose.Cells;

namespace AsposeCellsExamples
{
    // Demonstrates how to create an Aspose.Cells Workbook, populate it, save it directly to a MemoryStream in CSV format, and then write the CSV data to a GZIP file using .NET GZipStream with optimal compression. Includes proper stream handling and exception management.
    class ConvertWorkbookToCsvGzip
    {
        public static void Run()
        {
            try
            {
                // Create a new workbook
                using (Workbook workbook = new Workbook())
                {
                    // Populate the first worksheet with sample data
                    Worksheet ws = workbook.Worksheets[0];
                    ws.Cells["A1"].PutValue("Name");
                    ws.Cells["B1"].PutValue("Age");
                    ws.Cells["A2"].PutValue("John");
                    ws.Cells["B2"].PutValue(30);
                    ws.Cells["A3"].PutValue("Alice");
                    ws.Cells["B3"].PutValue(25);

                    // Save the workbook to a memory stream in CSV format
                    using (MemoryStream csvStream = new MemoryStream())
                    {
                        workbook.Save(csvStream, SaveFormat.Csv);
                        csvStream.Position = 0; // Reset stream position for reading

                        // Write the CSV data into a GZIP file
                        using (FileStream fileStream = new FileStream("output.csv.gz", FileMode.Create, FileAccess.Write))
                        using (GZipStream gzipStream = new GZipStream(fileStream, CompressionLevel.Optimal))
                        {
                            csvStream.CopyTo(gzipStream);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error during conversion: {ex.Message}");
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ConvertWorkbookToCsvGzip.Run();
        }
    }
}
