// Title: C# – Convert Aspose.Cells Workbook to PDF without Accessibility Tags (ExportDocumentStructure = false)
// Description: Creates a workbook, fills sample cells, sets PdfSaveOptions.ExportDocumentStructure to false to omit accessibility tags, calculates formulas, and saves the file as a lightweight PDF.
// Keywords: Aspose.Cells | C# | PDF conversion | ExportDocumentStructure | disable accessibility tags | PdfSaveOptions | Excel to PDF | lightweight PDF | document structure | no tags
// Common Searches: Aspose.Cells disable accessibility tags PDF | ExportDocumentStructure false C# example | How to save Excel as PDF without tags using Aspose | C# PdfSaveOptions ExportDocumentStructure property | Remove document structure from PDF generated by Aspose.Cells
// Developer Intent: Generate a PDF from an Excel workbook while excluding PDF accessibility (document‑structure) tags.
// Use Cases: Produce compact PDFs for internal reporting where accessibility metadata is unnecessary. | Batch‑process Excel files into PDFs for archival storage without extra document‑structure information. | Create print‑ready PDFs from spreadsheets while keeping file size minimal. | Export spreadsheets to PDF for systems that do not support PDF/UA compliance.
// AI Prompts: Show C# code that converts an Aspose.Cells workbook to PDF with ExportDocumentStructure set to false. | Explain the impact of the ExportDocumentStructure property on the PDF output in Aspose.Cells. | Give an example of disabling accessibility tags during Excel‑to‑PDF conversion using Aspose.Cells.

using System;
using Aspose.Cells;

// Creates a workbook, fills sample cells, sets PdfSaveOptions.ExportDocumentStructure to false to omit accessibility tags, calculates formulas, and saves the file as a lightweight PDF.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Populate some sample data
        worksheet.Cells["A1"].PutValue("Name");
        worksheet.Cells["B1"].PutValue("Age");
        worksheet.Cells["A2"].PutValue("John");
        worksheet.Cells["B2"].PutValue(30);
        worksheet.Cells["A3"].PutValue("Alice");
        worksheet.Cells["B3"].PutValue(25);

        // Create PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Disable exporting of document structure (accessibility tags) for a simpler PDF
        pdfOptions.ExportDocumentStructure = false;

        // Ensure formulas are calculated before saving (optional)
        workbook.CalculateFormula();

        // Save the workbook as a PDF using the specified options
        workbook.Save("output.pdf", pdfOptions);
    }
}
