// Title: Embed a Memory‑Loaded OpenType Font in PDF Export with Aspose.Cells (C#)
// Description: Demonstrates how to load an OTF/TTF font from a byte array, register it with Aspose.Cells via MemoryFontSource, set the workbook’s default style, configure PdfSaveOptions to embed the font, and save the workbook as a PDF. Includes a fallback when the font file is missing.
// Keywords: Aspose.Cells PDF export custom font | C# embed OpenType font memory stream | MemoryFontSource Aspose.Cells | PdfSaveOptions embed font | register in‑memory font Aspose | convert workbook to PDF with custom typography
// Common Searches: how to embed OTF font in Aspose.Cells PDF C# | load custom font from byte array Aspose.Cells | PdfSaveOptions custom font memory stream | Aspose.Cells register font without installing | C# convert Excel to PDF with embedded font
// Developer Intent: Add a custom OpenType font that is loaded from a memory stream to a PDF generated by Aspose.Cells.
// Use Cases: Generate branded PDF reports when the font cannot be installed on the server. | Create PDFs in serverless or containerized environments using only in‑memory font data. | Ensure consistent typography across different machines by embedding the exact font in the PDF.
// AI Prompts: Show code to register several memory‑loaded fonts with Aspose.Cells before saving to PDF. | Provide a method to verify that a specific font is embedded in the resulting PDF file. | Explain how to implement a fallback to a default font if the custom OpenType family name is not found.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to load an OTF/TTF font from a byte array, register it with Aspose.Cells via MemoryFontSource, set the workbook’s default style, configure PdfSaveOptions to embed the font, and save the workbook as a PDF. Includes a fallback when the font file is missing.
class Program
{
    static void Main()
    {
        try
        {
            // 1. Create a new workbook and add some sample text
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Text using a custom OpenType font loaded from memory.");

            // 2. Load the custom OpenType font into a memory stream (if the file exists)
            string fontPath = "customfont.otf";
            bool fontLoaded = false;
            if (File.Exists(fontPath))
            {
                byte[] fontData;
                using (FileStream fs = new FileStream(fontPath, FileMode.Open, FileAccess.Read))
                {
                    fontData = new byte[fs.Length];
                    fs.Read(fontData, 0, (int)fs.Length);
                }

                // 3. Create a MemoryFontSource from the font bytes
                MemoryFontSource memoryFont = new MemoryFontSource(fontData);

                // 4. Register the memory font with Aspose.Cells
                FontSourceBase[] fontSources = new FontSourceBase[] { memoryFont };
                FontConfigs.SetFontSources(fontSources);

                // 5. Apply the custom font to the workbook's default style
                string customFontName = "CustomFont"; // Exact family name inside the OTF/TTF
                workbook.DefaultStyle.Font.Name = customFontName;
                workbook.DefaultStyle.Font.Size = 12;

                // 6. Configure PDF save options to embed the custom font
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    DefaultFont = customFontName,
                    CheckWorkbookDefaultFont = true,
                    EmbedStandardWindowsFonts = true,
                    FontEncoding = PdfFontEncoding.Identity
                };

                // 7. Save the workbook as PDF with the specified options
                workbook.Save("output.pdf", pdfOptions);
                fontLoaded = true;
            }

            if (!fontLoaded)
            {
                // Save without custom font (default settings)
                workbook.Save("output.pdf");
                Console.WriteLine("Custom font file not found. PDF generated with default fonts.");
            }
            else
            {
                Console.WriteLine("Workbook successfully converted to PDF with the custom font embedded.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
