// Title: C# – Convert Excel to Accessible PDF/A‑1b with Aspose.Cells (ExportDocumentStructure)
// Description: Load an Excel workbook with Aspose.Cells, enable ExportDocumentStructure for screen‑reader tags, set PDF/A‑1b compliance, and save as an accessible PDF in a single C# snippet.
// Keywords: Aspose.Cells C# PDF export | Excel to PDF accessibility tags | ExportDocumentStructure | PDF/A‑1b compliance | accessible PDF generation | screen reader friendly PDF | Aspose.Cells PdfSaveOptions
// Common Searches: Aspose.Cells export Excel to accessible PDF | How to add PDF accessibility tags with Aspose.Cells .NET | Set PDF/A‑1b compliance in Aspose.Cells C# | Generate screen‑reader friendly PDF from Excel | C# code for PDF/A‑1b with document structure
// Developer Intent: Create an accessible PDF/A‑1b file from an Excel workbook using Aspose.Cells for .NET.
// Use Cases: Regulatory filing PDFs that must meet PDF/A‑1b standards and be readable by assistive technology. | Financial or medical reports distributed to users with visual impairments. | Automated batch conversion of Excel archives into long‑term, accessible PDF/A documents.
// AI Prompts: Show how to add custom PDF metadata (title, author) while keeping ExportDocumentStructure enabled in Aspose.Cells. | Provide a loop that converts multiple Excel files to PDF/A‑2u with accessibility tags using Aspose.Cells C#. | Give code to validate that a PDF generated by Aspose.Cells contains accessibility tags and passes PDF/A compliance checks.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering; // for PdfCompliance enum

// Load an Excel workbook with Aspose.Cells, enable ExportDocumentStructure for screen‑reader tags, set PDF/A‑1b compliance, and save as an accessible PDF in a single C# snippet.
class Program
{
    static void Main()
    {
        // Load an existing Excel workbook (replace with your actual file path)
        Workbook workbook = new Workbook("input.xlsx");

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Enable accessibility tags (document structure) for screen readers
        pdfOptions.ExportDocumentStructure = true;

        // Set PDF/A compliance (e.g., PDF/A-1b) to meet standard requirements
        pdfOptions.Compliance = PdfCompliance.PdfA1b;

        // Save the workbook as a PDF with the specified options
        workbook.Save("output.pdf", pdfOptions);
    }
}
