// Title: C# – Convert Excel Workbook to PDF with Author, Title & Keywords using Aspose.Cells
// Description: Demonstrates how to set built‑in document properties (Author, Title, Keywords) on an Aspose.Cells Workbook, configure PdfSaveOptions to export standard properties, and save the workbook as a PDF that contains the specified metadata.
// Keywords: Aspose.Cells | C# | Excel to PDF conversion | PDF metadata | author property | title property | keywords property | PdfSaveOptions | BuiltInDocumentProperties | Aspose.Cells for .NET
// Common Searches: Aspose.Cells set PDF author title keywords | C# export Excel built‑in properties to PDF | PdfSaveOptions custom properties export Aspose | How to embed metadata in PDF using Aspose.Cells | Convert workbook to PDF with document properties .NET
// Developer Intent: Add built‑in document properties to an Excel workbook and generate a PDF that carries those properties as embedded metadata.
// Use Cases: Create PDF reports from Excel templates that automatically include author and title for document management systems. | Generate searchable PDF invoices with keyword tags for indexing in enterprise repositories. | Produce compliance‑ready PDF manuals from spreadsheets with embedded metadata for audit trails.
// AI Prompts: Show how to add custom document properties in addition to built‑in ones and export them to PDF with Aspose.Cells. | Provide C# code to read the Author, Title, and Keywords from a PDF generated by Aspose.Cells for verification. | Explain the differences between PdfCustomPropertiesExport.Standard and .All and when to use each.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Demonstrates how to set built‑in document properties (Author, Title, Keywords) on an Aspose.Cells Workbook, configure PdfSaveOptions to export standard properties, and save the workbook as a PDF that contains the specified metadata.
class ConvertWorkbookToPdfWithMetadata
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Add some sample data (optional, just to have content)
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Hello Aspose.Cells!");

        // Set built‑in document properties
        workbook.BuiltInDocumentProperties["Author"].Value = "John Doe";
        workbook.BuiltInDocumentProperties["Title"].Value = "Sample PDF Document";
        workbook.BuiltInDocumentProperties["Keywords"].Value = "Aspose, PDF, Metadata";

        // Configure PDF save options (export custom properties if any)
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            CustomPropertiesExport = PdfCustomPropertiesExport.Standard
        };

        // Save the workbook as PDF with the specified options
        workbook.Save("SampleWithMetadata.pdf", pdfOptions);
    }
}
