// Title: Convert an Excel workbook to a secured, non‑editable PDF that strips all form fields with Aspose.Cells for .NET
// AI Prompts: Generate C# code that loads an .xlsx file with Aspose.Cells, removes personal information, and saves it as a PDF with PdfSecurityOptions set to block editing and form filling. | Show how to configure PdfSecurityOptions in Aspose.Cells to create a PDF that disallows modifications, annotations, and form‑field filling. | Provide a complete example that converts an Excel workbook to a PDF and applies owner‑password protection while keeping the document open for viewing only.
// Common Searches: how to export Excel to PDF with disabled form fields using Aspose.Cells C# | Aspose.Cells PDF security options to prevent editing and form filling | remove personal information from Excel before converting to PDF with Aspose | C# code to create a read‑only PDF from a workbook using Aspose.Cells | set owner password and restrict modifications in PDF generated by Aspose.Cells
// Tags: Aspose.Cells PDF permissions C# | disable form filling Aspose.Cells PDF | remove personal information Aspose.Cells workbook | non‑editable PDF generation with Aspose.Cells | owner password Aspose.Cells PDF

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// // Loads an Excel file, removes personal information, and saves it as a PDF with security settings that block editing, form filling, and annotations.
class ConvertToPdfNonEditable
{
    static void Main()
    {
        // Load the source Excel workbook
        string excelFile = "input.xlsx";
        Workbook workbook = new Workbook(excelFile);

        // Remove personal information (author names, comments, etc.)
        workbook.RemovePersonalInformation();

        // Create PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Configure security options to make the PDF non‑editable
        PdfSecurityOptions security = new PdfSecurityOptions
        {
            OwnerPassword = "owner123",   // optional owner password
            UserPassword = "",           // no user password required to open
            PrintPermission = true,      // allow printing
            ModifyDocumentPermission = false, // disallow modifications
            FillFormsPermission = false, // disallow filling existing form fields
            AnnotationsPermission = false // disallow adding/modifying annotations
        };

        pdfOptions.SecurityOptions = security;

        // Save the workbook as a secured PDF
        string pdfFile = "output.pdf";
        workbook.Save(pdfFile, pdfOptions);
    }
}
