// Title: C# – Convert Excel Workbook to PDF with Left‑to‑Right Layout using Aspose.Cells
// Description: Shows how to create a workbook, disable right‑to‑left display (DisplayRightToLeft = false), optionally add data, and save the file as a PDF that follows the standard left‑to‑right orientation for Western scripts.
// Keywords: Aspose.Cells PDF conversion C# | DisplayRightToLeft false | left to right Excel PDF export | export workbook to PDF .NET | Western script layout Aspose.Cells | C# Excel to PDF left‑to‑right
// Common Searches: Aspose.Cells set worksheet direction before PDF export | C# export Excel to PDF left to right | disable right to left layout Aspose.Cells PDF | how to use DisplayRightToLeft property in PDF conversion | convert workbook to PDF with western script orientation
// Developer Intent: Generate a PDF from an Excel workbook while guaranteeing a left‑to‑right reading order suitable for Western languages.
// Use Cases: Produce printable reports or invoices in PDF where the default left‑to‑right layout is required. | Automate server‑side conversion of user‑edited worksheets to PDF without right‑to‑left formatting. | Integrate PDF export into a web API that serves Western‑script documents to clients.
// AI Prompts: Write C# code with Aspose.Cells that converts a workbook to PDF and forces a left‑to‑right layout. | Explain how the DisplayRightToLeft property influences the orientation of a PDF generated by Aspose.Cells. | Provide troubleshooting steps if a PDF generated with Aspose.Cells still appears right‑to‑left despite setting DisplayRightToLeft to false.

using System;
using Aspose.Cells;

// Shows how to create a workbook, disable right‑to‑left display (DisplayRightToLeft = false), optionally add data, and save the file as a PDF that follows the standard left‑to‑right orientation for Western scripts.
class ConvertWorkbookToPdf
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet worksheet = workbook.Worksheets[0];

        // Set the worksheet to display left‑to‑right (default for Western scripts)
        worksheet.DisplayRightToLeft = false;

        // Optional: add some sample data
        worksheet.Cells["A1"].PutValue("Hello");
        worksheet.Cells["B1"].PutValue("World");

        // Save the workbook as a PDF file
        workbook.Save("output.pdf", SaveFormat.Pdf);

        Console.WriteLine("Workbook successfully converted to PDF with left‑to‑right direction.");
    }
}
