// Title: Convert Excel to PDF with Fillable Form Fields using Aspose.Cells for .NET
// Description: Shows how to load an .xlsx workbook, set PdfSaveOptions with PdfSecurityOptions (owner/user passwords, FillFormsPermission, PrintPermission), enable formula calculation, and save as a PDF that keeps interactive form controls for end‑user input.
// Keywords: Aspose.Cells | C# | Excel to PDF | fillable PDF | PdfSaveOptions | PdfSecurityOptions | FillFormsPermission | preserve form controls | interactive PDF forms | calculate formulas
// Common Searches: Aspose.Cells keep Excel form controls in PDF | C# Aspose.Cells fillable PDF conversion | PdfSaveOptions FillFormsPermission example | enable form filling in PDF generated by Aspose.Cells | secure PDF with fillable fields using Aspose.Cells
// Developer Intent: Create a PDF from an Excel workbook that retains editable form fields.
// Use Cases: Generate fillable PDF questionnaires from Excel templates for distribution to clients. | Produce PDF reports that show calculated values while allowing recipients to complete embedded form controls. | Distribute secured PDFs with owner/user passwords that still permit form filling and printing.
// AI Prompts: Write C# code with Aspose.Cells to convert an Excel file to a PDF that preserves fillable fields and applies owner/user passwords. | Explain the role of PdfSecurityOptions.FillFormsPermission in Aspose.Cells and how to combine it with PrintPermission. | Show how to adjust the example to disable form filling or modify security settings for the generated PDF.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering.PdfSecurity;

// Shows how to load an .xlsx workbook, set PdfSaveOptions with PdfSecurityOptions (owner/user passwords, FillFormsPermission, PrintPermission), enable formula calculation, and save as a PDF that keeps interactive form controls for end‑user input.
class WorkbookToPdfWithInteractiveForms
{
    static void Main()
    {
        // Path to the source Excel file (can contain form controls)
        string sourcePath = "input.xlsx";

        // Load the workbook from the file system
        Workbook workbook = new Workbook(sourcePath);

        // Create PDF save options
        PdfSaveOptions pdfSaveOptions = new PdfSaveOptions();

        // Configure security options to allow filling form fields after distribution
        PdfSecurityOptions securityOptions = new PdfSecurityOptions
        {
            OwnerPassword = "owner123",   // optional owner password
            UserPassword = "user123",     // optional user password
            FillFormsPermission = true,   // enable interactive form filling
            PrintPermission = true        // allow printing (optional)
        };

        // Assign the security options to the PDF save options
        pdfSaveOptions.SecurityOptions = securityOptions;

        // (Optional) Calculate formulas before saving so that calculated values appear in the PDF
        pdfSaveOptions.CalculateFormula = true;

        // Save the workbook as a PDF file with the specified options
        string outputPath = "output.pdf";
        workbook.Save(outputPath, pdfSaveOptions);

        Console.WriteLine($"Workbook converted to PDF with interactive form fields enabled: {outputPath}");
    }
}
