// Title: Convert Excel to PDF with English language settings using Aspose.Cells for .NET
// Description: Loads an Excel workbook, sets the built‑in Language property to "en-US" and the UI language to United States, configures PdfSaveOptions.DefaultEditLanguage to English, then saves the file as a PDF. The resulting PDF carries English (US) metadata for correct spell checking and layout.
// Keywords: Aspose.Cells | C# | Excel to PDF conversion | PDF language English | DefaultEditLanguage | en-US document property | PdfSaveOptions | spell checking metadata | CountryCode USA | built‑in Language property
// Common Searches: Aspose.Cells set PDF language to English | C# convert Excel workbook to PDF with language metadata | How to use DefaultEditLanguage in Aspose.Cells | Set built‑in Language property before PDF export | English spell check in PDFs generated by Aspose.Cells
// Developer Intent: Export an Excel workbook to PDF while marking the document as English (US) so that spell checking and layout are applied correctly.
// Use Cases: Generate PDF reports from Excel templates that require English (US) spell‑check compliance. | Create localized PDFs for a US audience by embedding language metadata during conversion. | Automate batch processing of workbooks to PDF with consistent English language settings.
// AI Prompts: Provide C# code that converts an Excel file to PDF with Aspose.Cells and sets the document language to en‑US. | Show how to assign both the built‑in Language property and the UI language before saving a workbook as PDF using Aspose.Cells. | Explain the effect of PdfSaveOptions.DefaultEditLanguage on spell checking in PDFs generated by Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Properties;

namespace AsposeCellsPdfConversion
{
    // Loads an Excel workbook, sets the built‑in Language property to "en-US" and the UI language to United States, configures PdfSaveOptions.DefaultEditLanguage to English, then saves the file as a PDF. The resulting PDF carries English (US) metadata for correct spell checking and layout.
    class Program
    {
        static void Main()
        {
            // Path to the source Excel workbook
            string sourcePath = "input.xlsx";

            // Path for the resulting PDF file
            string pdfPath = "output.pdf";

            // Load the workbook from the file system
            Workbook workbook = new Workbook(sourcePath);

            // Set the built‑in document property "Language" to English (en‑US)
            workbook.BuiltInDocumentProperties.Language = "en-US";

            // Set the workbook UI language to English (United States)
            workbook.Settings.LanguageCode = CountryCode.USA;

            // Create PDF save options and specify English as the default edit language
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // This ensures proper spell checking and layout for English text
                DefaultEditLanguage = DefaultEditLanguage.English
            };

            // Save the workbook as a PDF using the configured options
            workbook.Save(pdfPath, pdfOptions);

            Console.WriteLine("Workbook successfully converted to PDF with English language settings.");
        }
    }
}
