// Title: C# – Convert Excel Workbook to PDF with Fast Web View (Linearized PDF) using Aspose.Cells
// Description: Demonstrates how to load or create a workbook, configure PdfSaveOptions, optionally enable Fast Web View, ensure the output directory exists, and save the workbook as a linearized PDF for quicker browser rendering.
// Keywords: Aspose.Cells PDF conversion C# | Fast Web View PDF Aspose | EnableFastWebView .NET | Excel to PDF linearized | PdfSaveOptions Aspose.Cells | C# generate web‑optimized PDF | Aspose.Cells save as PDF options
// Common Searches: Aspose.Cells enable Fast Web View when saving PDF | C# example for linearized PDF with Aspose.Cells | How to create web‑optimized PDF from Excel in .NET | PdfSaveOptions EnableFastWebView property | Save workbook as PDF with fast loading in browsers
// Developer Intent: Produce a PDF from an Excel workbook and activate Fast Web View to reduce load time in web browsers.
// Use Cases: Deliver dynamically generated reports as fast‑loading PDFs on a web portal. | Batch‑process Excel files into linearized PDFs for reduced client download latency. | Expose a REST endpoint that returns PDF documents optimized for streaming in browsers.
// AI Prompts: Write C# code that loads an existing Excel file, sets PdfSaveOptions.EnableFastWebView = true (if supported), and saves it as a linearized PDF. | Create a reusable method that accepts input and output paths, creates missing folders, and exports the workbook to PDF with Fast Web View enabled. | Explain the benefits of Fast Web View in PDFs generated by Aspose.Cells and list the Aspose.Cells versions that support the feature.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

namespace FastWebViewPdfExample
{
    // Demonstrates how to load or create a workbook, configure PdfSaveOptions, optionally enable Fast Web View, ensure the output directory exists, and save the workbook as a linearized PDF for quicker browser rendering.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook (or load an existing one)
                Workbook workbook = new Workbook();

                // Add some sample data to the first worksheet
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Cells["A1"].PutValue("Fast Web View PDF Example");
                sheet.Cells["A2"].PutValue(DateTime.Now);

                // Configure PDF save options
                PdfSaveOptions pdfOptions = new PdfSaveOptions();

                // Note: In some versions of Aspose.Cells the EnableFastWebView property may not be available.
                // If supported, you can enable it as shown below:
                // pdfOptions.EnableFastWebView = true;

                // Define output file path
                string outputPath = "FastWebView.pdf";

                // Ensure the directory for the output file exists
                string fullPath = Path.GetFullPath(outputPath);
                string outputDir = Path.GetDirectoryName(fullPath) ?? Directory.GetCurrentDirectory();

                if (!Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the workbook as a PDF
                workbook.Save(outputPath, pdfOptions);
                Console.WriteLine($"PDF saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
