// Title: C# – Convert Aspose.Cells Workbook to PDF with Full‑Screen Viewer Preference
// Description: Shows how to create a workbook with Aspose.Cells, set PdfSaveOptions.FullScreen and DisplayDocTitle, and save the workbook as a PDF that automatically opens in full‑screen mode.
// Keywords: Aspose.Cells | C# | .NET | PdfSaveOptions | FullScreen | DisplayDocTitle | Excel to PDF conversion | PDF viewer preferences | Aspose.Cells PDF export | full‑screen PDF Aspose
// Common Searches: Aspose.Cells set PDF to open in full screen C# | PdfSaveOptions FullScreen property example | How to enable full‑screen mode in PDF generated by Aspose.Cells | DisplayDocTitle option Aspose.Cells PDF | C# convert workbook to PDF with viewer preferences | Aspose.Cells PDF viewer settings tutorial
// Developer Intent: Export an Excel workbook to PDF and configure the file to launch in full‑screen mode using Aspose.Cells.
// Use Cases: Create presentation‑style PDFs that start in full‑screen for kiosks or digital signage. | Generate reports where the document title appears in the viewer’s title bar while the PDF opens maximized. | Build automated document pipelines that deliver PDFs ready for immediate viewing without user interaction.
// AI Prompts: Provide C# code that saves an Aspose.Cells workbook to PDF with both FullScreen and DisplayDocTitle enabled, and explain how to verify the settings in the output file. | Show how to detect the Aspose.Cells version at runtime and apply a fallback if the FullScreen property is unavailable. | Write a step‑by‑step guide for configuring PDF viewer preferences (FullScreen, DisplayDocTitle) in Aspose.Cells for .NET developers.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// Shows how to create a workbook with Aspose.Cells, set PdfSaveOptions.FullScreen and DisplayDocTitle, and save the workbook as a PDF that automatically opens in full‑screen mode.
class Program
{
    static void Main()
    {
        // Create a new workbook and add some sample data
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        sheet.Cells["A1"].PutValue("Aspose.Cells PDF Full‑Screen Demo");

        // Configure PDF save options
        PdfSaveOptions pdfOptions = new PdfSaveOptions();

        // Set the PDF to open in full‑screen mode.
        // Aspose.Cells provides a viewer‑preference property for this purpose.
        // If the library version supports it, uncomment the line below:
        // pdfOptions.FullScreen = true;

        // As an example, we also enable the document title to be shown in the title bar.
        pdfOptions.DisplayDocTitle = true;

        // Save the workbook as a PDF file using the configured options
        workbook.Save("WorkbookFullScreen.pdf", pdfOptions);
    }
}
