// Title: Convert Excel Workbook to PDF and Add Auto‑Print JavaScript with Aspose.Cells & Aspose.Pdf (C#)
// Description: Demonstrates how to create an Excel workbook with Aspose.Cells, save it as a PDF using PdfSaveOptions, and then embed JavaScript that triggers the print dialog when the PDF opens. The example notes that the JavaScript step requires the Aspose.Pdf library.
// Keywords: Aspose.Cells PDF conversion | Aspose.Pdf JavaScript embed | C# auto‑print PDF | Excel to PDF with print script | PdfSaveOptions | embed JavaScript in PDF | print on open PDF | .NET PDF automation | batch PDF generation | Aspose .NET libraries
// Common Searches: how to add auto print JavaScript to PDF generated by Aspose.Cells | Aspose.Pdf embed JavaScript after Excel to PDF conversion | C# save workbook as PDF and trigger print on open | Aspose.Cells PdfSaveOptions example | add JavaScript action to PDF using Aspose.Pdf
// Developer Intent: Create a PDF from an Excel workbook and attach a JavaScript action that automatically opens the print dialog when the PDF is viewed.
// Use Cases: Generate sales reports in Excel, convert them to PDF, and enable one‑click printing for office staff. | Automate invoice production where each PDF opens the printer dialog for fast batch printing. | Deploy kiosk or point‑of‑sale solutions that convert Excel templates to PDFs that print immediately on display.
// AI Prompts: Provide C# code that saves an Aspose.Cells workbook as PDF and then uses Aspose.Pdf to embed a JavaScript print command that runs on document open. | Show how to combine PdfSaveOptions with Aspose.Pdf's PdfFileEditor to add an auto‑print JavaScript action after PDF creation. | Explain how to verify that the generated PDF contains the JavaScript print script and how to test it in Adobe Reader and other PDF viewers.

using System;
using System.IO;
using Aspose.Cells;

// Demonstrates how to create an Excel workbook with Aspose.Cells, save it as a PDF using PdfSaveOptions, and then embed JavaScript that triggers the print dialog when the PDF opens. The example notes that the JavaScript step requires the Aspose.Pdf library.
class WorkbookToPdfWithPrintJs
{
    static void Main()
    {
        try
        {
            // 1. Create a workbook and add some sample data
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Cells["A1"].PutValue("Product");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["A2"].PutValue("Apples");
            sheet.Cells["B2"].PutValue(120);
            sheet.Cells["A3"].PutValue("Oranges");
            sheet.Cells["B3"].PutValue(85);

            // 2. Define PDF save options (optional customizations)
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Example: keep document structure, you can set other options as needed
                ExportDocumentStructure = true
            };

            // 3. Save the workbook as a PDF file
            string pdfPath = "Report.pdf";

            // Ensure the directory exists before saving
            string pdfDirectory = Path.GetDirectoryName(Path.GetFullPath(pdfPath));
            if (!Directory.Exists(pdfDirectory))
            {
                Directory.CreateDirectory(pdfDirectory);
            }

            workbook.Save(pdfPath, pdfOptions);

            // Verify that the PDF was created
            if (!File.Exists(pdfPath))
                throw new FileNotFoundException($"The PDF file '{pdfPath}' was not found.");

            Console.WriteLine($"PDF created at '{pdfPath}'.");
            Console.WriteLine("Embedding JavaScript requires Aspose.Pdf, which is not referenced in this project.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
