// Title: Convert an Aspose.Cells workbook to PDF without accessibility tags (disable document structure) in C#
// AI Prompts: Write C# code that creates an Aspose.Cells workbook, fills cells, and saves it as a PDF with ExportDocumentStructure set to false. | Show how to configure PdfSaveOptions in Aspose.Cells to omit PDF/UA tags during Excel‑to‑PDF conversion. | Provide a minimal example that disables document structure when exporting a workbook to PDF using Aspose.Cells for .NET. | Demonstrate disabling accessibility tags in a PDF generated from an Excel file with Aspose.Cells.
// Common Searches: Aspose.Cells how to export Excel to PDF without PDF/UA tags in C# | disable document structure when saving workbook as PDF using Aspose.Cells .NET | C# code sample for removing accessibility tags from PDF generated by Aspose.Cells | PdfSaveOptions ExportDocumentStructure false example Aspose.Cells | convert workbook to PDF without accessibility metadata Aspose.Cells C#
// Tags: Aspose.Cells PDF export disable document structure | ExportDocumentStructure false PdfSaveOptions | C# Excel to PDF conversion without accessibility tags | Workbook to PDF without PDF/UA metadata | Aspose.Cells PDFSaveOptions configuration example

using System;
using Aspose.Cells;

namespace AsposeCellsPdfExport
{
    // The sample creates a new workbook, adds data to the first worksheet, sets PdfSaveOptions.ExportDocumentStructure to false, optionally calculates formulas, and saves the workbook as a PDF. The resulting PDF is generated without accessibility (document structure) tags.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (using the standard creation rule)
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add some sample data
            sheet.Cells["A1"].PutValue("Name");
            sheet.Cells["B1"].PutValue("Age");
            sheet.Cells["A2"].PutValue("John");
            sheet.Cells["B2"].PutValue(30);
            sheet.Cells["A3"].PutValue("Alice");
            sheet.Cells["B3"].PutValue(25);

            // Create PDF save options (using the constructor rule)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Disable exporting of document structure (accessibility tags)
            pdfOptions.ExportDocumentStructure = false;

            // Optional: calculate formulas before saving
            workbook.CalculateFormula();

            // Save the workbook to PDF with the specified options (using the save rule)
            workbook.Save("SimpleDocument.pdf", pdfOptions);

            Console.WriteLine("PDF saved without document structure (accessibility tags).");
        }
    }
}
