// Title: Embed a Custom TrueType Font in PDF using Aspose.Cells (C#)
// Description: Registers an external folder containing a TrueType font, applies the font to worksheet cells, configures PdfSaveOptions to use the font as the default, enables embedding and Unicode Identity encoding, and saves the workbook as a PDF with the custom font embedded.
// Keywords: Aspose.Cells PDF custom font | C# embed TrueType font PDF | register external font folder Aspose.Cells | PdfSaveOptions default font | font embedding Aspose.Cells | Unicode Identity encoding PDF | Aspose.Cells workbook to PDF
// Common Searches: how to embed a custom TrueType font in Aspose.Cells PDF | register external font folder for PDF conversion Aspose.Cells .NET | set default font when saving workbook as PDF Aspose.Cells | enable font embedding and Unicode encoding in Aspose.Cells PDF output | Aspose.Cells C# custom font PDF example
// Developer Intent: Embed a TrueType font from an external directory into a PDF generated by Aspose.Cells.
// Use Cases: Create invoices that use a corporate brand font and display correctly on any device. | Generate multilingual reports requiring a specific Unicode font not installed on the viewer’s system. | Produce printable worksheets with a custom hand‑written style font for educational materials.
// AI Prompts: Write C# code that registers a folder with a custom TrueType font, applies the font to cells, and saves an Aspose.Cells workbook as a PDF with the font embedded. | Explain how to configure PdfSaveOptions in Aspose.Cells to set a custom default font, enable font embedding, and use Identity encoding for Unicode characters. | Show how to verify that a custom font is embedded in the resulting PDF using a PDF inspection tool or Aspose.Cells API.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

namespace AsposeCellsCustomFontPdf
{
    // Registers an external folder containing a TrueType font, applies the font to worksheet cells, configures PdfSaveOptions to use the font as the default, enables embedding and Unicode Identity encoding, and saves the workbook as a PDF with the custom font embedded.
    class Program
    {
        static void Main()
        {
            // Path to the folder that contains the custom TrueType font file.
            // The folder will be scanned recursively for fonts.
            string customFontFolder = @"C:\CustomFonts";

            // Register the custom font folder with Aspose.Cells.
            // This enables the library to locate and use the font during PDF conversion.
            FontConfigs.SetFontFolder(customFontFolder, true);

            // Create a new workbook (lifecycle rule: create).
            Workbook workbook = new Workbook();

            // Access the first worksheet.
            Worksheet sheet = workbook.Worksheets[0];

            // Add some sample text that will use the custom font.
            Cell cell = sheet.Cells["A1"];
            cell.PutValue("Text rendered with a custom TrueType font");

            // Apply the custom font to the cell style.
            // The font name must match the name defined inside the TrueType file.
            Style style = cell.GetStyle();
            style.Font.Name = "MyFont"; // Replace with the actual font name inside MyFont.ttf
            style.Font.Size = 14;
            cell.SetStyle(style);

            // Configure PDF save options.
            PdfSaveOptions pdfOptions = new PdfSaveOptions
            {
                // Use the custom font as the default font for any characters
                // that do not have an explicit font set.
                DefaultFont = "MyFont",

                // Ensure the library checks the workbook's default font first.
                CheckWorkbookDefaultFont = true,

                // Embed the font into the PDF so that the document displays correctly
                // on machines that do not have the font installed.
                EmbedStandardWindowsFonts = true,

                // Use Identity encoding to preserve all Unicode characters.
                FontEncoding = PdfFontEncoding.Identity
            };

            // Save the workbook as PDF with the specified options (lifecycle rule: save).
            string outputPdfPath = @"C:\Output\CustomFontDocument.pdf";
            workbook.Save(outputPdfPath, pdfOptions);

            Console.WriteLine("PDF saved successfully with embedded custom font at:");
            Console.WriteLine(outputPdfPath);
        }
    }
}
