using System;
using Aspose.Cells;

class WorkbookToPdfWithHeaderFooter
{
    static void Main()
    {
        // Create a new workbook (or load an existing one)
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];

        // ----- Set custom header -----
        // Left section: company name in Arial Bold, size 12
        sheet.PageSetup.SetHeader(0, "&\"Arial,Bold\"&12My Company");
        // Center section: report title
        sheet.PageSetup.SetHeader(1, "Confidential Report");
        // Right section: current date
        sheet.PageSetup.SetHeader(2, "&D");

        // ----- Set custom footer -----
        // Left section: page number of total pages
        sheet.PageSetup.SetFooter(0, "Page &P of &N");
        // Center section: generator information
        sheet.PageSetup.SetFooter(1, "Generated by Aspose.Cells");
        // Right section: current time
        sheet.PageSetup.SetFooter(2, "&T");

        // Add sample data to demonstrate content
        sheet.Cells["A1"].PutValue("Sample Data");
        sheet.Cells["B2"].PutValue(12345);

        // Configure PDF save options (optional settings)
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        pdfOptions.ExportDocumentStructure = true; // retain document structure in PDF

        // Save the workbook as PDF; headers and footers will appear on every page
        workbook.Save("output.pdf", pdfOptions);
    }
}