// Title: C# Folder Watcher that Auto‑Converts CSV to XLSX with Aspose.Cells
// Description: A reusable C# utility that watches a directory for new *.csv files, waits until each file is free, and instantly converts it to an .xlsx workbook using Aspose.Cells ConversionUtility. The output can be saved in the same folder or a separate location, with built‑in error handling and console logging.
// Keywords: Aspose.Cells | CSV to XLSX conversion | C# FileSystemWatcher | automatic Excel conversion | ConversionUtility.Convert | .NET folder monitor | real‑time data processing | batch CSV conversion | Windows service CSV watcher | C# data import automation
// Common Searches: C# watch folder and convert CSV to Excel | Aspose.Cells ConversionUtility example | FileSystemWatcher convert new CSV files | automatic CSV to XLSX conversion .NET | handle file lock when converting CSV in C#
// Developer Intent: Implement a background service that continuously monitors a directory and transforms each newly added CSV file into an XLSX workbook using Aspose.Cells.
// Use Cases: Process incoming data exports placed in a drop folder and generate ready‑to‑use Excel reports. | Run as a Windows service to automate conversion of CSV logs generated by external applications. | Integrate into CI/CD pipelines to turn CSV test data into Excel workbooks for visual validation.
// AI Prompts: Generate a C# class that uses FileSystemWatcher to detect new CSV files and converts them to XLSX with Aspose.Cells, including retry logic for locked files. | Add structured logging (e.g., Serilog) to the CsvToXlsxWatcher and expose conversion status via events. | Extend the watcher to monitor subfolders recursively and preserve the folder hierarchy when saving converted XLSX files.

using System;
using System.IO;
using System.Threading;
using Aspose.Cells.Utility;

namespace AsposeCellsCsvWatcher
{
    // A reusable C# utility that watches a directory for new *.csv files, waits until each file is free, and instantly converts it to an .xlsx workbook using Aspose.Cells ConversionUtility. The output can be saved in the same folder or a separate location, with built‑in error handling and console logging.
    public class CsvToXlsxWatcher : IDisposable
    {
        private readonly FileSystemWatcher _watcher;
        private readonly string _outputFolder;
        private bool _disposed;

        /// <summary>
        /// Initializes the watcher.
        /// </summary>
        /// <param name="inputFolder">Folder to monitor for CSV files.</param>
        /// <param name="outputFolder">Folder where converted XLSX files will be saved. If null, uses the input folder.</param>
        public CsvToXlsxWatcher(string inputFolder, string outputFolder = null)
        {
            if (string.IsNullOrWhiteSpace(inputFolder))
                throw new ArgumentException("Input folder path must be provided.", nameof(inputFolder));

            _outputFolder = string.IsNullOrWhiteSpace(outputFolder) ? inputFolder : outputFolder;

            _watcher = new FileSystemWatcher(inputFolder, "*.csv")
            {
                NotifyFilter = NotifyFilters.FileName | NotifyFilters.CreationTime,
                EnableRaisingEvents = true,
                IncludeSubdirectories = false
            };

            _watcher.Created += OnCreated;
        }

        private void OnCreated(object sender, FileSystemEventArgs e)
        {
            // Run conversion on a separate thread to avoid blocking the watcher.
            ThreadPool.QueueUserWorkItem(_ => ProcessCsvFile(e.FullPath));
        }

        private void ProcessCsvFile(string csvPath)
        {
            // Wait until the file is accessible (some programs lock the file briefly after creation).
            const int maxAttempts = 10;
            int attempts = 0;
            while (attempts < maxAttempts)
            {
                try
                {
                    using (FileStream stream = File.Open(csvPath, FileMode.Open, FileAccess.Read, FileShare.None))
                    {
                        // If we can open the file exclusively, it is ready.
                        break;
                    }
                }
                catch (IOException)
                {
                    attempts++;
                    Thread.Sleep(500); // wait half a second before retrying
                }
            }

            try
            {
                string fileNameWithoutExt = Path.GetFileNameWithoutExtension(csvPath);
                string destPath = Path.Combine(_outputFolder, fileNameWithoutExt + ".xlsx");

                // Use Aspose.Cells ConversionUtility to convert CSV to XLSX.
                // This follows the provided rule: ConversionUtility.Convert(string source, string saveAs)
                ConversionUtility.Convert(csvPath, destPath);

                Console.WriteLine($"Converted '{csvPath}' to '{destPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error converting '{csvPath}': {ex.Message}");
            }
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                _watcher.Created -= OnCreated;
                _watcher.Dispose();
                _disposed = true;
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // Example usage:
            // Monitor the "InputCsv" folder and place converted files in the same folder.
            string folderToWatch = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "InputCsv");

            // Ensure the folder exists.
            Directory.CreateDirectory(folderToWatch);

            using (var watcher = new CsvToXlsxWatcher(folderToWatch))
            {
                Console.WriteLine($"Watching folder: {folderToWatch}");
                Console.WriteLine("Press ENTER to exit.");
                Console.ReadLine(); // Keep the application running until user decides to quit.
            }
        }
    }
}
