// Title: How to export an Aspose.Cells workbook to camelCase‑formatted JSON in C#
// AI Prompts: Write C# code that creates a Workbook, configures JsonSaveOptions (header row, skip empty rows, always export as object), saves the workbook to a memory stream as JSON, then re‑serializes the JSON with System.Text.Json using a camelCase naming policy and writes the result to a file. | Show how to parse the JSON generated by Aspose.Cells and apply JsonSerializerOptions with PropertyNamingPolicy = JsonNamingPolicy.CamelCase to produce camelCase keys before persisting the output.
// Common Searches: c# Aspose.Cells export workbook to JSON with camelCase property names | using JsonSaveOptions to generate JSON from Excel and convert keys to camelCase | how to convert Aspose.Cells JSON output to camelCase with System.Text.Json | skip empty rows and include header row when exporting Excel to JSON in C# | write camelCase JSON file from Aspose.Cells workbook in .NET
// Tags: Aspose.Cells JsonSaveOptions export to JSON | C# convert JSON property names to camelCase | Excel workbook to camelCase JSON using System.Text.Json | skip empty rows Aspose.Cells JSON export | include header row Aspose.Cells JSON output

using System;
using System.IO;
using System.Text;
using Aspose.Cells;
using Aspose.Cells.Utility;
using System.Text.Json;

namespace AsposeCellsJsonCamelCaseDemo
{
    // The example creates a workbook with employee data, sets JsonSaveOptions to include the header row, skip empty rows, and always export as a JSON object, saves the workbook to a memory stream, parses the generated JSON, re‑serializes it with System.Text.Json using a camelCase naming policy, and writes the camelCase JSON to a file named EmployeesCamelCase.json.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and add sample data
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Name = "Employees";

                // Header row
                sheet.Cells["A1"].PutValue("EmployeeId");
                sheet.Cells["B1"].PutValue("FirstName");
                sheet.Cells["C1"].PutValue("LastName");
                sheet.Cells["D1"].PutValue("Salary");

                // Data rows
                sheet.Cells["A2"].PutValue(101);
                sheet.Cells["B2"].PutValue("John");
                sheet.Cells["C2"].PutValue("Doe");
                sheet.Cells["D2"].PutValue(75000);

                sheet.Cells["A3"].PutValue(102);
                sheet.Cells["B3"].PutValue("Jane");
                sheet.Cells["C3"].PutValue("Smith");
                sheet.Cells["D3"].PutValue(82000);

                // Configure JSON save options
                JsonSaveOptions saveOptions = new JsonSaveOptions
                {
                    AlwaysExportAsJsonObject = true, // Export as a JSON object even if there is only one worksheet
                    HasHeaderRow = true,              // Include header row information
                    SkipEmptyRows = true,             // Skip empty rows for cleaner output
                    Indent = "    "                   // Indent for readability (optional)
                };

                // Save the workbook to a memory stream using Aspose.Cells
                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.Save(ms, saveOptions);
                    ms.Position = 0;

                    // Read the generated JSON string
                    string originalJson = new StreamReader(ms, Encoding.UTF8).ReadToEnd();

                    // Convert property names to camelCase using System.Text.Json
                    using JsonDocument jsonDoc = JsonDocument.Parse(originalJson);
                    JsonSerializerOptions jsonOptions = new JsonSerializerOptions
                    {
                        WriteIndented = true,
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    };
                    string camelCaseJson = JsonSerializer.Serialize(jsonDoc.RootElement, jsonOptions);

                    // Write the camelCase JSON to a file
                    string outputPath = "EmployeesCamelCase.json";
                    File.WriteAllText(outputPath, camelCaseJson, Encoding.UTF8);

                    Console.WriteLine($"CamelCase JSON saved to: {outputPath}");
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
