// Title: Export each worksheet to a separate HTML file with Aspose.Cells for .NET
// Description: This example creates a workbook with three sheets, fills them with sample data, and uses HtmlSaveOptions together with a custom IFilePathProvider to generate an individual HTML file for every worksheet. ExportActiveWorksheetOnly is set to false, SaveAsSingleFile is disabled, and the provider returns "{SheetName}.html" so the output files are named after their sheets.
// Keywords: Aspose.Cells | C# | .NET | HtmlSaveOptions | SaveAsSingleFile false | ExportActiveWorksheetOnly false | IFilePathProvider | separate HTML per worksheet | worksheet to HTML conversion | multi‑sheet HTML export
// Common Searches: Aspose.Cells export each worksheet to HTML | How to save Excel sheets as individual HTML files in C# | Custom IFilePathProvider example Aspose.Cells | Generate separate HTML pages for Excel workbook using Aspose.Cells | C# HtmlSaveOptions multiple HTML files per sheet
// Developer Intent: Generate one HTML file per worksheet in an Excel workbook using Aspose.Cells for .NET.
// Use Cases: Web reporting portal that displays each sheet on its own page | Downloadable per‑sheet HTML reports for finance or analytics teams | Automated publishing of multi‑sheet Excel models to static web pages | Creating a navigation index that links to sheet‑specific HTML files
// AI Prompts: Write C# code with Aspose.Cells that exports every worksheet of a workbook to separate HTML files, using a custom IFilePathProvider to name files after the sheet. | Explain the required HtmlSaveOptions settings to produce individual HTML files for each worksheet and how to disable single‑file export. | Provide a tutorial that adds a main index HTML linking to each sheet‑specific file generated by Aspose.Cells. | Show how to customize the file path provider to include a folder structure based on worksheet names.

using System;
using Aspose.Cells;

namespace AsposeCellsHtmlExport
{
    // Custom file path provider to generate separate HTML file for each worksheet
    // This example creates a workbook with three sheets, fills them with sample data, and uses HtmlSaveOptions together with a custom IFilePathProvider to generate an individual HTML file for every worksheet. ExportActiveWorksheetOnly is set to false, SaveAsSingleFile is disabled, and the provider returns "{SheetName}.html" so the output files are named after their sheets.
    public class CustomFilePathProvider : IFilePathProvider
    {
        // Returns a file name based on the worksheet name
        public string GetFullName(string sheetName)
        {
            // Example: "Sheet1.html", "DataSheet.html", etc.
            return $"{sheetName}.html";
        }
    }

    public class ExportSeparateHtmlPerWorksheet
    {
        public static void Run()
        {
            // Create a new workbook and add three worksheets
            Workbook workbook = new Workbook();
            workbook.Worksheets[0].Name = "Summary";
            Worksheet sheet1 = workbook.Worksheets.Add("Data");
            Worksheet sheet2 = workbook.Worksheets.Add("Report");

            // Populate each worksheet with sample data
            workbook.Worksheets["Summary"].Cells["A1"].PutValue("This is the summary sheet.");
            sheet1.Cells["A1"].PutValue("Data Sheet Header");
            sheet1.Cells["A2"].PutValue(123);
            sheet2.Cells["A1"].PutValue("Report Sheet Header");
            sheet2.Cells["B2"].PutValue(DateTime.Now);

            // Configure HTML save options
            HtmlSaveOptions saveOptions = new HtmlSaveOptions
            {
                // Ensure all worksheets are exported (default is false for single sheet)
                ExportActiveWorksheetOnly = false,
                // Save each worksheet as a separate HTML file
                SaveAsSingleFile = false,
                // Use the custom file path provider to name files after the worksheet
                FilePathProvider = new CustomFilePathProvider()
            };

            // Save the workbook; separate HTML files will be created for each worksheet
            // The main file name is used only as a placeholder; actual files are generated by the provider
            workbook.Save("WorkbookIndex.html", saveOptions);
        }
    }

    // Example entry point
    class Program
    {
        static void Main()
        {
            ExportSeparateHtmlPerWorksheet.Run();
            Console.WriteLine("Export completed. Check the output HTML files.");
        }
    }
}
