// Title: Convert XLSX to High‑Resolution PDF with Aspose.Cells for .NET (C#)
// Description: This example demonstrates how to load an XLSX workbook using Aspose.Cells, verify the source file, configure PdfSaveOptions (including ExportDocumentStructure), and save the workbook as a high‑resolution PDF while handling errors gracefully.
// Keywords: Aspose.Cells | XLSX to PDF | C# | .NET | high resolution PDF | PdfSaveOptions | ExportDocumentStructure | Excel to PDF conversion | Workbook.Save PDF | Aspose.Cells API
// Common Searches: convert xlsx to pdf c# aspose.cells | high resolution pdf from excel using aspose | pdfsaveoptions exportdocumentstructure example | c# check file exists before converting excel to pdf | asp.net excel to pdf batch conversion
// Developer Intent: Generate a high‑resolution PDF from an XLSX workbook using Aspose.Cells in C#.
// Use Cases: Create client‑ready PDF reports from financial Excel workbooks while preserving document hierarchy. | Automate batch conversion of multiple XLSX files to high‑quality PDFs in a server‑side .NET service. | Validate Excel input files before conversion to avoid runtime errors in CI/CD pipelines.
// AI Prompts: Write C# code that loads an .xlsx file with Aspose.Cells, checks for its existence, sets PdfSaveOptions with ExportDocumentStructure, and saves a high‑resolution PDF. | Explain how the ExportDocumentStructure option affects the PDF output generated by Aspose.Cells. | Provide a C# snippet that iterates through a folder of .xlsx files and converts each to a high‑resolution PDF using the same Aspose.Cells settings.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Saving;

namespace AsposeCellsConversionDemo
{
    // This example demonstrates how to load an XLSX workbook using Aspose.Cells, verify the source file, configure PdfSaveOptions (including ExportDocumentStructure), and save the workbook as a high‑resolution PDF while handling errors gracefully.
    public class XlsxToHighResPdf
    {
        public static void Run()
        {
            // Path to the source XLSX file
            string sourcePath = "input.xlsx";

            // Path for the resulting high‑resolution PDF file
            string pdfPath = "output.pdf";

            // Verify that the source file exists to avoid FileNotFoundException
            if (!File.Exists(sourcePath))
            {
                Console.WriteLine($"Error: Source file not found at '{sourcePath}'.");
                return;
            }

            try
            {
                // Load the workbook from the XLSX file
                Workbook workbook = new Workbook(sourcePath);

                // Create PDF save options – adjust options here if needed
                PdfSaveOptions pdfOptions = new PdfSaveOptions
                {
                    // Example option: preserve document structure (optional)
                    ExportDocumentStructure = true
                };

                // Save the workbook as a PDF
                workbook.Save(pdfPath, pdfOptions);

                Console.WriteLine($"Workbook successfully converted to PDF: {pdfPath}");
            }
            catch (Exception ex)
            {
                // Handle any runtime errors gracefully
                Console.WriteLine($"An error occurred during conversion: {ex.Message}");
            }
        }

        // Entry point required for the application
        public static void Main(string[] args)
        {
            Run();
        }
    }
}
