// Title: Verify ODS Page Background Graphic Appears in PDF Export with Aspose.Cells for .NET
// Description: Shows how to assign a tiled, centered PNG as the ODS page background of a worksheet, add sample data, and save the workbook as a PDF using PdfSaveOptions, so you can confirm the background image is rendered in the output file.
// Keywords: Aspose.Cells | ODSPageBackground | PDF export | C# | background image | tiled graphic | PdfSaveOptions | render verification
// Common Searches: Aspose.Cells set ODS page background image | export ODS background to PDF C# | verify background graphic in PDF generated by Aspose.Cells | tile centered image on ODS page and convert to PDF | C# code sample ODSPageBackground PDF output
// Developer Intent: Confirm that the ODS page background image is correctly rendered in the PDF produced by Aspose.Cells.
// Use Cases: Apply a tiled PNG as the ODS page background, export to PDF, and visually validate the graphic. | Load background image bytes from a file, assign them to ODSPageBackground, and check placement after conversion. | Add worksheet content over the background to test layering and ensure the image remains visible in the PDF.
// AI Prompts: Write C# code that programmatically verifies the ODS background graphic is embedded in the exported PDF using Aspose.Cells. | Explain how to extract the background image from a PDF generated by Aspose.Cells and compare it with the original PNG for validation. | Provide a unit‑test pattern for confirming ODS page background rendering in a PDF with Aspose.Cells for .NET.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Ods;
using Aspose.Cells.Rendering;

// Shows how to assign a tiled, centered PNG as the ODS page background of a worksheet, add sample data, and save the workbook as a PDF using PdfSaveOptions, so you can confirm the background image is rendered in the output file.
class VerifyOdsBackgroundInPdf
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Configure ODS page background to use a graphic
        OdsPageBackground background = worksheet.PageSetup.ODSPageBackground;
        background.Type = OdsPageBackgroundType.Graphic;
        background.GraphicType = OdsPageBackgroundGraphicType.Tile;
        background.GraphicPositionType = OdsPageBackgroundGraphicPositionType.CenterCenter;

        // Load image data and assign it to the background
        string imagePath = "background.png"; // Ensure this file exists in the executable directory
        if (File.Exists(imagePath))
        {
            background.GraphicData = File.ReadAllBytes(imagePath);
        }

        // Add some sample content to visualize the background in the PDF
        worksheet.Cells["A1"].PutValue("Content over ODS background graphic");

        // Save the workbook as PDF
        PdfSaveOptions pdfOptions = new PdfSaveOptions();
        workbook.Save("OdsBackgroundVerification.pdf", pdfOptions);
    }
}
