using System;
using Aspose.Cells;

namespace AsposeCellsGlobalizationDemo
{
    // Custom class that derives from SettableGlobalizationSettings
    // Allows us to change the default total name for a specific function.
    public class CustomGlobalizationSettings : SettableGlobalizationSettings
    {
        public CustomGlobalizationSettings()
        {
            // Change the label that will be used for the Sum total in subtotals.
            // This label appears in the "Total" row generated by the Subtotal method.
            SetTotalName(ConsolidationFunction.Sum, "Custom Sum Total");
        }
    }

    public class Program
    {
        public static void Main()
        {
            // ---------- Create a new workbook ----------
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Populate sample data that will be subtotaled
            cells["A1"].PutValue("Category");
            cells["B1"].PutValue("Amount");
            cells["A2"].PutValue("Food");
            cells["B2"].PutValue(120);
            cells["A3"].PutValue("Food");
            cells["B3"].PutValue(80);
            cells["A4"].PutValue("Drink");
            cells["B4"].PutValue(150);
            cells["A5"].PutValue("Drink");
            cells["B5"].PutValue(70);
            cells["A6"].PutValue("Other");
            cells["B6"].PutValue(200);

            // ---------- Assign custom globalization settings ----------
            // The settings must be applied BEFORE calling Subtotal so that the
            // generated subtotal labels use the customized text.
            workbook.Settings.GlobalizationSettings = new CustomGlobalizationSettings();

            // ---------- Add subtotals ----------
            // Define the range that contains the data (including header row)
            CellArea dataRange = CellArea.CreateCellArea(0, 0, 5, 1); // rows 0-5, columns 0-1

            // Subtotal on column 0 (Category) using Sum on column 1 (Amount)
            // Parameters:
            //   dataRange          - range to process
            //   columnIndex        - column to group by (Category)
            //   function           - ConsolidationFunction.Sum
            //   totalColumns       - array of column indexes to total (Amount)
            //   replace            - true to replace existing subtotals
            //   pageBreaks         - false (no page breaks)
            //   summaryBelow       - true (subtotal rows appear below each group)
            cells.Subtotal(dataRange, 0, ConsolidationFunction.Sum, new int[] { 1 }, true, false, true);

            // ---------- Save the workbook ----------
            workbook.Save("CustomGlobalizationSubtotal.xlsx");
        }
    }
}