// Title: Save a workbook with Japanese era‑formatted dates as PDF using Aspose.Cells in C#
// AI Prompts: Generate C# code that creates a workbook, sets its CultureInfo to ja-JP, applies a custom number format using the ggge era specifier, and saves the sheet as a PDF. | Show how to format a cell to display a Japanese era date (e.g., 令和5年4月1日) and export the workbook to PDF while preserving the era symbols with Aspose.Cells.
// Common Searches: C# Aspose.Cells export sheet to PDF with Japanese era date format | set workbook culture to ja-JP for PDF output using Aspose.Cells | custom number format ggge for Japanese era dates in PDF export | display 令和 era dates in PDF generated by Aspose.Cells .NET
// Tags: locale-aware Japanese era number format | Aspose.Cells PDF export with culture settings | C# workbook culture ja-JP | custom ggge era specifier | PDF rendering of Japanese calendar dates

using System;
using System.Globalization;
using Aspose.Cells;

// The example creates a workbook, sets its culture to Japanese (ja-JP), inserts a DateTime value, applies a custom number format that uses the ggge era specifier to show dates like 令和5年4月1日, auto‑fits the column, and saves the worksheet as a PDF, ensuring the era symbols are rendered correctly.
class JapaneseEraPdfExport
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Set the workbook's culture to Japanese (Japan) to enable era formatting
        workbook.Settings.CultureInfo = new CultureInfo("ja-JP");

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];
        Cells cells = sheet.Cells;

        // Insert a date value (e.g., 2023-04-01) into cell A1
        DateTime sampleDate = new DateTime(2023, 4, 1);
        cells["A1"].PutValue(sampleDate);

        // Apply a number format that displays the Japanese era (e.g., "令和5年4月1日")
        // The format string uses the locale-specific era symbol (ggge)
        Style eraStyle = workbook.CreateStyle();
        eraStyle.Custom = "[$-ja-JP]ggge\"年\"m\"月\"d\"日\"";
        cells["A1"].SetStyle(eraStyle);

        // Optionally adjust column width for better visibility
        sheet.AutoFitColumn(0);

        // Save the workbook as PDF; the era symbols will be rendered in the PDF output
        string pdfPath = "JapaneseEraDates.pdf";
        workbook.Save(pdfPath, SaveFormat.Pdf);

        Console.WriteLine($"Workbook saved as PDF at: {pdfPath}");
    }
}
