// Title: C# Aspose.Cells Example: 10‑Row Moving Average Using Shared R1C1 Formula
// Description: The sample creates a new workbook, populates 30 rows of numeric data in columns A‑C, and applies a 10‑row moving‑average to each column with SetSharedFormula using the R1C1 expression =AVERAGE(R[-9]C:R[-0]C). After calculating the formulas, the workbook is saved as MovingAverageResult.xlsx.
// Keywords: Aspose.Cells | C# | .NET | moving average | rolling average | shared formula | R1C1 notation | SetSharedFormula | Excel automation | sliding window average | calculate formulas
// Common Searches: Aspose.Cells set moving average formula | C# shared formula R1C1 Aspose.Cells | how to calculate rolling average in Aspose.Cells | apply same formula to multiple columns Aspose.Cells | SetSharedFormula example C#
// Developer Intent: Add a 10‑row rolling average to each data column using a shared R1C1 formula and save the calculated workbook.
// Use Cases: Financial reporting – compute a 10‑day moving average of stock prices across several columns. | Sales analysis – display a 10‑row average of daily sales figures for multiple product lines. | Time‑series preprocessing – embed rolling averages directly in Excel files generated by .NET applications.
// AI Prompts: Generate C# code that uses Aspose.Cells to apply a 7‑row moving average to columns D‑F with SetSharedFormula. | Modify the example to accept a user‑defined window size and apply the moving‑average formula to a configurable range of columns. | Show how to read the calculated moving‑average values from the worksheet after calling workbook.CalculateFormula(). | Explain the difference between A1 and R1C1 notation when using SetSharedFormula in Aspose.Cells.

using System;
using Aspose.Cells;

namespace MovingAverageExample
{
    // The sample creates a new workbook, populates 30 rows of numeric data in columns A‑C, and applies a 10‑row moving‑average to each column with SetSharedFormula using the R1C1 expression =AVERAGE(R[-9]C:R[-0]C). After calculating the formulas, the workbook is saved as MovingAverageResult.xlsx.
    class Program
    {
        static void Main()
        {
            // 1. Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // 2. Populate sample data in columns A, B and C (30 rows)
            int totalRows = 30;
            for (int row = 0; row < totalRows; row++)
            {
                // Example data: A = row+1, B = (row+1)*2, C = (row+1)*3
                cells[row, 0].PutValue(row + 1);          // Column A
                cells[row, 1].PutValue((row + 1) * 2);    // Column B
                cells[row, 2].PutValue((row + 1) * 3);    // Column C
            }

            // 3. Apply a moving‑average (window = 10 rows) formula to each column.
            //    The formula uses R1C1 notation so it can be shared across the range.
            //    For a cell in row r (1‑based), the formula is:
            //        =AVERAGE(R[-9]C:R[-0]C)
            //    which averages the current cell and the 9 cells above it.
            //    We start from row 11 because the first 10 rows do not have a full window.
            int windowSize = 10;
            int startDataRow = windowSize + 1;                     // Excel row number where formula starts
            int formulaRowsCount = totalRows - windowSize;         // Number of rows that will contain the formula

            // Apply the formula to column A
            Cell startCellA = cells[startDataRow - 1, 0]; // zero‑based indices
            startCellA.SetSharedFormula(
                "=AVERAGE(R[-9]C:R[-0]C)",   // R1C1 formula
                formulaRowsCount,            // rows to fill
                1,                           // columns to fill (single column)
                true,                        // isR1C1
                false);                      // isLocal (use invariant locale)

            // Apply the same formula to column B
            Cell startCellB = cells[startDataRow - 1, 1];
            startCellB.SetSharedFormula(
                "=AVERAGE(R[-9]C:R[-0]C)",
                formulaRowsCount,
                1,
                true,
                false);

            // Apply the same formula to column C
            Cell startCellC = cells[startDataRow - 1, 2];
            startCellC.SetSharedFormula(
                "=AVERAGE(R[-9]C:R[-0]C)",
                formulaRowsCount,
                1,
                true,
                false);

            // 4. Calculate all formulas so the moving‑average values are materialized
            workbook.CalculateFormula();

            // 5. Save the workbook
            workbook.Save("MovingAverageResult.xlsx");
        }
    }
}
