using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsArrayFormulaDemo
{
    class Program
    {
        static void Main()
        {
            const string inputPath = "InputDataTable.xlsx";
            const string outputPath = "OutputDataTableCalculated.xlsx";

            Workbook workbook;

            if (File.Exists(inputPath))
            {
                // Load existing workbook
                workbook = new Workbook(inputPath);
            }
            else
            {
                // Create a new workbook with sample data and a dynamic array formula
                workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Sample source data (A1:A5)
                cells["A1"].PutValue(1);
                cells["A2"].PutValue(2);
                cells["A3"].PutValue(3);
                cells["A4"].PutValue(4);
                cells["A5"].PutValue(5);

                // Dynamic array formula that generates a data table (C3)
                // Example: =SORT(A1:A5,1,TRUE)
                cells["C3"].Formula = "=SORT(A1:A5,1,TRUE)";
            }

            // Refresh dynamic array formulas (including those generated by data tables)
            // The 'true' flag also calculates the spilled range values.
            workbook.RefreshDynamicArrayFormulas(true);

            // Calculate all other formulas in the workbook.
            workbook.CalculateFormula();

            // Retrieve a calculated result from the top‑left cell of the data table.
            Worksheet firstSheet = workbook.Worksheets[0];
            Cell resultCell = firstSheet.Cells["C3"]; // top‑left cell of the data table
            Console.WriteLine("Top‑left data table value: " + resultCell.Value);

            // Save the workbook with the calculated results.
            workbook.Save(outputPath);
        }
    }
}