// Title: Create a named range and SUMIFS formula to aggregate monthly sales between two dates in an Aspose.Cells workbook (C#)
// AI Prompts: Generate C# code using Aspose.Cells that defines a named range for the Sales column and inserts a SUMIFS formula referencing start‑date and end‑date cells to compute total sales for the selected month. | Show how to programmatically set up start and end date cells, create a dynamic named range for the date column, and use it in a SUMIFS formula for monthly reporting with Aspose.Cells. | Provide a C# snippet that saves the workbook to a specified path, ensuring the output directory exists, after adding the named range and SUMIFS calculation.
// Common Searches: aspnet c# how to add a named range for a column in Aspose.Cells | using SUMIFS with date criteria in Aspose.Cells C# example | dynamic monthly sales report Excel generated by Aspose.Cells C# | create date‑driven SUMIFS formula programmatically with Aspose.Cells | save Aspose.Cells workbook to custom folder ensuring directory exists
// Tags: Aspose.Cells create named range C# | SUMIFS formula with date criteria Aspose.Cells | dynamic monthly sales aggregation Excel | C# workbook save with directory check Aspose.Cells | Excel report generation Aspose.Cells C#

using Aspose.Cells;
using System;
using System.IO;

// The example creates a new workbook, adds headers and sample monthly sales data, places start and end dates in cells, defines a named range for the Sales column, inserts a SUMIFS formula that uses the date range to calculate total sales for the chosen month, and saves the workbook to a specified location while ensuring the output directory exists.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            sheet.Name = "SalesData";

            // Add header row
            sheet.Cells["A1"].PutValue("Date");
            sheet.Cells["B1"].PutValue("Region");
            sheet.Cells["C1"].PutValue("Sales");

            // Populate sample monthly sales data (12 rows)
            DateTime startDate = new DateTime(2023, 1, 1);
            for (int i = 0; i < 12; i++)
            {
                // Date column (A)
                sheet.Cells[i + 1, 0].PutValue(startDate.AddMonths(i));
                // Region column (B)
                sheet.Cells[i + 1, 1].PutValue("North");
                // Sales column (C) – example values
                sheet.Cells[i + 1, 2].PutValue(1000 + i * 150);
            }

            // Cells E1 and E2 will hold the start and end dates for the month to aggregate
            sheet.Cells["E1"].PutValue(new DateTime(2023, 1, 1));   // Start of month
            sheet.Cells["E2"].PutValue(new DateTime(2023, 1, 31)); // End of month

            // Build the SUMIFS formula:
            // =SUMIFS(C2:C13, A2:A13, ">=E1", A2:A13, "<=E2")
            string sumIfsFormula = "=SUMIFS(C2:C13, A2:A13, \">=\"&E1, A2:A13, \"<=\"&E2)";

            // Place the formula directly in a cell for verification (named ranges are not used here)
            sheet.Cells["G1"].Formula = sumIfsFormula;

            // Define output file path
            string outputPath = "MonthlySalesReport.xlsx";

            // Ensure the directory exists (if a path is provided)
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the workbook
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
