// Title: Iterative formula calculation with 100‑iteration limit for circular references in Aspose.Cells .NET
// AI Prompts: Write C# code that creates a circular reference between A1 and B1 and uses a manual loop with Workbook.CalculateFormula() to iterate up to 100 times, breaking when the change is below 0.001. | Show how to enable iterative calculation in Aspose.Cells, set the maximum iteration count and convergence tolerance, then save the workbook after the values stabilize. | Add comprehensive error handling and ensure the output directory exists before writing the workbook generated by the iterative calculation.
// Common Searches: Aspose.Cells .NET iterative calculation example with circular reference and max 100 iterations | C# how to resolve circular reference formulas using Aspose.Cells iterative loop | Set convergence tolerance for formula evaluation in an Aspose.Cells workbook | Configure iterative formula evaluation settings in Aspose.Cells for .NET projects
// Tags: iterative calculation Aspose.Cells .NET | circular reference handling Aspose.Cells | max iterations workbook formula | convergence tolerance Excel formulas | manual formula loop Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

// The sample creates a new workbook, defines a circular reference between cells A1 and B1, then manually iterates formula calculation up to 100 times, stopping when the change between iterations is less than 0.001. It outputs the final values, ensures the output folder exists, and saves the workbook as IterativeCalculation.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Set up a circular reference:
            // A1 = B1 + 1
            // B1 = A1 + 1
            cells["A1"].Formula = "=B1+1";
            cells["B1"].Formula = "=A1+1";

            // Manual iterative calculation (fallback for versions without built‑in iterative settings)
            const int maxIterations = 100;
            const double maxChange = 0.001;
            double prevA1 = double.NaN;
            double prevB1 = double.NaN;

            for (int i = 0; i < maxIterations; i++)
            {
                workbook.CalculateFormula();

                double curA1 = cells["A1"].DoubleValue;
                double curB1 = cells["B1"].DoubleValue;

                // Check convergence
                if (!double.IsNaN(prevA1) && !double.IsNaN(prevB1))
                {
                    if (Math.Abs(curA1 - prevA1) < maxChange && Math.Abs(curB1 - prevB1) < maxChange)
                    {
                        break;
                    }
                }

                prevA1 = curA1;
                prevB1 = curB1;
            }

            // Retrieve and display the calculated values
            double valueA1 = cells["A1"].DoubleValue;
            double valueB1 = cells["B1"].DoubleValue;

            Console.WriteLine($"A1 = {valueA1}");
            Console.WriteLine($"B1 = {valueB1}");

            // Save the workbook (optional)
            string outputPath = "IterativeCalculation.xlsx";

            // Ensure the directory exists before saving
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved to {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
