// Title: Detect and List #DIV/0! Errors with Aspose.Cells for .NET (C#)
// Description: This example creates a workbook, adds formulas (including a division‑by‑zero), runs Workbook.CalculateFormula, enables evaluation‑error checking via ErrorCheckOptionCollection, scans the used range for cells whose StringValue is "#DIV/0!", collects their addresses, prints them, and saves the file.
// Keywords: Aspose.Cells error checking C# | Detect #DIV/0! Aspose.Cells | ErrorCheckOption Aspose.Cells | Retrieve error cell addresses .NET | Excel division by zero detection C# | Workbook.CalculateFormula error handling | Aspose.Cells sample GitHub
// Common Searches: Aspose.Cells enable evaluation error checking C# | list cells with #DIV/0! after calculation Aspose.Cells | ErrorCheckOptionCollection example .NET | find error values in worksheet using Aspose.Cells | C# code to detect division by zero in Excel with Aspose
// Developer Intent: Identify cells that produce #DIV/0! after formula evaluation and obtain their addresses using Aspose.Cells for .NET.
// Use Cases: Configure ErrorCheckOptionCollection to flag evaluation errors across a worksheet. | Run Workbook.CalculateFormula then iterate the used range to capture cells where IsErrorValue is true and StringValue equals "#DIV/0!". | Generate a report of error cell addresses or log them for data validation. | Save the workbook after error analysis for further processing.
// AI Prompts: Provide C# code that adds an ErrorCheckOption to enable evaluation error checking in Aspose.Cells and returns all cell addresses containing #DIV/0!. | Show a step‑by‑step example of scanning a worksheet after CalculateFormula to collect division‑by‑zero errors using Aspose.Cells. | Explain how to combine ErrorCheckOptionCollection with cell iteration to log #DIV/0! errors in an Excel file generated by Aspose.Cells.

using System;
using System.Collections.Generic;
using Aspose.Cells;

namespace AsposeCellsErrorCheckDemo
{
    // This example creates a workbook, adds formulas (including a division‑by‑zero), runs Workbook.CalculateFormula, enables evaluation‑error checking via ErrorCheckOptionCollection, scans the used range for cells whose StringValue is "#DIV/0!", collects their addresses, prints them, and saves the file.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (lifecycle rule: create)
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Set formulas, some of which will cause #DIV/0! errors
            cells["A1"].Formula = "=1/0";          // Division by zero
            cells["A2"].Formula = "=10/2";         // Valid formula
            cells["A3"].Formula = "=A1+5";         // Dependent on error cell
            cells["B1"].Formula = "=SUM(5,5)";     // Valid formula

            // Calculate all formulas
            workbook.CalculateFormula();

            // Enable error checking for evaluation errors on the used range
            ErrorCheckOptionCollection errorOptions = sheet.ErrorCheckOptions;
            int optIdx = errorOptions.Add();                       // Add a new option
            ErrorCheckOption opt = errorOptions[optIdx];
            // Ensure evaluation errors (including #DIV/0!) are checked
            opt.SetErrorCheck(ErrorCheckType.EvaluationError, true);
            // Apply the option to the whole sheet
            CellArea fullArea = CellArea.CreateCellArea(0, 0, cells.MaxDataRow, cells.MaxDataColumn);
            opt.AddRange(fullArea);

            // Collect addresses of cells that contain #DIV/0! errors
            List<string> divZeroCells = new List<string>();
            for (int row = 0; row <= cells.MaxDataRow; row++)
            {
                for (int col = 0; col <= cells.MaxDataColumn; col++)
                {
                    Cell cell = cells[row, col];
                    if (cell.IsErrorValue && cell.StringValue == "#DIV/0!")
                    {
                        divZeroCells.Add(cell.Name);
                    }
                }
            }

            // Output the collected cell addresses
            Console.WriteLine("Cells with #DIV/0! errors:");
            foreach (string address in divZeroCells)
            {
                Console.WriteLine(address);
            }

            // Save the workbook (lifecycle rule: save)
            workbook.Save("ErrorCheckDivZeroDemo.xlsx");
        }
    }
}
