// Title: Generate a CSV log of Excel formula errors with cell address and timestamp using Aspose.Cells for .NET
// AI Prompts: Write C# code that opens an .xlsx workbook with Aspose.Cells, forces full formula calculation, scans every worksheet for cells whose evaluated value begins with '#', and writes a CSV file containing the cell address, the error string, and the current ISO‑8601 timestamp. | Create a reusable C# method that takes a Workbook object and returns a collection of objects each holding worksheet name, cell address, error type, and calculation time for all formula errors detected by Aspose.Cells. | Adapt the example to output the error information as a JSON array instead of CSV while preserving worksheet, address, error, and timestamp fields.
// Common Searches: aspnet export formula error cells to csv using aspose.cells | c# log #N/A and #DIV/0! errors from Excel workbook | how to get cell address of formula error with Aspose.Cells | add timestamp to Excel error report generated by Aspose.Cells | iterate used range to find formula errors in .NET
// Tags: export formula error log csv Aspose.Cells | detect Excel formula errors .NET | calculate workbook formulas Aspose.Cells | iterate used range Aspose.Cells | add timestamp to error report C#

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;

// The example loads an Excel file with Aspose.Cells, forces calculation of all formulas, iterates each worksheet's used range to identify cells whose result starts with '#', captures the cell address, error string, and current ISO‑8601 timestamp, and writes these details to a CSV file.
class FormulaErrorLogger
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "FormulaErrorLog.csv";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file not found: {Path.GetFullPath(inputPath)}");
                return;
            }

            // Load the workbook
            Workbook workbook = new Workbook(inputPath);

            // Calculate all formulas so that error values are materialized
            workbook.CalculateFormula();

            // Prepare CSV header
            List<string> logLines = new List<string>
            {
                "CellAddress,ErrorType,Timestamp"
            };

            // Iterate through all worksheets
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Get the used range of the worksheet
                var usedRange = sheet.Cells.MaxDisplayRange; // Aspose.Cells.Range

                // If the worksheet is empty, skip it
                if (usedRange == null || usedRange.RowCount == 0 || usedRange.ColumnCount == 0)
                    continue;

                int startRow = usedRange.FirstRow;
                int endRow = startRow + usedRange.RowCount - 1;
                int startCol = usedRange.FirstColumn;
                int endCol = startCol + usedRange.ColumnCount - 1;

                // Iterate through each cell in the used range
                for (int row = startRow; row <= endRow; row++)
                {
                    for (int col = startCol; col <= endCol; col++)
                    {
                        Cell cell = sheet.Cells[row, col];

                        // Process only formula cells
                        if (cell.IsFormula)
                        {
                            // After calculation, an error appears as a string starting with '#'
                            if (cell.Value is string valueStr && valueStr.StartsWith("#"))
                            {
                                string address = cell.Name;                     // e.g., "A1"
                                string errorType = valueStr;                    // e.g., "#DIV/0!"
                                string timestamp = DateTime.Now.ToString("o"); // ISO 8601

                                logLines.Add($"{address},{errorType},{timestamp}");
                            }
                        }
                    }
                }
            }

            // Write the log to a CSV file
            File.WriteAllLines(outputPath, logLines);
            Console.WriteLine($"Formula error log written to: {Path.GetFullPath(outputPath)}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
