// Title: Aspose.Cells for .NET – Clear a Dynamic Array Spill Range Without Removing the Formula
// Description: C# sample that builds a workbook, writes a dynamic array formula (e.g., =SEQUENCE(3,2)) in A1, forces calculation, retrieves the full array area with GetArrayRange, loops through the spill cells, skips the header cell, clears each spill cell using PutValue(null) while handling CellsException, and saves the file as DynamicArraySpillCleared.xlsx.
// Keywords: Aspose.Cells | C# | dynamic array | spill range | GetArrayRange | PutValue null | SEQUENCE formula | clear array output | .NET spreadsheet | Excel dynamic array handling
// Common Searches: clear dynamic array spill Aspose.Cells | preserve formula cell while deleting spill values .NET | remove SEQUENCE output without erasing formula | Aspose.Cells GetArrayRange usage example | C# erase spilled cells of Excel dynamic array
// Developer Intent: Erase the values generated by a dynamic array formula while keeping the original formula cell intact.
// Use Cases: Refresh a SEQUENCE‑based report by wiping previous results before recomputation. | Provide a UI button that empties only the spill area of a dynamic array without affecting the formula. | Automate cleanup of leftover spill data in generated workbooks to maintain a clean output sheet.
// AI Prompts: Show C# code that clears the spill range of a dynamic array formula in Aspose.Cells while leaving the formula cell untouched. | Explain how GetArrayRange and PutValue(null) can be combined to delete spilled values safely and handle possible CellsException. | Give a step‑by‑step tutorial for resetting a SEQUENCE spill area without removing the originating formula in a .NET workbook.

using System;
using Aspose.Cells;

namespace AsposeCellsDynamicArrayClearSpill
{
    // C# sample that builds a workbook, writes a dynamic array formula (e.g., =SEQUENCE(3,2)) in A1, forces calculation, retrieves the full array area with GetArrayRange, loops through the spill cells, skips the header cell, clears each spill cell using PutValue(null) while handling CellsException, and saves the file as DynamicArraySpillCleared.xlsx.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook and get the first worksheet
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];
                Cells cells = sheet.Cells;

                // Set a dynamic array formula in cell A1 (will spill to a 3x2 range)
                Cell formulaCell = cells["A1"];
                formulaCell.SetDynamicArrayFormula("=SEQUENCE(3,2)", new FormulaParseOptions(), true);

                // Calculate formulas so the spill range is populated
                workbook.CalculateFormula();

                // Retrieve the full array range (including the header cell A1)
                CellArea arrayRange = formulaCell.GetArrayRange();

                // Clear the spilled cells while keeping the original formula cell intact
                for (int row = arrayRange.StartRow; row <= arrayRange.EndRow; row++)
                {
                    for (int col = arrayRange.StartColumn; col <= arrayRange.EndColumn; col++)
                    {
                        // Skip the header cell that contains the formula
                        if (row == arrayRange.StartRow && col == arrayRange.StartColumn)
                            continue;

                        try
                        {
                            // Clear the content of the spill cell.
                            // Using PutValue(null) to remove the value safely.
                            cells[row, col].PutValue(null);
                        }
                        catch (CellsException)
                        {
                            // If clearing fails (e.g., due to array restrictions), ignore and continue.
                        }
                    }
                }

                // Save the workbook to a file
                workbook.Save("DynamicArraySpillCleared.xlsx");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
