// Title: Export a worksheet to PDF with Letter paper size and 300 DPI using Aspose.Cells for .NET
// AI Prompts: Create a PDF from a worksheet in Aspose.Cells, set the page setup to Letter size, and ensure the output uses 300 DPI. | Configure PdfSaveOptions in C# to generate a high‑resolution PDF while keeping the default margins in Aspose.Cells. | Show how to apply custom margins and paper size before saving a workbook as a 300 DPI PDF with Aspose.Cells.
// Common Searches: how to set PDF DPI to 300 in Aspose.Cells C# | Aspose.Cells export worksheet to PDF with Letter paper size | increase image quality of PDF generated by Aspose.Cells .NET | adjust margins and paper size before saving workbook as PDF using Aspose.Cells | default DPI of PdfSaveOptions in Aspose.Cells
// Tags: Aspose.Cells generate PDF with Letter paper dimensions | PdfSaveOptions DPI configuration | worksheet page setup margins C# Aspose.Cells | high‑resolution PDF creation from workbook | C# Aspose.Cells custom paper size handling

using System;
using Aspose.Cells;
using Aspose.Cells.Saving;

// The example creates a new workbook, writes sample data, sets the worksheet's paper size to Letter, optionally adjusts margins, uses PdfSaveOptions (which defaults to 300 DPI) to configure the PDF output, and saves the workbook as a high‑resolution PDF file.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate some sample data
            sheet.Cells["A1"].PutValue("Hello, Aspose.Cells!");
            sheet.Cells["A2"].PutValue(DateTime.Now);

            // Set a standard paper size (Letter) – custom dimensions are read‑only in this API version
            PageSetup pageSetup = sheet.PageSetup;
            pageSetup.PaperSize = PaperSizeType.PaperLetter;

            // Optional: adjust margins (in inches)
            pageSetup.LeftMargin = 0.5;
            pageSetup.RightMargin = 0.5;
            pageSetup.TopMargin = 0.5;
            pageSetup.BottomMargin = 0.5;

            // Configure PDF save options (default DPI is 300)
            PdfSaveOptions pdfOptions = new PdfSaveOptions();

            // Save the workbook as a PDF with the specified options
            workbook.Save("CustomPaper_300DPI.pdf", pdfOptions);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
