// Title: Create a column chart with the legend positioned at the bottom using Aspose.Cells for .NET (C#)
// AI Prompts: Write C# code that builds a column chart from worksheet data and sets the chart legend to the bottom using Aspose.Cells. | Show how to configure Legend.Position = LegendPositionType.Bottom for an Aspose.Cells chart in a .NET application. | Provide a complete example that populates sales data, adds a column chart, and moves the legend below the chart with Aspose.Cells.
// Common Searches: Aspose.Cells C# how to place chart legend at the bottom of an Excel sheet | set legend position bottom for column chart using Aspose.Cells .NET | example of moving Excel chart legend below the chart with Aspose.Cells in C# | C# Aspose.Cells chart legend placement bottom tutorial | bottom legend for column chart generated by Aspose.Cells
// Tags: Aspose.Cells chart legend position bottom | C# column chart creation with Aspose.Cells | set Excel chart legend location using Aspose.Cells | Aspose.Cells legend placement for worksheet charts | bottom legend configuration in Aspose.Cells .NET | Aspose.Cells column chart example C#

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

// Demonstrates creating a new workbook, adding sample sales data, generating a column chart, setting its legend to the bottom via Legend.Position, and saving the file as ChartWithBottomLegend.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            sheet.Cells["A1"].PutValue("Month");
            sheet.Cells["B1"].PutValue("Sales");
            sheet.Cells["A2"].PutValue("Jan");
            sheet.Cells["A3"].PutValue("Feb");
            sheet.Cells["A4"].PutValue("Mar");
            sheet.Cells["B2"].PutValue(120);
            sheet.Cells["B3"].PutValue(150);
            sheet.Cells["B4"].PutValue(130);

            // Add a column chart to the worksheet
            int chartIndex = sheet.Charts.Add(ChartType.Column, 5, 0, 20, 10);
            Chart chart = sheet.Charts[chartIndex];

            // Set the data range for the chart series
            chart.NSeries.Add("B2:B4", true);
            // Category data (months) is automatically taken from the first column,
            // so explicit CategoryData assignment is omitted for compatibility.

            // Position the legend at the bottom of the chart
            chart.Legend.Position = LegendPositionType.Bottom;

            // Define output file path
            string outputPath = "ChartWithBottomLegend.xlsx";

            // Save the workbook
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
