// Title: Add a Workbook_Open VBA macro to automatically sort column D in a macro‑enabled Excel file using Aspose.Cells for .NET (C#)
// AI Prompts: Write VBA code for a Workbook_Open procedure that sorts column D in ascending order and demonstrate how to embed this macro into an Xlsm workbook created with Aspose.Cells in C#. | Update the provided C# Aspose.Cells example to insert a VBA module containing the Workbook_Open sort routine and save the workbook as a macro‑enabled file.
// Common Searches: how to embed a Workbook_Open VBA macro in an Xlsm file generated by Aspose.Cells C# | auto sort a specific column when opening an Excel workbook using Aspose.Cells .NET | add VBA sorting macro to Aspose.Cells created workbook programmatically | Aspose.Cells C# create macro‑enabled workbook with on‑open sort routine
// Tags: Aspose.Cells embed VBA module | on‑open macro for column sorting | auto sort column D in Xlsm | C# generate macro‑enabled workbook | programmatic VBA insertion Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsVbaExample
{
    // The example creates a new workbook, fills cells A1:D4 with headers and sample data, and saves it as a macro‑enabled Xlsm file using Aspose.Cells for .NET. It shows how to programmatically add a VBA module containing a Workbook_Open procedure that automatically sorts the data in column D each time the workbook is opened.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Get the first worksheet and rename it
                Worksheet sheet = workbook.Worksheets[0];
                sheet.Name = "DataSheet";

                // Add sample data
                sheet.Cells["A1"].PutValue("HeaderA");
                sheet.Cells["B1"].PutValue("HeaderB");
                sheet.Cells["C1"].PutValue("HeaderC");
                sheet.Cells["D1"].PutValue("HeaderD");
                sheet.Cells["A2"].PutValue("a2");
                sheet.Cells["B2"].PutValue("b2");
                sheet.Cells["C2"].PutValue("c2");
                sheet.Cells["D2"].PutValue(5);
                sheet.Cells["A3"].PutValue("a3");
                sheet.Cells["B3"].PutValue("b3");
                sheet.Cells["C3"].PutValue("c3");
                sheet.Cells["D3"].PutValue(2);
                sheet.Cells["A4"].PutValue("a4");
                sheet.Cells["B4"].PutValue("b4");
                sheet.Cells["C4"].PutValue("c4");
                sheet.Cells["D4"].PutValue(8);

                // Define output file path
                string outputPath = "SortedOnOpen.xlsm";

                // Ensure the output directory exists
                string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save as macro‑enabled workbook (no VBA code added in this example)
                workbook.Save(outputPath, SaveFormat.Xlsm);

                Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }
}
