// Title: Apply a custom currency format to a price column and freeze the totals row in an Excel worksheet using Aspose.Cells for .NET
// AI Prompts: Generate an Excel workbook where the Price column uses the custom format $#,##0.00, includes a summed totals row, and the totals row remains fixed during scrolling, implemented with Aspose.Cells in C#. | Write C# code that creates a monetary style, applies it to a specific column range and the totals cell, then uses FreezePanes to lock rows through the totals row using Aspose.Cells. | Provide a .NET example that builds an item‑price table, adds a ListObject with a total, sets a currency number format, and anchors the top rows with Aspose.Cells.
// Common Searches: Aspose.Cells .NET how to apply $#,##0.00 format to a column range | C# freeze top rows after totals row in Excel with Aspose.Cells | Add a totals row to a ListObject and format as currency using Aspose.Cells | Keep totals row visible while scrolling in Excel generated by Aspose.Cells C# | Set custom monetary number format for price column in Aspose.Cells workbook
// Tags: custom monetary style Aspose.Cells .NET | apply currency format to column range Aspose.Cells | add totals row to ListObject Aspose.Cells | freeze panes up to totals row Aspose.Cells | Excel workbook monetary formatting C#

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Tables;

namespace AsposeCellsExamples
{
    // The example creates a new workbook, fills an item‑price table, converts the Price column into a ListObject with a summed totals row, defines a custom "$#,##0.00" style applied to the price data and the totals cell, freezes all rows through the totals row so it stays visible while scrolling, and saves the file as MonetaryFormatAndFreezeTotals.xlsx.
    public class MonetaryFormatAndFreezeTotals
    {
        public static void Main(string[] args)
        {
            try
            {
                Run();
                Console.WriteLine("Workbook created successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }

        public static void Run()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];
            Cells cells = worksheet.Cells;

            // ----- Populate sample data -----
            // Header
            cells["A1"].PutValue("Item");
            cells["B1"].PutValue("Price");

            // Data rows
            string[] items = { "Apple", "Banana", "Orange", "Grape" };
            double[] prices = { 1.25, 0.80, 1.50, 2.10 };

            for (int i = 0; i < items.Length; i++)
            {
                cells[i + 2, 0].PutValue(items[i]);   // Column A (Item)
                cells[i + 2, 1].PutValue(prices[i]); // Column B (Price)
            }

            // ----- Create a table (ListObject) -----
            // Table range: from A1 to B{last data row}
            int lastDataRow = items.Length + 1; // zero‑based index of last data row
            int tableIndex = worksheet.ListObjects.Add(0, 0, lastDataRow, 1, true);
            ListObject table = worksheet.ListObjects[tableIndex];
            table.ShowTotals = true;                     // Enable totals row
            table.ListColumns[1].TotalsCalculation = TotalsCalculation.Sum; // Sum for Price column

            // ----- Define monetary number format -----
            Style moneyStyle = workbook.CreateStyle();
            moneyStyle.Custom = "$#,##0.00"; // Custom format for currency

            // Apply the format to the Price column (data rows)
            StyleFlag flag = new StyleFlag();
            flag.NumberFormat = true; // Only number format will be applied

            // Range: rows 2..lastDataRow (zero‑based), column 1 (Price)
            Aspose.Cells.Range priceDataRange = cells.CreateRange(1, 1, items.Length, 1);
            priceDataRange.ApplyStyle(moneyStyle, flag);

            // Apply the same format to the totals cell (the cell just below the data)
            int totalsRowIndex = lastDataRow + 1; // zero‑based index of totals row
            Cell totalsCell = cells[totalsRowIndex, 1];
            totalsCell.SetStyle(moneyStyle);

            // ----- Freeze rows up to the totals row -----
            // Freeze the top (totalsRowIndex + 1) rows so the totals row stays visible while scrolling
            worksheet.FreezePanes(totalsRowIndex + 1, 0, totalsRowIndex + 1, 0);

            // Save the workbook
            string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "MonetaryFormatAndFreezeTotals.xlsx");
            workbook.Save(outputPath);
        }
    }
}
