// Title: Set worksheet‑specific paper sizes with Aspose.Cells for .NET using a dictionary
// Description: A C# example that builds a case‑insensitive dictionary of worksheet names to Aspose.Cells PaperSizeType values, loads a workbook, applies the mapped paper size to each matching sheet’s PageSetup, and saves the result.
// Keywords: Aspose.Cells C# paper size | worksheet page setup .NET | PaperSizeType mapping | dictionary Excel automation | set sheet paper size programmatically | Aspose.Cells worksheet configuration | Excel print settings C# | per‑sheet paper size Aspose
// Common Searches: Aspose.Cells set different paper sizes per worksheet | C# map sheet name to PaperSizeType | how to change page setup for specific Excel sheets using Aspose | automate worksheet paper size in .NET | dictionary based paper size assignment Aspose.Cells
// Developer Intent: Assign distinct paper sizes to selected worksheets based on a configurable name‑to‑size map.
// Use Cases: Print a "Summary" sheet on A4 while printing "Details" on Letter without manual adjustments. | Enforce Legal size for all "Report" tabs generated by an automated reporting pipeline. | Leave sheets without a defined mapping unchanged, preserving any existing page‑setup settings.
// AI Prompts: Generate C# code that reads a JSON file of worksheet‑to‑paper‑size mappings and applies them with Aspose.Cells. | Show how to add a fallback default paper size when a worksheet name is not present in the dictionary. | Provide robust error handling for missing files and invalid PaperSizeType values while configuring page setup.

using System;
using System.Collections.Generic;
using Aspose.Cells;

namespace AsposeCellsPaperSizeConfig
{
    // A C# example that builds a case‑insensitive dictionary of worksheet names to Aspose.Cells PaperSizeType values, loads a workbook, applies the mapped paper size to each matching sheet’s PageSetup, and saves the result.
    class Program
    {
        static void Main()
        {
            // Define a mapping between worksheet names and desired paper sizes.
            // The key is the worksheet name, the value is the corresponding PaperSizeType.
            var sheetPaperSizeMap = new Dictionary<string, PaperSizeType>(StringComparer.OrdinalIgnoreCase)
            {
                { "Summary", PaperSizeType.PaperA4 },
                { "Details", PaperSizeType.PaperLetter },
                { "Report",  PaperSizeType.PaperLegal }
            };

            // Load an existing workbook (replace with your actual file path).
            // This follows the required lifecycle rule for loading a workbook.
            Workbook workbook = new Workbook("InputWorkbook.xlsx");

            // Iterate through all worksheets in the workbook.
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Check if the current worksheet name exists in the configuration map.
                if (sheetPaperSizeMap.TryGetValue(sheet.Name, out PaperSizeType paperSize))
                {
                    // Apply the configured paper size to the worksheet's PageSetup.
                    sheet.PageSetup.PaperSize = paperSize;
                    Console.WriteLine($"Set paper size of sheet '{sheet.Name}' to {paperSize}.");
                }
                else
                {
                    // If no specific mapping is found, you can optionally set a default size.
                    // Here we leave the existing setting unchanged.
                    Console.WriteLine($"No paper size mapping for sheet '{sheet.Name}'. Skipping.");
                }
            }

            // Save the modified workbook to a new file.
            // This follows the required lifecycle rule for saving a workbook.
            workbook.Save("OutputWorkbook.xlsx", SaveFormat.Xlsx);
            Console.WriteLine("Workbook saved with updated paper sizes.");
        }
    }
}
