// Title: Add value and category data labels to a column chart and freeze the header row in an Excel workbook using Aspose.Cells for .NET (C#)
// AI Prompts: Create a C# console application that builds an Excel workbook, populates a table, inserts a column chart, turns on data labels to display both the numeric values and the category names, and then freezes the top row so it remains visible. | Write a .NET snippet using Aspose.Cells that adds a column chart from a range, enables ShowValue and ShowCategoryName on the series' DataLabels, applies FreezePanes to lock the header row, and saves the file as an .xlsx.
// Common Searches: Aspose.Cells how to display category names on column chart data labels in C# | C# Aspose.Cells freeze top worksheet row after adding chart | enable value and category data labels for chart using Aspose.Cells .NET | apply FreezePanes to keep header visible in Excel generated by Aspose.Cells | create column chart from range and show data labels with Aspose.Cells C#
// Tags: Aspose.Cells chart data labels C# | Aspose.Cells freeze panes Excel | column chart with value and category labels Aspose.Cells | generate Excel workbook with chart Aspose.Cells | lock header row using FreezePanes Aspose.Cells

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Charts;

namespace AsposeCellsChartDataLabelsAndFreeze
{
    // The example creates a new workbook, fills cells A1:B5 with sample data, adds a column chart referencing the values, enables data labels to show both values and category names, freezes the first worksheet row to keep the header visible, and saves the result as ChartWithDataLabelsAndFrozenRows.xlsx.
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Create a new workbook
                Workbook workbook = new Workbook();

                // Access the first worksheet
                Worksheet sheet = workbook.Worksheets[0];

                // Populate sample data (A1:B5)
                sheet.Cells["A1"].PutValue("Category");
                sheet.Cells["B1"].PutValue("Value");
                sheet.Cells["A2"].PutValue("Jan");
                sheet.Cells["A3"].PutValue("Feb");
                sheet.Cells["A4"].PutValue("Mar");
                sheet.Cells["A5"].PutValue("Apr");
                sheet.Cells["B2"].PutValue(10);
                sheet.Cells["B3"].PutValue(20);
                sheet.Cells["B4"].PutValue(30);
                sheet.Cells["B5"].PutValue(40);

                // Add a column chart
                int chartIndex = sheet.Charts.Add(ChartType.Column, 7, 0, 25, 10);
                Chart chart = sheet.Charts[chartIndex];

                // Set the data source for the chart series (values)
                chart.NSeries.Add("B2:B5", true);
                // Set the category (X‑axis) data for the series
                // Note: CategoryData property may not be available in older versions;
                // if unavailable, the chart will use default numeric categories.
                // Uncomment the following line if your Aspose.Cells version supports it.
                // chart.NSeries[0].CategoryData = "A2:A5";

                // Enable data labels to show values and category names
                chart.NSeries[0].DataLabels.ShowValue = true;
                chart.NSeries[0].DataLabels.ShowCategoryName = true;

                // Freeze the top row (header) so it stays visible while scrolling
                sheet.FreezePanes(1, 0, 1, 0); // freezes row 0 (the header)

                // Determine output path and ensure directory exists
                string outputFile = "ChartWithDataLabelsAndFrozenRows.xlsx";
                string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputFile));

                if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
                {
                    Directory.CreateDirectory(outputDir);
                }

                // Save the workbook
                workbook.Save(outputFile);
                Console.WriteLine($"Workbook saved successfully to '{outputFile}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
