// Title: Show screen gridlines and hide them when printing with Aspose.Cells for .NET
// Description: Creates a workbook, enables worksheet.IsGridlinesVisible for on‑screen display, disables PageSetup.PrintGridlines for print output, adds sample cells, and saves the file.
// Keywords: Aspose.Cells | C# | gridlines | IsGridlinesVisible | PrintGridlines | Excel printing | hide gridlines in print | show gridlines on screen | worksheet formatting | PageSetup
// Common Searches: Aspose.Cells show gridlines on screen only | hide gridlines in printed Excel using Aspose.Cells | C# set worksheet gridlines visibility for print | PageSetup.PrintGridlines example | IsGridlinesVisible property usage
// Developer Intent: Display gridlines while editing but omit them from printed pages.
// Use Cases: Data‑entry worksheets where gridlines aid navigation on screen yet printed reports need a clean look. | Excel templates generated by an application that show gridlines during editing but produce grid‑free PDFs for distribution. | Automated report exports where on‑screen readability is enhanced by gridlines, but the final hard copy must appear professional.
// AI Prompts: Generate C# code with Aspose.Cells that turns on worksheet gridlines for viewing and turns them off for printing. | Provide a function that accepts a boolean to toggle IsGridlinesVisible and PrintGridlines for multiple worksheets. | Explain how to configure gridline visibility globally across a workbook using Aspose.Cells PageSetup settings.

using System;
using Aspose.Cells;

// Creates a workbook, enables worksheet.IsGridlinesVisible for on‑screen display, disables PageSetup.PrintGridlines for print output, adds sample cells, and saves the file.
class Program
{
    static void Main()
    {
        // Create a new workbook
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet worksheet = workbook.Worksheets[0];

        // Show gridlines on screen
        worksheet.IsGridlinesVisible = true;

        // Hide gridlines when the sheet is printed
        worksheet.PageSetup.PrintGridlines = false;

        // Add sample data to visualize the gridlines on screen
        worksheet.Cells["A1"].PutValue("Screen: Gridlines Visible");
        worksheet.Cells["A2"].PutValue("Print: Gridlines Hidden");

        // Save the workbook
        workbook.Save("GridlinesDemo.xlsx");
    }
}
