// Title: Enable formula view instead of calculated values in an Aspose.Cells .NET workbook for debugging
// AI Prompts: Generate C# code that creates an Excel workbook with Aspose.Cells, inserts a formula, sets WorkbookSettings.ShowFormula to true, and saves the file so the worksheet displays the formulas. | Provide a concise example that populates referenced cells, applies a SUM formula, toggles the ShowFormula option, and notes how to handle versions where the property is missing.
// Common Searches: C# Aspose.Cells show formulas in worksheet instead of results | How to turn on formula display when saving Excel file with Aspose.Cells | Aspose.Cells WorkbookSettings.ShowFormula not available version workaround | Debug Excel formulas using Aspose.Cells by displaying them in the sheet | Enable formula view for Excel output generated by Aspose.Cells .NET
// Tags: Aspose.Cells WorkbookSettings.ShowFormula | display formulas in Excel workbook C# | debug Excel formulas with Aspose.Cells | save workbook with formulas visible | toggle formula view Aspose.Cells .NET

using System;
using System.IO;
using Aspose.Cells;

// The example creates a new workbook, inserts a SUM formula in cell A1, fills cells B1:B5 with values, optionally enables WorkbookSettings.ShowFormula to display formulas instead of results, and saves the file as FormulasDisplayed.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            var workbook = new Workbook();

            // Get the first worksheet
            var sheet = workbook.Worksheets[0];

            // Insert a sample formula in A1
            sheet.Cells["A1"].Formula = "=SUM(B1:B5)";

            // Populate B1:B5 with sample values
            for (int i = 0; i < 5; i++)
            {
                // Column B (index 1)
                sheet.Cells[i, 1].PutValue(i + 1);
            }

            // Display formulas instead of calculated results if the API supports it.
            // In newer Aspose.Cells versions the ShowFormula property may be unavailable.
            // Uncomment the following line if your version includes WorkbookSettings.ShowFormula.
            // workbook.Settings.ShowFormula = true;

            // Define output file path
            string outputPath = "FormulasDisplayed.xlsx";

            // Save the workbook to a file
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
