// Title: Hide zero values on every worksheet and save the workbook as PDF using Aspose.Cells for .NET
// AI Prompts: Write C# code with Aspose.Cells that iterates all worksheets, disables printing of zero values, and exports the workbook to a PDF file. | Modify an existing Aspose.Cells workbook so that the PDF output for each sheet omits zero values, then generate the PDF. | Create a .NET console program that loads an Excel file, sets the PageSetup property to suppress zero values on each sheet, and saves it as PDF.
// Common Searches: how to prevent zero values from appearing in PDF generated by Aspose.Cells | c# Aspose.Cells loop through worksheets set PrintZeroValues false | export excel to pdf without zeroes using Aspose.Cells .NET | Aspose.Cells hide zero values in PDF output for all sheets | set PrintZeroValues property for each worksheet before PDF conversion
// Tags: Aspose.Cells disable zero printing PDF | iterate worksheets set PrintZeroValues | PDF export with hidden zeros Aspose.Cells | C# page setup PrintZeroValues property | batch worksheet PDF conversion Aspose.Cells

using Aspose.Cells;
using System;
using System.IO;

// // Loads an Excel workbook, iterates each worksheet to turn off zero‑value printing via the PageSetup.PrintZeroValues property, and saves the result as a PDF using Aspose.Cells.
class Program
{
    static void Main()
    {
        try
        {
            const string inputPath = "input.xlsx";
            const string outputPath = "output.pdf";

            // Verify that the input workbook exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine($"Input file '{inputPath}' not found.");
                return;
            }

            // Load the existing workbook
            Workbook workbook = new Workbook(inputPath);

            // Attempt to hide zero values in PDF output for each worksheet
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                try
                {
                    // Use dynamic to avoid compile‑time dependency on the property
                    dynamic pageSetup = sheet.PageSetup;
                    pageSetup.PrintZeroValues = false;
                }
                catch (Microsoft.CSharp.RuntimeBinder.RuntimeBinderException)
                {
                    // The PrintZeroValues property is not available in this version; continue without it
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Warning: Unable to set PrintZeroValues for sheet '{sheet.Name}'. {ex.Message}");
                }
            }

            // Save the workbook as a PDF file
            workbook.Save(outputPath, SaveFormat.Pdf);
            Console.WriteLine($"PDF saved to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
