// Title: C# – Remove duplicate rows by ID and Name using Aspose.Cells RemoveDuplicates
// Description: Creates a workbook, adds sample data with a header, and uses Cells.RemoveDuplicates to delete rows that share the same values in columns A (ID) and B (Name). The header is kept and the cleaned file is saved as an Excel workbook.
// Keywords: Aspose.Cells RemoveDuplicates C# | delete duplicate rows Excel .NET | remove duplicate rows by multiple columns | Aspose.Cells deduplication example | C# Excel duplicate row removal
// Common Searches: Aspose.Cells delete duplicate rows C# | Remove rows with same ID and Name Aspose.Cells | How to use Cells.RemoveDuplicates with header row | C# Excel deduplicate based on two columns | Aspose.Cells example for removing duplicate records
// Developer Intent: Eliminate rows that have identical values in columns A and B while preserving the first header row.
// Use Cases: Clean imported sales or inventory sheets by removing repeated ID‑Name pairs before analysis. | Ensure unique composite keys (e.g., ID + Name) in data exports generated by automated processes. | Integrate deduplication into scheduled .NET jobs that receive Excel files from external partners.
// AI Prompts: Show a C# example that uses Cells.RemoveDuplicates to drop duplicate rows based on columns A and B with a header row. | Demonstrate how to run RemoveDuplicates on a specific range and write the result to a MemoryStream instead of a file. | Explain how to set the columnOffsets parameter for non‑adjacent columns when removing duplicates with Aspose.Cells.

using System;
using Aspose.Cells;

// Creates a workbook, adds sample data with a header, and uses Cells.RemoveDuplicates to delete rows that share the same values in columns A (ID) and B (Name). The header is kept and the cleaned file is saved as an Excel workbook.
class RemoveDuplicateRowsExample
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet's cells collection
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];
        Cells cells = sheet.Cells;

        // ----- Sample data (including header) -----
        // Header row
        cells["A1"].PutValue("ID");
        cells["B1"].PutValue("Name");
        cells["C1"].PutValue("Amount");

        // Data rows
        cells["A2"].PutValue(1);
        cells["B2"].PutValue("John");
        cells["C2"].PutValue(100);

        cells["A3"].PutValue(2);
        cells["B3"].PutValue("Jane");
        cells["C3"].PutValue(200);

        // Duplicate based on columns A (ID) and B (Name)
        cells["A4"].PutValue(1);
        cells["B4"].PutValue("John");
        cells["C4"].PutValue(150);

        cells["A5"].PutValue(3);
        cells["B5"].PutValue("Mike");
        cells["C5"].PutValue(300);

        // ----- Define the range for duplicate removal -----
        int startRow = 1;               // Row index after header (0‑based)
        int startColumn = 0;            // Column A (0‑based)
        int endRow = cells.MaxDataRow;  // Last row that contains data
        int endColumn = 1;              // Column B (0‑based)

        // Remove duplicate rows based on columns A and B.
        // hasHeaders = true indicates the first row is a header.
        // columnOffsets = {0,1} tells the method to consider columns A and B for duplicate checking.
        cells.RemoveDuplicates(startRow, startColumn, endRow, endColumn, true, new int[] { 0, 1 });

        // Save the cleaned workbook
        workbook.Save("CleanedData.xlsx");
    }
}
