// Title: Set a custom print area in an Excel worksheet and export only that range to PDF using Aspose.Cells for .NET
// AI Prompts: Generate C# code that assigns a specific print area (e.g., A1:C5) to a worksheet and saves the workbook as a PDF with Aspose.Cells. | Add error handling that checks whether the PDF file was created and logs an appropriate message if it is missing. | Update the program to read the source Excel path, destination PDF path, and desired print area from user input at runtime.
// Common Searches: Aspose.Cells .NET how to export only a selected range to PDF | C# set print area before saving workbook as PDF with Aspose | verify that PDF generated by Aspose.Cells respects the defined print area
// Tags: configure worksheet print area with Aspose.Cells | range‑based PDF export using Aspose.Cells | validate PDF generation Aspose.Cells | parameterize Excel to PDF conversion in C# | error handling for missing PDF file .NET

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.Cells;

// The sample loads an Excel workbook, defines a custom print area (A1:C5) on the first worksheet, saves the workbook as a PDF, and then confirms that the PDF file was created, providing success or error messages while handling exceptions.
class PrintAreaPdfValidator
{
    static void Main()
    {
        try
        {
            // Path to the source Excel file
            string excelPath = "source.xlsx";

            // Verify that the source Excel file exists
            if (!File.Exists(excelPath))
            {
                Console.WriteLine($"Error: The Excel file '{excelPath}' was not found.");
                return;
            }

            // Path for the generated PDF
            string pdfPath = "output.pdf";

            // Load the workbook
            Workbook workbook = new Workbook(excelPath);

            // -------------------------------------------------
            // Define a custom print area (e.g., A1:C5)
            // -------------------------------------------------
            Worksheet sheet = workbook.Worksheets[0];
            sheet.PageSetup.PrintArea = "A1:C5";

            // Save the workbook as PDF
            workbook.Save(pdfPath, SaveFormat.Pdf);

            // -------------------------------------------------
            // Simple validation: ensure the PDF file was created
            // -------------------------------------------------
            if (!File.Exists(pdfPath))
            {
                Console.WriteLine("Validation failed: PDF file was not created.");
                return;
            }

            // Additional optional validation could be added here
            // (e.g., using Aspose.Pdf if the assembly is referenced).

            Console.WriteLine("PDF validation succeeded: the file was generated successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An unexpected error occurred: {ex.Message}");
        }
    }
}
