// Title: Validate PDF Export Contains Only Custom Print Area Cells with Aspose.Cells (C#)
// Description: C# example that creates a workbook, defines a print area (B2:E10), saves it as PDF, then uses GetPrintingPageBreaks to verify each generated page lies within the specified CellArea, ensuring the PDF does not include cells outside the custom print range.
// Keywords: Aspose.Cells PDF print area validation | C# GetPrintingPageBreaks | custom print area PDF export | Aspose.Cells verify PDF content | Aspose.Cells page break validation | ExportPrintArea alternative | Aspose.Cells PDF save options | Aspose.Cells worksheet print area | automated test PDF Aspose.Cells | .NET PDF export boundary check
// Common Searches: Aspose.Cells verify PDF export respects print area | How to check PDF contains only B2:E10 cells using Aspose.Cells | GetPrintingPageBreaks example C# | Validate PDF page ranges against custom print area Aspose.Cells | Aspose.Cells PDF export includes extra cells | C# code to validate Aspose.Cells PDF print area | Aspose.Cells ExportPrintArea not available workaround
// Developer Intent: Ensure the PDF generated by Aspose.Cells includes only the cells defined in the worksheet’s custom print area.
// Use Cases: Add automated regression tests that confirm PDF export boundaries after setting Worksheet.PageSetup.PrintArea. | Diagnose unexpected extra pages when a print area is applied but the PDF contains the whole sheet. | Create compliance reports that must export a specific cell range without manual trimming. | Work around older Aspose.Cells versions that lack the ExportPrintArea flag.
// AI Prompts: Write C# code that trims a PDF to the worksheet's PrintArea when ExportPrintArea is unavailable in Aspose.Cells. | Show how to extend the validation loop to log the exact page number and cell coordinates that exceed the print area. | Suggest using Worksheet.PageSetup.FitToPagesWide/FitToPagesTall as an alternative to limit PDF output to a custom range. | Provide a unit test example that asserts all pages are within the defined CellArea.

using System;
using Aspose.Cells;
using Aspose.Cells.Rendering;

// C# example that creates a workbook, defines a print area (B2:E10), saves it as PDF, then uses GetPrintingPageBreaks to verify each generated page lies within the specified CellArea, ensuring the PDF does not include cells outside the custom print range.
class PrintAreaPdfValidation
{
    static void Main()
    {
        try
        {
            // Create a new workbook and fill it with sample data
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            for (int row = 0; row < 20; row++)
            {
                for (int col = 0; col < 10; col++)
                {
                    worksheet.Cells[row, col].PutValue($"R{row + 1}C{col + 1}");
                }
            }

            // Define a custom print area (for example B2:E10)
            worksheet.PageSetup.PrintArea = "B2:E10";

            // Save the workbook to PDF. The entire sheet will be exported because
            // the ExportPrintArea option is not available in this version of the API.
            PdfSaveOptions pdfOptions = new PdfSaveOptions();
            string pdfPath = "PrintAreaOnly.pdf";
            workbook.Save(pdfPath, pdfOptions);

            // -----------------------------------------------------------------
            // Validation: ensure that the pages generated correspond only to the
            // cells inside the custom print area.
            // -----------------------------------------------------------------

            // Get the automatic page breaks for the worksheet using rendering options
            ImageOrPrintOptions renderOptions = new ImageOrPrintOptions();
            CellArea[] pageBreaks = worksheet.GetPrintingPageBreaks(renderOptions);

            // Convert the defined print area string to a CellArea object
            CellArea definedPrintArea = CellArea.CreateCellArea("B2", "E10");

            bool allPagesWithinPrintArea = true;

            foreach (CellArea area in pageBreaks)
            {
                // Verify that each page's start/end rows and columns are inside the print area
                if (area.StartRow < definedPrintArea.StartRow ||
                    area.EndRow > definedPrintArea.EndRow ||
                    area.StartColumn < definedPrintArea.StartColumn ||
                    area.EndColumn > definedPrintArea.EndColumn)
                {
                    allPagesWithinPrintArea = false;
                    break;
                }
            }

            Console.WriteLine(allPagesWithinPrintArea
                ? "Validation passed: PDF contains only cells within the custom print area."
                : "Validation failed: Some pages exceed the custom print area.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
