// Title: Add a Column with a Constant Default Value to an Aspose.Cells Table (C# .NET)
// Description: Demonstrates how to insert a new column into an existing ListObject, resize the table, set a header, and populate every data cell with a constant value (e.g., "N/A") using Aspose.Cells for .NET.
// Keywords: Aspose.Cells add column to table | C# ListObject Resize | InsertColumn Aspose.Cells | default value new column | Aspose.Cells table schema update | constant placeholder cell value | .NET spreadsheet automation
// Common Searches: how to add a column to an Aspose.Cells ListObject | set default value for new table column in C# | resize Aspose.Cells table after inserting column | populate new column with constant value Aspose.Cells | Aspose.Cells insert column and fill with N/A
// Developer Intent: Insert a new column into an existing Aspose.Cells table and fill it with a fixed default value.
// Use Cases: Add a "Status" column with default "N/A" to an inventory table generated by Aspose.Cells. | Extend a financial report's table by inserting a placeholder column for future data entry. | Modify a worksheet's ListObject schema to include a new field that is pre‑populated with a constant value for downstream processing.
// AI Prompts: Generate C# code that uses Aspose.Cells to insert a new column into an existing ListObject, resize the table, set the header, and fill each cell with a constant value. | Explain the steps for adding a column with a default placeholder to an Aspose.Cells table, including InsertColumn and ListObject.Resize usage. | Create a sample Aspose.Cells .NET snippet that adds a "Status" column with default "N/A" to a table and saves the workbook.

using System;
using Aspose.Cells;
using Aspose.Cells.Tables;

// Demonstrates how to insert a new column into an existing ListObject, resize the table, set a header, and populate every data cell with a constant value (e.g., "N/A") using Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            Cells cells = sheet.Cells;

            // Populate sample data for an initial table (A1:B4)
            cells["A1"].PutValue("Product");
            cells["B1"].PutValue("Quantity");
            cells["A2"].PutValue("Apple");
            cells["B2"].PutValue(10);
            cells["A3"].PutValue("Banana");
            cells["B3"].PutValue(20);
            cells["A4"].PutValue("Cherry");
            cells["B4"].PutValue(30);

            // Create a ListObject (table) that covers the range A1:B4
            int tableIndex = sheet.ListObjects.Add(0, 0, 3, 1, true);
            ListObject table = sheet.ListObjects[tableIndex];

            // Determine the index where the new column will be inserted (after the last column)
            int newColumnIndex = table.EndColumn + 1;

            // Insert a new column in the worksheet; shift existing columns to the right
            cells.InsertColumn(newColumnIndex, true);

            // Expand the table to include the newly inserted column
            int totalRows = table.EndRow - table.StartRow + 1;
            int totalColumns = table.EndColumn - table.StartColumn + 2; // +1 for the new column
            // Resize requires a hasHeaders flag; the table has headers, so pass true
            table.Resize(table.StartRow, table.StartColumn, totalRows, totalColumns, true);

            // Set header for the new column
            cells[table.StartRow, newColumnIndex].PutValue("Status");

            // Define the constant default value for the new column's data cells
            const string defaultValue = "N/A";

            // Fill each data row of the new column with the default value
            int dataStartRow = table.StartRow + 1; // Skip header row
            int dataEndRow = table.EndRow;         // Last row of the table
            for (int row = dataStartRow; row <= dataEndRow; row++)
            {
                cells[row, newColumnIndex].PutValue(defaultValue);
            }

            // Save the workbook with the updated table
            workbook.Save("TableAddColumnWithDefault.xlsx");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
