// Title: C# Aspose.Cells: Create a macro‑enabled workbook, add a ListObject table, and embed a Worksheet_Change VBA macro
// Description: This C# example uses Aspose.Cells for .NET to generate an .xlsm file, enable macros, fill a range with data, create a ListObject named SampleTable, add a VBA module to the worksheet, write a Worksheet_Change procedure that detects edits inside the table and displays a message box, and finally save the workbook.
// Keywords: Aspose.Cells C# macro enabled workbook | Aspose.Cells ListObject table | Aspose.Cells VBA integration | Worksheet_Change event Aspose | save xlsm with Aspose.Cells | embed VBA in .NET Excel | add table Aspose.Cells | macro enabled Excel file C#
// Common Searches: Aspose.Cells add VBA macro to worksheet | Create .xlsm with ListObject using Aspose.Cells | C# embed Worksheet_Change event in Excel file | How to enable macros in Aspose.Cells workbook | Add table and VBA code with Aspose.Cells .NET
// Developer Intent: Generate an .xlsm workbook that contains a ListObject and automatically runs a VBA macro whenever the table’s data is modified.
// Use Cases: Show a pop‑up message each time a user edits a cell inside the SampleTable for immediate feedback. | Log changes or trigger audit routines in VBA whenever table rows are added, removed, or edited. | Recalculate dependent formulas or refresh charts automatically after table updates. | Combine the table with other VBA procedures to enforce data validation rules on entry.
// AI Prompts: Write C# code with Aspose.Cells to create an .xlsm workbook, add a ListObject covering A1:B4, and embed a Worksheet_Change macro that shows a message when the table changes. | Show how to enable macros in an Aspose.Cells workbook and attach a VBA module to a specific worksheet. | Explain how to retrieve the index of a newly added ListObject and set its DisplayName using Aspose.Cells. | Provide a step‑by‑step guide to embed VBA code in a macro‑enabled Excel file generated by Aspose.Cells for .NET.

using System;
using Aspose.Cells;
using Aspose.Cells.Vba;
using Aspose.Cells.Tables; // Required for ListObject

namespace AsposeCellsMacroTableDemo
{
    // This C# example uses Aspose.Cells for .NET to generate an .xlsm file, enable macros, fill a range with data, create a ListObject named SampleTable, add a VBA module to the worksheet, write a Worksheet_Change procedure that detects edits inside the table and displays a message box, and finally save the workbook.
    class Program
    {
        static void Main()
        {
            try
            {
                // Create a new workbook
                Workbook wb = new Workbook();

                // Enable macros for the workbook
                wb.Settings.EnableMacros = true;

                // Access the first worksheet
                Worksheet sheet = wb.Worksheets[0];
                sheet.Name = "DataSheet";

                // Populate sample data
                sheet.Cells["A1"].PutValue("ID");
                sheet.Cells["B1"].PutValue("Value");
                sheet.Cells["A2"].PutValue(1);
                sheet.Cells["B2"].PutValue(100);
                sheet.Cells["A3"].PutValue(2);
                sheet.Cells["B3"].PutValue(200);
                sheet.Cells["A4"].PutValue(3);
                sheet.Cells["B4"].PutValue(300);

                // Add a table (ListObject) covering the data range
                int tableIndex = sheet.ListObjects.Add("SampleTable", "A1:B4", true);
                ListObject table = sheet.ListObjects[tableIndex];
                table.DisplayName = "SampleTable";

                // Add a VBA module associated with the worksheet
                int vbaModuleIndex = wb.VbaProject.Modules.Add(sheet);
                VbaModule vbaModule = wb.VbaProject.Modules[vbaModuleIndex];

                // VBA code: runs whenever any cell on the sheet changes.
                vbaModule.Codes =
@"Private Sub Worksheet_Change(ByVal Target As Range)
    Dim tbl As ListObject
    Set tbl = Me.ListObjects(""SampleTable"")
    If Not Intersect(Target, tbl.Range) Is Nothing Then
        MsgBox ""Table has been modified!""
    End If
End Sub";

                // Save the workbook as a macro‑enabled file
                wb.Save("MacroTableDemo.xlsm", SaveFormat.Xlsm);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
