// Title: Export an Excel table to HTML with inline CSS using Aspose.Cells for .NET (C#)
// Description: This C# example creates a workbook, fills cells A1:C4 with product data, applies a bold centered header with a light‑gray background, and saves the sheet as an HTML file. HtmlSaveOptions are configured to export only the table portion, embed styling directly in the markup, and set a custom page title.
// Keywords: Aspose.Cells | C# HTML export | Excel to HTML | inline CSS | HtmlSaveOptions | ExportDataOptions.Table | .NET | GitHub sample | working with tables | product catalog HTML | email friendly table | static documentation
// Common Searches: Aspose.Cells export specific range to HTML | C# save worksheet as HTML with inline styles | disable external CSS when exporting Excel to HTML | set HTML page title using Aspose.Cells | generate HTML table from Excel without UI elements
// Developer Intent: Convert a worksheet’s tabular data into a clean HTML file that preserves the original grid layout and embeds all styling directly in the HTML.
// Use Cases: Build a product‑catalog web page directly from an Excel source. | Create email‑ready HTML tables from daily Excel reports. | Generate static documentation pages that display Excel tables with consistent formatting without external CSS files. | Automate conversion of Excel dashboards to embeddable HTML snippets for intranet portals.
// AI Prompts: Show how to export a custom range (e.g., B2:D10) as HTML with inline styles using Aspose.Cells. | Demonstrate adding custom inline style attributes to individual cells while keeping the overall table export. | Explain how to embed workbook images or charts into the HTML output with Aspose.Cells. | Provide code to merge header cells and preserve colspan in the generated HTML. | Suggest ways to minify the inline CSS generated by Aspose.Cells for faster page loads.

using System;
using Aspose.Cells;

namespace ExportTableToHtml
{
    // This C# example creates a workbook, fills cells A1:C4 with product data, applies a bold centered header with a light‑gray background, and saves the sheet as an HTML file. HtmlSaveOptions are configured to export only the table portion, embed styling directly in the markup, and set a custom page title.
    class Program
    {
        static void Main()
        {
            // Create a new workbook (lifecycle: create)
            Workbook workbook = new Workbook();

            // Get the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Populate the worksheet with sample table data
            sheet.Cells["A1"].PutValue("Product");
            sheet.Cells["B1"].PutValue("Quantity");
            sheet.Cells["C1"].PutValue("Price");

            sheet.Cells["A2"].PutValue("Apple");
            sheet.Cells["B2"].PutValue(10);
            sheet.Cells["C2"].PutValue(0.5);

            sheet.Cells["A3"].PutValue("Banana");
            sheet.Cells["B3"].PutValue(5);
            sheet.Cells["C3"].PutValue(0.3);

            sheet.Cells["A4"].PutValue("Orange");
            sheet.Cells["B4"].PutValue(8);
            sheet.Cells["C4"].PutValue(0.4);

            // Apply simple styling to the header row
            Style headerStyle = workbook.CreateStyle();
            headerStyle.Font.IsBold = true;
            headerStyle.ForegroundColor = System.Drawing.Color.LightGray;
            headerStyle.Pattern = BackgroundType.Solid;
            headerStyle.HorizontalAlignment = TextAlignmentType.Center;

            // Apply the style to the header cells (A1:C1)
            for (int col = 0; col < 3; col++)
            {
                sheet.Cells[0, col].SetStyle(headerStyle);
            }

            // Configure HTML save options
            HtmlSaveOptions htmlOptions = new HtmlSaveOptions
            {
                // Export only the table part (no extra workbook UI)
                ExportDataOptions = HtmlExportDataOptions.Table,

                // Use inline CSS styles instead of external CSS
                DisableCss = true,

                // Optional: set a custom title for the HTML page
                PageTitle = "Product Table"
            };

            // Save the workbook as an HTML file (lifecycle: save)
            string outputPath = "ProductTable.html";
            workbook.Save(outputPath, htmlOptions);

            Console.WriteLine($"HTML file saved to: {outputPath}");
        }
    }
}
