// Title: C# – Add Picture and Semi‑Transparent Diagonal Watermark to PDF with Aspose.Cells
// Description: Creates a new workbook, inserts an image at B2 with 50 % opacity, defines a red 48‑pt Arial watermark (30 % opacity, 45° rotation, centered), and saves the sheet as a PDF that includes the watermark behind the data.
// Keywords: Aspose.Cells C# picture insertion | image transparency Aspose.Cells | PDF watermark Aspose.Cells | RenderingWatermark example | PdfSaveOptions watermark | diagonal text watermark .NET | export workbook to PDF with watermark | add picture to worksheet Aspose.Cells
// Common Searches: how to insert an image in Aspose.Cells C# | set picture opacity in Aspose.Cells worksheet | add diagonal watermark to PDF generated by Aspose.Cells | Aspose.Cells semi transparent watermark example | C# export Excel to PDF with background watermark
// Developer Intent: Insert an image into a worksheet, adjust its opacity, and apply a semi‑transparent diagonal text watermark when exporting the workbook to PDF.
// Use Cases: Secure confidential reports by embedding a faded logo and a "CONFIDENTIAL" watermark in the exported PDF. | Brand marketing decks with a background picture at 50 % opacity and a subtle company watermark behind the data. | Legal or audit documents where a semi‑transparent watermark appears behind all cells while a partially transparent picture remains visible on the sheet.
// AI Prompts: Generate C# code using Aspose.Cells to place a picture at cell B2, set its transparency to 0.5, and save the workbook as PDF with a 30 % opaque diagonal "CONFIDENTIAL" watermark. | Show an Aspose.Cells example that adds an image, makes it semi‑transparent, and configures RenderingWatermark (font, color, rotation, opacity) in PdfSaveOptions. | Provide a step‑by‑step guide for C# developers to embed a picture and a background watermark when converting an Excel file to PDF with Aspose.Cells.

using System;
using System.Drawing;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;
using Aspose.Cells.Rendering;

// Creates a new workbook, inserts an image at B2 with 50 % opacity, defines a red 48‑pt Arial watermark (30 % opacity, 45° rotation, centered), and saves the sheet as a PDF that includes the watermark behind the data.
class AddPictureWithWatermark
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet sheet = workbook.Worksheets[0];

        // ---------- Add a picture ----------
        // Path to the image file to be inserted
        string picturePath = "sample_picture.jpg";

        if (!File.Exists(picturePath))
        {
            Console.WriteLine($"Picture file not found: {picturePath}");
            return;
        }

        // Add the picture at cell position (row 2, column 2) – zero‑based indexes
        int pictureIndex = sheet.Pictures.Add(1, 1, picturePath);
        Picture picture = sheet.Pictures[pictureIndex];

        // Optionally make the picture itself semi‑transparent (50% opacity)
        picture.FormatPicture.Transparency = 0.5; // 0 = opaque, 1 = fully transparent

        // ---------- Create a semi‑transparent text watermark ----------
        // Define the font for the watermark text
        RenderingFont watermarkFont = new RenderingFont("Arial", 48)
        {
            Bold = true,
            Color = Color.Red
        };

        // Create the watermark with desired text and font
        RenderingWatermark watermark = new RenderingWatermark("CONFIDENTIAL", watermarkFont)
        {
            // Place the watermark behind the sheet contents
            IsBackground = true,
            // Rotate for a typical diagonal appearance
            Rotation = 45,
            // Set opacity to make it semi‑transparent (e.g., 30% visible)
            Opacity = 0.3f,
            // Center the watermark on the page
            HAlignment = TextAlignmentType.Center,
            VAlignment = TextAlignmentType.Center,
            // Scale relative to the page size
            ScaleToPagePercent = 80
        };

        // ---------- Save the workbook as PDF with the watermark ----------
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            Watermark = watermark
        };

        string outputPath = "Workbook_With_Picture_And_Watermark.pdf";
        workbook.Save(outputPath, pdfOptions);

        Console.WriteLine($"Workbook saved successfully to '{outputPath}'.");
    }
}
