// Title: Add a Hyperlink to a TextBox Shape in Excel with Aspose.Cells for .NET (C#)
// Description: Creates a new workbook, inserts a TextBox shape, sets its display text, attaches a hyperlink that opens a web page when the shape is clicked, optionally adds a screen tip, and saves the file as TextBoxWithHyperlink.xlsx using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# | Excel | TextBox shape | hyperlink | add hyperlink to shape | screen tip | programmatic Excel hyperlink | Aspose.Cells example | Excel automation
// Common Searches: Aspose.Cells add hyperlink to textbox | C# add hyperlink to Excel shape | How to make a clickable textbox in Excel using Aspose.Cells | Set screen tip for shape hyperlink Aspose.Cells | Open URL from Excel shape programmatically
// Developer Intent: Programmatically attach a web hyperlink to a TextBox shape in an Excel workbook so that clicking the shape opens the URL.
// Use Cases: Insert a link to a help page inside a dashboard textbox generated by a reporting engine. | Create a call‑to‑action button in automated financial reports. | Add tool‑tips to linked shapes for better user guidance. | Generate interactive Excel templates with embedded web resources.
// AI Prompts: Write C# code with Aspose.Cells to add a hyperlink and screen tip to an existing TextBox shape. | Show how to update or remove a hyperlink from a TextBox after the workbook is saved. | Demonstrate adding different URLs to multiple shapes (TextBox, rectangle, picture) in the same worksheet. | Explain how to handle hyperlink click events in Excel when using Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsExamples
{
    // Creates a new workbook, inserts a TextBox shape, sets its display text, attaches a hyperlink that opens a web page when the shape is clicked, optionally adds a screen tip, and saves the file as TextBoxWithHyperlink.xlsx using Aspose.Cells for .NET.
    class TextBoxHyperlinkDemo
    {
        static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Add a TextBox shape to the worksheet
            // Parameters: upper left row, upper left column, row offset, column offset, height, width
            TextBox textBox = sheet.Shapes.AddTextBox(2, 2, 0, 0, 100, 200);
            textBox.Text = "Click here to visit Aspose";

            // Add a hyperlink to the TextBox that opens a web page when clicked
            Hyperlink hyperlink = textBox.AddHyperlink("https://www.aspose.com/");
            // Optional: set a screen tip for the hyperlink
            hyperlink.ScreenTip = "Open Aspose website";

            // Save the workbook
            workbook.Save("TextBoxWithHyperlink.xlsx");
        }
    }
}
