// Title: Aspose.Cells for .NET – Create a ListBox shape linked to a spilled array constant
// Description: Demonstrates how to insert a ListBox control into a worksheet, fill it from a horizontal array formula ({1,2,3}) that spills across A1:C1, bind the control to cell A1, refresh the selected entry, read the value via the linked cell, and save the file as ShapeLinkedArrayDemo.xlsx.
// Keywords: Aspose.Cells | C# | .NET | ListBox shape | linked cell | array formula | spilled array | input range | selected item | Excel form control
// Common Searches: link ListBox shape to array constant Aspose.Cells | populate ListBox from spilled array formula .NET | read selected ListBox value from linked cell | set input range for ListBox control using Aspose.Cells | update ListBox selection programmatically in C#
// Developer Intent: Add a ListBox control whose items come from a spilled array formula and synchronize its selection with a worksheet cell.
// Use Cases: Build interactive Excel forms where options are generated by formulas. | Keep a cell value in sync with a user’s choice from a shape‑based dropdown. | Create templates that auto‑populate controls from dynamic array calculations.
// AI Prompts: Generate C# code with Aspose.Cells that adds a ListBox, links it to a cell containing an array constant, and outputs the chosen item. | Explain the relationship between SetLinkedCell and SetInputRange for a ListBox bound to a spilled array in Aspose.Cells. | Show how to change the linked cell value and refresh the ListBox selected index in a .NET workbook.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Demonstrates how to insert a ListBox control into a worksheet, fill it from a horizontal array formula ({1,2,3}) that spills across A1:C1, bind the control to cell A1, refresh the selected entry, read the value via the linked cell, and save the file as ShapeLinkedArrayDemo.xlsx.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];
            Cells cells = worksheet.Cells;

            // Set an array constant in cell A1 that spills into three columns (A1:C1)
            // The array constant {1,2,3} creates a horizontal array.
            // RowCount = 1, ColumnCount = 3
            cells["A1"].SetArrayFormula("={1,2,3}", 1, 3);

            // Add a ListBox shape to the worksheet
            // Parameters: upperLeftRow, upperLeftColumn, top, left, width, height
            ListBox listBox = (ListBox)worksheet.Shapes.AddListBox(2, 0, 2, 0, 130, 130);

            // Link the ListBox value to the cell that holds the array constant (A1)
            // isR1C1 = false (A1 style), isLocal = false (default locale)
            listBox.SetLinkedCell("$A$1", false, false);

            // Populate the ListBox items from the same range (A1:C1)
            // This makes the ListBox display the three values of the array.
            listBox.SetInputRange("$A$1:$C$1", false, false);

            // Update the selected value of the shape based on the linked cell
            worksheet.Shapes.UpdateSelectedValue();

            // Retrieve the selected item value safely.
            // Aspose.Cells ListBox does not provide a direct method returning a string,
            // so we read the linked cell value which reflects the selected item.
            string selectedItem = cells["A1"].Value?.ToString() ?? string.Empty;

            // Display the linked cell value (first element of the array) and the selected index
            Console.WriteLine("Linked cell (A1) value: " + cells["A1"].Value);
            Console.WriteLine("ListBox selected index: " + listBox.SelectedIndex);
            Console.WriteLine("ListBox selected item value: " + selectedItem);

            // Save the workbook (ensure the directory exists)
            string outputPath = "ShapeLinkedArrayDemo.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine("Workbook saved to: " + Path.GetFullPath(outputPath));
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
