// Title: Create a rectangle shape in an Excel workbook with Aspose.Cells, retrieve its connection points, and verify them against a JSON baseline using C#
// AI Prompts: Write C# code that adds a rectangle shape to a worksheet with Aspose.Cells, calls GetConnectionPoints, and checks each point against values read from a JSON file with a tolerance of 0.001. | Implement a helper method that loads a list of BaselineConnectionPoint objects from a JSON file and returns a boolean indicating whether all shape connection points match the baseline within a specified tolerance. | Modify the example to output mismatched connection points to a CSV log while still saving the workbook as an .xlsx file.
// Common Searches: aspnet c# how to retrieve shape connection points using Aspose.Cells | compare shape GetConnectionPoints result with JSON data in Aspose.Cells | validate rectangle shape coordinates in Excel file generated by Aspose.Cells C# | load baseline connection points from a JSON file and check tolerance in .NET | Aspose.Cells GetConnectionPoints example with JSON baseline verification
// Tags: Aspose.Cells GetConnectionPoints rectangle shape | C# compare shape coordinates with JSON baseline | validate shape connection points tolerance Aspose.Cells | load baseline connection points from JSON .NET | save workbook with shape connection points Aspose.Cells

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsShapeConnectionDemo
{
    // Model representing a connection point defined in the JSON baseline
    // The sample creates a new workbook, adds a rectangle shape, extracts its connection points via GetConnectionPoints, loads expected points from a JSON baseline, compares each point within a 0.001 tolerance, reports any mismatches, and saves the workbook.
    public class BaselineConnectionPoint
    {
        public int Index { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
    }

    class Program
    {
        static void Main()
        {
            try
            {
                // ---------- Create a new workbook ----------
                Workbook workbook = new Workbook();
                Worksheet sheet = workbook.Worksheets[0];

                // ---------- Add a rectangle shape ----------
                // Parameters: type, upper left row, upper left column, row offset, column offset, height, width
                Shape shape = sheet.Shapes.AddShape(
                    MsoDrawingType.Rectangle,
                    2, // upper left row
                    2, // upper left column
                    0, // row offset (in points)
                    0, // column offset (in points)
                    80, // height (in points)
                    120 // width (in points)
                );

                // ---------- Retrieve connection points from the shape ----------
                // GetConnectionPoints returns a float[][] where each inner array holds X and Y coordinates.
                float[][] actualPoints = shape.GetConnectionPoints();

                // ---------- Load baseline connection points from JSON ----------
                // Expected JSON format: [{ "Index":0, "X":0.0, "Y":0.0 }, ...]
                string jsonPath = "baseline.json";
                if (!File.Exists(jsonPath))
                {
                    Console.WriteLine($"Baseline file not found: {jsonPath}");
                    return;
                }

                string jsonContent = File.ReadAllText(jsonPath);
                List<BaselineConnectionPoint> baselinePoints = JsonSerializer.Deserialize<List<BaselineConnectionPoint>>(jsonContent);
                if (baselinePoints == null)
                {
                    Console.WriteLine("Failed to deserialize baseline JSON.");
                    return;
                }

                // ---------- Compare actual points with baseline ----------
                const double tolerance = 0.001; // allowable difference due to floating‑point precision
                bool allMatch = true;

                foreach (BaselineConnectionPoint expected in baselinePoints)
                {
                    // Validate index range
                    if (expected.Index < 0 || expected.Index >= actualPoints.Length)
                    {
                        Console.WriteLine($"Baseline index {expected.Index} is out of range.");
                        allMatch = false;
                        continue;
                    }

                    float[] point = actualPoints[expected.Index];
                    double actualX = point.Length > 0 ? point[0] : 0.0;
                    double actualY = point.Length > 1 ? point[1] : 0.0;

                    // Compare X and Y coordinates
                    if (Math.Abs(actualX - expected.X) > tolerance || Math.Abs(actualY - expected.Y) > tolerance)
                    {
                        Console.WriteLine($"Mismatch at Index {expected.Index}: Expected (X={expected.X}, Y={expected.Y}) " +
                                          $"but got (X={actualX}, Y={actualY}).");
                        allMatch = false;
                    }
                }

                if (allMatch)
                    Console.WriteLine("All connection points match the baseline.");
                else
                    Console.WriteLine("Some connection points do not match the baseline.");

                // ---------- Save the workbook ----------
                string outputPath = "ShapeWithConnectionPoints.xlsx";
                workbook.Save(outputPath);
                Console.WriteLine($"Workbook saved to {outputPath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
            }
        }
    }
}
