// Title: Aspose.Cells for .NET: Add a Rectangle Shape and Lock Its Properties
// Description: Demonstrates how to create a new workbook, insert a rectangle shape on the first worksheet, enable the shape's IsLocked flag, lock specific attributes with SetLockedProperty (e.g., adjust handles and selection), protect the worksheet so the locks take effect, and save the file as ShapeLockedDemo.xlsx using C# and Aspose.Cells.
// Keywords: Aspose.Cells | C# | .NET | add rectangle shape | shape lock | IsLocked | SetLockedProperty | ShapeLockType | worksheet protection | prevent shape editing | Excel shape locking | sample code | GitHub example
// Common Searches: Aspose.Cells lock shape C# | How to prevent shape editing in Excel with Aspose.Cells | Set shape IsLocked and protect worksheet Aspose.Cells | Lock rectangle shape handles using Aspose.Cells for .NET | Aspose.Cells shape locking example GitHub
// Developer Intent: Secure a shape and its attributes so it cannot be moved, resized, or altered after the worksheet is protected.
// Use Cases: Create a diagram element that must stay fixed in a shared template workbook. | Lock selection and adjustment handles of a shape to maintain layout consistency in reports. | Prevent end‑users from modifying critical shapes in an Excel file generated by an automated process.
// AI Prompts: Generate C# code with Aspose.Cells to add a shape, lock all its properties, and protect the worksheet. | Explain the interaction between Shape.IsLocked and Shape.SetLockedProperty for securing shapes in Aspose.Cells. | Show how to unlock a previously locked shape after removing worksheet protection using Aspose.Cells.

using System;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsShapeLockDemo
{
    // Demonstrates how to create a new workbook, insert a rectangle shape on the first worksheet, enable the shape's IsLocked flag, lock specific attributes with SetLockedProperty (e.g., adjust handles and selection), protect the worksheet so the locks take effect, and save the file as ShapeLockedDemo.xlsx using C# and Aspose.Cells.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add a rectangle shape to the worksheet
            // Parameters: upper left row, top offset, upper left column, left offset, height, width
            Shape shape = worksheet.Shapes.AddRectangle(2, 0, 2, 0, 100, 200);

            // Set the overall locked flag – the shape cannot be modified when the sheet is protected
            shape.IsLocked = true;

            // Additionally lock specific properties (e.g., adjusting handles) to prevent accidental changes
            shape.SetLockedProperty(ShapeLockType.AdjustHandles, true);
            shape.SetLockedProperty(ShapeLockType.Selection, true);

            // Protect the worksheet so that the locked settings take effect
            worksheet.Protect(ProtectionType.All);

            // Save the workbook
            workbook.Save("ShapeLockedDemo.xlsx");

            Console.WriteLine("Shape added and locked successfully.");
        }
    }
}
