// Title: C# – Add comment shape to D4, light‑gray fill, lock, and protect sheet (Aspose.Cells)
// Description: Creates a new workbook, inserts a comment in cell D4, accesses its CommentShape, applies a light‑gray background, locks the shape, protects the worksheet, and saves the file as CommentShapeLocked.xlsx using Aspose.Cells for .NET.
// Keywords: Aspose.Cells comment shape | C# comment shape fill | light gray comment background | lock comment shape | protect worksheet Aspose.Cells | add comment to cell D4 | Excel comment shape styling | Aspose.Cells API | shape.IsLocked | shape.FillFormat
// Common Searches: Aspose.Cells set comment shape background color | How to lock a comment shape in Excel using Aspose.Cells | Add comment to specific cell and style it C# | Protect worksheet while keeping comment shape locked | Change comment shape fill to gray Aspose.Cells
// Developer Intent: Insert a comment on D4, give its shape a light‑gray fill, lock the shape, and protect the sheet.
// Use Cases: Add formatted, read‑only comments to cells for documentation in automated reports. | Prevent end‑users from altering comment appearance while allowing data entry in shared workbooks. | Enforce consistent comment styling across multiple worksheets generated by a .NET application.
// AI Prompts: Generate C# code with Aspose.Cells that adds a comment to cell D4, sets the comment shape's fill to light gray, locks the shape, and protects the worksheet. | Show how to lock comment shapes while keeping other cells editable in a protected worksheet using Aspose.Cells for .NET. | Provide code to modify the fill color of an existing comment shape and update its lock status in a workbook.

using System;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Creates a new workbook, inserts a comment in cell D4, accesses its CommentShape, applies a light‑gray background, locks the shape, protects the worksheet, and saves the file as CommentShapeLocked.xlsx using Aspose.Cells for .NET.
class Program
{
    static void Main()
    {
        // Create a new workbook and get the first worksheet
        Workbook workbook = new Workbook();
        Worksheet worksheet = workbook.Worksheets[0];

        // Add a comment to cell D4 (row index 3, column index 3)
        int commentIndex = worksheet.Comments.Add(3, 3);
        Comment comment = worksheet.Comments[commentIndex];
        comment.Note = "This is a comment attached to D4.";

        // Retrieve the shape associated with the comment
        Shape commentShape = comment.CommentShape;

        // Set the shape's background fill to light gray
        commentShape.FillFormat.ForeColor = Color.LightGray;
        commentShape.IsFilled = true; // Ensure the fill is applied

        // Lock the shape so it cannot be edited when the sheet is protected
        commentShape.IsLocked = true;

        // Protect the worksheet to enforce the lock (optional but typical)
        worksheet.Protect(ProtectionType.All);

        // Save the workbook
        workbook.Save("CommentShapeLocked.xlsx");
    }
}
