// Title: Set Dashed 2‑Point Line Style for a Shape Named "Divider" with Aspose.Cells for .NET (C#)
// Description: This example shows how to load or create a workbook, locate the shape called "Divider" on the first worksheet, change its line dash style to dashed, set the line weight to 2 points, and save the workbook.
// Keywords: Aspose.Cells shape line dash style | C# set shape line weight | Aspose.Cells modify shape appearance | Excel shape formatting Aspose.Cells | MsoLineDashStyle Dash | shape Divider Aspose.Cells | .NET line thickness Excel shape | Aspose.Cells line style example
// Common Searches: Aspose.Cells set shape line to dashed C# | change line weight of Excel shape using Aspose.Cells | retrieve shape by name in Aspose.Cells .NET | format divider line in generated workbook Aspose.Cells
// Developer Intent: Apply a dashed line style and a 2‑point thickness to the worksheet shape named "Divider" using Aspose.Cells for .NET.
// Use Cases: Create consistent visual separators in automated reports by formatting a line shape as dashed with a defined thickness. | Update legacy Excel templates to replace solid dividers with a 2‑point dashed line for clearer sectioning. | Standardize the appearance of divider shapes across multiple workbooks generated by a C# application.
// AI Prompts: Show how to change the line color of the "Divider" shape after setting its dash style and weight with Aspose.Cells. | Provide code that adds a new shape named "Divider" with a dashed 2‑point line if it does not already exist. | Explain how to apply the same dashed line formatting to all line shapes in a worksheet using Aspose.Cells for .NET.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// This example shows how to load or create a workbook, locate the shape called "Divider" on the first worksheet, change its line dash style to dashed, set the line weight to 2 points, and save the workbook.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (or load an existing one)
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet worksheet = workbook.Worksheets[0];

            // Retrieve the shape named "Divider"
            Shape divider = worksheet.Shapes["Divider"];

            if (divider != null)
            {
                // Set the line dash style to dashed
                divider.Line.DashStyle = MsoLineDashStyle.Dash;

                // Set the line thickness to 2 points
                divider.Line.Weight = 2.0f;
            }

            // Save the workbook
            string outputPath = "output.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
