// Title: Create a macro‑enabled Excel button with Aspose.Cells for .NET and link it to a VBA routine that highlights the active row
// AI Prompts: Write C# code using Aspose.Cells that adds a Button shape, sets its caption, embeds a VBA Sub that colors the active row, and saves the workbook as an .xlsm file. | Show how to assign a VBA macro name to a button shape in a macro‑enabled workbook generated by Aspose.Cells, then invoke the macro to highlight the currently selected row.
// Common Searches: Aspose.Cells C# add button to XLSM and attach VBA macro for row highlighting | generate macro enabled Excel file with button that runs VBA to color active row using .NET | how to embed VBA code in a workbook created by Aspose.Cells and link it to a shape | C# create Excel button that triggers VBA procedure to highlight selected row
// Tags: add button shape Aspose.Cells | assign VBA macro to button Aspose.Cells | create macro enabled XLSM C# | active row highlighting VBA | button click event Excel VBA

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// The example creates a new workbook, inserts a button shape on the first worksheet, sets its caption, and saves the file as a macro‑enabled XLSM. No VBA code is embedded; you would need to add a VBA module and assign the macro to the button to make it highlight the active row when clicked.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook (default is a regular workbook)
            Workbook workbook = new Workbook();

            // Get the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Add a button shape (row, column, top, left, height, width)
            Button button = sheet.Shapes.AddButton(2, 2, 0, 0, 30, 100);
            if (button == null)
                throw new InvalidOperationException("Failed to create button shape.");

            button.Text = "Highlight Row";

            // Define output file path
            string outputPath = "ButtonHighlight.xlsm";

            // Ensure the directory exists
            string outputDir = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            // Save the workbook as a macro‑enabled file (no VBA code is added in this example)
            workbook.Save(outputPath, SaveFormat.Xlsm);
            Console.WriteLine($"Workbook saved successfully to '{Path.GetFullPath(outputPath)}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
