// Title: Aspose.Cells .NET: Group Shapes, Apply a Movement Lock, and Verify Enforcement
// Description: This example builds a workbook, inserts two rectangle shapes, groups them, sets a movement lock via SetLockedProperty, protects the worksheet, tries to reposition an inner shape, catches the expected exception, and saves the result as an Excel file.
// Keywords: Aspose.Cells C# group shapes | shape movement lock Aspose.Cells | SetLockedProperty ShapeLockType.Move | protect worksheet shapes .NET | prevent shape reposition Excel | Aspose.Cells API lock group | Excel automation shape lock US | Aspose.Cells shape security Europe
// Common Searches: how to lock a grouped shape in Aspose.Cells | prevent shape movement after worksheet protection .NET | SetLockedProperty example for ShapeLockType.Move | test shape group lock enforcement Aspose.Cells | C# code to protect shapes in Excel workbook
// Developer Intent: Apply a lock that stops a grouped shape from being moved when the worksheet is protected, and confirm the lock works by attempting a move operation.
// Use Cases: Create a fixed header graphic that stays in place while users edit data. | Secure diagram elements in a shared workbook so they cannot be repositioned. | Automated testing of shape‑lock behavior in Excel files generated by .NET applications.
// AI Prompts: Write C# code using Aspose.Cells to group multiple shapes, lock their movement, protect the worksheet, and handle the exception when a shape is moved. | Explain the interaction between SetLockedProperty(ShapeLockType.Move) and worksheet protection in Aspose.Cells. | Provide a step‑by‑step tutorial for validating shape group lock enforcement in a .NET console app.

using System;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsShapeLockDemo
{
    // This example builds a workbook, inserts two rectangle shapes, groups them, sets a movement lock via SetLockedProperty, protects the worksheet, tries to reposition an inner shape, catches the expected exception, and saves the result as an Excel file.
    class Program
    {
        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add two rectangle shapes to the worksheet
            Shape shape1 = worksheet.Shapes.AddRectangle(2, 0, 2, 0, 80, 60);
            Shape shape2 = worksheet.Shapes.AddRectangle(6, 0, 2, 0, 80, 60);

            // Group the two shapes
            GroupShape group = worksheet.Shapes.Group(new Shape[] { shape1, shape2 });

            // Lock the group shape (prevent moving when sheet is protected)
            group.IsLocked = true; // General lock flag
            group.SetLockedProperty(ShapeLockType.Move, true); // Specifically lock movement

            // Protect the worksheet (all protection types)
            worksheet.Protect(ProtectionType.All);

            // Attempt to move an inner shape (should be prevented by the lock)
            try
            {
                // Change the position of the first shape inside the group
                shape1.Left += 20; // Attempt to move horizontally
                Console.WriteLine("Shape moved successfully (unexpected).");
            }
            catch (Exception ex)
            {
                // Expected behavior: an exception is thrown because the shape is locked
                Console.WriteLine("Failed to move shape as expected: " + ex.Message);
            }

            // Save the workbook
            workbook.Save("ShapeGroupLockDemo.xlsx");
        }
    }
}
