// Title: Export Excel shape properties (position, size, rotation, colors, shadow) to a JSON file with Aspose.Cells for .NET
// AI Prompts: Write C# code that uses Aspose.Cells to loop through every worksheet, gather each shape's Top, Left, Height, Width, RotationAngle, FillFormat color, LineFormat color, and ShadowEffect flag, then serialize the collection as an indented JSON array to a user‑specified path. | Enhance the exporter to also capture a shape's displayed text and any hyperlink URL, adding these fields to the JSON representation. | Create a C# routine that reads the JSON file generated by the exporter and rebuilds the shapes in a new workbook, applying the stored position, size, rotation, colors, and shadow settings.
// Common Searches: Aspose.Cells C# export shape dimensions and formatting to JSON | How to retrieve shape fill color and shadow information from an Excel workbook using Aspose.Cells | Serialize Excel shape metadata (top, left, height, width, rotation) into a JSON file in .NET | Extract shape properties with Aspose.Cells and save as JSON | C# read shape visual effects (shadow, glow) from Excel using Aspose.Cells
// Tags: Aspose.Cells export shape metadata to JSON | C# extract shape position and size Aspose.Cells | Aspose.Cells retrieve shape fill and line colors | serialize Excel shape visual effects Aspose.Cells | Aspose.Cells shape shadow detection

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Drawing;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace ShapeMetadataExporter
{
    // Class representing the metadata of a shape
    // The example loads an Excel workbook with Aspose.Cells, iterates each worksheet and its Shapes collection, and captures metadata such as worksheet name, shape name, top, left, height, width, rotation angle, shadow presence, fill color, and line color. The collected ShapeMetadata objects are serialized to a formatted JSON file, with directory creation and error handling for missing files and individual shape processing failures.
    public class ShapeMetadata
    {
        public string? WorksheetName { get; set; }
        public string? ShapeName { get; set; }
        public double Top { get; set; }               // Position from the top of the worksheet (points)
        public double Left { get; set; }              // Position from the left of the worksheet (points)
        public double Height { get; set; }            // Height of the shape (points)
        public double Width { get; set; }             // Width of the shape (points)
        public double RotationAngle { get; set; }     // Rotation angle in degrees

        // Visual effect properties (if available)
        public bool HasShadow { get; set; }
        public bool HasGlow { get; set; }
        public string? FillColor { get; set; }        // Hex representation of fill color
        public string? LineColor { get; set; }        // Hex representation of line color
    }

    public static class ShapeMetadataExporter
    {
        /// <param name="excelFilePath">Path to the source Excel workbook.</param>
        /// <param name="jsonOutputPath">Path where the JSON file will be saved.</param>
        public static void ExportShapeMetadata(string excelFilePath, string jsonOutputPath)
        {
            // Verify the input file exists to avoid FileNotFoundException
            if (!File.Exists(excelFilePath))
                throw new FileNotFoundException($"The Excel file '{excelFilePath}' does not exist.");

            Workbook workbook;
            try
            {
                // Load the workbook using Aspose.Cells
                workbook = new Workbook(excelFilePath);
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Failed to load workbook: {ex.Message}", ex);
            }

            // List to hold metadata for all shapes in the workbook
            List<ShapeMetadata> allShapes = new List<ShapeMetadata>();

            // Iterate through each worksheet
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Access the collection of shapes on the current worksheet
                ShapeCollection shapes = sheet.Shapes;

                // Iterate through each shape
                foreach (Shape shape in shapes)
                {
                    try
                    {
                        // Determine if the shape has a shadow (presence of ShadowEffect indicates a shadow)
                        bool hasShadow = shape.ShadowEffect != null;

                        // Aspose.Cells does not expose a GlowEffect property directly; set to false
                        bool hasGlow = false;

                        // Fill color (if defined) – using the obsolete FillFormat property (still functional)
                        string? fillColor = null;
                        if (shape.FillFormat != null && shape.FillFormat.ForeColor != Color.Empty)
                        {
                            Color c = shape.FillFormat.ForeColor;
                            fillColor = $"#{c.R:X2}{c.G:X2}{c.B:X2}";
                        }

                        // Line color (if defined) – using the obsolete LineFormat property (still functional)
                        string? lineColor = null;
                        if (shape.LineFormat != null && shape.LineFormat.ForeColor != Color.Empty)
                        {
                            Color c = shape.LineFormat.ForeColor;
                            lineColor = $"#{c.R:X2}{c.G:X2}{c.B:X2}";
                        }

                        ShapeMetadata meta = new ShapeMetadata
                        {
                            WorksheetName = sheet.Name,
                            ShapeName = shape.Name,
                            Top = shape.Top,
                            Left = shape.Left,
                            Height = shape.Height,
                            Width = shape.Width,
                            RotationAngle = shape.RotationAngle,
                            HasShadow = hasShadow,
                            HasGlow = hasGlow,
                            FillColor = fillColor,
                            LineColor = lineColor
                        };

                        allShapes.Add(meta);
                    }
                    catch (Exception ex)
                    {
                        // Log shape‑level errors but continue processing other shapes
                        Console.WriteLine($"Warning: Failed to process shape '{shape.Name}' on sheet '{sheet.Name}': {ex.Message}");
                    }
                }
            }

            // Serialize the list to JSON with indentation for readability
            JsonSerializerOptions options = new JsonSerializerOptions
            {
                WriteIndented = true
            };
            string json = JsonSerializer.Serialize(allShapes, options);

            // Ensure the output directory exists
            string? directory = Path.GetDirectoryName(jsonOutputPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // Write JSON to the specified file
            File.WriteAllText(jsonOutputPath, json);
        }

        // Example usage
        public static void Main(string[] args)
        {
            // Validate arguments
            if (args.Length != 2)
            {
                Console.WriteLine("Usage: ShapeMetadataExporter <input_excel_path> <output_json_path>");
                return;
            }

            string inputPath = args[0];
            string outputPath = args[1];

            try
            {
                ExportShapeMetadata(inputPath, outputPath);
                Console.WriteLine($"Shape metadata exported successfully to '{outputPath}'.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error during export: {ex.Message}");
            }
        }
    }
}
