// Title: Auto‑group shapes added within a time window using Aspose.Cells for .NET (C#)
// Description: This C# example creates a workbook, adds rectangles, ovals and lines to the first worksheet with simulated delays, records each shape's timestamp, and automatically groups shapes whose addition times fall inside a configurable TimeSpan (default 5 seconds). A final forced grouping ensures any remaining shapes are collected before the file is saved as AutoGroupedShapes.xlsx.
// Keywords: Aspose.Cells | C# | .NET | ShapeCollection.Group | auto group shapes | shape grouping by time | shape timestamps | ShapeGroup example | delay shape addition | workbook shape management
// Common Searches: Aspose.Cells automatically group shapes after a delay | C# group shapes added within a time interval using Aspose.Cells | ShapeCollection.Group example with time window | How to batch‑group shapes in Aspose.Cells workbook | auto‑group shapes in .NET Excel library
// Developer Intent: Implement logic that collects shapes added to a worksheet within a defined time span and creates a single ShapeGroup for them.
// Use Cases: Consolidate shapes created during a user session to keep the worksheet tidy and enable collective formatting. | Batch‑group shapes generated by a reporting script after a set delay, then apply a common style or name. | Ensure no stray shapes remain by forcing a final grouping at the end of processing.
// AI Prompts: Generate C# code that monitors shape additions in an Aspose.Cells worksheet and groups them when the elapsed time between additions exceeds a configurable number of seconds. | Provide an Aspose.Cells example that automatically creates a ShapeGroup for all shapes added within the last N seconds, skipping shapes that are already grouped. | Show how to extend the auto‑grouping logic to assign custom group names based on the types of shapes contained in the group.

using System;
using System.Collections.Generic;
using System.Threading;
using Aspose.Cells;
using Aspose.Cells.Drawing;

namespace AsposeCellsShapeAutoGroup
{
    // This C# example creates a workbook, adds rectangles, ovals and lines to the first worksheet with simulated delays, records each shape's timestamp, and automatically groups shapes whose addition times fall inside a configurable TimeSpan (default 5 seconds). A final forced grouping ensures any remaining shapes are collected before the file is saved as AutoGroupedShapes.xlsx.
    class Program
    {
        // Define the time window for grouping (e.g., 5 seconds)
        private static readonly TimeSpan GroupingWindow = TimeSpan.FromSeconds(5);

        // Holds shapes added together with their addition timestamps
        private static readonly List<(Shape shape, DateTime addedAt)> pendingShapes = new List<(Shape, DateTime)>();

        static void Main()
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            ShapeCollection shapes = sheet.Shapes;

            // Simulate adding shapes at different times
            AddShapeWithDelay(shapes, () => shapes.AddRectangle(2, 0, 2, 0, 50, 50), 0);   // immediate
            AddShapeWithDelay(shapes, () => shapes.AddOval(4, 0, 4, 0, 60, 60), 2000);   // after 2 seconds
            AddShapeWithDelay(shapes, () => shapes.AddLine(6, 0, 6, 0, 70, 70), 4000);   // after 4 seconds
            AddShapeWithDelay(shapes, () => shapes.AddRectangle(8, 0, 8, 0, 80, 80), 8000); // after 8 seconds
            AddShapeWithDelay(shapes, () => shapes.AddOval(10, 0, 10, 0, 90, 90), 12000); // after 12 seconds

            // After all additions, ensure any remaining pending shapes are grouped
            GroupPendingShapes(shapes, forceGroupAll: true);

            // Save the workbook
            workbook.Save("AutoGroupedShapes.xlsx");
        }

        // Adds a shape using the provided action, records its timestamp, and attempts grouping
        private static void AddShapeWithDelay(ShapeCollection shapes, Action addShapeAction, int delayMilliseconds)
        {
            // Wait for the specified delay to simulate time passing
            Thread.Sleep(delayMilliseconds);

            // Add the shape to the worksheet
            addShapeAction();

            // The newly added shape is always the last one in the collection
            Shape newShape = shapes[shapes.Count - 1];

            // Record the shape with the current time
            pendingShapes.Add((newShape, DateTime.UtcNow));

            // Attempt to group shapes that have been pending longer than the window
            GroupPendingShapes(shapes);
        }

        // Groups shapes that have been pending for at least the defined window.
        // If forceGroupAll is true, groups all pending shapes regardless of their age.
        private static void GroupPendingShapes(ShapeCollection shapes, bool forceGroupAll = false)
        {
            DateTime now = DateTime.UtcNow;
            List<Shape> toGroup = new List<Shape>();

            // Select shapes that satisfy the grouping condition
            foreach (var (shape, addedAt) in pendingShapes)
            {
                // Skip shapes that are already part of a group
                if (shape.IsInGroup) continue;

                if (forceGroupAll || (now - addedAt) >= GroupingWindow)
                {
                    toGroup.Add(shape);
                }
            }

            // If we have at least two shapes, create a group
            if (toGroup.Count >= 2)
            {
                // Use the ShapeCollection.Group method as defined in the documentation
                GroupShape group = shapes.Group(toGroup.ToArray());

                // Optionally, set a name for the group for identification
                group.Name = $"AutoGroup_{DateTime.Now:yyyyMMdd_HHmmss}";

                // Remove grouped shapes from the pending list
                pendingShapes.RemoveAll(item => toGroup.Contains(item.shape));
            }
        }
    }
}
