// Title: Link a Shape to a CONCATENATE Cell and Display Combined Text – Aspose.Cells for .NET (C#)
// Description: Creates a workbook, puts "Hello" and "World" in A1/B1, uses =CONCATENATE in C1, adds a rectangle shape, links it to C1, updates the shape text, fits the shape to the content, and saves the file.
// Keywords: Aspose.Cells shape linking | C# rectangle linked cell | CONCATENATE formula display | fit shape to text Aspose | update shape value formula | Aspose.Cells .NET example
// Common Searches: Aspose.Cells link shape to cell formula | display concatenated cell value in shape C# | fit rectangle shape to text Aspose.Cells | update shape after formula change .NET | set linked cell for rectangle shape Aspose
// Developer Intent: Link a rectangle shape to a cell that contains a CONCATENATE formula so the shape automatically shows the combined text.
// Use Cases: Dynamic report headers that combine multiple cell values into a single shape. | Dashboard widgets where shapes reflect concatenated identifiers that update with source data. | Template designs that auto‑resize shapes to fit text generated by spreadsheet formulas.
// AI Prompts: Generate C# code with Aspose.Cells to link a rectangle shape to a cell using the CONCATENATE function and keep the shape text synchronized. | Show how to resize a linked shape to fit the text of its source cell in Aspose.Cells for .NET. | Explain best practices for error handling when linking shapes to formula cells in Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Creates a workbook, puts "Hello" and "World" in A1/B1, uses =CONCATENATE in C1, adds a rectangle shape, links it to C1, updates the shape text, fits the shape to the content, and saves the file.
class ShapeLinkExample
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];

            // Populate cells with sample text
            sheet.Cells["A1"].PutValue("Hello");
            sheet.Cells["B1"].PutValue("World");

            // Set CONCATENATE formula in C1 to combine A1 and B1 with a space
            sheet.Cells["C1"].Formula = "=CONCATENATE(A1,\" \",B1)";

            // Add a rectangle shape to the worksheet
            // Parameters: upper left row, upper left column, lower right row, lower right column, width, height
            int upperLeftRow = 2;          // zero‑based row index
            int upperLeftColumn = 0;       // zero‑based column index
            int lowerRightRow = 5;
            int lowerRightColumn = 3;
            int width = 100;   // shape width in points
            int height = 50;   // shape height in points

            RectangleShape rectShape = sheet.Shapes.AddRectangle(
                upperLeftRow, upperLeftColumn, lowerRightRow, lowerRightColumn, width, height);

            // Link the shape to the cell containing the CONCATENATE formula (C1)
            rectShape.SetLinkedCell("C1", true, false);

            // Update the shape so it displays the combined text from the linked cell
            rectShape.UpdateSelectedValue();

            // Adjust the shape to fit the text size
            rectShape.FitToTextSize();

            // Save the workbook to a file
            string outputPath = "ShapeLinkedToConcatenatedCell.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved to {Path.GetFullPath(outputPath)}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
