// Title: Link a Rectangle Shape to a REPT Formula Cell with Aspose.Cells for .NET (C#)
// Description: Shows how to create a workbook, place a REPT formula in cell A1, add a rectangle shape, link the shape to the formula cell so it displays the repeated character string, refresh the displayed value, and save the file as XLSX using Aspose.Cells for .NET.
// Keywords: Aspose.Cells | C# shape linking | REPT function | link shape to cell | rectangle shape | Excel shape formula | update shape value | Aspose.Cells for .NET example | dynamic shape text | Excel automation
// Common Searches: Aspose.Cells link shape to cell | C# link rectangle to REPT formula | display REPT result in shape Aspose.Cells | set linked cell for shape Aspose.Cells .NET | update shape text from formula Aspose.Cells
// Developer Intent: Create an Excel workbook where a rectangle shape shows the text generated by a REPT formula in a linked cell.
// Use Cases: Build visual dashboards that display pattern text inside shapes. | Generate printable reports where shapes automatically reflect calculated values. | Design templates that update shape captions when source formulas change. | Combine multiple linked shapes for dynamic labeling in Excel workbooks.
// AI Prompts: Write C# code to link several shapes to different REPT cells and refresh each one using Aspose.Cells. | Explain how to change the linked cell of an existing shape and force a refresh in Aspose.Cells for .NET. | Show how to format a linked shape's text (font, color) after linking it to a REPT formula. | Provide a step‑by‑step guide to link a shape to a cell, update its value, and save the workbook with Aspose.Cells.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Shows how to create a workbook, place a REPT formula in cell A1, add a rectangle shape, link the shape to the formula cell so it displays the repeated character string, refresh the displayed value, and save the file as XLSX using Aspose.Cells for .NET.
class LinkShapeToReptCell
{
    static void Main()
    {
        try
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = workbook.Worksheets[0];

            // Set a cell formula that repeats a character pattern using REPT function
            // Example: repeat the character "*" 10 times
            Cell targetCell = sheet.Cells["A1"];
            targetCell.Formula = @"=REPT(""*"",10)";

            // Add a rectangle shape to the worksheet
            // Parameters: shape type, upper left row, upper left column, top, left, height, width
            // Here we place the shape roughly over cells B2:C4
            Shape rectangle = sheet.Shapes.AddShape(
                MsoDrawingType.Rectangle, // shape type (use MsoDrawingType enum)
                1,   // upper left row (zero‑based, so row 2)
                1,   // upper left column (zero‑based, so column B)
                5,   // top offset in pixels
                5,   // left offset in pixels
                100, // height in pixels
                200  // width in pixels
            );

            // Link the shape to the cell containing the REPT formula
            // The shape will display the value of the linked cell
            rectangle.SetLinkedCell("A1", false, false);

            // Update the shape's displayed value based on the linked cell
            rectangle.UpdateSelectedValue();

            // Determine output file path
            string outputFile = "LinkedShapeRept.xlsx";
            string outputPath = Path.Combine(Directory.GetCurrentDirectory(), outputFile);

            // Save the workbook to a file
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved successfully to: {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}
