// Title: C# – Measure Excel workbook size before and after shape changes with Aspose.Cells
// Description: This C# example creates a workbook, adds a TextBox shape, captures the file size via a MemoryStream, applies FitToTextSize and appends text, saves the workbook again, and calculates the byte‑size delta. It shows how to assess the impact of shape modifications on an Excel file generated with Aspose.Cells for .NET.
// Keywords: Aspose.Cells | .NET | C# | Excel workbook size | shape modification | FitToTextSize | MemoryStream | file size comparison | size delta | GitHub example | global | US
// Common Searches: How to get Excel file size in bytes using Aspose.Cells | Workbook size before and after shape edit Aspose.Cells | Impact of FitToTextSize on Excel file size | Compare Excel file size after adding text to a shape | Measure size difference of .xlsx generated by Aspose.Cells
// Developer Intent: Calculate the byte‑size difference of an Excel workbook before and after programmatically modifying a shape.
// Use Cases: Verify that shape changes stay within storage limits for automated report generation. | Benchmark how different shape properties (e.g., FitToTextSize, added text) affect final workbook size. | Log workbook size variations when updating shapes in bulk processing pipelines.
// AI Prompts: Generate code that writes the before/after size values to a log file instead of the console. | Show how to measure size differences when multiple shapes are added or modified in the same workbook. | Explain how to use SaveOptions (e.g., compression) to reduce the size increase caused by shape modifications.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// This C# example creates a workbook, adds a TextBox shape, captures the file size via a MemoryStream, applies FitToTextSize and appends text, saves the workbook again, and calculates the byte‑size delta. It shows how to assess the impact of shape modifications on an Excel file generated with Aspose.Cells for .NET.
class WorkbookShapeSizeComparison
{
    static void Main()
    {
        // Create a new workbook (lifecycle rule: create)
        Workbook workbook = new Workbook();

        // Access the first worksheet
        Worksheet sheet = workbook.Worksheets[0];

        // Add a text box shape to the worksheet
        Shape textBox = sheet.Shapes.AddTextBox(1, 0, 1, 0, 100, 100);
        textBox.Text = "Initial text for size measurement.";

        // Save the workbook to a memory stream (lifecycle rule: save)
        using (MemoryStream beforeStream = workbook.SaveToStream())
        {
            long beforeSize = beforeStream.Length;

            // Modify the shape: fit to text size and add more content
            textBox.FitToTextSize();
            textBox.Text += " Adding more text to increase the workbook size after modification.";

            // Save the modified workbook to another memory stream
            using (MemoryStream afterStream = workbook.SaveToStream())
            {
                long afterSize = afterStream.Length;
                long sizeDifference = afterSize - beforeSize;

                // Output the size information
                Console.WriteLine($"Size before modification: {beforeSize} bytes");
                Console.WriteLine($"Size after modification:  {afterSize} bytes");
                Console.WriteLine($"Difference:               {sizeDifference} bytes");
            }
        }

        // Clean up
        workbook.Dispose();
    }
}
