// Title: Aspose.Cells for .NET – Remove 3D Formatting from Chart Series Shapes While Preserving 2D Properties
// Description: Demonstrates how to create a workbook with a 3‑D column chart, apply a top‑bevel, then iterate through all worksheets, charts, and series to detect 3‑D formatting with HasFormat3D() and clear it using ClearFormat3D(), leaving line styles, fills and other 2‑D attributes untouched. Saves the workbook before and after the cleanup.
// Keywords: Aspose.Cells clear 3D formatting | remove 3D shape properties .NET | ClearFormat3D Aspose.Cells | HasFormat3D example | chart series 3D removal | preserve 2D attributes Aspose | C# Excel 3D chart cleanup | Aspose.Cells shape properties
// Common Searches: how to clear 3d formatting from chart series Aspose.Cells | remove bevel from Excel chart using C# | Aspose.Cells preserve 2d formatting when deleting 3d effects | ClearFormat3D method example | iterate charts to reset 3d shape properties
// Developer Intent: Programmatically strip all three‑dimensional formatting from chart series shapes while keeping their two‑dimensional styling intact.
// Use Cases: Prepare Excel reports for printing or PDF export by removing 3‑D effects that may distort layout. | Standardize workbooks generated by external tools that add unwanted bevels or depth to chart series. | Automate cleanup of legacy spreadsheets before migration to newer Office versions.
// AI Prompts: Write C# code with Aspose.Cells that loops through every chart in a workbook and calls ClearFormat3D() only when HasFormat3D() returns true. | Show a before‑and‑after comparison of a 3‑D column chart where the bevel is removed but line color and fill remain unchanged. | Explain how to unit‑test that ClearFormat3D() does not affect 2‑D properties such as border style, fill pattern, or data labels.

using System;
using Aspose.Cells;
using Aspose.Cells.Charts;
using Aspose.Cells.Drawing;

// Demonstrates how to create a workbook with a 3‑D column chart, apply a top‑bevel, then iterate through all worksheets, charts, and series to detect 3‑D formatting with HasFormat3D() and clear it using ClearFormat3D(), leaving line styles, fills and other 2‑D attributes untouched. Saves the workbook before and after the cleanup.
class Remove3DFormatting
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Populate sample data for the chart
            worksheet.Cells["A1"].PutValue("Category 1");
            worksheet.Cells["A2"].PutValue("Category 2");
            worksheet.Cells["B1"].PutValue(10);
            worksheet.Cells["B2"].PutValue(20);

            // Add a 3‑D column chart
            int chartIndex = worksheet.Charts.Add(ChartType.Column3D, 5, 0, 15, 10);
            Chart chart = worksheet.Charts[chartIndex];
            chart.NSeries.Add("B1:B2", true);
            chart.NSeries.CategoryData = "A1:A2";

            // Apply some 3‑D formatting to the first series (to demonstrate the effect)
            Series series = chart.NSeries[0];
            ShapePropertyCollection shapeProperties = series.ShapeProperties;
            Format3D format3D = shapeProperties.Format3D;
            format3D.TopBevel.Type = BevelPresetType.Circle;
            format3D.TopBevel.Height = 2;
            format3D.TopBevel.Width = 5;
            // Note: The 'Depth' property is not available in this API version; omitted.

            // Save the workbook before clearing 3‑D formatting
            workbook.Save("BeforeClear3D.xlsx", SaveFormat.Xlsx);

            // --------------------------------------------------------------------
            // Remove all three‑dimensional formatting from shapes while preserving
            // two‑dimensional properties.
            // --------------------------------------------------------------------
            foreach (Worksheet ws in workbook.Worksheets)
            {
                foreach (Chart ch in ws.Charts)
                {
                    foreach (Series s in ch.NSeries)
                    {
                        ShapePropertyCollection spc = s.ShapeProperties;
                        // Clear only the 3‑D formatting if it exists
                        if (spc.HasFormat3D())
                        {
                            spc.ClearFormat3D();
                        }
                    }
                }
            }

            // Save the workbook after clearing 3‑D formatting
            workbook.Save("AfterClear3D.xlsx", SaveFormat.Xlsx);
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}
