// Title: Move the Last Shape to the Back and Save the Workbook – Aspose.Cells for .NET (C#)
// Description: Creates a new workbook, adds a rectangle, an ellipse, and a picture (or placeholder) shape, sends the most recently added shape to the back of the drawing order using ToFrontOrBack(0), and saves the file as an XLSX document.
// Keywords: Aspose.Cells C# shape ordering | ToFrontOrBack method | send shape to back Aspose.Cells | add picture shape Aspose.Cells | save workbook after reordering shapes | Excel shape layer manipulation | Aspose.Cells drawing order
// Common Searches: Aspose.Cells move last shape to back | C# send shape behind other objects in Excel | ToFrontOrBack(0) example Aspose.Cells | how to reorder shapes in Aspose.Cells worksheet | save Excel file after changing shape order
// Developer Intent: Programmatically place the most recently added shape behind all other drawings in a worksheet and then persist the workbook.
// Use Cases: Set a background image behind charts and data tables in an automated report. | Ensure watermark or logo shapes stay underneath dynamic content generated by code. | Adjust layer order of diagram elements when building Excel-based flowcharts programmatically.
// AI Prompts: Generate C# code with Aspose.Cells that adds multiple shapes, moves the last one to the back using ToFrontOrBack(0), and saves the workbook. | Explain the ToFrontOrBack method parameters and how they affect shape layering in Aspose.Cells. | Create a sample that checks for an image file, inserts it as a picture shape, sends it to the back of the drawing order, and exports the Excel file.

using System;
using System.IO;
using Aspose.Cells;
using Aspose.Cells.Drawing;

// Creates a new workbook, adds a rectangle, an ellipse, and a picture (or placeholder) shape, sends the most recently added shape to the back of the drawing order using ToFrontOrBack(0), and saves the file as an XLSX document.
class Program
{
    static void Main()
    {
        try
        {
            // Create a new workbook and get the first worksheet
            Workbook workbook = new Workbook();
            Worksheet worksheet = workbook.Worksheets[0];

            // Add a rectangle shape
            worksheet.Shapes.AddRectangle(1, 1, 100, 100, 0, 0);

            // Add an ellipse shape. Use explicit cast to avoid enum version issues.
            worksheet.Shapes.AddShape((MsoDrawingType)3, 2, 2, 0, 0, 120, 120);

            // Add a picture shape if the file exists; otherwise add a placeholder rectangle
            string picturePath = "sample.png";
            Shape lastShape;
            if (File.Exists(picturePath))
            {
                using (FileStream fs = new FileStream(picturePath, FileMode.Open, FileAccess.Read))
                {
                    lastShape = worksheet.Shapes.AddPicture(3, 3, 0, 0, fs);
                }
            }
            else
            {
                lastShape = worksheet.Shapes.AddRectangle(3, 3, 100, 100, 0, 0);
            }

            // Send the last shape to the back of the drawing order (0 = back)
            lastShape.ToFrontOrBack(0);

            // Save the workbook
            string outputPath = "LastShapeToBack.xlsx";
            workbook.Save(outputPath);
            Console.WriteLine($"Workbook saved to {outputPath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
